### ISSUE TITLE
Vampires spawning in wrong biomes. 

### ISSUE THREAD

**Issue by slidingmike** [TeamLapen/Vampirism#100]
I'm trying to find out if it's possible to get a config option for vampires to not spawn in certain biomes. I.E. Prevent spawning in Mushroom Biomes.

**Comment by maxanier** [comment]
No there isn't a option for that currently. Why do you wan't to configure that?

I can implement that, but it will take some time (low priority).

**Comment by slidingmike** [comment]
Primarily to mimic the vanilla hostile mob spawning mechanics. Players in mushroom biomes aren't expecting hostile mobs, however vampires spawn. I'd like the ability to keep that equal.

**Comment by maxanier** [comment]
Ok, that's something different. I tried to make vampires spawn in the same biomes as Zombies do. 
If you can confirm that there are vampires spawning in the mushroom biome, I will investigate that

**Comment by slidingmike** [comment]
Can confirm.

http://grab.by/Ri5w

**Comment by maxanier** [comment]
Thx.
Is fixed in the next version.
If you are still interested in configurable spawn biomes, please create a new issue and I will implement it at some point
