### ISSUE TITLE
Balance the mod for vampires

### ISSUE THREAD

**Issue by itzhak-glitch** [TeamLapen/Vampirism#1004]
The mod is just unbalanced for vampires (examples: attack speed, attack damage, general strength and hunters 20 advantages on them) and I hate it staying like that and even getting more unbalanced, especially in recent updates so please make vampires powerful just as much or even stronger because the mod is more based on vampires then hunters.

1. i want to suggest that please don't make hunters stronger in updates
2. i want you to make default config more balanced for vampires
3. just fix the general strength of both vampire and hunters and make being a vampire fair for all of the vampires and dracula fans

**Comment by maxanier** [comment]
Thank you for your feedback.

However,
a) this is very generic feedback without anything specific to it that could be implemented
b) this is very exaggerated, especially in recent updates tides have turned a bit
A github issue only works for more concise suggestions, for general feedback please stick to Discord/CurseForge where I can get a more general atmospheric picture

Also why did you choose "**Don't use**, unless suggest something unrelated to mod functionality (like mod documentation or codestyle) " over "Suggest an idea for this mod " when creating this issue? :D
