### ISSUE TITLE
[Feature]: Allow removing accessories without replacing

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#1005]
### What?

After seeing it in action for some time, I think we should implement a way to remove accessories without equipping a new one. Maybe by just right clicking on the slot or something like that

### Mod experience

1. When accidentally equipping one you do not like after all, you currently have to find a replacement before you can get rid off it
2. For debugging it makes things easier

**Comment by Cheaterpaul** [comment]
closed by 21a053bd
