### ISSUE TITLE
[Bug]: Our server crashes whenever someone respawns and the cause is vampirism.

### ISSUE THREAD

**Issue by Tadryth** [TeamLapen/Vampirism#1007]
### Minecraft Version

1.16.x

### Forge Version

36.2.2

### Vampirism Version

1.8.0-1.8.3

### Singleplayer/Multiplayer

Server

### What happened?

Everytime we use the vampirism mod in our server and someone dies and respawns the server always dies. It can be instantly or sometimes a few seconds after they respawn. We have determined that it is indeed vampirism because we removed the mod and died respawned and it worked normally then we tried it again with vampirism the server crashes again.. We have tried all the versions for 1.16.5 

### Relevant log output

```shell
https://paste.ee/p/lPkTA
```

### Reproduce steps

1. Enter the server
2. Someone dies either naturally or on purpose
3. they press respawn
4. once they respawn the server crashes.

**Comment by MarkeR2005** [comment]
I have the same
Don't know how to fix

**Comment by maxanier** [comment]
Thank you for reporting. Can you please provide the crash report file. I suspect another mod is triggering (and maybe even causing) this issue and the crash report file contains a list of all active mods.
Also make sure there are no other errors printed to the log when respawning

**Comment by maxanier** [comment]
The latest 1.8.4 version includes some changes that may reduce the impact issue, but the root cause will likely persist, because it is caused by another mod.
Please reopen if you can provide a crashreport
