### ISSUE TITLE
[Feature] Make it so that the vamprires/werevolves can join the enemy factions.

### ISSUE THREAD

**Issue by DaRandomAcc** [TeamLapen/Vampirism#1015]
### What?

Make an option to betray your own faction (for example Vampires) and join the enemy faction as a hunter while keeping your powers. Upon betraying your faction they will start to attack you. This could be changed in the config and would be disabled by default.

### Mod experience

Positive

**Comment by maxanier** [comment]
Sorry, but this is too complicated/time consuming to implement. Especially for something that would be disabled by default
