### ISSUE TITLE
[Bug]: Vampire book is equipped as leggings

### ISSUE THREAD

**Issue by davidCMs** [TeamLapen/Vampirism#1019]
### Minecraft Version

1.16.x

### Forge Version

36.2.8

### Vampirism Version

1.8.1

### Singleplayer/Multiplayer

Singleplayer

### What happened?

i get a book in my laggings sloth

### Reproduce steps

idk it just hapens

### Other relevant mods

![Posnetek zaslona 2021-12-01 235301](https://user-images.githubusercontent.com/93453000/144327219-9edabfd0-850d-436e-ac5b-e17b4a205174.png)

(im not an ingish so if there is any spelling mestakes sorry)

**Comment by Cheaterpaul** [comment]
It is known that this could happen with the helmet slot but never with other slots.

Please update to Vampirism 1.8.4 (https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire/files/3536399)
and report back if the book ever appears in the armor slots again.
