### ISSUE TITLE
[Feature]: Create factions with datapacks?

### ISSUE THREAD

**Issue by davidCMs** [TeamLapen/Vampirism#1020]
### What?

can you maket so you can write costum factions what data paks

**Comment by Cheaterpaul** [comment]
That is hard to accomplish and would require a nearly total rewrite/reconstruction of the faction system with everything that is attached to it.

This could be considered if the faction system is split into a separate mod or for a 2.0 version.
But i am not sure if this is worth the effort in the foreseeable future.

**Comment by maxanier** [comment]
This is way to complicated and would rarely be used, sorry
