### ISSUE TITLE
[Bug]: Dupe through the bat... Aquaculture 2 

### ISSUE THREAD

**Issue by XionioXMaster** [TeamLapen/Vampirism#1021]
### Minecraft Version

1.16.x

### Forge Version

 36.2.18

### Vampirism Version

1.8.4

### Singleplayer/Multiplayer

Server

### What happened?

If you install a chest caught from the Aquaculture mod, namely the one that has not yet been opened by the player (it has the signs ???????), you can dup things by installing it through the bat!

![image](https://user-images.githubusercontent.com/86433158/144468244-d2270af0-bf14-4cc2-bf23-ce33b6c8d598.png)
![image](https://user-images.githubusercontent.com/86433158/144468266-29ad5af6-67c1-49f4-ba4d-122f227f7725.png)

### Relevant log output

```shell
The log does not record anything
```

### Reproduce steps

![image](https://user-images.githubusercontent.com/86433158/144468244-d2270af0-bf14-4cc2-bf23-ce33b6c8d598.png)
![image](https://user-images.githubusercontent.com/86433158/144468266-29ad5af6-67c1-49f4-ba4d-122f227f7725.png)
![image](https://user-images.githubusercontent.com/86433158/144468439-ab630631-d541-4527-83f3-28d57c77996a.png)
the creative chest will not have any pre-prepared items, so you just need to fish it out!

### Other relevant mods

Aquculture

**Comment by DonorKrovi** [comment]
ok, this work.... 
l m 
a o

**Comment by maxanier** [comment]
So when you right click to place the chest while in bat mode, the content will drop, but the (full) chest remains in your inventory?

**Comment by XionioXMaster** [comment]
> So when you right click to place the chest while in bat mode, the content will drop, but the (full) chest remains in your inventory?

The player will not put the chest, and things simply fall out of nowhere, the player's chest also remains in the inventory

but the player installs chest

**Comment by maxanier** [comment]
This is related to a Forge issue https://github.com/MinecraftForge/MinecraftForge/issues/7609, but I implemented a workaround.
Should be fixed with the next release
