### ISSUE TITLE
[Bug]: Barons not spawning/cant find spawn rates in config 

### ISSUE THREAD

**Issue by itzmelauryn** [TeamLapen/Vampirism#1023]
### Minecraft Version

1.12.x

### Forge Version

14.23.5

### Vampirism Version

1.12.2-1.6.2

### Modpack

https://www.technicpack.net/modpack/lullaby-of-the-forest.1679841

### Singleplayer/Multiplayer

Server

### What happened?

This is probably an issue that I am having on my end, but I have been looking for a vampire baron for hours in a vampire forest. I then went looking through the config and could not find where the spawn rates are. I think there is a mod clashing but I can’t find anything about an issue like this on the internet.

### Reproduce steps

1. Load in server 2. look in vampire forest

**Comment by maxanier** [comment]
Sorry, but we do not support 1.12 anymore.
It works pretty well, but sometimes other mods (or especially server plugins) cause trouble.
