### ISSUE TITLE
[Feature]: Aging system

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#1027]
### What?

Idea by krab:

Vampires will eventually get stronger abilities with age. This would be calculated with the days statistic, with higher counts being 10 days = to 720 hours.
This age would increase with the day and grant many benefits but also weaknesses, death would reset a vampires age. 

Vampires would age but never die of it, to counteract their abilities they will get; should they die their age will be reset back to its original 0. 
They would get small additions as well as large buffs/nerfs that are gained. An ancient vampire would be perfectly capable of slaughtering people but it would have massive drawbacks, it take a long time to reach this level and would be applicable to being reset if the ancient got caught out. 
Things like sunlight, water, garlic, fire, etc would be much more deadly/intrusive. 

Vampire strengths:
(1-2): minor buff to all main effects, higher damage, speed, jump, etc.
(3-4): Continuous buff, slight extra knock back
(5-6): Continuous buff, knock back increase, sunlight does 2 more damage, fire takes longer to leave.
(7) (This would be considered an older vampire, not ancient but still old): Your speed/jump has hit its limit. Your attack damage is increased by 2 damage, knock back increased, sunlight does 2 more damage, 
(9): Max blood increased, regen becomes passive, sunlight does 2 more damage, natural armor increased slightly, health increases, water now gives slowness, garlic lasts much longer
(9): Knockback increased, intense slowness in water (negated with water ability), fire drains blood.
(10): Strength increased by 2, time in sun without taking damage is decreased, increase in health, armor, blood, at this point the vampire can only be slain by the use of stakes, being in fire, sunlight; Either they quickly revive from DBNO and have no neonatal or they simply don't go down and just don't die without the use of said items. 

Potentially only apply for max level lords
Gamerule to disable

### Mod experience

Why?
The late game in vampirism is really really plain. You reach max level then there is just nothing more to do, with this update I feel it would give hunters and vampires much more to do. Vampires would have to worry about surviving and hunters would have to be busy actively hunting down every vampire they could find, lest they become old and powerful. It would also mean hunters would have to be smart with their hunting, Young vampires would be easy, but an ancient would take a group of people to carefully plan the attack. I also feel it would help with adding a fun twist to the mod. I feel to balance this out it could be a config that is automatically off, so it would be a choice.

**Comment by maxanier** [comment]
In general I like the idea. 
Once again there is the issue of balancing again. How to make old vampires feel stronger without completely demolishing any hunter (considering the suggested x2 strength increase)

It may be reasonable to only activate this system after reaching level 14

**Comment by Elder-Yaga** [comment]
I love this idea from start to finish. And I agree with you that this feature is best given to the lords. Also, I think you can somehow connect this idea and the peculiarity of the vampire emperor. Perhaps the emperor can become truly ancient (by finding somewhere, the blood of the first vampires and using it in a ritual). Sorry if I'm getting ahead of myself, but I really like these two ideas.

**Comment by jex290** [comment]
A age system would be a amazing addition to vampirism!

**Comment by FrostedOver** [comment]
Would be really nice, especially since hunters can so easily 1 or 2 shot vampires even with armor, not to mention hunters also having such powerful armor in their arsenal. Really interesting idea! Sounds super fun.

**Comment by Agentmcchicken** [comment]
I also really like the idea but maybe you could increase the highest buff increases per lord level. Like Baron 1-2 day buff, Viscount 3-4 day buff all the way up to prince.

**Comment by lusifer173** [comment]
wanna add something, I fairly sure my math is off. The ingame statistic is measured by actual playtime, which 1 day is 24 hours so it'd really be 240 hours. Additionally I agree that it should be for max levels or lord, plus yeah maybe hunters shouldn't reset -krab

**Comment by NoOneX45** [comment]
it is prefect

**Comment by Desanguin8ed** [comment]
What if the age dropped by one value every time a Totem of Undying activates?

**Comment by Cheaterpaul** [comment]
This was adapted as addon mod by TheDrOfDoctoring

https://www.curseforge.com/minecraft/mc-mods/vampiric-ageing-a-vampirism-addon
https://github.com/TheDrOfDoctoring/Vampiric-Ageing
