### ISSUE TITLE
Full Blood Bar and saturation does not regenerate health

### ISSUE THREAD

**Issue by tech-boy101** [TeamLapen/Vampirism#103]
hi once a again sorry not use the own one but ye the things is wind eat normal o lee like steak you get 8 or 4 points in to your saturation bar and that saturation is use to heal you very fast but wind you be come a vampire you can get saturation points no more so i like you to fix this by get some saturation points wind you feed on things like pig or humans or make that heal skill to give you max points but take a hunger away like x for some a mount points  way if understand what i mend if you do not msg me piz

**Comment by maxanier** [comment]
Ok I might understand you know but to clarify:

In Minecraft there are two different things points related to food:
The foodbar (displayed on right) which heals the player if full or damages the player if empty. (Replaced by the blood bar)
Saturations points (normally not visible, only added in the background) which are used up before the foodbar is being used.

Are you referring to the first or the second bar? And if you are referring to the second one: do you use another mod to display that?

**Comment by tech-boy101** [comment]
welll i do not use a mof to let me see the bar but normal minecraft use it now for faster healing so i wann to ask if you make you where you can get the saturations points becruse of 1.9 add a need heal thing that wind your low on hp or just miss some hp and you have saturation points  it well use the satutation points to heal you if still dont understand try playing normal minecraft and eat some meat or food like bread wind low on hp then try it wind your a vampire use your mod

**Comment by maxanier** [comment]
Ok, I get it now. That will be implemented/fixed in the next version
