### ISSUE TITLE
[Bug]: Can't respawn 

### ISSUE THREAD

**Issue by Nickmines** [TeamLapen/Vampirism#1033]
### Minecraft Version

1.17.x

### Forge Version

37.0.83

### Vampirism Version

1.17.1

### Modpack

only the mod it's self

### Singleplayer/Multiplayer

Singleplayer

### What happened?

I was in bat form in the nether, fighting a ghast when I got hit and died and now I can't respawn

### Reproduce steps

1. get in a single player world 
2. become level 4 vampire 
3. go to nether 
4. become a bat 
5. get killed by ghast 

### Other relevant mods

no other mods

**Comment by maxanier** [comment]
What exact Vampirism version are you using? I cannot reproduce this with 1.8.4-beta.1
