### ISSUE TITLE
[Bug]: Vampirism causing heavy tick lag, supposedly when unloading chunks

### ISSUE THREAD

**Issue by mindforger** [TeamLapen/Vampirism#1034]
### Minecraft Version

1.18.x

### Forge Version

39.0.14

### Vampirism Version

Vampirism-1.18.1-1.8.0-alpha+20220106-2313

### Modpack

Custom

### Singleplayer/Multiplayer

Server

### What happened?

When moving around the server it spontaneoulsy decides to drop the tickrate and spark profiling it leads to something related to unloading chunks connected with vampirism

PS: create mod had the same issue with the 1.0.4a version and fixed it in 1.0.4b(that is why we are updating), maybe there is some clue to find ? :)

### Relevant log output

```shell
https://spark.lucko.me/dHN4kc5xum
https://pastebin.com/dULuUGny
```

**Comment by mindforger** [comment]
to adhere, it also (exactly like the create mod) create a global lighting bug at the whole chunk where the village stone was located at a border of a chunk, so there seems to be a similar issue

when you port away and back to te location of the village stone the whole chunk will turn dark, when the village stione is at the border of a chunk

edit: scratch that, it was the WAYSTONE not the village totem that caused the lighing issue, had a communication issue there

**Comment by JulJuls** [comment]
Our modded server may have a similar crash problem caused by tickrate.
I will link it here, if it relevant. Otherwise I'll open a separate thread.
### **Minecraft Version**
1.18.x

### **Forge Version**
39.0.19

### **Vampirism Version**
Vampirism-1.18.1-1.8.0-alpha+20220106-2313

`
https://pastebin.com/8wZ6MHTQ
`

**Comment by maxanier** [comment]
Thank you for reporting. While I am unable to properly recreate this issue, I have an assumption what might be causing this based on the logs you provided (and the Create reference).
I will try to implement a workaround.
How severe is this tick lack?
Does the server freeze for a few ms or rather a few seconds. And does this occur frequently or only occasionally?

**Comment by maxanier** [comment]
Please try the new 1.8.0-beta.2 and let me know if the issue persists

**Comment by mindforger** [comment]
I will try tuesday when i get back on my PC. It is pure tick lag, all entities only move delayed and block updates are delayed
