### ISSUE TITLE
[Bug]: Vampire forest not generating with Biomes O Plenty

### ISSUE THREAD

**Issue by CaptainCortisol** [TeamLapen/Vampirism#1035]
### Minecraft Version

1.18.x

### Forge Version

39.0.9

### Vampirism Version

1.8.0 - alpha

### Singleplayer/Multiplayer

Both

### What happened?

The vampire forest does not generate when using Biomes O Plenty. I've explored and could not find it and also I've tried using /locatebiome

### Reproduce steps

1. Download latest version of Biomes O Plenty and TerraBlender
2. Download Vampirism 1.8.0 - Alpha
3. Run a new world and type /locatebiome vampirism:vampire_forest and press enter
4. MC cannot find this biome

**Comment by maxanier** [comment]
Fixed with f68bd33a3c5738e9e0cf51b8217712869d0b1071

The latest alpha should work with BOP

**Comment by CaptainCortisol** [comment]
Awesome thank you
