### ISSUE TITLE
[Feature]: Vampires Need Umbrellas, doesn't make perfect sense. 

### ISSUE THREAD

**Issue by SerketTheScorpion** [TeamLapen/Vampirism#1040]
### What?

In Vampirism, while playing as a Vampire, the sun hurts you. This of course can be negated by using an umbrella from the Vampires Need Umbrellas addon. Something else that negatively affects vampires, is water. When you're in water you gain Weakness, and when it's raining you gain Weakness as well. 

What I would like to see, is for the Umbrellas from Vampires Need Umbrellas, to actually do their job. As it currently stands (I'm playing the 1.16.5 version of the mods) the Umbrellas do not stop Rain from giving you weakness, which makes absolutely no sense. I mean come on, it's an umbrella, they're made to stop you from getting wet when it rains. 

### Mod experience

This change would make the Umbrellas more powerful, and thus makes vampirism less of a detriment to the player. For PvP, this could be a genuine balance issue. For PvE, this buff to Umbrellas makes perfect real-world sense.

**Comment by maxanier** [comment]
Maybe request this at the repo of the respective mod then: https://github.com/focamacho/VampiresNeedUmbrellas
By the way, in future version, vampire will only be affected by flowing water blocks.
