### ISSUE TITLE
[Feature]: Curing entities

### ISSUE THREAD

**Issue by SomeKristi** [TeamLapen/Vampirism#1043]
### What?

Could you please add an item that reverts entities back to a non vampire state, something like the conversion of villagers from zombies. 
Villagers could give a discount. It would be like a cross that needs to be filled with ultimate holy water to work.
It would have 8 durability and once its used up at 0 durability you could fill it up in the crafting table 

### Mod experience

It would affect the mod in a positive way. Because it would alow trading with villagers or curing mobs to use them as sources of blood

**Comment by maxanier** [comment]
Already possible in the more recent versions:
https://github.com/TeamLapen/Vampirism/wiki/Vampiric-Creatures#curing-creatures

**Comment by SomeKristi** [comment]
Ah i didnt know thank you.

**Comment by SomeKristi** [comment]
but can i ask what block creates a vampire master villager

**Comment by maxanier** [comment]
I'm not sure what a vampire master villager is...
If you want to have a villager with vampire profession, you need a vampire controlled village. The totem acts as a work station for the villager
