### ISSUE TITLE
Sound issue with doors

### ISSUE THREAD

**Issue by leggm97** [TeamLapen/Vampirism#105]
Whenever you open or close a door both the door and the chest sounds go off. (Tested this by spamming the door open and close). Just a minor issue but still one none the less.

**Comment by maxanier** [comment]
Did you notice that on the Official Server?
It happens there, but I can't reproduce it if not on the server. 
I think it is a bug not related to Vampirism

**Comment by leggm97** [comment]
Yeah I noticed it on the Official Server. Havn't tried it on a SP world. Going to try it now.

**Comment by maxanier** [comment]
Pretty sure that is not a bug in Vampirism, so closing this issue
