### ISSUE TITLE
[Modcompat]: Terralith Biome Generator

### ISSUE THREAD

**Issue by Jadan1213** [TeamLapen/Vampirism#1052]
### Minecraft Version

1.18.x

### Forge Version

39.0.88

### Vampirism Version

1.8.0-beta3

### Incompatible mod

Terralith_v2.0.12

### Singleplayer/Multiplayer

Both

### What happened?

Vampire forest biomes not generating

### Reproduce steps

Load world.

/locatebiome vampirism:vampire_forest

no biomes found within reasonable distance. Process repeated after teleporting to much further coordinates several times over, with still no biomes found..

**Comment by maxanier** [comment]
Starting with 1.18.2 (not yet released), compatibility with Terralith requires Terrablender to be installed. Then, the vampire forest should generate
