### ISSUE TITLE
[Modcompat]: Can't suck blood from MCA villager

### ISSUE THREAD

**Issue by aybarsckck** [TeamLapen/Vampirism#1056]
### Minecraft Version

1.18.x

### Forge Version

39.1.2

### Vampirism Version

1.8.0 beta 3

### Incompatible mod

MCA 7.1.0 forge

### Singleplayer/Multiplayer

Both

### What happened?

I can't suck blood from mca villagers

### Reproduce steps

1. log in to server 
2. become vampire

**Comment by Cheaterpaul** [comment]
fixed by eee4fc77

will be fixed in the next version
