### ISSUE TITLE
Possible mod incompatibility

### ISSUE THREAD

**Issue by RacerDelux** [TeamLapen/Vampirism#106]
Have a rather odd crash when using Vampirism with LLibrary.
http://pastebin.com/w6JwmqYL
I have been talking to iLexiconn (the author of LLibrary) and he is not sure if it is really a mod compat or issue with forge. Thought I would report it here either way.

LLibrary: http://minecraft.curseforge.com/projects/llibrary/files

Running forge 12.18.1.2010 on minecraft 1.10.2

**Comment by maxanier** [comment]
I think it is a issue on LLibrary side. I've created an issue on their repository

**Comment by RacerDelux** [comment]
Yep, he sees the issue. Thanks!
