### ISSUE TITLE
[Bug]: Terrain generation

### ISSUE THREAD

**Issue by Daihok41** [TeamLapen/Vampirism#1060]
### Minecraft Version

1.18.x

### Forge Version

39.1.2

### Vampirism Version

Vampirism-1.18.1-1.8.0

### Singleplayer/Multiplayer

Singleplayer

### What happened?

For some reason get alot of wierd terrain generation with this version. It generates alot of beach so much that it looks like huge desert. Not sure if this is a conflict with another mod like Terrablender or not. It also generates alot of land that is ocean biomes.

**Comment by Daihok41** [comment]
I have been doin alot of testing with this I do beleive it to be problem with terrablender. It takes alot of effort to find the terrain thats gerenreating wrong but it is there and usually when you find it its all clumped together. Problem is need Terrablender for BOP or BYG. Will do more testing though to make sure

**Comment by maxanier** [comment]
So far I haven't noticed this with just Vampirism. I'm also not sure how Vampirism would affect beach generation, but world generation in MC is always mysterious... so I cannot foreclose that.
With 1.18.2  I am still working on world gen anyway, so maybe I can find/fix this issue.

**Comment by maxanier** [comment]
Please report if this should occur again with 1.18.2
