### ISSUE TITLE
[Modcompat]: Cant fly as a bat with Divine RPG

### ISSUE THREAD

**Issue by mac10rp** [TeamLapen/Vampirism#1062]
### Minecraft Version

1.16.x

### Forge Version

36.2.31

### Vampirism Version

1.8.6

### Incompatible mod

divinerpg 1.8.8

### Singleplayer/Multiplayer

Singleplayer

### What happened?

Unable to fly as a bat

### Reproduce steps

1. Load up Divine Rpg Mod & Vampirism Mod
2. Load up a Single Player World
3. Become a Vampire
4. Unlock bat skills
5. Become a bat
6. Not being able to fly

**Comment by maxanier** [comment]
Thank you for reporting. This appears to be an issue in the DivineRPG mod. They constantly disable flying as long as the angelic armor is not equipped. There is nothing we can do about  this unfortunately.
Related issue: https://github.com/DivineRPG/DivineRPG/issues/472 (and duplicate https://github.com/DivineRPG/DivineRPG/issues/478)
Related code: https://github.com/DivineRPG/DivineRPG/blob/1c3ef733340b93027db2415f7530c994b0bfc6af/src/main/java/divinerpg/events/ArmorAbilitiesEvent.java#L276-L286

**Comment by Locomenmod** [comment]
Fixed in https://github.com/DivineRPG/DivineRPG/commit/22e40594f57461efffc3a20003ca3547538bf6c7
