### ISSUE TITLE
[Bug]: Vampire mobs still spawn at light levels up to 8 in Minecraft 1.18+

### ISSUE THREAD

**Issue by haleyjd** [TeamLapen/Vampirism#1068]
### Minecraft Version

1.18.x

### Forge Version

39.1.2

### Vampirism Version

1.8.0

### Modpack

https://www.curseforge.com/minecraft/modpacks/the-new-frontier-enhanced/files/3698837

### Singleplayer/Multiplayer

Singleplayer

### What happened?

I have seen vampires spawn in front of me as soon as the sky light level is less than 10 and light level is less than 8, which seems to correspond with two different checks that can be found in [this source file](https://github.com/TeamLapen/Vampirism/blob/136864d5ca2ee7e085758735406c468626541d61/src/main/java/de/teamlapen/vampirism/entity/VampirismEntity.java#L249) which check for a random number less than or equal to 8. 

In Minecraft 1.18, hostile mob spawning was redefined to only occur with overworld mobs at light level 0. Maybe this was left as-is in this mod as a conscious balance choice; however, every other important mod has moved on to being designed with a light level of 0 restriction in mind. In particular this is important for MineColonies (also in the TFE modpack I am playing, and the main thing I was interested in when starting it) which has prefabs that only instruct its builder to light areas to at least level 1 or higher (and in a few cases he misses spots, which I already check for - using Light Overlay, which by default assumes level 1 is the safety limit as well). 

This also re-imposes harsh limitations on aesthetic use of lighting in builds; I first noticed this when I was attacked unexpectedly - and infected no less - inside my own house, where I carefully built a "spooky" enchanting table room with a maximum light level of 3. In short, I have no desire to return to a restriction of 8 or higher for my builds.

This is clearly problematic. I feel like if this is not changed unconditionally to zero to match vanilla mechanics and other mods for 1.18, then it should at least be exposed as a configuration option to give the choice to the player.

### Reproduce steps

1. Construct any area with light levels below 8 which are otherwise safe and unspawnable
2. Get attacked from behind and turned into a vampire in your own basement.
3. You are now required to relight all your builds from scratch (with resulting pre-1.18 torch spam) if you intend your areas, pets, and colonists to be safe.

**Comment by maxanier** [comment]
Thank you for your detailed report. I was not aware of this change in Vanilla.
I adjust the spawning behavior to that (while not touching sundamage related thresholds)
