### ISSUE TITLE
[Modcompat]: 

### ISSUE THREAD

**Issue by LRBarbieri** [TeamLapen/Vampirism#1074]
### Minecraft Version

1.12.x

### Forge Version

.

### Vampirism Version

1.6.2

### Incompatible mod

Custom Mob Spawner 3.11.5

### Singleplayer/Multiplayer

Both

### What happened?

No vampires spawn in my world, no matter the biome. I think it's an issue with the Custom Mob Spawner, which is a requirement for Mo Creatures, but I don't know how to fix it.

### Reproduce steps

Mod list: 
AppleSkin-mc1.12-1.0.14.jar
Bookshelf-1.12.2-2.3.557.jar
CodeChickenLib-1.12.2-3.2.3.358-universal.jar
Currency-1.12.0-1.3.11.jar
CustomMobSpawner-3.11.5.jar
DrZharks-MoCreatures-Mod-12.0.5.jar
EnchantingPlus-1.12.2-5.0.176.jar
EpicFightMod-1.12.2-2.2.8.jar
Guide-API-1.12-2.1.8-63.jar
Hwyla-1.8.26-B41_1.12.2.jar
InventoryTweaks-1.63.jar
ironchest-1.12.2-7.0.72.847.jar
jei_1.12.2-4.16.1.302.jar
journeymap-1.12.2-5.7.1.jar
JustEnoughResources-1.12.2-0.9.2.60.jar
Mantle-1.12-1.3.3.55.jar
MCA-1.12.2-6.1.0-sources.jar
MCA-1.12.2-6.1.0-universal.jar
MouseTweaks-2.10-mc1.12.2.jar
Neat+1.4-17.jar
TConstruct-1.12.2-2.13.0.183.jar
tektopia-1.1.0.jar
TravellersBackpack-1.12.2-1.0.27.jar
twilightforest-1.12.2-3.11.1021-universal.jar
VampiresNeedUmbrellas-1.12.2-1.5.jar
Vampirism-1.12.2-1.6.2.jar
VampirismIntegrations-1.12.2-1.3.0.jar

**Comment by Cheaterpaul** [comment]
copy your world and remove Mo Creatures and the Custom Mob Spawner and see if that solves the issue.

And if there is a compatibility issue this will probably not be fixed as 1.12 is no longer supported

**Comment by maxanier** [comment]
https://github.com/TeamLapen/Vampirism/wiki/Troubleshooting#custom-mob-spawner--mos-creatures-112

https://github.com/TeamLapen/Vampirism/issues/301
