### ISSUE TITLE
[Bug]: No altar pillars

### ISSUE THREAD

**Issue by SpecialSock** [TeamLapen/Vampirism#1078]
### Minecraft Version

1.12.x

### Forge Version

0.195.2.1

### Vampirism Version

1.7.10

### Modpack

https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire

### Singleplayer/Multiplayer

Server

### What happened?

alright so basically my friend started a server all is well, i saw that vampires were a thing. became one but there a no altar pillars at all. i search for them nothings there. its as if they dont exsist. kinda annoying cause i cant go over level 4 vampire now. so ive been tryna find a solution. ( also at the top of this report im not sure what version i was playin in so i just chose 1.12)
im having similar problem with blood stained wool were the needle doesnt want to prick me. that may just be a problem with the witchery mod though.

### Relevant log output

```shell
.
```

### Reproduce steps

1. basically just be in the game

### Other relevant mods

.

**Comment by lunofe** [comment]
You definitely mixed up something with the versions. There is no Vampirism 1.7.10 for Minecraft 1.12. Vampirism 1.7.10 has been released for Minecraft 1.16.4. Do you perhaps mean you're playing Minecraft 1.7.10 with an unknown version of Vampirism?

<details>
    <summary>Click here to see the easiest way to figure out the versions</summary>
    <img src="https://user-images.githubusercontent.com/42828197/167266797-b6a0b799-16d2-4c63-9e6a-5ef83294b7ef.png">
    <br><br>
    <img src="https://user-images.githubusercontent.com/42828197/167266824-d0a2e998-db4e-467e-ac8e-1c2918844846.png">
</details>

**Comment by maxanier** [comment]
If you are using a very old version, chances are you do not have to place altar pillars and fill them with blocks. Instead you simply place the filler blocks themselves. Checkout the Wiki, it should still contain information about MC 1.7.10
