### ISSUE TITLE
Forest of Vampires won't spawn Vampires and Barons and I haven't found the reason

### ISSUE THREAD

**Issue by Voxyo** [TeamLapen/Vampirism#1079]
### Minecraft Version

1.16.x

### Forge Version

36.2.34

### Vampirism Version

1.8.8

### Singleplayer/Multiplayer

Singleplayer

### What happened?

Well, from the start I started my world in none of the vampire forests, barons appeared let alone normal vampires, and I have no idea why.

### Relevant log output

```shell
i also download vampirism integrations and vampires needs umbrella
```

### Reproduce steps

Create a world find a forest and you wont see vampires and barons

### Other relevant mods

here is the list of mods i used, please help me i dont know what as wrong

Additional Enchants
Adorn
Alex's Mobs
Aquaculture 2
Artifacts 
Atum 2: Return to the Sands
AutoRegLib
Back Tools
BetterEnd (Forge)
Biomes O' Plenty
Blood Magic
Bountiful
BrassAmber BattleTowers
Brooms
Carrots Library
Carry On
Chicken Chunks 1.8.+
Chisel
Citadel 
Clumps
CodeChicken Lib 1.8.+
Collective
Colossal Chests
ConnectedTexturesMod
Cosmetic Armor Reworked
Create
Curio of Undying 
Curios API
Cyclops Core
Decorative Blocks
Desolation
Dungeon Crawl
Dungeons Mobs
Dungeons Mod
Dungeons Plus
Dynamic Surroundings
Dynamic Trees
Dynamic Trees - Atum 2
Dynamic Trees - Biomes O' Plenty
Dynamic Trees - Quark
Dynamic Trees - Vampirism
Dynamic Trees + 
Eidolon
ExpandAbility
Extended Caves
FastFurnace
Fish's Undead Rising
Flywheel
Fps Reducer
GeckoLib
Goblin Traders
Goblins & Dungeons
Guard Villagers
Guide-API Village and Pillage
Hole Filler Mod
Ice and Fire: Dragons
iChunUtil 
Inspirations
Inventory Pets
Item Zoom
Jade 🔍
Just Enough Items (JEI)
Kobolds!
Kotlin for forge
Macaw Bridges
Macaw Doors
Macaw Fences and Walls
Macaw Trapdoors
Macaw Windows
Macaw's Lights and Lamps
Mantle
Mo' Structures 
More Villagers
Morpheus
Mowzie's Mobs
MrCrayfish's Furniture Mod
Mutant Beasts
Mutant More
Mystical World
Nature's Compass
ObserverLib
Occultism
OpenBlocks Elevator
OptiForge
Pandoras Creatures
Patchouli
Placebo
Quark
Rats
Relics
Repurposed Structures
Selene Lib 
Serene Seasons
Shutup Experimental Settings!
Simple Storage Network
Small Ships
Sophisticated Backpacks
Spartan Shields
Spartan Weaponry
Spartan Weaponry: Ice and Fire 
Spartan Weaponry: Twilight Forest 
Spice of Life: Carrot Edition
Structure Gel API
Subterranean Wilderness
Supplementaries
The Conjurer 
The Twilight Forest
ToroHealth Damage Indicators
TrashSlot 
UnionLib
Valhelsia Core
Valhelsia Structures
Vampires Need Umbrellas
Vampirism - Become a vampire!
Vampirism Integrations
Village Spawn Point
Villager Names
Waystones
Werewolves - Become a Beast!
When Dungeons Arise - Forge!
Wyrmroost
Xaero's Minimap
YUNG's API 
YUNG's Better Caves
YUNG's Better Dungeons
YUNG's Better Mineshafts
YUNG's Better Strongholds 
YUNG's Extras

**Comment by DragonInsight** [comment]
i can confirm this as i have not seen a single vampire or baron spawn either.

**Comment by itsmagu** [comment]
I have the same problem in 1.19.2.
Using /locate will not print a result
