### ISSUE TITLE
Vampire player max health is set to normal on respawn

### ISSUE THREAD

**Issue by tonimark** [TeamLapen/Vampirism#108]
in original multiplayer server when i died as vampire i losting 2.5hearts and return to defeult 10 hearts
but originaly you have 12.5 hearts in level 1, plz fix that

**Comment by maxanier** [comment]
Did the health bar only display 10 hearts or were only 10 out of 12.5 restored?

**Comment by maxanier** [comment]
This is an issue with SpongeForge because that is doing some strange stuff with player respawns. See issue [here](https://github.com/SpongePowered/SpongeForge/issues/736).
But I will implement a workaround for now

**Comment by maxanier** [comment]
Workaround implemented in 33b7f93e033e80dead7d9634df3d01d4f6bebe9f
