### ISSUE TITLE
[Feature]: /vampirism-test skill enableall

### ISSUE THREAD

**Issue by lunofe** [TeamLapen/Vampirism#1081]
### What?

When testing new updates and creating textures/models, it often happens that you change factions and have to unlock a certain skill. There is already the command `/vampirism-test skill disableall` to remove all skills, and it would be nice if there was also the counterpart that would practically work like running `/vampirism-test skill <> force` for every skill of the faction.

### Mod experience

📈

### Contributions

n/a

**Comment by Cheaterpaul** [comment]
implemented as `/vampirism-test skill enableall`
