### ISSUE TITLE
[Feature]:Boss Fighting and Mini Bosses 

### ISSUE THREAD

**Issue by shumn1k** [TeamLapen/Vampirism#1082]
### What?

Good afternoon, a very interesting idea came into my head about the fight between the boss and mini-bosses.

What are my suggestions:
1. Since there will be several mini-bosses, I propose the following option: each mini-boss will have its own special skill that it will use against the player.
2. After the player kills the mini-boss, his skills and part of the attack power and the already present skills will be transferred to him. 
3. When we first see the main boss, he will be in his human form at first, but after the fight starts he takes his demonic guise.
4. The main boss will have all the skills of the previous minibosses (he is after all a "Dracula").
5. To complicate things, and make the fight with the main boss more interesting, I propose to make such mechanics:

Players usually take a sword and just hit the mob in a hole or a corner, but with the boss so will not work. Boss at the slightest sign that he is somewhere stuck, will teleport behind the player. Also, the boss at some point will be completely immune to certain attacks the player (eg sword), then here to help take away skills killed mini-bosses, with some of the skill you can deal damage to the boss for a while, after that he will again become immune to this skill and you have to guess what it will beat again. 

6. After killing the main boss the player takes all skills and power of the boss, also in the nickname is signed with the inscription [Dracula]. 
7. The player has a huge advantage between regular vampire mobs and players (1-14 level and 1-5 level lord), as well as the advantage between hunter mobs and players (1-14 level and 1-5 level lord), but if the player-hunter gets as well to the main boss of his faction, he will have the same indicators as the player Dracula. (they will be equal in strength) 

8. After killing the boss player-vampire wings, which he can use in a human guise (about this I have already written an article in discord, also described mechanics of use).
9. The player will appear in the additional menu, where he can adjust the visibility of the wings, as well as be able to adjust their appearance, for example, choose to be constantly in demonic guise, to be different from other vampires)

That's the end of the ideas, I really tried to describe each idea in detail, I think each of them interesting and balanced. Good luck everyone!) 

Nickname in discord: SHUMNIK 

### Mod experience

Just a little bit, just between the players when they became Dracula or Van Helsing

**Comment by maxanier** [comment]
Moved to #757
