### ISSUE TITLE
[Modcompat]: MCA Reborn Villagers still have no blood in 1.16.5 despite everything seems correct

### ISSUE THREAD

**Issue by zlainsama** [TeamLapen/Vampirism#1083]
### Minecraft Version

1.16.x

### Forge Version

36.2.34

### Vampirism Version

1.8.8

### Incompatible mod

"mca", "7.0.11"

### Singleplayer/Multiplayer

Both

### What happened?

MCA Reborn Villagers have no blood in 1.16.5 despite everything seems correct

### Reproduce steps

1. Load a world with Vampirism and MCA Reborn in 1.16.5.
2. Become a vampire and find a MCA Reborn Villager.
3. Observe the entity has no blood.

**Comment by zlainsama** [comment]
![2022-05-11_17 18 02](https://user-images.githubusercontent.com/3251859/167817354-e3e0139b-2505-4d89-8427-b3a299eae062.png)
![2022-05-11_17 18 04](https://user-images.githubusercontent.com/3251859/167817382-d84bd8c0-fcbd-439a-94e4-0f396fd2fee1.png)
![2022-05-11_17 19 17](https://user-images.githubusercontent.com/3251859/167817461-38f196fe-a6a6-445e-bbe0-5459580a23cd.png)
![2022-05-11_17 20 01](https://user-images.githubusercontent.com/3251859/167817478-a50ad2ca-5b54-4858-aae9-8c69904c2b06.png)

**Comment by zlainsama** [comment]
Despite everything data-wise seems correct, they have no blood.

**Comment by zlainsama** [comment]
Also, minecolonies:visitor has no blood.

**Comment by Cheaterpaul** [comment]
there was an issue with the loading of the values. Fixed in the next version

**Comment by zlainsama** [comment]
@Cheaterpaul Please also port this to newer versions, I just tested in 1.18.2 this also happens in newer versions.

**Comment by maxanier** [comment]
Done
