### ISSUE TITLE
[Modcompat]: Residence Claim Protection

### ISSUE THREAD

**Issue by sugar5727** [TeamLapen/Vampirism#1085]
### Minecraft Version

1.12.x

### Forge Version

14.23.5.2859

### Vampirism Version

1.6.2

### Incompatible mod

Residence

### Singleplayer/Multiplayer

Server

### What happened?

Cannot control vampire generation with Residence

### Reproduce steps

I turned off the generation of all entities in the territory, but there were still quite a few vampires generated

**Comment by lunofe** [comment]
1. Vampirism for 1.12.2 is no longer receiving updates unless there are game-breaking bugs.<br>Maintained versions as of now are 1.16.5 & 1.18.2.
2. Bukkit/Spigot plugins tend to be incompatible, or at least not 100% compatible with Forge mods. Hybrid servers are prone to errors like these.
3. I don't think Vampirism is the only mod with this kind of problem, so I would probably see the problem leaning more towards the developers of Residence or the hybrid server you're using.
