### ISSUE TITLE
[Bug]: Crash in DBNO

### ISSUE THREAD

**Issue by Ferisia** [TeamLapen/Vampirism#1088]
### Minecraft Version

1.18.x

### Forge Version

40.1.19

### Vampirism Version

1.8.2

### Modpack

https://www.curseforge.com/minecraft/modpacks/chadpack-1/files/3810404

### Singleplayer/Multiplayer

Both

### What happened?

Game slows and sometimes crashes when vampire enters DBNO state. Whatmore, the game begins to lag again if the vampire chooses to give up instead of resurrecting. 

### Relevant log output

```shell
Server is just killed, there is no crash-report.
```

### Reproduce steps

1. Load game
2. Down a vampire or give up as a vampire.

**Comment by Cheaterpaul** [comment]
Instead of the crash-report, can you provide the `debug.log` file from the log directory?

**Comment by Ferisia** [comment]
Of course, here you go

[debug.log](https://github.com/TeamLapen/Vampirism/files/8800503/debug.log)
.

**Comment by Cheaterpaul** [comment]
I can not reproduce this and the log file does not give a hint what might be the issues.

Feel free to reopen the issue, if this bug is still present
