### ISSUE TITLE
[Feature]: Minion inventory monitoring

### ISSUE THREAD

**Issue by lunofe** [TeamLapen/Vampirism#1091]
### What?

Servers often use two certain types of plugins that 1) allow staff members to view & edit other player's inventories for moderation; and 2) log block placement/breaking, entity interactions, items, and so on.

Examples:
![image](https://user-images.githubusercontent.com/42828197/172016582-7260e534-6424-4206-b0f5-0a102847e72f.png)
![image](https://user-images.githubusercontent.com/42828197/172016734-27cc2327-bcbb-49d9-850e-d597cfdd197e.png)

---

The inventory of minions can't be monitored by either of these types of plugins. It would be very helpful to have a command that allows staff members to view and edit the inventories of another player's minions with a GUI. Some sort of "autocomplete" for the minion names would be needed (another example below).

`/vampirism-test minion inventory <player>:<minion>`

![image](https://user-images.githubusercontent.com/42828197/172017100-e4885fd0-d60d-4a32-928a-327eb95334f2.png)

### Mod experience

Staff: 📈
Players: 〰️

**Comment by supermike1999** [comment]
love to see my name there
