### ISSUE TITLE
[Bug]: config 'totemweight' breaks village generation when set about 150 even though no max is listed in the config

### ISSUE THREAD

**Issue by EnderMelody** [TeamLapen/Vampirism#1092]
### Minecraft Version

1.18.x

### Forge Version

40.1.0

### Vampirism Version

1.8.2

### Singleplayer/Multiplayer

Singleplayer

### What happened?

setting 'totemweight' above 150 prevents village buildings from generating. there simply needs to be a max listed in the config.

### Relevant log output

```shell
[05Jun2022 17:23:30.200] [Render thread/ERROR] [net.minecraft.resources.RegistryResourceAccess$InMemoryStorage/]: Error adding element: Value 151 outside of range [1:150]
```

### Reproduce steps

set 'totemweight' to above 150
load a new village
it will only be the bell and paths

**Comment by maxanier** [comment]
Thank you for reporting. I stumbled across empty villages before and wasn't able to figure out why.
