### ISSUE TITLE
[Bug]: Minions are removed and can not be recalled

### ISSUE THREAD

**Issue by Sebaty5** [TeamLapen/Vampirism#1093]
### Minecraft Version

1.18.x

### Forge Version

40.1.48

### Vampirism Version

1.8.2

### Singleplayer/Multiplayer

Server

### What happened?

I got myself a minion and told it to stay at my base. I went on a bit of exploration and when i came back the minion was gone.

I can't revive or call the minion to me and when ever i try i get the following warnings in the server console.

[Server thread/WARN] [de.te.va.en.mi.ma.PlayerMinionController/]: Retrieved entity is not a minion entity null
[Server thread/WARN] [de.te.va.en.mi.ma.PlayerMinionController/]: Retrieved entity is not a minion entity null
[Server thread/WARN] [de.te.va.en.mi.ma.PlayerMinionController/]: Retrieved entity is not a minion entity null
[Server thread/WARN] [de.te.va.en.mi.MinionEntity/]: Minion without lord.

Is there anything i can try or do to either get my minion back or prevent future minions from following this fate?

### Reproduce steps

I tried but were unable to since i am not even sure what happened.

**Comment by Sebaty5** [comment]
I managed to reproduce in singleplayer, atleast I think i did.

Become a lvl5 lord and get some minions.
Teleport far away (10000 blocks in any direction best done on a superflat)
Wait for 5 min so the chunks unload.
teleport back.

**Comment by maxanier** [comment]
Thank you for reporting. I will have a look.
Reloading the world/Restarting the server allows you to get the minions back, doesn't it?

**Comment by Sebaty5** [comment]
yes after a server reload i can recall them to me again but as soon as i leave render distance they vanish again and cant be retrieved till the server is restarted.

If i try to recall them then they appear for a split second before vanishing again. Similar to how mobs appear and disappear in peaceful mode when spawned using a mob egg.

**Comment by Cheaterpaul** [comment]
@maxanier was this fixed with Vampirism 1.18.2-1.8.3?

**Comment by maxanier** [comment]
Ah, yeah, forgot this 1.18 is not the main branch. Not present on 1.16
