### ISSUE TITLE
[Bug]: Bees kill without triggering DBNO system

### ISSUE THREAD

**Issue by TheDrOfDoctoring** [TeamLapen/Vampirism#1096]
### Minecraft Version

1.16.x

### Forge Version

36.2.33

### Vampirism Version

1.8.8

### Singleplayer/Multiplayer

Both

### What happened?

Assuming this isn't intentional for bees to be vampire slayers, the bee damage source isn't accounted for in the list of immortal from damage sources in the config by default, so they'll kill through DBNO. Adding "sting" to the list will prevent them from ignoring DBNO (atleast in 1.16.5, don't know if the damage source is the same in 1.18 but I would assume so)

### Reproduce steps

1. Become a vampire in any world
2. Be attacked by a bee until death
3. On death, DBNO system won't apply

**Comment by Cheaterpaul** [comment]
@maxanier is this on purpose?

**Comment by maxanier** [comment]
nope
