### ISSUE TITLE
[Bug]: I don't have vampire anything

### ISSUE THREAD

**Issue by Virusneko** [TeamLapen/Vampirism#1103]
### Minecraft Version

1.16.x

### Forge Version

36.2.35

### Vampirism Version

1.8.8

### Singleplayer/Multiplayer

Singleplayer

### What happened?

I tried becoming a vampire in various singleplayer words but when the effect dissapears, i dont see the bar above the xp bar, i dont have the hud yellow because the sunlight and i can't even open vampirism menu 

### Reproduce steps

1. Start New World
2. Get bitted by a vampire
3. Get the status effect
4. Status effect dissappears
5. Nothing

### Other relevant mods

TL skin and cape
JEI
The One Probe
Jade
SecurityCraft
Cooking for blockheads
Cosmetic armor renewed
Draconic Evolution
Dynamic lights
Enchantment descriptions
Hats
Inventory Tweaks
Mahou Tsukai
Pneumatic Craft
Travelers Backpack
Waifucraft
Mowzie's Mobs
Vampirism
KNY
Inventory pets
Gravestone moid

**Comment by maxanier** [comment]
Can you please try to use `/vampirism level vampirism:vampire 1` in a creative world.
If nothing happens, please provide the debug.log from that time frame.
If that works, please reset your level (`/vampirism level vampirism:vampire 0`) and use `/effect <your playername> give vampirism:sanguinare_vampiris`, wait until the effect disappears and then provide the debug.log file.
