### ISSUE TITLE
[Feature]: Bloodfog Diffuser

### ISSUE THREAD

**Issue by sunlightFrequency** [TeamLapen/Vampirism#1104]
### What?

Similarly to how Hunters get the Garlic Diffuser to protect themselves from Vampires, I propose that Vampires get a Bloodfog Diffuser that blankets the surrounding area in fog, allowing them to go about their business during the day within their territory as well as providing an aesthetic appeal. 

It would be crafted similarly to the Garlic Diffuser, except with a Diffuser Core that would be need to be made by combining Wool with a bottle of Pure Blood in a crafting grid. Purity 1-4 blood will create the Bloodfog Diffuser Core, while Purity 5 blood will create the Enhanced Bloodfog Diffuser Core, a more potent form of the core that affects a larger area. While within the area, the skybox and fog would take on a red tint similar to Vampire Forests, but less extreme. Right-clicking the diffuser with a plain Water Bottle would change the fog to a more natural tint similar to the Vampire villages, and right-clicking with a Blood Bottle would change it back, allowing the player to choose the aesthetic of their base.

### Mod experience

I believe this would affect mod balance positively, as it would enable a sort of soft "territory claim" system beyond just villages, in both a PvP sense and a roleplaying sense - vampires are classically territorial creatures, after all. It wouldn't give Vampire players any new abilities or buffs either, keeping in the spirit of the Vampire's power being contained within their skill tree and weapons, simply allowing them to roam about their own homes without fear of the sun. For PvP-enabled servers, it would also function as a tell for Hunter players, and perhaps NPC Hunter scouts could rarely spawn within chunks affected by a Bloodfog Diffuser similar to Pillager patrols.

Plus, the aesthetic of a vampire manor coated in foreboding fog is just really cool. :B
I know there's already the umbrellas mod, but there's no reason the two ideas can't co-exist, right? Temporary mobile protection vs permanent, fixed protection.

### Contributions

I have no contributions at present.

**Comment by JDBS** [comment]
It is not a bad idea, however I think it should periodically consume blood from a jar to spread the fog in a 3x3 chunks.

**Comment by maxanier** [comment]
Yes. This will be added eventually. Maybe without the tint control, but definitely a local fog generator.
