### ISSUE TITLE
[Modcompat]: PlayerRevive and Vampirism causes softlock

### ISSUE THREAD

**Issue by BlockTheVillager** [TeamLapen/Vampirism#1105]
### Minecraft Version

1.18.x

### Forge Version

40.1.57

### Vampirism Version

1.8.4

### Incompatible mod

PlayerRevive 2.0.1

### Singleplayer/Multiplayer

Server

### What happened?

When a player vampire dies, they get softlocked

### Reproduce steps

1. join a server with another player as a vampire
2. "die" and get downed, you'll be in the normal player revive menu until..
3. wait for timer to go out or hold left click, set your volume low as it will be very loud, give up and resurrect will not work

**Comment by maxanier** [comment]
Should be fixed with PlayerRevive 2.0.9 or higher
