### ISSUE TITLE
[Bug]: I can't suck blood from an animal but I can suck blood from a receptacle

### ISSUE THREAD

**Issue by wadoox** [TeamLapen/Vampirism#1108]
### Minecraft Version

1.12.x

### Forge Version

Forge - 14.23.5.2854

### Vampirism Version

Vampirism-1.12.2-1.6.2.jar

### Modpack

Mc Eternal Lite

### Singleplayer/Multiplayer

Server

### What happened?

I turned into a vampire but it is impossible for me to suck the blood of animals or other, I can only use the blood available in the blood receptacles and the blood cannot be put in the bottles so it is impossible to play as a vampire

### Reproduce steps

1.connect to an alternos server with the mc eternal lite modpack
2. transforme to vampire
3. it's time to get a blood but impossible for me

### Other relevant mods

All of the mc eternal lite modpack sorry i'dont have this

**Comment by maxanier** [comment]
I am sorry, but 1.12 is no longer supported by us.
From our experience it generally works fine, but some rare mod incompatibilities might be the cause of this.
You could try to figure out which mod is incompatible with Vampirism, but there is not much we can do, unfortunately
