### ISSUE TITLE
[Bug]: Vampire Baron not Spawing from Spawners

### ISSUE THREAD

**Issue by Maxi90909** [TeamLapen/Vampirism#1113]
### Minecraft Version

1.18.x

### Forge Version

40.1.68

### Vampirism Version

1.8.4

### Singleplayer/Multiplayer

Server

### What happened?

I have the Enchanced Spawners Mod. I obtained a Vampire Baron Spawn Egg and wanted to set up a vampire Baron farm. I already had a normal and advanced vampire farm so I just build the same spawn Room and put the Vampire baron spawn egg in the spawner. I noticed that after some time no Barons were spawning at all. 

### Relevant log output

```shell
Debug Log was too long. Max letters 65k :/
```

### Reproduce steps

1. Put an Vampire Baron Spawn Egg in a Enhanced Spawner.
2. No Barons are Spawning

### Other relevant mods

The Server Modpack:
https://www.mediafire.com/file/yza4h4ilpx1sndl/mods.zip/file

**Comment by Cheaterpaul** [comment]
the barons can only spawn in the vampire forest, have you tried to place the spawner there?

**Comment by Maxi90909** [comment]
I Used The world edit mod to change the biome to a vampire Forest. First there were no barons Spawning but after I increased the spawn speed and spawned mobs they started spawning. 
There is one Problem though. All the Barons that Spawn from that Spawner are Lvl 1 Barons. And Lvl 1 Barons aren’t that useful. The Barons Should be around lvl 3-5 because I am Hunterlvl Colonel.

**Comment by Cheaterpaul** [comment]
The level of the barons depend on the "difficulty" around them, which is higher when high level player are close.

**Comment by Maxi90909** [comment]
I am Hunter Lvl Colonel (Lvl 14 Vampire Hunter with Lord lvl 4) and the Barons are still Lvl 1.

**Comment by Maxi90909** [comment]
The Lord Lvl is the Problem. It is not only the spawner, it is general. I spawned Barons with commands and the all the barons are lvl 1. I think the lord lvl is messing up the difficulty for the barons.

**Comment by Cheaterpaul** [comment]
I found the issue here. The spawner has a weird behavior of spawning entities that does not work with out way of determining the level of the barons. Will be hopefully fixed in the next version.

The summon commands work on the other hand works different. It just summons the creature you have descried in the command. If you do not specify the level it will always be level 1. You can summon a specific level with `/summon vampirism:vampire_baron ~ ~ ~ {level: 2}`
