### ISSUE TITLE
Bug: Quest Path of Oblivion accepts any Potion

### ISSUE THREAD

**Issue by Maxi90909** [TeamLapen/Vampirism#1114]
### Minecraft Version

1.18.x

### Forge Version

40.1.68

### Vampirism Version

1.8.4

### Singleplayer/Multiplayer

Server

### What happened?

I was doing the Path of oblivion quest as a hunter. I noticed that the Hunter Representative accepted any type of potion, even Water Bottles. Despite him saying he wants a Potion of poison (45 seconds)

### Reproduce steps

1. Become any faction (Hunter, Vampire or Werewolve) 
2. Go the the faction respective Quest giver Villager.
3. Accept the Path of Oblivion Quest.
4. Get all Required items expect the potion. 
5. Put any type of potion, even a water bottle in your inventory.
6. The Quest giver Villager accepts any potion, even a Water Bottle.

**Comment by Cheaterpaul** [comment]
thanks for reporting, there was a little oversight. Will be fixed in the next version
