### ISSUE TITLE
[Bug]: Zombie Blood Injection Takes Multible Syringes

### ISSUE THREAD

**Issue by Maxi90909** [TeamLapen/Vampirism#1115]
### Minecraft Version

1.18.x

### Forge Version

40.1.68

### Vampirism Version

1.8.4

### Singleplayer/Multiplayer

Server

### What happened?

I watered to get Multible Zombie Blood injection’s. So I used syringes on a Zombie. I had Syringes in my hotbar in a stack of 9. When I used the Syrinfe on one of the Zombies it gave me one Zombie Blood injection. In my hotbar the other 8 Syringes just got deleted.

### Reproduce steps

1.Load any world
2.Get Multible Syringes in a stack of more than 1. 
3. Use the stack of Syringes on a Zombie in Survival mode.
4. Get 1 Zombie Blood injection.
5. All the other syringes are gone.

**Comment by Maxi90909** [comment]
I wanted, not I watered. Stupid Autocorrection.

**Comment by Cheaterpaul** [comment]
thanks for reporting, will be fixed in the next version
