### ISSUE TITLE
[Modcompat]: Vampirism x Tektopia

### ISSUE THREAD

**Issue by TGamingTiger** [TeamLapen/Vampirism#1116]
### Minecraft Version

1.12.x

### Forge Version

14.23.5.2859

### Vampirism Version

1.6.2

### Incompatible mod

Don't know the mod id but it's called Tektopia and I'm using 1.1.0

### Singleplayer/Multiplayer

Both

### What happened?

The village totem spawns in villages but it doesn't actually detect them and when I ran the command /locate village it couldn't find one so my theory is that Tektopia uses the minecraft villages that spawn hence the village totems, vampire hunter houses and other things from other mods spawning in villages but then changes how the village identifies so things that then require to be in an active village don't work so could you find out what type of village Tektopia uses and possibly add that to your intiration mod

### Reproduce steps

1. Download vampirism 1.6.2 and Tektopia
2. Create a singleplayer world or a server
3. Enter the world
4. Find a village
5. Click on the village totem
You should then see a message in chat saying the totem isn't in a village
I'm not sure if it works as a hunter I've only tested as a vamp

**_Possible Fix 1_**
1. Have Vampirism check if Tektopia is also launched or is going to be launched by running though the mod list and if so add that to a variable or if not make the variable the normal village totem
2. Find out the Tektopia village identifier
3. Add a second type of village totem that is only accessible through creative when Tektopia isn't installed or just isn't accessible at all
4. Copy the code from the first village totem and paste the code into the second village totem
5. Change the village identifier on the second village totem to the one Tektopia villages use
6. Make it so that when Tektopia is installed the craftable village totem and the one you find naturally are both changed to the second village totem and make the first village totem become only accessible through creative mode or not accessible at all (you can do this by adding the variable of what type of village totem it is to the crafting recipe and the totem that is spawned)
**_I know what I'm proposing is a lot more complicated then my explanation gives it credit for but I did a lot of digging before I came here and this is the best way I can think of that should work I also didn't describe it word for word how I would do it and left some easily fillable gaps because unlike most people in this world I actually know that everyone have there own way of coding with this method you would be able to add more types of villages in the future if need be_**

**_Possible Fix 2_**

This shouldn't be a permanent fix as it is limited to the people who know what they are doing when it comes to creating modpacks and to some possibly game breaking mechanics but you could just add a command that would say the identifier of the structure in chat and have an area in the village config that would make the village totem work anywhere it has the structure identifier for
**_The problem with this one though is that people can get the structure identifier for an end city for example and use a village totem in an end city_**

**Comment by maxanier** [comment]
Thank your for reporting this issue.
The village totem system has been totally reworked for MC 1.14 and up to support any village like structure and should therefore support Tektopia like villages. Unfortunately, Tektopia is only available for MC1.12.
We do no longer support MC1.12 ourselves.

**Comment by TGamingTiger** [comment]
Then would you allow me to decompile vampirism and make the suggested change myself? also if so would using one of the codes from one of the newer ones for some ideas on how I could do it without having to completely rewrite your code and which one would be the best for that

**Comment by maxanier** [comment]
The mod is open source, you have the code right in this repository, no need to decompile. Just checkout the 1.12 branch and locate the TotemTileEntity
As long as you adhere to the license (LGPLv3, give credit, publish code if you publish compiled file) you are welcome to implement the suggested changes yourself.

**Comment by TGamingTiger** [comment]
Correct me if I'm wrong but I'm allowed to edit it as long as I publish the code if I'm going to put it on a modpack and i give you some of the credit for it?

**Comment by maxanier** [comment]
If you do not upload anything, you can do whatever you want.
If you upload the modified jar or a modpack somewhere, you have to also provide the source code of your changes and give credit.

**Comment by TGamingTiger** [comment]
ok

**Comment by TGamingTiger** [comment]
How does the 1.16.5 one know what is and isn't a village
