### ISSUE TITLE
[Bug]: Cant join Waterfall server

### ISSUE THREAD

**Issue by PabloGirol** [TeamLapen/Vampirism#1117]
### Minecraft Version

1.16.x

### Forge Version

36.2.36

### Vampirism Version

1.8.10

### Singleplayer/Multiplayer

Server

### What happened?

I am joining a lightfall (Waterfall with forge support) server, First we join a vanilla server and then we move on to the modded server
(Theoretically)
But trying to join Waterfall we are greeted with a message that says "Incomplete set of tags received from server Please contact server operator"
Is there any way you could modify the code that it will not require this on any server join? Like the server handshaking before the tags are sent?

### Reproduce steps

1. Create lightfall server, with forge support enabled, and 2 servers, one with vanilla and the other one with forge
2. Set the priority to the vanilla server
3. Try to join.

### Other relevant mods

lightfallClient

**Comment by maxanier** [comment]
I think you should rather contact the lightfall devs regarding this. I don't think Vampirism is doing anything special here, so this is likely more a prroblem with Forge in general?
On first look I also found this similar issue report over at their repo, but it does not contain much information or has any response
https://github.com/ArclightPowered/lightfall/issues/29

If there is something specific that must be changed, I'm happy to make such adjustments, but I need someone to explain to me what exactly.

**Comment by PabloGirol** [comment]
What I seem to understand of what is happening is that the client is expecting the vampirism tags being sent from the server.
When using lightfall, you join a vanilla server at first, so you cannot receive those tags immediately untill you join the modded server

If you join the modded server first, that will not happen, but we are experiencing another issue while logging in, which seems unrelated to this

**Comment by Cheaterpaul** [comment]
just like maxanier said, we are not doing anything special other than using the tools forge provides. You should bring this up the the lighfall developers.
