### ISSUE TITLE
[Feature]: Mysterious Forest Boss

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#1118]
### General
- faction specific achievement
- unique decoration block or armor piece
### Vampire
- Crafting ingredient for fog generator (which may also function as saturation beacon) #1104 
- enhance vampire cloth
### Hunter
- Maybe item that can replace vampire blood without being consumed (if we add more use for vampire blood)

## Implementation details:

- Indestructible base block
- Requires graph search to find all structure blocks (implementing interface) from any given point in structure
- Central block fully enclosed by structure
  - Loot table chest like
- Weak points
  - Convert to block entity upon damage
  - Require continuous damaging for full destroying
  - Trigger defensive forces upon damaging
  - Slowly heal if not damaged
  - Convert to destroyed weakpoint block after destruction
  - Animated texture (while active)
  - Upon full destruction trigger structure integrity check based on graph search. If no further intact weakpoints are found, trigger structure destruction process
  - Potentially, activating one weakpoint could lock all for some time
  - Damage to block entity is collected via dummy entity
    - BE spawns entity with slightly larger BB
    - remembers ID to check if existent
    - Dummy entity forwards damage to BE
    - Dummy and dummy id in BE is not saved to disk, but respawned upon load
 - Structure destruction process (all block dissolve into air revealing central loot "chest")
 - WorldSavedData `ForestBossManager`
   - Not sure if actually needed
   - Fight id is derived from block pos of central block, weakpoint tile entities can search for it once, then cache id
 - Defense
   - Weakpoint BE continuously spawns vampires or new mob type nearby until destroyed or healed
   - Occasionally, new blocks are placed nearby (on ground/structure) that drain blood from nearby players, but can be destroyed with normal tools (axe)
 - Mob type
   - Spawned in ground
   - While in ground, does not suffocate, and slowly rise upwards
   - When above ground, reset collision box, and attack normally
 - Specific player action weaknesses
   - Freeze action temporarily "freezes" weakpoint defense (need to visuallize somehow)

**Comment by maxanier** [comment]
Slowly destroy blocks from the outside to the inside.
Extend connector collector to save depth.
Somehow queue destruction

**Comment by maxanier** [comment]
Remaining TODO:
- [x] Replace continuous damage by weak points with continuous blood loss
- [x] Weak points spawn defense blocks on open side
  - [x] Block (entity) ? shulker like ?
  - [x] Blood projectiles
  - [x] Destructible
- [x] Weak points as vampire leader (attract basic vampire) **Change weakpoint dummy entity to `LivingEntity` ?** Also good for freeze/fire/holy water ...
- ~[ ] Spawn vampires~
- [x] New *ghoul* like entity (maybe ghost model) 
  -  Initial no clip. Spawn in floor
- [x] Fine tune loot (table)
   - [x] Recipe mother core #1181
- [x] update structure

**Comment by maxanier** [comment]
We also still need
- [x] faction specific achievement
- [x] Unique decorative item or armor piece
- [x] a way for hunters to benefit from the mother core
- [x] add sounds
  - [x] client sided mother sounds
- [ ] tips and tricks in lore ...

**Comment by Cheaterpaul** [comment]
- [x] add thorns damage when attacking vulnerabilities
- [x] potion damage to the vulnerabilities
- [x] vampire sword finisher on vulnerabilities, defenders and ghosts

think about:

- ~[ ] add low over time damage when the player is not moving~

**Comment by DeathXInvader** [comment]
yo I play problem i ran across im not sure if its desighned this way but the bloodfog diffuser does work fine and runs constantly like designed however when you leave the game and come back its no longer activated
