### ISSUE TITLE
[Bug]: Client crash when generating world

### ISSUE THREAD

**Issue by SkyKingPX** [TeamLapen/Vampirism#1119]
### Minecraft Version

1.18.x

### Forge Version

40.1.73

### Vampirism Version

1.8.5

### Singleplayer/Multiplayer

Singleplayer

### What happened?

Client has crashed while generating a new world

### Reproduce steps

1. Create new world (Creative)

**Comment by Cheaterpaul** [comment]
Without a crash report or a debug.log there is no way we can help you

**Comment by SkyKingPX** [comment]
Then I paste it when I have time :D

**Comment by Kangy1103** [comment]
[crash-2022-08-19_00.14.57-server.txt](https://github.com/TeamLapen/Vampirism/files/9384060/crash-2022-08-19_00.14.57-server.txt)
[crash-2022-08-19_18.04.14-server.txt](https://github.com/TeamLapen/Vampirism/files/9384061/crash-2022-08-19_18.04.14-server.txt)

@Cheaterpaul Hi, Same issue here for me as well.  I've attached a couple of crash reports for you

**Comment by Cheaterpaul** [comment]
Will be fixed in the next release.

@Alphastein2021 please reopen if this was not your issue
