### ISSUE TITLE
[Feature]: Use vanilla method for curing vampires

### ISSUE THREAD

**Issue by MarioSMB** [TeamLapen/Vampirism#1124]
### What?

The vanilla game provides a means of curing the undead (golden apples fed to weakened mobs). While this mechanic does exist in the mod, the addition of a new item (infected apples) to do so seems a little redundant.   
It would be nice if curing yourself and other vampiric creatures could be done with the vanilla method to avoid adding a duplicate item for the task - one less item contributing to feature bloat!

### Mod experience

Players are familiar with the vanilla mechanic of curing the undead, this would be far more intuitive and fit better as a part of the game.

### Contributions

N/A

**Comment by maxanier** [comment]
I understand that this is one more single-purpose item. I think the idea behind it was, that curing a vampire should take more effort than curing a zombified villager and this process was developed with our "lore taskforce" if I recall correctly.
Maybe it would beneficial for gameplay to not use this process. @Cheaterpaul call

**Comment by Cheaterpaul** [comment]
Yes, the ides was to have a different way to cure vampire creatures because vampires and zombies are quite different. But since the crafting recipe for the cursed apple doesn't make much sense and a golden apple isn't zombie specific, I changed it.
