### ISSUE TITLE
[Bug]: Item Requirements for Tasks must be exact

### ISSUE THREAD

**Issue by torgriddy** [TeamLapen/Vampirism#1125]
### Minecraft Version

1.18.x

### Forge Version

40.1.73

### Vampirism Version

1.8.5

### Werewolves Version

0.6.1

### Singleplayer/Multiplayer

Singleplayer

### What happened?

When I tried to become a werewolf lord, I had all the criteria completed and the items, but it would not register that I had the items in my inventory an would not let me complete the mission

### Reproduce steps

1. load singleplayer world
2. get to werewolf level 14
3. Initiate the Becoming a Lord quest
4. complete criteria and put the necessary items in inventory 
5. try to submit the quest

### Other relevant mods

Balm 3.2.0+0
waystones-forge 10.1.0

**Comment by Cheaterpaul** [comment]
Can you try it with an exact item stack. Meaning if the quest wants 2 werewolf tooth only have 2 werewolf tooth in your inventory, no more no less.

**Comment by torgriddy** [comment]
I tried that already, it still didnt work
    On Thursday, August 25, 2022 at 04:33:28 a.m. CDT, Paul Becker ***@***.***> wrote:  
 
 


Can you try it with an exact item stack. Meaning if the quest wants 2 werewolf tooth only have 2 werewolf tooth in your inventory, no more no less.

**Comment by Cheaterpaul** [comment]
I can only confirm this when have you don't have an exact stack in your inventory.

if the task requires two werewolf tooth you must have a stack of two werewolf tooth in you inventory, not a stack of more than two and not two stacks with one werewolf tooth.

**Comment by maxanier** [comment]
@Cheaterpaul This also affects stable 1.18 right?

**Comment by Cheaterpaul** [comment]
yes it does
