### ISSUE TITLE
[Feature]: Slight Change for config

### ISSUE THREAD

**Issue by 78codemonkey** [TeamLapen/Vampirism#1126]
### What?

using MC : 1.18.2, Forge: 40.1.74, vampirism: Latest Version for 1.18.2

For vampirism, have config file for VampireEyes = true
Instead be separated toggle like:
VampireEyes = true
VampireFangs = false

also maybe support player eyes for MCA?

### Mod experience

with current skin don't need the fangs part, only prefer eyes to properly set, about 60% negative for fangs

**Comment by 78codemonkey** [comment]
or have blank fang added to selection

**Comment by maxanier** [comment]
Fangs 7 should be blank already, right?
