### ISSUE TITLE
[Bug]: Hunter Axes dont do the crit sound

### ISSUE THREAD

**Issue by JustPandas** [TeamLapen/Vampirism#1128]
### Minecraft Version

1.16.x

### Forge Version

36.2.2

### Vampirism Version

1.8.3

### Singleplayer/Multiplayer

Both

### What happened?

I have noticed that Hunter axes dont do the critical hit sound, even tho you crit an entity. it still does the amount of damage it shoul do for a crit, so i dont know why its like that

### Reproduce steps

1. join the vampirism server/load up a world
2. become a hunter 
3. get a hunter axe (i used the ultimate)
4. crit an entity

**Comment by maxanier** [comment]
The implementation of the hunter axe and especially the vampire slayer effect is a bit weird in Vampirism 1.8.
It is already changed in the 1.9 alphas (428ab400ce8794200ab97a8859417963a8af7bea) and the crit sound should work as expected there. It probability won't be fixed for 1.8 as it is not really a big problem
