### ISSUE TITLE
[Feature]: Building Vampirism 1.8 for 1.12.2

### ISSUE THREAD

**Issue by wedgevic** [TeamLapen/Vampirism#1129]
### What?

Heya, so as the title suggests, I have been wondering if I can play vampirism 1.8 with all of it's fantastic features on 1.12.2, or if I can at least build it myself.

I know the joke about pestering mod devs to add versions, but I just want to know if it's possible and I'm sorry if it comes across as that. Thanks for the help!

**Comment by Cheaterpaul** [comment]
Well, the 1.12 versions are too far back as that it would be easy to build a 1.8 version for it. The 1.12 branch is 1400 commits behind the current version, that's about half of all commits and would take hundred of hours to port back to 1.12. This would also lead to feature removals that are not supported by older Forge/Minecraft versions.

All in all i would say that it is far to much work. It would be more beneficial to start playing Minecraft 1.19. Not only is Minecraft 1.19 more feature rich, but also the updated and new mods that are almost always better than the 1.12 mods.

But of cause are you free to do it under the LGPL license of Vampirism.

**Comment by wedgevic** [comment]
ok, thank you
