### ISSUE TITLE
[Bug]: Ultimate tier of Heartseeker and Heartstriker accept only a few enchantments

### ISSUE THREAD

**Issue by Einhornyordle** [TeamLapen/Vampirism#1132]
### Minecraft Version

1.18.x

### Forge Version

43.1.32

### Vampirism Version

1.8.0

### Singleplayer/Multiplayer

Singleplayer

### What happened?

First of all, this bug occurred in 1.19.2, the Minecraft Version dropdown element had no 1.19+ option so I chose the latest version available which was 1.18.x

The Ultimate tier of Heartseeker and Heartstriker can only get a few minor enchantments compared to vanilla swords and lower tiers (normal & enhanced) editions. I'd expect them to get the same enchantments as the other tiers.

### Reproduce steps

1. Load a creative single player world
2. Get a few Ultimate Heartseekers /-strikers
3. Put them one by one in an enchanting table and enchant them
4. They will only get Unbreaking and maybe some Enchantments by other mods.

### Other relevant mods

You can also use Just Enough Ressources and press U while the mouse is over one of the swords or use the Enchanting Infuser Mod to see all possible enchantments.

**Comment by Cheaterpaul** [comment]
It was intended that the ultimate versions would only have access to some enchantments.

But that was changed in Vampirism 1.9, where they can have any enchantment except Fire Aspect and Mending.
