### ISSUE TITLE
[Bug]: (Garlic-) Blood Vision shows Vanilla mobs rotated on an axis

### ISSUE THREAD

**Issue by InsomnicNoA** [TeamLapen/Vampirism#1137]
### Minecraft Version

1.19.x

### Forge Version

43.1.33

### Vampirism Version

1.19.2-1.8.1

### Singleplayer/Multiplayer

Both

### What happened?

When using Blood / Garlic Blood Vision creatures will not have their outlines rendered properly
This likely has something to do with another mod rendering the game differently
![image](https://user-images.githubusercontent.com/115367974/194720649-3cb62c75-0ef2-42ac-8e23-83f974c41099.png) 
![image_2022-10-08_193717999](https://user-images.githubusercontent.com/115367974/194720386-2fa299f1-1cad-47a9-9316-4d90dc72cf0e.png)
![image_2022-10-08_193741368](https://user-images.githubusercontent.com/115367974/194720403-b6102936-097f-4a3d-84c1-b0b4ca02c34a.png)

### Reproduce steps

1. Be level 7 or 8 for Blood / Garlic Blood Vision (See image for my current skill tree)
2. Activate (Garlic-) Blood Vision
3. See creatures being weirdly turned on an axis around you
![image_2022-10-08_194015821](https://user-images.githubusercontent.com/115367974/194720505-121fdd3b-012b-48ae-b035-755b53dc7479.png)

### Other relevant mods

(If asked I will give out a download of all of the mods in a zip file)

3dskinlayers-forge-1.5.2-mc1.19.1.jar
abnormals_delight-1.19-4.0.0.jar
Adorn-3.6.1+1.19-forge.jar
AI-Improvements-1.19.2-0.5.2.jar
alexsmobs-1.20.1.jar
another_furniture-forge-2.0.3-1.19.2.jar
appleskin-forge-mc1.19-2.4.2.jar
Aquaculture-1.19.2-2.4.7.jar
architectury-6.2.46-forge.jar
ars_elemental-1.19.2-0.5.5.3c.jar
ars_nouveau-1.19.2-3.4.1.jar
AttributeFix-Forge-1.19.2-17.1.2.jar
auudio_forge_1.0.3_MC_1.19.jar
backpacked-2.1.10-1.19.jar
BadMobs-1.19.2-16.1.2.jar
balm-4.5.3.jar
BetterAdvancements-1.19.2-0.2.2.142.jar
BetterCompatibilityChecker-1.0.8-build.36+mc1.19.2.jar
BetterModsButton-v4.2.1-1.19.2-Forge.jar
BetterTridents-v4.0.1-1.19.2-Forge.jar
BHMenu-Forge-1.19.2-1.3.jar
biomemakeover-FORGE-1.19.2-1.5.12.jar
blue_skies-1.19.2-1.3.20.jar
blueprint-1.19.2-6.1.0.jar
Bookshelf-Forge-1.19.2-16.1.5.jar
buzzier_bees-1.19-5.0.1.jar
caelus-forge-1.19.2-3.0.0.6.jar
canary-mc1.19.2-0.0.3.jar
Cataclysm-0.20-1.19.2-hotfix.jar
charmofundying-forge-6.0.0+1.19.2.jar
cherishedworlds-forge-6.0.1+1.19.2.jar
Chimes-1.1.4-1.19.jar
citadel-1.12.12-1.19.jar
cloth-config-8.2.88-forge.jar
collective-1.19.2-5.0.jar
comforts-forge-6.0.2+1.19.2.jar
configured-2.0.1-1.19.2.jar
Controlling-forge-1.19.2-10.0+6.jar
corail_woodcutter_extension_byg-1.19.2-1.0.3.jar
corail_woodcutter-1.19.2-2.5.0.jar
corpse-1.19.2-1.0.0.jar
Cucumber-1.19.2-6.0.2.jar
curios-forge-1.19.2-5.1.1.0.jar
DarkPaintings-Forge-1.19.2-13.1.2.jar
Decorative+Blocks-forge-1.19.2-3.0.0.jar
deeperdarker-1.0.0b-1.19.2.jar
Delightful-1.19-3.1.1.jar
DiagonalFences-v4.2.1-1.19.2-Forge.jar
Disenchanting-forge-1.19-2.1.0.jar
doubledoors_1.19.2-3.5.jar
DoubleSlabs-1.19-6.1.0.jar
dragonmounts-1.19.2-1.1.4a.jar
drippyloadingscreen_forge_1.6.4-1_MC_1.19.jar
duckling-2.0.7-forge.jar
DungeonsArise-1.19-2.1.51-beta.jar
dynamic_asset_generator-forge-1.19.2-1.0.1.jar
EarthMobs-1.19.2-3.2.1.jar
EasyAnvils-v4.0.1-1.19.2-Forge.jar
EasyMagic-v4.3.2-1.19.2-Forge.jar
ecologics-forge-1.19.2-2.1.10.jar
effective_fg-1.3.4.jar
elevatorid-1.19-1.8.7.jar
elytraslot-forge-6.0.0+1.19.2.jar
EnchantmentDescriptions-Forge-1.19.2-13.0.3.jar
enchantwithmob-1.19.2-6.2.0.jar
entity_texture_features_forge_1.19.x-4.1.1.jar
entityculling-forge-1.5.2-mc1.19.1.jar
EquipmentCompare-1.19.1-1.3.1.jar
everycomp-1.19.2-2.0.6.jar
excavated_variants-forge-1.19.2-1.0.3.jar
Fallingleaves-1.19.1-1.3.0.jar
FallingTree-1.19.2-3.10.0.jar
fancymenu_forge_2.12.2-1_MC_1.19-1.19.2.jar
FarmersDelight-1.19-1.2.0.jar
ferritecore-5.0.1-forge.jar
friendsandfoes-forge-mc1.19.2-1.5.11.jar
frozenup-2.0.0-forge.jar
geckolib-forge-1.19-3.1.23.jar
geode-1.1.3-1.19.2.jar
goblintraders-1.8.0-1.19.2.jar
guardvillagers-1.19.2-1.5.2.jar
Guide-API-VP-1.19.2-2.2.4.jar
Highlighter-1.19.1-1.1.4.jar
hunterillager-1.19.2-6.0.1.jar
Iceberg-1.19.2-forge-1.0.48.jar
illagersweararmor-1.2.1.jar
InventoryHud_[1.19.2].forge-3.4.6.jar
ironchests-3.0.4-forge.jar
Jade-1.19.1-forge-8.3.0.jar
jei-1.19.2-forge-11.3.0.262.jar
JustEnoughProfessions-forge-1.19-2.0.1.jar
JustEnoughResources-1.19.2-1.1.0.179.jar
Kiwi-1.19.1-forge-8.1.1.jar
kleeslabs-forge-1.19-12.1.0.jar
konkrete_forge_1.5.0_MC_1.19-1.19.1.jar
kotlinforforge-3.7.1-obf.jar
MagicalTorches-1.19.2-2.0.2.jar
MagnumTorch-v4.2.0-1.19.2-Forge.jar
mavm-1.1.0-mc1.19.jar
modonomicon-1.19.2-1.4.0.jar
moonlight-1.19.2-2.0.32.jar
More+Babies-forge-1.19.1-1.0.0.jar
morevillagers-forge-1.19-4.0.3.jar
mvs-3.1.3.jar
MysticalAgriculture-1.19.2-6.0.3.jar
NaturesAura-37.4.jar
NaturesCompass-1.19.2-1.9.7-forge.jar
NekosEnchantedBooks-1.19-1.8.0.jar
netherportalfix-forge-1.19-10.0.0.jar
NoChatReports-FORGE-1.19.2-v1.4.0.jar
notenoughanimations-forge-1.6.1-mc1.19.1.jar
occultism-1.19.2-1.45.4.jar
oculus-mc1.19.2-1.2.8.jar
Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.11.jar
OpenLoader-Forge-1.19.2-15.0.1.jar
open-parties-and-claims-forge-1.19.2-0.14.1.jar
Paintings-forge-1.19.2-10.2.1.0.jar
Patchouli-1.19.2-76 (1).jar
personality-1.19-3.0.1.jar
PickUpNotifier-v4.2.0-1.19.2-Forge.jar
polymorph-forge-0.45.0+1.19.2.jar
PuzzlesLib-v4.3.9-1.19.2-Forge.jar
Raided-1.19.2-0.1.1.jar
recall-1.19-1.3.1.jar
repurposed_structures_forge-6.3.1+1.19.2.jar
respawningshulkers_1.19.2-1.9.jar
revampedwolf-1.19-2.0.2.jar
Rex's-AdditionalStructures-1.19.x-(v.4.0.2).jar
rubidium-0.6.2.jar
saturn-mc1.19.2-0.0.1.jar
savage_and_ravage-1.19-5.0.2.jar
SereneSeasons-1.19.2-8.1.0.21.jar
SimpleDiscordRichPresence-forge-3.0.2-build.23+mc1.19.2.jar
SimpleStorageNetwork-1.19-1.6.4.jar
skinned_lanterns-1.19.2-1.3.4.jar
smoothboot(reloaded)-mc1.19.2-1.0.4.jar
smoothchunk-1.19.1-2.0.jar
SnowRealMagic-1.19.2-forge-5.0.3.jar
snowundertrees-1.19.2-1.3.jar
snowyspirit-1.19.2-2.0.6.jar
snuffles-1.0.3.jar
spirit-forge-1.19.2-2.1.12.jar
starterkit_1.19.2-3.4.jar
Structory-1.19-1.2.jar
structure_gel-1.19.2-2.7.0.jar
supplementaries-1.19.2-2.2.3.jar
swingthroughgrass-1.19.2-1.10.0.jar
takesapillage-1.0.1-1.19.2.jar
TaxFreeLevels-1.3.1-forge-1.18.1.jar
TerraBlender-forge-1.19.2-2.0.1.127.jar
textrues_rubidium_options-1.0.3-mc1.19.2.jar
the-conjurer-1.19.2-1.1.4.jar
Tips-Forge-1.19.2-8.0.3.jar
TradingPost-v4.2.0-1.19.2-Forge.jar
transparent-5.1.0+1.19-forge.jar
twilightforest-1.19-4.2.1421-universal.jar
upgradedcore-1.19.2-4.1.0.0-release.jar
upgradednetherite_items-1.19.2-4.1.0.1-release.jar
upgradednetherite_ultimate-1.19.2-4.1.0.0-release.jar
upgradednetherite-1.19.2-5.1.0.2-release.jar
Vampirism-1.19.2-1.8.1.jar
villagernames_1.19.2-4.1.jar
VisualWorkbench-v4.2.0-1.19.2-Forge.jar
voidtotem-forge-1.19.2-2.1.0.jar
waystones-forge-1.19-11.1.0.jar
Werewolves-1.19.2-1.8-0.6.0-beta.1.jar
Xaeros_Minimap_22.15.1_Forge_1.19.1.jar
XaerosWorldMap_1.28.0_Forge_1.19.1.jar
xptome-1.19-2.1.6.jar

**Comment by Cheaterpaul** [comment]
already fixed in the latest versions
