### ISSUE TITLE
[Bug]:  weird item stacking bug

### ISSUE THREAD

**Issue by tech-boy101** [TeamLapen/Vampirism#1139]
### Minecraft Version

1.16.x

### Forge Version

36.2.39

### Vampirism Version

1.9.0 beta 1

### Singleplayer/Multiplayer

Singleplayer

### What happened?

for some reasons and item that same thing can not stack each other best to test out i find is to ether craft some torches and place
one down then pick back up is wont stack with it other torches inventory unless you place all torches and then pick up again then stack this happen to more just torches they just best way to test it out is happen ore like lapis this happen just with mod and it self no other mod are need for this happen

### Reproduce steps

1. created new world
2. craft torches or get from creative mode
3. place torches down
4. pick torches back up
5.not stackable item that should stack with it self

**Comment by Daihok41** [comment]
I am experienceing this bug in the 1.19.2 -1.9.0  alpha version as well

**Comment by Cheaterpaul** [comment]
Thanks for reporting, we mistakenly modified the item nbt data.
