### ISSUE TITLE
NPE crash on startup with Block Drops mod

### ISSUE THREAD

**Issue by Anarcraft** [TeamLapen/Vampirism#114]
NPE crash on startup.  Disabling either mod prevents the issue.

http://pastebin.com/ei9cwM8Z

**Comment by maxanier** [comment]
Not totally sure, but I think that problem is mainly caused on Block Drops side. I've created an issue there:
https://github.com/MrRiegel/BlockDrops/issues/13

**Comment by Anarcraft** [comment]
Yea I wasn't sure who to file it with but I chose you because it showed up in the log first.  Thanks for letting them know.

**Comment by maxanier** [comment]
Should be fixed in a new version of Block Drops
