### ISSUE TITLE
[Feature]: increase the minion stats increase for vampire lord perk

### ISSUE THREAD

**Issue by tech-boy101** [TeamLapen/Vampirism#1140]
### What?

the new vampire lord perk for minion that increase value is not worth the point put in to be at end you own gain extra 3 hp if put in health or 0.3 or 0.6 damage increases from what i test out so far also on side note why add blood collect is perk vs give blood collect for minion a upgrade like chance to find better and newer items like maybe some vampire weapons or vampire Accessory and some stop get blood bottle and just collect human heart instead is they are worth more blood then the blood bottle and are stackable and actual give you saturation so you much faster

**Comment by maxanier** [comment]
I am sorry, but I do not understand what you are suggesting exactly.
Can you please rephrase/organize your suggestion

**Comment by tech-boy101** [comment]
the new perk offer by become a vampire lord that boost your minion stacks [Vampirism-1.19.2-1.9.0-beta.2] only seem to give a 0.3 or 0.6 increase to your damage even wind upgrade them use the different minion upgrade scrolls did that help to expanded it i best wanna to know if that tended or not is not even noticeable is a actual damage upgrade or at less from what i use of wind i was test it out with first post i have no idea if that still the same in the mod 1.9,0 beta 3 the way i seen was use the stats system for minions where show how much damage the minion actual deals sorry still can make sense of this my not best with grammar or spelling
