### ISSUE TITLE
[Feature]:  better vampire  Regeneration

### ISSUE THREAD

**Issue by tech-boy101** [TeamLapen/Vampirism#1141]
### What?

vampire regeneration is stand right now is only usefully from what i play so far in single player is have not join pvp sever or any like that wind you just below hunger regen threshold and low on life and need wanna bit just in case arrow come at why try to find or get some blood  new i subject wood be is fast is normal minecraft saturation wind to heal rate but remove hunger threshold so each time heal you take bit your blood away will also stop the whole can active the power with no blood bit is well and make lot more useful is fast quick heal at cost of lot of blood this wood also remove cooldown of the power is i think with how this work should be petty bad is go drain also drain of blood more just level you with with half or one full one once done and stuff that increase this power wood basic made heal for 1 more heart per half blood drop

**Comment by maxanier** [comment]
The hunger effect has been removed in the latest beta/release of 1.9 a couple of days ago
