### ISSUE TITLE
[Bug][1.16.x]: Crash when trying to sleep on a coffin wich has solid blocks (or beds) on the sides

### ISSUE THREAD

**Issue by israpps** [TeamLapen/Vampirism#1144]
### Minecraft Version

1.16.x

### Forge Version

latest. can't remember specific version

### Vampirism Version

latest 1.16.5 build (can't remember version too lol)

### Modpack

none

### Singleplayer/Multiplayer

Singleplayer

### What happened?

When trying to sleep on a coffin wich has solid blocks on the sides, the animation halts (right when POV changes to the coffin insides, right before the coffin cap starts moving) then game crashes.

It happened to me twice
1st time there was a bed on the side
2nd time, there were dark oak planks (vanilla)

### Relevant log output

```shell
i'm not on the PC with the log, will upload one later
```

### Reproduce steps

1. place a coffin
2. place a solid block on the sides of it 
3. try to sleep

**Comment by maxanier** [comment]
Cannot reproduce. Please provide crash report once you are at your PC again

**Comment by israpps** [comment]
[crash-2022-10-30_17.02.48-server.txt](https://github.com/TeamLapen/Vampirism/files/9914945/crash-2022-10-30_17.02.48-server.txt)
Here, hope it provides the info you need

**Comment by maxanier** [comment]
Sorry for the long delay. I am not 100% certain, but the latest version 1.16.5-1.9.1 may fix this issue. Please report if it still occcurs

**Comment by israpps** [comment]
Hi, thanks for answering.
Unfortunately, due to certain circumstances, I won't have access to hardware capable of running modded Minecraft for a long time

**Comment by maxanier** [comment]
Sorry to hear that :/
