### ISSUE TITLE
[Bug]: The textures of the entire armor are missing.

### ISSUE THREAD

**Issue by sssHpion007** [TeamLapen/Vampirism#1145]
### Minecraft Version

1.19.x

### Forge Version

43.1.2

### Vampirism Version

1.9.0-alpha+20221030-1855

### Singleplayer/Multiplayer

Singleplayer

### What happened?

The textures of the entire armor are missing.
![image](https://user-images.githubusercontent.com/30200363/199341535-393f5733-8d1b-4446-9bc2-952e5d8558b1.png)

**Comment by sssHpion007** [comment]
Sorry I didn't notice that I downloaded alpha

**Comment by maxanier** [comment]
No worries. Is fixed in the now released beta.1
