### ISSUE TITLE
[Bug]: Armor Breaking On death

### ISSUE THREAD

**Issue by wolflord212312** [TeamLapen/Vampirism#1149]
### Minecraft Version

1.18.x

### Forge Version

40.1.84

### Vampirism Version

1.8.7

### Modpack

https://www.curseforge.com/minecraft/modpacks/foxycraft-colonies

### Singleplayer/Multiplayer

Both

### What happened?

When a vampire i sometimes lose my armor(instant breaks) when i hit give up instead of reviving

### Reproduce steps

1.load server/solo
2.become vampire level 1
3.put on armor
4.Get knocked down
5.give up
6.Hear armor break
7.pickup grave
8.realize you lost your max level netherite armor

### Other relevant mods
gravestone-1.18.2-1.0.1.jar

**Comment by maxanier** [comment]
I will have a look.
Maybe I forgot to make sure the DBNO damage bypasses armor
https://github.com/TeamLapen/Vampirism/blob/2bac55776e59ba28c128585957ea9a6794d4a016/src/main/java/de/teamlapen/vampirism/entity/player/vampire/VampirePlayer.java#L1094

**Comment by wolflord212312** [comment]
Ok my good sir

**Comment by EnotScript** [comment]
you fix that? My armor annihilate from any mod 🤯 v 1.20.1

**Comment by Cheaterpaul** [comment]
> you fix that? My armor annihilate from any mod 🤯 v 1.20.1


Does your armor break when giving up as a vampire after being downed?

**Comment by EnotScript** [comment]
https://youtu.be/cXlQpsTpqd8

**Comment by Cheaterpaul** [comment]
Your armor does not break when giving up, but when you are killed with a stake.
Will be fixed
