### ISSUE TITLE
[1.10.2] Crash on Startup

### ISSUE THREAD

**Issue by nikkimas** [TeamLapen/Vampirism#115]
Crash-Report: http://pastebin.com/VKMXCvcz

Problem: Crash on Startup

Expected behaviour: No crash on startup

Steps to reproduce the problem:
- Start Minecraft
- Wait
- See Crash

**Comment by nikkimas** [comment]
Okay, stupid me. Seems to be the same Issue as then one at #114

**Comment by maxanier** [comment]
"Expected behaviour: No crash on startup" :joy:

Closing this as duplicate
