### ISSUE TITLE
[Bug]: Blood bottle converting back to normal bottle when empty

### ISSUE THREAD

**Issue by Scotterrr** [TeamLapen/Vampirism#1151]
### Minecraft Version

1.19.x

### Forge Version

1.19.2 - 43.1.52

### Vampirism Version

Vampirism-1.19.2-1.9.0-beta.3

### Modpack

NA

### Singleplayer/Multiplayer

Server

### What happened?

Hi,

I'm having a problem on my server. Every time I or someone else drinks a blood bottle empty it automatically converts back to a normal bottle.
I am unable to use this normal bottles to extract blood from blood containers, only if I spawn in a blood bottle I can extract.

So without spawning in the blood bottles I can't seem to fill them at my blood containers.

Am I missing something or is there another way to create blood bottles (not that I could find.)
Thanks in advance!

Kind regards,
Scott

### Reproduce steps

1. Drink villager/animal
2. Converts to blood bottle
3. Empties blood bottle into altar
4. Converts to normal bottle
5. Can't use normal bottle at blood container

**Comment by Scotterrr** [comment]
![image](https://user-images.githubusercontent.com/37208556/201986702-165d95b5-b39e-49fc-828d-720655427a80.png)
FYI this is my mod list

**Comment by maxanier** [comment]
This is mostly intended behavior. They should revert back. However, once you right-click a blood tank they should be converted to blood bottles once again.

I will double-check if this works with just Vampirism.

In the meantime you can disable the config option `autoConvertGlassBottles` in the common config file of Vampirism

**Comment by Scotterrr** [comment]
Thank you for the reply, I found the config!
