### ISSUE TITLE
[Bug]: Aggressive mobs are not attacking players

### ISSUE THREAD

**Issue by AbraaoLion** [TeamLapen/Vampirism#1152]
### Minecraft Version

1.16.x

### Forge Version

36.2.39

### Vampirism Version

1.8.11-1.9.0

### Singleplayer/Multiplayer

Both

### What happened?

I'm using a translator so my English won't be good
I have a modpack of at least 170 mods and I noticed something that mobs from other mods are passive even though these players are not vampires. I removed the vampirism from the modpack and the mobs became aggressive again. I tested the mods in question only with vampirism and the mobs were passive again. So conclude that the problem was the vampirism mod. I wanted to know if there is a way to somehow disable passive zombies from vampirism, as I think this would already solve my problem.
Mods I tested: ''specialmobs'',''mobz reborn'' and ''dungeon mobs.''

### Reproduce steps

1.Open the world with the vampirism mod and the mod in question
2.Take a mob egg(undead mob) from the mod in question and summon it
3.And he will be passive even if you are not a vampire

### Other relevant mods

dungeons_mobs-1.16.5-1.0.10
MobZReborn-3.0.1
specialmobs-1.16.5-1.0.2

**Comment by AbraaoLion** [comment]
If you can just tell me if there is any way to disable passive zombies

**Comment by Cheaterpaul** [comment]
For the time being you can set the `zombieIgnoreVampire` value in the balance config to false
