### ISSUE TITLE
[Bug]: Only half of vampire clothing showing

### ISSUE THREAD

**Issue by Scotterrr** [TeamLapen/Vampirism#1153]
### Minecraft Version

1.19.x

### Forge Version

43.1.52

### Vampirism Version

1.9.0-beta.3

### Singleplayer/Multiplayer

Server

### What happened?

When wearing the vampire pants and boots only one side is showing on my character. Its even happening on a clean install with only the required files, also happened when I tested it with Vampirism 18.2.

Thanks in advance!

Below is a screenshot:
![image](https://user-images.githubusercontent.com/37208556/202783259-cba08164-3acf-4d1b-9048-faec507dd3f2.png)

### Reproduce steps

1. Craft clothing
2. Put it on
3. Only one side appearing, also for other players

**Comment by Scotterrr** [comment]
FYI Also in single player

![image](https://user-images.githubusercontent.com/37208556/202783496-8eae0b34-8b25-4848-8717-94aed189ca6c.png)

**Comment by maxanier** [comment]
Thank you for reporting. Will be fixed in next version
