### ISSUE TITLE
[Bug]: Vampire Representative quests disappearing

### ISSUE THREAD

**Issue by JetyWawoo** [TeamLapen/Vampirism#1154]
### Minecraft Version

1.19.x

### Forge Version

43.1.52

### Vampirism Version

1.9.0-beta.3

### Singleplayer/Multiplayer

Both

### What happened?

I accepted a "Path to Oblivion" quest, I teleported via waystone to get back home and gathers the materials, and came back after some time also via waystone and the quest was no longer in his quests list and he tried offering me new quests, even though in the Vampirism menu it said that I had completed the quest.

The same thing happened later with a "Break their bones" quest, I completed it, teleported back via waystone, and the representative tried offering me new quests instead.

### Relevant log output

[debug.log](https://github.com/TeamLapen/Vampirism/files/10048151/debug.log)

### Reproduce steps

1. Accept a quest from a Vampire Representative
2.  Teleport away to a place where the chunk is not loaded.
3.  Teleport back after some time

### Other relevant mods

AI Improvements 0.5.2
AttributeFix 17.1.3
Better FPS - Render Distance 1.7
Canary 0.1.3
Connectivity 3.4
Dynamic View 2.9
Entity Collision FPS Fix 2.0.0.0
Entity Culling - 1.5.2
Farsight 2.1
ForgetMeChunk 0.0.1
FPS Reducer 2.1
ItShallNotTick  1.0.11
Limited Chunkloading 2.4
Pluto 0.0.6
Radon 0.8.2
Saturn 0.0.1
Server Performance - Smooth Chunk Save 2.0
Waystones 11.1.0

**Comment by Cheaterpaul** [comment]
Are you sure that it is the same representative? It is most likely that your old representative was killed and a new one spawned.

**Comment by JetyWawoo** [comment]
Yes, it seems that my village has two representatives and two vampire experts.
