### ISSUE TITLE
[Modcompat]: Optifine Light and Shadow Configuration?

### ISSUE THREAD

**Issue by xiaoxin-zk** [TeamLapen/Vampirism#1156]
### Minecraft Version

1.19.x

### Forge Version

43.1.55

### Vampirism Version

1855

### Incompatible mod

optifine

### Singleplayer/Multiplayer

Singleplayer

### What happened?

Enable light and shadow map scrambling

### Reproduce steps

1.19.2 The configuration file cannot be modified in the game. How can I modify it if I want to use light and shadow?

**Comment by Cheaterpaul** [comment]
What configuration files do you want to modify. Vampirism has no light and shadow feature.

Vampirism's configuration files can be edited in the respective files in the filesystem.

And what Vampirism version are you using?
