### ISSUE TITLE
[Modcompat]: Crash with Emojiful upon sleeping in coffins

### ISSUE THREAD

**Issue by Gronglegrowth** [TeamLapen/Vampirism#1157]
### Minecraft Version

1.19.x

### Forge Version

43.1.57

### Vampirism Version

1.9.0 beta 3

### Incompatible mod

Emojiful 4.0.3

### Singleplayer/Multiplayer

Singleplayer

### What happened?

When sleeping in a coffin, the game instantly freezes then crashes, I suspect this is on Emojiful's side, I reported it to them as well - https://github.com/InnovativeOnlineIndustries/Emojiful/issues/63

### Reproduce steps

1. Place down a coffin with Emojiful loaded
2. Sleep in it
3. Observe crash

### Relevant log output

```shell
The following links contain both crashlogs that were produced
https://github.com/InnovativeOnlineIndustries/Emojiful/files/10114972/crash-2022-11-29_11.18.50-client.txt
https://github.com/InnovativeOnlineIndustries/Emojiful/files/10114974/crash-2022-11-29_11.18.38-server.txt
```

**Comment by maxanier** [comment]
Todo:
https://github.com/TeamLapen/Vampirism/blob/4370ca18a1b32aae263aa202069e09c6e60cc93d/src/main/java/de/teamlapen/vampirism/proxy/ClientProxy.java#L160

Either only replace exact class instance or move to NewScreen event

**Comment by maxanier** [comment]
Please try the new 1.9.0 release. It should hopefully resolve this issue.

**Comment by Gronglegrowth** [comment]
1.9.0 does fix it.
