### ISSUE TITLE
Leveling Up is to easy

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#116]
To slow down the level up progress the following could be implemented:
+Require items from the end
+Require books that can be found in the world
+Other things, suggestions?

**Comment by maxanier** [comment]
More or less fixed for now in 63e3b8cb3587a036024d5bdfab3cc85fe88d83f5
Going to wait for the poll result about end items before closing this

**Comment by tech-boy101** [comment]
if wann make it take some time where you can do this is to not make the builds but make like rpg level thing so more you feed the more exp you get and more exp you get the more level you get do understand what im say in

**Comment by maxanier** [comment]
Yeah, requiring "Experience Points" that are collected by sucking blood, respectively killing vampires, is a good idea. But I'm not really sure if that isn't to much "RPG style" or not, so I won't implement something like that for now. Maybe later

**Comment by tech-boy101** [comment]
if make not to rpg style you make where at ever end of get exp be for you level up you need kill boss like vampire lord this be both for vampire and hunters

**Comment by maxanier** [comment]
The poll on the Minecraft Forum suggests to add a some kind of requirement to go to the end to reach max level.
But I think that would require adding some kind of boss or world gen to make it fit. 
Since leveling up got a little bit harder, because you need vampire books now, I will put this back a little bit.

**Comment by maxanier** [comment]
After adding the vampire books as level up requirement, it seems to be hard respectively time consuming enough to level up. So closing this issue for now.
