### ISSUE TITLE
[Feature]: Show sunscreen buff on screen at all times

### ISSUE THREAD

**Issue by MarioSMB** [TeamLapen/Vampirism#1161]
### What?

Currently you have to open the skill selector or your inventory to see when the sunscreen buff is going to run out, which can put you at a great risk of dying.  
It would be nice if the sunscreen buff always showed on screen like weakness and other buffs, thanks!

**Comment by maxanier** [comment]
For some reason we actively decided against showing it, but I do not know why.
Will change.
Note to self: https://github.com/TeamLapen/Vampirism/blob/f2a22f9365be9a37c38cbe03d4e812e571653b06/src/main/java/de/teamlapen/vampirism/entity/player/vampire/actions/SunscreenVampireAction.java#L17

**Comment by maxanier** [comment]
In Vampirism 1.9 you have small icons on screen that show you the active actions and their remaining duration. In think this should solve your issue
