### ISSUE TITLE
[Bug]: Server Issue Report : Action config For Players 

### ISSUE THREAD

**Issue by FuenteMiracles** [TeamLapen/Vampirism#1162]
### Minecraft Version

1.16.x

### Forge Version

36.2.39

### Vampirism Version

1.8.3

### Modpack

n/a

### Singleplayer/Multiplayer

Server

### What happened?

So, Recently I Could not find the Configuration for the server to prevent players in to bat in only the End dimension for the default setting, Me and my friend hosting Exaroton Server Trying vampirism but Once my friend Reach Level 4 and Upgraded to Turning in to bat it's Just Not working with These When I tried my self (As operator) it turn me into a bat Normally but not for a normal player

![image](https://user-images.githubusercontent.com/120737723/208135908-875114aa-1198-424c-9132-73c2151af9b3.png)

if I am missing Something that has been written I do Apology 

If there any Change Or reply Would you Kindly Sending us a Solution

Long599long@gmail.com

Thank you

### Relevant log output

```shell
n/a
```

### Reproduce steps

n/a

### Other relevant mods

n/a

**Comment by maxanier** [comment]
Are you using a permission plugin? Maybe something went wrong there. Give you players all Vampirism permissions again: https://wiki.vampirism.dev/docs/wiki/permissions

If that does not help: Make sure to a) be in the overworld, b) be in an area without any sunlight
