### ISSUE TITLE
[Bug]: No option to turn off Night Vision and Blood Vision

### ISSUE THREAD

**Issue by MarioSMB** [TeamLapen/Vampirism#1163]
### Minecraft Version

1.19.x

### Forge Version

43.2.0

### Vampirism Version

1.9.0

### Singleplayer/Multiplayer

Both

### What happened?

Most vampire skills can be turned off in the vampirism-balance.toml configuration, however no such option exists for blood vision and night vision currently.

**Comment by ghost** [comment]
Night vision and blood vision can be toggled in game with a keybind. So it doesn’t make much sense to have that in the vampirism-balance, unless you want vampires to not have these abilities for some reason

**Comment by MarioSMB** [comment]
Indeed, it seems to be possible to enable/disable most vampire skills, I'd like to be able to control these two as well.

**Comment by maxanier** [comment]
Vampire actions work differently from the night and blood vision. That's why they do not "automatically" have a config option atm. 
We can add one though. Instead of activating it will probably send a message like "disabled by server admin"

**Comment by MarioSMB** [comment]
Saw that this was resolved, thanks!
