### ISSUE TITLE
[Bug]: Problems with village raids

### ISSUE THREAD

**Issue by BioWolf1221** [TeamLapen/Vampirism#1164]
### Minecraft Version

1.18.x

### Forge Version

40.1.86

### Vampirism Version

1.8.8

### Singleplayer/Multiplayer

Server

### What happened?

I'm running a modded server, the modpack I made is linked.

So I'm a vampire trying to run a vampire village (Note that I also have Minecraft Comes Alive Reborn installed), but the problem is that everytime I load in it says that a hunter raid is currently underway. I run to the bell to see the intruders and it highlights all of my villagers. This has happened twice now. Even the vampire villagers have to die before it'll end. Also, during the raid all of my villagers attempt to kill me as well (unsure if this is normal or not, this also happens during normal raids but they calm down after the attackers have been killed). I should also mention that this didn't use to happen (especially not when the village was under the control of different factions) and that this village is within the spawn chunks. The first time I just thought it was a raid that started while I was gone, but the second time was just after a server restart so that doesn't seem likely. I am still able to talk and trade with villagers (if I right click before they land their first hit). Anyone know what's going on? EDIT: Ok now anytime I have a raid I have to kill all my villagers. Please help.
[New RPG.zip](https://github.com/TeamLapen/Vampirism/files/10297923/New.RPG.zip)

### Other relevant mods

MCA Reborn 7.3.21

**Comment by Cheaterpaul** [comment]
Yes it is not ideal that, in a hunter raid, you need to kill all vampire villager, but that the current way it works.

Additionally it is possible for a raid to be triggered randomly.

Feel free to reopen the issue
