### ISSUE TITLE
[Feature] Revamp Bat mode

### ISSUE THREAD

**Issue by Cheaterpaul** [TeamLapen/Vampirism#1166]
Currently the bad mode feels to much as creative flight. The following suggests turning the bat mode into in more interactive flying mode with new limitations.

## Fly mechanism
The new goal is to require the user to constantly interact the the game to keep the bat flying.

The bat is no longer immune to gravity, the user is required to repeatedly press the jump button to keep their y position, hold the jump button to ascent or stop pressing the button to drop down. (This should work like jetpacks from other mods)

An addition, a modification or a replacement to this fly mechanism is to introduce a slow decending mode as long as the jump button is not pressed.

## Action properties

Besides the direct flying mechanism I suggest following general changes to balance the action
### Vertical flying

The bat mode should no longer allow users to ascend to every height they want.
Players should only be able to fly to a maximum height. To keep is real and balanced I suggest setting the limit to the surface level + `<amount>` blocks

### Horizontal flying
To limit the long distance travel of bats the horizontal flying capabilities of bats should be limited. After some time they should lower their flying speed to suggest a landing or slowly reduce the upwards speed to force the player to the ground

**Comment by maxanier** [comment]
Some experiments will be necessary.

@MarioSMB what are your thoughts?

**Comment by supermike1999** [comment]
I don’t think a cap for how high a bat can fly should be needed since some bats irl can fly thousands of feet in the air. And for flight distance, kind of hard to determine how long a vampire bat can go, perhaps increase blood drain over a period of time as bat so your forced to land? (But I think there’s something like that already added?).

**Comment by maxanier** [comment]
Closing this in favor of #1160 which we missed before, sorry.
