### ISSUE TITLE
[Modcompat]: Farmer's Delight nourishment buff

### ISSUE THREAD

**Issue by MarioSMB** [TeamLapen/Vampirism#1167]
### Minecraft Version

1.18.x

### Forge Version

40.1.86

### Vampirism Version

1.9.0

### Incompatible mod

farmersdelight 1.2.0

### Singleplayer/Multiplayer

Both

### What happened?

There is a design conflict with Farmer's Delight and its Nourishment buff which is obtained by eating high-tier foods.  
I've reported this problem to their team and they concluded that it may be possible to fix it on Vampirism's end: https://github.com/vectorwing/FarmersDelight/issues/604

### Reproduce steps

1. Load a world with Farmer's Delight installed https://www.curseforge.com/minecraft/mc-mods/farmers-delight
2. Become a vampire (any level)
3. Consume one of the food items with the "Nourishing" tooltip

**Comment by Cheaterpaul** [comment]
Fixed in Farmer's Delight
