### ISSUE TITLE
[Bug]: Bat insta death + Can't infect

### ISSUE THREAD

**Issue by CriceEnelace** [TeamLapen/Vampirism#1168]
### Minecraft Version

1.16.x

### Forge Version

36.2.2

### Vampirism Version

1.9

### Singleplayer/Multiplayer

Server

### What happened?

When u morf from bat into human and get even 1 damage u insta kill (i mean go in "fallen" mode). (Old bug, discovered even before 1.8, but i not report this)
Ability "Infect" not work. And even if i idiot, and just not correctly do this, but on players that not work. We tested.

### Reproduce steps

Bat insta kill:
1. Become vampire lvl 4
2. Morf into bat
3. Fly 5 blocks high
4. Morf into human

**Comment by maxanier** [comment]
The infect action is a bit broken, currently it sometimes only allows infection creatures from the front.
I have fixed this: In the next version you must be behind players and villagers to infect them.

Regarding the bat problem. I cannot reproduce this with just Vampirism. Please open a separate issue if you either can reproduce this with just Vampirism or if you can narrow down the mod that is causing this

**Comment by DeityLamb** [comment]
I have the same problem with instant death after morf
It seems to be related to using the Catserver core
`(I tested it with fresh Catserver + Vampirism mod only)`

I don't think it's an issue with the Vampirism mod,
just wanted to add this for anyone who encounters the same problem
