### ISSUE TITLE
[Bug]: Unable to sleep during the day

### ISSUE THREAD

**Issue by ghost** [TeamLapen/Vampirism#1169]
### Minecraft Version

1.19.x

### Forge Version

4.3.2.3

### Vampirism Version

Vampirism-1.19.2-1.9.0

### Singleplayer/Multiplayer

Singleplayer

### What happened?

Unable to sleep during the day
https://imgloc.com/i/CjIvb

**Comment by FanRenLa** [comment]
Sorry for the wrong feedback
