### ISSUE TITLE
[Bug]: Default Capability implementation is initialized

### ISSUE THREAD

**Issue by william7733** [TeamLapen/Vampirism#1172]
### Minecraft Version

1.16.x

### Forge Version

36.2.39

### Vampirism Version

1.9.0

### Singleplayer/Multiplayer

Server

### What happened?

having these messages spammed in server log

[Server] Server thread/ERROR [de.te.va.en.fa.FactionPlayerHandlerDefaultImpl/]: Created Default Implementation. THIS SHOULD NOT BE DONE. The default impl does absolutely nothing

[Server] Server thread/ERROR [de.te.va.pl.va.VampirePlayerDefaultImpl/]: Created Default Implementation. THIS SHOULD NOT BE DONE. The default impl does absolutely nothing

[Server] Server thread/ERROR [de.te.va.pl.hu.HunterPlayerDefaultImpl/]: Created Default Implementation. THIS SHOULD NOT BE DONE. The default impl does absolutely nothing

### Reproduce steps

1) log into server
spam only happens when player(s) are connected to server

**Comment by Cheaterpaul** [comment]
As the message suggests this is an error which can cause more errors or crashes down the line.

I have not seen this type of error.

May you share your servers whole `debug.log`, so we can see if it gives any clue what might cause this?

**Comment by william7733** [comment]
![Screenshot (44)](https://user-images.githubusercontent.com/90850721/213858336-a567824e-35ea-434b-887f-759eb6edddff.png)
![Screenshot (45)](https://user-images.githubusercontent.com/90850721/213858340-5424c260-559c-4d9e-8f11-4556d557b36d.png)

**Comment by william7733** [comment]
i will find the debug.log and share it

**Comment by william7733** [comment]
[debug.log](https://github.com/TeamLapen/Vampirism/files/10471764/debug.log)

**Comment by maxanier** [comment]
Thank you for sharing the debug log. Unfortunately, I haven't been able to find the reason for this.
If you are still playing with Vampirism and still experiencing this issue, please download the latest version and upload a log again. I have added some debugging utility that hopefully should allow us to pinpoint the cause of this
