### ISSUE TITLE
[Bug]: abilities not working 

### ISSUE THREAD

**Issue by Ruslanllll** [TeamLapen/Vampirism#1175]
### Minecraft Version

1.16.x

### Forge Version

36.2.39

### Vampirism Version

1.9.1

### Singleplayer/Multiplayer

Server

### What happened?

Abilities not working 

### Other relevant mods

Server core Mohist

Mods:
Blockysiege
Chipped
Extractures
Furnish
IndustrialRenewal
lostcities
Obfuscate
tac
AtlasLib
Ballistix
Electrodynamics
Farmers delignt
Nuclear science
The Hordes
Curios
GeckoLib
Mana and artiface
SpecialTools
Werewolves
CraftTweaker
JeiTweaker
Plugins:
EssentialsX
LuckPerms
AuthMe

**Comment by supermike1999** [comment]
Do you happen to get something similar to this when loading into your world? 
![C24EE0B6-310B-49A5-A3D5-5CEFD710F620](https://user-images.githubusercontent.com/106882130/214514964-f2147d6f-41b1-44ab-bd51-106f34dd175e.jpeg)

**Comment by Ruslanllll** [comment]
> Do you happen to get something similar to this when loading into your world? ![C24EE0B6-310B-49A5-A3D5-5CEFD710F620](https://user-images.githubusercontent.com/106882130/214514964-f2147d6f-41b1-44ab-bd51-106f34dd175e.jpeg)

Yes, i getting

**Comment by Ruslanllll** [comment]
But if I give a Vampirism.* permission node, people can increase their level(/vampirism level)?

**Comment by Ruslanllll** [comment]
Oh... I understood 
I am stupid
