### ISSUE TITLE
[Bug]: Blessing salt water with the off-hand crashes the server

### ISSUE THREAD

**Issue by lunofe** [TeamLapen/Vampirism#1182]
### Minecraft Version

1.16.x

### Forge Version

36.2.39

### Vampirism Version

1.9.1

### Modpack

Vampirism.co

### Singleplayer/Multiplayer

Server

### What happened?

[Screencast from 2023-02-19 12-46-39.webm](https://user-images.githubusercontent.com/42828197/219946023-3a5d4c0c-ca12-4e95-8363-8411ff97b285.webm)

### Relevant log output

This is the full crash-report of Vampirism.co (Mohist): https://mclo.gs/mtzjoiX

When reproducing the issue with a regular Forge server and just Vampirism as shown in the video, the log states that a crash report is being created, but the server doesn't actually crash or create the file: https://mclo.gs/htZCJNj

### Reproduce steps

This does not seem to affect singleplayer worlds.
Set up a Forge 36.2.39 client & server with Vampirism, join the server and become a hunter. Put a bottle of salt water in your off-hand and hold right-click at an altar of cleansing.

**Comment by Cheaterpaul** [comment]
no relevant for MC 1.19
