### ISSUE TITLE
[Bug]: Some multi-block structures enable duping in combination with claims

### ISSUE THREAD

**Issue by lunofe** [TeamLapen/Vampirism#1184]
### Minecraft Version

1.16.x

### Forge Version

36.2.39

### Vampirism Version

1.9.2

### Modpack

Vampirism.co

### Singleplayer/Multiplayer

Server

### What happened?

[Screencast from 2023-02-26 00-44-10.webm](https://user-images.githubusercontent.com/42828197/221384768-b266978b-1143-42f5-a44d-83872a1a4c63.webm)

Weirdly enough, these were the only blocks I could find that can be used for this. Tents, coffins, etc. don't cause the chest to break. The tent doesn't even trigger GP's claim warning, probably because it checks for enough space even before placing the first block?

### Reproduce steps

- create a claim, place a chest with items in the air
- /transferclaim to another player
- place a cross or throne below the chest
- profit!

### Other relevant mods

[Grief Prevention](https://beta.curseforge.com/minecraft/bukkit-plugins/grief-prevention/files/3173411)

**Comment by supermike1999** [comment]
i will add that the cross/throne can break any unbreakable block as well
