### ISSUE TITLE
Can't See Effects

### ISSUE THREAD

**Issue by HyperStryk** [TeamLapen/Vampirism#1185]
### Minecraft Version

1.19.2

### Forge Version

1.19.2

### Vampirism Version

1.19.2

### Singleplayer/Multiplayer

Server

### What happened?

I can't see my blood projectiles or other effects as a vampire

**Comment by lunofe** [comment]
@HyperStryk Please edit your bug report and fill in the required information. "1.19.2" is not a valid version for Vampirism and Forge.

**Comment by Cheaterpaul** [comment]
Feel free to reopen the issue, if this bug is still present
