### ISSUE TITLE
[1.10.2] Too many Hunters

### ISSUE THREAD

**Issue by UnstableCodeScarlet** [TeamLapen/Vampirism#119]
Could a config be added to control Hunter Camp Spawn rate? I can't tell if RTG is messing with the mod, or if the spawn rates are really this stupidly high, But it's annoying none the less.

**Comment by UnstableCodeScarlet** [comment]
Ah, I'm an idiot, I didn't notice the folder inside the folder.
What a weird setup.

**Comment by maxanier** [comment]
I decide to use an extra folder for the balance configuration, because they can/should be reset after every update.
