### ISSUE TITLE
[Modcompat]: 1.18.2 Mobs not Spawning

### ISSUE THREAD

**Issue by Kaiokengodx1000** [TeamLapen/Vampirism#1190]
### Minecraft Version

1.18.x

### Forge Version

20.2.0

### Vampirism Version

1.8.8

### Incompatible mod

Terralith 2.2.3

### Singleplayer/Multiplayer

Server

### What happened?

Me and my friends had a vampirism/create modpack made for us, However upon playing we find that vampires and werewolves are not spawning as they should and are ultra rare.

### Reproduce steps

1. Loaded the server
2. Just played the game as intended
3. failure to find any vampirism mob but hunters.

**Comment by Kaiokengodx1000** [comment]
and before asking, We are checking the vanilla biomes for said mobs, we even found a vampire forest and didnt find more than 1 vampire. I checked all the configs and the rates are set to the default (all except the hunters)

**Comment by Jackiecrazy** [comment]
use tellme or spawn balance utility to check if some mod is inserting themselves into a lot of spawn tables. The pool may be diluted by such insertions.

**Comment by Kaiokengodx1000** [comment]
we did manage to fix it, due to a terrain mod I had to set hunters to spawn naturally, I set there spawn rate to what the configs told me too but that was apparently too high, and didnt let any other mobs spawn. So I had to turn it down 5 instead of the 75 the config had told me. they seem to all spawn fine now.
