### ISSUE TITLE
[Bug]: Can`t get a Priest

### ISSUE THREAD

**Issue by bakuzan16** [TeamLapen/Vampirism#1193]
### Minecraft Version

1.19.2

### Forge Version

43.2.8

### Vampirism Version

1.9.3

### Singleplayer/Multiplayer

Singleplayer

### What happened?

I can`t get a single priest villager. Villagers just ignore the altar of cleansing. I am running modpack made by me, but I don`t have any villager changing mods. Just Enough Professions see this type of villager and say that altar of cleansing is a workplace, but I still can`t get one, no matter how hard I tried. Before writing this I tried it on superflat world, but still nothing (Screenshot attached).
P. S. Sorry for my bad english

![Mods](https://user-images.githubusercontent.com/121336237/229269653-18aca3c9-b049-475f-88e0-fbcbb8c9cd40.jpg)
![2023-04-01_09 30 37](https://user-images.githubusercontent.com/121336237/229269789-9ade8cf7-aacb-4ca9-a587-646de9403678.png)

### Reproduce steps

1. Create singleplayer superflat creative world
2. Load this world
3. Spawn some villagers
4. Place some altars of cleansing

**Comment by bakuzan16** [comment]
I'm glad to see that developers have read my bug report and made some changes in code. I'm here because I noticed one other bug, but don't want to create new bug repord. Seems like on this line of code  
https://github.com/TeamLapen/Vampirism/blob/53b52f222c0c7da8de517c52134c23319ae86188/src/main/java/de/teamlapen/vampirism/core/ModVillage.java#L118 trade, where you give 25 pure salt water and recieve 1 emerald, but it don`t work so because pure salt water do not stack. Also it is takes a lot of time to make from non-stackable pure salt water holy water. I think this problem is not difficult to solve editing code there  
https://github.com/TeamLapen/Vampirism/blob/53b52f222c0c7da8de517c52134c23319ae86188/src/main/java/de/teamlapen/vampirism/core/ModItems.java#L95 , but i thing it will affect some other aspects of game.

P.S If developers don`t notice this I will create a new bug report.

**Comment by Cheaterpaul** [comment]
Then we will remove the trade
