### ISSUE TITLE
[Bug]: can't drink blood from blood container 

### ISSUE THREAD

**Issue by burrito-brine** [TeamLapen/Vampirism#1199]
### Minecraft Version

1.19.2

### Forge Version

43.2.0

### Vampirism Version

1.9.4

### Singleplayer/Multiplayer

Singleplayer

### What happened?

i can't drink the blood from the container i have the grinder on top of the container 

do i have to put the grinder on top of the blood sieve and the blood container on the bottom?

**Comment by Cheaterpaul** [comment]
the grinder only produces impure blood which first must be sieved to become drinkable blood.
Simply put a sieve below the grinder and a blood container below the sieve. Or you can put the container with impure blood above the sieve.
