### ISSUE TITLE
[Bug]: Permissions dont work with luckperms plugin/mod

### ISSUE THREAD

**Issue by ferjaisarg** [TeamLapen/Vampirism#1201]
### Minecraft Version

1.18.x

### Forge Version

40.1.80

### Vampirism Version

1.8.8

### Singleplayer/Multiplayer

Server

### What happened?

I assigned the permission for each rank and not work
Player cant use batmode or other skills

**Comment by Cheaterpaul** [comment]
Vampirism only uses the permission system which Forge provides. This is the first time I hear that the permission do not work, which brings me to the conclusion that you did not configure them correctly.

I can only refer you to the official wiki of luckperms to reconfigure them https://luckperms.net/wiki/Home

**Comment by Cheaterpaul** [comment]
Feel free to reopen the issue if you have configured the permissions correctly but it still does not work
