### ISSUE TITLE
vampire can eat human food

### ISSUE THREAD

**Issue by MuzanAwnKingerGyuu** [TeamLapen/Vampirism#1203]
### What?

how do you make the vampire be able to have their normal hunger bar back, not needing blood or heart to survive?

**Comment by Cheaterpaul** [comment]
Vampires only gain nutrition from blood. This can not be disabled.
If you want to eat other food you should not become a vampire.

If you have other questions, make sure to check out our discord server https://discord.gg/wuamm4P

**Comment by MuzanAwnKingerGyuu** [comment]
ah, thank you
