### ISSUE TITLE
i can't find the vampire expert

### ISSUE THREAD

**Issue by burrito-brine** [TeamLapen/Vampirism#1204]
### Minecraft Version

1.19.2

### Forge Version

43.2.0

### Vampirism Version

1.9.4

### Singleplayer/Multiplayer

Singleplayer

### What happened?

i can't find the vampire expert and the hunter expert to get the ultimate versions of the items

**Comment by wolf653** [comment]
Did you try any commands like _/effect give @e minecraft:glowing 60_ in a village claimed by the faction?

**Comment by burrito-brine** [comment]
i don't know what thats is supposed to do?

**Comment by wolf653** [comment]
It applies the glowing effect to every mob in the loaded chunks, the same effect from spectral arrows, makes them have a glowing outline so they are easier to find. in case the expert did actually spawn in.

**Comment by Cheaterpaul** [comment]
The vampire expert is a normal villager professions, which need the totem as work station in a vampiire village

**Comment by maxanier** [comment]
Can you confirm that you are in a vampire village and there are sufficient unemployed villagers?
