### ISSUE TITLE
[Bug]: hiya, hum... the  game wont load the map

### ISSUE THREAD

**Issue by PHVMASTER** [TeamLapen/Vampirism#1207]
### Minecraft Version

1.16.x

### Forge Version

36.2.39

### Vampirism Version

1.9.2+03

### Singleplayer/Multiplayer

Singleplayer

### What happened?

hey, i have had two  problems, one i already solved myself it was rubidiun mod and resse's mod prob, but now i have a diferent one this time, after deleting resse's mod (aka textrubidiumoptions) and re installing the rubidiun mod, i got to enter in the game, but im having a problem, the game is stuck in this screen
![image](https://user-images.githubusercontent.com/132164840/235320314-2140639d-ffc0-4b4b-9006-175548b58f47.png)
the game is in portuguese so the text is saying "saving your world", but it just doesn't get out of that page, i have left the game open for more than 45 minutes and it is still in that part
when i press the buttom to close it, it doesn't, i have to use tast manager to close it

### Reproduce steps

1°- delete resse's mod (aka textrubidiumoptions)
2°- install the version 1.16.5 of Rubidium
3°- Load the game
4°- Enter/Create a world
5°- See it happening

**Comment by lunofe** [comment]
It seems like you're talking about the Vampirism.co modpack, not the Vampirism mod itself. Open a support ticket on this [Discord](https://discord.gg/rP8j7hA).
