### ISSUE TITLE
[Bug]: Village totems stop chunk loading and freeze mobs within a certain radius

### ISSUE THREAD

**Issue by HikenMC** [TeamLapen/Vampirism#1208]
### Minecraft Version

1.19.2

### Forge Version

43.2.8

### Vampirism Version

1.9.4

### Modpack

https://drive.google.com/file/d/1VnxIexLFLTKvd3HxE8jBVId0hS5uNBWR/view?usp=sharing

### Singleplayer/Multiplayer

Server

### What happened?

I am playing on an Aternos server with my friend and whenever we go to a village, the chunks stop loading. Any and every entity in a certain chunk radius of the totem freezes. Corpses of mobs won't disappear and items can't be picked up. Even my dog who entered the radius together with me froze and can't be rescued anymore. Players are fine and blocks can still be updated/placed/broken. I have read a bug report that was back in 2020 on 1.14.4 which had a similar issue and was supposedly resolved after a new beta had been released, but we still have that problem now. On my single-player world for 1.19.3 this issue doesn't exist (granted I use a different modpack with Vampirism version 1.9.1.)

### Reproduce steps

1. Walk into render distance of a village totem

**Comment by maxanier** [comment]
Is it possible to download the world from the server and load it in Singleplayer?
Also is there anything printed in the server console when you get close to the village?
