### ISSUE TITLE
[1.10.2][Forge 2081]Crash with Zoology

### ISSUE THREAD

**Issue by Hastling** [TeamLapen/Vampirism#121]
http://pastebin.com/pHmcVqw8

**Comment by maxanier** [comment]
This issue was occurring if you already have a converted creature in your world and then install Zoology.
I implemented a workaround, it makes all converted creatures, which were spawned before installing Zoology, disappear, but that should not be too big a deal.

**Comment by Hastling** [comment]
I've had Zoology installed since 7/2 and only added Vampirism last week, so I guess what I'm saying is that I'm concerned this will happen again, but don't worry I'll be sure to open up another issue report if it does.

**Comment by maxanier** [comment]
Ok, I did not test the other way.
But this exact issue cannot appear again, the only thing that could happen is that converted creatures disappear (or you are not able to convert any creatures). If that happens please create a new issue.
