### ISSUE TITLE
[Bug]: Inventory contents voided when sorting inventory with specific stacks of blood bottles held

### ISSUE THREAD

**Issue by Gronglegrowth** [TeamLapen/Vampirism#1216]
### Minecraft Version

1.19.2

### Forge Version

43.2.13

### Vampirism Version

1.9.4

### Singleplayer/Multiplayer

Singleplayer

### What happened?

When sorting the inventory with Quark's inventory sort button, and a blood bottle stack that has a count of higher than 1 (ex. when you buy them from vampire villagers and shift-click the stack to your inventory), most of the inventory contents will be deleted.

Other methods of inventory sorting may also trigger it, haven't tried.

### Reproduce steps

1. Load a world
2. Obtain multiple blood bottles in one stack - easiest way is to trade for them from a villager
3. Fill your inventory with whatever contents
4. Sort the inventory

### Other relevant mods

Quark, 3.4-402

**Comment by Cheaterpaul** [comment]
Blood bottles are not stackable by default. But the villager trade awards a stack with multiple bottles. I assume Quark checks the maximum stack size and removed any items that do not match their maximum size.

Will be fixed in newer versions
