### ISSUE TITLE
[Bug]: Server players can only use actions when being op-ed

### ISSUE THREAD

**Issue by fercarft7** [TeamLapen/Vampirism#1217]
### Minecraft Version

1.16.x

### Forge Version

36.2.39

### Vampirism Version

1.9.8

### Modpack

https://drive.google.com/file/d/1ktKFPT9fDqEGQIx2rvjUUjG4juTX14Ot/view?usp=sharing

### Singleplayer/Multiplayer

Server

### What happened?

When people who are not op in my server try to do a vampire skill, such as transforming into a bat or using the regeneration ability, an error appears. It says: "You do not have the permission to do this action". However, when I give them op they can use the abilities. Is there any chance to fix this without giving them op?

Thank you.

**Comment by supermike1999** [comment]
Hi there. To fix this issue, i recommend installing a permission plugin (Luckperms). This will fix the issue of giving players players op to use the skills.

**Comment by Cheaterpaul** [comment]
Take a look at https://wiki.vampirism.dev/docs/wiki/permissions#permission-problems for more details
