### ISSUE TITLE
[Modcompat]: Modify instead of replace target goals

### ISSUE THREAD

**Issue by ForestLive6** [TeamLapen/Vampirism#1221]
### Minecraft Version

1.16.x

### Forge Version

36.2.39

### Vampirism Version

1.9.8

### Incompatible mod

Goal Optimizer  goaloptimizer-1.16.5-1.0.3.jar

### Singleplayer/Multiplayer

Both

### What happened?

Hello, I use Goal Optimizer mod, but it is not compatible with your mod, which may cause lag in the game. Read more in the link where the author Goal Optimizer mod explains what the problem is. https://github.com/MCTeamPotato/GoalOptimizer/issues/2 

### Reproduce steps

Install two mods.

### Relevant log output

```shell
https://github.com/MCTeamPotato/GoalOptimizer/issues/2
```

**Comment by Cheaterpaul** [comment]
Instead of removing and adding a goal we just modify the predicate of the target goal

**Comment by maxanier** [comment]
@Cheaterpaul If you are certain that this solution does not cause new problems, we may want to port it to stable versions as well. I have added it to the version management. Did we decide on 1.19.2 vs 1.19.4 yet?
