### ISSUE TITLE
[Bug]: Crash entering the Nether

### ISSUE THREAD

**Issue by CloWnicide** [TeamLapen/Vampirism#1222]
### Minecraft Version

1.20.1

### Forge Version

47.0.34

### Vampirism Version

1.20.1-1.9.1-alpha+20230621-1954

### Singleplayer/Multiplayer

Singleplayer

### What happened?

While attempting to enter the Nether, the game will load, but then will cause immediate hang-up. Removing Vampirism fixes the issue.

### Relevant log output

```shell
https://gist.github.com/CloWnicide/69d34778e5553d0b1f7155a5b9606478
```

### Reproduce steps

Load game
Attempt to go through Nether portal
Game lags/hangs up

**Comment by Cheaterpaul** [comment]
Unfortunately the log only says that the game is shutting down, but not why:
`[30Jun2023 14:40:52.458] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Stopping!`

Do you have a crash report for this as well?

**Comment by CloWnicide** [comment]
No, the game just sticks on `waiting on server` and have to force the game to close so it won't produce a crash report or an exit code that's actually useful. Also upon further testing, it also doesn't seem to be entirely Vampirism's fault as the game continues this behavior after loading more chunks.

**Comment by maxanier** [comment]
From your last comment I understand, this is not Vampirism's fault.

In the log you provided there are quite a few other errors as well.

I am closing this issue now. If the problem should still occur and you can confirm that it only occurs with Vampirism installed. Please reopen
