### ISSUE TITLE
[Bug]: I can`t find Vampire Baron and the configuration files that are responsible for his spawn

### ISSUE THREAD

**Issue by oneslaught** [TeamLapen/Vampirism#1223]
### Minecraft Version

1.12.x

### Forge Version

14.23.5.2859

### Vampirism Version

1.6.2

### Singleplayer/Multiplayer

Both

### What happened?

Barons do not spawn in the vampire forest. When I opened the config I saw the vampire and advanced vampire spawn setting which looked like " I:vampire_spawn_chance='num' " and " I:advanced_vampire_spawn_probe='num' " but nothing related to baron spawn I could find, only characteristics responsible for damage and hp. I also have a few mods that I`ll attach to this post

### Reproduce steps

1. Create new world
2. Find a vampire forest
3. Spend three hours in a failed attempt to find the vampire baron

### Other relevant mods

[1.12.2]+SecurityCraft+v1.9.7
Advanced-Fishing-1.12.2-1.3.3
AIImprovements-1.12-0.0.1b3
ancientbeasts-1.9.99999
AoA3-3.3.6
AppleSkin-mc1.12-1.0.14
base-1.12.2-3.14.0
Baubles-1.12-1.5.2
bettercaves-1.12.2-2.0.4
BetterFps-1.4.8
BetterMineshaftsForge-1.12.2-2.2.1
BiblioCraft[v2.4.6][MC1.12.2]
BiomesYouGo1.7.1+Fixes
blue_skies-1.12.2-v1.1.3
Bookshelf-1.12.2-2.3.590
Cavern_1.12.2-v2.3.1
censoredasm5.13
ChestTransporter-1.12.2-2.8.8
ChickenChunks-1.12.2-2.4.2.74-universal
Chunk+Pregenerator-V1.12-2.5.7
Clumps-3.1.2
CodeChickenLib-1.12.2-3.2.3.358-universal
conarm-1.12.2-1.2.5.10
disenchanter[1.12]1.8
DivineRPG-1.7.1
ElectroblobsWizardry-4.3.10
EnchantingPlus-1.12.2-5.0.176
ExtraGolems-1.12-7.1.9
FastLeafDecay-v14
FenceOverhaul-1.3.4
geckolib-forge-1.12.2-3.0.31
GIsCraftableWizardryItems-2.0
grappling_hook_mod-1.12.2-v13
Hwyla-1.8.26-B41_1.12.2
ironchest-1.12.2-7.0.72.847
jei_1.12.2-4.16.1.1003
journeymap-1.12.2-5.7.1
JustEnoughResources-1.12.2-0.9.2.60
mahoutsukai-1.12.2-v1.19.55
Mantle-1.12-1.3.3.55
!mixinbooter-8.3
NaturesCompass-1.12.2-1.8.5
OpenGlider-1.12.1-1.1.0
OptiFine-OptiFine-1.12.2_HD_U_G5
Pam's+HarvestCraft+1.12.2zg
Patchouli-1.0-23.6
Rex's-AdditionalStructures-1.12.x(v.2.5.0)
SpartanShields-1.12.2-1.5.5
stg-1.12.2-1.2.3
Surge-1.12.2-2.0.79
TConstruct-1.12.2-2.13.0.183
tektopia-1.1.0
TenshiLib-1.12.2-1.2.4
Thaumcraft-1.12.2-6.1.BETA26
ThaumicJEI-1.12.2-1.6.0-27
ToolBelt-1.12.2-1.9.14
useful_backpacks-1.12.2-1.5.4.85
u_team_core-1.12.2-2.2.5.255
WizardryGolems-1.12.2-1.2.0
WizardryTales-2.2.2
WizardryUtils-1.12.2-1.1.4

**Comment by Cheaterpaul** [comment]
There is no spawn config value for the vampire baron.

It is most likely that some another mod is responsible for the barons not spawning.

Minecraft 1.12 / Vampirism 1.6 is outdated and we no longer support this version.
