### ISSUE TITLE
[Feature]:  Human Blood thirst

### ISSUE THREAD

**Issue by Cursed-Shadow** [TeamLapen/Vampirism#1225]
### What?

Hey, I have an idea for the Mod. What if a normal human gets a curse when they drink too much blood and they are not a vampire? There would be a potion effect in the inventory that says they have a human blood thirst. it affects negatively if the problem isn't solved quickly, The blood bar would appear on them . Also the blood bar consumption would be faster than vampires 

### Contributions

**I will try to contribute in this attractive mod**

**Comment by maxanier** [comment]
It may be reasonable to just add a nausea effect or similar if a human drinks blood or eats human hearts (if that is even possible atm). Adding a blood bar or other things adds to much (code) complexity for a feature that will probably only rarely occur

**Comment by maxanier** [comment]
I decided not to allow humans to drink blood.
While this would be a nice detail, it is not worth the effort I think. Thank you for the suggestion anyway
