### ISSUE TITLE
[Bug]: no text showing up with hovering over skills or in appearance

### ISSUE THREAD

**Issue by aguzthin** [TeamLapen/Vampirism#1227]
### Minecraft Version

1.19.3+

### Forge Version

44.1.23

### Vampirism Version

1.9.0

### Singleplayer/Multiplayer

Both

### What happened?

inside the vampire menu no text other than the main menu ones apear
this is in the appearance menu
![image](https://github.com/TeamLapen/Vampirism/assets/138641208/b0cc11f0-c64b-4b24-9b28-4f9696c591ff)
 this also happens in the skill screen
![image](https://github.com/TeamLapen/Vampirism/assets/138641208/8cdff6cd-c8aa-4d7c-acfd-e9c3724fcc4c)
i have no mods other than werewolves 1.1.0.0
this also happened in a server with more mods but the screenshots are from a singleplayer world with vampires and werewolves only

### Reproduce steps

1. load a world
2.  become a vampire
3.  enter the vampire menu
4. enter the 

### Other relevant mods

werewolves 1.1.0.0

**Comment by maxanier** [comment]
I tried reproducing it with the exact versions you mention, but everything seems to work fine for me.
Do you have any other idea what might be different in your setup? (Language other than en_US, special graphic/interface setting)
Is there anything printed to the client log file?

**Comment by aguzthin** [comment]
sorry i have found the issue, there appears to be a conflict between
optifine and vampirism because that's what cause the issue on my part

**Comment by Cheaterpaul** [comment]
I am unable to reproduce this behavior with Forge 44.1.23, Vampirism 1.9.0, Werewolves 1.1.0.0 and Optifine 1.19.3 HD U I3.

Are you using any shaders? If so which one?
Have you tried to setup a new Minecraft instance with these version only?
