### ISSUE TITLE
[Feature]: a crafting recipe to convert enchanced holy water into normall holy water

### ISSUE THREAD

**Issue by ciotex666** [TeamLapen/Vampirism#1228]
### What?

as of right now a hunter who unlocks greater blessing can no longer make normall holy water 
this wouldnt be a problem if not for the fact that some recipes use normall holy water like the iron crucifix or alchemical fire 

i would just make it the same as blood bottle put into any crafting grind to turn enchanced holy water into normall holy water

**Comment by Cheaterpaul** [comment]
Will be introduced in Vampirism 1.10
