### ISSUE TITLE
[Modcompat]: Raised

### ISSUE THREAD

**Issue by Lukebb04** [TeamLapen/Vampirism#1234]
### Minecraft Version

1.19.3+

### Forge Version

47.1.5

### Vampirism Version

1.9.1-beta.1

### Incompatible mod

Raised

### Singleplayer/Multiplayer

Singleplayer

### What happened?

Level number overlaps with xp number

**Comment by Lukebb04** [comment]
Compatibility code [here](https://github.com/yurisuika/Raised/wiki/Compatibility)

**Comment by Cheaterpaul** [comment]
is fixed in the new version
