### ISSUE TITLE
[Bug]: Vampire level too high on screen

### ISSUE THREAD

**Issue by MarioSMB** [TeamLapen/Vampirism#1238]
### Minecraft Version

1.20.1

### Forge Version

47.1.43

### Vampirism Version

1.9.1

### Singleplayer/Multiplayer

Singleplayer

### What happened?

The vampire level is too high on screen:  
![2023-07-27_17 55 05](https://github.com/TeamLapen/Vampirism/assets/1998392/ad172890-b904-4dfd-9e0d-310dd3de0cbb)

### Reproduce steps

Become a vampire - personally tried via infection by fangs.

### Other relevant mods

I don't know what could cause this, if needed I can provide a full list of installed mods.

**Comment by MarioSMB** [comment]
Now that I think about it, [Iron's Spells 'n Spellbooks](https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks) may possibly be responsible if this doesn't normally happen, as they have a (normally hidden) HUD element directly above the hunger bar. I will test more isolated cases when I have some spare time.

**Comment by MarioSMB** [comment]
So the problem was config-related; the levelOffsetY setting in vampirism-client.toml had somehow been changed to 47.  
I don't know if something is automatically adjusting it but resetting it to the default of 0 seems to have fixed the position of the level. Very strange!  

I'll close the issue for now but if it happens again I'll re-open the issue and try to help track down any potential causes.

**Comment by maxanier** [comment]
47 is the default value which seems to usually place it at the correct position. Maybe Spellbooks does add some additional shift?
Anyways, that is what the config option is for

**Comment by MarioSMB** [comment]
That’s strange, I generated a fresh config to get the default and it was 0.
