### ISSUE TITLE
[Bug]:  cant open skill menu in 1.7.10

### ISSUE THREAD

**Issue by peterisnotcool** [TeamLapen/Vampirism#1239]
### Minecraft Version

1.12.x

### Forge Version

dont know

### Vampirism Version

Vampirism-1.7.10-0.7.9.jar

### Modpack

crazy craft 4.0

### Singleplayer/Multiplayer

Server

### What happened?

i cant open or find a button to bind to open skill menu

**Comment by maxanier** [comment]
Ancient Vampirism for 1.7.10 is very different from today's Vampirism. There is no skill menu
