### ISSUE TITLE
[Bug]: Missing hanging signs for wood types

### ISSUE THREAD

**Issue by MarioSMB** [TeamLapen/Vampirism#1240]
### Minecraft Version

1.20.x

### Forge Version

47.1.43

### Vampirism Version

1.9.1

### Singleplayer/Multiplayer

Singleplayer

### What happened?

Just noting here that there are no hanging signs for cursed and dark spruce wood types in the 1.20 versions of the mod yet, thanks!

**Comment by maxanier** [comment]
Will be introduced in Vampirism 1.10
