### ISSUE TITLE
[Feature]: Chinese Simplification Improvements

### ISSUE THREAD

**Issue by Sorrow-Scarlet** [TeamLapen/Vampirism#1241]
### What?

- Version: 1.18.2
- Forge  

To change some improper/incomprehensible translations of zh_cn.json

### Mod experience

Absolutely positive.

### Contributions

1.   "text.vampirism.i_am_busy_right_now": "我将会很忙" -> “我现在很忙”, "将会很忙" means "will be busy", "现在" means "now"
2.   "text.vampirism.cant_fly_dimension": "You are not able to stay as bat in this dimension"->“你不能在此维度飞行”
3.   "text.vampirism.decorative_only": "Decorative block",->"装饰性方块"
4.   "text.vampirism.oil.effect_on_hit": "Effect On Hit:",->“击中效果”
5.  "text.vampirism.blessing": "Blessing",->“祝圣”
6.   "advancement.vampirism.desc": "Getting started with Vampirism",->“欢迎来到血族传说”
7.   "advancement.vampirism.become_vampire": "Moving Beyond Humanity",“我不做人了！”
8.   "container.vampirism.hunter_table.level_wrong": "无法在此级别使用表",->“这张研究台不适合你” "表"has another meaning in Chinese, which could be understand as “a watch” or "sheet like an excel sheet"
9.  "block.vampirism.garlic_diffuser": "Garlic Diffuser",->“大蒜喷洒器”
10.   "item.vampirism.blood_infused_iron_ingot": "Blood-Infused Iron Ingot",->“注血铁锭”
11.   "item.vampirism.blood_infused_enhanced_iron_ingot": "Enhanced Blood-Infused Iron Ingot",->“增强注血铁锭”
12.   "item.vampirism.pure_salt_water": "Pure Salt Water",->“祝福盐水”

**Comment by Cheaterpaul** [comment]
The simplified chinese has already a 99% translation coverage. 1.18 simply uses an older version where not all translations were available when the version was build. You can check the current status on [Crowdin](https://crowdin.com/project/vampirism/zh-CN).

I refrain from changing them myself as i can not judge if one translation is better than another. If you want you can still edit them directly in Crowing, there you can see the current translation.

One side node here regarding `container.vampirism.hunter_table.level_wrong`:
Yes i can not tell what is correct or not, but "这张研究台不适合你" translates to "This research table is not for you" but here it is important that the level of the player is relevant for this. As far as i remember we have another message that tells you that the block can not be used by the player when they have another faction, where the player could no longer tell the difference.

"text.vampirism.i_am_busy_right_now" hasn't changed so i updated it.
