### ISSUE TITLE
[Bug]: Villagers remaining text overlapping with raid text

### ISSUE THREAD

**Issue by MarioSMB** [TeamLapen/Vampirism#1242]
### Minecraft Version

1.20.x

### Forge Version

47.1.43

### Vampirism Version

1.9.1

### Singleplayer/Multiplayer

Singleplayer

### What happened?

The "villagers remaining" text is overlapping with the "vampire raid" text on the top of the screen:  
![2023-08-03_16 08 59](https://github.com/TeamLapen/Vampirism/assets/1998392/f202244f-846a-41fd-b07f-c0faa708b45f)

**Comment by MarioSMB** [comment]
Additionally, the raid text seems to stay on screen long after the raid is over - relogging clears it.

**Comment by Cheaterpaul** [comment]
Apparently it fixed itself by now
