### ISSUE TITLE
[Bug]: Night/Blood Vision toggle often activates twice

### ISSUE THREAD

**Issue by MarioSMB** [TeamLapen/Vampirism#1245]
### Minecraft Version

1.20.x

### Forge Version

47.1.43

### Vampirism Version

1.9.1

### Singleplayer/Multiplayer

Singleplayer

### What happened?

Quite often when I press the "Switch vision" key (N by default) it will activate twice, toggling back off/on again or switching to the other vision mode. It's like the input goes through twice on occasion.

Also, holding the N key in dark places makes the screen flash violently! This might be seizure-inducing for some.

### Other relevant mods

I don't think this is a conflict of any kind as it has been happening for a long time.

**Comment by Cheaterpaul** [comment]
I can not reproduce the double click and never head of it, but i see why this may happen.

The screen flashing it the default behavior of all gui related keybinding, eg. holding down the escape key. But this is a good idea.

**Comment by MarioSMB** [comment]
That is interesting, I've had this problem for as long as I've been playing with the mod and with multiple systems - I assumed it was commonplace and just unreported (apologies for taking so long on that part, it's funny how we sometimes forget to report the details that catch our eyes!).
