### ISSUE TITLE
[Feature]: Don't show sun overlay when in creative mode

### ISSUE THREAD

**Issue by MarioSMB** [TeamLapen/Vampirism#1248]
### What?

Just a small detail but could be nice if the sun overlay didn't display as a vampire in creative mode!

**Comment by Cheaterpaul** [comment]
We already reduce the size of the overlay when in creative mode. Here is the question if we really want to not show the bar.

It may happen that you get out of creative mode and immediately die.

**Comment by MarioSMB** [comment]
Perhaps creative mode should act as if the player is no longer in sunlight, so when you move to survival mode the effect will come back normally giving you some time to react.

**Comment by MarioSMB** [comment]
I can also understand wanting to keep it - that's a tough call, maybe having the effect even further reduced would help keep it from being a distraction for creative mode builders?

**Comment by maxanier** [comment]
The question is, what is the benefit of being a vampire when you are permanently in creative mode anyways.
If you are in creative just temporarily, it may be helpful to remind you to but some sunblocker in your building or for testing/debugging.
Maybe we can reduce the border down to 10px, but unless more people complain, I don't see a strong point for removing it. https://github.com/TeamLapen/Vampirism/blob/7a857f1bcfd4962720dd0fb41b046cab9befb2a2/src/main/java/de/teamlapen/vampirism/client/gui/overlay/VampirismHUDOverlay.java#L346

You can also give yourself sunscreen 5 or 6 to get rid of the overlay.
