### ISSUE TITLE
[Bug]: Gradle bug

### ISSUE THREAD

**Issue by oleg12054** [TeamLapen/Vampirism#1252]
### Minecraft Version

1.18.x

### Forge Version

40.1.0

### Vampirism Version

?

### Singleplayer/Multiplayer

Singleplayer

### What happened?

When I downloaded the source file, I installed it and started preparing to compile the files, but even when not everything was imported yet, the following error appeared: "Gradle Gradle version 7.4 was found. The minimum required level is Gradle 8.1.
Note: First update the gradle version before trying to switch to FG6."

![Снимок экрана 2023-08-11 231808](https://github.com/TeamLapen/Vampirism/assets/127609432/79c85cba-78a9-4ee0-bcc0-0de8c1ee29ce)

When I finally decided to try changing the gradle version to 8.1, another error flew out: "Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: could not find the classifier() method for [api] arguments in the organizational type ':apijar' task.gradle.api.tasks.bundling.Jar ." 

![Снимок экрана 2023-08-11 231822](https://github.com/TeamLapen/Vampirism/assets/127609432/7fd74821-1082-486d-9aaf-776fcd7b2a88)

I didn't change or do anything except try to change the gradle version, but nothing helped. Tell me, what could have gone wrong?

### Relevant log output

```shell
No
```

**Comment by Cheaterpaul** [comment]
The gradle version is set to automatically use the newest version, which is incompatible with gradle 7.

You can set 
`classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '[5.1.26,)', changing: true`
to 
`classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '5.1.26', changing: true`
 at
https://github.com/TeamLapen/Vampirism/blob/52a82a31516eae2a86949970052c525514ad0106/build.gradle#L11C9-L11C112

This way the old forge gradle version is used

**Comment by oleg12054** [comment]
Yes, it helped. Thanks!
