### ISSUE TITLE
Breathe underwater skill

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#126]
Readd some kind of breathe underwater skill. Maybe only if not in realism mode.

**Comment by maxanier** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2756555-vampirism-become-a-vampire-release-for-mc-1-10-and?comment=7
Waiting for feedback relevant for this and #128

**Comment by maxanier** [comment]
Vampire will now be able to breathe underwater, but they will be greatly weakened unless they unlock a certain skill. Let's see how this is accepted.
521e61bf172dbccfdedf8d3a1450c7648cace1c2

**Comment by FrilyX** [comment]
Accept
