### ISSUE TITLE
[Modcompat]: server crashes with sponge

### ISSUE THREAD

**Issue by lollopanta** [TeamLapen/Vampirism#1261]
### Minecraft Version

1.16.x

### Forge Version

36.2.39

### Vampirism Version

1.9.9

### Incompatible mod

sponge

### Singleplayer/Multiplayer

Server

### What happened?

server crashes

### Reproduce steps

1. install sponge and vampirism
2. run server in java8 zulu and server in windows 11 with this flags;
@echo off
"C:\Program Files\Zulu\zulu-8\bin\javaw.exe" -Xms4096M -Xmx4096M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -jar server.jar --nogui
pause

### Relevant log output

```shell
https://paste.md-5.net/tofoxepili.md
```

**Comment by maxanier** [comment]
Thank you for reporting
Will be closed with next release.
