### ISSUE TITLE
[Bug]: drink blood from a blood container in someone else's private

### ISSUE THREAD

**Issue by BloodInAs** [TeamLapen/Vampirism#1265]
### Minecraft Version

1.20.x

### Forge Version

47.2.1

### Vampirism Version

Vampirism-1.20.1-1.9.2

### Singleplayer/Multiplayer

Server

### What happened?

You can drink blood from a blood container in someone else's private
`'vampirism:blood_container'`
![1](https://github.com/TeamLapen/Vampirism/assets/146227359/031341ea-a4da-43bd-9903-a6f8bb4bc84e)

**Comment by Cheaterpaul** [comment]
> in someone else's private

I do not understand what you mean that.


I assume this is a translation issue. Can you therefore describe the problem differently.

**Comment by BloodInAs** [comment]
There is a plugin on the server `worldguard-bukkit-7.0.9-dist.jar`

Players set up private regions that they can control, for example, strangers cannot break blocks

**Comment by lunofe** [comment]
Forge mods work fundamentally different than Bukkit plugins. There's no common ground for them and so neither Worldguard or Vampirism know of each others existence. That's a limitation of hybrid servers we cannot change.

**Comment by maxanier** [comment]
As explained above, there is nothing we can do. 
Only solution is to "physically" prevent other players from accessing your blood container.
