### ISSUE TITLE
[Bug]: Dupe blood through teleportation

### ISSUE THREAD

**Issue by BloodInAs** [TeamLapen/Vampirism#1266]
### Minecraft Version

1.20.x

### Forge Version

47.2.1

### Vampirism Version

Vampirism-1.20.1-1.9.2

### Singleplayer/Multiplayer

Singleplayer

### What happened?

We die once, teleport to /spawn and enter any portal. We teleport to /home and your health and blood are restored. This way you can get up to any number of bottles of blood by drinking it from a friend or constantly replenishing it yourself. Health also regenerates  full.

https://www.youtube.com/watch?v=sMHOvvK5Rw4&ab_channel=ShaniMad

**Comment by lunofe** [comment]
That is most likely caused by the server or another modification and not Vampirism.

**Comment by maxanier** [comment]
If health is restored after teleport, this is probably not a Vampirism problem
