### ISSUE TITLE
[Bug]: You can't drink blood

### ISSUE THREAD

**Issue by BloodInAs** [TeamLapen/Vampirism#1267]
### Minecraft Version

1.20.x

### Forge Version

47.2.1

### Vampirism Version

Vampirism-1.20.1-1.9.2

### Singleplayer/Multiplayer

Server

### What happened?

It is impossible to drink the blood of players and mobs, even outside of private (you can only drink from a container)

**Comment by maxanier** [comment]
Maybe it has something to do with permissions:
https://wiki.vampirism.dev/docs/wiki/permissions#permission-problems

Do you see the red fang when looking at a player/mob?

**Comment by BloodInAs** [comment]
Everything works, thank you
