### ISSUE TITLE
[Bug]: The Vampire Lord can kill players with his minions in privates where PvP is disabled

### ISSUE THREAD

**Issue by BloodInAs** [TeamLapen/Vampirism#1268]
### Minecraft Version

1.20.x

### Forge Version

47.2.1

### Vampirism Version

Vampirism-1.20.1-1.9.2

### Singleplayer/Multiplayer

Server

### What happened?

The Vampire Lord can kill players with his minions in privates where PvP is disabled

### Reproduce steps

Set minions against the player

**Comment by BloodInAs** [comment]
I'm sorry, I want to clarify. Are you suggesting that I apply these changes myself or will there be a mod update that will already include these changes?

**Comment by Cheaterpaul** [comment]
We will release an update to apply them.
