### ISSUE TITLE
[Bug]: Vampire hunters will kill their allies if accidently shot

### ISSUE THREAD

**Issue by Voltem0** [TeamLapen/Vampirism#1270]
### Minecraft Version

1.20.x

### Forge Version

47.2.0

### Vampirism Version

1.9.2

### Modpack

custom

### Singleplayer/Multiplayer

Singleplayer

### What happened?

Nothing big, but vampire hunters will attack any other mob if it shoots them, even other vampire hunters and other 'friendly' mobs. This can happen easily if multiple vampire hunters are shooting a zombie and one accidently shoots another with a crossbow, the vampire hunter will then shoot its own supposed ally in retaliation until it dies.
This means after any kind of firefight, in case the vampire hunters win, they will usually attack eachother until like half the survivors are dead.
Suboptimal.
I don't know excactly how minecraft mobs like skeletons do this, but they dont fall to infighting like they used to a few versions ago in the same scenario.

**Comment by maxanier** [comment]
Yeah, probably makes sense that hunters would be smarter than that.
I changed it so that they do not take revenger on other hunter mobs
