### ISSUE TITLE
[Bug]: Crash while attacking vampires

### ISSUE THREAD

**Issue by CuchilloMucho** [TeamLapen/Vampirism#1272]
### Minecraft Version

1.12.x

### Forge Version

47.1.3

### Vampirism Version

1.9.3

### Singleplayer/Multiplayer

Singleplayer

### What happened?

Was fighting vampires when my game crashed

### Relevant log output

```shell
Error: java.lang.ClassCastException: class de.teamlapen.vampirism.entity.vampire.BasicVampireEntity cannot be cast to class net.minecraft.world.entity.player.Player (de.teamlapen.vampirism.entity.vampire.BasicVampireEntity is in module vampirism@1.9.3 of loader 'TRANSFORMER' @c6c58ce; net.minecraft.world.entity.player.Player is in module minecraft@1.20.1 of loader 'TRANSFORMER' @c6c58ce)
```

### Reproduce steps

no idea

### Other relevant mods

Vampirism Ageing. Vampirism Integrations

**Comment by CuchilloMucho** [comment]
Seems to be due to Vampiric Ageing, disabling it fixed the crash

**Comment by maxanier** [comment]
Can you please provide the full crash report. Especially the lines following above error message are crucial

**Comment by CuchilloMucho** [comment]
Here is the full crash report but it has been fixed on Vampiric agings side.
[crash-2023-10-22_15.57.58-server.txt](https://github.com/TeamLapen/Vampirism/files/13067042/crash-2023-10-22_15.57.58-server.txt)

**Comment by Cheaterpaul** [comment]
TheDrOfDoctoring/Vampiric-Ageing#2
