### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mayahereis** [TeamLapen/Vampirism#1273]
### Minecraft Version

1.12.x

### Forge Version

14.23.5.2847

### Vampirism Version

1.6.2

### Modpack

ARTHALOS

### Singleplayer/Multiplayer

Server

### What happened?

I have a server on aternos and we tried to claim a village as vampires, but anytime we right click the totem it says theres no village nearby even tho the totem is in the middle of a village. We tried moving the totem too but it didnt work. There is also Tektopia mod in the modpack and Im not sure if it doesnt work because of that.

### Other relevant mods
Tektopia

_No response_

**Comment by Cheaterpaul** [comment]
Minecraft 1.12 is no longer supported.

The totem detects a village by searching for the workstations and beds of the villager. It requires 4 beds, 4 workstations and 4 villager. Either the village has to few of them or they are to far away from the totem. Try placing them near the totem.
