### ISSUE TITLE
[Modcompat]: Intense Fog Flickering with Alex's Caves

### ISSUE THREAD

**Issue by mrdrewlego** [TeamLapen/Vampirism#1274]
### Minecraft Version

1.20.x

### Forge Version

47.1.3

### Vampirism Version

1.9.3

### Incompatible mod

Alex's Caves 1.0.4

### Singleplayer/Multiplayer

Singleplayer

### What happened?

A flickering effect is being created when moving in an area that produces the fog effect from this mod.

### Reproduce steps

1. Install Alex's Caves 1.0.4, vampirism 1.9.3 and required dependencies.
2. Travel or teleport to location that uses the fog (This includes a village with an active totem or the vampire forest)
3. Move the player character around in the environment to notice the flickering of the fog effect.

### Relevant log output

```shell
https://paste.gg/p/anonymous/75928bfe1cbd4602962a3e1a5521826b
```

**Comment by Cheaterpaul** [comment]
As quick workaround you can set the `biome_sky_fog_overrides` config option in the alexscaves client config to false

**Comment by Cheaterpaul** [comment]
AlexModGuy/AlexsCaves#109

**Comment by Cheaterpaul** [comment]
Alexs Caves has some logic to calculate the fog which no longer works correctly when other mods use fog.
