### ISSUE TITLE
[Bug]: Due crossbow clip

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#1275]
### Minecraft Version

1.20.x

### Forge Version

xx

### Vampirism Version

1.10-halloween

### Singleplayer/Multiplayer

Singleplayer

### What happened?

Random on Discord: 
Hmm, the new semi-auto crossbow clip can stack even if clips are loaded but the whole stack of charged clips becomes empty once you reload your crossbow
It seems like you can dupe crossbow bolts. You can load stack of empty clips with 12 quarrels and just separate it

**Comment by supermike1999** [comment]
Not sure if you confirmed it your self, but i made a quick video of it here
https://youtu.be/zkH-OD2-CS8

**Comment by maxanier** [comment]
Paul, did you also check the general behavior again? Like the clip being empty after the first crossbow shot. Is that intentional?

**Comment by Cheaterpaul** [comment]
I seem to have misremembered.
Yes, the crossbow will empty the clip after it is loaded.
