### ISSUE TITLE
Attacking vampire skills

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#128]
The vampire skill tree is lacking offensive skills like fire attack or others.
Inspiration: e.g. https://www.youtube.com/watch?v=L2Vty5V-810

**Comment by maxanier** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2756555-vampirism-become-a-vampire-release-for-mc-1-10-and?comment=7
Waiting for feedback relevant for this and #126

**Comment by maxanier** [comment]
Definitvely need ranged (non fire based) attack

**Comment by LatentDesire** [comment]
Fire (and sunlight) is generally seen as anathema to vampires. Though it would certainly fit hunters (even the example video is of a vampire hunter.)

Perhaps a projectile of darkness, or bats for vampires. I'd say blood, but blood as a resource would make shooting it at people ill advised.

**Comment by vansuncnk** [comment]
it should be blood shot . it will consume own hp .

**Comment by KamiSami** [comment]
More skills still in progress?

**Comment by maxanier** [comment]
One planned one is some kind of "magic"/bloody projectile. Maybe similar to a ghast thingy, but a lot faster, larger area of impact, blood instead of fire and some more magical looks.

Probably going to consume some blood from your blood bar. See also #252

**Comment by maxanier** [comment]
Also working on some vampire swords, see branch -vampire-swords.
Might get some nicer looking models from @AlbertoJVD

**Comment by maxanier** [comment]
Could also add some kind of ranged (blast) attack to vampire barons to make it harder to trick them

**Comment by Cheaterpaul** [comment]
a few ideas:
One skill could be to get Invulnerable/damagereduction against high damage attacks.
Anotherone could be, after activating the skill,to get additional empty blood bar and
after a few seconds potentionally consume the additional blood and some else to damage everything in a circle around him based on the additional filled blood and a base value

**Comment by Cheaterpaul** [comment]
These ideas are all implemented somehow or not.

We can create new issues on demand.
