### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by HyperAtill** [TeamLapen/Vampirism#1281]
### Minecraft Version

1.20.x

### Forge Version

47.2.0

### Vampirism Version

1.9.3

### Singleplayer/Multiplayer

Singleplayer

### What happened?

Vampires have such an ability, it’s called “Advanced Biter”. Usually, it increases the amount of blood you drink, but now, after I leveled it up at level 6, it didn't do anything. The level of blood I drank was half a drop of blood above the hotbar, and remained half a drop (For example, when I drank blood from a sheep). (Translated using Google Translate)

### Reproduce steps

1. Load Singleplayer world
2. Become a 6-level vampire
3. Upgrade "Advanced Biter"
4. Try to drink blood from anybody

### Other relevant mods

Other mods in my Modpack:
appleskin-forge-mc1.20.1-2.5.1
jei-1.20.1-forge-15.2.0.27
justzoom_forge_1.0.2_MC_1.20.1
konkrete_forge_1.6.1-2_MC_1.20
notenoughanimations-forge-1.6.4-mc1.20
radium-mc1.20.1-0.12.2+git.5f80f74
Vampirism-1.20.1-1.9.3

**Comment by Cheaterpaul** [comment]
Advanced bite only gives a chance to drink double the amount and stops the bite on the last blood.

**Comment by Cheaterpaul** [comment]
Feel free to reopen
