### ISSUE TITLE
[Bug]: 2 zombies and a vampire

### ISSUE THREAD

**Issue by BloodInAs** [TeamLapen/Vampirism#1284]
### Minecraft Version

1.20.x

### Forge Version

47.2.1

### Vampirism Version

Vampirism-1.20.1-1.9.2

### Modpack

-

### Singleplayer/Multiplayer

Server

### What happened?

2 zombies attack a vampire, this causes an error
[message.txt](https://github.com/TeamLapen/Vampirism/files/13369547/message.txt)

### Reproduce steps

spawn two zombies near the vampire. They start beating him and this error occurs in the console

**Comment by Cheaterpaul** [comment]
The log entry is only a warning, and not an error. FYI: this happens when the player is attacked by the zombie.
There is not necessarily something wrong.
