### ISSUE TITLE
[Modcompat]: Dying from radiation (Mekanism)

### ISSUE THREAD

**Issue by EnderCat263** [TeamLapen/Vampirism#1285]
### Minecraft Version

1.20.x

### Forge Version

47.2.1

### Vampirism Version

1.9.2

### Incompatible mod

Mekanism-1.20.1-10.4.1.15

### Singleplayer/Multiplayer

Server

### What happened?

When you become a vampire and died from radiation(mekanism) button respawn don't shows

### Reproduce steps

1. Load server with mods
2. Become a vampire 
3. Try to die
4. Respawn Title don't have button `respawn`

**Comment by Cheaterpaul** [comment]
Is this shown to you, but without the respawn button? 

![2023-11-16_23 10 11](https://github.com/TeamLapen/Vampirism/assets/17816456/4e289d3a-b957-4d68-b356-1ee9bc13be27)


Or what is shown to you instead?

**Comment by EnderCat263** [comment]
> Is this shown to you, but without the respawn button? 
> 
> ![2023-11-16_23 10 11](https://github.com/TeamLapen/Vampirism/assets/17816456/4e289d3a-b957-4d68-b356-1ee9bc13be27)
> 
> 
> Or what is shown to you instead?

Are you become vampire?

**Comment by Cheaterpaul** [comment]
> > Is this shown to you, but without the respawn button?
> > ![2023-11-16_23 10 11](https://user-images.githubusercontent.com/17816456/283610471-4e289d3a-b957-4d68-b356-1ee9bc13be27.png)
> > Or what is shown to you instead?
> 
> Are you become vampire?

Yes, hence the purple name.

**Comment by satonagrad1234** [comment]
> > > Is this shown to you, but without the respawn button?
> > > ![2023-11-16_23 10 11](https://user-images.githubusercontent.com/17816456/283610471-4e289d3a-b957-4d68-b356-1ee9bc13be27.png)
> > > Or what is shown to you instead?
> > 
> > 
> > Are you become vampire?
> 
> Yes, hence the purple name.

You just managed to repeat the mistake, because when a vampire dies, he should have a button to Give up and Resurrect, because a vampire should not die immediately

![image](https://github.com/TeamLapen/Vampirism/assets/112409236/1921fa89-46fc-482a-aef2-1a48c9dfc5bd)
