### ISSUE TITLE
[Bug]: vampires randomly unable to die from back stab 

### ISSUE THREAD

**Issue by zarganitsa** [TeamLapen/Vampirism#1288]
### Minecraft Version

1.19.2

### Forge Version

43.3.5

### Vampirism Version

1.9

### Singleplayer/Multiplayer

Singleplayer

### What happened?

vampires sometimes are not killed from a backstab with the hunter skill1 and 2 
i have notices they are not harmed at all from anything vampirism mod related

**Comment by maxanier** [comment]
Sorry, for the delayed response. This is a difficult issue to debug and if it only happens only occasionally, it is also low priority.
There is also some potential for confusion here. The back stab does not consider whether you are hitting the back of the vampire body, but rather considers whether the vampire is able to see you (base on head rotation) and thus able to react to your attack (lorewise).
Furthermore, there may be some inconsistency between rendering and game logic (more in multiplayer than in single-player though).
I have clarified the text.
Please let us know if the problem should be more serious
