### ISSUE TITLE
Vampire Lord/Hunter Lord

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#129]
"Vampire Lord"/"Hunter Lord"
        At max level after boss fight
        Not loose it
        Allow minion/recruit hunters
        Maybe one and only afterwards
        Different levels "Captain/Major/General..."

TODO: Reseach forum posts for more suggestions

**Comment by vansuncnk** [comment]
it will great

**Comment by ZatsuneSakurako** [comment]
Vampire Lord will come back? There was a boss in a special world before

**Comment by KamiSami** [comment]
It's been awhile since this was opened, will this be still feature soon perhaps?

**Comment by OfficialGKing** [comment]
Is this still a feature being planned?

**Comment by maxanier** [comment]
Yes but many things have gotten into the way

**Comment by maxanier** [comment]
Just some suggestions/notes by _smashbro596_:

> i propose the lord form would have two modes: grounded and flying. while grounded, the lord gains a vicious claw swipe that has a lower swinging rate than a sword.  in this mode, it can still bite, but it cant draw blood like the humanoid form can. in flight mode, it can gain some nifty magic abilities, such as grabbing enemies via telekinesis or an enhanced dark blood projectile. it can also fire a projectile that slowly drains a target of its blood. as a balance, the vampire lord form drains blood quickly unupgraded, and with insufficiant blood, you will be forced out of the form and cant re-transform until you drink the amount of blood necessary to transform again.  its size isnt ideal for indoor environments. it also gets double the weakness to holy items.

**Comment by PendragonII** [comment]
> Just some suggestions/notes by _smashbro596_:
> 
> > i propose the lord form would have two modes [...]

Another proposal: Vampire Lords (VL) and Hunter Lords (HL) continue to have the ability to wear armor and use tools (insuring that on hardcore modpacks VL and HL are not a liability). VL and HL also have a dedicated skill tree as the players do.

**Comment by KamiSami** [comment]
Still looking forward to this after some years

**Comment by maxanier** [comment]
So, just roughly 4 years later, this issue can finally be closed :D
The lord feature is implemented in the latest 1.7 alpha for MC 1.14
It allows you to control minions
https://gist.github.com/maxanier/1df3a7831ad2dd910df475ee99d48c25

It does not include the old "one and only" mechanic, but that might be an option in the future #757
