### ISSUE TITLE
[Bug]: When putting on vampire Hat as non-vampire game crashes

### ISSUE THREAD

**Issue by PatTheWizard** [TeamLapen/Vampirism#1291]
### Minecraft Version

1.20.1

### Forge Version

47.2.6

### Vampirism Version

1.9.3  

### Singleplayer/Multiplayer

Singleplayer

### What happened?

I put on the vampire hat as a non vampire in my personal modded game and it crashed the game. When i went back in loaded up fine but as soon as I opened my inventory it crashes 

### Reproduce steps

1. Load world 
2. Put on Vampire Hat as Non vampire 
3. Crash 
[crash-2023-11-28_12.55.14-client.txt](https://github.com/TeamLapen/Vampirism/files/13491505/crash-2023-11-28_12.55.14-client.txt)

**Comment by Cheaterpaul** [comment]
This is caused by AzureLib Armor.
They cast a Model to a Humanoid Model without checking.
