### ISSUE TITLE
[Bug]: Villager texture not working

### ISSUE THREAD

**Issue by YagoVini** [TeamLapen/Vampirism#1293]
### Minecraft Version

1.16.x

### Forge Version

36.3.34

### Vampirism Version

1.9.10

### Singleplayer/Multiplayer

Both

### What happened?

one of the villagers get a glitched texture
![image_2023-11-29_214547961](https://github.com/TeamLapen/Vampirism/assets/151583709/72f01018-2635-4705-8014-9a2bc4c1f6cf)

### Other relevant mods

morevillagers-1.5.4
alexsmobs-1.12.1

**Comment by Cheaterpaul** [comment]
Is this related to Vampirism? All our professions have textures even the zombie variants.

**Comment by YagoVini** [comment]
> Is this related to Vampirism? All our professions have textures even the zombie variants.

Hi Cheaterpaul
it seems to be, i opened the same report to alexmobs mod developer, and seems like is not on their mod, i have, a feeling that, it may be some of the zombified versions , are taking the wrong texture

**Comment by Cheaterpaul** [comment]
From the screenshot it can be any mod that adds a profession. You can check your logs if a texture is missing. It should print a warning.


Try spawning a Zombie Villager with Vampirism's professions

`/summon minecraft:zombie_villager ~ ~ ~ {VillagerData:{profession: "vampirism:hunter_expert"}}`
`/summon minecraft:zombie_villager ~ ~ ~ {VillagerData:{profession: "vampirism:vampire_expert"}}`
`/summon minecraft:zombie_villager ~ ~ ~ {VillagerData:{profession: "vampirism:priest"}}`

If they work correctly, Vampirism has nothing to do with this.
