### ISSUE TITLE
[Modcompat]: Able to cast spells in bat mode (Iron's Spells and Spellbooks)

### ISSUE THREAD

**Issue by MarioSMB** [TeamLapen/Vampirism#1304]
### Minecraft Version

1.20.x

### Forge Version

47.2.17

### Vampirism Version

1.10.0

### Incompatible mod

Iron's Spells and Spellbooks (irons_spellbooks) 2.1.2

### Singleplayer/Multiplayer

Server

### What happened?

While in bat mode one is still able to cast spells when playing with the Iron's Spells and Spellbooks mod. The mod uses items (spellbooks and scrolls) for its spellcasting so I assume it is on Vampirism's end that item use is not cancelled, but please let me know if this is something that must be reported on their end.

**Comment by MarioSMB** [comment]
Unrelated but the mod compatibility report text in the "What happened?" section only expands to a single line rather than a full text box making it hard to format a proper report.

**Comment by Cheaterpaul** [comment]
We did not explicitly forbid the usage of item in bat mode. But that might be a good idea.
