### ISSUE TITLE
[Bug]: vampires dont come back to life

### ISSUE THREAD

**Issue by kaboom24** [TeamLapen/Vampirism#1305]
### Minecraft Version

1.20.x

### Forge Version

47.2.0

### Vampirism Version

1.10.1

### Singleplayer/Multiplayer

Singleplayer

### What happened?

im pretty sure that vampires are supposed to respawn if you dont kill them with the right stuff

### Reproduce steps

1. load single player world
2. kill vampire
3. it does not respawn

**Comment by lunofe** [comment]
Works as intended. You can kill vampires with a variety of weapons.
