### ISSUE TITLE
[Feature]: vampire forest cured

### ISSUE THREAD

**Issue by kaboom24** [TeamLapen/Vampirism#1306]
### What?

I think you should be able to slowly cure the vampire forest after you destroy the ancient remains also every large vampire forest should have a gauranteed chance of ancient remains spawning

### Mod experience

I think it would be a little cooler but to keep the balance make it so the forest is cured SLOWLY and you cant do it on a server because then you might come back and find out you cant farm barons anymore

**Comment by Cheaterpaul** [comment]
Curing the forest has been suggested before. However, we felt that this feature was not feasible and not very clear on multiplayer servers where you can destroy a savezone for other players.

Doing it only when the Ancient Remains are destroyed raises the same issue, while vampire players can settle in forests without a Ancient Remains to be safe.

But as I just said, there are forests without Ancient Remains, which raises the question of whether a forest can exist without a Ancient Remains.

We explain it this way:
An Ancient Remain is the source of the Vampire Forest. It is the reason the forest exists in the first place, but it is not necessary for its continued existence.
