### ISSUE TITLE
[Feature]: wings

### ISSUE THREAD

**Issue by kaboom24** [TeamLapen/Vampirism#1307]
### What?

I think that you should be able to grow temporary wings that make you stronger and faster by wearing a cloak and drinking pure blood (which you cant do anymore please fix) the idea comes from the vampire book "my prince" where the prince grows wings by following the instructions mentioned above

### Mod experience

I think it affects it positively as long as you balance the stat increase with the duration maybe have your stats increased more but the duration decreased by drinking higher tier pure blood

**Comment by lunofe** [comment]
This was a cosmetic easter egg in prior versions. I don't think it should have any real buffs, because that way, it'll be just a different version of a golden apple.

**Comment by kaboom24** [comment]
okay then maybe just add the easter egg back because that seems fun

**Comment by Cheaterpaul** [comment]
Well, an easter egg is an easter egg for a reason and not a feature. If they come back, we will find a way to make them fit into the overall experience.
