### ISSUE TITLE
[Bug]: fog diffuser

### ISSUE THREAD

**Issue by kaboom24** [TeamLapen/Vampirism#1308]
### Minecraft Version

1.20.x

### Forge Version

47.2.0

### Vampirism Version

1.10.1

### Singleplayer/Multiplayer

Singleplayer

### What happened?

I cant turn on the fog diffuser am I just doing it wrong or is this an actual bug I right click it but nothing happens except pulling up the GUI after which I click on startup progress but nothing happens

### Reproduce steps

1. Load singleplayer world
2. place fog diffuser
3. fail to turn it on

**Comment by lunofe** [comment]
You need to use a bottle of pure blood.
