### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by kaboom24** [TeamLapen/Vampirism#1309]
### Minecraft Version

1.20.x

### Forge Version

47.2.0

### Vampirism Version

1.10.1

### Singleplayer/Multiplayer

Singleplayer

### What happened?

vampire hunters (advanced and normal) dont attack all undead only zombies

### Reproduce steps

1. Load singleplayer world
2. spawn non zombie undead (skeleton/stray)
3. watch thay dont attack each other

**Comment by lunofe** [comment]
Works as intended. Vampire hunters fight zombies, because zombies see them as villagers, which are also attacked by zombies. Skeletons and strays ignore villagers, so vampire hunters ignore them.
