### ISSUE TITLE
[Bug]: armor points vanish

### ISSUE THREAD

**Issue by kaboom24** [TeamLapen/Vampirism#1312]
### Minecraft Version

1.20.x

### Forge Version

47.2.0

### Vampirism Version

1.10.1

### Singleplayer/Multiplayer

Singleplayer

### What happened?

so I put on some vampire accessories specifically a blue amulet of damage a blue ring of armor and a purple obi belt of healthy atheism and with commands enchanted them with unbreaking and mending now at first everything was normal but the next day I came back and found out that one of my armor points vanished is it maybe because they are not supposed to be able to have mending?

### Reproduce steps

not sure

**Comment by Cheaterpaul** [comment]
I can not reproduce this behavior while testing. My armor stays always the same.

But mending can not be applied to accessories.

**Comment by kaboom24** [comment]
Figured it out, just realized that amulet of damage reduces armor XD
