### ISSUE TITLE
[Bug]: Vampire Armors textures not working

### ISSUE THREAD

**Issue by Vicky-Felix** [TeamLapen/Vampirism#1322]
### Minecraft Version

1.20.x

### Forge Version

47.2.19

### Vampirism Version

1.10.3

### Singleplayer/Multiplayer

Both

### What happened?

after spending some time killing vampire hunters, i was finally able to build the vampire armor set (cloak, crown, boots and pants), but the textures dont seem right. i thought it could be some incompatibility with Epic Fight, but removing it didn't solve the problem, reinstalling vampirism also didn't work. all the cloaks colors and also the hat are weird.
![2024-01-12_19 15 36](https://github.com/TeamLapen/Vampirism/assets/118778823/7ef4f70f-8455-40ff-b6b9-52995da9feac)

### Reproduce steps

1. Load single or multiplayer world
2. Become a vampire
3. Equip vampiric armor set

### Other relevant mods

Alex's Mobs 1.22.7
Angel Ring 2 2.2.1
AE2 15.0.18
Better Village 3.1.0
Biomes O' Plenty 18.0.0.598
Botania 443
Curios 5.4.7
Dynamic Lights 1.20.1.2
Farmer's Delight 1.20.1
Lucky block 13.0
Mekanism (also tools and generators) 10.4.5
MrCrayfish's furniture mod 7.0.0-pre36
Nether's Delight 4.0
ProjectE 1.0.1
Sophisticated Backpacks 3.19.5.998
TLSkinCape 1.32
Traveler's Backpack 9.1.12

**Comment by supermike1999** [comment]
Are you playing with Optifine or Rubidium?

**Comment by Vicky-Felix** [comment]
> Are you playing with Optifine or Rubidium?

Yes, i'm using optifine, forgot of putting it on the list, my bad

**Comment by supermike1999** [comment]
> Yes, i'm using optifine, forgot of putting it on the list, my bad

Optifine is causing this visual issue

**Comment by Vicky-Felix** [comment]
is there any mod i can use o substitute optifine and have no visual issues with vampirism? i use it mainly for performance improvement

**Comment by supermike1999** [comment]
Rubidium is one that works.

**Comment by Cheaterpaul** [comment]
Optifine today only improves performance in rare cases, and then only with a lot of bugs, while Rubidium / Sodium actually improves performance. They are not bug free, but much more compatible.

**Comment by FaustRinovski** [comment]
Got same issue, rubidium installed, but tested without it, and the result is same
