### ISSUE TITLE
Hunter Changes

### ISSUE THREAD

**Issue by Cheaterpaul** [TeamLapen/Vampirism#1323]
Developed with LilCatGod and @supermike1999
# Skills 
## Remove skills
- Attack as swift as the wind
- Double It
- Garlic Vision

## Switch skills
- Crucifix Wielder <-> Vampire repelling
- Improved Garlic <-> Greater Blessing
- Disguise <-> Hunter Weapon Table

## Rename skills
- Hunter Weapon Table -> Basic Technology
- Attack Speed -> Attack as swift as the wind

## Change skills
- Permanent Attack Speed -> + 0.3
- Permanent Attack damage -> + 0.1 total
### Vampire awareness
- clientsided highlighting of vampies
- 15 seconds duration
- 45 seconds cooldown
#### Alternative - Vampire weakness
- apply poison to nearby vampires / wither / weakness

### Speed Walking / Jumping
  - Applies when 4 hunter armor pieces are worn
  - apply speed or jump boost
### Reload Faster / cooldown faster
  - faster crossbow reloading or faster item cooldown
### Double it
  - use two crossbows
  - shoot both at the same time / after one another
  - slower reload
  - apply stagger effect on impact
  - reduce accuracy
 ### Basic Crossbow
- enable crafting and usage of all basic crossbow versions

### Master Craftsmanship
- craft enhanced armor
- craft enhanced crossbow
- craft enhanced weapons

### How to actually use a stake
- apply bleed on hit
  - for 2 seconds
  - only to vampires
### how to actually use an axe
- apply bleed on hit
  - 1 second
  - only to vampires

# Item changes
#### Damage
Normal - 10
Enhanced - 11
Ultimate - 12
#### Bonus damage to vampires
Normal - 20
Enhanced - 30
Ultimate - 40
#### Attack speed
Normal - 1.0
Enhanced - 0.9
Ultimate - 0.8
## Purified garlic
- stack to 16

# Block changes
## Garlic diffuser
- consume garlic / blessed garlic as fuel like a furnace
## Ancient Beacon
- move saturation to last level

# Potions
- remove strength 3

**Comment by maxanier** [comment]
Sounds cool :=)

**Comment by maxanier** [comment]
40 bonus damage to vampires sounds likes insta kill against most vampire, right? Was this discussed with the "hardcore PVP" community?

**Comment by supermike1999** [comment]
The 40 shouldn't be an issue if strength 3 is removed. As that was the big thing that would insta kill vampires.
It also should provide a reason to use the ultimate axe since it there wasn't much difference between it and the enhanced one except the knockback enchant.

**Comment by Cheaterpaul** [comment]
> 40 bonus damage to vampires sounds likes insta kill against most vampire, right? Was this discussed with the "hardcore PVP" community?

LilCatGod, mike and I developed these changes along with other vampire related changes. They need to be tested, especially the axe changes and the new double it skill, but we will see.

**Comment by LilCatGod** [comment]
There is a lot of testing to do, but this (imo) is a good start, making the hunter axes act more like axes than swords. In compensation, an increase in attack damage is applied, which also makes the ultimate different from the others. We gave it a lower attack speed because we were trying to compare it to the other axes (normal = iron, enhanced = diamond, etc.), and we thought it would be harder to swing due to it being heavier.
