### ISSUE TITLE
[Modcompat]: Inventory Pets and Bat mode

### ISSUE THREAD

**Issue by Jangoism** [TeamLapen/Vampirism#1327]
### Minecraft Version

1.20.x

### Forge Version

47.2.0

### Vampirism Version

1.10.3

### Incompatible mod

inventorypets-1.20.1-2.0.20

### Singleplayer/Multiplayer

Server

### What happened?

Bat mode just has player hopping on ground, cannot fly.

### Reproduce steps

1. Install Inventory Pets, load into world, turn into bat.

**Comment by Cheaterpaul** [comment]
look like an issue in Inventory Pets https://github.com/capnkirok/Inventory-Pets/issues/566

**Comment by Jangoism** [comment]
> look like an issue in Inventory Pets [capnkirok/Inventory-Pets#566](https://github.com/capnkirok/Inventory-Pets/issues/566)

Thanks for taking a look into that!

**Comment by Cheaterpaul** [comment]
#1385
