### ISSUE TITLE
[Bug]: Resistance potion effect not being applied to Vampires and Werewolves

### ISSUE THREAD

**Issue by Goiabaaa** [TeamLapen/Vampirism#1330]
### Minecraft Version

1.20.x

### Forge Version

47.2.20

### Vampirism Version

1.10.4

### Singleplayer/Multiplayer

Singleplayer

### What happened?

If you are either a vampire or a werewolf (assuming you have the addon on) and you eat a golden apple, drink a potion of the turtle master or use commands to get the resistance effect applied to you, It will not grant you any damage reduction. Basically, it has no effect. However if you have no faction or you are a hunter, resistance will be effective. 

### Reproduce steps

1. Load a singleplayer world
2. Become either a vampire or a werewolf
3. Get resistance effect
4. Take damage and see how it changes nothing

**Comment by Cheaterpaul** [comment]
After eating the golden apple, the current active effects are shown in the inventory. Is the resistance effect shown there?

**Comment by Goiabaaa** [comment]
For some reason I no longer had issue with this so consider it as just a weird occurance. But I'll let you know if this happens again.
