### ISSUE TITLE
[Bug]: Game refusing to launch

### ISSUE THREAD

**Issue by DaddySpin** [TeamLapen/Vampirism#1334]
### Minecraft Version

1.20.1

### Forge Version

47.1.3

### Vampirism Version

1.10.6

### Singleplayer/Multiplayer

Singleplayer

### What happened?

I am attempting to just launch the game and it refuses to load.

[latest.log](https://github.com/TeamLapen/Vampirism/files/14157240/latest.log)

[crash-2024-02-04_08.48.53-fml.txt](https://github.com/TeamLapen/Vampirism/files/14157241/crash-2024-02-04_08.48.53-fml.txt)

![javaw_mebUTBurJz](https://github.com/TeamLapen/Vampirism/assets/34575655/301c1e96-0a5a-4842-a823-90361f99d151)

### Relevant log output

```shell
crash is to long
```

### Reproduce steps

1. launch game
2. crash

**Comment by Cheaterpaul** [comment]
delete your vampirism-client.toml config file
