### ISSUE TITLE
[Bug]: Temporary loss of resources from armor and hand slots due to resurrection

### ISSUE THREAD

**Issue by Kvakochka** [TeamLapen/Vampirism#1336]
### Minecraft Version

1.20.x

### Forge Version

47.2.1

### Vampirism Version

1.9.2

### Singleplayer/Multiplayer

Server

### What happened?

If, after you are killed, you “Resurrect”, then the amulet, blocks in your hands and armor will disappear, but the next time you die without “Resurrection”, the missing items are returned.
https://youtu.be/B8vu_NB13ik?si=7cT1zDR9d7KKJSLy

### Reproduce steps

1)As a vampire, die from someone/something.
2)Then click the "Resurrect" button
3)To return resources, you need to die again, but without resurrection.

### Other relevant mods

Vampirism Integrations (version 1.8.0- beta. 1) 
Vampirism Need Umbrellas (version 1.0.1)
Godly Vampirism (version 1.0.6)

**Comment by Cheaterpaul** [comment]
From the looks of it there are other mods that makes the resurrection incompatible. After clicking the resurrect button you should be directly resurrected and not need to click it 4 times.

Are you using other mods as well?
