### ISSUE TITLE
When dying from radiation, no resurrection was offered. + Mekanism

### ISSUE THREAD

**Issue by 4u4aaa** [TeamLapen/Vampirism#1337]
### Minecraft Version

1.20.x

### Forge Version

47.2.1

### Vampirism Version

1.9.2

### Singleplayer/Multiplayer

Server

### What happened?

When dying from radiation, no resurrection was offered.

**Comment by Cheaterpaul** [comment]
you can add `mekanism.radiation` to the `immortalFromDamageSources` config option in the balance config
