### ISSUE TITLE
visual bug

### ISSUE THREAD

**Issue by 4u4aaa** [TeamLapen/Vampirism#1338]
### Minecraft Version

1.20.x

### Forge Version

47.2.1

### Vampirism Version

1.9.2

### Singleplayer/Multiplayer

Server

### What happened?

You drink blood from a bottle, but before you can drink it, you open the chest.

**Comment by Cheaterpaul** [comment]
How do you mean? Do you look at a chest, drink from the bottle and then when finished drinking you open the chest?
