### ISSUE TITLE
Turning from a bat to a human - even falling three blocks can kill you.

### ISSUE THREAD

**Issue by 4u4aaa** [TeamLapen/Vampirism#1339]
### Minecraft Version

1.20.x

### Forge Version

47.2.1

### Vampirism Version

1.9.2

### Singleplayer/Multiplayer

Server

### What happened?

Turning from a bat to a human - even falling three blocks can kill you.

**Comment by Cheaterpaul** [comment]
Are you playing on a classic Forge server or does it use some sort of Hybrid software? Mohist for example.

**Comment by 4u4aaa** [comment]
Mohist 554

**Comment by Cheaterpaul** [comment]
This is around in Mohist for some time now. It was confirmed on the official Vampirism server with Mohist as well.
