### ISSUE TITLE
[Modcompat]: cant fly as a bat

### ISSUE THREAD

**Issue by Nick56731** [TeamLapen/Vampirism#1340]
### Minecraft Version

1.20.x

### Forge Version

47.2.0

### Vampirism Version

1.20.1-1.10.6

### Incompatible mod

no idea which

### Singleplayer/Multiplayer

Server

### What happened?

can only jump as a bat

### Reproduce steps

load world
become bat
no flight

### Relevant log output

```shell
instead of a log i will just post my modpack in a google drive link here:
https://drive.google.com/drive/folders/1vYOpyi2BrqPPpGVSf5NvaZk1kQlgLlei
```

**Comment by Cheaterpaul** [comment]
Do you know of any mod you are using that allows flying as well besides Vampirism?

**Comment by Nick56731** [comment]
I had create Stuff and Additions in before but i removed it after reading that it breaks flying but im not sure if i have any other mod on that allows flight

**Comment by Cheaterpaul** [comment]
I do not recognize any of your used mods as one that has incompatibilities with Vampirism.

You can try to remove mods one by one to find which is the one responsible for this bug.

**Comment by xXNinjaWarXx** [comment]
For me it was inventory pets

**Comment by Cheaterpaul** [comment]
#1385
