### ISSUE TITLE
[Modcompat]: Doctor Who - Reborn incompatibility  

### ISSUE THREAD

**Issue by ImShEthan** [TeamLapen/Vampirism#1342]
### Minecraft Version

1.20.x

### Forge Version

47.2.20

### Vampirism Version

1.10.6

### Incompatible mod

dwm v 1.0.7(Doctor Who - Reborn)

### Singleplayer/Multiplayer

Both

### What happened?

When entering the TARDIS from the mod this error pop out : "[18:15:31] [Server thread/WARN] [de.te.va.en.fa.FactionPlayerHandler/]: Cannot get Faction player capability. This might break mod functionality.", all skills have been gone and blood diseapear and going back to regular food.

### Reproduce steps

1 - Be a vampire
2 - Enter the Tardis
3 - See Error in server console + now normal food instead of blood.

**Comment by Cheaterpaul** [comment]
The doctor who mod seems to have problems with every mod that depends on capabilities.

Here is an equivalent bug report https://github.com/drgmes/doctor-who-mod/issues/14

**Comment by Cheaterpaul** [comment]
Should be fixed
