### ISSUE TITLE
[Bug]: Client Crash

### ISSUE THREAD

**Issue by KamiSami** [TeamLapen/Vampirism#1348]
### Minecraft Version

1.20.1

### Forge Version

47.2.20

### Vampirism Version

1.10.6

### Singleplayer/Multiplayer

Singleplayer

### What happened?

Hi, so in short, the game will not get past loading screen without crashing. Here is crash logs https://pastebin.com/WSq9rfGr

### Relevant log output

Already pasted crash report in "What happened?"

### Reproduce steps

Launch game

### Other relevant mods

They are listed in crash report i think

**Comment by Cheaterpaul** [comment]
Duplicate of #1334

**Comment by Cheaterpaul** [comment]
fixed by fa914e7f51035defd78e218e2be135a8e7ef9005
