### ISSUE TITLE
Unable to Fly in bat form

### ISSUE THREAD

**Issue by KzillaLizard** [TeamLapen/Vampirism#1351]
### Minecraft Version

1.20.x

### Forge Version

47.2.0

### Vampirism Version

1.8.0

### Incompatible mod

Inventory Pets but idk the mod ID. Version of that is: 2.1.1

### Singleplayer/Multiplayer

Both

### What happened?

Tried to Fly in Bat Mode, was unable to. 

### Reproduce steps

There's not really any steps, I just turned into bat form to try and fly out of a ravine, and it wouldn't let me fly. I'm assuming that I can't fly because the cloud pet lets you fly with that. 

### Relevant log output

```shell
No crashes, just can't fly
```

**Comment by Cheaterpaul** [comment]
This is an issue on Inventory Pets side. https://github.com/capnkirok/Inventory-Pets/issues/584

**Comment by Cheaterpaul** [comment]
#1385
