### ISSUE TITLE
[Bug]: Endless resurrection on the first level of the vampire.

### ISSUE THREAD

**Issue by DesiRe234** [TeamLapen/Vampirism#1352]
### Minecraft Version

1.20.1

### Forge Version

47.2.1

### Vampirism Version

1.10.7

### Singleplayer/Multiplayer

Server

### What happened?

The bottom line is that players can be killed as many times as they want, but they are constantly resurrected. This leads to a situation where players become virtually invulnerable at this level.

However, I found that if you increase the level from the first level to any other, players can be killed in a normal way. This is a serious problem that distorts the game balance and creates unfair conditions for players.

### Reproduce steps

Here are the reproductions of the problem on these videos:
Vampire level 1 (you can resurrect as much as you want): https://www.youtube.com/watch?v=bHmd44VA3YE
Any other level of vampire, after the blood runs out, you die without the opportunity to resurrect: https://www.youtube.com/watch?v=l-rEATyfdnU

**Comment by Cheaterpaul** [comment]
You can be resurrected as long as you do not have the neonatal effect. From the second video I can see that the effect is only applied for a very short duration.

Either the config option of the duration of the effect is modified or a third party mod interferes here and removed the effect or shortens the duration drastically.

You can check for the config value in the balance config in `vampirism-balance.toml` under the `neonatalDuration` value. By default is is set to 120 seconds.
