### ISSUE TITLE
[Bug]: Crash useing tech crossbow

### ISSUE THREAD

**Issue by Acat1234** [TeamLapen/Vampirism#1357]
### Minecraft Version

1.20.1

### Forge Version

47.2.30

### Vampirism Version

1.10.7

### Singleplayer/Multiplayer

Singleplayer

### What happened?

I was capturing a village and game crashed

**Comment by lunofe** [comment]
@Acat1234 You need to provide a crash log, otherwise there is no way we can help

**Comment by Acat1234** [comment]
Oh

**Comment by Acat1234** [comment]
It seamed to only happen when the minions used it

**Comment by lunofe** [comment]
Please upload a crash report

**Comment by Cheaterpaul** [comment]
This sounds like an issue we had in 1.10.6, which should be fixed in 1.10.7

**Comment by Acat1234** [comment]
I think it may be fixed
