### ISSUE TITLE
[Bug]: First 2 heartstrikers have -1/0 attack speed makeing them never sweep

### ISSUE THREAD

**Issue by Acat1234** [TeamLapen/Vampirism#1358]
### Minecraft Version

1.20.1

### Forge Version

47.2.30

### Vampirism Version

1.10.7

### Singleplayer/Multiplayer

Singleplayer

### What happened?

I saw the thing in the creative inventory and saw it

### Reproduce steps

check them
see -1 or 0

(btw it may be cuz im in hunter faction)

**Comment by Cheaterpaul** [comment]
Do you use Better Combat by any chance?

**Comment by Acat1234** [comment]
No

**Comment by Acat1234** [comment]
I think

**Comment by Cheaterpaul** [comment]
fixed by beb96a740c17abf8202703fd5961c21332d74d8a
