### ISSUE TITLE
[Bug]: when in sunlight nothing happens

### ISSUE THREAD

**Issue by babbidy** [TeamLapen/Vampirism#1359]
### Minecraft Version

1.16.x

### Forge Version

36.2.31

### Vampirism Version

1.9.9

### Modpack

https://www.curseforge.com/minecraft/modpacks/werewolves-vs-vampires

### Singleplayer/Multiplayer

Singleplayer

### What happened?

i became a vampire and then went into the sun and the sun did not burn

### Reproduce steps

load singleplayer world. become a vampire via teeth. walk into sunlight

**Comment by supermike1999** [comment]
I assume you're a level 1 vampire?

**Comment by babbidy** [comment]
yes

**Comment by supermike1999** [comment]
Vampires don't start burning in sun light until they reach level 4

**Comment by babbidy** [comment]
ahh thanks so much
