### ISSUE TITLE
[Bug]: hunger not depleting

### ISSUE THREAD

**Issue by kaboom24** [TeamLapen/Vampirism#1360]
### Minecraft Version

1.20.1

### Forge Version

47.2.0

### Vampirism Version

1.10.7

### Singleplayer/Multiplayer

Singleplayer

### What happened?

when I become a tier 5 vampire lord my blood bar stops depleting no matter what happens it should be depleting, maybe bug with frugal vampire? probably something else though

### Reproduce steps

1. load singleplayer world 2. become vampire lord level 5. 3. attempt to deplete hunger bar

### Other relevant mods

werewolves become a beast version 2.0.0.0 vampires need umbrellas version 1.0.1 the bumblezone version 7.3.5 godly vampirism 1.10.0

**Comment by Cheaterpaul** [comment]
Your blood saturation might be so high, that you do not loose blood
