### ISSUE TITLE
[Modcompat]: Origins mod diets and the human heart

### ISSUE THREAD

**Issue by FuryJack07** [TeamLapen/Vampirism#1364]
### Minecraft Version

1.20.x

### Forge Version

47.3.30

### Vampirism Version

1.10.7

### Incompatible mod

Origins (Forge) v 1.10.0.8

### Singleplayer/Multiplayer

Both

### What happened?

Some origins have diets, like being vegetarians or carnivorous, and the human heart is treated by the mod as an item that only vegetarians can eat, despite the fact that not only does this not make sense, but it also makes things harder for the vampires that chose a carnivorous origin. I suggest either making the heart usable to both (If that's even possible) or at least making it a carnivorous only item.

### Reproduce steps

1. Load any world
2. Choose any carnivorous origin like Arachnid
3. Get the human heart item and notice that you can't eat it
4. either load a new world and chose a vegetarian origin or grab an orb of origin from the creative menu to change your origin to a vegetarian on like Avian
5. notice that you can eat the human heart like normal, despite the fact that it should at least be the opposite

**Comment by wolf653** [comment]
Is the diet determined by a tag on the item? If so, you can add the respective tag using crafttweaker or a datapack.
Also, I generally wouldn't recommend other mods that add these diet restrictions in combination with this mod, especially if you have its add-on werewolves installed.

**Comment by Cheaterpaul** [comment]
Origins uses its own meat tag `origins:meat` because there is no global meat tag.
Starting with NeoForge for 1.20.6 we have a `c:meat` that that we use.

But for now you can add the the item/tags using crafttweaker or a datapack.
