### ISSUE TITLE
[Bug]: Oddly specific crash

### ISSUE THREAD

**Issue by Acat1234** [TeamLapen/Vampirism#1365]
### Minecraft Version

1.20.1

### Forge Version

47.2.32

### Vampirism Version

1.10.7

### Singleplayer/Multiplayer

Singleplayer

### What happened?

Uh I think the game crashed cuz of a minion having garlic bread and a crossbow and Minecraft panicking cuz of it

### Reproduce steps

1. get the items
2. give it to minion
3. crash

**Comment by lunofe** [comment]
Please provide crashlogs for bug reports.

**Comment by lunofe** [comment]
Can't reproduce with the steps provided. ![20240515_084208.jpg](https://github.com/TeamLapen/Vampirism/assets/42828197/1f469e0c-d6b3-49c6-9885-6ce83b50266d)

**Comment by Acat1234** [comment]
Not like that
they need to hold it in the way that lets them use it
crossbow in main hand and garlic bread in offhand

**Comment by lunofe** [comment]
Still can't reproduce. Please just provide a crashlog @Acat1234.
![image](https://github.com/TeamLapen/Vampirism/assets/42828197/9d5597bf-1e37-4501-8aa2-2d0440009769)

**Comment by Acat1234** [comment]
It may be a error caused by other mods sorry
