### ISSUE TITLE
[Bug]: Vampirism+Werewolves  | Leveling up points are not given correctly

### ISSUE THREAD

**Issue by ArtemMASTER** [TeamLapen/Vampirism#1367]
### Minecraft Version

1.20.1

### Forge Version

47.2.1

### Vampirism Version

1.10.7+ Werewolves 2.0.0.0.3-beta.3

### Singleplayer/Multiplayer

Server

### What happened?

On our server, the first skill for both vampires and werewolves can only be upgraded by reaching level 4

**Comment by Cheaterpaul** [comment]
Did you try using a newer Werewolves version?

**Comment by Cheaterpaul** [comment]
Reopen if this issue still exists
