### ISSUE TITLE
[Bug]: cat not vampirised

### ISSUE THREAD

**Issue by kaboom24** [TeamLapen/Vampirism#1369]
### Minecraft Version

1.20.1

### Forge Version

47.2.0

### Vampirism Version

Vampirism-1.20.1-1.10.7.jar

### Singleplayer/Multiplayer

Singleplayer

### What happened?

when I tried to use the infect action on my pure black cat it did not work

### Reproduce steps

1. load singleplayer world 2. become vampire 3. try to infect tamed cat 4. fail to infect tamed cat

### Other relevant mods

all mods are up to date as of this post
alexs caves
alexs mobs
aquaculture 2
balm (forge edition)
biomes o plenty
bosses of mass destruction
cerbons API [forge I fabric I neoforge]
citadel
cloth config API (fabric/forge/neoforge)
clumps
cosmetic armor reworked
curios API (forge neoforge)
geckolib
godly vampirism
just enough items (JEI)
just enough resources (JER)
L_enders cataclysm
Lionfish API
mob battle mod (forge)
nethers exoticism
not enough crashes (forge)
pet your cat
rats (ratlantis experiment turned on)
terrablender (forge)
the bumblezone (neoforge/forge)
vampires need umbrellas
vampirism - become a vampire
waystones
werewolves become a beast

**Comment by Cheaterpaul** [comment]
Works for me. Have you tried to infect the cat from behind?
