### ISSUE TITLE
[Bug]: Not able to even load a world

### ISSUE THREAD

**Issue by AlyxEnRosario** [TeamLapen/Vampirism#1374]
### Minecraft Version

1.20.1

### Forge Version

47.2.32

### Vampirism Version

1.10.7

### Singleplayer/Multiplayer

Singleplayer

### What happened?

I create a world and everything works fine. Al of the sudden after a few times of logging out I get an error that just crashes the wole game that says failed to tick world. 

### Relevant log output

[crash-2024-05-29_23.15.11-client.txt](https://github.com/TeamLapen/Vampirism/files/15493636/crash-2024-05-29_23.15.11-client.txt)

### Reproduce steps

1. Create a world. 
2. Log in and out a few times. 
3. Suddenly not be able to load that world and crash with the resulting crash log. 

### Other relevant mods

Running with hundreds of other mods but the error is only coming from Vampirism and nothing else.

**Comment by Cheaterpaul** [comment]
This is an issue in Vampires Delight. But it was fixed in TheGridExpert/VampiresDelight@3254edf8365f8f6e8eee4947b117a7b37509c9d6
