### ISSUE TITLE
[Modcompat]: Create Balanced Flight : Angel Ring - prevents Bat Form flight from working

### ISSUE THREAD

**Issue by Baaleos** [TeamLapen/Vampirism#1375]
### Minecraft Version

1.20.x

### Forge Version

47.1.X

### Vampirism Version

1.10.7

### Incompatible mod

https://www.curseforge.com/minecraft/mc-mods/create-balanced-flight/files/4635838

### Singleplayer/Multiplayer

Both

### What happened?

balancedflight-1.20.1_v2.1.0 - prevents flying while in bat form

### Reproduce steps

1. Load single or multiplayer world
2. Get bat form
3. Attempt to fly as a bat

Result: Able to jump, but not fly

On removing balancedflight-1.20.1_v2.1.0
flight suddenly works.

**Comment by Cheaterpaul** [comment]
This is an issue in Create Balanced Flight

https://github.com/anthxnymc/BalancedFlight/issues/32

**Comment by Cheaterpaul** [comment]
#1375
