### ISSUE TITLE
[Bug]: Crash server

### ISSUE THREAD

**Issue by Reaviik** [TeamLapen/Vampirism#1376]
### Minecraft Version

1.20.1

### Forge Version

47.2.20

### Vampirism Version

1.10.7

### Modpack

https://www.curseforge.com/minecraft/modpacks/infinity-nexus-reborn

### Singleplayer/Multiplayer

Server

### What happened?

Just reporting

### Relevant log output

[crash-2024-06-06_21.55.34-server.txt](https://github.com/user-attachments/files/15688305/crash-2024-06-06_21.55.34-server.txt)

### Reproduce steps

I'm not sure

**Comment by Cheaterpaul** [comment]
I do not see a relation to Vampirism here. This looks like an issue in arclight
