### ISSUE TITLE
[Bug]: Can't infect other mobs, only players.

### ISSUE THREAD

**Issue by pirata01yt** [TeamLapen/Vampirism#1377]
### Minecraft Version

1.20.1

### Forge Version

47.3.0

### Vampirism Version

1.10.8

### Singleplayer/Multiplayer

Server

### What happened?

I became a vampire lvl 14 so now i wanna become a lord, so i got the mission and i need to infect 25 mobs, but i cant infect mobs, only other players. I've tryed to do it with the infection skill, injection, suckin all their blood, hitting them, but it doesn't work.

**Comment by Cheaterpaul** [comment]
It only works withe the infection action.
What doesn't work. Does the action trigger or is the infect action always red in the action menu? Did you try to infect the entities from behind?
