### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Maxi90909** [TeamLapen/Vampirism#1379]
### Minecraft Version

1.20.1

### Forge Version

1.20.1-47.3.1

### Vampirism Version

1.10.8

### Modpack

I created my own Modpack

### Singleplayer/Multiplayer

Singleplayer

### What happened?

Minecraft crashes on startup. I dunno why. I can't say more as the game isn't launching.
I expect the game to not crash on startup

### Relevant log output

https://pastebin.com/DYyWkLp4 <- Crash
https://pastebin.com/vPTcf7dG <- Lastest log output

### Reproduce steps

1. Start the game 
2. Crash

This is all I did. I dunno.

### Other relevant mods

https://pastebin.com/cqmZUjhN <- Modlist

**Comment by Maxi90909** [comment]
Sorry I forgot to include a titel. Crash on startup, I guess.

**Comment by Maxi90909** [comment]
Crash cause is supermartijn642corelib. But without it Minecraft loads but looks like this:
![Screenshot (19)](https://github.com/TeamLapen/Vampirism/assets/76815835/b61c7e0c-2c3c-4093-9742-e38d1189b830)

**Comment by Cheaterpaul** [comment]
I fail to see a connection to Vampirism.
