### ISSUE TITLE
Readme says to import Vampirism.iml but that file is in .gitignore

### ISSUE THREAD

**Issue by blk-addr** [TeamLapen/Vampirism#138]
The readme file says under Import > Step 4. to import Vampirism.iml, but that file is also in the .gitignore so it is not in your repo.

**Comment by maxanier** [comment]
Did you execute the previous tasks? 
`gradle setupDecompWorkspace ideaModule` should generate one for you.

It is in .gitignore, because it contains user/device specific configurations and thereby, does not help anyone else.

Did that work for you?

**Comment by maxanier** [comment]
Closing because outdated and no response
