### ISSUE TITLE
[Bug]: super high client tps

### ISSUE THREAD

**Issue by KooKooGH** [TeamLapen/Vampirism#1380]
### Minecraft Version

1.20.1

### Forge Version

47.2.20

### Vampirism Version

1.10.8

### Modpack

https://www.curseforge.com/minecraft/modpacks/all-the-mods-9

### Singleplayer/Multiplayer

Singleplayer

### What happened?

almost 20% tps usage for what!?

### Relevant log output

[2024-06-28-1.log](https://github.com/user-attachments/files/16038892/2024-06-28-1.log)

### Reproduce steps

1. become a vampire in a single world player world
2. High tps

**Comment by Cheaterpaul** [comment]
Isn't a high number of ticks per second desirable?


Given that it is a huge modpack there can be any sorts of issues causing reduced ticks per second.
Adding another mod to such a huge modpack can behave in many ways.

I can not reproduce this, do you have any evidence for this? You can use the spark profiler.

**Comment by KooKooGH** [comment]
I did use spark profiler and will report some more evidence later but almost 30% of client ticks
