### ISSUE TITLE
[Bug]: Missing Guidebook?

### ISSUE THREAD

**Issue by Anin0000** [TeamLapen/Vampirism#1383]
### Minecraft Version

1.20.1

### Forge Version

47.2.0

### Vampirism Version

unsure

### Singleplayer/Multiplayer

Singleplayer

### What happened?

I cannot for the LIFE of me find the Vampirism Guidebook or how to get started with altars and such (even in creative) and every altar or item I interact with gives me the "this is unknown to you" type message.

### Reproduce steps

1. Literally just have the mod LOL

### Other relevant mods

I use the Cave Horror Project but with a TON of added mods such as Ice and Fire, Alex's Mobs, etc

**Comment by lunofe** [comment]
To have a guidebook, you need to install the GuideAPI-VP mod.
