### ISSUE TITLE
[Bug]:    Co-authored-by: Matyrobbrt <65940752+Matyrobbrt@users.noreply.github.com>  - `21.0.39` Replace PlantType system with SpecialPlantable interface and canSustainPlant block method (#971)

### ISSUE THREAD

**Issue by ootwclyhe** [TeamLapen/Vampirism#1386]
### Minecraft Version

1.20.4+

### Forge Version

neoforge1.21#76

### Vampirism Version

vampirism@1.10.0-alpha+240623-1409

### Singleplayer/Multiplayer

Both

### What happened?

        - Vampirism (vampirism) has failed to load correctly
          java.lang.NoClassDefFoundError: net/neoforged/neoforge/common/PlantType

**Comment by Cheaterpaul** [comment]
Fixed with #1381
