### ISSUE TITLE
[Modcompat]: 

### ISSUE THREAD

**Issue by Alcatone** [TeamLapen/Vampirism#1388]
### Minecraft Version

1.20.x

### Forge Version

47.3.0

### Vampirism Version

1.10.8

### Incompatible mod

inventorypets-1.20.1-2.1.2

### Singleplayer/Multiplayer

Both

### What happened?

Bat fly dont work

### Reproduce steps

1.just try to fly with the bat mod and it not work.

**Comment by Cheaterpaul** [comment]
#1385
