### ISSUE TITLE
Vampire Flying Bugged

### ISSUE THREAD

**Issue by Telemain** [TeamLapen/Vampirism#139]
I've recently come across a problem with the bat form: it seems players are able to activate bat form day or night, and either way it results in reduced health, but not flight and not physical transformation.

[Error that appears in server console](https://gist.github.com/Telemain/f51586b3c695d52b5c4dd61bdf71354d)

[Player screenshot showing health change but no other effects](https://images.discordapp.net/.eJwNw0sOgyAQANC7sHdm-A3iZRqCBE1UCExXTe_evuR91HtcalOHSJ8b4n7O3MYOU9pItUBtrV4l9XNCbjcmkZSPuzwyUTOxphCZLfnwz2g48uookLc2eu-jQ0M6LKQXbV_GgmFwK_Snqu8Pi1ojsg.05-BAk4DEDBRBCdoFrrs_yNkaBU)

[I do have a rather ridiculous number of mods](https://gist.github.com/Telemain/595a712c8c5221c04e40962a3f876c33) but I was hoping you might be able to help me nonetheless

**Comment by maxanier** [comment]
Did not mean to close it yet.

I will upload a new alpha later today or tomorrow, so you can test if the problem is fixed

**Comment by maxanier** [comment]
Sorry, I hoped I would be able to release a new alpha with some new features by today, but it's not finished.
So please try this build (it is based on your current version, but contains a potential fix for your issue): [https://maxanier.de/maven2/de/teamlapen/vampirism/Vampirism/1.10.2-1.1.0-alpha+01-16-14-51/Vampirism-1.10.2-1.1.0-alpha+01-16-14-51.jar](https://maxanier.de/maven2/de/teamlapen/vampirism/Vampirism/1.10.2-1.1.0-alpha+01-16-14-51/Vampirism-1.10.2-1.1.0-alpha+01-16-14-51.jar)

**Comment by maxanier** [comment]
Did you try the build already?

**Comment by Telemain** [comment]
Sorry for the delay. I can confirm that bat mode now works perfectly.

**Comment by maxanier** [comment]
Perfect :)
