### ISSUE TITLE
[Bug]: Regarding the error caused by generating hunters in the wild

### ISSUE THREAD

**Issue by openthedoge** [TeamLapen/Vampirism#1390]
### Minecraft Version

1.21.x

### (Neo)Forge Version

neo 21.0.86

### Vampirism Version

1.10.0-alpha+240712

### Singleplayer/Multiplayer

Both

### What happened?

After transforming into a vampire, tents and hunters will appear in the wild, and an error message will appear when approaching a crossbow hunter. This situation applies to both single players and servers

变身吸血鬼后，野外会刷出帐篷与猎人，在靠近带弩猎人时会出现报错，单机与服务器均有这个情况

### Relevant log output

The following is the server error log以下为服务器报错日志[crash-2024-07-13_16.19.59-server.txt](https://github.com/user-attachments/files/16201390/crash-2024-07-13_16.19.59-server.txt)
The following is the single machine error log以下为单机报错日志[minecraft-exported-crash-info-2024-07-13T16-11-33.zip](https://github.com/user-attachments/files/16201392/minecraft-exported-crash-info-2024-07-13T16-11-33.zip)

### Reproduce steps

When I run around in the wilderness on the server, I will encounter a tent. When I approach, I will start refreshing the hunter, and then randomly report an error. Then, when I test in single player mode, if I place the tent in single player mode and encounter a hunter holding a crossbow, an error will be reported
当我在服务器野外乱跑时会遇到帐篷，靠近开始刷新猎人，之后随机报错，然后在单人模式中测试，单人模式放置帐篷，出现手持弩的猎人就报错

**Comment by Cheaterpaul** [comment]
duplicate #1389
