### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by warden23ou** [TeamLapen/Vampirism#1392]
### Minecraft Version

1.20.1

### (Neo)Forge Version

47.3.5

### Vampirism Version

1.10.9

### Singleplayer/Multiplayer

Singleplayer

### What happened?

Hi!my minecraft got crashed without any reasons(game froze,then black screen and game just closed itself) and ppl on forge support said that it's might be because of vampirism,i would like to get  a help :(
https://imgur.com/a/mf4eyhm - all mods that were used 

### Relevant log output

[latest.log](https://github.com/user-attachments/files/16267690/latest.log)

**Comment by Cheaterpaul** [comment]
This happened after you removed Vampirism. The log lists a lot of errors because the world was saved with Vampirism and the Vampire Forest. But that looks to be resolvable by Minecraft, but it does not indicate why it stops.

Can you load the world again when adding Vampirism?

**Comment by warden23ou** [comment]
[latest.log](https://github.com/user-attachments/files/16494731/latest.log)
[crash-2024-08-05_13.54.38-server.txt](https://github.com/user-attachments/files/16494732/crash-2024-08-05_13.54.38-server.txt)
Hi,im sorry,i didn't saw the message...i think i uploaded wrong file last time,here's what i get now..
