### ISSUE TITLE
[Bug]: Bat mode problem (modcompat problem)

### ISSUE THREAD

**Issue by TakehisaYuji** [TeamLapen/Vampirism#1397]
### Minecraft Version

1.20.1

### (Neo)Forge Version

47.2.0

### Vampirism Version

1.10.9

### Modpack

[modpack.zip](https://github.com/user-attachments/files/16405331/modpack.zip)

### Singleplayer/Multiplayer

Both

### What happened?

sometimes when flying as a bat, the bat mode just turns off for seemingly no reason.
in details: the flying itself stops but the player still remains a bat but will still take a fall damage.

### Relevant log output

log says nothing when the bug happens

### Reproduce steps

thats the worst part. i dont know what causes this bug.

you just fly around the world and randomly you just fall.
that seems to happen more often in the Ice dragon cave for some reason, but the ice and fire mod does not seem to cause this issue.

**Comment by Cheaterpaul** [comment]
do you use any mods listed here #1385?

**Comment by TakehisaYuji** [comment]
> do you use any mods listed here #1385?

no, i never used any of them. but i think i forgot to close the issue.
the problem went away after a month or so, after updating most of the mods.

still have no idea what caused this, it was probably some mod that added mobs to the caves

**Comment by Cheaterpaul** [comment]
Ok, then lets hope, that it was a bug in one of the mods and it was already fixed somewhere
