### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by nikola0921** [TeamLapen/Vampirism#1398]
### Minecraft Version

1.12.x

### (Neo)Forge Version

8.0.99.99

### Vampirism Version

1.6.2

### Singleplayer/Multiplayer

Singleplayer

### What happened?

The skilltree GUI just doesn't show up

**Comment by lunofe** [comment]
1.12.2 is out of support and this bug does not exist without other mods. You can seek help from the community on our Discord, but this won't be something we'll fix via update.
