### ISSUE TITLE
[Feature]: I hope the author or friends with relevant experience can help me

### ISSUE THREAD

**Issue by openthedoge** [TeamLapen/Vampirism#1400]
### What?

Hello, I would like to request a copy from this website from you（ https://github.com/TeamLapen/VampirismDatapackExamples ）Blood Value Space version 1.21; Forgive my poor technical skills. At first, I was looking for ways to add MOD creatures so that they could be bloodsucked, but I was not familiar with these professional knowledge. If you are willing to create a template for me in your free time so that I can add creatures or items on my own, I would be extremely grateful!

### Mod experience

No effect

### Contributions

https://github.com/TeamLapen/VampirismDatapackExamples

**Comment by maxanier** [comment]
We have to update the example and the relevant documentation eventually.
However, we are not going to create a custom file for you.
Please follow these issues to get notified when there is a new example. You can also politely try to find somebody to help you on Discord.

https://github.com/TeamLapen/VampirismDatapackExamples/issues/2
https://github.com/TeamLapen/Vampirism/issues/1411

**Comment by maxanier** [comment]
You can have a look here:
https://wiki.vampirism.dev/docs/data/bloodvalues
and at the example files here:
https://github.com/TeamLapen/Vampirism/blob/1.21/src/generated/resources/data/vampirism/data_maps/entity_type/entity_blood.json
