### ISSUE TITLE
[Bug]: Vampire forest not spawning with biome makeover

### ISSUE THREAD

**Issue by Piero3400** [TeamLapen/Vampirism#1404]
### Minecraft Version

1.20.1

### (Neo)Forge Version

47.2.17

### Vampirism Version

1.10.9

### Singleplayer/Multiplayer

Both

### What happened?

Hi , well straight to the point the vampire forest is not spawning at all , i've gone far a lot of times and use the /locate biome vampirism:vampire_forest command and it doesnt found the biome , i think this is because biome makeover mod , since i think this is the only mod that interacts with biomes that i have installled , hope i can get an answer and posible solution , and hope you all have a great day

### Reproduce steps

1,Load the single player world
2.Use /locate biome vampirism:vampire_forest 
3.Not find the biome 
4.Panic

1.Load multiplayer world
2.Explore 10000 blocks on all the axis
3.Not find the biome 
4.Panic even worse
5.Calm down and seach the github to report the bug

### Other relevant mods

Biome makeover ver. 1.20.1-1.11.4
Terralith 2.4.11
Geophilic 3.1.1
Tectonic 2.3.5a

**Comment by supermike1999** [comment]
You'll need to install Terrablender in order for the vampire forests to generate with TerraLith.
