### ISSUE TITLE
[Bug]: Server crashes while walking in vampire biome

### ISSUE THREAD

**Issue by Leiriad** [TeamLapen/Vampirism#1405]
### Minecraft Version

1.20.1

### (Neo)Forge Version

47.1.106

### Vampirism Version

1.10.9

### Modpack

https://modrinth.com/modpack/inventorium/version/H5Y98FGU

### Singleplayer/Multiplayer

Server

### What happened?

Soon after walking in the forest, the game crashes. When I reconnect, I can explore for a few seconds to a few minutes before another crash. It appears as a human and as a vampire. I tried deleting the chunk and clearing the player data, but I still have the same error. I tried removing Valkyrien Skies and Smoothchunk as they are mentionned in the crash report, but nothing changed.
This issue is similar to this one [#1399](https://github.com/TeamLapen/Vampirism/issues/1399).

### Relevant log output

[latest.log](https://github.com/user-attachments/files/16610948/latest.log)
[crash-2024-08-14_11.18.20-server.txt](https://github.com/user-attachments/files/16610949/crash-2024-08-14_11.18.20-server.txt)

### Reproduce steps

1. Load multiplayer world
2. Locate a vampire forest
3. Teleport to the forest
4. Play in the forest

**Comment by Leiriad** [comment]
I found a temporary solution [here](https://github.com/AllTheMods/ATM-9/issues/406)

**Comment by Cheaterpaul** [comment]
fixed in the latest version
