### ISSUE TITLE
[Bug]: Potential crash with breath of ender dragon

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#1408]
### Minecraft Version

1.21.x

### (Neo)Forge Version

Unknown

### Vampirism Version

1.10.0-beta1

### Singleplayer/Multiplayer

Singleplayer

### What happened?

Multiple reports on CurseForge suggest a crash when touching the purple breath fired by the Ender dragon.
Not sure if you need to be a Vampire.
The reports are not so extensive and I have not attempted to reproduce it.
Will try to do so when I find some time.

**Comment by supermike1999** [comment]
Went and created an Instance with just Vampirism-1.21-1.10.0-beta.1 on neoforge 1.21(Latest release)
I was able to recreate the crash mentioned by switching to a vampire and walking into the dragons breath, giving me this crash report

[CrashReport.txt](https://github.com/user-attachments/files/16673368/CrashReport.txt)

Update: So it crashed me while as a human, giving the same crash as before.

**Comment by maxanier** [comment]
Thank you ❤️
