### ISSUE TITLE
[Bug]: Rapid Hunter NPC Spawning

### ISSUE THREAD

**Issue by DamienNightbird** [TeamLapen/Vampirism#1409]
### Minecraft Version

1.19

### (Neo)Forge Version

43.3.7

### Vampirism Version

1.19.2

### Modpack

The Chocolate Edition - [FORGE]

### Singleplayer/Multiplayer

Singleplayer

### What happened?

It's likely been covered or explained to someone else before since I was aware it could happen but had yet to have it happen to me. I'm experiencing a bug where hunter NPCs spawn in their dozens upon loading into a new world, tanking my framerate with no way to stop them besides setting the difficulty to peaceful. I've looked in the configs for any way to change their spawn rate, but I can't find anything from the glance over I did. Not that this is necessarily a problem with Vampirism itself, as I've put it into a modpack that didn't have it originally, but I'd like to know what causes it and if it can be fixed somehow, because I love Vampirism it is by far my favorite mod to add into packs, and I'd like to enjoy some new packs I play with it, rather than struggle to render my game because hundreds of hunters are spawning at once.

### Reproduce steps

1: Download pack without Vampirism, load one or two worlds
2: Install Vampirism, Vampirism Integrations, Vampires Need Umbrellas, Vampirism - Covered Armor and Vampiric Ageing into the pack
3: Load another world with Vampirism and addons, hunters will already have spawned with even more spawning as the chunks load in

### Other relevant mods

Vampirism Integrations, Vampires Need Umbrellas, Vampirism - Covered Armor and Vampiric Ageing were all installed in the pack as well, all on 1.19.2 except Ageing which was on 1.3.17

**Comment by maxanier** [comment]
This is a problem in conjunction with SpawnBalanceUtility.
They modify the hunter spawn weight.

Workaround: Go to the config folder and open `spawnbalanceutility-common.toml`
Change the last line to start with Vampirim values
`defaultSpawnWeightList = " vampirism:hunter,0;vampirism:advanced_hunter,0;minecraft:enderman,5;minecraft:witch,5;alexsmobs:flutter,40;dungeons_mobs:wraith,20;cataclysm:deepling,5;cataclysm:deepling_angler,5;cataclysm:deepling_brute,5;minecraft:pig,40;minecraft:cow,40;minecraft:sheep,40;minecraft:chicken,40;"`

**Comment by maxanier** [comment]
For newer versions of Vampirism or SpawnBalanceUtility, this issue should not occur anymore.
https://github.com/mactso/SpawnBalanceUtility/issues/23
https://github.com/mactso/SpawnBalanceUtility/commit/f22712ac0cccf66a65be14e3ddefe05267f316de
(Also we no longer have the weight zero file in Vampirism)
