### ISSUE TITLE
Switching Night Vision to Blood Vision Crashes Client

### ISSUE THREAD

**Issue by Telemain** [TeamLapen/Vampirism#141]
The server gets a "Connection forcibly closed by remote host" error

[Client Crash Report](https://gist.github.com/Telemain/25aa8a7015445e1a8d4ff17097e97b8b)
[Modlist](https://gist.github.com/Telemain/595a712c8c5221c04e40962a3f876c33)

This crash happens both with
Vampirism-1.10.2-1.1.0-alpha+12-23-17-21
and
Vampirism-1.10.2-1.1.0-alpha+01-16-14-51
from
[#139](https://github.com/TeamLapen/Vampirism/issues/139)

**Comment by maxanier** [comment]
This is an issue with ArsMagica. It seems to be fixed in newer versions of the mod.
Try the latest version Ars Magica 2 1.5.0-15 https://github.com/Growlith1223/ArsMagica2/releases/tag/v1.5.0-15

I think it is only a coincidence that this happens when switching to blood vision.

**Comment by Telemain** [comment]
Ah I should have seen that sorry. I can confirm everything works fine with the new ars magica. Thanks for your help!

**Comment by maxanier** [comment]
No problem :) Happy to help
