### ISSUE TITLE
[Bug]: black screen

### ISSUE THREAD

**Issue by EnotScript** [TeamLapen/Vampirism#1410]
### Minecraft Version

1.21.x

### (Neo)Forge Version

21.1.23

### Vampirism Version

1.10. -beta2

### Modpack

ATM10 - https://www.curseforge.com/minecraft/modpacks/all-the-mods-10

### Singleplayer/Multiplayer

Both

### What happened?

Black screen after start minecraft.

### Relevant log output

[debug.log](https://github.com/user-attachments/files/16732085/debug.log)
[latest.log](https://github.com/user-attachments/files/16732086/latest.log)

### Reproduce steps

1. Start modpack with mod

**Comment by maxanier** [comment]
Thank you for reporting.
This is mainly an issue with SecurityCraft. It has been fixed on their side and will probably be solved with the next SecurityCraft release.
https://github.com/Geforce132/SecurityCraft/issues/538
