### ISSUE TITLE
Lan Server crashes when someone enters combat mode while being a vampirie

### ISSUE THREAD

**Issue by Snowiro** [TeamLapen/Vampirism#1414]
### Minecraft Version

1.20.x

### Forge Version

47.3.5

### Vampirism Version

1.10.9

### Incompatible mod

epicfight-forge-20.9.2-1.20.1

### Singleplayer/Multiplayer

Server

### What happened?

Playing in 1.20.1 multiplayer lan after my friend became a vampire when they enter combat mode my client crashes and whenever they join my world my game crashes again, I'm assuming its because they crashed and got stuck in combat mode while being a vampire my other friends can still join and enter combat mode.  I tried becoming a vampire while not hosting but it does not crash my game when in combat mode.

### Reproduce steps

Have Epic fight and Vampirism installed
Host lan server
Have someone be a vampire
Let them enter combat mode

### Relevant log output

```shell
Crash report and mod list https://pastebin.com/ZeVYbnEK
```

**Comment by Snowiro** [comment]
Never mind its not Epic fight, will open a new when I figure out which one causes it

**Comment by Cheaterpaul** [comment]
Looks to be something between Epic fight and Yes Steve Model

**Comment by Snowiro** [comment]
> Looks to be something between Epic fight and Yes Steve Model

Its Yes Steve model removing it solves the crash issue
