### ISSUE TITLE
[Bug]: Vampirism Server Player crash when summoning (1.21.1 NeoForge)

### ISSUE THREAD

**Issue by gamerpotion** [TeamLapen/Vampirism#1416]
### Minecraft Version

1.21.x

### (Neo)Forge Version

Vampirism-1.21-1.10.0-beta.2.jar

### Vampirism Version

Vampirism-1.21-1.10.0-beta.2.jar

### Modpack

Vagrant Saga

### Singleplayer/Multiplayer

Both

### What happened?

One of our users has reported the following for Vampirism on our modpack for NeoForge 1.21.1

Crash log - https://pastebin.com/Z3RmXwyV

```
OP 𝑀𝑜𝑑 𝐶𝑖𝑝ℎ𝑒𝑟
 — Today at 10:58 PM
with the mod vampirism if you try to use the summon one command as a Lord Hunter or vampire it completely crashes your game and kicks you out```


### Relevant log output

https://pastebin.com/Z3RmXwyV

### Reproduce steps

_No response_

### Other relevant mods

_No response_

**Comment by maxanier** [comment]
Thank you for reporting. I was able to reproduce it when calling a specific minion. Will be fixed in the next release.
