### ISSUE TITLE
[Bug]: 1.20.1 crash when you give up

### ISSUE THREAD

**Issue by robohavier** [TeamLapen/Vampirism#1418]
### Minecraft Version

1.20.1

### (Neo)Forge Version

1.20.1- 47.3.10

### Vampirism Version

1.10.10

### Singleplayer/Multiplayer

Singleplayer

### What happened?

When I clicked give up I instantly crashed but when I click resurrect I don't crash

### Relevant log output

https://pastebin.com/SQr3kr7G

### Reproduce steps

1.install mods 2.load single player world 3.die click give up and crash

### Other relevant mods

[Medieval Craft (by Ffunari2004)](https://www.curseforge.com/minecraft/mc-mods/franciscofunari)
[Toast Control (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/toast-control)
[Architectury API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Pufferfish's Skills [Forge & Fabric] (by Pufferfish)](https://www.curseforge.com/minecraft/mc-mods/puffish-skills)
[TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
[Spice of Life: Carrot Edition (by lordcazsius)](https://www.curseforge.com/minecraft/mc-mods/spice-of-life-carrot-edition)
[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[Curios API (Forge/NeoForge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
[Godly Vampirism (by maxanier)](https://www.curseforge.com/minecraft/mc-mods/godly-vampirism)
[Vampiric Ageing - A Vampirism Addon (by thedoctorofdoctoring)](https://www.curseforge.com/minecraft/mc-mods/vampiric-ageing-a-vampirism-addon)
[Random Loot Mod (by milomaz1)](https://www.curseforge.com/minecraft/mc-mods/random-loot-mod)
[Realm RPG: Fallen Adventurers (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/realm-rpg-fallen-adventurers)
[Mowzie's Mobs (by bobmowzie)](https://www.curseforge.com/minecraft/mc-mods/mowzies-mobs)
[Capsule (by Lythom)](https://www.curseforge.com/minecraft/mc-mods/capsule)
[Kobolds! (by Jusey1z)](https://www.curseforge.com/minecraft/mc-mods/kobolds)
[Crafting on a stick (by OfekN_)](https://www.curseforge.com/minecraft/mc-mods/crafting-on-a-stick)
[Majrusz Library (by Majrusz17)](https://www.curseforge.com/minecraft/mc-mods/majrusz-library)
[Epic Power Bracelets (by Lupin)](https://www.curseforge.com/minecraft/mc-mods/epic-power-bracelets)
[AzureDooms Angel Ring (by AzureDoomC)](https://www.curseforge.com/minecraft/mc-mods/azuredooms-angel-ring)
[bad packets (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/badpackets)
[ArmorPlus (by sokratis12GR)](https://www.curseforge.com/minecraft/mc-mods/armorplus)
[MobZ (by Globox_Z)](https://www.curseforge.com/minecraft/mc-mods/mobz)
[Magic Rings (by JenkiMods)](https://www.curseforge.com/minecraft/mc-mods/magic-rings)
[Reliquary Reincarnations (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/reliquary-reincarnations)
[Nature's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/natures-compass)
[Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[Enchantment Descriptions (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Enigmatic Legacy (by Aizistral)](https://www.curseforge.com/minecraft/mc-mods/enigmatic-legacy)
[Forgified Fabric API (by Su5eD)](https://www.curseforge.com/minecraft/mc-mods/forgified-fabric-api)
[SlashBlade (by flammpfeil)](https://www.curseforge.com/minecraft/mc-mods/slashblade)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Ender Trigon (by nonamecrackers2)](https://www.curseforge.com/minecraft/mc-mods/ender-trigon)
[Better Advancements (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/better-advancements)
[LevelHearts (by FireController1847)](https://www.curseforge.com/minecraft/mc-mods/levelhearts)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Epic Stats Remastered (by felinacatness)](https://www.curseforge.com/minecraft/mc-mods/epic-stats)
[Player Companions (by Kaworru)](https://www.curseforge.com/minecraft/mc-mods/player-companions)
[Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)
[Tarot Cards (by shiroroku)](https://www.curseforge.com/minecraft/mc-mods/tarot-cards)
[Rings of Ascension (Forge/NeoForge) (by focamacho)](https://www.curseforge.com/minecraft/mc-mods/rings-of-ascension)
[AzureLib (by AzureDoomC)](https://www.curseforge.com/minecraft/mc-mods/azurelib)
[Loot Bag - Renewed (by big_energy)](https://www.curseforge.com/minecraft/mc-mods/loot-bag-mod-renewed)
[Nyf's Spiders (by Nyfaria)](https://www.curseforge.com/minecraft/mc-mods/nyfs-spiders)
[Inventory Pets (by Purplicious_Cow_)](https://www.curseforge.com/minecraft/mc-mods/inventory-pets)
[FPS Reducer (by bre2el)](https://www.curseforge.com/minecraft/mc-mods/fps-reducer)
[Vampires Need Umbrellas (by focamacho)](https://www.curseforge.com/minecraft/mc-mods/vampires-need-umbrellas)
[Horror Elements mod (by predator97427fr)](https://www.curseforge.com/minecraft/mc-mods/horror-elements-mod)
[Default Skill Trees (by Pufferfish)](https://www.curseforge.com/minecraft/mc-mods/default-skill-trees)
[Medieval craft (Weapons) (by Ffunari2004)](https://www.curseforge.com/minecraft/mc-mods/medievalcraftweapons)
[Armor Set Bonuses (Forge) (by SpaceCat_97)](https://www.curseforge.com/minecraft/mc-mods/armor-set-bonuses)
[AtomicStryker's Infernal Mobs (by atomicstrykergrumpy)](https://www.curseforge.com/minecraft/mc-mods/atomicstrykers-infernal-mobs)
[Embers Rekindled (by BordListian)](https://www.curseforge.com/minecraft/mc-mods/embers-rekindled)
[Mahou Tsukai (by stepcros)](https://www.curseforge.com/minecraft/mc-mods/mahou-tsukai)
[Cloth Config API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Resourceful Lib (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)
[Werewolves - Become a Beast! (by Cheaterpaul)](https://www.curseforge.com/minecraft/mc-mods/werewolves-become-a-beast)
[THE UNDEAD REVAMPED (by punpanprolol)](https://www.curseforge.com/minecraft/mc-mods/theundead)
[ShadowizardLib (by Mindoth)](https://www.curseforge.com/minecraft/mc-mods/shadowizardlib)
[Embeddium (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/embeddium)
[Guard Villagers (by almightytallestred)](https://www.curseforge.com/minecraft/mc-mods/guard-villagers)
[Majrusz's Enchantments (by Majrusz17)](https://www.curseforge.com/minecraft/mc-mods/wonderful-enchantments)
[Not Enough Wands (by romelo333)](https://www.curseforge.com/minecraft/mc-mods/not-enough-wands)
[Divine Weaponry - Better Combat (by WoroxIV)](https://www.curseforge.com/minecraft/mc-mods/divine-weaponry)
[Placebo (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/placebo)
[Realistic Bees (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/realistic-bees)
[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
[Medieval Buildings [End Edition] (by Lupin)](https://www.curseforge.com/minecraft/mc-mods/medieval-buildings-end-edition)
[Traveller's Boots (by DenisMasterHerobrine)](https://www.curseforge.com/minecraft/mc-mods/travellers-boots)
[TheDragonLib (by sokratis12GR)](https://www.curseforge.com/minecraft/mc-mods/thedragonlib)
[Ice and Fire: Dragons (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons)
[Random Crits (by InfernalEclipse)](https://www.curseforge.com/minecraft/mc-mods/random-crits)
[Zombies More (by CaraAleatorio7)](https://www.curseforge.com/minecraft/mc-mods/zombie-more)
[Zeta (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/zeta)
[Resourceful Config (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-config)
[Snad (by TheRoBrit)](https://www.curseforge.com/minecraft/mc-mods/snad)
[Dungeon Crawl (by xiroc_)](https://www.curseforge.com/minecraft/mc-mods/dungeon-crawl)
[Epic Paladins - closed (by VeroxUniverse)](https://www.curseforge.com/minecraft/mc-mods/epic-paladins)
[Cyclops Core (by kroeser)](https://www.curseforge.com/minecraft/mc-mods/cyclops-core)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[Gateways to Eternity (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/gateways-to-eternity)
[Better Invisibility (by Purplicious_Cow_)](https://www.curseforge.com/minecraft/mc-mods/better-invisibility)
[WTHIT Forge Edition (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/wthit-forge)
[Relics (by SSKirillSS)](https://www.curseforge.com/minecraft/mc-mods/relics-mod)
[Cupboard (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/cupboard)
[AI Improvements (by QueenOfMissiles)](https://www.curseforge.com/minecraft/mc-mods/ai-improvements)
[Pufferfish's Attributes [Forge & Fabric] (by Pufferfish)](https://www.curseforge.com/minecraft/mc-mods/puffish-attributes)
[Xaero's Minimap (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)
[fix GPU memory leak[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/fix-gpu-memory-leak)
[Enemy Expansion (by InfernalStudios)](https://www.curseforge.com/minecraft/mc-mods/enemy-expansion)
[Better Respawn (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/better-respawn)
[Extra Golems (by skyjay1)](https://www.curseforge.com/minecraft/mc-mods/extra-golems)
[Model Gap Fix (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/model-gap-fix)
[Realistic Horse Genetics (by sekelsta)](https://www.curseforge.com/minecraft/mc-mods/realistic-horse-genetics)
[Starlight (Forge) (by Spottedstar)](https://www.curseforge.com/minecraft/mc-mods/starlight-forge)
[Max Health Fix (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/max-health-fix)
[Library Ferret - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/library-ferret-forge)
[Caelus API (Forge/NeoForge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/caelus)
[Pandora's Box (by Ivorius)](https://www.curseforge.com/minecraft/mc-mods/pandoras-box)
[Corail Tombstone (by Corail_31)](https://www.curseforge.com/minecraft/mc-mods/corail-tombstone)
[FLIB (by Lothrazar)](https://www.curseforge.com/minecraft/mc-mods/flib)
[Overloaded Armor Bar (by tfarecnim)](https://www.curseforge.com/minecraft/mc-mods/overloaded-armor-bar)
[Realm RPG: Pots & Mimics (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/pots-and-mimics-rpg)
[Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[Iron's Spells 'n Spellbooks (by Iron431)](https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks)
[Roots Classic (by Lothrazar)](https://www.curseforge.com/minecraft/mc-mods/roots-classic)
[Improvable Skills 3 (by Zeith)](https://www.curseforge.com/minecraft/mc-mods/improvable-skills)
[Realm RPG: Imps & Demons (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/realm-rpg-imps-demons)
[Better Combat [Fabric & Forge] (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus)
[Realm RPG: Dragon Wyrms (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/realm-rpg-dragon-wyrms)
[HammerLib (by Zeith)](https://www.curseforge.com/minecraft/mc-mods/hammer-lib)
[Vampirism - Become a vampire! (by maxanier)](https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire)
[Vampirism Integrations (by maxanier)](https://www.curseforge.com/minecraft/mc-mods/vampirism-integrations)
[AmbientSounds 6 (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/ambientsounds)
[Handcrafted (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/handcrafted)
[EverlastingAbilities (by kroeser)](https://www.curseforge.com/minecraft/mc-mods/everlastingabilities)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[The Conjurer (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/the-conjurer)
[OctoLib (by SSKirillSS)](https://www.curseforge.com/minecraft/mc-mods/octo-lib)
[McJtyLib (by McJty)](https://www.curseforge.com/minecraft/mc-mods/mcjtylib)
[Better Villages - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/better-village-forge)
[MCA Reborn [Fabric/Forge] (by jahx_senpoopie)](https://www.curseforge.com/minecraft/mc-mods/minecraft-comes-alive-reborn)
[Nameless Trinkets (by Cozary)](https://www.curseforge.com/minecraft/mc-mods/nameless-trinkets)
[Loot Integrations[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/loot-integrations)
[Structure Gel API (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/structure-gel-api)
[ConRad's Scary Spiders (by ConRad)](https://www.curseforge.com/minecraft/mc-mods/conrads-scary-spiders)
[Abyssal Decor (by starrysock)](https://www.curseforge.com/minecraft/mc-mods/abyssal-decor)
[Enderman Overhaul (by joosh_7889)](https://www.curseforge.com/minecraft/mc-mods/enderman-overhaul)
[Lucky Block (by player_in_distress)](https://www.curseforge.com/minecraft/mc-mods/lucky-block)
[Traveler's Backpack (by Tiviacz1337)](https://www.curseforge.com/minecraft/mc-mods/travelers-backpack)
[Vanilla Expanded - Orcz (by duke2die4)](https://www.curseforge.com/minecraft/mc-mods/orcz)
[Serene Seasons (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/serene-seasons)
[Better chunk loading[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/better-chunk-loading-forge-fabric)
[Apothic Attributes (AttributesLib) (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/apothic-attributes)
[Necronomicon API (by ElocinDev)](https://www.curseforge.com/minecraft/mc-mods/necronomicon)
[Dynamic Lights (by atomicstrykergrumpy)](https://www.curseforge.com/minecraft/mc-mods/dynamic-lights)
[Fast Leaf Decay (by olafskiii)](https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Alex's Mobs (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)
[Bone Zone (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bone-zone)
[Quark (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark)
[Grimoire of Gaia (by Silentine_)](https://www.curseforge.com/minecraft/mc-mods/grimoire-of-gaia)
[Apple Cows (by TrueRealCursed_Warrior)](https://www.curseforge.com/minecraft/mc-mods/apple-cows)
[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[Traveler's Compass (by nNined)](https://www.curseforge.com/minecraft/mc-mods/travelers-compass)
[Ars Nouveau (by baileyholl2)](https://www.curseforge.com/minecraft/mc-mods/ars-nouveau)
[Searchables (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/searchables)
[Ore Excavation (by Funwayguy)](https://www.curseforge.com/minecraft/mc-mods/ore-excavation)
[Guide-API Village and Pillage (by maxanier)](https://www.curseforge.com/minecraft/mc-mods/guide-api-village-and-pillage)
[Configured (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/configured)
[Untamed Wilds (by raytrace82)](https://www.curseforge.com/minecraft/mc-mods/untamedwilds)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[Blood And Madness (A Bloodborne Inspired Mod) (by Nitespring)](https://www.curseforge.com/minecraft/mc-mods/blood-and-madness)
[Cosmetic Armor Reworked (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
[ExpandAbility (by florensie)](https://www.curseforge.com/minecraft/mc-mods/expandability)
[Mythic Mounts (Forge) (by chirpycricket__)](https://www.curseforge.com/minecraft/mc-mods/mythic-mounts-forge)
[ProjectE (by SinKillerJ)](https://www.curseforge.com/minecraft/mc-mods/projecte)
[Eldritch End (by ElocinDev)](https://www.curseforge.com/minecraft/mc-mods/eldritch-end)
[Regrowth (by MacTso)](https://www.curseforge.com/minecraft/mc-mods/regrowth)
[Connectivity[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/connectivity)
[Biomes O' Plenty (by Forstride)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)
[Attributizer (by TheRealJackiecrazy)](https://www.curseforge.com/minecraft/mc-mods/attributizer)
[Naturalist (by Starfish_Studios)](https://www.curseforge.com/minecraft/mc-mods/naturalist)
[Colorful Hearts (by Terrails)](https://www.curseforge.com/minecraft/mc-mods/colorful-hearts)
[EvilCraft (by kroeser)](https://www.curseforge.com/minecraft/mc-mods/evilcraft)

**Comment by maxanier** [comment]
The log more or less ends with `After robohavier32 was slain by Heavy Knight, they gave up`
I can't see a crash.

Can you provide the crash-report (usually in a crash-report folder).
