### ISSUE TITLE
[Bug]: channel issue

### ISSUE THREAD

**Issue by aclarityV** [TeamLapen/Vampirism#1424]
### Minecraft Version

1.21.x

### (Neo)Forge Version

21.1.59

### Vampirism Version

1.21.1

### Singleplayer/Multiplayer

Server

### What happened?

I keep trying to run vampirism on my server and whenever I try to join it says that: channel name (vampirism: sundamage) failed to connect: This channel is missing on the server side, but required on the client!

I've tried to fix it myself but I've gotten no where

### Reproduce steps

1. Install the Craftoria modpack
2. add vampirism to the pack
3. try to load into the server.

**Comment by maxanier** [comment]
Just to confirm, do you have the identical Vampirism Jar installed on both server and client?
And what is the exact Vampirism version? You specified 1.21.1, but there should be more like 1.10.?-beta.?

**Comment by aclarityV** [comment]
Yes identical versions installed on both, it's the 1.10.0 beta.2 for neoforge

**Comment by aclarityV** [comment]
Is vampirism more like a plugin rather than a mod?

**Comment by supermike1999** [comment]
Vampirism is a mod

**Comment by aclarityV** [comment]
I was just thinking if the server were treating it like a plugin that might be it

**Comment by maxanier** [comment]
A quick test with just Vampirism and in Dev environment did not reproduce the issue. 
I did not have time to further investigate it today

**Comment by Cheaterpaul** [comment]
The sundamage package was marked registered to the configuration and play channel, although it only needed to be registered to the play channel. This fixes it, but it do not know why this should pose an issue here. It seems like there, it looks to me like there is not everything correct with the server.
But it is fixed for now.
