### ISSUE TITLE
[Bug]: Night Vision Potion status UI display error

### ISSUE THREAD

**Issue by nmsl123467** [TeamLapen/Vampirism#1426]
### Minecraft Version

1.20.1

### (Neo)Forge Version

47.3.7

### Vampirism Version

1.10.10

### Singleplayer/Multiplayer

Singleplayer

### What happened?

As shown in the picture, the night vision potion status UI is blank, but other potion UIs do not have this problem. After disabling this mod, everything returns to normal.
![2024-10-01_08 21 58](https://github.com/user-attachments/assets/2ac73d64-70f1-4ab6-895a-3351e709e053)

### Reproduce steps

1. Load a single player world
2. Drink a night vision potion and check the status UI
3. Drink other potions and compare them with the night vision potion UI

**Comment by Cheaterpaul** [comment]
The night vision is not supposed to show at all, because as a vampire it should be considered the default. Unfortunately there is not a clear way to do this, so that is works for every case.

**Comment by nmsl123467** [comment]
> The night vision is not supposed to show at all, because as a vampire it should be considered the default. Unfortunately there is not a clear way to do this, so that is works for every case.



> The night vision is not supposed to show at all, because as a vampire it should be considered the default. Unfortunately there is not a clear way to do this, so that is works for every case.

ok I thought it was a bug lol

**Comment by nmsl123467** [comment]
> The night vision is not supposed to show at all, because as a vampire it should be considered the default. Unfortunately there is not a clear way to do this, so that is works for every case.

ok I thought it was a bug lol

**Comment by maxanier** [comment]
Not ideal, but not that big of an issue
