### ISSUE TITLE
Vampires Spawning in Light

### ISSUE THREAD

**Issue by SuperSaiyanSolar** [TeamLapen/Vampirism#143]
I don't really know if this is a feature or a bug, but Vampires have been spawning in light levels that are higher than those of normal mobs- basically spawning in my house and putting my pets at risk.

I just wanted to kind of suggest a config option if this is a feature, or report this if it was a bug. Any further information can be provided, it'd just be nice to put a stop to these blood-sucking monsters spawning inside my own home.

Thanks in advance for your time.

**Comment by maxanier** [comment]
Thank you for the report.
I thought I already disabled vampire spawning in lit areas, but maybe it does not work.

What version of Vampirism are you using?

**Comment by SuperSaiyanSolar** [comment]
We're using version 1.0.3 for Minecraft 1.10.2

**Comment by maxanier** [comment]
Thank you.
The "fix" for this is not included in that version. :/
But it is in the newer alpha version and will be in the next release.
