### ISSUE TITLE
[Modcompat]: PMMO key conflect causes client crash

### ISSUE THREAD

**Issue by schindlershadow** [TeamLapen/Vampirism#1439]
### Minecraft Version

1.12.x

### Forge Version

Neoforge 21.1.61

### Vampirism Version

1.10.0

### Incompatible mod

Project MMO

### Singleplayer/Multiplayer

Both

### What happened?

P key is conflected by default with both mods and when pressed crashes the client

### Relevant log output

```shell
https://pastebin.com/raw/gX6WWnyR
```

**Comment by Cheaterpaul** [comment]
Duplicate of #1432

**Comment by Cheaterpaul** [comment]
Nothing to do about key conficts, you can change them yourself
