### ISSUE TITLE
[Bug]: unknown crash

### ISSUE THREAD

**Issue by KzKrit** [TeamLapen/Vampirism#1443]
### Minecraft Version

1.20.1

### (Neo)Forge Version

47.3.7

### Vampirism Version

1.10.11

### Singleplayer/Multiplayer

Singleplayer

### What happened?

My game suddenly crashed and my crash-report tell me that..

Suspected Mod: 
	Vampirism (vampirism), Version: 1.10.11
		Issue tracker URL: https://github.com/TeamLapen/Vampirism/issues
		at TRANSFORMER/vampirism@1.10.11/de.teamlapen.vampirism.entity.ai.goals.AttackMeleeNoSunGoal.m_8036_(AttackMeleeNoSunGoal.java:47)

### Relevant log output

[crash-2024-10-24_20.19.42-server.txt](https://github.com/user-attachments/files/17522136/crash-2024-10-24_20.19.42-server.txt)
[latest.log](https://github.com/user-attachments/files/17522137/latest.log)

**Comment by benolot** [comment]
Heya, my friend had this crash today happen a bunch on the server - log attached.
[crash-2024-10-23_13.18.04-server.txt](https://github.com/user-attachments/files/17528202/crash-2024-10-23_13.18.04-server.txt)

When I took a quick look, and I appreciate I am most likely incredibly wrong here as I'm no Java dev nor an MC Modder but it looks like this got fixed on the 1.20.6 branch (`Path path = ((MeleeAttackGoalAccessor) this).getPath();`) and never backported to the 1.20.1 branch (`Path path = this.path;`).
