### ISSUE TITLE
[Bug]: The server closes when a player vampire of level 6 enter

### ISSUE THREAD

**Issue by pikpow** [TeamLapen/Vampirism#1444]
### Minecraft Version

1.21.x

### (Neo)Forge Version

1.21.1 (73)

### Vampirism Version

1.10.0

### Modpack

https://drive.google.com/drive/folders/1ABm4sAo_U0NXiRLc3EvrtsK4U4a0k5Fb?usp=sharing

### Singleplayer/Multiplayer

Server

### What happened?

https://mclo.gs/EDIVKQq
the error crash 

### Relevant log output

https://mclo.gs/EDIVKQq

### Reproduce steps

1º enter to multiplayer 
2º enter the world 
3º server crarsh

**Comment by Cheaterpaul** [comment]
Vampirism tries to hurt an entity here, but Tombstone produces this specific error when handling the damage.

**Comment by Corail31** [comment]
@pikpow @Cheaterpaul It has been fixed in 9.1.5 (fixes to capture with a Receptacle of Familiar when the player owner is offline), so it can be closed.
