### ISSUE TITLE
/vtest entity command not working in 1.10.2

### ISSUE THREAD

**Issue by spraaq** [TeamLapen/Vampirism#145]
Gives an unknown command error.

**Comment by maxanier** [comment]
Sorry, I forgot to update the wiki. You have to use "/vampirism-test entity" now. Thx for reporting this

**Comment by spraaq** [comment]
Okay, I compiled an entity list for GoG 3 and sent it to you. It dosen't seemd to work in the config way but the entity names are probably correct anyway.

**Comment by maxanier** [comment]
Perfect :)
Do you want to send it to me (either upload to pastebin and put a link here, or dev@maxgb.de), so others can use it as well?

**Comment by spraaq** [comment]
I sent an e-mail yesterday, but since than I added Sophisticated wolves support too (and a missed GoG creature), so here is the pastebin.

http://pastebin.com/bzB0sEni

**Comment by maxanier** [comment]
Thank you very much, I've added the values, they will be automatically loaded as of the next version, if the respective mod is installed.
(You can still override them in the txt file, if you want to change any)
