### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Ciellix** [TeamLapen/Vampirism#1450]
### Minecraft Version

1.21.x

### (Neo)Forge Version

21.1.79

### Vampirism Version

1.10.0

### Modpack

https://legacy.curseforge.com/minecraft/modpacks/edge-of-chaos

### Singleplayer/Multiplayer

Server

### What happened?

Not sure if this is a bug, or if its meant too be like this, but when drinking blood from adult mobs your blood bar fills up, but drinking blood from baby mobs does not fill your blood bar

### Reproduce steps

Load up the mod(idk if its mod issue or pack issue or just a config issue) become a vampire, try drinking blood from baby mobs

### Other relevant mods

only other vampire related mods we are using are 
Vampiric Ageing - A Vampirism Addon
Bloodlines - A Vampirism Addon
Vampire's Delight

**Comment by Cheaterpaul** [comment]
Can confirm. Yes, baby creatures have blood, but it is so less that you would drink ~ 1/3 blood. But that can not be handled by the current system, thus you do not receive any blood but the creature loses some blood.

Just make sure to let them grow before using them as your food source.
