### ISSUE TITLE
[Bug]: advanced vampire names

### ISSUE THREAD

**Issue by kaboom24** [TeamLapen/Vampirism#1461]
### Minecraft Version

1.20.1

### (Neo)Forge Version

47.3.0

### Vampirism Version

1.10.11

### Singleplayer/Multiplayer

Singleplayer

### What happened?

advanced vampires no longer have custom names and textures they are just called advanced vampire and have one texture.

### Reproduce steps

1. load singleplayer world
2. summon advanced vampire
3. look at it
4. see error

### Other relevant mods

Rats
sbom_xela
Rats-1.20.1-8.1.3.jar

The Bumblezone (NeoForge/Forge)
telepathicgrunt
the_bumblezone-7.5.5+1.20.1-forge.jar

Vampires Need Umbrellas
focamacho
VampiresNeedUmbrellas-1.20.1-1.0.1.jar

Vampirism - Become a vampire!
maxanier
Vampirism-1.20.1-1.10.11.jar

Waystones
BlayTheNinth
waystones-forge-1.20-14.1.6.jar

WorldEdit
sk89q
worldedit-mod-7.2.15.jar

**Comment by Cheaterpaul** [comment]
should be temporarily working again

**Comment by Cheaterpaul** [comment]
Is fixed
