### ISSUE TITLE
Vampires not spawning at all

### ISSUE THREAD

**Issue by Arkade117** [TeamLapen/Vampirism#149]
Acknowledging that this may be an issue on my end, i'm running a modded forge server for around 5 people with a handful of mods and for some reason vampires aren't spawning in any biome. I'm running version 1.10.2 and I've used several different versions of the vampirism mod to see if it was just a bug. To no avail I can't seem to find any vampires while every other aspect of the mod works perfectly. It's such an awesome mod but it's almost impossible to progress without vampires spawnying, any ideas?

**Comment by LemADEC** [comment]
Vampires are spawning just right in our modpack, you just need to adjust the spawn rate of other mods that are using insane values.

**Comment by Arkade117** [comment]
Hmm, that sounds like it could be the reason although ghosts are spawning A LOT. How would I go about doing that?

**Comment by LemADEC** [comment]
That's up the related 'ghost' mod configuration

**Comment by Arkade117** [comment]
Huh? Sorry i'm really lost when it comes to messing with the config files. lol

**Comment by maxanier** [comment]
I assume you are referring to the ghosts added by Vampirism in the Vampire Forest? (not sure how we came up with the idea of adding ghosts to Vampirism btw  :D).

I really do not like the spawning system in Minecraft. It somehow almost always causes trouble when multiple mods are used and is quite hard to debug.
Regarding your issue, could you post your mod list, one is probably interfering with the vampire spawn.
Maybe I can spot a suspicious one.

**Comment by LemADEC** [comment]
The other mod has put a default weight too high, that's a configuration to fix in the other mod.

**Comment by maxanier** [comment]
Still waiting for some kind of response.
Is this not an issue anymore or can you provide a mod list?

**Comment by LemADEC** [comment]
it's an issue on his end, you can probably close this one

**Comment by maxanier** [comment]
how do you know that? Do you know him or his mod setup?

**Comment by LemADEC** [comment]
I had to fix this kind of issues multiple times, it's a classic misunderstanding by mod/modpack authors on how mob spawning works and giving too much weight to certain mob types.

**Comment by maxanier** [comment]
Yes, sometimes that is actually the problem, but sometimes not. Spawning is an annoying thing to work on, so I'm not always sure if it works correctly in Vampirism.
So I would like to take a short look on the mod list, maybe it is something else (probably not).
But if we don't get any kind of response from @Arkade117 I will close this.

**Comment by HeberonYT** [comment]
Hi, I have this same problem, no kind of entity generated in the vampire forest, nothing.
But I have detected that when removing the mod "Mob Mash" all the vampires come back to spawn, I already reported it to the author of the other mod but I have not received an answer yet.
I'm using a server in version 1.11.2

**Comment by LemADEC** [comment]
the original issue was confirmed as fixed, please open a new one for you specific case.
Also, please do link to the other issue you're referring to

**Comment by Gaple2007** [comment]
Hi, I have the same issue and tried a lot of things that didin't work. Can you guys help me?
