### ISSUE TITLE
Nullpointer in WorldGenVampirism

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#15]
There is a error report about a nullpointer exception in WorldGenVampirism in v0.3.1 at this line:
https://github.com/TeamLapen/Vampirism/blob/v0.3.1/src/main/java/de/teamlapen/vampirism/generation/WorldGenVampirism.java#L40

I'm not sure why it occurs, but a try-catch should fix it.

Report: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2364443-vampirism-become-a-vampire?comment=47

**Comment by wildbill22** [comment]
Added a try/catch block around code in addEntities. This is probably a bug in Minecraft, but this should prevent the crash.
