### ISSUE TITLE
ReflectionHelper lag

### ISSUE THREAD

**Issue by LemADEC** [TeamLapen/Vampirism#151]
ReflectionHelper is intended for one time use, typically at boot. It appears the mod is using it every tick for vampires, this is causing lag due to the constant lookup in the (de)obfuscation tables.
Instead, you can cache the property accessor and directly reuse it, saving a lot of CPU time.

Profiler shows up notably here:
https://github.com/TeamLapen/Vampirism/blob/86897dd9b0a9e0e4cdeb2732861c6cfb21475126/src/main/java/de/teamlapen/vampirism/player/vampire/BloodStats.java#L100

I wouldn't be surprise to see here too:
https://github.com/TeamLapen/Vampirism/blob/474f807f0532976ce67ae3564089737154f714fe/src/main/java/de/teamlapen/vampirism/entity/ai/EntityAIAttackMeleeNoSun.java#L38
https://github.com/TeamLapen/Vampirism/blob/6aaf52571b40fe562f0cba75abd71ff9a4f4f900/src/main/java/de/teamlapen/vampirism/client/render/RenderHandler.java#L139

**Comment by maxanier** [comment]
Oh, thanks for reporting this. I did not think it would cause a noticeable amount of lag.
I planned to use AccessTransformers to avoid having to use Reflection, but there always was a severe problem with that when I tried to do so, not sure what it was though. 
But caching the accessor sounds like a good idea, I will try to implement that.

Thank you very much for investigating this issue and your suggestion.

**Comment by maxanier** [comment]
Caching the fields did help to improve the performance a little bit.
In my test scenario it got the blood update tick time down from 0.11% to 0.05% (with one player).
Using ATs to avoid Reflection completely would get it down to about 0.03%.
Same goes for the EntityAttackSunNoMelee.

Maybe I will give ATs another try in 1.11.
