### ISSUE TITLE
Howling Moon Compatibility 

### ISSUE THREAD

**Issue by Rookie873** [TeamLapen/Vampirism#152]
when you are a vampire player and get infected by a werewolf then transform it causes the game to crash and makes you lose all your stuff think you can fix that?

**Comment by maxanier** [comment]
Thx for reporting this, I will investigate this issue

**Comment by maxanier** [comment]
Are you using the latest alpha or the 1.0 version?

**Comment by maxanier** [comment]
I need your support to fix this issue. So pls answer

**Comment by Rookie873** [comment]
it was for the 1.7.10 version but an idea how about a werepyre addon which
means you would have to work with the developer of the howling moon mod.
Sound like a good idea?

**Comment by maxanier** [comment]
Ok, since I'm not supporting the 1.7.10 version anymore I cannot help you, but maybe the author of the Howling Moon mod still does.

Regarding future mod compatibility between Vampirism and Howling Moon. What kind of interaction would you suggest? (E.g. werewolves attack vampire hunter but not vampires)

**Comment by Rookie873** [comment]
maybe werewolves and vampires would fight each other also vampire players
and werewolf players should be immune to either infection or if a werepyre
is possible it would have to be a player not fully infected yet by a
vampire then gets attacked by a werewolf (easier option i think). if you
were able to work with the owner of the howling moon mod maybe awesome
things could happen.

**Comment by LatentDesire** [comment]
I second this. If you've got the misfortune to be attacked by vampires and werewolves in the same night, it should result in something special. (Provided you manage to survive both encounters. Lol

**Comment by maxanier** [comment]
https://github.com/Razmen/HowlingMoon/issues/4

**Comment by maxanier** [comment]
Was moved here https://github.com/TeamLapen/VampirismIntegrations/issues/3

Howling Moon seems to be dead though

**Comment by UnlimitedTurtlez** [comment]
how do i set it so that players cant be both wolf and vampire?

**Comment by Luandhe** [comment]
O mod howling Moon ainda está sendo atualizado?

**Comment by Luandhe** [comment]
?
