### ISSUE TITLE
[suggestion] a mechanic for vampires similar to spice of life's food variety/diminishing returns

### ISSUE THREAD

**Issue by macks2008** [TeamLapen/Vampirism#155]
I was thinking maybe the villagers would have random blood types based on real life? This idea came to mind because my server is using spice of life and I'd hate for people to choose the Vampirism branch of the mod just to avoid Spice of Life's diminishing returns. What do you think?

**Comment by maxanier** [comment]
Different blood types were suggested a few tiems, and would be an interesting feature probably. But there are too many other things I have/want to implement first, so I do not have time for this :/
