### ISSUE TITLE
Cannot remove blood from blood container, instead getting empty blood bottle

### ISSUE THREAD

**Issue by macks2008** [TeamLapen/Vampirism#157]
I can put blood in just fine, but when I try to take it back out, no blood is removed and instead of the bottle filling it becomes a "Blood Bottle" but remains empty. Furthermore you don't seem to have any failsafe code (although you do have a recipe) to turn a Blood Bottle that can't be drank back to a normal one.

neither of these do anything when I try to drink them.
![2017-04-08_15 04 28](https://cloud.githubusercontent.com/assets/7110033/24831976/3a33932c-1c73-11e7-90a6-c3079b7b4619.png)
![2017-04-08_15 04 35](https://cloud.githubusercontent.com/assets/7110033/24831979/509cad1a-1c73-11e7-87f9-9aca700fb1de.png)

**Comment by maxanier** [comment]
So you tried sneaking, but it only converts the bottle and does nothing else?
Maybe another mod is interfering. Can you pls post your log file after trying to fill the bottle and your version of Vampirism? Thx

**Comment by macks2008** [comment]
exactly, and will do. Just let me start Minecraft from scratch so the log isn't quite as massive XD.
this was on a server I set up, but I expect it'll also happen in single player, unless SpongeForge is causing an issue somehow. If I can't get it to happen in singleplayer, I'll also give you the server log, obviously

**Comment by macks2008** [comment]
I couldn't reproduce it, even on the server. Maybe I was doing something wrong, or maybe I removed or updated the conflicting mod. ¯\_(ツ)_/¯

**Comment by maxanier** [comment]
¯\(ツ)/¯, ok, so I will close this issue

**Comment by macks2008** [comment]
@maxanier I'd like to reopen the issue, as the bug in question is currently happening for me. It seems it might have something to do with trying to fill a blood bottle when I'm already full on hunger, although I can't be sure. I hold shift and right-click on the tank that has blood, but it only converts the bottle, and doesn't fill it

**Comment by macks2008** [comment]
examining the NBT data of my inventory, the resulting blood bottles have neither damage value nor NBT metadata

**Comment by maxanier** [comment]
OK, Can you pls post your log file after trying to fill the bottle and share your version of Vampirism and Forge? Thx

**Comment by macks2008** [comment]
will do, once I get the chance.

**Comment by macks2008** [comment]
https://gist.github.com/macks2008/ab23749c233831bc865c3cc0c2360c36
https://gist.github.com/macks2008/9b14ddb41a900ff8e8f3f03a845a4b0b

**Comment by maxanier** [comment]
Thanks for the logs.
Unfortunately I'm still unable to find the issue or even reproduce it.
I've created a test version with some verbose logging. Can you please reproduce the issue and then send me the last few (maybe 50) lines of the log (sever side should be sufficient). Thx
https://server1.maxgb.de/s/cZGb530F0y4YzJ6

**Comment by macks2008** [comment]
Okay, will do.

**Comment by macks2008** [comment]
@maxanier here you go. https://gist.github.com/macks2008/880eca6c05f606270509444c723f2d39

**Comment by macks2008** [comment]
oh! I found a triggering condition. This seems to happen when I have something in my offhand, like a torch.

**Comment by maxanier** [comment]
Thank you very much :)
I did not mind that an offhand item might interfere.
If holding an item in the offhand (like a torch) disallows block interactions while sneaking even if the main hand item allows it.

Solution is to force block interaction during the block interact event.

Fix will be included in the next release. Many thanks for your investiations.

**Comment by macks2008** [comment]
@maxanier Bailey's Dailies

**Comment by macks2008** [comment]
@maxanier I should also note that this is the only weirdness I've noticed with offhand items. Shift right clicking on the altar of inspiration is also affected. Both hands have to be empty as is, where as it might be possible to only require the main hand to be empty.
As far as helping you bug hunt, it was my pleasure. I want the bug fixed about as much as you do :-)

**Comment by maxanier** [comment]
There are several issues with sneak right clicking, so I have decided to disable the sneak requirement for the altars. Activation is then done by righ clicking them with an empty hand.
But this will come with Version 1.2 not 1.1 as it needs an updated GuideBook etc.
