### ISSUE TITLE
Bat Mode Bug

### ISSUE THREAD

**Issue by EmkoCZ** [TeamLapen/Vampirism#158]
Idk how but sometimes Bat mode bugs, I will not transform into bat or health will bug, (ITS ON SERVER)
Avoided by Creeper is not working on servers (Atleast for my server)

BTW This mod is awesome!!!!!!!!!!!!!

**Comment by maxanier** [comment]
Happy that you like this mod :)
But I need a more detailed description of the problem and/or the log file of the server after the bug happened.

**Comment by maxanier** [comment]
Closing since no response. Create a new issue with a more detailed descriptions if the issue persists.
