### ISSUE TITLE
Crash, odd interaction with another mod.

### ISSUE THREAD

**Issue by omegadmm** [TeamLapen/Vampirism#163]
## Versions
- Minecraft: 1.10.2                   
- Forge:  2281                     
- Vampirism:  Vampirism-1.10.2-1.1.0-beta.2                                           

## Issue Description
A crash with another mod occurred when it's entity? interacted with a block from this mod. The other mod's author has been informed.

## Reproduce Steps
Use Coroutil coremod and weather2 mod with this mod and wait for a tornado to actually effect the item: BlockTentMain.java:29. Game ran fine until this event occurred. 

## Additional Information
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Bloodmoon-MC1.10.2-1.5.1.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.10.2-3.3.8.0.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 4/30/17 11:02 AM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at de.teamlapen.vampirism.blocks.BlockTentMain.func_180663_b(BlockTentMain.java:29)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:565)
	at net.minecraft.world.World.func_180501_a(World.java:331)
	at weather2.weathersystem.storm.TornadoHelper.tick(TornadoHelper.java:155)
	at weather2.weathersystem.storm.StormObject.tick(StormObject.java:438)
	at weather2.weathersystem.WeatherManagerBase.tick(WeatherManagerBase.java:133)
	at weather2.weathersystem.WeatherManagerServer.tick(WeatherManagerServer.java:52)
	at weather2.ServerTickHandler.onTickInGame(ServerTickHandler.java:87)
	at weather2.EventHandlerFML.tickServer(EventHandlerFML.java:30)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_143_EventHandlerFML_tickServer_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 171554328 bytes (163 MB) / 921812992 bytes (879 MB) up to 3177644032 bytes (3030 MB)
	JVM Flags: 23 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:ParallelGCThreads=5
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2281 Optifine OptiFine_1.10.2_HD_U_D7 31 mods loaded, 31 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2281.jar) 
	UCHIJAAAA	Forge{12.18.3.2281} [Minecraft Forge] (forge-1.10.2-12.18.3.2281.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAAAA	dmonsters{1.15} [Deadly Monsters] (1.10.2_deadly_monsters_1.5.jar) 
	UCHIJAAAA	bettercombatmod{1.4.0} [Better Combat] ([MC 1.10.X] BetterCombatMod 1.4.jar) 
	UCHIJAAAA	bloodmoon{1.5.1} [Bloodmoon] (Bloodmoon-MC1.10.2-1.5.1.jar) 
	UCHIJAAAA	extendedrenderer{v1.0} [Extended Renderer] (coroutil-1.10.2-1.1.16.jar) 
	UCHIJAAAA	coroutil{1.10.2-1.1.16} [CoroUtil Library] (coroutil-1.10.2-1.1.16.jar) 
	UCHIJAAAA	configmod{v1.0} [Extended Mod Config] (coroutil-1.10.2-1.1.16.jar) 
	UCHIJAAAA	dispensergun{1.10-0.1} [Dispenser Gun] (Dispenser-Gun-Mod-1.10.2.jar) 
	UCHIJAAAA	DurabilityShow{3.1.1} [Durability Show] (Durability Show-1.9.4-3.1.1.jar) 
	UCHIJAAAA	dsurround{3.3.8.0} [§3Dynamic Surroundings] (DynamicSurroundings-1.10.2-3.3.8.0.jar) 
	UCHIJAAAA	epicsiegemod{11.0.156} [Epic Siege Mod] (EpicSiegeMod-11.0.156.jar) 
	UCHIJAAAA	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHIJAAAA	JEI{3.14.7.419} [Just Enough Items] (jei_1.10.2-3.14.7.419.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.4.6} [JourneyMap] (journeymap-1.10.2-5.4.6.jar) 
	UCHIJAAAA	kagic{1.7.16} [KAGIC] (KAGIC-1.7.16.jar) 
	UCHIJAAAA	levels{r1.2.8} [Levels] (Levels 2-1.10.2-r1.2.8.jar) 
	UCHIJAAAA	missing_pieces{4.1.3} [Missing Pieces] (missing_pieces-1.10.2-4.1.3.jar) 
	UCHIJAAAA	mobends{0.22.5} [Mo'Bends] (mobends-0.22.5_for_MC-1.10.2.jar) 
	UCHIJAAAA	subcommonlib{1.1.3.0} [Subaraki's Common Library] (sublib-1.10.2-1.1.3.0.jar) 
	UCHIJAAAA	petbuddy{1.10.2 2.3.1.1} [Pet Buddy] (petbuddy-beta-1.10.2-2.3.1.1.jar) 
	UCHIJAAAA	StellarAPI{0.5.4.1.4} [Stellar API] (Stellar API-0.5.4.1.4.jar) 
	UCHIJAAAA	stellarsky{0.5.5.1.9} [Stellar Sky] (Stellar Sky-0.5.5.1.9.jar) 
	UCHIJAAAA	terraincontrol{2.8.2-SNAPSHOT} [TerrainControl] (terraincontrol-forge-2.8.2-1.10.2-B1.jar) 
	UCHIJAAAA	torohealthmod{1.10.2-7} [ToroHealth Damage Indicators] (torohealth-1.10.2-7.jar) 
	UCHIJAAAA	vampirism{1.1.0-beta.2} [Vampirism] (Vampirism-1.10.2-1.1.0-beta.2.jar) 
	UCHIJAAAA	teamlapen-lib{1.1.0-beta.2} [TeamLapen Library] (Vampirism-1.10.2-1.1.0-beta.2.jar) 
	UCHIJAAAA	weather2{1.10.2-2.4.10} [Localized Weather & Storms] (weather2-1.10.2-2.4.10.jar) 
	UCHIJAAAA	zombieawareness{1.10.2-1.11.7} [Zombie Awareness] (zombieawareness-1.10.2-1.11.7.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Bloodmoon-MC1.10.2-1.5.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.10.2-3.3.8.0.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Lord_Sombra'/281, l='New World-', x=327.30, y=66.00, z=130.67]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.10.2_HD_U_D7
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13474 Compatibility Profile Context 22.19.157.3
	OpenGlRenderer: AMD Radeon HD 7800 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 6

**Comment by maxanier** [comment]
Weather2 seems to be doing some strange things there, but Vampirism's code was missing something too.
This should be solved with the next version of Vampirism.
