### ISSUE TITLE
Sleeping player fly away when its coffin gets broken

### ISSUE THREAD

**Issue by LemADEC** [TeamLapen/Vampirism#165]
## Versions
- Minecraft:                 1.10.2
- Forge:                       1.10.2-12.18.3.2254
- Vampirism:               1.10.2-1.1.0-beta.2

## Issue Description
Player A is a vampire sleeping in his coffin
Player B breaks the coffin
Player A remains in a sleep position, flying away through blocks
If Player A click 'wake up', he/she'll take fall damage.

## Reproduce Steps
see above

## Additional Information
n/a

**Comment by maxanier** [comment]
What do you think about your face (minecraft skin one of course) appearing on a Advanced Vampire Hunter named "Bug Hunter" or "The Bug Hunter" ingame?

**Comment by LemADEC** [comment]
I'm good, thanks :)
