### ISSUE TITLE
Animal Net from Hatchery Mod resets animal blood level

### ISSUE THREAD

**Issue by macks2008** [TeamLapen/Vampirism#167]
## Versions
- Minecraft:                 1.10.2
- Forge:                       2281
- Vampirism:               1.1.0-beta.1

## Issue Description
items that suspend a mob (such as a wolf. That's what I experienced the issue with) by serializing it into their NBT data —in my case, Animal Nets from the Hatchery mod, but it probably applies to any such item— apparently reset the mob's blood level to full upon release. Blood level should be stored as or at least mirrored by the mob's NBT data to fix the problem. Of course I'm just guessing that you're not doing this. Maybe you are and there some other problem, but I wouldn't know.

## Reproduce Steps
probably a simple matter of installing the version of vampirism I listed and any version of a mod that adds something akin to the Golden Lasso or Animal Net. Then just make yourself a vampire, drain some blood from a wolf or other passive mob that has blood, and then pick it up and put it back down with one of the items mentioned

**Comment by maxanier** [comment]
The blood level is usually saved with the entities NBT (as part of the Forge capabilities).
I've taken a quick look, it seems that Hatchery is only saving part's of the relevant data (Entity#writeEntityToNBT) and ignores anything from Entity#writeToNBT. Thereby any capabilities are not saved (including Vampirism's entity information).
I think that can be solved by Hatchery by manually saving the capabilities.

I will verify this and create an issue on Hatchery's repository tomorrow

**Comment by Twisted-Code** [comment]
@maxanier this issue is still present in some of the most recent builds of the relevant mods. Please be sure you've done everything you need to to ensure the NBT is saved and find out what's going on on Hatchery's end? it looks like the other developer may have fell into the void while he was working on it 😜

**Comment by maxanier** [comment]
Feel free to bug the developer yourself. Issue is linked above

**Comment by Twisted-Code** [comment]
With pleasure. Just wanted to make sure you were aware.

**Comment by GenDeathrow** [comment]
Finishing up some testing on this.. should have a new update soon.

**Comment by maxanier** [comment]
Fixed in Hatchery now

**Comment by GenDeathrow** [comment]
Sorry for taking so long everyone...

**Comment by Twisted-Code** [comment]
no worries. At least it's fixed now. And apparently has been for a month, but it's never too late to say thanks is it? So thanks 😄
