### ISSUE TITLE
Unable to level up

### ISSUE THREAD

**Issue by KamiSami** [TeamLapen/Vampirism#168]
## Versions
- Minecraft: 1.10.2                   
- Forge: 12.18.3.2254                      
- Vampirism: Vampirism-1.10.2-1.1.0                                            

So... Problem is, i want to level up as vampire hunter but the ampire hunters wont accept my vampire blood, the level up is greyed out no matter how much i offer them with vampire blood... If this doesn't happen with anyone else other than i, it's probably some other mod doing something i guess..

Reproduce? I am not entirely sure what this means

No crashes

**Comment by maxanier** [comment]
Strange, not sure how another mod could interfere here.
Which hunter level are you? And how much vampire blood (not pure blood and not blood bottles) did you offer him?
Are any of Vampirism's configs modified and is this single or multiplayer?

Thanks

**Comment by maxanier** [comment]
Any news on this?

**Comment by maxanier** [comment]
Closing since outdated
