### ISSUE TITLE
Uncraftable Items

### ISSUE THREAD

**Issue by princessbinas** [TeamLapen/Vampirism#169]
## Versions
- Minecraft:   1.10.2         
- Forge:       12.18.3.2297              
- Vampirism:      https://minecraft.curseforge.com/projects/vampirism-become-a-vampire/files/2419297                                       

Cannot craft anything in the vampirism tab in creative mode that I am supposed to be able to make like the alters.

## Reproduce Steps
-Use forge for 1.10.2
-Use the released version of Vmapirism mod for 1.10
-Have latest optifine with liteloader (this is because I lag a lot)
-Enter single player and try crafting the alter that has three iron, one gold, and three glass blocks to start with then try crafting the armor with the iron ingots and blood bottles
-See that neither recipes craft anything despite other recent youtubers within the year have been able to craft said objects from the guide book that cannot be found anymore (the links are dead)

https://cloud.githubusercontent.com/assets/19842754/26263986/a90ffb62-3ca0-11e7-8ba3-fdc15ccd9636.png
https://cloud.githubusercontent.com/assets/19842754/26264019/c7c44fea-3ca0-11e7-8326-6d8379d2f4e0.png

No crashes occurred

**Comment by maxanier** [comment]
Not sure where you got those recipes from. Try replacing the gold ingot in the second picture by a glas bottle and you should get an altar.
Do you have the GuideAPI mod installed or JustEnoughItems, they can show you the recipes.

**Comment by princessbinas** [comment]
I tried finding the GuideAPI, but I kept getting a dead link. Can you point me to a working link?

**Comment by maxanier** [comment]
Where did you find the dead link?
GuideAPI mod can be found here: [https://minecraft.curseforge.com/projects/guide-api](https://minecraft.curseforge.com/projects/guide-api)
