### ISSUE TITLE
Unable to put Blood into Altar of Inspiration

### ISSUE THREAD

**Issue by Maycus** [TeamLapen/Vampirism#170]
## Versions
- Minecraft:  1.11.2                  
- Forge:   13.20.0.2298                    
- Vampirism:  1.11.2-1.2.0                                           

## Issue Description
I created the Altar of Inspiration to level up my Vampire levels. However, I am unable to put blood into it.

**Comment by maxanier** [comment]
Thx for reporting. Fixed in latest alpha
