### ISSUE TITLE
Blood Vision [Bug]

### ISSUE THREAD

**Issue by princessbinas** [TeamLapen/Vampirism#171]
## Versions
- Minecraft:      1.10.2              
- Forge:                 12.18.3.2297      
- Vampirism:            1.1.1                                 

## Issue Description
Blood Vision goes to complete black once toggled to it.

## Reproduce Steps
-Use the version of forge, minecraft, and Vampirism
-Level up normally to level seven and get blood vision with no deviation
-Toggle with the key set for vision toggle from normal to night vision then to blood vision (which will be a black screen that won't even show the menu when you press ESC or  @E)

## Additional Information
If left on the glitched Blood Vision and you go to another window, you won't be able to switch away from Blood Vision into another setting. #

**Comment by maxanier** [comment]
Thanks for reporting, however, I can not reproduce this.
Do you use any other mod, e.g. optifine?

**Comment by princessbinas** [comment]
Yes. I always use Optifine. I also have Voxelmap and that is it.

**Comment by maxanier** [comment]
Can you pls, check if this also occurs without Optifine or Liteloader?

**Comment by princessbinas** [comment]
I am not sure how to separate Optifine and LiteLoader from Forge.

**Comment by maxanier** [comment]
Are you using the Vanilla Launcher?
Then you would have to create a new profile with just Forge and Vampirism.

Two other questions that  might help me: 
Does the fog in the vampire biome work for you?
Does the glowing effect (/effect <player> glowing) work for you (outlines are white in 3rd person)?

**Comment by princessbinas** [comment]
I am using the vanilla launcher.
Optifine was causing the problem.
The fog is the exact same and there is no glowing effect at all.

**Comment by maxanier** [comment]
Ok, I will investigate if I can find the problem then, but it might be caused by your hardware not supporting all required (OpenGL) features.

**Comment by princessbinas** [comment]
Okay. I wish you good luck.
