### ISSUE TITLE
Stuck in Bat Form [Bug]

### ISSUE THREAD

**Issue by princessbinas** [TeamLapen/Vampirism#173]
## Versions
- Minecraft:              1.10.2      
- Forge:        12.18.3.2297               
- Vampirism:            1.1.1                                 

## Issue Description
You are stuck in bat form, no matter how many times you try to undo it.

## Reproduce Steps
-Use the same versions of Minecraft, Forge, and Vampirism
-Get batform and fly around a bit
-Causally press the "E" key (or whatever you have set for inventory)
-Go to another window and do a bit of typing
-Go back to Minecraft, exit out of inventory, and try to under batform via the skills selection screen

**Comment by maxanier** [comment]
Thx for reporting, however, I'm not able to reproduce it.
Can you pls upload your log/fml-client-latest.log. (or is this happening on a server?)

**Comment by princessbinas** [comment]
I was in single player.
Here are the logs (I had to open and close several times)

https://paste.ee/p/keVfn

**Comment by princessbinas** [comment]
[2017-05-23-1.log.gz](https://github.com/TeamLapen/Vampirism/files/1026217/2017-05-23-1.log.gz)
[2017-05-23-2.log.gz](https://github.com/TeamLapen/Vampirism/files/1026218/2017-05-23-2.log.gz)
[2017-05-23-3.log.gz](https://github.com/TeamLapen/Vampirism/files/1026219/2017-05-23-3.log.gz)
[Uploading 2017-05-22-3.log.gz…]()

**Comment by maxanier** [comment]
Thank you.
Unfortunately I'm still not sure, what might cause this issue. 
I can't reproduce it even with Optifine and Liteloader.

Does it happen frequently or only rarely and does a world reload help?

**Comment by princessbinas** [comment]
Reload helps and so far, it happened at least once or twice.

**Comment by maxanier** [comment]
Hmm, I'm sorry, as I've currently no idea, what might be causing this and it only happens rarely and there is a workaround and because I do not have enough time to investigate this, I won't be able to fix this. Maybe it disappears with one of the future updates (e.g. 1.11)
