### ISSUE TITLE
[Enhancement] New Recipe ,  Add Cows Blood + Corn starch + Spices to make Gravy to put on Mashed Potatoes

### ISSUE THREAD

**Issue by Tsoccerguy3** [TeamLapen/Vampirism#179]
## Versions
- Minecraft:  Any Version 
- Forge:        Any Version
- Vampirism: Any Version                                            

## Issue Description :  Mod Enhancement :  It's Common knowledge that Cows Blood (other animals etc ...) mixed with Corn Starch and Seasonings , is how Gravy is made . Very tasty on mashed potatoes on steak and very nutritious etc ... 
Chicken Blood is the Prime ingredient in chicken soup or chicken broth great food for healing cold or flu .

Thanks

**Comment by maxanier** [comment]
I don't think that would to the mod

_Sent from my OnePlus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
