### ISSUE TITLE
Suggestion: Adding More Mobs and Biteables

### ISSUE THREAD

**Issue by princessbinas** [TeamLapen/Vampirism#181]
In the future, do you think it is possible to add new mobs (anything you think that would fit) and bite-able/convertible creatures (such as chickens, which I think would be pretty cute and funny)?

**Comment by maxanier** [comment]
It is possible to do so yourself. https://github.com/TeamLapen/Vampirism/wiki/Biteable-Creatures

I do not plan to add any additional vanilla biteable/convertibles (except creatures from future MC versions maybe).
However, I would like to make more creatures from other mods convertible. But since I do not have enough time, I would need help for that. (Suggestion creatures and blood values, and maybe even creating the overlay texture)

**Comment by princessbinas** [comment]
I think I could help with overlays, blood values, and suggestions when it comes to other mods. I am a digital artist and I have played with minecraft skins, recolored/frankensprited many RPG Maker sprites, and draw quite a bit (my deviantart: princessbinas.deviantart.com). I am not sure how to install the overlays, but I think I can definitely make some.

**Comment by maxanier** [comment]
Simplest way to create new overlays:
- First get the texture of the creature (either it is available e.g. on Github, or you have to open the mod file (as zip, e.g. using 7zip, or by changing the file ending to .zip) and navigate to 'resources/assets...').
- Then the file with an image tool that supports layers (e.g. GIMP or Photoshop). Create a new transparent layer and draw the 'converted changes' (e.g. red eyes) into this layer.
- Afterwards make the base layer invisible and only export your own drawings. Send the image to me (vampirism@maxanier.de)
- If you want to test how it looks in-game beforehand, you can save the complete image (with base layer) and put it into a resource pack (at the same path as you found it in the mod's file).

(Cool drawings by the way :) )

**Comment by princessbinas** [comment]
Okay. I sent you my first converted mob overlay. I hope you like it.

**Comment by Cheaterpaul** [comment]
For anyone interested https://github.com/TeamLapen/Vampirism/wiki/Biteable-Creatures-Blood-Grinder should give a full description.
