### ISSUE TITLE
Hunter Table Causing Crashes

### ISSUE THREAD

**Issue by princessbinas** [TeamLapen/Vampirism#182]
## Versions
- Minecraft:          1.11.2          
- Forge:                  13.20.0.2265     
- Vampirism:                Vampirism-1.11.2-1.2.0-alpha+05-26-13-10                             

When using the hunter's table as a hunter, if you try placing things like the guide book or vampire blood (not pure blood) while trying to figure out what you need to use the table, the game will crash with the following:

The game crashed whilst updating screen events
Error: java.lang.NullPointerException: Updating screen events

## Reproduce Steps
-Become a hunter
-Go to the Hunter's Table in the hunter's house
-Try to insert Vampire Blood via shift click
-Wait for the crash message in the Minecraft loader

## Additional Information

Here are the log files that I got when using one of the mentioned items:

[2017-06-05-2.log.gz](https://github.com/TeamLapen/Vampirism/files/1053070/2017-06-05-2.log.gz)
[2017-06-05-3.log.gz](https://github.com/TeamLapen/Vampirism/files/1053069/2017-06-05-3.log.gz)

**Comment by princessbinas** [comment]
[fml-client-latest.zip](https://github.com/TeamLapen/Vampirism/files/1053077/fml-client-latest.zip)

**Comment by Avarice** [comment]
https://paste.ee/p/8V6OU
 Same exact crash

**Comment by maxanier** [comment]
Thanks for reporting, will fix tomorrow
