### ISSUE TITLE
Alter of Infusion Eating Items

### ISSUE THREAD

**Issue by princessbinas** [TeamLapen/Vampirism#184]
## Versions
- Minecraft:        1.11.2            
- Forge:                 13.20.0.2265       
- Vampirism:        Vampirism-1.11.2-1.2.0-alpha+05-26-13-10                                     

## Issue Description

When ever I try to level up, the alter makes all inserted items disappear without giving me the level up or the flashy animation that signifies the ritual was a success. In stead it tells me "Missing 1 "Pure Blood Purity 1" for this ritual" despite being a level 6, trying to go up to level 7.

## Reproduce Steps

-Go onto the server (As this is were it happens the most frequent and I can actually recall it)
-Go up to level 6
-Gather up the items for the next ritual
-It will tell you it needs 5 human hearts and pure blood 1/5 and a book
-Plug those items in and exit out to do the ritual
-Right click the alter again with an empty hand
-See that all inserted items disappear

## Additional Information

This has happened to me four times, all on the official server if I can recall correctly. This is a very irritating bug.

If you need log files, I do not know how to provide the ones that occur on your server.

**Comment by maxanier** [comment]
Thx for reporting, I will investigate this tomorrow.

**Comment by maxanier** [comment]
I'm unfortunately not able to reproduce this (even on the server). 
I'm on vampire level 6, build the altar of infusion structure, insert a pure blood, some heats as well as a vampire book. Then I leave the GUI and right click with an empty hand. The ritual starts and levels me up.

Where did you try this on the server, maybe the protection plugin interferes somehow

**Comment by princessbinas** [comment]
I was in my nation (which I called Akatsuki).

**Comment by maxanier** [comment]
I've tried to reproduce it in my own nation (without admin privileges), but it also did work. Very strange.
Did you hear from anyone else having the same problem?

**Comment by princessbinas** [comment]
So far no because I told everyone that was online at the time that the alter was glitched and not to attempt it unless they wanted to risk the chance that they had the glitch themselves.

**Comment by GrimmBread** [comment]
I'm actually having the exact same problem, also at level 6 trying to move onward. Just in my own private game though, not on a server...

**Comment by maxanier** [comment]
@GrimmBread What other mods do you have installed?

**Comment by GrimmBread** [comment]
Quite a few actually, but a lot of them I installed after having the issue.
I'm working on going through to see which ones could be conflicting now, but if you already know of any issues with some of these that would be helpful.

advancedcombat-1.0.1-[1.11.2].jar
AmbientSounds v2.0.3 mc1.11.2.zip
armorplus-1.11.2-10.7.0.1.jar
BetterFoliage-MC1.11.2-2.1.7.jar
BiomesOPlenty-1.11.2-6.2.0.2254-universal.jar
CosmeticArmorReworked-1.11.2-v1a.jar
EnderCompass-1.11-1.2.5.3.jar
Forgelin-1.4.2.jar
inventorypets-1.11.2-1.4.9.7.jar
ironchest-1.11.2-7.0.25.815.jar
IvToolkit-1.3.3.jar
jei_1.11.2-4.5.0.289.jar
journeymap-1.11.2-5.4.7.jar
llibrary-1.7.6-1.11.2.jar
MoreShearables1.2.2-1.11.2.jar
Neat 1.4-13.jar
OptiFine_1.11.2_HD_U_C3.jar
RandomThings-MC1.11.2-4.0.jar
RealisticItemDrops-1.1.10.jar
RecurrentComplex-1.4.4-1.11.jar
switchbow-1.3.jar
Tails-1.11.2-1.9.3.jar
thedragonlib-1.11.2-3.2.2.jar
TreeChopper-1.11.2-1.1.2.jar
Vampirism-1.11.2-1.2.1.jar
WearableBackpacks-1.11.2-2.5.0.jar

**Comment by maxanier** [comment]
Still not really sure what is causing the issue.
I've now partly rewritten the system to avoid such issues in the future.

**Comment by GrimmBread** [comment]
Yeah, have all the same mods installed and it's working fine now
