### ISSUE TITLE
[1.11.2] Server crashed when vampire players were attacked by mobs weapon with vampire slayer enchantment

### ISSUE THREAD

**Issue by ghost** [TeamLapen/Vampirism#191]
## Versions
- Minecraft:
1.11.2                    
- Forge:
forge-1.11.2-13.20.0.2315                       
- Vampirism:
Vampirism-1.11.2-1.2.0-alpha+06-10-15-15
Vampirism-1.11.2-1.2.0-beta.1                                             

## Issue Description
Server crashed when vampire players were attacked by mobs weapon with vampire slayer enchantment

## Reproduce Steps
Always they hit I think.

## Additional Information
Crash Report here.
https://pastebin.com/9krmZ2HJ

**Comment by maxanier** [comment]
Thx for reporting.
I made a stupid mistake there, will fixed soon.

**Comment by maxanier** [comment]
Fixed.
While fixing this I also noticed that the vampire slayer enchantment was not working at all until now.
Now it works against vampire mobs at least. To make it work against vampire players I'm have to wait for Forge.

Does the server crash often (do you need a new version right away), or can I wait another week before releasing a new beta?

**Comment by ghost** [comment]
I can wait ;) Thank you for fixing!

**Comment by maxanier** [comment]
https://minecraft.curseforge.com/projects/vampirism-become-a-vampire/files/2443231
