### ISSUE TITLE
[1.11.2] Vampire Hunter's Tents were not created in Custom Dimension

### ISSUE THREAD

**Issue by ghost** [TeamLapen/Vampirism#192]
## Versions
- Minecraft:                    
1.11.2
- Forge:
forge-1.11.2-13.20.0.2315
- Vampirism:                                             
Vampirism-1.11.2-1.2.0-beta.1                       

## Issue Description
I created Custom Overworld with the same setting DIM0 as DIM100 by Just Enough Dimemsion. It looks good but I can't find any Hunter's Tent with Hunters. ( I found Hunter Trainers and Alter of Cleansing in DIM100. )  I can find them in DIM0 correctly.

**Comment by maxanier** [comment]
They are only generating in DIM0 as Vampirism does not know if it would be appropriate to generate camps in that world.
I will take a look if there is a way to determine this at runtime or if I have to add a config system for this

**Comment by maxanier** [comment]
I did not find a simple way to determine if Vampirism should execute world gen in a DIM!=0. So I've decided to just implement a config option. You will be able to add dimension ids to world_gen_dimensions in the next version

**Comment by ghost** [comment]
Thank you so much!

**Comment by maxanier** [comment]
https://minecraft.curseforge.com/projects/vampirism-become-a-vampire/files/2443231
