### ISSUE TITLE
Vampire Slayer Enchantment not working

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#193]
During #191 I noticed that the Vampire Slayer enchantment does not affect vampire players.
Needs Forge PR https://github.com/MinecraftForge/MinecraftForge/pull/4052 

Guess this will be 1.12 only.

**Comment by maxanier** [comment]
Investigate if there is a simple way to do this via Mixins otherwise give up

**Comment by Cheaterpaul** [comment]
I don't think there is a way to do this safely with mixins.

The only working idea i had was to cache the entity when `#getMobType` is called, so we can access it in the enchantment.
