### ISSUE TITLE
altar pillar and the bone block inside it disappeared when I broke them on a lag spike

### ISSUE THREAD

**Issue by Twisted-Code** [TeamLapen/Vampirism#200]
## Versions
- Minecraft:                    1.10.2
- Forge:                          build 2185
- SPONGEFORGE:        spongeforge-1.10.2-2281-5.2.0-BETA-2353.jar
- Vampirism:                   1.1.2

## Issue Description
I wanted to pick up my Altar of Infusion's Northwest pillar, but when I broke it with my hammer from Tinker's Construct, the server lagged and instead of dropping the pillar and bone block like I expected, the block vanished and I couldn't find it.

## Reproduce Steps
not entirely sure. my best guess is as follows:
1. Install the relevant mods with the versions above
2. Set up an Altar of Infusion with bone blocks in the pillar frames.
3. Set up a planned server-only lag spike somehow.
4. When the spike happens, make sure to break the upper pillar frame (the one at eye level, not the one on the ground) in the northwest of the altar. If successful, it will vanish instead of dropping, along with the bone block in it

## Additional Information
N/A

**Comment by maxanier** [comment]
This can have many reasons and has only occurred under very specific conditions which might not be reproducible. So won't put any time into this. Report again if this happens frequently

_Sent from my OnePlus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Twisted-Code** [comment]
fair enough. will do
