### ISSUE TITLE
[suggestion]please grant vampire players the sunscreen buff for at least 10 seconds on login

### ISSUE THREAD

**Issue by Twisted-Code** [TeamLapen/Vampirism#201]
## Versions
- Minecraft:                    1.10.2
- Forge:                          build 2185
- SPONGEFORGE:        spongeforge-1.10.2-2281-5.2.0-BETA-2353.jar
- Vampirism:                   1.1.2

## Issue Description
I can't tell you the number of times I've died from sun damage on logging in. While players should make an effort to log off in a safe spot, safe spots can change for any number of reasons, so...

## Reproduce Steps
pretty straightforward, although since I'm playing on a sponge server and have yet to test in single player, it could be partly sponge's fault.

**Comment by maxanier** [comment]
If playing on a dedicated server you will now get a 10 sec sunscreen effect on login.

Can be abused to avoid sundamage by frequently reconnecting, but what the hell.

**Comment by Twisted-Code** [comment]
Is there a config option for it in case of abuse? Such an option could be useful,  and possibly more so if you can toggle it without restarting the server. That way, for instance, I could turn it off if I noticed someone was trying to abuse it, wait for them to die a couple of times and give up, and then turn it back on. I then keep an eye on them and if they start doing it again, more drastic measures can be used

**Comment by Twisted-Code** [comment]
@maxanier ^
