### ISSUE TITLE
Blood Values Won't Change

### ISSUE THREAD

**Issue by princessbinas** [TeamLapen/Vampirism#202]
## Versions
Minecraft: 1.11.2
Forge: 13.20.0.2265
Vampirism: Vampirism-1.11.2-1.2.0-alpha+06-10-15-15 and Vampirism-1.11.2-1.2.0-beta.1

I decided to change blood values for my single player world with the .txt file you provided (with modification) and the values do not reflect on previously generated worlds nor does it show on new single player worlds. Using WAILA, I could tell that the defaults were still present and not higher values like 30, which I wanted because I wanted more blood to be available.

## Reproduce Steps
-Use the versions above
-Use the following in a .txt document in the config/vampirisim directory:

#General Multiplier. Is divided by 5.
minecraft:multiplier=5

#Vanilla
minecraft:cow=30
minecraft:horse=30
minecraft:villager=30
minecraft:pig=20
minecraft:sheep=20
minecraft:ocelot=20
minecraft:wolf=20
minecraft:mooshroom=25
minecraft:polar_bear=30
minecraft:rabbit=15
minecraft:llama=20
minecraft:chicken=10

#MCA
mca:EntityHuman=35

**Comment by maxanier** [comment]
Did you name this file exactly "vampirism_blood_values.txt" and put in the config dir alongside vampirism.cfg etc. ?
It is working for me.

Also, with the config you posted here you will get a blood value of 15 for cow, horse .... . You changed the general modifier from 10 to 5, which is still divided by 10 (even though you changed the config), so 30 * 5 /10 =15.

You can also check if it loads correctly by reading the console output, there should be a line similar to `[23:43:23] [Client thread/INFO] [vampirism/vampirism]: [VampirismEntityRegistry] Registering convertible net.minecraft.entity.passive.EntityCow with blood 15 and handler null`

**Comment by princessbinas** [comment]
It reads "[14:59:56] [Client thread/INFO] [vampirism/vampirism]: [VampirismEntityRegistry] Registering convertible net.minecraft.entity.passive.EntityCow with blood 15 and handler null" so it is the exact same as the line you gave me. And I named the file "vampirism_blood_values.txt"

**Comment by maxanier** [comment]
Then everything seems to be working fine.

If you change the multiplier back to 10, newly spawned cows should have 30 blood (still only takes two bites to kill or convert, you just drink more at once)

**Comment by princessbinas** [comment]
Okay. Thank you. I think that should be mentioned in the guide.

**Comment by maxanier** [comment]
Do you refer to the Github Wiki or did I mention that in the ingame guide?

Changed the wiki: https://github.com/TeamLapen/Vampirism/wiki/Biteable-Creatures#adjusting-the-values--adding-new-biteable-creatures

Can this be closed?

**Comment by princessbinas** [comment]
I am talking about the Github, and might as well throw it into the in-game guide as well. 
This thread can be closed.
