### ISSUE TITLE
Cannot fly

### ISSUE THREAD

**Issue by SoulVinicius** [TeamLapen/Vampirism#204]
## Versions
- Minecraft: 1.7.10                    
- Forge: 1.7.10-10.13.4.1614-1.7.10                       
- Vampirism: 1.7.10-0.6.2.167                                            

## Issue Dercription
   I can't fly as a bat, but i still can turn into a bat.

**Comment by maxanier** [comment]
You are using a completely outdated version. Check here for newer ones https://minecraft.curseforge.com/projects/vampirism-become-a-vampire/files?filter-game-version=2020709689%3A4449

_Sent from my OnePlus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by SoulVinicius** [comment]
Now i cant use my abilities 
![image](https://user-images.githubusercontent.com/29808313/27766700-ad639954-5eaf-11e7-8a2a-4c98f9d133f3.png)

**Comment by SoulVinicius** [comment]
Now  i can't use my skills 
![image](https://user-images.githubusercontent.com/29808313/27766701-c7ba60e4-5eaf-11e7-9703-dbbe7e0f9030.png)

**Comment by maxanier** [comment]
Please create a new creative test world, run "/vtest level 14" and check if you can activate any skills there.

**Comment by SoulVinicius** [comment]
Still not working
http://prntscr.com/fqpdk5

**Comment by maxanier** [comment]
Very strange. 
Did you edit any vampirism related configs or are you using a modpack?

**Comment by SoulVinicius** [comment]
both.
http://prntscr.com/frlvps
http://prntscr.com/frlw40
http://prntscr.com/frlwif
http://prntscr.com/frlwqc
http://prntscr.com/frlxac
http://prntscr.com/frlxgo
http://prntscr.com/frm2be
http://prntscr.com/frm2m1

**Comment by maxanier** [comment]
thx, looks fine to me. 
Can you pls upload your .minecraft/logs/fml-client-latest.log after opening the skill menu?

**Comment by SoulVinicius** [comment]
idk how

**Comment by SoulVinicius** [comment]
nvm
[fml-client-latest.zip](https://github.com/TeamLapen/Vampirism/files/1123219/fml-client-latest.zip)

**Comment by maxanier** [comment]
Thank you. Sorry for not getting back to you earlier.
The log seems fine as well so I've absolutely no idea what might be causing this issue. It's might be a very uncommon mod compatibility issue.

Unfortunately, I don't have the time to support 1.7.10 besides the 1.12 version, so I can't look into this any further. I'm sorry, I was hoping this was an easy fix.

Last thing I could suggest is deleting any vampirism related file in the config directory.
