### ISSUE TITLE
Propably missing Vampire book

### ISSUE THREAD

**Issue by GxVITT0** [TeamLapen/Vampirism#205]
Hello,
I cant find a Vampire book. I try everything. Neither in Creative I can not found in invetory.
I dowload Vampirism from Technic Launcher. Sorry for my bad English 🗡 

## Versions
- Minecraft:                    
- Forge:                       
- Vampirism:

**Comment by maxanier** [comment]
It can be found in vampire  dungeons and is dropped by advanced vampires and hunters. ( if you want to cheat it, "vampirism-test vampireBook" might work

**Comment by maxanier** [comment]
Did the above help (and are you using Minecraft 1.10 or higher)

BTW:  The vampire book generation will be reworked, see #194.

**Comment by maxanier** [comment]
Unanswered -> Closing
