### ISSUE TITLE
Building For Vampire Forest (Vampire Mansion)

### ISSUE THREAD

**Issue by princessbinas** [TeamLapen/Vampirism#206]
This is something I put together for you if you need anything to add to the Vampire Forest biome (or for making a new biome entirely). I hope you like it. :)
[Vampirism BuildWorld.zip](https://github.com/TeamLapen/Vampirism/files/1117607/Vampirism.BuildWorld.zip)

Edit: I added a tower. You can do whatever you want to the inside of it.

**Comment by maxanier** [comment]
Thx, yes I will need a few buildings in the future, but not sure when.

I will mention it here, if I need could use more buildings.

BTW: In the future, to make it easier for me, you can save the building to a [structure file](https://www.digminecraft.com/getting_started/structure_block_save_mode.php) and just upload the file as well as a screenshot.

**Comment by princessbinas** [comment]
Okay. I will do my best to remember that. Just let me know what buildings you need I will do my best to make them.

**Comment by princessbinas** [comment]
I did some testing with structure blocks, and appearently I made the vampire mansion way too big for it. Not sure how to increase the size from 32 blocks...

**Comment by maxanier** [comment]
For larger buildings, I did split buildings up into 16x16 areas, which were added together at world gen. This also allows randomly combining parts to make each building look individual.

However, pls keep in mind that I'm still not sure what/how stuff will be implemented, so I can't guarantee that your buildings will be used

**Comment by princessbinas** [comment]
I can try breaking some of the builds up (already separated the trees into their own structure files and same with the buildings).

I understand, but if you need a build, just ask me and I will see if I can do it. Also, I am going to need the castle blocks to get half slab and stair versions, they are really important to experienced builders as they allow for more shapes and roofs to be made while making builds less blocky.

**Comment by maxanier** [comment]
So, finally getting around to work on structures.
Check out #236 for more information. 

Buildings should still be 16x16 or smaller (maybe slightly larger ones are ok, too, but I am not sure yet).

With the latest alpha of Vampirism you also have half-slabs and stairs available :)

**Comment by Cheaterpaul** [comment]
included in #236
