### ISSUE TITLE
Blood Altar Tier 1 / Asking for a config option.

### ISSUE THREAD

**Issue by evernife** [TeamLapen/Vampirism#21]
Hello, I need to ask you something, i am a server owner, and i really liked the mod and i want to put this on my multiplayer server.

I want you to let an option in the config-file for me to ''block'' the ]Blood Altar Tier 1[. In resume, i dont want people get him just by killing the 20 vampires, I want the people to buy it (with the server gold, or in a quest reward).

So, like this, i could limit the number of Vampires in the server. If you could do this for me i will be very happy.

(I am just waiting for the new version for the translate)

**Comment by maxanier** [comment]
I don't really like ingame gold etc., but you have to finance it of cource. I think a extra config option for that would be a little strange, but we should have a config option to set the required vampire kills, it's called ALTAR_1_BLOOD. You can set that to an high number and then give them prefilled swords.

**Comment by evernife** [comment]
Ok, its really helpfull. I wanted it to be a reward of a quest, but this way i can do something like what i wanted.

Ty dude.
