### ISSUE TITLE
Game Not Loading [1.12]

### ISSUE THREAD

**Issue by princessbinas** [TeamLapen/Vampirism#211]
## Versions
- Minecraft:         1.12           
- Forge:                 forge-1.12-14.21.1.2387      
- Vampirism:         Vampirism-1.12-1.3.0-alpha+07-06-20-05                                    

## Issue Description

When I load a previously saved game from 1.11.2 or make a new one, the game hangs on the loading screen until I go into task manager and shut it off. I made sure that I had at least 6GB of memory allocated for Minecraft to be sure that was not the issue, and it turns out memory is not an issue. There is something in the Vmapirism code that is not allowing me to load. I have the following mods:

jei_1.12-4.6.0.58
journeymap-1.12-5.4.9
OptiFine_1.12_HD_U_C4
Vampirism-1.12-1.3.0-alpha+07-06-20-05

## Reproduce Steps

-Install the mods I have
-Set minecraft to have around 6GB of memory
-Load up a world from 1.11.2

## Additional Information Iam not sure which one is associated with the hanging.

[2017-07-07-3.log.gz](https://github.com/TeamLapen/Vampirism/files/1132136/2017-07-07-3.log.gz)
[2017-07-07-4.log.gz](https://github.com/TeamLapen/Vampirism/files/1132138/2017-07-07-4.log.gz)
[2017-07-06-2.log.gz](https://github.com/TeamLapen/Vampirism/files/1132139/2017-07-06-2.log.gz)
[2017-07-07-1.log.gz](https://github.com/TeamLapen/Vampirism/files/1132137/2017-07-07-1.log.gz)
[2017-07-07-2.log.gz](https://github.com/TeamLapen/Vampirism/files/1132135/2017-07-07-2.log.gz)

**Comment by maxanier** [comment]
This is unrelated to Vampirism (also hangs without Vampirism installed). 
JEI is causing the problems here, pls update to a more recent version like https://minecraft.curseforge.com/projects/just-enough-items-jei/files/2443648.

BTW: these logs you provided, do not contain relevant data, pls (only) upload fml-client-latest.log (or fml-server-latest.log respectively)
