### ISSUE TITLE
Vampirism/Guide-API 1.12 - All the Mods 3 Crash on Startup

### ISSUE THREAD

**Issue by AsuraTakun** [TeamLapen/Vampirism#212]
## Versions
- Minecraft: 1.12                   
- Forge: 14.21.1.2396                      
- Vampirism: 1.3.0-alpha+07-06-20-05                                            

## Issue Description
Running All The Mods 3 mod pack, trying to add Vampirism,
MC crashes on load during steps 6 of 7, crash report indicates:

Caught exception from Guide-API (guideapi)
Caused by: java.lang.NoSuchMethodError: joptsimple.internal.Strings.join(Ljava/lang/Iterable;Ljava/lang/String;)Ljava/lang/String;
	at de.teamlapen.vampirism.modcompat.guide.GuideHelper.pagesForLongText(GuideHelper.java:249)
	at de.teamlapen.vampirism.modcompat.guide.GuideHelper.pagesForLongText(GuideHelper.java:260)
	at de.teamlapen.vampirism.modcompat.guide.GuideBook.buildOverview(GuideBook.java:91)
	at de.teamlapen.vampirism.modcompat.guide.GuideBook.buildCategories(GuideBook.java:67)
	at de.teamlapen.vampirism.modcompat.guide.GuideBook.handlePost(GuideBook.java:447)
	at amerifrance.guideapi.GuideMod.postInit(GuideMod.java:69)
        ...

Turning off Guide API allows the game to continue loading, though obviously without the vampirism guide book (or cyclic guide book). Turning off Vampirism allows the modpack to run normally. The config for guide-api shows vampirism=true.

## Reproduce Steps
Install All the Mods 3 v1.3 from curse/twitch launcher
Unlock the profile and add Vampirism
Toggle Guide-API off to load normally

Additional mods I have added but don't seem to affect the ability to play either way are (all are turned on with or without vampirism/guideapi and don't change the outcome):
Optifine 1.12 HD U C4
BetterFPS 1.4.6
BetterFoliage 2.1.6
Tails 1.10
Dynamic Surroundings 3.4.5.7
Mo' Bends 0.23.4
Sound Filters 0.10
Enhanced Visuals 1.1.3
Multihotbar 3.0-T62
Neat 1.4-15
Doggy Talents 1.13.1g
SilentsGems 2.4.0-202, Lib 2.2.5b-81, Extra 1.3.0-22
Terraqueous 1.4.0.1, Shetiphiancore 3.5.0.1
MusicCraft 3.2.2
ActualMusic 1.3.2.121, Embassy 1.0.2.110
Level Up! 2 1.1.1

## Additional Information
[crash-2017-07-07_23.20.26-client.txt](https://github.com/TeamLapen/Vampirism/files/1132721/crash-2017-07-07_23.20.26-client.txt)
[latest.log.txt](https://github.com/TeamLapen/Vampirism/files/1132727/latest.log.txt)

**Comment by maxanier** [comment]
Thx for reporting. Should be fixed in https://minecraft.curseforge.com/projects/vampirism-become-a-vampire/files/2447482

**Comment by AsuraTakun** [comment]
It works now, thanks for the fast response and fix!
