### ISSUE TITLE
Client crash when placing a blood container

### ISSUE THREAD

**Issue by Twisted-Code** [TeamLapen/Vampirism#214]
## Versions
- Minecraft:                 ;1.10.2
- Forge:                       ;forge-1.10.2-12.18.3.2281-universal(.jar)
- Vampirism:               ;Vampirism-1.10.2-1.2.0

## Issue Description
I crashed when I tried to place a blood container, as I tried to tell you on your ?new? IRC channel. I don't have much information besides the versions and [this crash report, crash-2017-07-12_14.20.19-client.txt](https://github.com/TeamLapen/Vampirism/files/1143062/crash-2017-07-12_14.20.19-client.txt)
, so good luck figuring out what happened

## Reproduce Steps
not sure. All I know is I placed a blood container and crashed, and that blood container's class appears to be mentioned in the traceback, so have at it I guess.

## Additional Information
as stated inline above, here's the most recent crash report [crash-2017-07-12_14.20.19-client.txt](https://github.com/TeamLapen/Vampirism/files/1143062/crash-2017-07-12_14.20.19-client.txt)

**Comment by maxanier** [comment]
Sorry, did not check IRC lately.
Will look into this

**Comment by maxanier** [comment]
Fixed version is uploading right now
