### ISSUE TITLE
Crash when drinking a blood bottle

### ISSUE THREAD

**Issue by Twisted-Code** [TeamLapen/Vampirism#216]
## Versions
- Minecraft:                1.10.2
- Forge:                      forge-1.10.2-12.18.3.2281-universal(.jar)
- Vampirism:              Vampirism-1.10.2-1.2.0

## Issue Description
crash when I tried to drink a blood bottle. Between this and the client crash i reported  Wednesday, I'm beginning to wonder just how many ways I can crash with this mod,, and if the 2 could be related

## Reproduce Steps
not sure. All I did was drink a blood bottle. It crashed when I finished sipping

## Additional Information
[crash-2017-07-15_11.40.32-client.txt](https://github.com/TeamLapen/Vampirism/files/1150443/crash-2017-07-15_11.40.32-client.txt)

**Comment by maxanier** [comment]
Looks like you have a talent to somehow find all possible crashes :D

Fixed version is uploading right now

**Comment by Twisted-Code** [comment]
So what happened anyway? Conflict with something in the offhand maybe? Because it just happened again. Mind you **I have _NOT_ updated the mod yet** —and in fact didn't realize you had fixed it until I came here to report the repeat— so it's probably already fixed. I'm just curious.

**Comment by maxanier** [comment]
Not sure, was missing a null check for some tank properties, which could be null somehow

**Comment by Twisted-Code** [comment]
@maxanier I wonder if it has anything to do with drinking while something is in the offhand? Remember we had issues removing stuff from a "blood container" tank when something was in the offhand. I'm not sure how that would result in null properties, but again, I'm not the dev 😉

**Comment by Twisted-Code** [comment]
also, this fix and the sunscreen-on-login change should be in the latest build right? Because it seems I still haven't updated *facepalm*

**Comment by Twisted-Code** [comment]
@maxanier I think I might've found another possible cause for those properties being null: the blood bottles obtained by killing advanced vampires, and especially the extra ones produced by doing so with a Fortune weapon. Mind you this is just a guess/possibility, but I just just crashed again (yes I still have not updated. I've decided to finish out this map before worrying about updating anything). This time, notable circumstances of the crash include having a bow in my offhand and having obtained the blood bottle from an advanced vampire

**Comment by maxanier** [comment]
TODO (for me): Check why tank properties can be null

**Comment by Twisted-Code** [comment]
sounds like a plan. I'll leave you to do that TODO, if you know what I mean 😄 

(pretty sure it has something to do with the offhand though. I keep crashing under the same circumstances: taking the last sip of a blood bottle while something is in my offhand. Perhaps certain aspects of the item in the offhand are somehow pulled in as if they are tank properties. Just an idea)

**Comment by maxanier** [comment]
Still can't figure out what is causing this, maybe some other mod doing strange stuff.
Won't investigate this further since a) we have a workaround and b) we use a different approach in 1.11+ up anyway
