### ISSUE TITLE
entity ticking

### ISSUE THREAD

**Issue by CarmenCelen** [TeamLapen/Vampirism#217]
## Versions
- Minecraft: 1.12                   
- Forge:  14.21.1.2415                    
- Vampirism:  1.12-1.3.0-alpha+07-08-10-42                                           

## Issue Description
Singleplayer has crashed multiple times seemingly random

## Additional Information

2 crashreports. Seems a problem with vehicle nullpointerexception?
[crash-2017-07-21_10.27.40-server.txt](https://github.com/TeamLapen/Vampirism/files/1165578/crash-2017-07-21_10.27.40-server.txt)

[crash-2017-07-21_14.57.32-server.txt](https://github.com/TeamLapen/Vampirism/files/1165579/crash-2017-07-21_14.57.32-server.txt)

**Comment by maxanier** [comment]
Thx for reporting: Fixed version: https://minecraft.curseforge.com/projects/vampirism-become-a-vampire/files/2456777
