### ISSUE TITLE
RPG-Hud can't render blood meter

### ISSUE THREAD

**Issue by thetalorian** [TeamLapen/Vampirism#220]
## Versions
- Minecraft:  1.11.2                  
- Forge: 13.20.1.2386                       
- Vampirism: 1.2.1                                             
- RPG-Hud: 3.6.3

## Issue Description
I'm having a mod interaction issue when using RPG-Hud. If the hud mod is installed I simply can't get the blood meter to render at all. In theory it is replacing the hunger meter when you become a vampire, but no combination of settings in RPG-Hud seems to allow the blood meter to appear. The only time I've seen it at all is when I've completely removed RPG-Hud.
In theory RPG-Hud should not prevent additional HUD elements from other mods from rendering, and so far that's shown true. I have no issues with the mana meter in Botania, or blood indicator in EvilCraft, etc. It looks like there is something about the rendering process for the Vampirism blood meter that is throwing it off.
Technically Vampirism is still playable, but it's going to be a rough life as a vamp if I don't know how much blood I have.

## Reproduce Steps
Install Vampirism
Become Vampire
Install RPG-Hud
Toggle all RPG-Hud settings for Prevent Render, Render Vanilla Element, Prevent Event, etc, for Player Health, Player Hunger, etc.
Sigh in frustration

## Additional Information
None, I'm not really sure what would be helpful here.

**Comment by maxanier** [comment]
Will be fixed in the next version of RPG-Hud

**Comment by thetalorian** [comment]
Awesome!
