### ISSUE TITLE
Config changes not being applied

### ISSUE THREAD

**Issue by Yorkforce** [TeamLapen/Vampirism#222]
## Versions
- Minecraft: 1.10.2                   
- Forge: 2281                        
- Vampirism: 1.2.3                                             

## Issue Description
We have set the following server config option to false:
    # If one player can bite infect a human player with sanguinare [default: true]
    B:player_can_turn_player=false
However we have reports from players that vampires are able to bite other players and infect them regardless.

**Comment by maxanier** [comment]
Sorry for the late response. Will be fixed in the next 1.12 version. Not sure if I will release another 1.10 version just for this.

Thanks for reporting
