### ISSUE TITLE
[1.12][1.3.1] Blood Dupe (via Forestry, Thermal Dynamics)

### ISSUE THREAD

**Issue by Alaberti** [TeamLapen/Vampirism#226]
## Versions
- Minecraft: 1.12.1                    
- Forge: 2470                      
- Vampirism: 1.3.1
- Forestry: 5.5.5.193                                         
- Thermal Dynamics: 2.3.5.12

## Issue Description
A player on my server has discovered a dupe to get infinite blood via cross-mod techniques. He has a video here: https://www.youtube.com/watch?v=ohNBnbZqBdc

## Reproduce Steps
Using an forestry bottler with a blood bottle and a thermal dynamics pipe pumping it out creates the issue.

## Additional Information
@ForestryMC @CoFH might be interested in these findings.

Edit: Apologies, it was a Forestry bottler, not an immersive engineering one.

**Comment by maxanier** [comment]
Thank your for reporting. I will take a closer look at this this weekend

**Comment by maxanier** [comment]
Should be fixed in Forestry
