### ISSUE TITLE
[1.12.1] Sleep system like Morpheus

### ISSUE THREAD

**Issue by Alaberti** [TeamLapen/Vampirism#227]
Just requesting support for the Morpheus mod when vampire players sleep in a coffin.

**Comment by maxanier** [comment]
Thank your for reporting. I will take a closer look at this this weekend

**Comment by maxanier** [comment]
This might cause some issues, imagine the following situation:
You set the required percentage to 50% and there are two vampires and two normal players online at the same time.
Under this circumstances it would allow the players to annoy each other by sleeping in bed/coffin.

I will have to think about how to implement this, but I guess it would be independent from morpheus.

**Comment by Alaberti** [comment]
I think that's more incumbent on us server admins - I use 75% to create the opportunity, but not make it a given, and it's worked very well for the hunters. Unfortunately, the vampire players don't have that same opportunity so it's pretty one-sided. And I certainly understand the implications - but I think it's your fault if our players go back and forth because we can't manage simple configs.

**Comment by Alaberti** [comment]
I think that's more incumbent on us server admins - I use 75% to create the opportunity, but not make it a given, and it's worked very well for the hunters. Unfortunately, the vampire players don't have that same opportunity so it's pretty one-sided. And I certainly understand the implications - but I *don't* think it's your fault if our players go back and forth because we can't manage simple configs.

Edit: Forgot the key *DON'T* part in my original post

**Comment by maxanier** [comment]
Fun fact: There already is a system like that in place, I just forgot that I implemented it. :man_facepalming: 

Check the coffin_sleep_percentage in Vampirism's main config. I did not test it again, but it should work.

**Comment by maxanier** [comment]
Can you confirm it is working?

**Comment by Alaberti** [comment]
Yes, thank you!
