### ISSUE TITLE
[mod compat]Apple skin doesn't correctly show hunger debug information for vampires

### ISSUE THREAD

**Issue by Twisted-Code** [TeamLapen/Vampirism#228]
## Versions
- Minecraft   : 1.10.2
- Forge         : 2477
- Vampirism : 1.2, I think. I'll check the exact version if you really think you need it

## Issue Description
Apple skin, when installed, will normally show you an overlay on your hunger bar indicating your saturation and exhaustion, along with showing the exact numbers in the F3 debug screen. For obvious reasons, this doesn't work so well for vampires. The debug menu shows hunger 10, sat 5, and 0 exhaustion,, regardless of what I'm doing. I don't mind the overlay not working, as your "blood bar" would have to be reworked to display the information the hunger bar normally displays with apple skin installed, but could you at least synchronize vanilla's hunger information with your blood bar if possible? 

## Reproduce Steps
N/A, unless you count the obvious step of "install the relevant mods"

**Comment by maxanier** [comment]
Not sure I will be able to do anything about that.
I cannot update the food stats object (that AppleSkin is using) with the blood stat values (except maybe the exhaustion value) since the player might take damage twice otherwise.

Displaying this information by Vampirism would require almost rewriting the same stuff AppleSkin does. Annoying, since we have to manually sync the information between client and server to be accurate.

Don't think it is worth it.

**Comment by maxanier** [comment]
Mhh, maybe it is sufficient to display blood and saturation and let AppleSkin handle exhaustion which would not require implementing a sync.

Moved to https://github.com/TeamLapen/VampirismIntegrations/issues/1 where future mod compat will be handled/implemented

**Comment by Twisted-Code** [comment]
@maxanier that's another thing: is it really necessary to make an entirely separate mod to achieve what you're trying to get? Couldn't you just re-factor it as a module of the same mod that either enables automatically upon detecting a relevant mod and/or can be enabled/disabled via the config? I ask because most/all other mods I can think of do not do this and also (because of the previous point) it may not be immediately obvious another mod is required for compatibility.

**Comment by maxanier** [comment]
It is already a modular setup with integrations automatically activating and being individually configurable. However, there are a few reasons I split it into a seperated mod:
a) Mod integrations are a lot of work regarding Minecraft updates. If MC updates, but the other mods are not finished yet, I have to uncomment all the relevant parts in Vampirism codes, remove the dependencies and redo all these things once the mod eventually updates.
b) If a other mods changes and requires changes, I don't want to release an update for Vampirism each time
c) It keeps Vampirism's code slightly more organized
d) It verifies that Vampirism's API is working, shows me areas for impovement and can act as an example.
e) It makes it more straight-forward for others contribute and add more integrations (hope this is gonna happen, but I did not have any luck so far)

The most important integrations will say in Vampirism (JEI, GuideAPI,?), but any additional (hopefully many) will be added into the seperate mod.
If you are already installing many mods or a modpack it should not make that much a difference anyway.

I will add some kind of notification to Vampirism to suggest installing the mod if one of the other compat mods is installed.

**Comment by Twisted-Code** [comment]
@maxanier ahhh... ok, yeah those reasons make a lot of sense. Thanks for explaining. And yes, I suppose it's not *that* much more work to download just one more mod (especially when it saves other players from having to update vampirism for mod compat when it's the only mod they use). I suppose if you at least have something in vampirism itself to notify the player about the fact vampirism compatibility for an installed mod is not included, I can completely understand and agree with the decision. 

in any event, I recommend you list this compat mod on curseforge as an "optional library" of vampirism. That way it's easier to find and easier to get to. That makes it 4 or less clicks required to get from vampirism to the other: click "relations", click the drop-down to filter for "optional libraries", click to select an option on that drop-down, and click on the other mod. 
(of course, direct links in vampirism's project overview and the notification about vampirism compat to the companion mod are also welcome.)

**Comment by macks2008** [comment]
edited ^
