### ISSUE TITLE
Cant Find Vampires

### ISSUE THREAD

**Issue by IvanNSBS** [TeamLapen/Vampirism#231]
That's it. I can't find vampires (vampire hunters are fine).
I'm using other mods that have spawns, but i've lowered every other mod spawn rate to 1/4 or 1/5 of it's original value and increased 6 times the spawn rate of the vampirism mobs, but still i can't find vampires.
MC Version : 1.10.2
Mod Version : 1.2.3

**Comment by maxanier** [comment]
That is strange.
Is there any kind of error message in the console or in .minecraft/logs/fml-latest.log during the MC night?

**Comment by maxanier** [comment]
Closing since no answer
