### ISSUE TITLE
Vampire AI bite target priorities

### ISSUE THREAD

**Issue by Twisted-Code** [TeamLapen/Vampirism#232]
## Versions
- Minecraft:   v1.10.2
- Forge:         v2477
- Vampirism: v1.2.3
note: you have inconsistent spacing on you issue creation template for the above three lines. You may want to rework it at some point. I fix it manually out of courtesy, but it's more than slightly annoying for obsessive-compulsive side of my brain

## Issue Description
these guys (see screenshot below) have been sitting here staring at my cows and bobbing their heads for quite some time now. Pretty sure they should have realized they can't get to the cows and begun wondering, running around, ANYTHING but standing in one place.

I'm unsure exactly what's going on here, but I think it's either the non-solid conveyor belts (from immersive engineering) confusing your pathfinding algorithm, or they really are close enough to bite but the fences are getting in the way.

## Reproduce Steps
without being sure of exactly what's happening, I'm not sure how you would reproduce it. try with just a fenced pen full of cows, some vampires, and something to keep them just out of reach. If that doesn't work, try adding some debug logging to the most recent **stable** build, give it to me, and I'll get back to you with a log later

## Additional Information
screenshot (more can be supplied if needed):
![2017-10-28_10 53 30](https://user-images.githubusercontent.com/7110033/32135726-bf565ed8-bbd1-11e7-97c5-c68b5bd50b0d.png)
I'd give you my server's FML-server-latest.log as well, but it has been running for a significant period of time so it's going to be longer than I'm willing to upload unless absolutely necessary.

**Comment by Twisted-Code** [comment]
in the process of trying to get them to walk onto the spiked plate (which extracts blood even from vampires somehow? granted, it's a different mod, but still...), I found that they still won't move even without the conveyors, so you should be able to reproduce this by just getting them close enough. in any case, good luck :-)

**Comment by maxanier** [comment]
I fixed some (rather stupid) AI bug/inconsistency for 1.12. This should solve this issue, at least I cannot reproduce it anymore. Maybe there is something special happening with the modded glass or with 1.10, but won't investigate further as it looks fine in 1.12 and MC AI is just designed to be slightly buggy
