### ISSUE TITLE
Severe Error

### ISSUE THREAD

**Issue by tamem313a** [TeamLapen/Vampirism#233]
- Minecraft:             1.7.10       
- Forge:                      1.7.10 
- Vampirism:                1.7.10-0.7.9                             

My Issue 
Everytime i log in i get a message https://gyazo.com/a944788a9d932a14c2756d253359cf21
that spams me non stop
i tried changing the config but non worked
i dont crash or anything

thanks

**Comment by maxanier** [comment]
There are some id conflicts with another mod (not possible in 1.11+ anymore).

You have to change the following id values to unique values between 30 and 255 and restart the game.
potion_id_sunscreen
potion_id_saturation
potion_id_thirst
potion_id_sanguinare

It might take several attempts to find some free ids if there are many mods installed.

**Comment by tamem313a** [comment]
Thanks but when i did that 
everytime i load a world with vampirism 
i crash https://pastebin.com/fXyDNtnE
1.7.10-Forge10.13.4.1614-1.7.10
Mods:
Vampirism 
am running on -Xmx9G -XX:+UnlockExperimentalVMOptions

**Comment by maxanier** [comment]
Looks like you changed "player_data_watcher_id" leave that as it is unless it complains about this exact property (default is 21 I think).

Your first error is only related to 
potion_id_sunscreen
potion_id_saturation
potion_id_thirst
potion_id_sanguinare

**Comment by tamem313a** [comment]
oo thanks alot

**Comment by maxanier** [comment]
So it works now? Can I close the issue

**Comment by JohnBrown091** [comment]
> potion_id_sunscreen potion_id_saturation potion_id_thirst potion_id_sanguinare
> what do you think i should do to sort it and this is 1.7.10 were talking about i mean changing the config.
