### ISSUE TITLE
Inescapable Coffin after teleporting

### ISSUE THREAD

**Issue by dukeofodd** [TeamLapen/Vampirism#235]
## Versions
- Minecraft: 1.11.2                   
- Forge: 13.20.1.2530                      
- Vampirism: 1.10                                            

## Issue Description
About 75% of the time that I sleep in a coffin, the time changes to night; however, my character is unable to exit the coffin and is left with a screen like this:
![2017-11-04_23 53 50](https://user-images.githubusercontent.com/33386076/32412128-fa5e6418-c1bb-11e7-8557-893b9cfd3277.png)
Clicking the "Leave Bed" button causes the clicking noise to play; however, nothing happens. The only way to escape the coffin is to use task manager to close Minecraft (as the main menu is inaccessible while the "Leave Bed" screen is active) and relaunch the game.

## Reproduce Steps
All that I have to do is sleep in a coffin. I am unsure if this is happening to a mod conflict, and it very well may be. I will leave a list of other mods in the "Additional Information" section.

## Additional Information
The other mods that I am using are: Animania, Astral Sorcery, AutoRegLib, BiblioCraft, BiomesOPlenty, Chameleon Library, Chisel, Code Chicken Lib, Craft Studio, CTM, Decocraft, Extra Utilities, Fairy Lights, Journey Map, JEI, LLibrary, Missing Pieces, Mowzies Mobs, NEI, Optifine, Pam's HarvestCraft, Quark, Rainbow Oak Trees, Rope Bridge, Spartan Shields, Storage Drawers, TreeCapitator, Uncrafting Table, and Waila.

**Comment by maxanier** [comment]
That is strange, I will look into this.
But before let's clarify which version of Vampirism are you using 

> Vampirism: 1.10
is not a valid version.

Please make sure you are running the latest version of Vampirism for MC 1.11 (1.2.3) https://minecraft.curseforge.com/projects/vampirism-become-a-vampire/files?filter-game-version=1738749986%3A599

**Comment by dukeofodd** [comment]
I've checked and I am on 1.2.3, don't know where I saw 1.10. After a bit of experimentation, it seems to be a glitch with using the waypoint teleport in Journey Map and then using the coffin. I looked this up and it seems to be a common issue with warping in other modpacks:

https://forum.feed-the-beast.com/threads/hermitpack-cant-get-out-of-the-bed.170905/

So, it would seem that this would have likely happened to me in a bed as well and is not an issue with the coffin. Either way, thanks for getting back to me so quickly!

**Comment by maxanier** [comment]
Ok, thank you for investigating. 
Seems like there is a workaround  (standing on the bed/coffin when going to sleep).

As this is a vanilla/forge bug it is unlikely I will fix it, however, I will leave this issue open for now, if I should find some time, I will investigate if I can implement a workaround
