### ISSUE TITLE
Blood Potions only work in Creative

### ISSUE THREAD

**Issue by KingEdward9830** [TeamLapen/Vampirism#247]
## Versions
- Minecraft: 1.12.2                   
- Forge:  14.23.1.2555                     
- Vampirism:  1.3.4                                           

## Issue Description
Blood potions only work in Creative Mode, drinking in Survival produces no effects.

## Reproduce Steps
1. Get the Hunter skill to make Blood Potions.
2. Make some Potions at the Blood Alchemy table
3. Drink one in Survival. Notice lack of effects.
4. Drink one in Creative, notice how it works as intended.

## Additional Information
I found this bug a long time ago but didn't report it because I was pretty severely outdated at the time. I decided to test if it was still a thing in the latest version, and it most definitely is.

**Comment by maxanier** [comment]
Thank you very much for reporting again. Also a longstanding bug nobody reported
Caused by MC stupid ItemStack change in 1.11 and me not verifying every single bit of the mod.

**Comment by maxanier** [comment]
Fix is implemented and should hit CurseForge soon
