### ISSUE TITLE
Vampire mobs can suck blood through fences

### ISSUE THREAD

**Issue by flamechair** [TeamLapen/Vampirism#249]
## Versions
- Minecraft:  1.12.2                  
- Forge:   1.12.2                     
- Vampirism: 1.3.5                                            

## Issue Description
Vampire mobs can suck blood through fences

## Reproduce Steps
Place bait on one side of fence
Place vampire mob on other side of fence

## Additional Information
Even if I build the fence 2 layers deep, the vampire mobs still can suck the blood through the fence

**Comment by maxanier** [comment]
This is difficult to prevent.  It is hard to tell (code wise) if a non solid block should prevent a vampire from biting what ever is on the opposite side. Also it somehow makes sense for them to be able to "lean" over the fence and bite a creature. I understand that it might be a little bit more annoying to defend your animal farm from vampires, but I don't think I will change anything about that.

However, vampires being able to bite though 2 layers of fence is ridiculous of course. I will reduce the bite radius in the next version.

**Comment by flamechair** [comment]
Thats reasonable and realistic, thank you!
