### ISSUE TITLE
Not an inssue/ The translated file pt_BR

### ISSUE THREAD

**Issue by evernife** [TeamLapen/Vampirism#25]
I will send the translate file in a fork, or the way you want to.

**Comment by maxanier** [comment]
Pull request would be best, a pastebin would also work

**Comment by evernife** [comment]
Pull request sent :+1:

**Comment by maxanier** [comment]
I could not find you pull request, and could create one myself, since apparently you deleted the en file in your branch.
To cut a long story short, I just added the file myself and as soon as we release the next version/hotfix the translation is included. Thanks man :+1:

**Comment by evernife** [comment]
^^ ok, sorry for my mistakes
