### ISSUE TITLE
Add Twilight Forest Mobs to default_blood_values.txt

### ISSUE THREAD

**Issue by flamechair** [TeamLapen/Vampirism#250]
## Versions
- Minecraft: 1.12.2                   
- Forge: 1.12.2                      
- Vampirism: 1.3.5                                            

## Issue Description
Twilight Forest Mobs do not allow you to suck blood

## Reproduce Steps
Go into Twilight Forest
Try to suck blood of passive mob

## Additional Information
I noticed that you have some default settings for blood defined here: 
https://github.com/TeamLapen/Vampirism/blob/1.12/src/main/resources/blood_values/default_blood_values.txt

I wanted to see if we could get the Twilight Forest mobs added (they have almost 1:1 mapping for vanilla mobs) so Twilight Forest mobs can be used for blood gathering. Or if you can tell me how to do it, I'd be happy to submit a PR.

**Comment by maxanier** [comment]
I would be grateful if you could compile this blood value list.
Check out this page https://github.com/TeamLapen/Vampirism/wiki/Biteable-Creatures#users-and-mod-pack-creator

If you provide me with a list of blood values (in the format of the default_blood_values.txt) I will happily add them :)
You can also create a PR if you want. But if doing so please create a new file in that directory called _modid_.txt and add a line like here https://github.com/TeamLapen/Vampirism/blob/b92314d2be7f33c4847c1fc77418d10d21e9846f/src/main/java/de/teamlapen/vampirism/config/BloodValueLoader.java#L58 in the BloodValueLoader.

**Comment by flamechair** [comment]
Twilight Forest:
`twilightforest:bighorn_sheep=5`
`twilightforest:wild_boar=5`
`twilightforest:deer=5`
`twilightforest:bunny=2`

Also for Sophisticated Wolves:
`sophisticatedwolves:textures/entity/gray/wolf.png=5`
`sophisticatedwolves:textures/entity/forest/wolf.png=5`
`sophisticatedwolves:textures/entity/black/wolf.png=5`
`sophisticatedwolves:textures/entity/brown/wolf.png=5`

**Comment by maxanier** [comment]
Thank you very much.
I will include them in the next version

**Comment by maxanier** [comment]
Will be included in Vampirism 1.4. Until then you can just add them to your blood values config (if you haven't done so already)
