### ISSUE TITLE
Newest 1.12.2 vs of Vamp and Vamp Integration not excepting each other.

### ISSUE THREAD

**Issue by Daihok41** [TeamLapen/Vampirism#259]
## Versions
- Minecraft:   1.12.2                 
- Forge:          1.12.2-14.23.1.2585            
- Vampirism:        Vampirism-1.12.2-1.4.0-alpha+01-07-19-32                                     

## Additional Information
The newest versions of Vampirism and Vamp Integration not excepting each other. Vamp integration tells me im missing Vampirism. Which shown above in vs Im using the latest.

**Comment by maxanier** [comment]
Thanks for letting me know. Apparently my version/dependency system does not work if the year changes 🤦‍♂️ .
A fixed versions of the integrations mod is uploading right now.
