### ISSUE TITLE
Apply cooldown mechanic to bat flight mode

### ISSUE THREAD

**Issue by flamechair** [TeamLapen/Vampirism#262]
Hi again,

Having bat mode indefinitely seems to be a little strong for vampires, and almost every other action has some sort of cooldown attached to it. 

I think if bat mode was given a timer (60 seconds, with a 30 second cooldown) it would balance it out a bit. 

Another option could be 60 second flight time with a 10 second cooldown, but push it further down the skill tree. That way players don't get it immediately at level 4.

Otherwise it's free creative fly whenever you want (during the night, or in dimensions where you don't take sun damage)

Edit: On my server, I'm disabling bat mode due to how strong it is. As a compensation I've buffed a few other skills to make up for it.

**Comment by AlbertoJVD** [comment]
I don’t necessrily agree, as a bat you’re extremely weak with just two hearts, unless the regular health stays and the timer is applied then ok.

**Comment by flamechair** [comment]
@AlbertoJVD I agree, you are extremely weak as a bat. However all other actions as a Vampire have a cooldown/timer associated with them. Bat mode is the only one that does not. 

By simply adding a duration and cooldown key associated with bat mode to the config, we'd be free to customize it based on what works best for us. Setting the cooldown/timer to -1 would keep the action instantaneous.

**Comment by AlbertoJVD** [comment]
In your own game yes but servers and so on.

**Comment by flamechair** [comment]
If this change gets added, in the new release the config option could be defaulted to -1. This would keep things as they are currently, but allow server owners (like myself) the option to customize how we balance the mod.

**Comment by AlbertoJVD** [comment]
Ok I think that’s fair

**Comment by maxanier** [comment]
Due to the restrictions enforced in bat mode (health, can't place or break, ...) I think it is quite balanced (considering that most mods make you more powerful if you follow the system and craft or do certain things).

Actually, there already is a cooldown for that, but it is just 1/20 of a second :laughing:, not sure why I hardcoded that.
I will add a config option for that like for the other skills.

**Comment by maxanier** [comment]
Next version will allow configuration of both duration and cooldown duration of bat mode. Defaults are as before (infinite/0).
Configuration is in the vampire action balance settings.
