### ISSUE TITLE
Russian translate

### ISSUE THREAD

**Issue by McKoZa** [TeamLapen/Vampirism#264]
## Versions
- Minecraft:                    
- Forge:                       
- Vampirism:

**Comment by McKoZa** [comment]
I can help with translate your github page on russian language

**Comment by maxanier** [comment]
The Github wiki unfortunately does not have a translation system as far as I know.
But you could contribute to the Russian translation of the mod and guide book itself if you want:
https://crowdin.com/project/vampirism/ru
