### ISSUE TITLE
Vampires can only teleport when pointing at the top face of a block

### ISSUE THREAD

**Issue by flamechair** [TeamLapen/Vampirism#265]
## Versions
Minecraft: 1.12.2
Forge: forge-1.12.2-14.23.1.2555-universal-server
Vampirism: Vampirism-1.12-1.3.7                                      

## Issue Description
Vampires can only teleport to a block when they can see the top side of said block

## Reproduce Steps
1. Be a Vampire
2. Get teleport
3. Try to teleport upwards by hovering on the side/bottom of a block
4. Fail to teleport

**Comment by flamechair** [comment]
On second glance, this seems to be more the server and not the mod. Trying to teleport using the bottom or side of blocks produces errors in the server log: "X moved too quickly" or "X moved wrongly!" Not sure how much can be done to fix this

**Comment by maxanier** [comment]
I will have a look. I am pretty sure it works in single player, but not sure if I tested it on server side.
You are running Sponge right?

**Comment by maxanier** [comment]
Note to myself: Fix https://github.com/TeamLapen/Vampirism/blob/f2ebb3cedd46a7cba5cb423c4879f08e226409fd/src/main/java/de/teamlapen/vampirism/player/vampire/actions/TeleportVampireAction.java#L77
Cooldown not configurable (thx for reporting btw)

**Comment by flamechair** [comment]
Yep sponge forge 2842 I believe

**Comment by maxanier** [comment]
Unfortunately, I cannot reproduce this (without Sponge). It might be unrelated to Sponge and be rather caused by some strange network/latency behaviour, but I can't explain it right now.
However, Sponge should have a config to disable this kind of checks (something like "movement-checks"

**Comment by flamechair** [comment]
Yeah, this might be a sponge/forge issue handling the teleporting. I don't think this is from Vampirism
