### ISSUE TITLE
Game crashes in LAN multiplayer

### ISSUE THREAD

**Issue by leoamaro01** [TeamLapen/Vampirism#268]
## Versions
- Minecraft: 1.12.2                   
- Forge: 14.3.1.2555                      
- Vampirism: 1.3.4 -> 1.4.0alpha (latest)                                            

## Issue Description
When I was playing over LAN with a friend (I was the host), I attacked a Villager and, naturally, he turned into a vampire, then my friend got disconnected, when he tried to connect again his Minecraft crashed. We tried it backwards, he hosted, we did it again and the same thing happened to me.

## Reproduce Steps
-Host in LAN, somebody else join.
-Bite something (a cow, for example).
-When it turns, it will happend ( it isn't 100% accurate, it doesn't ALWAYS happends )

**Comment by maxanier** [comment]
Hello, thank you for reporting this.

Can you please post the crash report (should be in the minecraft folder in the crash_report directory) when this happens again. Maybe also the fml-client-latest log of the player hosting the game. Thank you

**Comment by leoamaro01** [comment]
SORRY! The crash report got deleted somehow, I tried again with 1.3.7 and it crashed again, and also with the 1.4.0a, me and my friend are really excited about this project, we love vampirism and we really support you!

**Comment by maxanier** [comment]
Glad to hear that you like the mod.
However, I need a crash report and/or the according log file. Otherwise I will not be able to help you.

Just upload the crash report when it crashes the next time.
This might help with locating the .minecraft folder and the crash report subfolder: https://help.mojang.com/customer/portal/articles/1480874-where-are-minecraft-files-stored-

Open the file in a text editor and upload the file here or e.g. https://paste.ee

**Comment by leoamaro01** [comment]
Ok, i'll do that next time I play with my friend, it should be next weekend, don't bother with files location, actually I am learning Java, so I can do mods or so, it isn't as easy as C# or JavaScript, but it ain't that hard. Thanks again!

**Comment by maxanier** [comment]
Alright, tested it myself today and can confirm there is an issue. Seems to be a very strange range related to nasty netty code.
Apparently the vanilla code and FMLProxyPacket do not work together nicely as the proxy packages cannot be send to multiple players without correct reference counting (e.g. like in https://github.com/MinecraftForge/MinecraftForge/pull/4536). For some reason this is only an issue in LAN.

**Comment by maxanier** [comment]
Should be fixed in next version
