### ISSUE TITLE
Vamp Books are not in chest?

### ISSUE THREAD

**Issue by bzald** [TeamLapen/Vampirism#271]
## Versions
- Minecraft: 1.12.2             
- Forge:  have to ask server person tommrow                     
- Vampirism:  1.12-1.3.7                                           

## Issue Description

I'm not sure what happen but if we are suppose to get the books from chest and such they are not spawning? Me and a vamp player has went into several places but no luck is that even possible? 

## Reproduce Steps

go into chasm looks for vamp castle finds nothing, go into abounded spelling mine finds 2ish, im sure i am forgetting somewhere.

 
## Additional Information

Since this seems to be a issue with loot drop in chest I will see what i can get for more info.

**Comment by maxanier** [comment]
I will have a look. 
Keep in mind they are only generated in certain locations and only by chance. However, vampire dungeons should have a 100% chance as far as I can remember

**Comment by maxanier** [comment]
I cannot reproduce this. Found a vampire dungeon with a book (should 100% chance).

For testing purposes you can enable world gen debug (/vampirism-test debugGen) in a test cheat world. It should log generated dungeons to the console/log.

**Comment by maxanier** [comment]
Closing this as there has been no response and the issue does not seem to exist
