### ISSUE TITLE
HWYLA/TOP compatability issue

### ISSUE THREAD

**Issue by Kordov19** [TeamLapen/Vampirism#275]
## Versions
- Minecraft: 1.12.2                    
- Forge:  14.23.2.2618                     
- Vampirism:  1.3.7   
- HWYLA: 1.8.23-B38
- The One Probe: 1.4.19                                        

My friend has Vampirism installed as well as HWYLA, and that shows him an entities blood. I wasn't getting that with The One Probe, so I installed HWYLA to use in tandem with TOP. When I looked at an entity, HWYLA didn't show the entity blood level like it did on my friends system.

Install HWYLA, look at an entity (preferably a cow/sheep/villager). Does it show entityBlood?

Additional Information

**Comment by maxanier** [comment]
This is feature (HWYLA integration) is only available when using both Vampirism 1.4 and [VampirismIntegrations](https://minecraft.curseforge.com/projects/vampirism-integrations). Both are still in alpha, so you might want to wait a few more weeks if you prefer a stable setup
