### ISSUE TITLE
vampire swords have very slow attack speeds

### ISSUE THREAD

**Issue by lag42** [TeamLapen/Vampirism#278]
## Versions
- Minecraft:1.12.2                    
- Forge:14.23.2.2624                    
- Vampirism:1.12.2-1.4.0-alpha+03-09-14-57

**Comment by maxanier** [comment]
This is intentional.
You need to use them to get better in using them. Each killed mob increases your attack speed slightly.
There should be a "Trained" percentage in the items tooltip
