### ISSUE TITLE
Requestings

### ISSUE THREAD

**Issue by evernife** [TeamLapen/Vampirism#28]
I know this is not the best way to ask, but at last, its a bug report.

I am using Vampirism with Twlight, and both use the same BiomeID. 
At this time i could change the Twilight one, but, i need to aks you to add an option to change que IDbiome in the config.

And another point, i suggest you to add an option in the config file to deactivate the spell "WEATHER"
This could really screw up in multiplayer servers (my case)

I do something to temporary resolve for me, i changed the min level to 10. But, it will be cool to have a option for each spell.

**Comment by maxanier** [comment]
In the next bigger version you will be able to set the min level of a skill to -1 to deactivate it. But if the  configuration property is not set to -1 on client side it will still show up

**Comment by maxanier** [comment]
The biome id should also be configurable then

**Comment by maxanier** [comment]
Also with the next update the altar tier 1 will be removed with the next bigger update, you will then have to get bitten to become a vampire. To deactivate that for you server, you will have to set the probability setting for this to the highest value (There will still be a very very tiny chance that it happens)

**Comment by evernife** [comment]
Ok, i liked it.
I will not put this version on my server, but the next one will. I really liked this mod, and i think it will be great.

I suggest you, to every commits you do, to make a jenkings, its really nice and we can test the issues more further

**Comment by maxanier** [comment]
I added a system which only builds snapshots or releases if it's requested in the commit message, since there often are commits which don't change much, are WIP (destroy the game) or else.
But I will try to sometimes request snapshot build which then can be found in the download section under "latest".

**Comment by evernife** [comment]
Thank You ^^
