### ISSUE TITLE
Undersized hit-box and eye level

### ISSUE THREAD

**Issue by LemADEC** [TeamLapen/Vampirism#280]
## Versions
- Minecraft:                 1.10.2
- Forge:                       1.10.2-12.18.3.2511
- Vampirism:               1.10.2-1.2.4

## Issue Description
I've noticed it's sometime hard to hit vampire hunter, especially from above.
According to debug overlay, the hitbox stops at eye level and eye is set to the neck for all the mod entities except the Ghost.

The Ghost appears to have invisible legs, making it possible to hit below it's actually body.

## Reproduce Steps
Spawn entites from the mod and press F3+B

## Additional Information
![image](https://user-images.githubusercontent.com/4776032/37565814-ab47a12e-2ab0-11e8-8b1a-ed200b7a794b.png)
![image](https://user-images.githubusercontent.com/4776032/37565871-6ff6133e-2ab1-11e8-9a7a-13f0c080505b.png)
![image](https://user-images.githubusercontent.com/4776032/37565887-b067c674-2ab1-11e8-914c-41e9b0dfdb5f.png)

**Comment by LemADEC** [comment]
Issue is also reproduced with 1.12.1-1.4.0-beta.1

**Comment by maxanier** [comment]
Thank you very much for reporting. Looks like I completely missed that.
Will fix that before the final 1.4 release.

/remind me about this in 7 days

**Comment by maxanier** [comment]
I always assumed the player is the same size as the standard biped mobs as they have the same model. But apparently the player is scaled during rendering.

I fixed the bounding boxes for most of Vampirism entities. However, won't modify the ghost as this would require quite some work and I don't think it is worth that effort.

Might backport this to 1.10 at some point
