### ISSUE TITLE
No Vampire Book

### ISSUE THREAD

**Issue by StrawberryCard** [TeamLapen/Vampirism#282]
## Versions
- Minecraft: 1.12.2                   
- Forge: 14.23.2.2640                      
- Vampirism: 1.3.7                                            

## Issue Description
I cannot get the 'vampire book' for level 5+

## Reproduce Steps
Create the infusion altar + pillars, and then realize that it doesn't work, as you need a vampire book, which doesn't exist.

## Additional Information
Nothing that I can think of.

**Comment by StrawberryCard** [comment]
Note: Guide book does not work.

**Comment by maxanier** [comment]
Vampire book refers to special books which can be found in (vampire) dungeons and are rarely dropped by advanced hunters.
They might not be named "vampire book" but have an individual (random) title.

Will check if the Guide Book explains this properly

**Comment by StrawberryCard** [comment]
Are they able to be found in creative mode?

**Comment by maxanier** [comment]
You should be able to find them in JEI.
Otherwise "/vampirism-test vampireBook" should help

**Comment by maxanier** [comment]
Is explained properly in the GuideBook.
Changed the display name in the creative inventory anyway
