### ISSUE TITLE
vampire keybind command issue

### ISSUE THREAD

**Issue by truesimonjs** [TeamLapen/Vampirism#283]
## Versions
- Minecraft:server version                    
- Forge: server version                      
- Vampirism:   server version                                          

## Issue Description
using the keybind command on 2 will make it override number 1 instead of adding it to number 2

## Reproduce Steps
1: bind dark blood to 1
2: use the keybind
3: bind bat to 2 
4:use keybind 2 it wont do anything
5:try to use keybind 1 again it will turn you to a bat

**Comment by maxanier** [comment]
Thank you for reporting. I will have a look
