### ISSUE TITLE
Client crash when doing ritual

### ISSUE THREAD

**Issue by stephen92** [TeamLapen/Vampirism#288]
## Versions
- Minecraft: 1.12.2                   
- Forge: 2669                      
- Vampirism: Vampirism-1.12.2-1.4.0-beta.2                                            

## Issue Description
When doing a ritual near by players crash.

## Reproduce Steps
Do a ritual with players around

## Additional Information
Crash Log:
https://pastebin.com/3W59FWJS

**Comment by maxanier** [comment]
Should be solved in the next version, though I am not 100% sure, as I was not able to reproduce it beforehand
