### ISSUE TITLE
Blood converting problem

### ISSUE THREAD

**Issue by Iceflame3029** [TeamLapen/Vampirism#289]
## Versions
- Minecraft: 1.12.2                   
- Forge: 2611                      
- Vampirism:Vampirism-1.12.2-1.4.0-beta.2                                             

## Issue Description
I cannot convert blood of Evilcraft mod to blood of this mod.

**Comment by maxanier** [comment]
Please explain what you have tried in more detail and if possible provide a screenshot of the block setup
