### ISSUE TITLE
Hunter Intel duplication bug

### ISSUE THREAD

**Issue by Witchcrafter1** [TeamLapen/Vampirism#296]
## Versions
- Minecraft:  1.12.2                  
- Forge:       forge-1.12.2-14.23.2.2611                
- Vampirism:   1.4.0 (release) 

- On the server                                           

## Issue Description

Duplication of the hunter Intel inside the hunter crafting table 

## Reproduce Steps

Place all needed ingredients in the table, 
Remove all ingredients 
Take a Intel
Repeat 

## Additional Information

Video with bug in #bugreports on discord 
Message is marked with
@maxanier bug by piklach

**Comment by maxanier** [comment]
Ah, was able to reproduce it now. Only occurs if you shift click to remove the items
