### ISSUE TITLE
Blood Pedsetal crash on place

### ISSUE THREAD

**Issue by Y0ungSandwich** [TeamLapen/Vampirism#298]
## Versions
- Minecraft:             1.12.2       
- Forge:                       forge-1.12.2-14.23.3.2655-universal
- Vampirism:                    Vampirism-1.12.2-1.4.1                         

Upon placing the Blood Pedestal in the world the game instantly locks up and crashes.

Place a Blood Pedestal in the world

https://pastebin.com/QJGcvgGh

The mod is compiled in the modpack Mech & Magic on the ATLauncher
https://www.atlauncher.com/pack/MechMagic

**Comment by maxanier** [comment]
Thank you for reporting. Will be fixed in the next release (probably in a couple of days)
