### ISSUE TITLE
Suggetion

### ISSUE THREAD

**Issue by evernife** [TeamLapen/Vampirism#30]
Make it compatible with ForgeEssentials.
Make only players with an specific permission transform in vampires.

Actually the best system is ForgeEssentials, being comptible with them will be really helpful.

(I am OutToDate, but i will download the lastest version and test the new features)

**Comment by maxanier** [comment]
I will consider making it compatible, but it won't be of priority.
By the way I would really appreciate it if you would post suggestions and feedback in the Minecraft Forum Thread http://goo.gl/qb1kie and only used Github issues for real issues or source code related stuff. Thanks :)
