### ISSUE TITLE
[Enhancement] Add config option to disable FOV change

### ISSUE THREAD

**Issue by GreatestFool** [TeamLapen/Vampirism#300]
When you're a vampire you end up with higher fov, this should be able to be disabled. When you're already playing on high fov increasing it even further can be a bit annoying. Being able to disable that would be much appreciated.

**Comment by maxanier** [comment]
Minecraft automatically does this depending on your speed. Since vampires are faster the FOV is automatically adjusted. But I can have a look if that can be circumvented.

**Comment by GreatestFool** [comment]
Oh, I didn't know that. Thanks for replying so quickly.
