### ISSUE TITLE
Mo's Custom Mob Spawner Mod messes with vampire spawns

### ISSUE THREAD

**Issue by ganhito** [TeamLapen/Vampirism#301]
## Versions
- Minecraft: 1.12.2                    
- Forge: 1.12.2 - 14.23.3.2655                      
- Vampirism: 1.4.1                                            

## Dont spawn vampires in the world on my server, but is possible to summon than using commands or spawn eggs.
Mods in using:
![sem titulo](https://user-images.githubusercontent.com/39133371/39830803-e01cea9c-5398-11e8-8cfa-941764947c01.png)

**Comment by maxanier** [comment]
Do Zombies spawn?

**Comment by PolarisHD** [comment]
I've been having this same issue as well, for the life of me I can't find a single vampire no matter where i look. Zombies spawn in massive numbers (I'm running the zombie awareness mod) but still not a single vampire. I believe it might have something to do with Mo'creatures but im not 100% sure just yet

**Comment by PolarisHD** [comment]
Yeah, after removing Mo' creatures, and it's required Custom Mob Spawner, I'm seeing vampires spawn all over the place.

**Comment by maxanier** [comment]
Thx, I will look into it.

**Comment by PolarisHD** [comment]
I did a bit of extra research, it turns out it's just the custom mob spawner that's stopping vampires from spawning, idk if that helps or not

**Comment by maxanier** [comment]
Thanks for testing that.
I tried it myself now and can confirm the issue. Somehow Custom Mob Spawner takes over the spawn process but does not see a reason to spawn vampires.
Unfortunately the mod is not Open Source, so it is difficult figuring out the exact reason. Maybe you can file a bug report at their end so they can help (I think the issue itself has to be fixed on their side anyway).

In the meantime I found a workaround:
Go to your config directory and look for the `CustomSpawner` directory. In there you should find a `overworld` folder with a `Creatures` subfolder. Edit the `DE.cfg` file and look for `vampire` and `vampire baron`. Change `canSpawn` to `true` and the `type` to `MONSTER`.
With that I was able to see some vampires spawn. However, I do not know if this is reset on certain occasions.

**Comment by PolarisHD** [comment]
I'm glad I could help! thanks for finding that workaround, I tried messing with those settings myself at one point, but I didn't see a change. Might want to say something about this issue in a mod compatibility section of your mod, so people don't continue to report this problem.
