### ISSUE TITLE
Vampire Forest too big

### ISSUE THREAD

**Issue by vrork** [TeamLapen/Vampirism#303]
Can we please get a config option to lower the size of it? Its too damn big and not dense enough (doesnt seem to make sense it not being dense).

Also, what does the realism config does?

**Comment by maxanier** [comment]
I will have a look, but the size is determined by the world generator. The default generator generates biomes of only one size as far as I know so I am not sure if this is possible.

The realism option changes a few default (balance) options at once. For example bitten creatures are not immediately converted but infected with sanguinare vampiris

**Comment by mjlmjl888** [comment]
Also they seem to spawn to often. Every world I create has one in view at spawn.

**Comment by maxanier** [comment]
In theory they should occur less often than any other "Warm" biome. Maybe you are just having bad luck
I will decrease the rate slightly though
