### ISSUE TITLE
Vampirism and Epic Siege

### ISSUE THREAD

**Issue by Ceifeire** [TeamLapen/Vampirism#306]
## Versions
- Minecraft: 1.12.2                    
- Forge: 14.23.2.2627                       
- Vampirism: 1.4.2

## Issue Description
So just did a mod update for the server including going up to the latest addition of Vampirism and added a mod called Epic Siege. The server is now constantly giving a message saying "could not replace creeper target task". Was just wondering if these 2 mods just dont talk well together because the epic siege mod alters the creeper AI a little bit.

## Reproduce Steps
install vampirism and epic siege together and then read the console window

## Additional Information
Don't see any crash reports yet but are having regular random kicks from the server
![vampirsim issue](https://user-images.githubusercontent.com/38624271/40576983-72fe951e-60cc-11e8-891a-acf60235789f.PNG)

**Comment by maxanier** [comment]
This means the Avoided by creeper vampire skill is not going to work. I can't really do much about that, but it should not be a big issue.
There should not be any other impact, so the random kicks are most likely unrelated.

If you want to get rid of these messages you can change the balance config `DISABLE_AVOIDED_BY_CREEPERS` (in Balance VampireSkills)
