### ISSUE TITLE
Add some more "story elements" to the GuideBook / Web / Extra journals

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#309]
From Discord@Nifilus#6309:

> So... Bat form for example: "The Vampires of old are said to have been birthed from the original Sanguine Demons, givers of the Dark Gift. These first Vampires marked the beginning of the Vampiric Bloodlines and had untold powers, quite different from the modern, lesser Vampires of today. The elder vampries had the abiltiy to shapeshift into a form which was greater than any Vampire Lord, and far from possible for any modern vampire, a form which marked the beginning of the mix between bats and humans. Throughout the ages, inbreeding, lessers Vampires, and more have tarnished and weakened the bloodlines, causing the weak bat form which most Vampires have now.

> The modern bat form is not without its advantages. The simple ability of flight in such a small form allows many vampires to travel the land quickly and easily, and to find into small spaces to get into homes for feeding. Many Vampiric abilities still can be used for further manipulation of this form, and the rich history of this form can still be felt in the blood which runs through any Vampire."

**Comment by maxanier** [comment]
Maybe as an addon mod (probably not necessary, unless there should be a ton of story) otherwise simply putting it in loot chests would do.

Only issue is that I personally don't like reading texts/books in MC as they are formatted really badly and there is far to less text per page. Maybe there is a different way.

**Comment by princessbinas** [comment]
Maybe a progression story like in other mods with progression such as Thaumcraft? Except, it is you either learning about your new vampire form and such or learning what it is like being a hunter.

**Comment by maxanier** [comment]
The "new" vampire books contain lore and stories
