### ISSUE TITLE
Weapons From Vampirism do not integrate with DSS

### ISSUE THREAD

**Issue by PolarisHD** [TeamLapen/Vampirism#313]
## Versions
- Minecraft:                             1.12.2             
- Forge:                                   14.23.4.2705
- Vampirism:                           1.4.2                     
- Dynamic Sword Skills:          6.0.1     

 Weapons from vampirism (Heartseeker, Heartstriker) do not integrate the effects/abilities from the Dynamic Sword Skills mod. This issue is not exactly game breaking or urgent but it would still be a nice touch, and would make said weapons more viable in modpacks that use the Dynamic Sword Skills mod.

N/A

**Comment by PolarisHD** [comment]
I tried adding heartseeker and heartstriker to the list of weapons and swords in DSS but it seems that that still hasn't solved the problem. Since other mods automatically integrate with DSS I'm not exactly sure what the problem is here.

**Comment by Jackiecrazy** [comment]
The problem, I believe, is that the vampirism swords don't seem to implement ItemSword. Perhaps certain parts of it could be moved to an interface to allow cross-mod compat? I'm not sure how difficult that'd be since my weapons directly stem off ItemSword, but an IBloodRechargeable interface doesn't sound terribly difficult.

**Comment by PolarisHD** [comment]
I wish I was capable of helping with something like that, if you come up with a temporary solution in the meantime, or some kind of a beta solution you'd like to test out I'd be more than happy to assist there, and anywhere else I can.

**Comment by maxanier** [comment]
I am not entirely sure why Vampirism's weapons do not extend ItemSword. Either I wanted to have some kind of base class for all of Vampirism's weapons (even not sword ones), or there was a more important reason.

I could probably change that, but I will have to make sure it does not break anything
