### ISSUE TITLE
If bat_duration is enabled, show visual notification when time is running out

### ISSUE THREAD

**Issue by flamechair** [TeamLapen/Vampirism#316]
## Versions
- Minecraft:  1.12.2                  
- Forge:  1.12.2 2705                     
- Vampirism:  Vampirism-1.12.2-1.4.2                                               

## Additional Information
Currently if `bat_duration` is set to a non-zero value, players don't know when they are almost out of time and can be forced out of bat mode without warning. It would be nice to have some potion effect with duration of `bat_duration` to keep the players informed

**Comment by maxanier** [comment]
Mhh, sounds reasonable. But I think I will have to add a custom Potion for that (e.g. "Bat mode"). Maybe we could add something similar to the sunscreen border which lights up during the last 10 seconds or so

**Comment by flamechair** [comment]
Yeah that could work, I'm up for any sort of visual notification
