### ISSUE TITLE
Make blood grinder take values from text file

### ISSUE THREAD

**Issue by flamechair** [TeamLapen/Vampirism#317]
## Versions
- Minecraft:  1.12.2                  
- Forge:  1.12.2 2705                     
- Vampirism:  Vampirism-1.12.2-1.4.2                                  

## Additional Information
The way you designed the custom defined blood values for sucking blood works fantastic, and it would be a great addition to implement the same system for what types of meat can be put inside the blood grinder so we can add other mod's meats in there.

Also Beef/Pork are included by default, but not Mutton. Is this intended?

**Comment by Teibidh** [comment]
I don't see a reference to this in the documentation, what is the filename and format to use for adding modded meat to the grinder?

**Comment by Cheaterpaul** [comment]
in 1.12 you can add the file `vampirism_blood_values_grinder.txt` to the vampirism config directory with the same pattern as https://github.com/TeamLapen/Vampirism/blob/1.12/src/main/resources/blood_values_grinder/default_blood_values.txt and/or submit the values

**Comment by maxanier** [comment]
@Cheaterpaul maybe you can update the wiki for 1.14 if you have some spare time https://github.com/TeamLapen/Vampirism/wiki/Biteable-Creatures-Blood-Grinder#114 and provide an example in https://github.com/TeamLapen/VampirismDatapackExamples.
I can't remember how it works, actually

**Comment by Cheaterpaul** [comment]
~~i didn't know you can use IMC messages to register blood values~~
sending IMC messages about the blood values have no effect at the moment

**Comment by maxanier** [comment]
I think that is fine, should be clear from the updated wiki.
Data packs should work as good
