### ISSUE TITLE
cant use my skills as a vampire

### ISSUE THREAD

**Issue by RaimboWBlood** [TeamLapen/Vampirism#318]
## Versions 
- Minecraft:1.12.2                    
- Forge:1.12.2-14.23.4.2712                       
- Vampirism:1.4.2                                             

## Issue Description
when i open my action thing and chose any skills it say: This action is not unlocked but i did unlock it in the skills menu

## Reproduce Steps
be a vampire

**Comment by maxanier** [comment]
Can you do the following for me:
- Unlock a skill
- Try using it
- Upload your ".minecraft/logs/fml-client-latest.log" or similar

Thank you.
Also: Are you playing in singleplayer or on a server?

**Comment by RaimboWBlood** [comment]
im on an other serv and it work so idk how and why

**Comment by maxanier** [comment]
If you need any more help, please do as described above
