### ISSUE TITLE
Thaumcraft Incompatibility

### ISSUE THREAD

**Issue by princessbinas** [TeamLapen/Vampirism#319]
## Versions
- Minecraft:  1.12.2                  
- Forge:   14.23.42705                    
- Vampirism:    1.12.2-1.4.2                                         

## Issue Description

When trying to complete Basic Auromancy Stage 2/3, as a vampire, you are unable to do so as fire is involved and fire damage is manipulated when it comes to vampire players. 

## Reproduce Steps

- Become a vampire and progress through Thaumcraft to Basic Auromancy 2/3.
- Walk into fire without fire protection or anything else that is not by default with being a vampire.
- Fail to progress because you don't get notified that you got close to fire and end up dying.

## Additional Information

Human players don't have this issue. Not sure about hunters though.

This issue is also on Anazor's Thaumcraft Issues page.
https://github.com/Azanor/thaumcraft-beta/issues/1052

**Comment by maxanier** [comment]
As a workaround you can go to your config directory (or use the GUI Main Menu -> Mods -> Vampirsm -> Config -> Balance) and open the Balance - vampire_player.cfg (Vampire Player General) and change fire_vulnerability_type to 0 and fire_vulnerability_max_mod to 1. Thereby the increased fire vulnerability added by Vampirism is deactivated.

**Comment by princessbinas** [comment]
Thank you, Max! I will help spread the word.
