### ISSUE TITLE
Blood Vision shows black screen

### ISSUE THREAD

**Issue by flamechair** [TeamLapen/Vampirism#322]
## Versions
- Minecraft:       1.12.2             
- Forge:             2705 (SF 3247)          
- Vampirism:     1.4.3                                        

## Issue Description
Blood vision just shows a black screen when toggled

## Reproduce Steps
Unlock blood vision
toggle it via the "n" key

## Additional Information
Optifine is installed, not sure if that is the culprit

**Comment by maxanier** [comment]
Yeah, blood vision is bugged on some systems. Some people reported it works without Optifine, some say they have the problem even without optifine. E.g. see #171
As this is difficult to debug, I decided to ignore this for now as it is not that big an issue and I don't want to change the way blood vision works.
