### ISSUE TITLE
Everytime i go to page four on the crossbow section in the guide book API it cashes my game

### ISSUE THREAD

**Issue by Rebelord01** [TeamLapen/Vampirism#325]
## Versions
- Minecraft: 1.12.2                   
- Forge:    1.12.2-14.23.3.2655                   
- Vampirism:   Vampirism-1.12.2-1.4.3                                          

## Issue Description
Everytime I go to page four on the crossbow sections in guide API the game crashes

## Reproduce Steps
open book go to crossbow section then go to page four

**Comment by maxanier** [comment]
I cannot reproduce this. Please provide a crash report https://github.com/TeamLapen/Vampirism/wiki/Troubleshooting#if-your-game-crashes-or-does-not-start-we-do-need-a-crashreport

**Comment by StevenSeegal** [comment]
Something similar but with a different page in the Guide Book
[Log](https://pastebin.com/5fTR8CwP)

**Comment by maxanier** [comment]
Thank you for the crash report. Looks like the latest version of GuideAPI introduced some changes. 
Will be fixed in Vampirism's next release. Until then please downgrade to GuideAPI 1.12-2.1.5-60 or lower
