### ISSUE TITLE
twilightforest and coffin spawn point

### ISSUE THREAD

**Issue by Hazender** [TeamLapen/Vampirism#326]
## Versions
- Minecraft: 1.12.2                   
- Forge: forge-1.12.2-14.23.4.2705                      
- Vampirism: Vampirism-1.12.2-1.4.3    
- Twilightforest: twilightforest-1.12.2-3.7.424-universal                                       

In the Twilight Forest it is always night.
So is not possible for a vampire to put his spawn point.
The coffin always says: "You can only sleep at day".

## Reproduce Steps
Place a coffin in Twilightforest or another dimension where it is always night and test to sleep.

## Additional Information

I am a big French fan.
Thank you for your work.

**Comment by maxanier** [comment]
I will think about his, I guess I will change the coffin to set the spawn point earlier (before checking for daytime)
