### ISSUE TITLE
Capabilities Crash

### ISSUE THREAD

**Issue by Sunconure11** [TeamLapen/Vampirism#327]
## Versions
- Minecraft: 1.12.2         
- Forge: 14.23.4.2738                       
- Vampirism: Vampirism-1.12.2-1.4.3                            

## Issue Description

While trying to figure out the cause of an unrelated error, I stumbled upon this crash

## Reproduce Steps

1. Install Vampirism
2. Install Reputed

## Additional Information

https://pastebin.com/0MkCb2Fx

**Comment by Sunconure11** [comment]
It also seems to blame repose.

@delvr @jaredlll08

**Comment by jaredlll08** [comment]
Fixed on my side

**Comment by maxanier** [comment]
Thank You
