### ISSUE TITLE
Please Update zh_cn.lang

### ISSUE THREAD

**Issue by sandtechnology** [TeamLapen/Vampirism#328]
Hi,I have updated the chinese translation,could you help me upload it?
[assets.zip](https://github.com/TeamLapen/Vampirism/files/2207859/assets.zip)

**Comment by maxanier** [comment]
Thank you for your contribution.

I have uploaded them at the translation portal used for Vampirism: https://crowdin.com/project/vampirism/zh-CN
But it does not look like any new strings have been translated. Maybe you can check yourself if it works.
For future contributions please use that website directly if possible. Translations uploaded there will be included in the next release.

**Comment by sandtechnology** [comment]
Have you upload it correctly?
The assets.zip included Vampirismguide(assets\vampirismguide\lang\zh_cn.lang) and Vampirism(assets\vampirism\lang\zh_cn.lang) as translation.

**Comment by maxanier** [comment]
I tried again and this time it worked. Chinese translation seems to be complete for now.
New strings will be included in next release. Thank you
