### ISSUE TITLE
Possible conflict with Vampire Hunter Merchants

### ISSUE THREAD

**Issue by Sunconure11** [TeamLapen/Vampirism#329]
As I am not 100% sure as to what mod is behind this, I will just a take a screencap instead.

![screenshot 2018-07-19 16 24 13](https://user-images.githubusercontent.com/5614902/42968100-4ce847d4-8b70-11e8-9d6c-db2bd51c763e.png)

**Comment by maxanier** [comment]
Was my bad. Fixed in next release.
Vanilla MC is very inconsistent with their lower casing
