### ISSUE TITLE
[Bug]The blood potion table can make any stackable item become Double

### ISSUE THREAD

**Issue by MoeShimaKaze** [TeamLapen/Vampirism#333]
## Versions
- Minecraft:1.12.2                    
- Forge: 1.12.2-14.23.4.2705                      
- Vampirism: Vampirism-1.12.2-1.4.3                                            

## Issue Description
i running in SSP,or SpongeForge Server,the problem still exist
The blood potion table can make any stackable item become Double
Just put it inside The box indicated by the arrow in the picture
Pictuere:https://upload.cc/i1/2018/08/03/Xsz0Le.png

## Reproduce Steps
First,become a hunter,learn how to use the blood potion table and take a  any stackable item
such as Iron ingots，and put one into The box indicated by the arrow in the picture
Pictuere:https://upload.cc/i1/2018/08/03/Xsz0Le.png
and Hold Shift to take him out,the thing become double
you also can watch this vedio to lean how to REPRODUCE this
https://youtu.be/R0l_O5UBQxU

## Additional Information
i do not find the error logs

**Comment by maxanier** [comment]
Thank you for reporting. Looks like I had trouble counting to 4 when implementing this :see_no_evil:

**Comment by MoeShimaKaze** [comment]
thanks!

**Comment by maxanier** [comment]
A fixed version should be available later today
