### ISSUE TITLE
Mortar Glitch, witch items

### ISSUE THREAD

**Issue by avescarelo** [TeamLapen/Vampirism#337]
## Versions
- Minecraft: 1.12.2                   
- Forge: 14.23.4.2747                       
- Vampirism: 1.4.3                                            

## Issue Description
When I try to open the Altar with an empty Hand without having a level, it does not come out.
But i clicked an any item on the Altar, i can use its interface.

## Additional Information
![image](https://user-images.githubusercontent.com/26678843/43963619-7e4630d4-9cc3-11e8-947c-18b78183a9ee.png)

**Comment by maxanier** [comment]
This is kind of intentional.
I need to distinguish if you want to access the inventory or to start the ritual. So I decided that using an empty hand initiates the ritual, but holding an item opens the GUI.
You have to start the ritual with an empty hand.
