### ISSUE TITLE
Idea from update :D

### ISSUE THREAD

**Issue by GilgameshDragonBorn** [TeamLapen/Vampirism#34]
How about add a boss?specifically the Dracula?and a new mobs,maybe gargoyle,frankenstein or even a werewolf? sounds good :D something like a entire castle guarded by minions(gargoyle,frakenstein,werewolf),the floor of red wool and black,walls with obsidian,at the very top of the castle the boss,Dracula,150~300 life points,8 hearts of damage without protection per hit,poison effect each hit,or wither eff,but the poison somehow is more "realistic",and give Drácula speed,strength,no sun damage,and some regeneration,would be one of the best challenges xD,i have a loooooooooooot of ideas to the mod,if you want of course,i can help a lot,i think and i can divulge on facebook,twitter,even curse :O leave a reply if so.Thanks,and that mod is awesome.

**Comment by maxanier** [comment]
Thanks for the suggestions:
Quite a lot of the things you suggested are already planned or even almost done. Take a look at the "Upcoming Version" spoiler in the main forum post.
More ideas are always welcome :), but please post them on the Minecraft Forum and keep the Github issues for bugs and crashes, thanks.
