### ISSUE TITLE
branche 1.12 code issue

### ISSUE THREAD

**Issue by Cheaterpaul** [TeamLapen/Vampirism#342]
## Versions
-Branche 1.12
-Commit [15657b6](https://github.com/TeamLapen/Vampirism/commit/15657b68271cd624c0dfc974ab971da0629181e6)
                        

## Issue Description

https://github.com/TeamLapen/Vampirism/blob/1.12/src/main/java/de/teamlapen/vampirism/entity/EntityFactionVillager.java line 54 & 57/58

the class can't see the populateBuyingList() method and buyingList field from EntityVillager (private)

**Comment by maxanier** [comment]
You probably have to run the setup gradle tasks (setupDecompWorkspace, eclipse ..., the same two used during initial setup, no need to regenerate the run configuration) again.

The mentioned fields are private by default, but Forge has a AccessTransformer system in place which can modify the field/method attributes on load. See https://github.com/TeamLapen/Vampirism/blob/1.12/src/main/resources/vampirism_at.cfg

To see this changes in your development environment gradle has to re-decompile Minecraft

**Comment by Cheaterpaul** [comment]
thought about this 3 sec befor i got the notification
