### ISSUE TITLE
1.4.5 does not fix crash with guide-api on newer versions of forge

### ISSUE THREAD

**Issue by tsheinen** [TeamLapen/Vampirism#346]
## Versions
- Minecraft: 1.12.2                    
- Forge:   14.23.4.2750
- Vampirism:    1.4.5                 

## Issue Description

Vampirism + Guide-API crashes with newer versions of forge.  It worked fine on one of my old instances running forge 14.23.1.2555.  I haven't determined how far forward I can go before it crashes, but I know 2750 crashes.  

## Reproduce Steps

1.  Install Vampirism and Guide-API
2.  Install forge 14.23.4.2750 (or potentially older ones?)  
3.  Start up minecraft

## Additional Information

https://paste.dimdev.org/vozebuxivo.mccrash

Thanks!

**Comment by tsheinen** [comment]
It seems to be fixed on forge 14.23.4.2751, I imagine it was the same issue as ExU2 and Gendustry.

**Comment by maxanier** [comment]
Thanks for reporting the solution :) Did save me some time

**Comment by maxanier** [comment]
Related forge issue: https://github.com/MinecraftForge/MinecraftForge/pull/5105
Should be fixed with latest Forge, but somehow the MC assets that where triggering this issue, have also been changed so maybe just recreating the game profile or similar should fix it too
