### ISSUE TITLE
reduce damage from the sun and more skills 

### ISSUE THREAD

**Issue by iccarusA** [TeamLapen/Vampirism#350]
## Versions
- Minecraft: 1.12.2                   
- Forge: 14.23 .4.2705                     
- Vampirism: 1.50                                            

## Issue Description
I think in a potion, ring or armors can reduce, or nulify all the damage from the sun.
vampires need more skills and more lvls, trasformation for vampire lord and do blood magic like skyrim

## Reproduce Steps

https://www.youtube.com/watch?v=3DnGTemyjh0

**Comment by maxanier** [comment]
Sun damage will stay as is. More skills and transformations are planned
