### ISSUE TITLE
Typo in vampire player action balance

### ISSUE THREAD

**Issue by xoption** [TeamLapen/Vampirism#352]
## Versions
- Minecraft: 1.12.2                   
- Forge:  N/A                     
- Vampirism: 1.12.2-1.5.0-alpha+08-16-14-13                                            

## Auto-generated  balance\vampire_player_actions.cfg has a type-O line 63 

I:summon_bats_ooldown=300
should be 
I:summon_bats_cooldown=300

**Comment by maxanier** [comment]
Thx.
But changing this would break old config files, so I will postpone this until the 1.13 update.
Edit: Btw, if you change this, it will not be recognized

**Comment by xoption** [comment]
Thanks for the info! Great work on the mod!
