### ISSUE TITLE
Update Gradle?  I needed to update gradle locally to build.  

### ISSUE THREAD

**Issue by tsheinen** [TeamLapen/Vampirism#353]
I was trying to build Vampirism locally and I had trouble because the forge dependency couldn't be found.  I looked through the log and the only thing similar to an error I found was it complaining about invalid cookie headers on the ExtractMCPMappings step. 

```
:extractMcpMappings
Invalid cookie header: "Set-Cookie: AWSALB=3T+xYcDSipe/Iug1Z0DuCUKpcgc7nY9ja3RGaOjLRS51CfbUtlMXKGrV+NSG5JgDnvlHfOPfs9VTartuc93z1tfSYOs4KWxGri9GVj2yk0SC4MJoHu5RG+KJ/yAu; Expires=Sat, 01 Sep 2018 15:12:55 GMT; Path=/". Invalid 'expires' attribute: Sat, 01 Sep 2018 15:12:55 GMT
```

I did some searching for this error and I found that it was a known issue in old versions of Gradle, caused by an old version of Apache HTTPClient.  The gradle issue report can be found at https://github.com/gradle/gradle/issues/1596.  The issue doesn't mention any troubles compiling so I'm not certain that this is the source of my problem, but after updating Gradle to 4.4 my problem was solved so it might be worth updating anyway.  

Thanks!

**Comment by maxanier** [comment]
I have those logs too, but it is working for me.
How did you try to build Vampirism (`./gradlew build` , `gradle build` , `gradlew.bat build` , ) and are you using Linux or Windows?

I remember some discussion on the MinecraftForge repo about gradle 4+. For some reason they did not want to use it, so they are still using 2.14. 
But I guess as long as it is working ...

**Comment by tsheinen** [comment]
I was using Windows with IntelliJ.  I didn't actually get to the build step, the problem was that during the workspace setup (gradlew setupDecompWorkspace) it didn't download forge for some reason.  I suppose if it works fine for you then it's probably something else and there isn't any need to change it.  You might want to mention it when you're giving instructions on setting up the development environment though.

**Comment by maxanier** [comment]
Hmm, I double checked and we are already using 3.x anyway. Also it seems other popular mods are using all kind of gradle versions.

Guess I will just update it to 4.4+ then.

**Comment by maxanier** [comment]
Updated gradle to 4.4 97d9bbc28d0dee0b3ec3f9dd5bc7bf7eb392699d
As a additional benefit console output looks a lot nicer now :)
