### ISSUE TITLE
Crossbows, crossbows everywhere

### ISSUE THREAD

**Issue by Sunconure11** [TeamLapen/Vampirism#354]
Crossbows are appearing in most tabs.

![screenshot 2018-08-26 21 38 21](https://user-images.githubusercontent.com/5614902/44636208-69bd8d80-a978-11e8-84cf-583e10fc9dcf.png)

**Comment by maxanier** [comment]
So? Crossbows are awesome you want to have them everywhere.
Just kidding :D 
Thanks for reporting will be fixed
