### ISSUE TITLE
Integration with Game Stages mod

### ISSUE THREAD

**Issue by avescarelo** [TeamLapen/Vampirism#356]
## Versions
- Minecraft: 1.12.2                   
- Forge: 14.23.4.2750                      
- Vampirism: 1.12.2-1.5.0-alpha+08-16-14-13                                

## Suggestion

Make please integration with GameStagesMod
Link to this mod: https://minecraft.curseforge.com/projects/game-stages

**Comment by maxanier** [comment]
Can you be more specific? What exactly should Vampirism do in conjuction with the GameStages mod?
