### ISSUE TITLE
Not turning into a vampire

### ISSUE THREAD

**Issue by timbirtles** [TeamLapen/Vampirism#357]
## Versions
- Minecraft:  1.12.2                  
- Forge:  14.23.4.2758                     
- Vampirism: Latest                                            

I have eaten 3 vampire fangs and the potion effect just dissapears after a while and I do not turn into a vampire. I haven't been drinking any milk

**Comment by maxanier** [comment]
That is strange. I assume you also did not die in the meantime?

Maybe there is a conflict with another mod.
To be able to debug this I need a log file which includes the moment when the potion wears off.
Please infect yourself again and write "Now" into the chat once the effect disappeared. Then upload your log file like described here: https://github.com/TeamLapen/Vampirism/wiki/Troubleshooting#if-your-game-crashes-or-does-not-start-we-do-need-a-crashreport
