### ISSUE TITLE
can not use skills

### ISSUE THREAD

**Issue by splesh321** [TeamLapen/Vampirism#358]
## Versions
- Minecraft:1.12.2                    
- Forge:14.23.4.2705                       
- Vampirism:1.5.0                                             

## Issue Description
when trying to use regerneration or sun screen ability's 'This action is not unlocked'
this is unlocked and i am playing on a server

**Comment by ProsperCraft** [comment]
We have the same issue on our multiplayer server-

Vampirism-1.12.2-1.5.0-alpha+09-26-15-05
forge-1.12.2-14.23.4.2760-universal

![58830bef9261e5999c222c33792a358e](https://user-images.githubusercontent.com/4427684/46229157-e221c080-c321-11e8-8b0c-1683dfb1b1ac.png)

**Comment by maxanier** [comment]
Thanks for reporting.
There has been a bigger internal issue. I am surprised it did not cause any more trouble.
Should be fixed now
