### ISSUE TITLE
Stacktrace in console - NPE SimpleChannelHandlerWrapper

### ISSUE THREAD

**Issue by ProsperCraft** [TeamLapen/Vampirism#359]
## Versions
- Minecraft:          1.12.2          
- Forge:                       14.23.4.2760
- Vampirism:       1.12.2.1.5.0-alpha 09 08 14 41                                      

## Issue Description
Console stacktraces.

SimpleChannelHandlerWrapper exception
java.lang.NullPointerException: null

## Additional Information

Modpack - TownCraft [https://minecraft.curseforge.com/projects/ancient-towncraft](https://minecraft.curseforge.com/projects/ancient-towncraft)
https://gist.github.com/ProsperCraft/e5fbb4027de22acd3534c4c1d4286d79

**Comment by maxanier** [comment]
Unfortunately the topmost lines of the stacktrace are missing but I think I have found the issue which was introduced with #355. Should be fixed with the next release

**Comment by maxanier** [comment]
Thank you for reporting and sorry for the long wait
