### ISSUE TITLE
Stacktrace in console - NPE - .AbstractPacketDispatcher.sendTo

### ISSUE THREAD

**Issue by ProsperCraft** [TeamLapen/Vampirism#360]
## Versions
- Minecraft:    1.12.2
- Forge:           forge-1.12.2-14.23.4.2760-universal.jar            
- Vampirism:    Vampirism-1.12.2-1.5.0-alpha+09-08-14-41.jar                                          

## Issue Description
When my client crashed due to Effortless building, I got this stacktrace in console.

https://gist.github.com/ProsperCraft/82c71d40f713a691dd4aa842ce56b8fe

**Comment by ProsperCraft** [comment]
I I was just unable to log in to the multiplayer server due to this issue- 

Console- https://gist.github.com/ProsperCraft/373b9415dae8bbc7d382775129ba7f34

**Comment by maxanier** [comment]
Seems to have the same origin as #359
