### ISSUE TITLE
Crashing my world but not game.

### ISSUE THREAD

**Issue by jonathan-x01** [TeamLapen/Vampirism#361]
## Versions
- Minecraft: 1.12.2                   
- Forge: 14.23.4.2705                      
- Vampirism: 1.4.2-1.5.0_alpha                                            

## Issue Description
So last night I upgraded the mod and a couple others including forge but after it didn't like start my game world but started the game.

## Reproduce Steps
http://www.minecraftforge.net/forum/topic/66555-game-crashing/?tab=comments#comment-319295
Just click this link and someone explains how to fix it. For some odd reason as well is that it isn't working for all versions when it did before.

## Additional Information
None

**Comment by maxanier** [comment]
This issue appears to only occur together with another mod which changes the behaviour of MC. However, it's probably still an issue at our end. It will be fixed with the next release
