### ISSUE TITLE
Sunscreen

### ISSUE THREAD

**Issue by jordan11v** [TeamLapen/Vampirism#363]
## Versions
- Minecraft:  1.12.2                  
- Forge:        .2750               
- Vampirism:   1.4.6                                          

## Issue Description
Simply put when you get to rank 5 and try to unlock sunscreen and bind and use it. It doesnt work.

**Comment by tsheinen** [comment]
I can't reproduce on identical versions.  Can you confirm that this is still the case on a separate creative world?  Does it work with the wheel?

**Comment by jordan11v** [comment]
The wheel? Is that the hold R thing because i cant even get that up. For me
im trying to bind it to alt 2. Its 1am at sending time ill try in a single
player world tomorrow

**Comment by maxanier** [comment]
I cannot reproduce this either (SP or MP), but I am guessing this has the same cause as #364 . So I will wait for the crash report

**Comment by jordan11v** [comment]
Sunscreen doesnt crash the game. It simply says to me the skill isnt
unlocked even though i have it unlocked.

**Comment by jordan11v** [comment]
solved by the alpha
