### ISSUE TITLE
Bat Swarm game crash bug

### ISSUE THREAD

**Issue by jordan11v** [TeamLapen/Vampirism#364]
## Versions
- Minecraft: 1.12.2                   
- Forge: .2750                      
- Vampirism:   1.4.6                                          

## Issue Description
You try to use the ability you crash

## Reproduce Steps
Have your bat form set to alt 1 and your swarm to alt 2 and try to use alt 2 and you crash.

**Comment by maxanier** [comment]
Unfortunately I am unable to reproduce this.
Can you upload the entire crash report please (.minecraft/crash-reports/...)

**Comment by jordan11v** [comment]
The game crashed whilst ticking entity
Error: java.lang.ClassCastException:
de.teamlapen.vampirism.player.vampire.actions.SummonBatVampireAction cannot
be cast to de.teamlapen.vampirism.api.entity.player.actions.ILastingAction

That above is what was in the little box. Ill send the full log next.

The server runs on a custom mod pack. Everything else works just fine but
batswarm and sunscreen(#363) to my knowledge so far.but here is the rest of
the log

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ObfuscatePlugin (obfuscate-0.2.5-1.12.2.jar)
  AstralCore (astralsorcery-1.12.2-1.9.4 (1).jar)
  llibrary (llibrary-core-1.0.8-1.12.2.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta:
[~~HUG~~]

Time: 10/2/18 1:00 PM
Description: Ticking entity

java.lang.ClassCastException:
de.teamlapen.vampirism.player.vampire.actions.SummonBatVampireAction cannot
be cast to de.teamlapen.vampirism.api.entity.player.actions.ILastingAction
at
de.teamlapen.vampirism.player.actions.ActionHandler.updateActions(ActionHandler.java:275)
at
de.teamlapen.vampirism.player.vampire.VampirePlayer.onUpdate(VampirePlayer.java:744)
at
de.teamlapen.lib.entity.EntityEventHandler.onLivingUpdate(EntityEventHandler.java:80)
at
net.minecraftforge.fml.common.eventhandler.ASMEventHandler_891_EntityEventHandler_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic)
at
net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
at
net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:567)
at
net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088)
at
net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
at
net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:181)
at net.minecraft.world.World.func_72866_a(World.java:1990)
at net.minecraft.world.World.func_72870_g(World.java:1952)
at net.minecraft.world.World.func_72939_s(World.java:1756)
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1846)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is
as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
at
de.teamlapen.vampirism.player.actions.ActionHandler.updateActions(ActionHandler.java:275)
at
de.teamlapen.vampirism.player.vampire.VampirePlayer.onUpdate(VampirePlayer.java:744)
at
de.teamlapen.lib.entity.EntityEventHandler.onLivingUpdate(EntityEventHandler.java:80)
at
net.minecraftforge.fml.common.eventhandler.ASMEventHandler_891_EntityEventHandler_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic)
at
net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
at
net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:567)
at
net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088)
at
net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
at
net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:181)
at net.minecraft.world.World.func_72866_a(World.java:1990)
at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
Entity ID: 737
Entity Name: jordan11v
Entity's Exact location: 499.24, 75.00, 308.05
Entity's Block location: World: (499,75,308), Chunk: (at 3,4,4 in 31,19;
contains blocks 496,0,304 to 511,255,319), Region: (0,0; contains chunks
0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Entity's Momentum: 0.00, -0.08, 0.00
Entity's Passengers: []
Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
at net.minecraft.world.World.func_72939_s(World.java:1756)

-- Affected level --
Details:
Level name: MpServer
All players: 1 total; [EntityPlayerSP['jordan11v'/737, l='MpServer',
x=499.24, y=75.00, z=308.05]]
Chunk stats: MultiplayerChunkCache: 225, 225
Level seed: 0
Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
Level generator options:
Level spawn location: World: (-257,64,358), Chunk: (at 15,4,6 in -17,22;
contains blocks -272,0,352 to -257,255,367), Region: (-1,0; contains chunks
-32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Level time: 2719644 game time, 4288393 day time
Level dimension: 0
Level storage version: 0x00000 - Unknown?
Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Forced entities: 51 total; [EntityPlayerSP['jordan11v'/737, l='MpServer',
x=499.24, y=75.00, z=308.05], EntityLatchedRenderer['unknown'/3,
l='MpServer', x=499.24, y=75.00, z=308.05],
EntityItem['item.item.egg'/5151, l='MpServer', x=557.98, y=72.00,
z=253.66], EntityItem['item.item.egg'/5162, l='MpServer', x=563.04,
y=76.00, z=268.52], EntityPig['Pig'/3115, l='MpServer', x=571.78, y=66.00,
z=377.40], EntityChicken['Chicken'/815, l='MpServer', x=504.54, y=71.00,
z=372.47], EntityItem['item.item.egg'/5168, l='MpServer', x=552.03,
y=69.00, z=327.23], EntityChicken['Chicken'/3136, l='MpServer', x=531.13,
y=74.00, z=255.42], EntityChicken['Chicken'/3137, l='MpServer', x=529.50,
y=72.00, z=241.89], EntityBat['Bat'/5197, l='MpServer', x=446.45, y=15.10,
z=339.25], EntityChicken['Chicken'/3150, l='MpServer', x=569.80, y=79.00,
z=289.61], EntityBat['Bat'/5198, l='MpServer', x=444.25, y=15.10,
z=320.42], EntityItemFrame['entity.ItemFrame.name'/3927, l='MpServer',
x=497.50, y=71.50, z=310.97],
EntityItem['item.item.bloodmagic.upgradeTome'/5207, l='MpServer', x=502.49,
y=69.00, z=302.13], EntityCow['Cow'/3929, l='MpServer', x=510.52, y=70.00,
z=317.45], EntityCow['Cow'/3930, l='MpServer', x=511.53, y=70.00,
z=317.90], EntityItem['item.item.rottenFlesh'/5216, l='MpServer', x=502.88,
y=70.00, z=300.98], EntityPainting['Painting'/3496, l='MpServer', x=637.00,
y=69.00, z=335.97], EntityItem['item.item.minecraft:apple'/5217,
l='MpServer', x=503.26, y=71.00, z=301.24],
EntityItem['item.item.vampirism.armor_of_swiftness.chest'/5218,
l='MpServer', x=502.88, y=70.00, z=300.91], EntityPainting['Painting'/2351,
l='MpServer', x=637.00, y=69.00, z=335.97],
EntityItem['item.item.chococraft.ability_fruit.spike_fruit'/5230,
l='MpServer', x=502.88, y=70.00, z=300.98],
EntityItem['item.item.egg'/4975, l='MpServer', x=557.47, y=74.00,
z=280.07], EntityChicken['Chicken'/2928, l='MpServer', x=552.72, y=69.00,
z=327.27], EntityPainting['Painting'/3496, l='MpServer', x=637.00, y=69.00,
z=335.97], EntityPainting['Painting'/1295, l='MpServer', x=637.00, y=69.00,
z=335.97], EntityItemFrame['entity.ItemFrame.name'/3964, l='MpServer',
x=494.50, y=69.50, z=312.97], EntityItemFrame['entity.ItemFrame.name'/3967,
l='MpServer', x=495.50, y=69.50, z=312.97], EntityItemFrame['
entity.ItemFrame.name'/3968, l='MpServer', x=493.03, y=69.50, z=312.50],
EntityItem['item.item.egg'/4992, l='MpServer', x=542.72, y=65.00,
z=365.61], EntityItemFrame['entity.ItemFrame.name'/3969, l='MpServer',
x=493.03, y=70.50, z=312.50], EntityChicken['Chicken'/3982, l='MpServer',
x=472.17, y=67.00, z=256.48], EntityChicken['Chicken'/2977, l='MpServer',
x=576.50, y=77.00, z=284.04], EntityChicken['Chicken'/4288, l='MpServer',
x=427.88, y=77.00, z=250.60], EntityHorse['Horse'/4291, l='MpServer',
x=429.13, y=69.00, z=362.18], EntityChicken['Chicken'/3021, l='MpServer',
x=577.57, y=70.00, z=361.49], EntityChicken['Chicken'/3022, l='MpServer',
x=577.17, y=69.00, z=365.87], EntityChicken['Chicken'/3023, l='MpServer',
x=558.04, y=74.00, z=273.50], EntityItem['item.item.egg'/4816,
l='MpServer', x=471.94, y=67.00, z=256.33], EntityChicken['Chicken'/3026,
l='MpServer', x=566.49, y=78.00, z=284.83], EntityChicken['Chicken'/3027,
l='MpServer', x=557.90, y=74.00, z=279.61], EntityChicken['Chicken'/3031,
l='MpServer', x=565.50, y=77.00, z=267.79], EntityChicken['Chicken'/3037,
l='MpServer', x=546.34, y=66.00, z=291.88], EntityChicken['Chicken'/3046,
l='MpServer', x=562.85, y=76.00, z=268.60], EntityChicken['Chicken'/3051,
l='MpServer', x=532.19, y=73.00, z=259.59], EntityChicken['Chicken'/3053,
l='MpServer', x=558.45, y=72.00, z=252.78], EntityChicken['Chicken'/751,
l='MpServer', x=542.12, y=65.00, z=366.29], EntityChicken['Chicken'/752,
l='MpServer', x=551.16, y=67.00, z=356.58],
EntityItem['item.item.onionitem'/4851, l='MpServer', x=500.31, y=70.00,
z=306.69], EntityItem['item.item.ma.crafting_inferium_essence'/4852,
l='MpServer', x=500.31, y=70.00, z=306.69], EntityBat['Bat'/5109,
l='MpServer', x=505.25, y=12.10, z=269.25]]
Retry entities: 0 total; []
Server brand: fml,forge
Server type: Non-integrated multiplayer server
Stacktrace:
at
net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
Minecraft Version: 1.12.2
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle
Corporation
Memory: 663664696 bytes (632 MB) / 2432696320 bytes (2320 MB) up to
5368709120 bytes (5120 MB)
JVM Flags: 8 total;
-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
-Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC
-XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50
-XX:G1HeapRegionSize=16M
IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
FML: MCP 9.42 Powered by Forge 14.23.4.2750 Optifine
OptiFine_1.12.2_HD_U_E2 42 mods loaded, 42 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized
'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E'
= Errored

| State  | ID                                   | Version
| Source                                            | Signature
                    |
|:------ |:------------------------------------ |:------------------------
|:-------------------------------------------------
|:---------------------------------------- |
| UCHIJA | minecraft                            | 1.12.2
 | minecraft.jar                                     | None
                     |
| UCHIJA | mcp                                  | 9.42
 | minecraft.jar                                     | None
                     |
| UCHIJA | FML                                  | 8.0.99.99
| forge-1.12.2-14.23.4.2750.jar                     |
e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UCHIJA | forge                                | 14.23.4.2750
 | forge-1.12.2-14.23.4.2750.jar                     |
e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UCHIJA | obfuscate                            | 0.2.5
| minecraft.jar                                     | None
                   |
| UCHIJA | adventurepack                        | 1.5.0
| adventurepack-1.5.jar                             | None
                   |
| UCHIJA | antiqueatlas                         | 4.4.9
| antiqueatlas-1.12.2-4.4.9.jar                     | None
                   |
| UCHIJA | antiqueatlasoverlay                  | 1.2
| antiqueatlas-1.12.2-4.4.9.jar                     | None
                   |
| UCHIJA | examplemod                           | 1.0
| antiqueatlas-1.12.2-4.4.9.jar                     | None
                   |
| UCHIJA | baubles                              | 1.5.2
| Baubles-1.12-1.5.2 (3).jar                        | None
                   |
| UCHIJA | astralsorcery                        | 1.9.4
| astralsorcery-1.12.2-1.9.4 (1).jar                |
a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
| UCHIJA | bard_mania                           | 0.11.0-alpha
 | bard-mania_1.12.2-0.11.0-alpha.jar                |
999640c365a8443393a1a21df2c0ede9488400e9 |
| UCHIJA | biomesoplenty                        | 7.0.1.2399
 | BiomesOPlenty-1.12.2-7.0.1.2399-universal (1).jar | None
                     |
| UCHIJA | guideapi                             | 1.12-2.1.7-62
| Guide-API-1.12-2.1.7-62.jar                       | None
                   |
| UCHIJA | bloodmagic                           | 1.12.2-2.3.3-101
 | BloodMagic-1.12.2-2.3.3-101.jar                   | None
                     |
| UCHIJA | jei                                  | 4.13.0.218
 | jei_1.12.2-4.13.0.218.jar                         | None
                     |
| UCHIJA | thaumcraft                           | 6.1.BETA24
 | Thaumcraft-1.12.2-6.1.BETA24.jar                  | None
                     |
| UCHIJA | botania                              | r1.10-356
| Botania+r1.10-356.jar                             | None
                   |
| UCHIJA | chococraft                           | 0.9.1.52
 | chococraft_1.12.1-0.9.1.52 (1).jar                | None
                     |
| UCHIJA | cosmeticarmorreworked                | 1.12.2-v3
| CosmeticArmorReworked-1.12.2-v3.jar               |
aaaf83332a11df02406e9f266b1b65c1306f0f76 |
| UCHIJA | cosmeticarmorreworked|tombmanygraves | 1.12.2-v3
| CosmeticArmorReworked-1.12.2-v3.jar               |
aaaf83332a11df02406e9f266b1b65c1306f0f76 |
| UCHIJA | cucumber                             | 1.1.1
| Cucumber-1.12.2-1.1.1.jar                         | None
                   |
| UCHIJA | howlingmoon                          | 0.9
| howlingmoon-1.12.2-0.9.jar                        | None
                   |
| UCHIJA | llibrary                             | 1.7.15
 | llibrary-1.7.15-1.12.2 (1).jar                    |
b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
| UCHIJA | iceandfire                           | 1.5.2
| iceandfire-1.5.2.jar                              | None
                   |
| UCHIJA | ichunutil                            | 7.1.4
| iChunUtil-1.12.2-7.1.4.jar                        | None
                   |
| UCHIJA | ironbackpacks                        | 1.12.2-3.0.8-12
| IronBackpacks-1.12.2-3.0.8-12.jar                 | None
                   |
| UCHIJA | ironchest                            | 1.12.2-7.0.46.831
| ironchest-1.12.2-7.0.46.831.jar                   | None
                   |
| UCHIJA | lootbags                             | 2.5.7
| LootBags-1.12.2-2.5.7.jar                         | None
                   |
| UCHIJA | mantle                               | 1.12-1.3.2.24
| Mantle-1.12-1.3.2.24 (2).jar                      | None
                   |
| UCHIJA | morph                                | 7.1.2
| Morph-1.12.2-7.1.2.jar                            | None
                   |
| UCHIJA | mysticalagriculture                  | 1.6.13
 | MysticalAgriculture-1.12-1.6.13.jar               | None
                     |
| UCHIJA | natura                               | 1.12.2-4.3.2.62
| natura-1.12.2-4.3.2.62.jar                        | None
                   |
| UCHIJA | harvestcraft                         | 1.12.2z
| Pam_s+HarvestCraft+1.12.2z.jar                    | None
                   |
| UCHIJA | roots                                | 0.104
| roots-2-0.104.jar                                 | None
                   |
| UCHIJA | twilightforest                       | 3.8.689
| twilightforest-1.12.2-3.8.689-universal.jar       | None
                   |
| UCHIJA | tconstruct                           | 1.12.2-2.10.1.87
 | TConstruct-1.12.2-2.10.1.87 (1).jar               | None
                     |
| UCHIJA | tinkertoolleveling                   | 1.12.2-1.0.5.DEV.30c7957
| TinkerToolLeveling-1.12.2-1.0.5 (1).jar           | None
                   |
| UCHIJA | vampirism                            | 1.5.0-alpha+09-26-15-05
| Vampirism-1.12.2-1.5.0-alpha+09-26-15-05.jar      | None
                   |
| UCHIJA | teamlapen-lib                        | 1.5.0-alpha+09-26-15-05
| Vampirism-1.12.2-1.5.0-alpha+09-26-15-05.jar      | None
                   |
| UCHIJA | walljump                             | 1.12.2-1.1.6
 | walljump-1.12.2-1.1.6.jar                         | None
                     |
| UCHIJA | xaerominimap                         | 1.15.4
 | Xaeros_Minimap_1.15.4_Forge_1.12.jar              | None
                     |

Loaded coremods (and transformers):
ObfuscatePlugin (obfuscate-0.2.5-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
AstralCore (astralsorcery-1.12.2-1.9.4 (1).jar)

llibrary (llibrary-core-1.0.8-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 411.63'
Renderer: 'GeForce GTX 1080/PCIe/SSE2'
Pulsar/natura loaded Pulses:
- NaturaCommons (Enabled/Forced)
- NaturaOverworld (Enabled/Not Forced)
- NaturaNether (Enabled/Not Forced)
- NaturaDecorative (Enabled/Not Forced)
- NaturaTools (Enabled/Not Forced)
- NaturaEntities (Enabled/Not Forced)
- NaturaOredict (Enabled/Forced)
- NaturaWorld (Enabled/Not Forced)

Pulsar/tconstruct loaded Pulses:
- TinkerCommons (Enabled/Forced)
- TinkerWorld (Enabled/Not Forced)
- TinkerTools (Enabled/Not Forced)
- TinkerHarvestTools (Enabled/Forced)
- TinkerMeleeWeapons (Enabled/Forced)
- TinkerRangedWeapons (Enabled/Forced)
- TinkerModifiers (Enabled/Forced)
- TinkerSmeltery (Enabled/Not Forced)
- TinkerGadgets (Enabled/Not Forced)
- TinkerOredict (Enabled/Forced)
- TinkerIntegration (Enabled/Forced)
- TinkerFluids (Enabled/Forced)
- TinkerMaterials (Enabled/Forced)
- TinkerModelRegister (Enabled/Forced)

Launched Version: 1.12.2-forge1.12.2-14.23.4.2750
LWJGL: 2.9.4
OpenGL: GeForce GTX 1080/PCIe/SSE2 GL version 4.6.0 NVIDIA 411.63, NVIDIA
Corporation
GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate
blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs:
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
OptiFine Version: OptiFine_1.12.2_HD_U_E2
OptiFine Build: 20180728-185429
Render Distance Chunks: 12
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: null
OpenGlVersion: 4.6.0 NVIDIA 411.63
OpenGlRenderer: GeForce GTX 1080/PCIe/SSE2
OpenGlVendor: NVIDIA Corporation
CpuCount: 8

**Comment by jordan11v** [comment]
If you would like our modpack and to try and figure it out on our server too. If that would help you can ask me and I'd gladly let you join to try and figure this out. I feel like whats conflicting shouldnt be because of other mods but hey I dont know how to make mods for minecraft. Java Yes modding no,

**Comment by maxanier** [comment]
I decided to rework the entire internal system. It is a little bit more complicated now but should be more robust.

I have seen you are already using a alpha version, you maybe you want to try out the new alpha version (uploading right now [here](https://minecraft.curseforge.com/projects/vampirism-become-a-vampire/files/2624030)), before I fix it for the stable (1.4) branch too.

**Comment by jordan11v** [comment]
solved by the alpha

**Comment by maxanier** [comment]
:+1:
