### ISSUE TITLE
Sunscreen Block Bug

### ISSUE THREAD

**Issue by fohlenetech** [TeamLapen/Vampirism#365]
- Minecraft: 1.12.2                   
- Forge:  14.24.4.2765                     
- Vampirism: 1.46                                            

When placing the suncreen beacon underneath a surface or above the surface it doesn't seem to work at all, sundamage is still applied to the player no matter what happens. - NOTE: Tried this in single player as well.

Just uh.. Place down a sunscreen block. And try to murder yourself in the sun with it down

I do have the block distance completely maxed out for anyone in the area of the block in order to help the server survive a little, plan to change it back to the default 32 shortly.

Update: I tried setting the block distance back to normal, having it on 32 does not cause the issue.

**Comment by jordan11v** [comment]
Try using the alpha that has worked for me. 1.5

**Comment by maxanier** [comment]
The value currently set as maximum is to high. I will fix that.
Try to use a distance of 45.000 or less.
