### ISSUE TITLE
[Feature Request] Config for bat form movement speed.

### ISSUE THREAD

**Issue by ProsperCraft** [TeamLapen/Vampirism#366]
Bat form flying vampires are far too fast for the server and cause lag, please add a config option to configure the speed they are able to move.

For now I have to disable bat form to keep the server playable for other players.

**Comment by maxanier** [comment]
As I said on the MC forum I have added this in the latest alpha (with 6a7a939a9d06fb45279fab43d0c1313161945e6e ). `BAT_FLIGHT_SPEED` in vampire action balance configuration.
