### ISSUE TITLE
Disable Halloween Dracula

### ISSUE THREAD

**Issue by Valawyn** [TeamLapen/Vampirism#369]
## Versions
- Minecraft: 1.12.2                   
- Forge: 14.23.4.2739                      
- Vampirism:  1.4.7                                           

## Issue Description
Halloween Dracula is an incredible nuisance, and has potentially world-destroying consequences.  If a player is afflicted by disease-like status effects, it can spread to every single other player in the server in seconds.  Things like Thaumorrhea and the Dread Plague (from Thaumcraft and Abyssalcraft, respectively) can lead to world-wide biome corruption.

## Reproduce Steps
Simple.  Get a disease (namely Dread Plague; it's the most egregious) and then simply exist at night.  The teleporting vampire will take care of the rest, and happily destroy your world.

## Additional Information

We've already had to revert to a backup, and are now using a command block on a timer (this is making chat very difficult to utilize at night for OPs) to keep the spawns subdued because there is no config option to disable this... "feature".

**Comment by maxanier** [comment]
Does the Halloween Dracula spawn appear all year around?
It is supposed to only appear on Halloween itself.

**Comment by maxanier** [comment]
Nevermind, it looks like I completely messed up things, and set the trigger to the 22.

I will add an option to disable this for next year. I did not know about such destructive effects like Dread Plague
