### ISSUE TITLE
Altar of infusion UI doesn't show up with a bare hand

### ISSUE THREAD

**Issue by jinkhya** [TeamLapen/Vampirism#370]
## Versions
- Minecraft: 1.12.2                  
- Forge: 2768                      
- Vampirism: 1.4.7                                            

## Issue Description
You can't open the Altar of Infusion UI with a bare hand, even with a valid structure. You can however open it with any item in hand (afaik)

## Reproduce Steps
Place the Altar of Infusion, Right click it with nothing in hand.

**Comment by jinkhya** [comment]
Actually now that I think of it it's probably because right click activates the ritual. Maybe shift right click to either open the UI or to activate it ?

**Comment by maxanier** [comment]
Yes, this is intentional. It is not the best solution. But we had some other (mod compat) issues with shift-right click, so this is the most reliable yet slightly confusing solution
