### ISSUE TITLE
Server-based crash with a strange trigger

### ISSUE THREAD

**Issue by Sunconure11** [TeamLapen/Vampirism#371]
## Versions
- Minecraft: 1.12.2
- Forge: 2772         
- Vampirism: 1.4.7                           

## Issue Description

A player managed to somehow trigger a crash with this mod upon entering my server. I have no clue what exactly caused it, other than him loading in.

## Reproduce Steps

Unsure, since it happened upon a player entering

## Additional Information

https://pastebin.com/7RamDx4e

**Comment by Sunconure11** [comment]
Said user reported a massive horde of vampires in their base.

**Comment by maxanier** [comment]
This is quite a strange issue, did the crash occur multiple times?

**Comment by maxanier** [comment]
Finally got around releasing a version with a potential fix. You can try it ou https://minecraft.curseforge.com/projects/vampirism-become-a-vampire/files/2643737
