### ISSUE TITLE
JER Crash

### ISSUE THREAD

**Issue by Shabnakh-adyr** [TeamLapen/Vampirism#372]
- Minecraft: 1.12.2                   
- Forge: 14.23.5.2772                
- Vampirism: 1.12.2-1.4.7                                             

Appears to be a conflict between Just Enough Resources profiling code and Vampirism's village helper.

Create new world, stand near a village, run /profile 100

[crash-2018-11-10_09.01.44-server.txt](https://github.com/TeamLapen/Vampirism/files/2568496/crash-2018-11-10_09.01.44-server.txt)

**Comment by maxanier** [comment]
Released 1.4.8 which should fix this issue
