### ISSUE TITLE
REQUEST: Vampire Portal in Superflat worlds

### ISSUE THREAD

**Issue by HyperMan19680** [TeamLapen/Vampirism#38]
I'd like for a way to create my own portal to Dracula's castle while in a default SuperFlat World. Cause they don't spawn structures.

**Comment by maxanier** [comment]
You should be able to cheat the portal block with "/give <username> vampirism:castlePortal"

**Comment by HyperMan19680** [comment]
Okay, I'll keep that in mind.

**Comment by HyperMan19680** [comment]
I'm having trouble finding a way home from Drac's castle once I beat him. Where is the portal home?

**Comment by maxanier** [comment]
As long as you traveled there via a (cheated) portal, there should be another portal outside the castle walls on a small platform. Just follow the path in front of the castle entrance. Did you find it?

**Comment by HyperMan19680** [comment]
I fear I did not. No worries though, I cheated up another portal by the gate, and I got home that way.

**Comment by maxanier** [comment]
That's really strange. Maybe you can try it again (in a flat world or in the normal way) and see if the problem occurs again. Maybe another mod is conflicting, what other mods do you have installed?
