### ISSUE TITLE
Bite Issue

### ISSUE THREAD

**Issue by legonorris201** [TeamLapen/Vampirism#383]
## Versions
- Minecraft: 1.12.2                   
- Forge:  forge1.12.2-14.23.5.2768                   
- Vampirism:  Vampirism-1.12.2-1.5.0-alpha+12-06-11-35                                           

## Issue Description
It is possible to bite mobs even as a hunter or normal player.

## Reproduce Steps
Go up to a mob and press the bite button. (Note: Other mods are included, but none that effect Vampirism.

**Comment by maxanier** [comment]
Thx for reporting
