### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by SpyroThyKing** [TeamLapen/Vampirism#385]
## Versions
- Minecraft: 1.12.2                   
- Forge: 14.23.5.2807                      
- Vampirism: 1.12.2-1.4.9                                            

## Issue Description 
Server Crashes shortly after any player joins.

## Reproduce Steps
Unsure.

## Additional Information
---- Minecraft Crash Report ----

WARNING: coremods are present:
  OTGCorePlugin (OTG-Core.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.4.10.6.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  EmoticonsCore (emoticons-0.2.1-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  llibrary (llibrary-core-1.0.10-1.12.2.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  CosmicLibFakeCoreMod (CosmicLib-1.12.2-0.4.0.BETA.jar)
  BlurPlugin (Blur-1.0.4-14.jar)
  TickrateChanger (TickrateChanger-1.0.14.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.3-core.jar)
  MMFMLCorePlugin (MultiMine-1.12.2.jar)
  SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  wings (wings-1.1.2-1.12.2.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  LoadingPlugin (Quark-r1.5-144.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 2/13/19 2:02 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:124)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at de.teamlapen.vampirism.entity.EntityVampirism.func_70636_d(EntityVampirism.java:148)
	at de.teamlapen.vampirism.entity.vampire.EntityVampireBase.func_70636_d(EntityVampireBase.java:174)
	at de.teamlapen.vampirism.entity.vampire.EntityBasicVampire.func_70636_d(EntityBasicVampire.java:132)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at de.teamlapen.vampirism.entity.EntityVampirism.func_70071_h_(EntityVampirism.java:153)
	at de.teamlapen.vampirism.entity.vampire.EntityBasicVampire.func_70071_h_(EntityBasicVampire.java:151)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:124)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at de.teamlapen.vampirism.entity.EntityVampirism.func_70636_d(EntityVampirism.java:148)
	at de.teamlapen.vampirism.entity.vampire.EntityVampireBase.func_70636_d(EntityVampireBase.java:174)
	at de.teamlapen.vampirism.entity.vampire.EntityBasicVampire.func_70636_d(EntityBasicVampire.java:132)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at de.teamlapen.vampirism.entity.EntityVampirism.func_70071_h_(EntityVampirism.java:153)
	at de.teamlapen.vampirism.entity.vampire.EntityBasicVampire.func_70071_h_(EntityBasicVampire.java:151)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: vampirism:vampire (de.teamlapen.vampirism.entity.vampire.EntityBasicVampire)
	Entity ID: 410
	Entity Name: Vampire
	Entity's Exact location: 373.51, 73.00, 1520.43
	Entity's Block location: World: (373,73,1520), Chunk: (at 5,4,0 in 23,95; contains blocks 368,0,1520 to 383,255,1535), Region: (0,2; contains chunks 0,64 to 31,95, blocks 0,0,1024 to 511,255,1535)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['Spyro_ThyKing'/1007, l='world', x=398.83, y=72.25, z=1544.69]]
	Chunk stats: ServerChunkCache: 441 Drop: 0
	Level seed: 3973598368399427675
	Level generator: ID 07 - OTG, ver 0. Features enabled: true
	Level generator options: OpenTerrainGenerator
	Level spawn location: World: (408,64,1533), Chunk: (at 8,4,13 in 25,95; contains blocks 400,0,1520 to 415,255,1535), Region: (0,2; contains chunks 0,64 to 31,95, blocks 0,0,1024 to 511,255,1535)
	Level time: 274602 game time, 51328 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 14156 (now: true), thunder time: 137339 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2407094440 bytes (2295 MB) / 3516399616 bytes (3353 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 2 total; -Xms512M -Xmx6G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2807 117 mods loaded, 115 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                           | Version                  | Source                                            | Signature                                |
	|:------ |:-------------------------------------------- |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                                    | 1.12.2                   | minecraft.jar                                     | None                                     |
	| LCHIJA | mcp                                          | 9.42                     | minecraft.jar                                     | None                                     |
	| LCHIJA | FML                                          | 8.0.99.99                | forge-1.12.2-14.23.5.2807-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                                        | 14.23.5.2807             | forge-1.12.2-14.23.5.2807-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | ivtoolkit                                    | 1.3.3-1.12               | minecraft.jar                                     | None                                     |
	| LCHIJA | otgcore                                      | 1.12.2 - v7              | minecraft.jar                                     | None                                     |
	| LCHIJA | com.elytradev.movingworld.common.asm.coremod |                          | minecraft.jar                                     | None                                     |
	| LCHIJA | obfuscate                                    | 0.2.6                    | minecraft.jar                                     | None                                     |
	| LCHIJA | srm-hooks                                    | 1.12.2-1.0.0             | minecraft.jar                                     | None                                     |
	| LCHIJA | dsurroundcore                                |                          | minecraft.jar                                     | None                                     |
	| LCHIJA | securitycraft                                | v1.8.10                  | [1.12.2] SecurityCraft v1.8.10.jar                | None                                     |
	| LCHIJA | actuallyadditions                            | 1.12.2-r144              | ActuallyAdditions-1.12.2-r144.jar                 | None                                     |
	| LCHIJA | advancedcombat                               | 1.1.2                    | advancedcombat-1.1.2-[1.12].jar                   | None                                     |
	| LCHIJA | jei                                          | 4.13.1.225               | jei_1.12.2-4.13.1.225.jar                         | None                                     |
	| LCHIJA | quark                                        | r1.5-144                 | Quark-r1.5-144.jar                                | None                                     |
	| LCHIJA | autoreglib                                   | 1.3-24                   | AutoRegLib-1.3-24.jar                             | None                                     |
	| LCHIJA | baubles                                      | 1.5.2                    | Baubles-1.12-1.5.2.jar                            | None                                     |
	| LCHIJA | betteranimalsplus                            | 4.1.0                    | betteranimalsplus-4.1.0.jar                       | None                                     |
	| LCHIJA | betterinvisibility                           | 1.0                      | betterinvisibility-1.12-1.0.jar                   | None                                     |
	| LCHIJA | bibliocraft                                  | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                 | None                                     |
	| LCHIJA | blockcraftery                                | 1.12.2-1.1.0             | blockcraftery-1.12.2-1.1.0.jar                    | None                                     |
	| LCHIJA | bloodmoon                                    | 1.5.3                    | Bloodmoon-MC1.12.2-1.5.3.jar                      | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | bookshelf                                    | 2.3.569                  | Bookshelf-1.12.2-2.3.569.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | chameleon                                    | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                          | None                                     |
	| LCHIJA | chisel                                       | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                      | None                                     |
	| LCHIJA | chunkpregenerator                            | 2.0                      | Chunk Pregenerator V1.12-2.0.jar                  | None                                     |
	| LCHIJA | codechickenlib                               | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | crafttweaker                                 | 4.1.13                   | CraftTweaker2-1.12-4.1.13.jar                     | None                                     |
	| LCHIJA | mantle                                       | 1.12-1.3.3.39            | Mantle-1.12-1.3.3.39.jar                          | None                                     |
	| LCHIJA | twilightforest                               | 3.8.689                  | twilightforest-1.12.2-3.8.689-universal.jar       | None                                     |
	| LCHIJA | tconstruct                                   | 1.12.2-2.12.0.115        | TConstruct-1.12.2-2.12.0.115.jar                  | None                                     |
	| LCHIJA | conarm                                       | 1.2.3                    | conarm-1.12.2-1.2.3.jar                           | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | coralreef                                    | 2.0                      | CoralReef-2.5-1.12.2.jar                          | None                                     |
	| LCHIJA | cosmiclib                                    | 0.4.0                    | CosmicLib-1.12.2-0.4.0.BETA.jar                   | d3974446c00f9f1d275edce305771eeddf30c658 |
	| LCHIJA | crafttweakerjei                              | 2.0.2                    | CraftTweaker2-1.12-4.1.13.jar                     | None                                     |
	| LCHIJA | customnpcs                                   | 1.12                     | CustomNPCs_1.12.2(30Jan19).jar                    | None                                     |
	| LCHIJA | customstartinggear                           | 1.2.0                    | CustomStartingGear-1.12-1.2.0.9-universal.jar     | None                                     |
	| LCHIJA | cxlibrary                                    | 1.6.1                    | cxlibrary-1.12.1-1.6.1.jar                        | None                                     |
	| LCHIJA | movingworld                                  | 1.12-6.342               | movingworld-1.12-6.342-full.jar                   | None                                     |
	| LCHIJA | davincisvessels                              | @DVESSELSVER@            | davincisvessels-1.12-6.340-full.jar               | None                                     |
	| LCHIJA | dynamicstealth                               | 1.12.2.032               | DynamicStealth-1.12.2.032.jar                     | None                                     |
	| LCHIJA | ebwizardry                                   | 4.1.4                    | Electroblob's Wizardry - 4.1.4 - MC 1.12.2.jar    | None                                     |
	| LCHIJA | emoticons                                    | 0.2.1                    | emoticons-0.2.1-1.12.2.jar                        | None                                     |
	| LCHIJA | eplus                                        | 5.0.174                  | EnchantingPlus-1.12.2-5.0.174.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | enderstorage                                 | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | enhancedarmaments                            | 1.3.15                   | EnhancedArmaments-1.3.15.jar                      | None                                     |
	| LCHIJA | enhancedvisuals                              | 1.0                      | EnhancedVisuals_v1.2.1_mc1.12.2.jar               | None                                     |
	| LCHIJA | exoticbirds                                  | 1.0                      | Exotic Birds 1.12.2-2.2.1.jar                     | None                                     |
	| LCHIJA | extraalchemy                                 | 0.3.8.6.1-release        | extraalchemy-0.3.8.6.1-release.jar                | None                                     |
	| LCHIJA | extrautils2                                  | 1.0                      | extrautils2-1.12-1.9.8.jar                        | None                                     |
	| LCHIJA | fastleafdecay                                | v14                      | FastLeafDecay-v14.jar                             | None                                     |
	| LCHIJA | forgelin                                     | 1.8.2                    | Forgelin-1.8.2.jar                                | None                                     |
	| LCHIJA | gottschcore                                  | 1.7.0                    | GottschCore-mc1.12.2-f14.23.5.2768-v1.7.0.jar     | None                                     |
	| LCHIJA | gravestone                                   | 1.10.1                   | gravestone-1.10.1.jar                             | None                                     |
	| LCHIJA | cgm                                          | 0.9.2                    | guns-0.9.2-1.12.2.jar                             | None                                     |
	| LCHIJA | ichunutil                                    | 7.1.4                    | iChunUtil-1.12.2-7.1.4.jar                        | None                                     |
	| LCHIJA | hats                                         | 7.0.0                    | Hats-1.12.2-7.0.2.jar                             | None                                     |
	| LCHIJA | howlingmoon                                  | 0.9                      | howlingmoon-1.12.2-0.9.jar                        | None                                     |
	| LCHIJA | waila                                        | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                       | None                                     |
	| LCHIJA | llibrary                                     | 1.7.17                   | llibrary-1.7.17-1.12.2.jar                        | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire                                   | 1.6.1                    | iceandfire-1.6.1-1.12.2.jar                       | None                                     |
	| LCHIJA | inventorytweaks                              | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                          | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironbackpacks                                | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                 | None                                     |
	| LCHIJA | ironchest                                    | 1.12.2-7.0.54.838        | ironchest-1.12.2-7.0.54.838.jar                   | None                                     |
	| LCHIJA | journeymap                                   | 1.12.2-5.5.3             | journeymap-1.12.2-5.5.3.jar                       | None                                     |
	| LCHIJA | jaff                                         | 1.7_for_1.12             | JustAFewFish-1.7_for_1.12.jar                     | None                                     |
	| LCHIJA | levelup2                                     | ${version}               | Level Up! 2-1.1.22-1.12.jar                       | None                                     |
	| LCHIJA | lootbags                                     | 2.5.7                    | LootBags-1.12.2-2.5.7.jar                         | None                                     |
	| LCHIJA | magiccraft                                   | 1.3                      | magiccraft-1.12.2-1.5.jar                         | None                                     |
	| LCHIJA | malisiscore                                  | 1.12.2-6.4.0             | malisiscore-1.12.2-6.4.0.jar                      | None                                     |
	| LCHIJA | malisisdoors                                 | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                     | None                                     |
	| LCHIJA | megaloot                                     | 0.2.30                   | megaloot-1.12.2-0.2.30.jar                        | None                                     |
	| LCHIJA | mtrm                                         | 1.2.2.30                 | MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar        | None                                     |
	| LCHIJA | mobamputation                                | 7.0.0                    | MobAmputation-1.12.2-7.0.0.jar                    | None                                     |
	| LCHIJA | morefurnaces                                 | 1.10.5                   | MoreFurnaces-1.12.2-1.10.6.jar                    | None                                     |
	| LCHIJA | mowziesmobs                                  | 1.5.2                    | mowziesmobs-1.5.2.jar                             | None                                     |
	| LCHIJA | shetiphiancore                               | 3.5.9                    | shetiphiancore-1.12.0-3.5.9.jar                   | None                                     |
	| LCHIJA | multibeds                                    | 1.4.4                    | multibeds-1.12.0-1.4.4.jar                        | None                                     |
	| LCHIJA | multimine                                    | 1.6.0                    | MultiMine-1.12.2.jar                              | None                                     |
	| LCHIJA | openterraingenerator                         | v6                       | OpenTerrainGenerator-1.12.2 - v6.jar              | e9f7847a78c5342af5b0a9e04e5abc0b554d69e0 |
	| LCHIJA | parry                                        | 1.0                      | parry-1.0-hotfix.jar                              | None                                     |
	| LCHIJA | portalgun                                    | 7.0.2                    | PortalGun-1.12.2-7.0.2.jar                        | None                                     |
	| LCHIJA | projecte                                     | 1.12-PE1.3.2h            | ProjectE-1.12-PE1.3.2h.jar                        | None                                     |
	| LCHIJA | reccomplex                                   | 1.4.7                    | RecurrentComplex-1.4.7.jar                        | None                                     |
	| LCHIJA | reforged                                     | 0.7.5                    | Reforged-0.7.5-1.12+.jar                          | None                                     |
	| LCHIJA | additionalstructures                         | 2.0.0                    | Rex's-Additional-Structures-1.12.x -(v.2.0.0).jar | None                                     |
	| LCHIJA | roguelike                                    | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar                | None                                     |
	| LCHIJA | subcommonlib                                 | 1.2.0.1                  | subcommonlib-sublib-1.12.2-1.2.0.4.jar            | None                                     |
	| LCHIJA | rpginventory                                 | 1.12.2                   | rpginventory-1.12-5.3.0.0.jar                     | None                                     |
	| LCHIJA | ruins                                        | 17.1                     | Ruins-1.12.2.jar                                  | None                                     |
	| LCHIJA | silentlib                                    | 3.0.9                    | SilentLib-1.12.2-3.0.9-159.jar                    | None                                     |
	| LCHIJA | scalinghealth                                | 1.3.31                   | ScalingHealth-1.12.2-1.3.31-132.jar               | None                                     |
	| LCHIJA | secretroomsmod                               | 5.6.4                    | secretroomsmod-1.12.2-5.6.4.jar                   | None                                     |
	| LCHIJA | t3s4ebw                                      | 1.0                      | SeedsForWizardry 1.0 For MC Forge 1.12.2.jar      | None                                     |
	| LCHIJA | tickratechanger                              | 1.0.14                   | TickrateChanger-1.0.14.jar                        | None                                     |
	| LCHIJA | sleepingoverhaul                             | 1.0.0                    | SleepingOverhaul-1.12.2-1.0.0.jar                 | d3974446c00f9f1d275edce305771eeddf30c658 |
	| LCHIJA | somanyenchantments                           | 0.3.0                    | SoManyEnchantments V0.3.1 (1.12.2).jar            | None                                     |
	| LCHIJA | sophisticatedwolves                          | 3.13.7                   | SophisticatedWolves-1.12.2-3.13.7.jar             | None                                     |
	| LCHIJA | spartanshields                               | 1.4.1                    | SpartanShields-1.12.2-1.4.1.jar                   | None                                     |
	| LCHIJA | swisscheese                                  | 1.1                      | SwissCheese-1.1-1.12.jar                          | None                                     |
	| LCHIJA | tinkertoolleveling                           | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar               | None                                     |
	| LCHIJA | toroquest                                    | 1.12.2-5.3               | toroquest-1.12.2-5.3.jar                          | None                                     |
	| LCHIJA | treasure2                                    | 1.3.0                    | Treasure2-mc1.12.2-f14.23.5.2768-v1.3.0.jar       | None                                     |
	| LCHIJA | vampirism                                    | 1.4.9                    | Vampirism-1.12.2-1.4.9.jar                        | None                                     |
	| LCHIJA | teamlapen-lib                                | 1.4.9                    | Vampirism-1.12.2-1.4.9.jar                        | None                                     |
	| LCHIJA | vehicle                                      | 0.35.0                   | vehicle-mod-0.35.0-1.12.2.jar                     | None                                     |
	| LCHIJA | waystones                                    | 4.0.67                   | Waystones_1.12.2-4.0.67.jar                       | None                                     |
	| LCHIJA | wearablebackpacks                            | 3.1.3                    | WearableBackpacks-1.12.2-3.1.3.jar                | None                                     |
	| LCHIJA | wings                                        | 1.1.2                    | wings-1.1.2-1.12.2.jar                            | None                                     |
	| LCHIJA | bauble_wings                                 | 1.0.0                    | wings-1.1.2-1.12.2.jar                            | None                                     |
	| LCHIJA | dsurround                                    | 3.4.10.6                 | DynamicSurroundings-1.12.2-3.4.10.6.jar           | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | thebetweenlands                              | 3.4.3                    | TheBetweenlands-3.4.3-universal.jar               | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| LCHIJA | trapexpansion                                | 1.0.0                    | trapexpansion-1.0.0.jar                           | None                                     |
	| LCHIJA | gravelores                                   | 1.8                      | gravelores-1.8.jar                                | None                                     |
	| LCHIJA | mysticallib                                  | 1.12.2-1.0.0             | mysticallib-1.12.2-1.0.0.jar                      | None                                     |
	| UD     | emoticons_core                               | 0.2.1                    | minecraft.jar                                     | None                                     |
	| UD     | mobends_wings                                | 1.0.0                    | wings-1.1.2-1.12.2.jar                            | None                                     |

	Loaded coremods (and transformers): 
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.OTGClassTransformer
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  cubex2.cxlibrary.CoreModTransformer
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.4.10.6.jar)
  org.blockartistry.DynSurround.asm.Transformer
ForgelinPlugin (Forgelin-1.8.2.jar)
  
EmoticonsCore (emoticons-0.2.1-1.12.2.jar)
  mchorse.emoticons.core.EmoCoreClassTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
llibrary (llibrary-core-1.0.10-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  shetiphian.asm.ClassTransformer
CosmicLibFakeCoreMod (CosmicLib-1.12.2-0.4.0.BETA.jar)
  
BlurPlugin (Blur-1.0.4-14.jar)
  com.tterrag.blur.BlurTransformer
TickrateChanger (TickrateChanger-1.0.14.jar)
  me.guichaguri.tickratechanger.TickrateTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.3-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
MMFMLCorePlugin (MultiMine-1.12.2.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  com.wynprice.secretroomsmod.core.SecretRoomsTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
wings (wings-1.1.2-1.12.2.jar)
  me.paulf.wings.server.asm.WingsRuntimePatcher
  me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
LoadingPlugin (Quark-r1.5-144.jar)
  vazkii.quark.base.asm.ClassTransformer
MovingWorldCore (movingworld-1.12-6.342-full.jar)
  
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['Spyro_ThyKing'/1007, l='world', x=398.83, y=72.25, z=1544.69]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by maxanier** [comment]
I am sorry, but I cannot find out what exactly is causing this.
There are just too many (core)mods installed. You could try to figure out which mod is causing this issue, but that will take a lot of effort

**Comment by theron61** [comment]
Saw this on my server as well:

**Comment by theron61** [comment]
Time: 3/12/19 1:49 AM
Description: Ticking entity

java.lang.IllegalArgumentException
        at net.minecraft.util.WeightedRandom.func_76273_a(SourceFile:18)
        at net.minecraft.util.WeightedRandom.func_76271_a(SourceFile:37)
        at de.teamlapen.vampirism.entity.action.EntityActionHandler.chooseNewAction(EntityActionHandler.java:148)
        at de.teamlapen.vampirism.entity.action.EntityActionHandler.updateHandler(EntityActionHandler.java:129)
        at de.teamlapen.vampirism.entity.action.EntityActionHandler.handle(EntityActionHandler.java:155)
        at de.teamlapen.vampirism.entity.EntityVampirism.func_70636_d(EntityVampirism.java:160)
        at de.teamlapen.vampirism.entity.vampire.EntityVampireBase.func_70636_d(EntityVampireBase.java:190)
        at de.teamlapen.vampirism.entity.vampire.EntityBasicVampire.func_70636_d(EntityBasicVampire.java:134)
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
        at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
        at de.teamlapen.vampirism.entity.EntityVampirism.func_70071_h_(EntityVampirism.java:166)
        at de.teamlapen.vampirism.entity.vampire.EntityBasicVampire.func_70071_h_(EntityBasicVampire.java:153)
        at net.minecraft.world.World.func_72866_a(World.java:1993)
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
        at net.minecraft.world.World.func_72870_g(World.java:1955)
        at net.minecraft.world.World.func_72939_s(World.java:1759)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
        at net.minecraft.util.WeightedRandom.func_76273_a(SourceFile:18)
        at net.minecraft.util.WeightedRandom.func_76271_a(SourceFile:37)
        at de.teamlapen.vampirism.entity.action.EntityActionHandler.chooseNewAction(EntityActionHandler.java:148)
        at de.teamlapen.vampirism.entity.action.EntityActionHandler.updateHandler(EntityActionHandler.java:129)
        at de.teamlapen.vampirism.entity.action.EntityActionHandler.handle(EntityActionHandler.java:155)
        at de.teamlapen.vampirism.entity.EntityVampirism.func_70636_d(EntityVampirism.java:160)
        at de.teamlapen.vampirism.entity.vampire.EntityVampireBase.func_70636_d(EntityVampireBase.java:190)
        at de.teamlapen.vampirism.entity.vampire.EntityBasicVampire.func_70636_d(EntityBasicVampire.java:134)
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
        at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
        at de.teamlapen.vampirism.entity.EntityVampirism.func_70071_h_(EntityVampirism.java:166)
        at de.teamlapen.vampirism.entity.vampire.EntityBasicVampire.func_70071_h_(EntityBasicVampire.java:153)
        at net.minecraft.world.World.func_72866_a(World.java:1993)
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
        at net.minecraft.world.World.func_72870_g(World.java:1955)

**Comment by maxanier** [comment]
This is a separate crash occurring only with the latest alpha. I have created a new issue for that
