### ISSUE TITLE
Crash when hit by vampire

### ISSUE THREAD

**Issue by antoniokf5** [TeamLapen/Vampirism#389]
## Versions
- Minecraft: 1.7.10 (Technic Modpack - Galinhas com Dentes)                 
- Forge: 10.13.4.1614      
- Vampirism: 0.7.9                               

## Issue Description
I try to get the status effect of vampirism, and it crashes my game. I'm on a server with various mods

## Reproduce Steps 
I try to get hit by a vampire
It crashes
[crash-2019-03-01_14.18.38-client.txt](https://github.com/TeamLapen/Vampirism/files/2920005/crash-2019-03-01_14.18.38-client.txt)

**Comment by maxanier** [comment]
Check the vampirism.cfg configuration, maybe some potion ID (maybe sanguinare) is set to a wrong value.

However, I am going to close this issue, since 1.7.10 is not supported anymore.
1.12 does not have potion IDs so something like this should be impossible there.

**Comment by maxanier** [comment]
You can also check if there is a config option to disable infaction by bite. I am not sure if that was already added in version 0.7.9
