### ISSUE TITLE
How do you cure someone when they become a vampire?

### ISSUE THREAD

**Issue by SiennaWesty** [TeamLapen/Vampirism#392]
## Versions
- Minecraft: 1.12.2        
- Forge:                      
- Vampirism:  Vampirism-1.12.2-1.4.9                                             

## Issue Description
How do you cure someone when they become a vampire?

## Additional Information
My friend is an idiot

**Comment by maxanier** [comment]
They have to do it themselves. Look for an altar in a village church building.
