### ISSUE TITLE
New hunter weapon: Vampire killer whip

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#400]
I have a model for the Vampire Killer whip for the Vampirism mod. Here's how the weapon will work, whenever you right-click with the whip in your hand, a ball and chain will extend and deal damage to any mob, then the ball and chain will retract back into the handle. This will happen rather quickly, and it will do massive amounts of damage (at least 60 damage) to undead mobs, like vampires, zombies, and skeletons. I used a program called Blockbench, to make these. keep up the good work.

PS. I'm unable to attach the models and textures to this, so email me so i can send the models.
It's **_fallouttoonlink@gmail.com_**

_Originally posted by @TheDoomSlayer in https://github.com/TeamLapen/Vampirism/pull/386#issuecomment-472942192_

https://gist.github.com/TheDoomSlayer/501b89273798b93960162ebc525598a4

**Comment by maxanier** [comment]
@TheDoomSlayer
Thank you for the model. (In the future, please do not hijack other threads though ;) )
How is the chain supposed to be attached to the cross/handle, right at the crossing point?

However, I am not sure if I will find the time to create an awesome animation for this.
If you have textures for this, you can upload them here: http://cloud.maxgb.de/s/z2HWkeS9xcobEHw

**Comment by TheDoomSlayer** [comment]
Yes. Sorry about hijacking your thread. Wasn't able to contact you.

**Comment by TheDoomSlayer** [comment]
![Combat_cross](https://user-images.githubusercontent.com/39161614/54560208-cd002300-498f-11e9-8ebd-153a8fafd5de.png)

i have here a resource pic for the whip

**Comment by TheDoomSlayer** [comment]
https://www.youtube.com/watch?v=uQL5aJetsnA   
 and here is a video of how the whip should work. the attack range should be about 5 to 6 blocks, making it the probably the only ranged melee weapon. i also forgot, the damage the whip should dish out to non-vampire and non-undead mobs, which includes cows, pigs, creepers, etc., should the same as a diamond sword.

**Comment by TheDoomSlayer** [comment]
I came up with some other stuff for the mod. but i'm going to wait for you to finish with this weapon before i can share you my other ideas and models.

**Comment by TheDoomSlayer** [comment]
Holy Hand Grenade- a thrown weapon that will explode with a blast of holy light, that is able to harm any hostile mobs
https://gist.github.com/TheDoomSlayer/fa6e4bf48018cf0d2f5f3fb78f257440

Alucard's Sword- the weapon that belongs to the son of Dracula, does 70 attack damage to any mob.
https://gist.github.com/TheDoomSlayer/a75b6aa0eb155104a198d41b3b9835a4

Boomerang Cross- a thrown holy weapon that returns to your hand and to holy damage to the undead and vampires.
https://gist.github.com/TheDoomSlayer/0126aba8e8d0af5793a4aaab181ff8b8

Special attack for vampire hunters: Grand Cross- a attack where a hunter creates a immense cross of pure light with a large damage radius that can harm any undead mob or vampire that is caught in the radius, the most powerful attack in the hunter's moveset.
https://gist.github.com/TheDoomSlayer/0126aba8e8d0af5793a4aaab181ff8b8

![DOS_Grand_Cross](https://user-images.githubusercontent.com/39161614/54923178-b732b680-4ed7-11e9-8507-16d6e5273a27.gif)

![boomerang cross](https://user-images.githubusercontent.com/39161614/54923210-c6196900-4ed7-11e9-8197-a09916e10d37.jpg)

**Comment by maxanier** [comment]
I still can't tell you if and when these weapons will be implemented in the mod.
I will have to see how well they can be implemented in Minecraft.

However, I can't use the obj models, so please submit any models as .json

**Comment by TheDoomSlayer** [comment]
I have to remake the models. But they'll be done before you'll know it.

**Comment by TheDoomSlayer** [comment]
also, the cross boomerang is going to be a pain in the ass to remake.

**Comment by TheDoomSlayer** [comment]
use the picture of the whip and the picture of Simon Belmont using the boomerang cross as a resource pic when applying the textures.

**Comment by TheDoomSlayer** [comment]
Please add Vampire Killer
