### ISSUE TITLE
Undead Mobs Ignore Vampire Players

### ISSUE THREAD

**Issue by PendragonII** [TeamLapen/Vampirism#402]
Feature Request: Undead mobs such as Zombies and Skeletons ignore Vampire Players.
This makes logical sense because Vampires are undead creatures which is what Zombies and Skeletons are also.

**Comment by Webdragon444** [comment]
I agree, but it may be a bit overpowered. I think that this could be added to the powers you get when you level up. to balance it out, maybe villagers and other passive mobs would flee from you, and maybe get a dark glow effect to other players. this would Ideally be a 5-10 minute effect, with a cool down of 10-15. dunno how hard this would be to implement, but a fun Idea nonetheless.

**Comment by maxanier** [comment]
I could agree with making Zombies stop attacking vampires. Skeletons are just very mean so they should continue attacking vampires (we want to keep at least some of the vanilla feeling).

@Webdragon444 that sounds cool, but is likely to cause issues with other mods' monsters, so it could only work for vanilla creatures causing inconsistent behavior if playing with multiple mods
