### ISSUE TITLE
Request: Better axe model

### ISSUE THREAD

**Issue by gravysamich** [TeamLapen/Vampirism#408]
this is honestly my only issue with this mod. the axes just don't look good. the vampire hunters i see holding them just look like they are holding up a protest sign. 

i love this mod a lot, but this one weapon model really stands out as being of lower quality than the rest of the mod.

**Comment by maxanier** [comment]
If someone submits a better model, I will gladly replace the old one.
Maybe you can try your look (using blockbench or cubic).
Or maybe you can convince @TheDoomSlayer to create a new axe model

**Comment by TheDoomSlayer** [comment]
I made a new axe model. It looks kind of like a wood cutting axe. Maybe you can do a "HERE'S JOHNNY!" with it?

**Comment by maxanier** [comment]
Thank you, looks good. However, due to the "colliding" cubes it might glitch a little bit ingame. I will have to try it out

**Comment by TheDoomSlayer** [comment]
Ok. And you're welcome. I'm happy to help.
