### ISSUE TITLE
Crash when generating vampire controlled villages using MCA

### ISSUE THREAD

**Issue by Webdragon444** [TeamLapen/Vampirism#409]
## Versions
- Minecraft: 1.12.2                   
- Forge: Forge 14.23.5.2815                       
- Vampirism: Vampirism-1.12.2-1.5.0-beta.1                                             

## Time: 2019-04-21 16:46:34 PDT
Description: Ticking block entity

java.lang.NoSuchMethodError: de.teamlapen.vampirism.api.event.VampirismVillageEvent$SpawnNewVillager.isWillBeAggressive()Z
    at de.teamlapen.vampirism_integrations.mca.EventHandlerMCA.onSpawnNewVillager(EventHandlerMCA.java:33)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1047_EventHandlerMCA_onSpawnNewVillager_SpawnNewVillager.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at de.teamlapen.vampirism.tileentity.TileTotem.update(TileTotem.java:626)
    at net.minecraft.world.World.redirect$tileEntityUpdate$zbc000(World.java:4131)
    at net.minecraft.world.World.updateEntities(World.java:1835)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)

-- Block entity being ticked --
  Name: vampirism:totem // de.teamlapen.vampirism.tileentity.TileTotem
  Block type: ID #1352 (tile.vampirism.totem_top // de.teamlapen.vampirism.blocks.BlockTotemTop // vampirism:totem_top)
  Block data value: 0 / 0x0 / 0b0000
  Block location: World: (-729,69,986), Chunk: (at 7,4,10 in -46,61; contains blocks -736,0,976 to -721,255,991), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
  Actual block type: ID #1352 (tile.vampirism.totem_top // de.teamlapen.vampirism.blocks.BlockTotemTop // vampirism:totem_top)
  Actual block data value: 0 / 0x0 / 0b0000
  Block Entity NBT: {capturing:"",x:-729,y:69,z:986,id:"vampirism:totem",controlling:"Vampire"}

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 3229657128 bytes (3080 MB) / 7751073792 bytes (7392 MB) up to 8589934592 bytes (8192 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
  FML: MCP 9.42 Powered by Forge 14.23.5.2815 Optifine OptiFine_1.12.2_HD_U_E3 64 mods loaded, 63 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                     | Version                | Source                                             | Signature                                |
       |:------ |:---------------------- |:---------------------- |:-------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft              | 1.12.2                 | minecraft.jar                                      | None                                     |
       | LCHIJA | mcp                    | 9.42                   | minecraft.jar                                      | None                                     |
       | LCHIJA | FML                    | 8.0.99.99              | forge-1.12.2-14.23.5.2815.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                  | 14.23.5.2815           | forge-1.12.2-14.23.5.2815.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | OldModelLoader         | 8.1.4.132              | minecraft.jar                                      | None                                     |
       | LCHIJA | jei                    | 4.15.0.268             | jei_1.12.2-4.15.0.268.jar                          | None                                     |
       | LCHIJA | abyssalcraft           | 1.9.6                  | AbyssalCraft-1.12.2-1.9.6.jar                      | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | LCHIJA | acintegration          | 1.8.1                  | AbyssalCraft+Integration-1.12.2-1.8.1.jar          | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | LCHIJA | advancedcombat         | 1.1.2                  | advancedcombat-1.1.2-[1.12].jar                    | None                                     |
       | LCHIJA | aether_legacy          | 1.12.2-v1.4.3          | aether_legacy-1.12.2-v1.4.3.jar                    | None                                     |
       | LCHIJA | biomesoplenty          | 7.0.1.2419             | BiomesOPlenty-1.12.2-7.0.1.2419-universal.jar      | None                                     |
       | LCHIJA | craftstudioapi         | 1.0.0                  | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
       | LCHIJA | ctm                    | MC1.12.2-0.3.3.22      | CTM-MC1.12.2-0.3.3.22.jar                          | None                                     |
       | LCHIJA | twilightforest         | 3.8.689                | twilightforest-1.12.2-3.8.689-universal.jar        | None                                     |
       | LCHIJA | animania               | 1.6.2                  | animania-1.12.2-1.6.2.jar                          | None                                     |
       | LCHIJA | quark                  | r1.5-146               | Quark-r1.5-146.jar                                 | None                                     |
       | LCHIJA | autoreglib             | 1.3-26                 | AutoRegLib-1.3-26.jar                              | None                                     |
       | LCHIJA | backpacks16840         | 3.5.5                  | backpacks+1.12.2+-+3.5.5.jar                       | None                                     |
       | LCHIJA | baubles                | 1.5.2                  | Baubles-1.12-1.5.2.jar                             | None                                     |
       | LCHIJA | patchouli              | 1.0-18                 | Patchouli-1.0-18.jar                               | None                                     |
       | LCHIJA | llibrary               | 1.7.18                 | llibrary-1.7.18-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | bewitchment            | @VERSION@              | Bewitchment-1.12.2-0.0.19.44-indev.jar             | None                                     |
       | LCHIJA | byg                    | 1.6.1                  | BiomesYouGo_1.6.1.jar                              | None                                     |
       | LCHIJA | bloodmoon              | 1.5.3                  | Bloodmoon-MC1.12.2-1.5.3.jar                       | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | carryon                | 1.12.1                 | Carry-On-Mod-1.12.2.jar                            | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
       | LCHIJA | cavern                 | 2.1.9                  | Cavern_1.12.2-v2.1.9.jar                           | b78e30ad27c82f3e348f76edf497058678207299 |
       | LCHIJA | chisel                 | MC1.12.2-0.2.1.35      | Chisel-MC1.12.2-0.2.1.35.jar                       | None                                     |
       | LCHIJA | dimdoors               | 3.0.9+287              | DimensionalDoors-3.0.9-287.jar                     | None                                     |
       | LCHIJA | ding                   | 1.0.1                  | Ding-1.12.1-1.0.1.jar                              | None                                     |
       | LCHIJA | dragonmounts           | 1.12.2-1.5.8           | DragonMounts-1.12.2-1.5.8(HOTFIX).jar              | None                                     |
       | LCHIJA | net.blacklab.lib       | 6.1.5.8                | EBlib-1.12.2.jar                                   | None                                     |
       | LCHIJA | ebwizardry             | 4.1.4                  | Electroblob's+Wizardry+-+4.1.4+-+MC+1.12.2.jar     | None                                     |
       | LCHIJA | extra_spells           | 1.0.3                  | ExtraSpells-1.12.2-1.0.3.jar                       | None                                     |
       | LCHIJA | friendlyfire           | 1.5.10                 | FriendlyFire-1.12.2-1.5.10.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | generaldisasters       | 1.0                    | General-Disasters-Mod-1.12.2.zip                   | None                                     |
       | LCHIJA | guideapi               | 1.12-2.1.8-63          | Guide-API-1.12-2.1.8-63.jar                        | None                                     |
       | LCHIJA | howlingmoon            | 0.9                    | howlingmoon-1.12.2-0.9.jar                         | None                                     |
       | LCHIJA | iceandfire             | 1.7.1                  | iceandfire-1.7.1-1.12.2.jar                        | None                                     |
       | LCHIJA | ichunutil              | 7.2.1                  | iChunUtil-1.12.2-7.2.1.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | keywizard              | 1.12.2-1.5.5           | keywizard-1.12.2-1.5.5.jar                         | None                                     |
       | LCHIJA | lmreengaged            | 8.1.4.132              | LittleMaidMob-Mod-1.12.2.jar                       | None                                     |
       | LCHIJA | radixcore              | 1.12.x-2.2.1           | RadixCore-1.12.x-2.2.1-universal.jar               | None                                     |
       | LCHIJA | mca                    | 1.12.2-5.3.1           | MCA-1.12.x-5.3.1-universal.jar                     | None                                     |
       | LCHIJA | mowziesmobs            | 1.5.3                  | mowziesmobs-1.5.3.jar                              | None                                     |
       | LCHIJA | naturescompass         | 1.5.1                  | NaturesCompass-1.12.2-1.5.1.jar                    | None                                     |
       | LCHIJA | placeableitems         | 3.3                    | placeableitems-3.3.jar                             | None                                     |
       | LCHIJA | randomloot             | 1.3                    | RandomLoot-1.4.1.jar                               | None                                     |
       | LCHIJA | randomworldname        | 1.1                    | randomworldname-1.1.jar                            | None                                     |
       | LCHIJA | roguelike              | 1.8.0                  | RoguelikeDungeons-1.12.2-1.8.0.jar                 | None                                     |
       | LCHIJA | roots                  | 0.104                  | roots-2-0.104.jar                                  | None                                     |
       | LCHIJA | sync                   | 7.1.0                  | Sync-1.12.2-7.1.0.jar                              | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | tammodized             | 0.15.6                 | TamModized-1.12.2-0.15.6.jar                       | None                                     |
       | LCHIJA | theoneprobe            | 1.4.28                 | theoneprobe-1.12-1.4.28.jar                        | None                                     |
       | LCHIJA | tombstone              | 3.3.4                  | tombstone-3.3.4-1.12.jar                           | None                                     |
       | LCHIJA | vampirism              | 1.5.0-beta.1           | Vampirism-1.12.2-1.5.0-beta.1.jar                  | None                                     |
       | LCHIJA | teamlapen-lib          | 1.5.0-beta.1           | Vampirism-1.12.2-1.5.0-beta.1.jar                  | None                                     |
       | LCHIJA | vampirism_integrations | vampirism_integrations | VampirismIntegrations-1.12.2-1.0.0.jar             | None                                     |
       | LCHIJA | vanillafix             | 1.0.10-SNAPSHOT        | VanillaFix-1.0.10-99.jar                           | None                                     |
       | LCHIJA | voidcraft              | 0.26.10                | VoidCraft-1.12-0.26.10.jar                         | None                                     |
       | LCHIJA | waystones              | 4.0.67                 | Waystones_1.12.2-4.0.67.jar                        | None                                     |
       | LCHIJA | wings                  | 1.1.4                  | Wings-Mod-1.12.2.jar                               | None                                     |
       | LCHIJA | bauble_wings           | 1.0.0                  | Wings-Mod-1.12.2.jar                               | None                                     |
       | LCHIJA | xaerominimap           | 1.16.2                 | Xaeros_Minimap_1.16.2_Forge_1.12.jar               | None                                     |
       | UD     | mobends_wings          | 1.0.0                  | Wings-Mod-1.12.2.jar                               | None                                     |
  Loaded coremods (and transformers): llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      LMRECoremod (LittleMaidMob-Mod-1.12.2.jar)
                                        net.blacklab.lmr.util.coremod.Transformer
                                      LoadingPlugin (Quark-r1.5-146.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      BCModPlugin (backpacks+1.12.2+-+3.5.5.jar)
                                        brad16840.core.ClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      wings (Wings-Mod-1.12.2.jar)
                                        me.paulf.wings.server.asm.WingsRuntimePatcher
                                        me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
                                        lumien.bloodmoon.asm.ClassTransformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  Suspected Mods: VampirismIntegrations (vampirism_integrations), TeamLapen Library (teamlapen-lib), Vampirism (vampirism)
  Profiler Position: N/A (disabled)
  Player Count: 1 / 8; [EntityPlayerMP['Webdragon444'/40, l='Vault of Sloth', x=-727.88, y=69.25, z=988.80]]

**Comment by maxanier** [comment]
Please update vampirism_integrations to the latest beta and try again

**Comment by Webdragon444** [comment]
ah, thanks, at the time I updated vampirism, it didn't seem that there was a new integrations out. issue is fixed now!
