### ISSUE TITLE
New VampirismVillage]Stats:  Doors: 1, Aggro leak

### ISSUE THREAD

**Issue by McKitten** [TeamLapen/Vampirism#410]
## Versions
- Minecraft:  1.12.2                  
- Forge: 2815                      
- Vampirism: 1.4.9                                            

Massive leak probably assisted by another mods' interaction as neither main or integration has been updated since the end of Jan and HDD space was only just noticed in the last week (172mb/day in the debug.log) however it is cloning what looks like an old nemesis with :
[00:13:15] [Server thread/DEBUG] [vampirism]: [VampirismVillage]Stats:  Doors: 1, Aggro: 0, v: 0, vh: 0, h: 0. Pos BlockPos{x=0, y=0, z=0}
etc being spammed.

## Reproduce Steps
My brief (2hours-ish) attempt at isolating/reproducing this outside the main server world (currently 11 players) to any of the mods I have updated in the last week failed.

## Additional Information
Full Modlist @ https://drive.google.com/open?id=1p8W2n3HqLtdMJ75qMjP2QlKeWSS0ncUy 
astralsorcery-1.12.2-1.10.17 | Ceramics-1.12-1.3.7 | conarm-1.12.2-1.2.3.4 | Cyclic-1.12.2-1.19.6 | EnderCore-1.12.2-0.5.57 | FTBLib-5.4.1.96 | FTBUtilities-5.4.0.94 | millenaire-1.12.2-7.2.0 | Millénaire Extended-1.12.2-0.2.2 | Psi-r1.1-74 | tinkersjei-1.2 | Totemic-1.12.2-0.11.5 | YABBA-1.1.2.48 being the files updated in the last week.

## Meep?
I realize this can be viewed as me dumping my server issues on you since it hasn't been fully diagnosed, I wouldn't have thought to bother except I know this can happen to someone else. All I can do is say thank you in advance for your hard work.

**Comment by maxanier** [comment]
Sorry for not answering quicker.
Unfortunately, the issue is quite difficult to debug and the village system has been reworked in Vampirism 1.5, therefore I won't try to fix it for 1.4.9.
You could update to 1.5-beta if the issue  still exists
