### ISSUE TITLE
Vampirism Infusion Books

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#412]
Suggested by BronzeShadow

These "books" could be used to unlock additional "hidden" skills once at max level.
These books should be rare. They could be sold by villagers, generated in loot chests, rewarded for achievements or dropped  by advanced creatures.

Hidden skills may include: Improved disguise, improved blood vision, improved what ever?

If they just include we probably don't have to change a lot about the skills GUI, otherwise we probably need to integrate skills that are not part of the skill tree.

**Comment by Dover2** [comment]
idea: passive regen buff for vampires

when you get this skill, you have a constant level of regen active as long as you arent starving, and your active regen skill will also go up a level. (say that the active regen gives regen 2 without the regen buff, and with the regen buff, active regen gives regen 3)
this might be OP so there might have to be a downside or just that it only works when you have full/near full blood bar

**Comment by maxanier** [comment]
Instead of special books we now have vampire accessories that can upgrade/sidegrade skills
