### ISSUE TITLE
[Feature] obsidian armor change

### ISSUE THREAD

**Issue by Nashor-Senpai** [TeamLapen/Vampirism#415]
Could you perhaps change the poison in obsidian armor  for vampires from poison II to garlic poison or any other kind of damaging debuff? there are several mods like grimoire of gaia or baubles that allows you to farm poison immune trinkets, that would allow vampires to wear obsidian armor and straight giving them a fair advantage.
Also, it would be great if there were a way to craft special armor as its suposed to give hunters an advantage against vampires but if you cant even find them and vampires can equip them with poison immunity it doesnt feel that rewarding.

**Comment by Cheaterpaul** [comment]
#422
