### ISSUE TITLE
Village faction reset when reloaded[Bug]

### ISSUE THREAD

**Issue by Webdragon444** [TeamLapen/Vampirism#417]
## Versions
- Minecraft: 1.12.2                    
- Forge: Forge 14.23.5.2815                      
- Vampirism: Vampirism-1.12.2-1.5.0-beta.1, VampirismIntegrations-1.12.2-1.1.0-beta.1
--

                                             

## Issue Description
Neutral village switched to vampire does not stay vampire controlled, but switches to neutral without prompt every time the chunk is reloaded. additionally, it occasionally says that no village can be found, even though it is a naturally generated village with doors and villagers.

## Reproduce Steps
turn a neutral village to vampire, then log out and back in.

## Additional Information
Am using vampirism, vampirismintegrations, MCA, and several unrelated mods

**Comment by MiruNyashka** [comment]
Same here. Without Vampirism integrations, only unrelated mods like Mapwriter, Hwyla and JEI. Once You leave a village for sometime it turnes into neutral or even hunters' village.

**Comment by TheDoomSlayer** [comment]
Hi!

**Comment by maxanier** [comment]
Unfortunately, I am not able to reproduce this issue.

Does this happen on a server or in SP.
With neutral village do you mean without village totem or with a totem, just not with a faction?

**Comment by Webdragon444** [comment]
Singleplayer, and it happens with a village totem. The village is captured by me as a vampire, then switches to neutral when I leave, regardless of original faction. it happens irregularly, but enough that its an issue, as we have to re-capture a village every time it happens. an alternative method of reproducing this is to leave the village far enough that it is unloaded, then return. thanks for your time :)

**Comment by princessbinas** [comment]
I am not sure how ideal this is, but I think I stumbled upon a solution.
I have a mod that I like using for when I want to go exploring but I also want things such as crops to continue growing for breeding. The mod is called Chicken Chunks on Cursed/Twitch. What it does is it keeps any chunks within the mod's chunk loader block range loaded. So far, it has kept my neutral-turned-vampire controlled village from reverting back to neutral. I know this because prior to putting down the chunk loader, I kept losing control of the village. 

Like I said, I am not sure how ideal this solution is, but it is a start if you don't want to keep fighting for control.

**Comment by Webdragon444** [comment]
Thanks, I will definitely try that for now! Hope it gets fixed soon, though.

**Comment by princessbinas** [comment]
I will say right now it only works for if you are playing hours on end (more than an hour) and if you are playing with dimensional mods like Twilight Forest or going into vanilla dimensions like the Nether. It doesn't prevent village faction reset upon relaunching/reloading the game/world. So it is not a 100% fix. It will just keep you from losing the village while you play.

**Comment by maxanier** [comment]
Please checkout the latest beta. I have added a couple failsafes which should hopefully solve this issue.
Since I still cannot reproduce it, I cannot verify it myself

**Comment by Webdragon444** [comment]
It seems to be working for me now, thanks!
