### ISSUE TITLE
[Bug] [VillageGen]The village map generator was overwritten by another mod. There might be a problem!   The new generator class is null

### ISSUE THREAD

**Issue by Mercurious1** [TeamLapen/Vampirism#419]
## Versions
- Minecraft:         1.12.2           
- Forge:       14.23.5.2836                
- Vampirism:      
Vampirism-1.12.2-1.5.0                                       

## Issue Description
Not sure if anything is wrong other than that I get that error 
[Server thread/WARN] [vampirism]: [VillageGen]The village map generator was overwritten by another mod. There might be a problem!   The new generator class is null

## Reproduce Steps
Have 450 mods.

**Comment by maxanier** [comment]
As long as you can find villages in your world everything should be fine.
Nothing game breaking should happen, some of Vampirism's features might not work perfectly, but with that many mods its probably impossible to get them running along nicely

**Comment by Mercurious1** [comment]
Suprisingly nicer than you'd expect but yea its impossible to find 2 mods conflicting with each other - at best, just one of the 2 ;P I do find villages though so a-ok :)
