### ISSUE TITLE
Add garlic to stop vampire from spawning

### ISSUE THREAD

**Issue by NassiC** [TeamLapen/Vampirism#42]
I have a problem with vampires spawning no matter what i do.
I have build my base in Extra Utility's Last Millennium. I have light every where, but they still spawned, so i made a magnum torch, but they still spawn.
I even had one spawn on glass (glass from ztones)

Im using version: 0.7.4.2
Extra Utillities is 1.2.11
Forge is 10.13.4.1492

Let me know if you need more infomation, then i will try do help as best i can.
Great mod btw. :D

**Comment by maxanier** [comment]
You unfortunatly cannot stop them from spawning with torches, only halfslabs might help.
I didn't really think about this until now; in later version there probably will be garlic to prevent them from spawning

**Comment by maxanier** [comment]
Implemented in 518b13a90a79d1943a053bedaf030468e64ec9b7. Available as of version 0.7.8
