### ISSUE TITLE
[TODO 1.14] Recipes

### ISSUE THREAD

**Issue by Cheaterpaul** [TeamLapen/Vampirism#421]
working recipes for 1.14 (https://github.com/TeamLapen/Vampirism/pull/462/commits/8324f8a941561ee3272b5c35a2f50778c2e7cb9c, https://github.com/TeamLapen/Vampirism/pull/462/commits/bea1b61084b4b14a6d021ffc0a4d51a6a1080978)

Todo 1.14:
- using groups
- test all recipes when forge fluid system is there

**Comment by TheDoomSlayer** [comment]
Vampire Killer!

**Comment by maxanier** [comment]
@TheDoomSlayer I am sorry that we did not find the time to add your items, but please stop hijacking other issues or posting meaningless comments

**Comment by TheDoomSlayer** [comment]
Ok

**Comment by maxanier** [comment]
Ping @Cheaterpaul is there still something to do here?

**Comment by Cheaterpaul** [comment]
i haven't tested them all, but the weapontable & alchemical cauldron recipes work
