### ISSUE TITLE
[Bug] Forge Version

### ISSUE THREAD

**Issue by Cheaterpaul** [TeamLapen/Vampirism#434]
Minecraft: 1.12.2
Forge Version: 14.23.5.2836
Vampirism: 1.5.0-beta.1

The converted villager trades dosent work as intented with this forge version.  (only tried with 14.23.5.2836 & 14.23.5.2768(vampirisms default version)) #428

**Comment by maxanier** [comment]
Closing this in favor of #428 , because it is much more descriptive and specific
