### ISSUE TITLE
[Bug] Hunter Weapon Table Rendering

### ISSUE THREAD

**Issue by lunofe** [TeamLapen/Vampirism#437]
## Versions
- Minecraft: 1.12.2
- Forge: 14.23.5.2836
- Vampirism: 1.5.0-beta.3

## Issue Description
The 2D items on the hunter research table are having non-transparent backgrounds.
![2019-06-01_14 07 30](https://user-images.githubusercontent.com/42828197/58749320-fa377a00-8484-11e9-87ec-b3c3e117df15.png)
![2019-06-01_14 11 31](https://user-images.githubusercontent.com/42828197/58749321-fa377a00-8484-11e9-845a-6636862feaff.png)

## Reproduce Steps
- Use versions from above and place a hunter research table
- Singleplayer/Server, etc. doesn't change anything.

**Comment by ThugPug43** [comment]
This seems like the right place to put this, the same happens with Alchemical fire
![2019-06-05_15 53 06](https://user-images.githubusercontent.com/31190716/58989902-69c1a800-87aa-11e9-8a73-67cdb52f5791.png)

**Comment by maxanier** [comment]
Closed in 988bd51e62cd7d7049eab72c3490fdb19aaa82a4. Mentioned the wrong issue in commit message :see_no_evil:
