### ISSUE TITLE
Client crash when joining Server

### ISSUE THREAD

**Issue by Solidflip** [TeamLapen/Vampirism#44]
Hello,

I recently tried to add this mod to a pack and got a crash when i tried to join the server. I took the mod out and the crash vanished and i was able to join the server no problem. 

I really liked the look of the mod so wanted to report this here to see if you have a fix (this is the server log, the client didnt crash just timed out or gave an internal server exception)

http://pastebin.com/gwqKbg7a

**Comment by maxanier** [comment]
Thanks for the report. I will fix this issue next week, until now please use version 0.7.4 of Vampirism http://minecraft.curseforge.com/mc-mods/233029-vampirism-become-a-vampire/files/2253347
