### ISSUE TITLE
[Bug] Crash on Startup.

### ISSUE THREAD

**Issue by TarnishedSoul0** [TeamLapen/Vampirism#444]
## Versions
- Minecraft: 1.12.2                    
- Forge: Forge-1.12.2-14.23.5.2838                       
- Vampirism: Vampirism-1.12.2-1.5.0-beta.3                                            

## Issue Description
I was setting up my forge server for my friends, but I kept getting multiple crashes on start-up, even after removing some mods. Upon looking at the crash report, I see that it says Vampirism at the top. Removing Vampirism fixes the problem.

## Reproduce Steps
Start your server with Vampirism. Crash upon startup.

## Additional Information
[crash-2019-06-10_22.50.13-server.txt](https://github.com/TeamLapen/Vampirism/files/3274693/crash-2019-06-10_22.50.13-server.txt)

**Comment by maxanier** [comment]
You are actually using "beta.2" instead of the "beta.3" you mentioned. Pls, update to 3 and this issue should be resolved

**Comment by TarnishedSoul0** [comment]
Ahh, okay. Sorry about that. Minor oversight on my part.
