### ISSUE TITLE
[Feature]More Class levels please i maxed out in 4 days

### ISSUE THREAD

**Issue by Octoham** [TeamLapen/Vampirism#446]
## What would you like to have changed or added to Vampirism
More class levels (i maxed out in 4 days)or a new level per 2 months

## Does this make the mod experience more balanced?
it will give something players could always go for

## Can you provide additional resources (etc. textures or models)
no

**Comment by lunofe** [comment]
I think both vampires and hunter are pretty much maxed out right now. The last skills (e.g. for vampires the teleport/freeze/invisibility) seem like they're meant to be the highest skills, as they're pretty powerful. I can't really think of any skill that could be added for future levels, at least for now. Maybe there's the possibility to add new levels or a fourth skill three once @Cheaterpaul has finished his Werewolf add-on.

**Comment by Cheaterpaul** [comment]
#475

**Comment by maxanier** [comment]
So, the now implemented option to become a lord and to further level up your minions should give you some more to do.
More levels are boring.
