### ISSUE TITLE
[Bug]Crash on Villager

### ISSUE THREAD

**Issue by franciscomirasg** [TeamLapen/Vampirism#448]
## Versions
- Minecraft: 1.12.2                 
- Forge: forge-1.12.2-14.23.5.2814
- Vampirism:  1.5                                    

Whe a vampire try to infect a villager the game crash.

1 Capture a village with vampire faction
2. Vampire bite a Villager
3. Vampire infect a Villager.
4. Game crash

[crash-2019-06-16_18.56.14-server.txt](https://github.com/TeamLapen/Vampirism/files/3294346/crash-2019-06-16_18.56.14-server.txt)

**Comment by maxanier** [comment]
This is a weird bug with OpenJ9 and Forge/Access Transformers https://github.com/MinecraftForge/MinecraftForge/issues/5254

Please update Forge to latest or at least 2816+
