### ISSUE TITLE
Biome Conflict with BuildCraft, requesting config option.

### ISSUE THREAD

**Issue by HyperMan19680** [TeamLapen/Vampirism#45]
I am using the latest version of this mod and Buildcraft, but the Buildcraft config refuses to change for some reason. Every time I edit it, it shifts back to 40 when run. Which conflicts with this mod.

**Comment by maxanier** [comment]
Take a look at the vampirism.cfg there should already be an option "vampirism_biome_id", just try a few values over 40, until you find a available id.
