### ISSUE TITLE
[Bug] Hunter Weapon Table Lava Doesn't Add

### ISSUE THREAD

**Issue by PendragonII** [TeamLapen/Vampirism#453]
## Issue Description
Cannot add lava to Hunter Weapon Table because lava is already inside, but not enough lava to create said weapon, armor, et cetera.

Place lava in Weapon Hunter Table, craft a Enhanced Crossbow then craft another Enhanced Crossbow. You'll see there's not enough lava.

## Additional Information
A current work around is break the Weapon Hunter Table and then place it, allowing to fill the lava completely.

**Comment by maxanier** [comment]
Alright, should work in the next version. However, the remaining lava (that would be left in the bucket) is wasted. The leftover lava is only useful with third party mods that provide more granular liquid containers.
