### ISSUE TITLE
[Bug] Vampire player health level problem

### ISSUE THREAD

**Issue by SeilafeiTeino** [TeamLapen/Vampirism#455]
## Versions
- Minecraft: 1.12.2                    
- Forge:1.12.2-forge1.12.2-14.23.5.2838                       
- Vampirism: 1.5.0                                             

## Issue Description
Some vampire players are not influenced by daylight, their health level automatically deduct to vanilla human players' level instead. This might be a problem with SX-Attribute.

**Comment by maxanier** [comment]
What is SX-Attribute, is it another mod?

Also please provide a full logfile (.minecraft/logs/debug.log)
