### ISSUE TITLE
[Bug] Unable To Craft Alchemy Fire With "Enhanced Holy Water" Skill

### ISSUE THREAD

**Issue by PendragonII** [TeamLapen/Vampirism#457]
## Versions
- Minecraft:                    1.12.2
- Forge:                       14.23.5.2816
- Vampirism:                       1.5.0                      

## Issue Description
When a Hunter player select the skill (in the skill tree) "Enhanced Holy Water", the Hunter player can no longer create Normal Hunter Water. The resulting consequence is the inability to create Alchemy Fire.

It is also not possible to substitute Enhanced Holy Water for Normal Holy Water when crafting/brewing Alchemy Fire.

## Reproduce Steps
Become a Hunter.
In skill tree, follow the skills and select "Enhanced Holy Water"
Attempt to craft/brew Alchemy Fire from scratch (using raw materials)

## Additional Information
This issue was found on the Official Vampirism Server: "vampirism.maxanier.de" on June 24, 2019. Originally discovered by player "lamebambus".

**Comment by PendragonII** [comment]
Forgot to add title: Unable To Craft Alchemy Fire With "Enhanced Holy Water" Skill

**Comment by maxanier** [comment]
Thank you for reporting.
I will think of a solution

**Comment by maxanier** [comment]
Using enhanced or special holy water should be possible now (and result in slightly more alchemical fire items)
