### ISSUE TITLE
Vampires should not watch invisible players

### ISSUE THREAD

**Issue by ThugPug43** [TeamLapen/Vampirism#467]
## Versions
- Minecraft: 1.12.2            
- Forge: All 1.12.2 versions affected                   
- Vampirism: All 1.12.2 versions affected                                     

## Issue Description
When using invisibility, vampire NPCs will still turn and face players. I've only tested this as a hunter, I'm not sure about anything else. This makes it very difficult to use the "How to actually use a stake" ability.

## Reproduce Steps
Drink an invisibility potion and go near a vampire NPC in survival mode.

## Additional Information
In 1.14 there were some tweaks to invisibility so it might not even be a Vampirism problem, but a vanilla one.

**Comment by Cheaterpaul** [comment]
While vampirism uses vanilla methods to choose the "target to look at", they ignore the invisibility of entities / players

**Comment by maxanier** [comment]
That's true, but it would actually make more sense if they wouldn't not. So maybe we should add our own little check to make sure vampires do not look at invisible players (or at least only very rarely).

**Comment by maxanier** [comment]
It looks like in 1.14 vanilla actually considers the "effective" distance, which is influenced by visibility aspects for the Watching Goal
