### ISSUE TITLE
[Bug] Alchemical Cauldron And Hopper

### ISSUE THREAD

**Issue by PendragonII** [TeamLapen/Vampirism#480]
## Versions
- Minecraft: 1.12.2
- Forge: 14.23.5.2816
- Vampirism: 1.5.1

## Issue Description
Placing a hopper under an Alchemical Cauldron will consume the coal (or any fuel) from the Alchemical Cauldron instead of the Alchemical Cauldron's product (such as Pure Salt)

This hinders the ability to create an "automated brewing" style production (such as with vanilla Brewing Stands, see image 1)

## Reproduce Steps
Go into a single player world with creative mode (a flat world will do)
Unlock the Hunter Skill "Basic Alchemy"
Place a hopper pointing into a chest
Place an Alchemical Cauldron on top of the hopper
Insert one piece of coal into the Alchemical Cauldron
Insert one water bucket into the Alchemical Cauldron

Pure Salt will not be produced due to the coal escaping the Alchemical Cauldron

## Additional Information
In late game of Minecraft, after gathering many resources (see image 2) automating production is very useful.
My hope is that Hunters will be able to automate production using the Alchemical Cauldron in the late game phase.

--
Image 1 - Automated brewing from brewing stands in survival. 
![2019-07-19_20 28 21](https://user-images.githubusercontent.com/43933998/61571786-135fae80-aa64-11e9-9543-a519d7ee9c6e.png)

Image 2 - Some resources I gathered in survival. Automation will be useful.
![2019-07-19_20 32 59](https://user-images.githubusercontent.com/43933998/61571814-74878200-aa64-11e9-8684-bbbd0fa5ea61.png)

**Comment by Cheaterpaul** [comment]
Todo: canExtractItem() in TileAlchemicalCauldron should return false for index 3
