### ISSUE TITLE
[Bug] Semi Auto Crossbows And Infinity Enchantments Do Not Work Together

### ISSUE THREAD

**Issue by PendragonII** [TeamLapen/Vampirism#482]
## Versions
- Minecraft: 1.12.2
- Forge: 14.23.5.2816
- Vampirism: 1.5.1

## Issue Description
The enchantment: enchantment.arrow_infinite on a Semi Automatic Crossbow (Normal or Enhanced) does not currently benefit from the infinity enchantment. When a player uses the Semi Automatic Crossbow with the enchantment.arrow_infinite enchantment, the Semi Automatic Crossbow will request for a reload after 12 shots regardless.

## Reproduce Steps
 - Go into a single player world with creative mode (a flat world will do)
 - Unlock the Hunter Skills "Enhanced Crossbow" and "Technology"
 - Place an anvil and add the enchantment "enchantment.arrow_infinite" onto the Semi Automatic Crossbow (Normal or Enhanced)
 - Now shoot into the sky rapidly. Normally you can do this until the crossbow breaks but you will need to reload (the bug)

## Additional Information
Also you may notice that the mending enchantment will work fine with the enchantment.arrow_infinite enchantment. Please continue the compatibility between these two enchantments. They are very good together as a Hunter.

**Comment by maxanier** [comment]
I will have to look into this, maybe it does not work for balancing reasons. It if it should be intentional, the crossbow shouldn't be enchant-able with infinity in the first place

**Comment by maxanier** [comment]
This is intentional. The crossbow would be very overpowered otherwise.
The infinity enchantment is never applied to the crossbow at an enchantment table. Unfortunately there is no way to prevent this from being done with a book.
