### ISSUE TITLE
[Bug] Vampire Player Bat Dies Then Will Lose Inventory Permanently (Multiplayer)

### ISSUE THREAD

**Issue by PendragonII** [TeamLapen/Vampirism#484]
## Versions
- Minecraft: 1.12.2
- Forge: 14.23.5.2816
- Vampirism: 1.5.2

## Issue Description
When a Vampire Player turns into a bat and then dies all their items will disappear upon death.

## Additional Information
This issue is only multiplayer related and is not appearing in singleplayer. It is possible that this is solely a server-side issue.
This occurred on the following Multiplayer Server: vampirism.maxanier.de

## Reproduce Steps
Become a Vampire Player.
Unlock the skill "Bat Mode"
The Vampire Player turns into a bat and dies. If they had items they have now disappeared.

**Comment by Cheaterpaul** [comment]
untill now i am unable to reproduce it.

as far as i now, If this is a problem with vampirism, I think the issue should appear no matter you are a bat or not.

under what circumstances did you die?

**Comment by maxanier** [comment]
Pendragon, does this happen every time one the server?

**Comment by lunofe** [comment]
The bug is exclusive to the server and was caused by another plugin, not Vampirism.
It is fixed by now.
