### ISSUE TITLE
Request: Config for door breaking

### ISSUE THREAD

**Issue by Teibidh** [TeamLapen/Vampirism#49]
While the vampires breaking doors to get to food supplies is cool and all, it's really really annoying when you're in your base doing stuff and you have to go deal with vampires trying to break doors to get to your horses. In early game, sure, it presents an additional challenge, late game? It's really nothing but an annoyance. All I have to do is shoot them through the door (yes, this works on zombies too), but it's stopping what I'm doing, going upstairs and doing it that's the problem. This might not be so bad if it weren't for the fact that the vampires don't seem to respect any other hostile mob code (see issue #48 ).

If we could either make this a config option, or at least have the vampires handle this the same way zombies do where they only break doors in Hard (or is it normal?) that would be great.

**Comment by maxanier** [comment]
Ok, I will implement that.

**Comment by maxanier** [comment]
Looking at the code it looks like they can only break doors on hard difficulty, I checked in game and for me they only break doors on hard. They will try to destroy them on easy and normal too, but will fail to (like Zombies to I think)

**Comment by Teibidh** [comment]
I completely agree that they cannot break the door. However, zombies will walk up to the door and sit in the doorway ... maybe pound on the door once ... The vampires continue to pound on the door, and it's a door that a player doesn't have to be near... They're going after horses. Meanwhile, I'm 20 blocks underground doing whatever I'm doing and it's obnoxiously loud P

This is very definitely more of a quality of life thing than a bug.

**Comment by maxanier** [comment]
Okay now I understand what you mean. Yeah, already the zombie, which try to break the doors, but can't, annoy me a lot. I think I will remove the door breaking ai, unless it is on hard and they can actually destroy it

**Comment by maxanier** [comment]
The door breaking AI is now only added if the difficulty is set to hard
