### ISSUE TITLE
How can I get Vampire Book

### ISSUE THREAD

**Issue by maaarooo** [TeamLapen/Vampirism#491]
## Versions
- Minecraft:                    
- Forge:                       
- Vampirism:

**Comment by lunofe** [comment]
The issue section isn't for general questions. It is for issues.
If you refer to the book required for leveling up as a vampire, you might want to take a look at the ingame guidebook, _which is answering literally every question_, instead.

**Comment by maxanier** [comment]
Make sure to install Guide-API
