### ISSUE TITLE
[Bug]Vampirism vampires don't extend IMob and thus, don't respect mega torches, discidia, etc.

### ISSUE THREAD

**Issue by smilodon79** [TeamLapen/Vampirism#492]
## Versions
- Minecraft:                    1.12.2
- Forge:                       14.23.5.2768
- Vampirism:                                   1.5.0          

## Issue Description
Vampirism vampires don't extend IMob.  As a result, they register as passive mobs and thus, don't respect mega torches.  It doesn't feel right that dread lamps prevent vampirism vampires from spawning, while mega torches don't.  This decision also prevents astral sorcery discidia rituals from working on vampires, making it complex to farm the vampires for progression.

## Reproduce Steps
1.  Plonk down a discidia ritual.  It doesn't kill vampires
OR
1.  Plonk down mega torches.  They don't prevent spawning of vampires
2.  Plonk down dread lamps.  They prevent spawning of squid, pigs, sheep, cows... and vampires.

## Additional Information
Not applicable.

**Comment by maxanier** [comment]
Difficult topic, see #190 #199

**Comment by Vectrobe** [comment]
It really isn't, vampires should be set as hostile, and you should be using custom targeting.

**Comment by maxanier** [comment]
Did you even read the discussion?

**Comment by Vectrobe** [comment]
Yes, I did.
