### ISSUE TITLE
[Bug] Iron Golems Do Not React to Vampire Player Biting

### ISSUE THREAD

**Issue by PendragonII** [TeamLapen/Vampirism#495]
## Versions
- Minecraft: 1.12.2
- Forge: 14.23.5.2816
- Vampirism: 1.5.2

## Issue Description
Iron Golems do not react to Vampire Players biting the Iron Golem regardless if the Iron Golem absorbed damage.

Iron Golems in Hunter Controlled Villages will not engage in Vampire NPC's nor will Vampires NPC's engage with the Iron Golem.

## Reproduce Steps
 - Go into a single player world with creative mode (a flat world will do)
 - Find a Hunter Controlled Village and join the Vampire faction.
 - Create an Iron Golem **[1]**
 - Go into singleplayer (having diamond armor on and a sword)
 - Bite The Iron Golem (Do not kill). The Iron Golem should not react (the bug).
 - Surround the Iron Golem with Vampires, Advanced Vampires, and Vampire Barons. The Iron Golem will not engage the vampire creatures (another bug?).

## Additional Information
It would make sense if Iron Golems in Vampire Controlled Villages did not pursue Vampires.

A good replacement for naturally spawning Iron Golems in Faction Controlled Villages would be Advanced Hunters/Vampires altogether on top of pre-existing Faction Controlled Guards.

https://discordapp.com/channels/430326060635258881/430336564862910475/608054277600182294

**[1]** https://minecraft.gamepedia.com/Iron_Golem#Creation

**Comment by maxanier** [comment]
This is correct (vanilla) behavior. Player created golems never ever attack players.

However, it would somehow make sense for them to attack vampires. Even though this is mainly the job of the vampire hunters. However, I will make golems attack vampires if they are assigned to a non vampire village
