### ISSUE TITLE
Add blacklist/whitelist for dimensions in which you get sundamage

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#50]
Currently you only get sundamage in the overworld which makes some modded dimensions unbalanced.

Add a boolean config to switch between white and blacklist (whitelist as default)
Add a String config option for both white and blacklist (Dimension id's comma seperated)
Add subcommand /vtest dimid to retrieve the current dimension's id

**Comment by maxanier** [comment]
Finished this for the 1.8 branch.
I will implement that for 1.7.10 if I do another update for it.

**Comment by Teibidh** [comment]
Oh, please do for 1.7 if you can find some time... I'm still stuck on that due to, you know, every other mod in the world. I was fine on 1.8 when I first started, but the kids wanted these silly mod things, and now I'm hooked :)

**Comment by maxanier** [comment]
Now also implemented in the 1.7 branch. Expect a release in the next few days.

You can set a default for unspecified dimension in the main config file (sundamage_default).
You can specify sundamage for a dimension by adding "<dimensionid>:<1/0>" to sundamge_dims (e.g. "5:1" to enable sundamage in dim 5). Use one line/String for each dimension.
You can find out the dimension you are in with "/vampirism currentDimension".

**Comment by maxanier** [comment]
Specifying sundamge via a command would be cool for mods like Mystcraft, but I just thought of it and I think it wouldn't be too popular anyways. Maybe later

**Comment by maxanier** [comment]
http://minecraft.curseforge.com/projects/vampirism-become-a-vampire/files/2270194
