### ISSUE TITLE
[Bug] Crash related to Sanguinare potion effect

### ISSUE THREAD

**Issue by Nawor3565** [TeamLapen/Vampirism#502]
## Versions
- Minecraft: 1.12.2                   
- Forge: 14.23.5.2838                      
- Vampirism: 1.5.3                                            

The game suddenly crashed with a ticking entity exception. The error mentions the Sanguinare potion effect. Crash log below.

N/A

Crash log: https://pastebin.com/HuJ8rW5q

**Comment by maxanier** [comment]
Thank you for reporting. Does this happen frequently or was this a one time crash?
Will fix it regardsless, just to decide if I should release a new version just for this

**Comment by Nawor3565** [comment]
Honestly, not sure. After removing the entity with NBTEdit I used the In Control! mod to disable advanced vampires from spawning. Haven't had a crash since then.

**Comment by maxanier** [comment]
Unfortunately, I can't really figure out what could be causing this crash. At the position of the crash log stacktrace mentions, nothing should be able to cause that exception. So there might another core mod messing with Minecraft's source code.

**Comment by Nawor3565** [comment]
Interesting. Not sure what mod could be causing it. Regardless, I just got another crash for the same reason ([crash log](https://pastebin.com/ymZ5dVUy)) with a normal vampire, so it looks like it's not a one-time thing. If you could publish an update with the workaround, that would be awesome.
