### ISSUE TITLE
[Bug] Can't suck blood on versions higher than 1.4.9

### ISSUE THREAD

**Issue by FiddleSticks96** [TeamLapen/Vampirism#505]
## Versions
- Minecraft: 1.12.2
- Forge: 14.23.5.2838                      
- Vampirism: 1.5.4                                            

## Issue Description

As the title says, I cannot suck blood as a vampire on any version of Vampirisim past version 1.4.9. The fangs icon still shows up and V is keybound only to the bite attack and no other action, but I cannot suck blood at all no matter what I try (sneaking, attacking/sneaking from behind, holding a glass bottle, holding an empty blood bottle, consoling my hunger to 0). I can still bite entities that you can't get blood from, like zombies (and chickens for some reason), but I cannot suck blood at all, whether it be on vanilla entities (like cows) or on MCA villagers (which I've added to the vampirism_blood_values txt file as instructed).

## Reproduce Steps

Run any version of Vampirism of 1.5.0 or higher, try to suck blood, be sad and hungry.

## Additional Information

Did something change after version 1.4.9? Is there something special I have to do to feed now? If I run version 1.4.9 it works fine.

**Comment by PendragonII** [comment]
Have you tried holding down the biting key for a few seconds while looking at a creature?
On version 1.5.0 and higher a delay has been added; sucking blood is no longer instant.

**Comment by FiddleSticks96** [comment]
> Have you tried holding down the biting key for a few seconds while looking at a creature?
> On version 1.5.0 and higher a delay has been added; sucking blood is no longer instant.

Thank you! That was what the problem was. I've been trying to figure out what was wrong all day.
