### ISSUE TITLE
[Feature] Revert Back To Normal

### ISSUE THREAD

**Issue by EmoOctober55** [TeamLapen/Vampirism#507]
## What would you like to have changed or added to Vampirism

I would like to be able to go back to normal and stop being a vampire. Even a command could be useful
## Does this make the mod experience more balanced?
yes

## Can you provide additional resources (etc. textures or models)
no

**Comment by PendragonII** [comment]
The command would be **/vampirism level vampire 0** or **/vampirism level hunter 0**.

In singleplayer survival there is a guide book for Vampirism craftable with a normal book and a heart placed next to each other.
In singleplayer creative you can go into the _creative mode inventory menu_ > _Miscellaneous_ scroll to the bottom and you'll find the Guide Book.

The Guide Book will teach everything about the Vampirism Mod, _including how to revert back to a Human_.
For commands: type **/vampirism [press-tab]** and Minecraft will autocomplete all possible commands for vampirism.

**Comment by maxanier** [comment]
You can also look for an altar of cleansing which is generated in the church building in some villages. There you can revert in survival
