### ISSUE TITLE
[Bug] Impossiblely Expensive Expert Villagers

### ISSUE THREAD

**Issue by PendragonII** [TeamLapen/Vampirism#510]
## Versions
- Minecraft: 1.12.2
- Forge: 14.23.5.2844
- Vampirism: 1.5.4

## Issue Description
Named Hunter Experts require more Vampire Souls as a price than the Hunter Player can input in the trade interface menu (see image)

## Reproduce Steps
 - Start a singleplayer Minecraft world (flat will do) with Creative Mode and Villages enabled.
 - Become a level 14 Hunter **/vampirism level hunter 14**
 - Find a natural Hunter Village with a Named Hunter Expert.
 - Continuously trade with the Named Hunter Expert, unlocking higher tier trades.
 - Eventually the Hunter Player will encounter an impossibly high trade.

## Additional Information

![2019-09-15_12 50 55](https://user-images.githubusercontent.com/43933998/64925244-8adb6100-d7bb-11e9-8cd2-2726db5bfff8.png)

You can see in this image that the Named Hunter Expert is requiring the Hunter Player **64 and 11**5 Vampire Souls, the Hunter Player can only trade **64 and 64** Vampire Souls making this trade impossible.
![2019-09-15_12 50 55-cropped](https://user-images.githubusercontent.com/43933998/64925273-ead20780-d7bb-11e9-8d41-e18b68e5ab04.png)
![2019-09-15_12 51 02](https://user-images.githubusercontent.com/43933998/64925245-8adb6100-d7bb-11e9-8482-9eb65280b3db.png)

 - Named Vampire Experts do not encounter any similar issue.
 - It would be convenient to have a toggable command to prevent Named Expert Villagers from thanking the player for every trade purchase because trading in bulk will have the villager spamming the player's chat.

**Comment by maxanier** [comment]
Fixed in next version.
Not gonna add a comment to suppress the message. Too much work for to little benefit.
