### ISSUE TITLE
[1.14] Village worldgen

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#516]
- <s>TileTotem</s>
- <s>Villagers</s>
- Village world gen
- <s>Village capturing commands</s>

**Comment by maxanier** [comment]
@Cheaterpaul 1.14 is currently missing the hunter trainer house and the village church, right?
What exactly do we need to add them back. I guess the Forge PR won't be accepted any time soon. So what can we do without? If we need some small modifications in MC code we could use a coremod

**Comment by Cheaterpaul** [comment]
basically we just need a method in JigsawPattern to add Jigsawpieces to the pattern

**Comment by maxanier** [comment]
If you write the (dummy) code of what has to be added to JigsawPattern, I can write the corresponding coremod

**Comment by maxanier** [comment]
Or can this even be done via access transformers or reflection?

**Comment by Cheaterpaul** [comment]
I think its possible with access transformers. Don't know why i never thought about it. I will test it later

**Comment by maxanier** [comment]
This is all done right?

Could keep this open to track Forge PR https://github.com/MinecraftForge/MinecraftForge/pull/6378
