### ISSUE TITLE
Bat mode

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#518]
- Bounding box isn't correct in bat mode.
Waiting for Forge

**Comment by maxanier** [comment]
Implemented using coremod 8232b16d4086d84a97b92e1f165b792b07c6d31c.
If https://github.com/MinecraftForge/MinecraftForge/pull/6369 is ever accepted, we should migrate

**Comment by Cheaterpaul** [comment]
PR MinecraftForge/MinecraftForge#6858 accepted
