### ISSUE TITLE
Permission to Enter A House [Feature]

### ISSUE THREAD

**Issue by tacticalGambling** [TeamLapen/Vampirism#520]
## What would you like to have changed or added to Vampirism
Since Vampires must always ask permission to enter a building before entering, I figured it would be quite interesting to add this to the mod. This could be accomplished by an item that works in a similar fashion to a claim wand in plugins, in the sense that you click the corners of a certain area to claim it as a house. There could be some sort of chat-given cue that allows the players in? If that is at all possible.

## Does this make the mod experience more balanced?
In my experience, absolutely! In a mod about vampires, there should always be as many references to vampire fiction as possible. Besides, waltzing into someone's house and sucking their blood is a bit imbalanced.

## Can you provide additional resources (etc. textures or models)
Unfortunately, I do not have experience in this area.

**Comment by varappdev** [comment]
I agree

**Comment by maxanier** [comment]
While this might make sense lore wise, the requirement of having some sort of claiming tool wouldn't fit in very well. Furthermore, it might be very annoying for server admins and there are already tons of permission plugins.
A reasonable alternative would be a plugin for the server that checks if the player is a vampire and bases (claim) permissions based on that. 
However, I won't write that, but I would try to assist anyone trying to do so.
