### ISSUE TITLE
[1.14.4][Bug] Server crash creeper - Cannot get ExtendedCreature from EntityCreature CreeperEntity

### ISSUE THREAD

**Issue by ProsperCraft** [TeamLapen/Vampirism#526]
## Versions
- Minecraft:       1.14.4             
- Forge:        1.14.4-28.1.26       
- Vampirism:  Vampirism-1.14.4-1.6.0-alpha+20191002-0007                                           

## Issue Description
Server crashed when a creeper blew up.

## Additional Information
https://gist.github.com/ProsperCraft/4bdacaed31b97ddcffda85adc6ba8732

**Comment by ProsperCraft** [comment]
https://paste.fedoraproject.org/paste/SpoQEcw4hSs3k2aXQ0UVqA

**Comment by maxanier** [comment]
Thx for reporting. There was a missing safety check.
Revisited the entire system.

New alpha should be live
