### ISSUE TITLE
[1.14.4][Bug] Server crash on changing dims after death then using the tombstone key to get back to grave.

### ISSUE THREAD

**Issue by ProsperCraft** [TeamLapen/Vampirism#527]
## Versions
- Minecraft:    1.14.4                
- Forge:              forge-1.14.4-28.1.26     
- Vampirism:             Vampirism-1.14.4-1.6.0-alpha+20191002-0007                                

## Issue Description
Server crash on changing dims after death then using the tombstone key to get back to grave.

## Reproduce Steps
Edit the tombstone config to enchant grave key 100% of the time and start server
go to the YAMDA mining dim using the portal from that mod
die, and use the enchanted key to teleport back to the tombstone in the mining dim.

## Additional Information
Stacktrace in logs -
https://gist.github.com/ProsperCraft/bf61757c7396ef4b5582eb8e2b41a225
[debug.log](https://github.com/TeamLapen/Vampirism/files/3679078/debug.log)
[latest.log](https://github.com/TeamLapen/Vampirism/files/3679079/latest.log)

**Comment by ghost** [comment]
As precision, the interdimensional teleportation is a vanilla method in the player :
```java
ServerPlayerEntity.teleport(targetWorld, xCoord, yCoord, zCoord, yaw, pitch);
```
so, i suppose it's reproductible with any interdimensional teleportation and not specially related to tombstone.

**Comment by ProsperCraft** [comment]
https://gist.github.com/ProsperCraft/d96b92d79317c4eb06d8e78721066622

Not limited to only Tombstone, this is the Stars mod author teleporting to another dim with Stars.

**Comment by maxanier** [comment]
Thank you for reporting.
Pretty stupid bug (not sure why it even compiled).  Apparently, I never changed dimensions during testing. Sorry, my bad.

**Comment by ProsperCraft** [comment]
This is not fixed as of Vampirism-1.14.4-1.6.0-alpha+20191005-1309

Server Crash on player changing dimension-
https://gist.github.com/ProsperCraft/7de8c09e481f7fba0c23fc4fa6a1ecc1

Logs
[crashondimchange.zip](https://github.com/TeamLapen/Vampirism/files/3693949/crashondimchange.zip)

**Comment by maxanier** [comment]
This is a different crash reason, which I cannot neither reproduce nor understand.
However, I have noticed that the method call that initiated this issue, was unnecessary and removed it. So with the latest version it hopefully should not occur anymore

**Comment by maxanier** [comment]
I assume the (new) issue is fixed as well?
