### ISSUE TITLE
Player head completely white

### ISSUE THREAD

**Issue by bigstiffy** [TeamLapen/Vampirism#53]
When becoming a vampire, the skin of the player's head turns completely white as if it was erased.
Mod version: 0.7.8.1
Java: 7
Forge: 10.13.4.1492
Vanilla launcher.

**Comment by maxanier** [comment]
How did you create your skin?
After checking http://skins.minecraft.net/MinecraftSkins/bigstiffy.png it seems your skin slightly differs from the usual ones. Most skins are 64x64 and have a transparent background, yours is 62x32 and has a white background.
Please try to remove the background from your skin, or recreate it with a skin editor like http://minecraft.novaskin.me/. This should solve the problem for now.
I will try to avoid such problems in the 1.8 rewrite, but don't know if I can consider all exceptions.

**Comment by bigstiffy** [comment]
I think I created the skin in gimp, back when MC 1.4.7 rolled out. Will try updating the skin and report back.

**Comment by maxanier** [comment]
I suppose your problem is solved, isn't it? @bigstiffy
