### ISSUE TITLE
[Bug] Can't suck blood 

### ISSUE THREAD

**Issue by TfsRaptor** [TeamLapen/Vampirism#533]
## Versions
- Minecraft: 1.12.2                    
- Forge: Curse (the twitch one)                    
- Vampirism:    1.12.2-1.5.4                                         

As a vampire i can't suck blood from creatures 
(correct creatures tryed pig,cow,villager)
also i can still attack with it to kill other mobs

I used RLcraft with vampirism as well and i'm jsut trying to suck blood but it wont work

**Comment by maxanier** [comment]
Do keep the button pressed?

If so, I need an logfile
