### ISSUE TITLE
[Bug][1.14.4] Vampire forests are far too common.

### ISSUE THREAD

**Issue by ProsperCraft** [TeamLapen/Vampirism#534]
## Versions
- Minecraft:    1.14.4                
- Forge:            forge-1.14.4-28.1.38           
- Vampirism:                  Vampirism-1.14.4-1.6.0-alpha+20191006-1207                           

## Issue Description
They generate too frequently drowning out all of the other variety that comes from Biomes O Plenty and other biome mods.

Please add a config to configure the weight?

This is how Useless mod did it for their biome and it worked well- 
https://github.com/TheMCBrothers/UselessMod/issues/9

**Comment by maxanier** [comment]
Theoretical it should have the same weight as the vanilla plains biome, but BOP might use different weights.

It is already "configurable", but the configuration is not yet editable #523.

**Comment by maxanier** [comment]
With the latest alpha there should be a new (server/save folder) balance config which includes the vampire forest weight
