### ISSUE TITLE
[Feature] 1.14.4 - Please make Vanilla phantoms not hunt vampires who don't sleep in a bed.

### ISSUE THREAD

**Issue by ProsperCraft** [TeamLapen/Vampirism#536]
## What would you like to have changed or added to Vampirism
Currently the 1.14 vanilla mechanic is that if you don't sleep in a bed phantoms come after you, I think this should not apply to those that are no longer living.

**Comment by maxanier** [comment]
Interesting, I should keep up with Vanilla changes more ^^

@Cheaterpaul What is the current status on the coffin sleep mechanic. And could this somehow be integrated in the Forge PR (if there is an active one)?

**Comment by Cheaterpaul** [comment]
At the moment coffins shouldnt work.

The phantoms spawn when the players last time in bed (Stats.TIME_SINCE_REST) is older than 3 days. Time is set every time a player has a bedlocation, which would be set when inside of a coffin (PR or not).

**Comment by maxanier** [comment]
Alright.
Vampires should need to rest too, don't they? Therefore, everything should work fine once coffins work again.

Or, do you think vampires should not have to rest at all? @ProsperCraft

**Comment by ProsperCraft** [comment]
I guess Vampires need their rest as well, and if the coffin resets the time since rest that will work.

**Comment by maxanier** [comment]
@Cheaterpaul is it possible to just set the last time in bed and the spawn point when right clicking the coffin until Forge is patched?

**Comment by Cheaterpaul** [comment]
at the moment the bedlocation is set even if you instanly drop out of the coffin

**Comment by maxanier** [comment]
Alright, closing this. Even though you can't sleep in coffins yet, you can use them to set your spawn point and reset the rest since timer
