### ISSUE TITLE
[Bug] Conflict with the mod Explorercraft!

### ISSUE THREAD

**Issue by umutarmut38** [TeamLapen/Vampirism#537]
## Versions
- Minecraft: 1.14.4                   
- Forge:  28.1.40                     
- Vampirism: 1.14.4                                            

## Issue Description
Hello,
I discovered a problem with vampirism in combination with the mod Explorercraft. Everytime a endercreeper or creeper with a mushroom explodes, the game/ server crashes. 

## Reproduce Steps
Having both mods installed and having a creeper from the Explorercraft mod explode.

## Additional Information
Here is the crash report on both mobs:
[crash-2019-10-09_17.39.48-server.txt](https://github.com/TeamLapen/Vampirism/files/3708419/crash-2019-10-09_17.39.48-server.txt)
[crash-2019-10-09_17.50.15-server.txt](https://github.com/TeamLapen/Vampirism/files/3708420/crash-2019-10-09_17.50.15-server.txt)

**Comment by Cheaterpaul** [comment]
Can you try to use a newer Vampirism version.

In your crash report is says you use Vampirism 1.14.4-1.6.0-alpha+20190930-2051,
there is a newer version available which should fix this.

**Comment by Cheaterpaul** [comment]
I assume this is fixed, so i am closing this issue.
