### ISSUE TITLE
[Bug][1.14.4] Server crash - .vampirism.entity.goals.BiteNearbyEntityVampireGoal

### ISSUE THREAD

**Issue by ProsperCraft** [TeamLapen/Vampirism#539]
## Versions
- Minecraft: 1.14.4                   
- Forge:     forge-1.14.4-28.1.40                  
- Vampirism:  Vampirism-1.14.4-1.6.0-alpha+20191011-0002           
- Modpack: https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk                                

## Issue Description
Server crashed while I was sleeping.  The players don't know what caused it or how to reproduce it.

## Reproduce Steps
Unkonwn.

## Additional Information
Crash report-
https://gist.github.com/ProsperCraft/e4d37a6c702705fe640a31734576eafb

**Comment by ProsperCraft** [comment]
Here is another one 
https://paste.fedoraproject.org/paste/4QlItvwm2gDSmN~F7-9SqQ

**Comment by ProsperCraft** [comment]
https://paste.fedoraproject.org/paste/~xFaqYGh2288o-RNw5-BHg

**Comment by maxanier** [comment]
Might be another mod doing strange things, not sure. Just catching and ignoring the exception now, as it does not do any real harm.
