### ISSUE TITLE
[Bug]Crash on new world creation(mod spawns you in a village) - related to village gen.

### ISSUE THREAD

**Issue by ProsperCraft** [TeamLapen/Vampirism#543]
## Versions
- Minecraft:       1.14.4             
- Forge:          forge-1.14.4-28.1.44             
- Vampirism:     Vampirism-1.14.4-1.6.0-alpha+20191011-0002                                        

## Issue Description

I have a mod that spawns you in a village on new world creation so it flushed out this village gen bug, it doesn't happen each new world, see the issue below.

Removing Vampirism stopped the crash, although of course this is not a smoking gun as that could have changed the worldgen, making a different village in a different location.

https://github.com/Glitchfiend/BiomesOPlenty/issues/1475

**Comment by Cheaterpaul** [comment]
this seems to be an issue where minecraft wants to get a village house from an empty pool (maybe a mod removes elements).
But unfortunate Vampirism momentanly doesn't mess with structures. So this shouldn't have anything to do with Vampirism.

**Comment by maxanier** [comment]
Another possible explanation is a biome with an incorrect village configuration.
If the `JigsawManager` gets a unregistered id (ResourceLocation) in `func_214889_a`, the `JigsawManager.REGISTRY` will return a `JigsawPattern#INVALID` entry. This has an empty piece list which again makes `getRandomPiece` crash.
Said id is specified in the `VillageConfig` which is retrieved from the current biome (via the ChunkGenerator).
Therefore, if some biome registeres an invalid structure like
```
this.addStructure(Feature.VILLAGE, new VillageConfig("village/does/not/exist", 6));
```
it could lead to this crash.

Vampirism does not add a village to it's forest biome. And only does an unrelated modification to GeneratorSettings, so I think it is very unlikely that Vampirism is involved (but I have been proven wrong before).
But maybe you can check with any biome adding mod, that they do this corretly.
