### ISSUE TITLE
[Bug] Server hard lock 2.0

### ISSUE THREAD

**Issue by ProsperCraft** [TeamLapen/Vampirism#544]
## Versions
- Minecraft:       1.14.4             
- Forge:              forge-1.14.4-28.1.44         
- Vampirism:       Vampirism-1.14.4-1.6.0-alpha+20191011-0002                                      

## Issue Description
Dedicated server hard lock.

## Reproduce Steps
This happens at random intervals after players are online and playing for a period of time on the dedicated server.

## Additional Information
Here is a warmroast of the server hard locked up.

![6b188152b1ca3bc34aa0a362bb0cf441](https://user-images.githubusercontent.com/4427684/66716542-12e96200-ed8c-11e9-89f6-6eac11931ede.png)

Here is a stacktrace from watchdog when I wasn't around to catch it and profile it before it rebooted itself-
https://gist.github.com/ProsperCraft/73b3fc59f3f97bb9d3c68a5c8dd4421e

**Comment by maxanier** [comment]
Looks like I missed something (Unless you added another mod). Gonna have another look. 
No need for the stacktrace/warmroast by the way. They unfortunately don't help in any way.

**Comment by maxanier** [comment]
Found something else. Please try the latest alpha

**Comment by ProsperCraft** [comment]
pulled from the pack for now and wiped he world, might readd later.

**Comment by maxanier** [comment]
Ok, sad but understandable. Guess developing a 1.14 pack is painful enough, don't need another alpha stage mod ^^

Going to close this, as I am 97% confident we are safe now.
