### ISSUE TITLE
[1.14.4] Blood bottle Item Issue

### ISSUE THREAD

**Issue by ghost** [TeamLapen/Vampirism#546]
## Versions
- Minecraft: 1.14.4                  
- Forge: 2.1.56                     
- Vampirism: 1.6.0                                            

## Issue Description
Blood Bottle item not showing up in inventory

## Reproduce Steps
The error happens just by getting a blood bottle

## Additional Information
![2019-10-17_23 51 26](https://user-images.githubusercontent.com/49107551/67062496-d1650800-f139-11e9-902d-7e6a9a1bfdc1.png)
![2019-10-17_23 51 31](https://user-images.githubusercontent.com/49107551/67062500-d1fd9e80-f139-11e9-902e-94d2a423f263.png)

**Comment by maxanier** [comment]
Please specify the full version of Vampirism. Not just 1.6 but 1.6.0-alphaXXXXXX.
I assume you are not running the latest version, as I cannot reproduce it with the latest alpha

**Comment by ghost** [comment]
The actual version I'm using is 1.6.0-alpha+20191013-2127

**Comment by Enzo12091209** [comment]
Also, to recreate the bug install Vampirism after creating a Forge world

**Comment by ghost** [comment]
The problem was caused because of optifine
