### ISSUE TITLE
[Bug] Missing Hunter-Table-Ritual requirements for next intel only update on shift-click

### ISSUE THREAD

**Issue by Kiliatos** [TeamLapen/Vampirism#548]
## Versions
- Minecraft: 1.14.4                    
- Forge: 28.1.45                      
- Vampirism: Vampirism-1.14.4-1.6.0-alpha+20191021-1133                                            

## Issue Description
When manuall picking items up from the inventory and putting them in the corresponding slot of the hunter table, the "Missing X of Y for this ritual" does not update.

It does update if the item is shift-clicked from the inventory.

## Reproduce Steps

1. Open hunter table UI
1. Select Book from inventory (works with Fangs or Blood as well)
1. Put it into the leftmost slot of the UI
1. See, that the requirements do not update

## Additional Information

Empty UI:
![grafik](https://user-images.githubusercontent.com/50572213/67234774-05943d80-f446-11e9-885b-12a148137f06.png)

After picking up the book in the inventory and puting it in the leftmost slot:
![grafik](https://user-images.githubusercontent.com/50572213/67234872-3aa09000-f446-11e9-9a77-2e757be32b83.png)

It dos not matter, how many books are put in there:
![grafik](https://user-images.githubusercontent.com/50572213/67234915-5015ba00-f446-11e9-89dc-72a6fc0f23da.png)

If I take a single book and shift-click it from the inventory, it works as expected:
![grafik](https://user-images.githubusercontent.com/50572213/67234971-72a7d300-f446-11e9-9c2d-3d711407ea59.png)

This bug prevents the completion of the ritual, even if all requirements are fulfilled:
![grafik](https://user-images.githubusercontent.com/50572213/67236246-30cc5c00-f449-11e9-9e31-2a10e0128fe0.png)

Shift-clicking all of the required items lets me complete the ritual:
![grafik](https://user-images.githubusercontent.com/50572213/67236309-522d4800-f449-11e9-8c21-a9d6059f6d04.png)

**Comment by maxanier** [comment]
Thx for reporting. Will be fixed in next alpha
