### ISSUE TITLE
Nausea effect

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [TeamLapen/Vampirism#55]
Is it possible to add a setting to disable the nausea effect, or at least, a setting to have nausea only when thirsty (blood bar empty or something like that)?

Or dunno, adding an item like sunglasses that could be used in armor slot or bauble maybe.

Thanks

**Comment by maxanier** [comment]
I will consider that for the 1.8 version

**Comment by ZatsuneNoMokou** [comment]
No way for the 1.7.10?

**Comment by maxanier** [comment]
In case I've to fix some bugs, I might implement it, but for now I don't want to do any 1.7.10 stuff, so 1.8 is released earlier.
By the way: When you fully wear vampire armor you do not get that nausea effect

**Comment by ZatsuneNoMokou** [comment]
Could you do it with a donation? If you want a craft that need blood, it could be good to make an enchant for armors of other mods.

**Comment by maxanier** [comment]
I won't implement something like that for a donation (although donations are of course appreciated :)).
But if you reaaally want it, I might implement that in the next days, shouldn't be too time consuming anyway.

**Comment by ZatsuneNoMokou** [comment]
Then thanks

**Comment by maxanier** [comment]
http://minecraft.curseforge.com/projects/vampirism-become-a-vampire/files/2281608

Haven't tested it yet, but should work.
Please tell me if it does so I can mark it as beta

**Comment by ZatsuneNoMokou** [comment]
It work, and I got a surprise, it work without having to restart the game, thanks you
