### ISSUE TITLE
[Bug] The village map generator was overwritten by another mod

### ISSUE THREAD

**Issue by LemADEC** [TeamLapen/Vampirism#551]
## Versions
- Minecraft: 1.12.2                    
- Forge: 14.23.5.2847
- Vampirism: 1.12.2-1.5.5
- UndergroundBiomesConstructs-1.12-1.3.7
- Metallurgy-4-Reforged-0.2.3

## Issue Description
When a village is loaded, logs are spammed with warnings about village map generator being overwritten and null:
```
[12:41:12] [Server thread/WARN]: [VillageGen]The village map generator was overwritten by another mod. There might be a problem! 
 The new generator class is null
```

## Reproduce Steps
Have a modpack with only those 3 mods list above, all with default configurations.
Start a new world, default settings, creative.
Fly to a village, wait up to 60 s.

## Additional Information
Once you've a village reproducing the issue, just staying will continue the spam, so it seems related to something else than pure world generation.
In most cases, issue happens immediately, sometime it takes up to ~40 s, I'm not sure why.
Issue doesn't happen in all villages, so you might need to find another. It could be related to the Vampirism totem being present in the village.

I couldn't reproduce while removing any of those 3 mods, maybe it's just less frequent or there's some unexpected cross dependency?
According to logs, there's no coremod involved here.

**Comment by maxanier** [comment]
The warning itself is intended and related to UndergroundBiomesConstruct replacing the village generator here. However, it is not supposed to be printed very often, but only when the world gen object is first created.
Maybe Metallurgy is doing something unexpected here.
I did a small change that prevents the warning from being printed multiple times
