### ISSUE TITLE
[Bug] EntityDraculaHalloween causes DataParameter ID conflicts

### ISSUE THREAD

**Issue by gamax92** [TeamLapen/Vampirism#552]
## Versions
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Vampirism: 1.5.5

## Issue Description
EntityDraculaHalloween creates a DataParameter on the EntityTameable class, which can cause an ID conflict with other mods if they have entities extending from EntityTameable and their DataParameter's initialize before EntityDraculaHalloween's does.

From what I understand, the DataParameter doesn't need to be created for EntityTameable, as it's specific to the behavior of EntityDraculaHalloween, and correcting the entity class would fix mod conflicts. If it's intended to be created for EntityTameable, then make sure the DataParameter is initialized as early as possible.

## Reproduce Steps
N/A

## Additional Information
N/A

**Comment by maxanier** [comment]
Oh, you are right, thank you for reporting. Didn't pay attention when copying from vanilla :see_no_evil:
