### ISSUE TITLE
Just a qustion

### ISSUE THREAD

**Issue by mantaszm** [TeamLapen/Vampirism#556]
1.11.2
## Versions
- Minecraft:  1.11.2                  
- Forge:         IDK              
- Vampirism:     IDK                                        

## Issue Description

Hi i got a qustion how do you   make the holly water?

**Comment by lunofe** [comment]
Github isn't for general questions, it's for feature requests and bug reports. Please refer to the official Discord server for more general topics: [https://discord.gg/NJzT7k9](https://discord.gg/NJzT7k9) 
You can use the ingame guidebook provided by the mod [GuideAPI](https://www.curseforge.com/minecraft/mc-mods/guide-api) or use the mod [Just Enough Items](https://www.curseforge.com/minecraft/mc-mods/jei) to get any crafting recipe.
