### ISSUE TITLE
[Question] Rarity of Vampire Books

### ISSUE THREAD

**Issue by user3287** [TeamLapen/Vampirism#558]
Hi! Sorry to annoy you here on GitHub, just couldnt find it anywhere else😒
Question 1: Does looting affect the droprate?
Question 2: Can Barons drop the books too?
Thx 👍

PS: Lov ur mod❤️

**Comment by PendragonII** [comment]
> couldnt find it anywhere else

Here is the Vampirism Mod Discord https://discord.gg/cAja2aj
> Does looting affect the droprate?

Yes, by a small percentage.

> Can Barons drop the books too?

No, Vampire Books can be obtained by loot chests or by killing Advanced Vampires/Hunters which have a 5% dropping chance (or 1/20).

**Comment by user3287** [comment]
Thx man ❤️ 👍
