### ISSUE TITLE
[Bug] mining tanks and altar of inspiration with flux bore (Thermal Innovation) causes error and items despawn

### ISSUE THREAD

**Issue by LocalBoomer** [TeamLapen/Vampirism#560]
## Versions
- Minecraft: 1.12.2                   
- Forge: 14.23.5.2847                      
- Vampirism: 1.5.6                                            

## Issue Description
crash and items not dropping when flux bore (in 5x5 mode) mines the tank and basic level up altar

## Reproduce Steps
place altar and/or tank in world
mine with flux bore in 5x5 mode (need resonant tier to do this) p.s. mine had Efficieny V Silk Touch and Unbreaking III enchants
(side note I have Vanilla Fix which stops the game crashing and closing if this kinda thing happens but usually it kicks me to main menu if the crash is normally fatal. This didn't so it doesn't seem to be game breaking but still problematic

## Additional Information
Pastebin not working for me so I've attached the crash report instead
[crash-2019-11-25_23.38.12-server.txt](https://github.com/TeamLapen/Vampirism/files/3889311/crash-2019-11-25_23.38.12-server.txt)

**Comment by LocalBoomer** [comment]
Placing a block where the altar was respawned the altar but not the tank. The tank was the block that was mined

**Comment by maxanier** [comment]
Thank you for reporting.
Vampirism was doing something wrong, and ThermalInnovation triggered it with some non-ideal behavior on their side https://github.com/CoFH/ThermalInnovation/pull/13.

Won't do a dedicated release for this fix, as it doesn't seem to be fatal and shouldn't be a frequent problem.
