### ISSUE TITLE
[Feature] bite attack should be changed to normal damage instead of magic damage

### ISSUE THREAD

**Issue by wolf653** [TeamLapen/Vampirism#562]
## What would you like to have changed or added to Vampirism
For the bite attack in vampire entities to be considered normal damage

## Does this make the mod experience more balanced?
Well yes due to them using magic damage for the bite attack shields and armor are ignored and not to mention the magic damage is not linked to them causing pets to not react in self defense the death message "pet was killed by magic" not "pet was killed by vampire using magic" proves this
## Can you provide additional resources (etc. textures or models)
Obviously no as this is simply a request to change the vampire up a bit
I

**Comment by maxanier** [comment]
Ah, this is only referring to creatures being bitten.
The reason for this is that the creatures are not dying from the bite itself but rather from not having any blood left to sustain their body functions.

However, them not acting in self defense is of course not good. Maybe I can make the bite attack deal 0.1 damage to trigger any self defense AI

**Comment by maxanier** [comment]
Ok, now entities have a chance to defend themselves. However, I have observed that tamed wolfs do not fight back if they are attacked.

**Comment by maxanier** [comment]
This is implemented in 1.14, so I am closing this now
