### ISSUE TITLE
[Bug] Replenishing Blood from Altar of Inspiration

### ISSUE THREAD

**Issue by PendragonII** [TeamLapen/Vampirism#563]
## Versions
- Minecraft: 1.12.2
- Forge: 14.23.5.2844
- Vampirism: 1.5.5

## Issue Description
When having empty blood/glass bottles in the inventory's hotbar while using the Altar of Inspiration, the empty blood/glass bottles will automatically replenish themselves.

## Reproduce Steps
 - Open a Minecraft World with creative and cheats enabled, a flat world will do.
 - Become a Level 1 Vampire.
 - Place down and fill an Altar of Inspiration.
 - Throughout your hotbar, place empty blood/glass bottles.
 - Activate the Altar of Inspiration, the empty blood/glass bottles are now replenished.

## Additional Information
This bug does not work with the Altar of Infusion nor with level 15. This only affects empty bottles in the hotbar and not the entire inventory.

**Comment by lunofe** [comment]
![GIF](https://user-images.githubusercontent.com/42828197/70159251-e598a080-16b8-11ea-8f3d-7b8d2ac8f32d.gif)

**Comment by Cheaterpaul** [comment]
shit after years someone found out.


https://github.com/TeamLapen/Vampirism/blob/e5b1f4f2486c428dea11934b9ef03c5a1da26da0/src/main/java/de/teamlapen/vampirism/tileentity/TileAltarInspiration.java#L102

https://github.com/TeamLapen/Vampirism/blob/e5b1f4f2486c428dea11934b9ef03c5a1da26da0/src/main/java/de/teamlapen/vampirism/tileentity/TileAltarInspiration.java#L114

i think the last line must be removed @maxanier

**Comment by maxanier** [comment]
Rather the first one. The last one deliberately does not fill blood bottles by passing `useRemaining=false`.
Not sure why the first one even exists.
