### ISSUE TITLE
Vampirism Sudden Crashes

### ISSUE THREAD

**Issue by DRAGO-KAMISAMA** [TeamLapen/Vampirism#564]
## Versions
- Minecraft: 1.12.2                   
- Forge:   14.23.5.2847                    
- Vampirism:  1.12.2-1.5.6                                           

## 
https://pastebin.com/cCRPiewz

**Comment by maxanier** [comment]
This should not be possible, but I assume some other mod is doing unexpected things.
We can probably just add a simple check on our side instead of looking into what is causing this
