### ISSUE TITLE
1.12.2 update

### ISSUE THREAD

**Issue by 9Unlimited** [TeamLapen/Vampirism#566]
## What would you like to have changed or added to Vampirism
Your most recenent update was for 1.14 but alot of people use this mod in a mod pack and most mods in general are usually 1.12.2 so if possible could you provide the same fixes to the 1.12.2 version?

**Comment by maxanier** [comment]
Almost all fixes are ported to 1.12.2 as well. Or am I missing a specific one?
Only difference is, I only do a new release for 1.12 if either enough fixes have accumulated or there is a critical one.
