### ISSUE TITLE
[Bug] [1.12.2] Blood Container

### ISSUE THREAD

**Issue by bigenergy** [TeamLapen/Vampirism#568]
## Versions
- Minecraft:     1.12.2               
- Forge:           14.23.5.2847            
- Vampirism:    1.5.6                                     

## Issue Description
The guide book states that from this container you can take blood from this container with bottles by clicking the right mouse button or shift + right mouse click. But that does not work. We tried to take blood with both vanilla bottles and "blood bottles" (from this mod)

**Comment by lunofe** [comment]
![GIF](https://user-images.githubusercontent.com/42828197/70995256-65b70100-20d0-11ea-9e58-19b7e73b4a85.gif)
Can't confirm. Do you use any other mods that could possibly cause this issue for you? Or did you only try it in creative or with stacks of bottles?

**Comment by lunofe** [comment]
Closing this now because there hasn't been an answer in the last 17 days

**Comment by nether123** [comment]
How do you craft them?
