### ISSUE TITLE
[Bug] Special Obsidian Armor Notwithstanding Vanilla Diamond Armor

### ISSUE THREAD

**Issue by PendragonII** [TeamLapen/Vampirism#571]
## Versions
- Minecraft: 1.12.2
- Forge: 14.23.5.2844
- Vampirism: 1.5.6

## Issue Description
Special Obsidian Armor of Hell (Special Obsidian) absorbs less damage than the Vanilla Diamond Armor as seen:
https://youtu.be/Sz7NLCHIBhk 
This can be traced back to Issue #553 

## Reproduce Steps
 - Open a Minecraft World with cheats enabled, a flat world will do.
 - Take a single set of Special Obsidian Armor and a single set of Vanilla Diamond Armor.
 - Find a hostile mob and record the damage absorption against the same hostile mob across both armor sets.

## Additional Information
The comparison video provided is done with unenchanted armor and a normal unenchanted diamond sword; all variables in the comparison are the same for both armor sets.

--
 - Special Obsidian Amor Durability:
        Helment:     165
        Chestplate: 240
        Leggings:    225
        Boots:         195

 - Vanilla Diamond Armor Durability:
        Helment:     363
        Chestplate: 528
        Leggings:    495
        Boots:         429

--
Vanilla Diamond Armor is still very superior against the specialized Special Obsidian Armor. The Bug is Obsidian Armor of Hell (Normal, Enhanced, Special) being inferior to the universally provided Vanilla Diamond Armor. Balancing the Absorption and Durability stats of Obsidian Armor of Hell in comparison to Vanilla Diamond Armor will overall set the Hunter Roleplayer as indeed a Hunter.

--
If you cannot watch the video: Wearing full Vanilla Diamond Armor and being hit with an unechanted diamond armor deals one and a half heart (1.5) damage intake; Special Obsidian against the same deals three and a half (3.5) damage intake.

The User in the video dealing damage was a Level 15 Hunter.
The User in the video dealing damage used only an unenchanted diamond word without issuing critical damage.
The User in the video intaking damage was a Level 15 Hunter.

**Comment by maxanier** [comment]
I think this is happens because the obsidian armor does not have armor toughness. For lower value attacks (zombie, enderman, ...) the obsidian armor absorbs more damage than the diamond armor. For very high damage values it is the other way around. I will change that today.

**Comment by maxanier** [comment]
Should be closed in latest 1.12.
Never existed in 1.14
