### ISSUE TITLE
Aggressive Pigmen

### ISSUE THREAD

**Issue by SYSTEMERROR-X** [TeamLapen/Vampirism#572]
## Versions
- Minecraft:    1.14.4                
- Forge:  28.1.104                     
- Vampirism:       Vampirism-1.14.4-1.6.0-alpha+20191210-0113                                      

## Issue Description
Zombie Pigmen are aggressive with this mod enabled. I took all mods out and created a new world and pigmen are still aggressive. They became passive again when I disabled the vampire mod.

**Comment by AryaRaiin** [comment]
I've been having the same issue in my modpack. However, I have yet to confirm whether it's Vampirisim causing the aggressive pigmen, another mod, or a compatibility issue. Let me know if you'd like me to provide anything else.

Minecraft: 1.14.4
Forge: 28.1.110
Vampirism: 1.6.0
Modpack: https://www.curseforge.com/minecraft/modpacks/chill-times
