### ISSUE TITLE
Add dimension blacklist to the configs [Feature]

### ISSUE THREAD

**Issue by AryaRaiin** [TeamLapen/Vampirism#576]
## What would you like to have changed or added to Vampirism

Please add a dimension entity spawn blacklist to the mod. I'm working on a modpack and they've become a nuisance in the end. After you kill the Ender Dragon and go through the portal the islands are covered in vampires! I love them, but they don't quite fit the scenery.

In case you need more info, or if this is unintended behavior:

Minecraft: 1.14.4
Forge: 28.1.110
Vampirism: 1.6.0 
Modpack: https://www.curseforge.com/minecraft/modpacks/chill-times

**Comment by maxanier** [comment]
Vampires in the end are definitively a bug. They should only spawn in the same biome as zombies.
