### ISSUE TITLE
[Bug] Cannot respawn when loaded alongside Angel of Vengeance

### ISSUE THREAD

**Issue by AryaRaiin** [TeamLapen/Vampirism#577]
## Versions
- Minecraft: 1.14.4
- Forge: 28.1.115
- Vampirism: 1.6.0-alpha+20200113-1207
- Angel of Vengeance 0.13.2

## Issue Description
When Vampirism is loaded in a modpack with Angel of Vengeance the player is unable to respawn.

## Reproduce Steps

1) Create a Forge modpack with Vampirism and Angel of Vengeance.
2) Create a new world, kill the player, and attempt to respawn

## Additional Information
This is not an issue with 1.6.0-alpha+20191210-0113, but found with the latest updates between 1/1/20 and 1/13/20.

Let me know if you believe I should file a separate report for [AoV](https://github.com/Tamaized/AoV/issues) to check out.

The log when attempting to respawn: https://pastebin.com/7nXwX1gb

**Comment by maxanier** [comment]
I think this is an issue in AoV: https://github.com/Tamaized/AoV/issues/146

**Comment by maxanier** [comment]
As AoV does not seem to be supported atm. I had another look, and thought of a potential workaround. Maybe this will prevent the crash

**Comment by maxanier** [comment]
Fixed in AoV
