### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Scubasteave** [TeamLapen/Vampirism#578]
## Versions
- Minecraft:1.12.2                    
- Forge:                       
- Vampirism:1.5.7                                             

## Issue Description
I can bite mobs for damage as normal,but on the other hand I can't fill bottle's with blood or drink blood at all

**Comment by maxanier** [comment]
We need some morre information do be able to do anything. Can you provide us with the `.minecraft/logs/debug.log` right after you tried to drink blood. Thank you

**Comment by lunofe** [comment]
Just in case, do you know that you need to keep pressing the key in order to get blood?

**Comment by lunofe** [comment]
Closing this now because there hasn't been an answer in the last 15 days
