### ISSUE TITLE
[Bug] Crash upon eating human hearth and cheat mode on max level cannot be activated. (In 1.14)

### ISSUE THREAD

**Issue by varappdev** [TeamLapen/Vampirism#579]
## Versions
- Minecraft:            1.14.4        
- Forge:            28.1.116           
- Vampirism:                             1.6.0-alpha+20200113-1207                

## Issue Description
I have eaten a human hearth in a singleplayer game and my minecraft instantly crashed. And also the cheat mode at max level does not work.

## Reproduce Steps
Number 1 (for human hearth crash):
1: Create a singleplayer world with creative mode active
2: Grab a human hearth from the creative inventory or through the give command
3: Go in survival
4: Eat it
5: Poof

Number 2 (cheat mode not working):
1: Change the unlock_all_skills_at_max property to true in config
2: Enter or make a singleplayer world
3: give yourself max level using a command
4: You can see you have limited skill points in the skills tab

## Additional Information
[crash-2020-01-26_13.52.27-server.txt](https://github.com/TeamLapen/Vampirism/files/4113534/crash-2020-01-26_13.52.27-server.txt)

**Comment by maxanier** [comment]
Once you are level 14, it should always display "1 skill point left", but you can unlock as many as you want

**Comment by varappdev** [comment]
But what about the crash?

**Comment by maxanier** [comment]
The crash should be fixed in the latest version
