### ISSUE TITLE
Generate vampire flowers in vampire forest

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#58]
Currently red roses are generated instead of vampire orchids are generated in the vampire forest, since the forge mechanism does not does what it seems.
Either wait until Forge is fixed or implement a workaround.
Flower Generation: BiomeDecorator around line 200

**Comment by tonimark** [comment]
me too

**Comment by maxanier** [comment]
Solved by replacing the yellowFlowerGenerator in the biomes BiomeDecorator (on every call of decorate, don't now why setting it in the constructor is not enought)
