### ISSUE TITLE
[Feature] Stackable blood bottles

### ISSUE THREAD

**Issue by Shines113** [TeamLapen/Vampirism#581]
## What would you like to have changed or added to Vampirism
The ability for blood bottles, or at least _full_ blood bottles, to stack.

## Does this make the mod experience more balanced?
I think so. While gearing up for a long trip, having food items take up several inventory slots is downright painful.

**Comment by maxanier** [comment]
You should be able to break (full) blood containers to carry them around.
But maybe some other way couldn't hurt.

Main issue is the interaction with stacked blood bottles. Either you cannot drink from blood bottles while they are stacked or the rest of the stack will be pushed somewhere else in the inventory or even dropped on the ground. Both options are not great

**Comment by Shines113** [comment]
I see. I didn't realize about the blood container, that helps some.

**Comment by cenodis** [comment]
I think it would help if we could fill the blood container like blood bottles, by keeping it in the hotbar and sucking blood. Right now you basically have to carry bottles + container around even though the bottles are almost never used. We can already drink blood from the container directly so this would alleviate the issue of taking multiple slots for food.
