### ISSUE TITLE
Vampirism Heartstriker 99%

### ISSUE THREAD

**Issue by EscapingSierra** [TeamLapen/Vampirism#583]
## Versions
- Minecraft:  1.12.2                  
- Forge:  14.23.5.2847                     
- Vampirism:  "Vampirism-1.12.2-1.5.7.jar"                                           

## Issue Description
Heartstriker sword from vampirism is not leveling past 99%. Weapon is fully charged with blood and repaired completely, spent over an hour fighting mobs now and has not changed. Not sure if there is another stage, if this is max, or if there is an issue. 

## Reproduce Steps
Created heartstriker, leveled to 99% training - no further progress

**Comment by maxanier** [comment]
As far as I remember this is kind of intended.
The training curve is asymptotical, so it will get very close to 100%, but will never reach exactly 100%.
It shouldn't make a difference gameplay wise as the damage difference is negligible, but I agree this is confusing. 

I will have a look how to improve that. (Maybe just round up the displayed value)
