### ISSUE TITLE
[Bug] crashes when lauching. game suggests a lower res size? 

### ISSUE THREAD

**Issue by Dover2** [TeamLapen/Vampirism#585]
## Versions
- Minecraft: 1.12.2
[crash-2020-02-09_01.09.51-client.txt](https://github.com/TeamLapen/Vampirism/files/4176649/crash-2020-02-09_01.09.51-client.txt)

           
- Forge:release 1.12.2-forge1.12.2-12.23.5.2847                      
- Vampirism: Vampirism-1.12.2-1.5.7.jar                                            

## Reproduce Steps launch minecraft with this forge installment and with the Vampirism-1.12.2-1.5.7.jar in the mod folder, it is the only mod that is in the mod folder

 look in attached files ( i put the **same file twice by accident**. They are both the same crash)

**Comment by Dover2** [comment]
problem resolved due to a lack of patience on my end

**Comment by Dover2** [comment]
issue is back.

**Comment by maxanier** [comment]
Are you using a texture pack?

**Comment by Dover2** [comment]
No, there is no texture pack. Just this mod is In with the forge installation

**Comment by Dover2** [comment]
Ok so this now has less to do with the mod and more just my MC, I will re install and see if I can play the mod afterwards.

**Comment by maxanier** [comment]
As far as I can tell from the crash report, it is indeed unlikely that Vampirism is the cause, it is probably merely triggering the issue. Any other large mod might cause the same issue.

I have noticed you are running a very outdated version of java 8. Maybe you could try updating that.

**Comment by Dover2** [comment]
Thank you for the consideration, I'll try to update java, it started working after I restarted my computer and re-installed mc along with forge and the vampirism mod. However I wont take the risks with an old java version, and will make sure java is up to date. I appreciate your work with this in- depth mod and hope to see future releases.
