### ISSUE TITLE
[Bug] Sucking blood

### ISSUE THREAD

**Issue by Glenndiscord** [TeamLapen/Vampirism#586]
## Versions
- Minecraft: 1.12.2                   
- Forge:  forge-14.23.5.2847                     
- Vampirism:1.5.7                                             

## Issue Description
I cant suck blood from any mob, rebound the key to multiple different ones edited the config only tried vanilla mobs i dont know what else i could be doing wrong

## Reproduce Steps
No clue i just cant suck blood

**Comment by lunofe** [comment]
Just in case, did you press and hold the key? It was changed to that a couple versions ago.

**Comment by Glenndiscord** [comment]
Just tried that after you said that and it worked thanks
