### ISSUE TITLE
[Bug] [1.14.4] Invisible Vampire Cows/Sheeps/Pigs 

### ISSUE THREAD

**Issue by JellyJYSK** [TeamLapen/Vampirism#587]
## Versions
- Minecraft: 1.14.4                
- Forge: forge-28.2.0               
- Vampirism: Vampirism-1.14.4-1.6.0-alpha+20200129-2311                            

## Issue Description
If you convert a pig, sheep, or cow, they turn invisible and just get a very long nametag. 

## Reproduce Steps
Convert a pig, sheep, or cow

## Additional Information
![2020-02-09_15 34 36](https://user-images.githubusercontent.com/54335787/74109485-d10dd400-4b51-11ea-9b51-d5feab6d0809.png)

This is a pig.

**Comment by maxanier** [comment]
How exactly did you convert the pig? From the screenshot it seems like you still have sanguinare vampiris suggesting you are not a vampire yet

I tried reproducing this, but for me the entities render properly

**Comment by JellyJYSK** [comment]
@maxanier 

The models are now rendering properly, but the nametags are still crazy long. xd
I didn't convert the pig in the photo. My world had corrupted so I had to become a vampire all over again and found a pig naturally spawned (or perhaps converted by another vampire?) in the Vampire Forest.

**Comment by maxanier** [comment]
Is this still an issue? And are you using any additional mods that might affect this?

**Comment by JellyJYSK** [comment]
This seemed to fix itself in one of the other 1.14.4 version. I haven't had
this issue in quite some time.
