### ISSUE TITLE
[Bug] [1.14.4] Vampire Hunters with Crossbows Can't Deal Damage

### ISSUE THREAD

**Issue by JellyJYSK** [TeamLapen/Vampirism#588]
## Versions
- Minecraft: 1.14.4          
- Forge: forge-28.2.0                     
- Vampirism: Vampirism-1.14.4-1.6.0-alpha+20200129-2311                                             

## Issue Description
Vampire Hunters with crossbows as their main weapon cannot deal damage and do not even attempt to. They stand around and do nothing.

## Reproduce Steps
Spawn a hunter with a crossbow. I'm not sure if this is the case with regular vampires, but I do know
they do not hurt the player character if they happen to be a vampire.

## Additional Information
[![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/cBs1iLz2BQY/0.jpg)](http://www.youtube.com/watch?v=cBs1iLz2BQY)

**Comment by maxanier** [comment]
Thank you for reporting. Should be fixed in the latest alpha
