### ISSUE TITLE
Unable to gain hunter level 2[Bug]

### ISSUE THREAD

**Issue by Beaustromswastaken** [TeamLapen/Vampirism#590]
## Versions 1.12.2
- Minecraft:     1.12.2            
- Forge:    14.23.5.2836                   
- Vampirism:     Vampirism-1.12.2-1.5.7.jar                                        

On the vampirism public server I have just injected myself with garlic. I have the vamp blood and everything for level 2 but the trainer still says I am too low level for him to train me.

No idea how to reproduce

**Comment by maxanier** [comment]
You have too talk to a normal hunter.
Hunter trainers are only required, for level 5 and higher.

Note to me: Maybe improve feedback message

**Comment by lunofe** [comment]
Not sure if you need to change the message, the guidebook is explaining the leveling process pretty good.
