### ISSUE TITLE
[MALEWARE LINK on your curseforge site]

### ISSUE THREAD

**Issue by globallog** [TeamLapen/Vampirism#592]
the link on your site:

https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire

to the texturepack:
https://www.curseforge.com/linkout?remoteUrl=http%253a%252f%252fgedankenspiel.me%252fgaming%252fvampirism%252f

is pointing to some malware siteredirecting to two sites, then comes a "detecting virus" / phishing site in directly browser

**Comment by Cheaterpaul** [comment]
@maxanier change to https://chimute.org/vampirism-patch/

**Comment by maxanier** [comment]
Thank you for reporting.
Has been updated.
