### ISSUE TITLE
[Bug] Fire Resistance Potions

### ISSUE THREAD

**Issue by JellyJYSK** [TeamLapen/Vampirism#596]
## Versions
- Minecraft: 1.14.4                 
- Forge: 28.2.0                      
- Vampirism: Vampirism-1.14.4-1.6.0-alpha+20200214-0141.jar                                             

## Issue Description
I'm not sure if it's 100% the Vampirism mod, but I believe it to be. I used a fire resistance potion and I still take damage when I'm on fire. Not sure if this was intentional or a feature or not even caused by the mod.  

## Reproduce Steps
Drink a potion of fire resistance and BUUUURRRN.

## Additional Information

![2020-02-16_14 08 07](https://user-images.githubusercontent.com/54335787/74610968-ec369180-50c5-11ea-9d4a-4f8c0e296c87.png)

**Comment by JellyJYSK** [comment]
Again, not completely sure, but it was the only thing I could think of that would do this.

**Comment by maxanier** [comment]
This is intended behavior. Vampires are very vulnerable to fire.
The fire resistance potion does decrease the damage though.

Not sure if this is a actually good idea balance wise though

**Comment by McKitten** [comment]
Complete protection for a modifiable % of time would make things easier; especially given what I remember of the vamp progression line and its available buffs.
