### ISSUE TITLE
[Feature] Vampire Bite Block Nullifier

### ISSUE THREAD

**Issue by PendragonII** [TeamLapen/Vampirism#597]
## What would you like to have changed or added to Vampirism
Garlic Diffusers are able to disable some Vampire abilities such as bat mode, this issue requests a block that disables Vampires' biting ability for a selected region.

When the block is placed, Vampires in the local region will not be able to bite any entities - including villagers and blood containers - but should be able to continue to drink blood bottles.

The requested block will be incredibly useful for Minecraft Servers, and should be a creative-only block.

## Does this make the mod experience more balanced?
Yes, for server creators and administrators.

**Comment by lunofe** [comment]
Or, instead of a block, a permission node → #207

**Comment by maxanier** [comment]
There should be a "vampirism.bite.feed" node. However, I am not sure if this affects feeding from blood containers as well

**Comment by Cheaterpaul** [comment]
the node exists but never used @maxanier
