### ISSUE TITLE
Blood bottle does not work in Multiplayer

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#6]
The blood bottle fill mechanism doesnt work in multiplayer:
If someone host a local server, the shift right-click action only works if the host is pressing shift.
That is probably caused by using Keyboard.isKeyDown which is not available on the server respectivly checks the servers keyboard. It probably has to be implemented with packages

**Comment by wildbill22** [comment]
Not sure what you mean by "implemented with packages". Do you mean network packets?
BTW, I got the code for the shift key detection off of forge.net, but that doesn't mean it is correct.
I want to be able to test this, but don't have the correct Server Configuration. Any idea what that is?

**Comment by maxanier** [comment]
Yeah, I meant packets. But I came up with an easier way (Did not test it though): You could just check player.isSneaking() instead of Keyboard.isDown, since the sneaking state should be synched automaticly.

For the right server configuration, create a new Run Configuration: Project: Minecraft Forge, Main class:cpw.mods.fml.relauncher.ServerLaunchWrapper, vm-arguments: -Dfml.ignoreInvalidMinecraftCertificates=true -Dfml.coreMods.load=de.teamlapen.vampirism.coremod.VampirismFMLLoadingPlugin. Then add the vampirism project to the user entries under classpath.
But the server doesnt work atm anyway, I still have to fix it, see issue #7 .

**Comment by wildbill22** [comment]
Check in d2ed81b8c855d2aa6c24e205cad0097a72887e26 fixes this.
