### ISSUE TITLE
[Feature] Position options for inventory Skills button

### ISSUE THREAD

**Issue by Teibidh** [TeamLapen/Vampirism#603]
## What would you like to have changed or added to Vampirism
Please add an option to re-position the Skills button in the inventory button. This overlaps with other mod buttons. The other mods it is overlapping with do allow for re-positioning, but I would have to space them out around the Vampirism Skills button making their grouping (otherwise by mod) awkward.

## Does this make the mod experience more balanced?
No change to balance.

## Can you provide additional resources (etc. textures or models)
Quark is a good example of the button overlap if you want to try it out.

**Comment by maxanier** [comment]
Good point.
For now you should be able to deactivate the button entirely in the (client) configuration. You can still access the skill menu using the assigned hotkey.
