### ISSUE TITLE
[Bug] 1.15.2 Ticking Enity Crash // Vampire Hunter Skins are nightmare fuel

### ISSUE THREAD

**Issue by MLMII** [TeamLapen/Vampirism#604]
## Versions
- Minecraft:  1.15.2                  
- Forge:  31.1.16                     
- Vampirism:   1.15.2-1.6.0-alpha+20200223-1524  
[crash-2020-02-25_18.54.34-server.txt](https://github.com/TeamLapen/Vampirism/files/4253045/crash-2020-02-25_18.54.34-server.txt)
                                         

## Issue Description

I was flying around in creative mode and looked at a Vampire Expert Villager when the game crashed.

Also the skins for Vampire Hunters are messed up.

## Reproduce Steps

I looked at a Vampire Expert Villager while flying in creative.

## Additional Information
[crash-2020-02-25_18.54.34-server.txt](https://github.com/TeamLapen/Vampirism/files/4253046/crash-2020-02-25_18.54.34-server.txt)

**Comment by maxanier** [comment]
@Cheaterpaul
The `Predicate<PointOfInterestType>` must not be null. https://github.com/TeamLapen/Vampirism/blob/48043463af8b2f09c2d1098c114ac683da05827b/src/main/java/de/teamlapen/vampirism/core/ModVillage.java#L44

Do we need to do something special here or should be just use the other constructor which creates a simple predicate.

**Comment by Cheaterpaul** [comment]
i assume the other constructor should be the way to go
