### ISSUE TITLE
[Bug] Vampire villagers have no trades

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#609]
Yet to be confirmed

**Comment by Cheaterpaul** [comment]
vampire expert or default villager? But can't confirm either.

**Comment by maxanier** [comment]
Vampire expert I think.
Do normal villagers even have trades in 1.14/15 anymore?
I think I have tried to interact with some, but nothing happened

**Comment by Cheaterpaul** [comment]
they must have been assigned a profession (not longer the default brown skin), to have trades

**Comment by maxanier** [comment]
alright, then I am gonna close this since you have tested both
