### ISSUE TITLE
[Bug] 1.15 Rendering is unfinshed/buggy

### ISSUE THREAD

**Issue by Ashtar084** [TeamLapen/Vampirism#611]
## Versions
- Minecraft:       1.15.2                
- Forge:             31.1.0 recomended              
- Vampirism:     1.6.0-alpha+20200228-0048                                 

## Issue Description

I think you guys already know, when I become a vampire, my char's head is all black and shows nothing on his face. and some vampire hunters also have the same bug. 

sorry if there was already this post but I didn't find it then I created this sorry again. 

but it’s not stopping me from playing. I'm playing the mod quiet
and thank you very much this mod and wonderful I love vampires and I'm a fan of Castlevania

## Reproduce Steps

when becoming a vampire, and going to vampire hunters' camps everyone has a black head.

**Comment by maxanier** [comment]
Yes. Rendering is still messy in 1.15

**Comment by Ashtar084** [comment]
alright thanks for responding quickly

:D

**Comment by Ashtar084** [comment]
TKS 4 help

**Comment by maxanier** [comment]
Gonna keep this open as a reminder and for other people to find. Still haven't found the time to work on rendering yet

**Comment by Cheaterpaul** [comment]
~~potted vampire orchid texture is not see through~~

**Comment by maxanier** [comment]
Almost done.
Missing: 
- Blood vision
- ~~Vampire face overlay does not "crouch with you" and using two layer skins it might turn black~~

**Comment by maxanier** [comment]
Should be complete with beta.3
