### ISSUE TITLE
[Bug] Eyes and fangs

### ISSUE THREAD

**Issue by pfediukina** [TeamLapen/Vampirism#612]
## Versions
- Minecraft: 1.14.4                 
- Forge: 1.14.4 (TLauncher)               
- Vampirism: 1.14.4-1.6.0-beta.1                                         

when i use /vampirism eye only fangs changes ( from 0 to 7). If i write 8...25  no result
Command /vampirism fang(s) does not exist.

Add /vampirism fangs and review the implementation of /vampirism eye

I'm sorry for my bad english.

**Comment by lunofe** [comment]
> Forge: 1.14.4 (TLauncher)

That is not a correct Forge version. It should look like this: _1.14.4 - 28.2.0_


> fangs changes ( from 0 to 7). If i write 8...25 no result

There are currently "only" 8 fang types, so anything beyond 7 won't work.

**Comment by maxanier** [comment]
Commands had the same name :see_no_evil: 
Thank you for reporting
