### ISSUE TITLE
Vampirsm replaces Minecraft Vanilla book "Infinity" 

### ISSUE THREAD

**Issue by RebornSerenity** [TeamLapen/Vampirism#613]
## Versions
- Minecraft:       1.12.2             
- Forge:              14.23.5.2826 
- Vampirism:         1.5.7                                    

## Issue Description
The minecraft book, Infinity, is replaced by Vampirism in the game. It makes it so the infnity book does not work at all, when you enchant an item, for instance, a bow, it takes arrows and won't shoot if you have none left. it will always take your last arrow. 

## Reproduce Steps
Get Vampirsm 1.5.7 and the MC /Forge version talked about, put them in game, it should override your vanilla book and NEI claims it is vampiriism that is taking over the book ID - it will not work as intended, for vanilla minecraft "infinity" to work.

**Comment by lunofe** [comment]
![GIF](https://user-images.githubusercontent.com/42828197/75612851-bd89d380-5b27-11ea-9399-cc315c76cbc6.gif)
Couldn't reproduce.
Vampirism isn't replacing the vanilla infinity enchantment, it's creating an additional one.

**Comment by RebornSerenity** [comment]
it is doing it for us, idk how to create a 'gif' like that but I'll show you in game what it says for us

**Comment by RebornSerenity** [comment]
![image](https://user-images.githubusercontent.com/3333378/75639041-bb854a80-5be3-11ea-9cb9-252aae9f2803.png)

**Comment by RebornSerenity** [comment]
![image](https://user-images.githubusercontent.com/3333378/75639072-dbb50980-5be3-11ea-97be-bf25a1eab317.png)

**Comment by RebornSerenity** [comment]
![image](https://user-images.githubusercontent.com/3333378/75639084-ecfe1600-5be3-11ea-92ee-8997de22cb57.png)

**Comment by maxanier** [comment]
Can confirm. For some reason NEI/JEI cannot differtiate between the two books.
But as Zin showed both books still exist. As a workaround you can use creative mode to get the vanilla book (if you are already using NEI cheat mode anyway).

Won't be fixed in 1.12 as not supported anymore. But will work in 1.14+

**Comment by RebornSerenity** [comment]
Ohh !!! thank you! That makes sense! You solved a huge problem we were confused about.
