### ISSUE TITLE
Debug Log Spam

### ISSUE THREAD

**Issue by KittenKoder** [TeamLapen/Vampirism#616]
## Versions
- Minecraft:                    1.14.4
- Forge:                       28.2.0
- Vampirism:                                             1.6.0

## The debug log being spammed makes it impossible to play so this is a bug as it causes huge issues. You need to include a setting to switch it off in the config or disable before uploading it.

Simply running it for 2 minutes generates a debug log of 1 mb, spammed with "calculated blood ..." messages. I want to love this mod, because it's one of the best ideas for MC ever, but this needs to be corrected as it will actually cause the game to freeze.

**Comment by maxanier** [comment]
Can you elaborate on you setup? Is this single player or multiplayer (and if so is the log on client side or server side?)
Furthermore can you include either a full log or at least an extract with the relevant lines. And are the lines always the same or similar or always different?

As a workaround you can turn of the dynamic calculation for now:
In the vampirism server config which is located in your world/save directory turn off `autoCalculateEntityBlood`

**Comment by KittenKoder** [comment]
None of that matters, spamming the any log that much is going to cause severe problems and crashes. I turned off the setting but it will make the mod extremely imbalanced in the server forcing me to remove it from the pack and find a replacement.

Never spam the logs for a released program of any sort, it also breaks hard drives and generates massive files for no reason. All you have to do is not spam the log during a routine process.

Also, the full log is too big to upload, FYI, and it's all from Vampirism.

**Comment by Cheaterpaul** [comment]
> Furthermore can you include either a ~~full log~~ or at least an extract with the relevant lines. And are the lines always the same or similar or always different?

**Comment by maxanier** [comment]
a) The message is not designed to be spammed, that is (part of) the bug/problem
b) Turning off this setting does by no mean break the balancing of the mod. It wasn't even existent until recently. It just makes Vampirism work nicer with other mods
c) Could you pls answer my questions, and provide an extract from the log. Otherwise I have no way of identifying and fixing the bug.

**Comment by maxanier** [comment]
If you are not interested in solving this problem. Why did you even bother creating it

**Comment by maxanier** [comment]
If anyone else is having this problem and willing to help, please open a new issue.
