### ISSUE TITLE
[Bug] [1.15] Blood Vision freezes the game

### ISSUE THREAD

**Issue by biteymcstabface** [TeamLapen/Vampirism#618]
## Versions
- Minecraft:                    1.15.2
- Forge:                          1.15.2 - 31.1.1
- Vampirism:                    1.15.2-1.6.0-alpha+20200228-0048
                         

## Issue Description
I play this mod on a server, and whenever I press the button to turn on Blood Vision, my game stops responding. It doesn't crash, and there is no log, it just stops responding and does not return to normal.

## Reproduce Steps
unlock blood vision, press the vision key (default N) to turn it on

**Comment by maxanier** [comment]
Thx for reporting will be fixed in the next alpha
