### ISSUE TITLE
[Bug] /vampirism eye command changes not eye but fang

### ISSUE THREAD

**Issue by Cywohoy** [TeamLapen/Vampirism#619]
## Versions
- Minecraft: 1.14.4                   
- Forge: forge-1.14.4-28.2.3                      
- Vampirism: Vampirism-1.14.4-1.6.0-beta.1                                            

## Issue Description
/vampirism eye <1-15> changes not eye but fang.

## Reproduce Steps
command /vampirism eye 1-6

**Comment by Cheaterpaul** [comment]
This is resolved with #612 and updated with the next release.
