### ISSUE TITLE
[Feature] Enchantment descriptions in-game

### ISSUE THREAD

**Issue by CritLoren** [TeamLapen/Vampirism#624]
## What would you like to have changed or added to Vampirism
Vampire enchantments descriptions in-game (via vampire.______.desc)

## Does this make the mod experience more balanced?
It makes the enchantments readable in-game

**Comment by maxanier** [comment]
I am not sure which mod displays the enchantment descriptions.
If you let me know the exact translation key that is displayed in game for one of Vampirism's enchantments, I can add them

**Comment by CritLoren** [comment]
I think vampire.vampire_killer.desc is one of the mentioned ones, take a look at https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions
Also, the enchantment names seem to show as their enchantment codes, not actual names.
