### ISSUE TITLE
[Bug] Too few hunter are spawning.

### ISSUE THREAD

**Issue by ghost** [TeamLapen/Vampirism#625]
## Versions
- Minecraft: 1.12.2              
- Forge:14.23.5.2847                       
- Vampirism:  1.12.2-1.6.2                                           

## Issue Description
Too few hunter are spawning and too hard to find one. This make hunters life harder, training yourself like impossible. I found 1 hunter in 10000x10000 block

## Reproduce Steps 
Generate a world and play.

**Comment by maxanier** [comment]
As you already closed this I assume it is now working for you?
If not try modifying the according mod config. It is working for most other players apparently
