### ISSUE TITLE
[Feature] Add sanguinare antidote instead of milk bucket

### ISSUE THREAD

**Issue by ghost** [TeamLapen/Vampirism#626]
## What would you like to have changed or added to Vampirism
You are injecting garlic extract to become a vampire hunter. It only causes you to be immune to vampire venom, regardless of when your blood is sucked it heals. What if vampires couldn't suck your blood because of it or just use it as a venom neutralizer, which would be the only antidote to vampire venom, and use another way to become vampire hunter like bring a vampire tooth or soul.

## Does this make the mod experience more balanced?
I think so.

## Can you provide additional resources (etc. textures or models)
Not needed.

**Comment by maxanier** [comment]
Once a player has injected themselves with the garlic extract their blood should become poisonous to vampires. Have you noticed something contradictory? It's very well possible I have missed something.

Using the hunter blood as a venom neutralizer or as an additional way to become a hunter would be cool, but such small detail is not worth the effort imho

**Comment by ghost** [comment]
Im not meant that way, but that is something too.

**Comment by ghost** [comment]
I mean the garlic serum would be the only antidote, and create an another way to become a hunter. Because now, you drik milk and thats all against vampire venom if you not a hunter. Would be awesome if, the hunters not be able to dodge this easily the venom, like they would infect, but they would craft an antidote what just a hunter can do.
Or, create a vampire venom neutralizer serum from garlic and some herb what's in the mod, or what's not yet. And yeah these are little things, but little things make mods more better. 
Like you make some vampire curse, or this antidote, or some structure for vampire like a castle, for hunter like a hunter scool or something. Maybe you can make a dungeon, full of vampire or a hunter base (as the dungeon, just for vampire player) with boss hunter/vampire. You can do a lots of thing with this mod.

**Comment by ghost** [comment]
Hello!
