### ISSUE TITLE
[Feature] Vampires can eat raw meats

### ISSUE THREAD

**Issue by Cywohoy** [TeamLapen/Vampirism#627]
## What would you like to have changed or added to Vampirism
Vampire players can eat raw meats to fill the blood bar.

## Does this make the mod experience more balanced?
I think so.

## Can you provide additional resources (etc. textures or models)
not needed

**Comment by maxanier** [comment]
You can use the blood grinder to extract the blood from the raw meat (and transfer it to a blood container).

One could argue, that it would make sense to directly consume raw meat as well, but that wouldn't fit the style of Vampirism.
