### ISSUE TITLE
[Bug] [1.15.2-1.6.0] Cannot fill Blood Bottles when feeding after blood bar is full

### ISSUE THREAD

**Issue by sandalle** [TeamLapen/Vampirism#628]
## Versions
- Minecraft: 1.15.2
- Forge:  1.15.2-31.1.18
- Vampirism: 1.15.2-1.6.0-alpha+20200307-2118
- Dedicated server: Yes

Other mods:

1. AI-Improvements-1.15.2-0.3.0.jar
2. alchemistry-1.15.2-5.jar
3. alib-1.15.2-1.jar
4. Apotheosis-1.15.2-3.0.6.jar
5. AppleSkin-mc1.15.2-forge-1.0.13.jar
6. AutoRegLib-1.5-36.jar
7. BetterAdvancements-1.15.2-0.1.0.96.jar
8. betterwithminecolonies-1.15.2-1.15.16.jar
9. BiomesOPlenty-1.15.2-10.0.0.345-universal.jar
10. BonsaiTrees-2.1.2.6.jar
11. caelus-FORGE-1.15.2-2.0-beta1.jar
12. cc-tweaked-1.15.2-1.86.2.jar
13. chemlib-1.15.2-2.jar
14. ChunkNoGoByeBye-1.15.2-1.2.0.jar
15. ClickMachine-1.15.2-3.0.1.jar
16. ClothConfig2-2.0.jar
17. cofh_core-1.15.2-0.3.2b.jar
18. colytra-FORGE-1.15.2-3.0.jar
19. C.O.M.B.A.T-1.15.2-4.1.0.jar
20. comforts-FORGE-1.15.2-2.0.jar
21. corail_recycler-4.0.2-1.15.2.jar
22. corail_woodcutter-1.1.1-1.15.2.jar
23. craftingstation-3.0.5.jar
24. CraftTweaker-1.15.2-6.0.0.9.jar
25. Cucumber-1.15.2-3.0.1.jar
26. curios-FORGE-1.15.2-2.0.jar
27. Cyclic-1.15.2-0.1.11.jar
28. DefaultOptions_1.15.2-11.0.1.jar
29. Ding-1.15.1-1.1.0.jar
30. elevatorid-1.15.2-1.7.0.jar
31. EnderBags-1.15.1-5.0.0.jar
32. engineersdecor-1.15.2-1.0.19-b5.jar
33. engineerstools-1.15.2-1.0.6.jar
34. FarmingForBlockheads_1.15.2-6.1.0.jar
35. FastFurnace-1.15.1-3.0.0.jar
36. FastLeafDecay-v20.jar
37. FastWorkbench-1.15.1-3.0.0.jar
38. furniture-7.0.0-pre16-1.15.1.jar
39. Hwyla-forge-1.10.8-B72_1.15.2.jar
40. industrial-foregoing-1.15.2-2.2.1-f27c515.jar
41. inventorysorter-1.15.2-17.0.0.jar
42. ironchest-1.15.2-10.0.2.jar
43. jei-1.15.2-6.0.0.2.jar
44. journeymap-1.15.2-5.7.0beta1.jar
45. JRFTL [1.15.2]-1.1.jar
46. justenoughbeacons-1.2.jar
47. libnonymous-1.15.2-1.1.1.5.jar
48. LightOverlay-4.2.jar
49. mcjtylib-1.15-4.0.2-alpha.jar
50. mcw-bridges-1.0.4fix-mc1.15.2.jar
51. Mekanism-1.15.2-9.9.15.407.jar
52. MekanismGenerators-1.15.2-9.9.15.407.jar
53. MekanismTools-1.15.2-9.9.15.407.jar
54. minecolonies-0.10.716-RELEASE-universal.jar
55. moredragoneggs-1.0.jar
56. Morpheus-1.15.2-4.2.47.jar
57. MysticalAgradditions-1.15.2-3.0.0.jar
58. MysticalAgriculture-1.15.2-3.0.0.jar
59. NetherPortalFix_1.15.2-6.0.0.jar
60. noRecipeBook_v1.5.2formc1.15.2.jar
61. obfuscate-0.3.4-1.15.2.jar
62. OreExcavation-1.7.149.jar
63. PackingTape-1.15.2-0.9.5.jar
64. Patchouli-1.15.2-1.2-28.jar
65. Placebo-1.15.2-3.0.2.jar
66. ProjectE-1.15.2-PE1.0.2B.jar
67. ProjectExtended-1.15.2-1.1.0.jar
68. reap-1.12.2.jar
69. ReAuth-1.14-3.8.0.jar
70. refinedstorage-1.8.1.jar
71. refinedstorageaddons-0.6.1.jar
72. rftoolsbase-1.15-1.0.0-alpha.jar
73. rftoolsbuilder-1.15-2.0.0-alpha.jar
74. rftoolspower-1.15-2.0.1-alpha.jar
75. rftoolsstorage-1.15-1.0.2-alpha.jar
76. rftoolsutility-1.15-2.0.0-alpha.jar
77. SolarFluxReborn-1.15.2-15.0.0.jar
78. StorageDrawers-1.15.2-7.0.2.jar
79. structurize-0.10.272-ALPHA.jar
80. swingthroughgrass-1.15.2-1.4.0.jar
81. tanknull-1.8.jar
82. theoneprobe-1.15-2.0.1.jar
83. titanium-1.15.2-2.3.6.jar
84. ToastControl-1.15.2-3.0.1.jar
85. tombstone-4.2.4-1.15.2.jar
86. torchmaster-2.1.1-rc0.jar
87. travel_bag-1.0.8-1.15.1.jar
88. VampiresNeedUmbrellas-1.15.2-1.0.jar
89. Vampirism-1.15.2-1.6.0-alpha+20200307-2118.jar
90. vehicle-mod-0.43.0-1.15.2.jar
91. Waystones_1.15.2-6.0.0.jar
92. WitherSkeletonTweaks-1.15.1-4.0.0.jar

## Issue Description
After using the Altar of Inspiration to get my Vampire to level 2, I (and no one else, so this may be unrelated) are able to fill our Blood Bottles with extra blood after feeding from a vanilla cow. My blood pool (bar) is full, I have an empty Blood Bottle (and extra vanilla Glass Bottles in my inventory which turn into Blood Bottles when I put them in my hotbar) in my hotbar. Blood briefly shows up in the Blood Bottle and then immediately disappears.

I ran `/vampire-test runTests` (or whatever the command is called) and got teleported to a room with a monster and a full Blood Container (I forget the name) full of Vampirism blood. I took this container back home and was able to fill Blood Bottles from this container then fill the Altar of Inspiration and reach level 3 (another player was also able to reach level 2).

## Reproduce Steps
This is my first time using the mod...so not sure how to reproduce. I'll try setting up another world and try to minimize the mod list to reproduce.

## Additional Information
No crashes nor entries in logs/latest.log nor logs/debug.log when I attempt to fill the Blood Bottle.

**Comment by sandalle** [comment]
Hrm...I cannot seem to replicate this with the same mods on a new world (single player or dedicated server with multi player). Not sure how I got into this state. If you want, I can provide a ZIP of my world.

**Comment by maxanier** [comment]
If it is still bugged in the old world and you could provide me with both world and mod directory, I could try to reproduce this.

Otherwise I will try to extend logging in the related code areas to simplify debugging if this should happen again.

You mentioned you checked the log files. Did you check the server or the client ones?
From your description it sounds like everything is working fine on your client, but the server does something strange

**Comment by sandalle** [comment]
[Here's a copy of my server folder](https://drive.google.com/open?id=17EVtRTMQE6cvdR8hKwjiqfOebjBDE1th) minus some JSONs so you can just start it up and test. :) Sorry about the delay. I didn't check the client logs, just the server logs.

**Comment by sandalle** [comment]
Sad news, happened again on the new world. Seems to happen after some time playing (we were playing for a few hours, but vampires for maybe 30 minutes). Let me know if there's anything you'd like me to do or try. :)

We fed from vanilla horses, pigs, sheep, lamas, and cows, with the same effect. When we fed from vanilla villagers, I noticed that the Vampirism Blood Bottle _did_ fill up if I fed fast enough from a creature that provides more blood per feeding (e.g. villager), and then the bottle drains itself (my blood pool was already full). So it's not an immediate drain.

**Comment by maxanier** [comment]
Thank you for the server files. I will investigate this when I have enough time

**Comment by maxanier** [comment]
Still not sure what is causing this. Could not reproduce this yet.

Can you try the latest alpha? There is a small change to blood bottles that might help.

If not can you try the following: Block your entire inventory (with cobble or so) and have a stack (2 or more) glass bottles on your hot bar and no blood bottles at all. When feeding the glass bottles should be dropped and filled with blood.

**Comment by sandalle** [comment]
Thank you @maxanier ! I tested **Vampirism-1.15.2-1.6.0-alpha+20200312-1042** on my server and I was able to fill Blood Bottles again without issue and without trying any inventory tricks. :)

**Comment by maxanier** [comment]
Then this was probably related to #634 . Apparently there are mods that automatically repair things and "repaired" the blood bottles.
If this issue should occur again, let me know.

**Comment by sandalle** [comment]
Oh, yes! I had the **Repair Talisman** from [Project E](https://www.curseforge.com/minecraft/mc-mods/projecte) . :)
