### ISSUE TITLE
[Bug]Can't insert end brick to altar pillars

### ISSUE THREAD

**Issue by Cywohoy** [TeamLapen/Vampirism#632]
## Versions
- Minecraft: 1.14.4                    
- Forge: 28.2.3                       
- Vampirism: Vampirism-1.14.4-1.6.0-beta.2                                             

## Issue Description
can't insert end brick to altar pillars
also there isn't any block state "end brick".

## Reproduce Steps
right-click on altar pillars using end brick

**Comment by maxanier** [comment]
The level 15 "easter egg" is exclusive to MC 1.12 and won't be implemented in new version as an entirely different system is planned.

Therefore, the end bricks are not required
