### ISSUE TITLE
[bug?] none "norepair" blood bottles

### ISSUE THREAD

**Issue by inbguy** [TeamLapen/Vampirism#634]
## Versions
- Minecraft:                    1.15.2
- Forge:                       forge-31.1.18
- Vampirism:                                             Vampirism-1.15.2-1.6.0-alpha+20200307-2118

## Issue Description
Mods that allow repairing items in your inventory attempt to repair the blood bottle, emptying it because of how the blood level is stored. 

## Reproduce Steps
Just install an item repair mod, fill a bottle and watch the magic happen. 

## Additional Information
From what I understood it can be fixed by adding a "norepair" tag to the item, it might be worth looking at

I don't know if this is a big enough issue to be worked on and it might be just because this is an alpha version but thanks for listening anyways!

**Comment by Cheaterpaul** [comment]
@maxanier probably modifying the ItemProperties of the BloodBottle with #setNoRepair() should be enough

**Comment by maxanier** [comment]
Thank you for reporting and investigating.
Can you try the latest alpha and let me know if this is still an issue?

**Comment by inbguy** [comment]
That fixed it, thank you so much! <3
