### ISSUE TITLE
[Bug] Hunters on 1.15 have rendering issues.

### ISSUE THREAD

**Issue by Sunconure11** [TeamLapen/Vampirism#637]
![Screenshot 2020-03-13 16 27 33](https://user-images.githubusercontent.com/5614902/76657198-aa273100-6547-11ea-8f60-c192b54f2914.png)

**Comment by maxanier** [comment]
Yes, the rendering is still buggy in 1.15 unfortunately. There should be an occasional note about this when loading a world. 
Closing this as it is included in #611

**Comment by maxanier** [comment]
should be resolved in the latest alpha btw
