### ISSUE TITLE
[Bug] lag

### ISSUE THREAD

**Issue by blairwilson** [TeamLapen/Vampirism#638]
## Versions
- Minecraft: 1.12.2
- Forge:         2847              
- Vampirism:                                       1.6.2      

## Issue Description
lag onBlockPlaced event 

https://github.com/TeamLapen/Vampirism/blob/23d6ee6f827e5f3e6db6b6e99f0ce193e4cc0011/src/main/java/de/teamlapen/vampirism/player/ModPlayerEventHandler.java#L102

https://imgur.com/1pcsXkQ

**Comment by maxanier** [comment]
Can you describe the issue a little bit more detailed?
Is this permanent lag or does it spike sometimes or only occur when many players are online or on a specific world  and what other mods are you running.

And can you provide the full profile
