### ISSUE TITLE
[Bug] 1.15 Vampire Coffins do not work, and blood doesnt render in containers

### ISSUE THREAD

**Issue by Inonedn** [TeamLapen/Vampirism#642]

**Comment by maxanier** [comment]
What do you mean with coffins don't work? And which version are you using. Make sure to use the latest alpha.

Blood rendering will eventually be fixed

**Comment by Inonedn** [comment]
Coffins do not change the time to night

**Comment by maxanier** [comment]
Ok, I can confirm this, it only happens if you sleep in the very early morning hour.
Fixed in next version
