### ISSUE TITLE
[Bug] [1.15.2] Garlic does not grow

### ISSUE THREAD

**Issue by sandalle** [TeamLapen/Vampirism#644]
## Versions
- Minecraft: 1.15.2
- Forge: 1.15.2-forge-31.1.25
- Vampirism: 1.15.2-1.6.0-alpha+20200315-2007

## Issue Description
Garlic does not grow, so we only have a limited amount of garlic in the world.

## Reproduce Steps
Find garlic in a village.
Break the garlic (left-click; if you have one of the harvest mods, e.g. [Reap Mod](https://www.curseforge.com/minecraft/mc-mods/reap-mod), these don't work with garlic), you only get one garlic. You either consume this garlic or plant it, but then you still only have the one garlic.
Mods like [HWYLA](https://www.curseforge.com/minecraft/mc-mods/hwyla) report "Growth: 0%" even after real-time days of the world running and the chunk loaded.

## Additional Information
Should act more like vanilla potatoes, breaking gives you 2+ returned potatoes so you may re-plant one and have a net gain in your potato supply. :)

**Comment by Cheaterpaul** [comment]
Thx for reporting.

We missed to enable the random ticking (growing of the garlic) for 1.14 & 1.15. should be working in the next alpha.

And then the garlic should drop the appropriate amount of garlic on destroy.

**Comment by maxanier** [comment]
Bonemeal might work as a workaround until the next release. (Not tested)

**Comment by sandalle** [comment]
Vanilla bonemeal (and other fertilizers, e.g. Mystical Agriculture's Fertilized Essence) triggers garlic growth, thank you. :)
