### ISSUE TITLE
Barons won’t spawn

### ISSUE THREAD

**Issue by cfernandez734** [TeamLapen/Vampirism#645]
## Versions
- Minecraft: 1.15.2                   
- Forge: 31.1.19                      
- Vampirism: 1.6.0                                            

## Issue Description

Vampire Barons aren’t spawning so I’m unable to progress further in the mod. I search the vampire biome every night but I can never find any. Am I missing something?

**Comment by maxanier** [comment]
Thanks for reporting. I messed something up.
Fixed alpha uploading right now
