### ISSUE TITLE
[1.12.2] crash after capturing the village

### ISSUE THREAD

**Issue by A-So-Nya** [TeamLapen/Vampirism#646]
## Versions
- Minecraft: 1.12.2                   
- Forge: 14.23.5.2847                      
- Vampirism: 1.6.2                                            

## Issue Description
I get crashes upon loading the world after capturing the village as vampire

## Reproduce Steps
1) Capture the village as a vampire

## Additional Information
crash-reports:
1) https://pastebin.com/bjg7mecd
2) https://pastebin.com/jKqpj6Tp

**Comment by maxanier** [comment]
There appears to be some other mod messing with things.
This should not be able to happen in theory and I can also not reproduce it with just Vampirism. So there most likely is a strange coremod.

Are you using a public modpack or a private one?

**Comment by A-So-Nya** [comment]
It's just my own modpack from mods i wanted to use
Checked with just vampirism and tickdynamics which i thought could be the issue, but also couldn't reproduce the crash

**Comment by maxanier** [comment]
Can you check if "/vampirism-test makeVillagerAgressive" also crashes the game?

If so you can use this to check potential mods.
I had a quick glance at the core mods used, but not all of them are open source.
My main suspects:
- Performant
- Born in a barn
- DynamicSurroundings
- phospor
- vanillafix
- surge
- CreativeCore

**Comment by A-So-Nya** [comment]
/vampirism-test makeVillagerAgressive doesn't force crash
But i loaded into superflat world with:

born in a barn
creative core
perfomant
phosphor
surge
vampirism & vampirism integrations
vanillafix

and game crashed just the moment i saw a village
here's crash-report https://pastebin.com/99z2wzhh
will try to find out which one of those mods actually crashes the game

**Comment by A-So-Nya** [comment]
it's perfomant
https://pastebin.com/QEYuCPMu
Game crashes with just perfomant and vampirism & vampirism integrations

**Comment by A-So-Nya** [comment]
oh
it's updated 4 hours ago
will check if it's still crashing with new version

**Comment by A-So-Nya** [comment]
yes, it's still crashing
probably need to report it to them
https://pastebin.com/FGaZfNR3

**Comment by A-So-Nya** [comment]
opened issue to him https://github.com/ldtteam/Performant/issues/15

**Comment by maxanier** [comment]
Apparently they already fixed it
