### ISSUE TITLE
[Feature] Allow for Toggable Night Vision

### ISSUE THREAD

**Issue by Zyian** [TeamLapen/Vampirism#647]
## What would you like to have changed or added to Vampirism
The ability to bind regular night vision to the actions/skills wheel or bind it to a hot key, this helps with building for distinguishing if something is properly lit. This is mostly a quality of life change as having permanent can sometimes get in the way of building things.

## Does this make the mod experience more balanced?
N/A mostly quality of life

## Can you provide additional resources (etc. textures or models)
N/A

**Comment by maxanier** [comment]
This should already be possible. Default binding n

**Comment by Zyian** [comment]
Ah my bad, often hard to find controls with search.
