### ISSUE TITLE
[Feature] Remove campfires from jungles

### ISSUE THREAD

**Issue by mjlmjl888** [TeamLapen/Vampirism#648]
## What would you like to have changed or added to Vampirism
Remove hunter's campfires being spawned jungles.

## Does this make the mod experience more balanced?
No, but it is more immersive because it looks weird to have a fire burning in a jungle.

**Comment by Cheaterpaul** [comment]
Thx for reporting.

The jungle was blacklisted, but the blacklist did not work as intended.
Fixed in the next Beta.
