### ISSUE TITLE
[Wiki] Biteable creatures redirects to the main page

### ISSUE THREAD

**Issue by Arkandos** [TeamLapen/Vampirism#649]
https://github.com/TeamLapen/Vampirism/wiki/Biteable-Creatures redirects to the main page of the wiki.

**Comment by maxanier** [comment]
Thank you for reporting. This is now https://github.com/TeamLapen/Vampirism/wiki/Biteable-Creatures-Blood-Grinder
I have added a note to the old page and updated the other links
