### ISSUE TITLE
 word's error

### ISSUE THREAD

**Issue by tonimark** [TeamLapen/Vampirism#65]
bug:a lot of items and the chat have the pasword transfer error:
(tile.vampirism...)
examples:(items-blocks)
tile.vampirism.altarInspiration.name  >  altar of inspiration
item.vampirism.battleAxe.name         > hunter's battle axe
tile.vampirism.vampire_orhid.name   > vampire forest orhid (vampire's forest flower)
(chat)
text.vampirism.immune_to_sanguinare vampiris > ? (unknow)

**Comment by maxanier** [comment]
Thanks, I've added them.
