### ISSUE TITLE
[Bug] Vampire hunters not respawning? [NeedsInfo]

### ISSUE THREAD

**Issue by mafias21** [TeamLapen/Vampirism#650]
## Versions 1.15.2
- Minecraft:                    
- Forge:    forge-1.15.2-31.1.27                   
- Vampirism:   last one                                          

## Issue Description

Hunters Vampire not respawning i have found a lot of tends with 0 vampire hunters, is this a bug or do i need to change spawn rate in config? Cant find where is the spawn rate in the config file

**Comment by mafias21** [comment]
They spawned when i ran the server for the first time, but now they dont spawn anymore

Also theres no master vampire hunter in any village

**Comment by mafias21** [comment]
never mind i figured out you just had to wait a while around the tent to let them spawn. But now i cant find any advanced vampire anywhere theres only barons and average vampires.

**Comment by maxanier** [comment]
I did a quick test and can confirm that advanced vampire problem. However, if I ramp up the spawn chance, they spawn correctly.
The spawn chance did not change since 1.12 though, so I am not sure why they spawn so rarely.

I will increase the default spawn rate a little bit.

**Comment by mafias21** [comment]
Thanks, great mod but also great developer.

**Comment by maxanier** [comment]
I am very sorry, there actually was a bug.
Unfortunately, it only occurred if reloading the world before observing the tents. Therefore I failed to reproduce this.
Will be fixed with next version
