### ISSUE TITLE
[Bug] Can't feed

### ISSUE THREAD

**Issue by Ashwood327** [TeamLapen/Vampirism#652]
## Versions
- Minecraft:                    1.12.2
- Forge:                       1.12.2
- Vampirism:                                    1.12.2

## Issue Description
I have tried holding down the feeding button. I have tried simply pressing it. I have tried resetting my vampire level, I have tried leaving the server I'm on and rejoining. Despite all of these attempts to fix the issue, I cannot seem to feed on anything. Not players, not pigs, not sheep, not cows, and not villagers.

**Comment by maxanier** [comment]
The versions you provided are invalid.

Are you a vampire yet?
Does the vampire fang icon show?

Can you provide the client-latest log, after trying to feed. Thank you

**Comment by velxundussa** [comment]
I've got the same bug (I think) on the modpack "MC Eternal" version 1.3.5b.

Minecraft version: 1.12
Vampirism: 1.6.2

I can get the client-latest log if you still need it, where is it located?

Edit:
A clean restart of the game client seems to have fixed the issue, cannot reproduce anymore.

Edit 2:
It seems it actually comes back randomly after a bit of gameplay

**Comment by maxanier** [comment]
The log file location depends on the launcher you are using.
For the official launcher it's in `.minecraft/logs` https://minecraft.gamepedia.com/.minecraft
