### ISSUE TITLE
[Проблема] [1.14.4] В одиночном режиме нет ни одной деревни с домом тренера охотников, так же нет монумента, который показывает принадлежность деревни к той или иной фракции, лес тяжело найти, не видел ни одного данжа, не получается настройки мода открыть(но это может не в моде проблема). Как это исправить?

### ISSUE THREAD

**Issue by VADIM3435** [TeamLapen/Vampirism#655]
## Versions
- Minecraft:                    
- Forge:                       
- Vampirism:

**Comment by lunofe** [comment]
English translation:
> In single-player mode, there is not a single village with the house of a hunter’s trainer, nor is there a monument that shows the village’s belonging to a particular faction, it’s hard to find a forest, I haven’t seen a single dungeon, it’s impossible to open the mod’s settings (but this may not be a fashion problem ) How to fix it?

**Comment by lunofe** [comment]
@VADIM3435 Пожалуйста, говорите по-английски, чтобы мы могли вас правильно понять. _Please speak English so we can understand you correctly._

You need to provide your Forge and Vampirism version so we can actually help.

**Comment by VADIM3435** [comment]
[Problem] [1.14.4] in single-player mode, there is no village with a hunter trainer's house, there is also no monument that shows the village belonging to a particular faction, the forest is hard to find, I haven't seen any Danja, I can't open the mod settings(but this may not be a problem in fashion). How do I fix this? Do you understand now?

**Comment by lunofe** [comment]
You need to provide your Forge and Vampirism version so we can actually help.

**Comment by VADIM3435** [comment]
Forge 28.2.0  Vampirism-1.14.4-1.6.0-alpha+20200218-1132

**Comment by maxanier** [comment]
Please grab the latest version from the official download site: https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire/files/2915388

**Comment by VADIM3435** [comment]
у меня и так последняя версия 1.14.4 за 29 марта 2020 года, установленная с этого сайта
