### ISSUE TITLE
[Feature] Add support for Pam's HarvestCraft 2 - Crops

### ISSUE THREAD

**Issue by mjlmjl888** [TeamLapen/Vampirism#656]
## What would you like to have changed or added to Vampirism
Add support for [Pam's HarvestCraft 2 - Crops](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-crops).

## Does this make the mod experience more balanced?
It makes garlic easier to get.

**Comment by maxanier** [comment]
Can you elaborate what this means? I am not familiar with HarvestCraft

**Comment by mjlmjl888** [comment]
In HarvestCraft there is a garlic plant, what I am saying is that it would be nice if you could also use HarvestCraft's garlic too make the syringes and stuff.

**Comment by maxanier** [comment]
Alright, that should be possible.
TODO: Add garlic tag like https://github.com/MatrexsVigil/phc2crops/blob/master/src/main/resources/data/forge/tags/items/crops/garlic.json
and adjust recipes.
