### ISSUE TITLE
Vampire hunters not spawning 14.23.5.2847

### ISSUE THREAD

**Issue by Byronixus** [TeamLapen/Vampirism#657]
## Versions
- Minecraft: 14.23                   
- Forge:                       
- Vampirism:                                             

## Issue Description
Vampire hunter not spawning in second to latest update

## Reproduce Steps
just get unlucky on a multiplayer server (cannot be hosted to lan)

**Comment by maxanier** [comment]
I assume 14.23.5.2847 is the forge version, meaning this is mc 1.12.
Can you also provide the Vampirism version.
Also we probably need a server log file.
This usually works just fine so there must be some mod conflict or config issue in your instance.
