### ISSUE TITLE
[Feature] New vampire advancement

### ISSUE THREAD

**Issue by Dover2** [TeamLapen/Vampirism#658]
## What would you like to have changed or added to Vampirism
In reference to JoJo's bizarre adventure, as a vampire, freeze a vampire hunter and punch them to death before the freeze ends. this would be similar to how DIO, a vampire, stops time to punch his foes to death. the advancement name would have to be a quote from DIO, such as "Useless... Useless..." 
on a technical level, it would be best to be a high level vampire to have the freeze ability, you would likely have to use the vampire rage to do enough damage by punching in 6 seconds

## Does this make the mod experience more balanced?
just a fun reference to a series where people punch vampires and vampires stop time to throw fists.

## Can you provide additional resources (etc. textures or models)
no.

**Comment by maxanier** [comment]
Ensuring that the entire damage is dealt during the freeze duration would take some coding (and processing) effort, so that is probably not worth it.
However, we could use a simpler trigger, like killing them while they have the freeze effect.

**Comment by Dover2** [comment]
well that would be an easier way to code it for the time being, I'm fine with that. as for other things, such as the image used in the advancement menu, i would suggest an inverted minecraft clock to reference freezing to be like stopping time. also for the name of the advancement, here are a few names that fit the  reference. "Useless! Useless!" or "Bring time to a halt!" along with descriptions such as: "Approach a Ghost frozen in time with your fists" of course if you know any better references to JOJO's bizarre adventure that fit a vampire stopping time, then you can use something you think would suit it better
