### ISSUE TITLE
[Bug] (1.15.2) No Churches Spawning

### ISSUE THREAD

**Issue by Rixhephtos** [TeamLapen/Vampirism#659]
## Versions
- Minecraft: 1.15.2                 
- Forge: 31.1.43                      
- Vampirism:  Vampirism-1.15.2-1.6.0-alpha+20200329-0140                                          

## Issue Description 
I have spent over 5 hours searching for villages, found a ton, and not a single one has a church. I'm looking for an Altar of Cleansing- is there another way to get one? "Vampire Book" is uncraftable and I haven't found it anywhere, and I can't find any information on it.

## Additional Information 
Playing on a Singleplayer server with another person via LAN.

**Comment by Cheaterpaul** [comment]
Do you have some other mod installed that is adding village structures or something else?

**Comment by Rixhephtos** [comment]
Only other one I can think of is Bountiful. However, we ended up joining a server hosting the modpack we were playing on (The Endless Frontier),instead of playing it over LAN, and there was a church in a village there so it's not a pack thing. I'm going to hope we were just EXCEPTIONALLY unlucky on the single player world. I haven't tried another SP world though.

**Comment by maxanier** [comment]
The book should be found in loot chests, but it is rare.
I have added an additional recipe that allows crafting the altar without this expensive item.
Same recipe but with normal book and vampire fangs in the top left and right corner

**Comment by Rixhephtos** [comment]
Thank you, that's a brilliant idea. :) That way if someone gets bit by accident and can't find a church they're aren't SOL.

**Comment by Cheaterpaul** [comment]
closing this assuming this was just unlucky.
