### ISSUE TITLE
[1.9] Sanguinare Vampiris is not applied if attacked by vampires

### ISSUE THREAD

**Issue by tonimark** [TeamLapen/Vampirism#66]
the vampires attacks you a long time and won't poisson you with suignair vampiris effect ,
why it is possible ?

**Comment by maxanier** [comment]
I indeed forgot to implement that, thanks :)
Added [here](https://github.com/TeamLapen/Vampirism/commit/1b60c7420ba7dd0e2f86b62f14b00e0099a10c21)
