### ISSUE TITLE
No villages to complete the next level!

### ISSUE THREAD

**Issue by Bolenya** [TeamLapen/Vampirism#660]
- Minecraft:    1.7.10                
- Forge:                       
- Vampirism:                                             

So I am on a Regrowth Server meaning there are no villages. Without 3 villages to fly to, I cannot complete the level so we decided to use commands /vtest 9 which apparently should send me to level 9.. this did not work so please if anyone can provide guidance I would much appreciate it.

Be level 8 vampire, have no villages :(

None

**Comment by maxanier** [comment]
1.7.10 is not supported anymore and I actually cannot recall how the leveling system used to work. What do you need the villages for?
Command might be "/vampirism-test level 9"
