### ISSUE TITLE
[Bug] Sleeping in coffin does not skip the day time

### ISSUE THREAD

**Issue by Azumi0** [TeamLapen/Vampirism#661]
## Versions
- Minecraft: 1.15.2                    
- Forge: 31.1.36                      
- Vampirism: 1.6.0-alpha+20200329-0140                                            

## Issue Description
When my character uses the coffin during the day, the time skips to the beginning of next day, instead of skipping to the night.

## Reproduce Steps
Try sleeping in the coffin.

## Additional Information
We are playing on RAM modpack, version 0.3.0

**Comment by Cheaterpaul** [comment]
I cannot reproduce it. There was such bug in a previous version, but in this version this should be fixed.

Does the time get skipped to the next day at any time of the day ? or just in specific part of the day?

**Comment by Azumi0** [comment]
The bug occures when I lay to the coffin at any part of day. We are playing on dedicated server. I could send you params to connect to it if it would help.

**Comment by Cheaterpaul** [comment]
Can confirm this only with the modpack.

@maxanier 
It seem that Vampirism don't catch SleepFinishedTimeEvent.
Tested with custom jar that prints a log message in the event and EventPriority.Highest

**Comment by maxanier** [comment]
Maybe a different world handles the sleep cycle and does not throw the SleepFinishedTimeEvent.
Not sure what's the best way to find the offending mod, as the modpack looks pretty big

**Comment by maxanier** [comment]
Maybe ~https://github.com/TheIllusiveC4/Comforts~ or ~https://gitlab.com/modding-legacy/Good-Night-Sleep~

**Comment by Azumi0** [comment]
Will you guys try to find a solution for that or should I post this as a bug to the modpack owner?

**Comment by maxanier** [comment]
Maybe they have an idea which other mod might be messing with the daytime/sleep process

**Comment by Darkere** [comment]
Can someone check if it's quark? Not seeing them calling the event. https://github.com/Vazkii/Quark/blob/f4c6d2914ff4b60f6404992729543d130af9f913/src/main/java/vazkii/quark/tweaks/module/ImprovedSleepingModule.java#L162

**Comment by maxanier** [comment]
@Darkere thanks you! Even though the event is fired in the blob you linked, quark is the offending mod. The event call was only added in r2.1-231, but RAM is still using r2.1-230.
https://github.com/Vazkii/Quark/issues/2036

Once RAM updates this should hopefully fix this

**Comment by Darkere** [comment]
Cool. We will hopefully be updating somewhat soon.

**Comment by Azumi0** [comment]
Thank you very much for the support guys! I'm waiting for the pack update then :)

**Comment by maxanier** [comment]
Closing this as it it is hopefully resolved.
Let me know if the issue should still exist with thee latest quark version
