### ISSUE TITLE
[Bug] Crash when unlocking nightvision

### ISSUE THREAD

**Issue by icthieves** [TeamLapen/Vampirism#663]
## Versions
Modpack: MC Eternal 1.3.5b
- Minecraft: 1.12.2                   
- Forge: 14.23.5.2847                      
- Vampirism:  1.6.2                                           

## Issue Description
This is likely an issue with a mod conflict in the MC Eternal modpack, however since I couldn't find any reference to the issue elsewhere, I thought i'd open an issue on Github.

When first unlocking Night Vision, the game will crash, and continue to instantly crash when the save is reloaded. The only fix is to disable the overlay in the Vampirism config (just disabling the nightvision replacement doesn't fix it.) Once the overlay is disable, the lighting appears to be fullbright.

## Reproduce Steps
1) Create an MC Eternal instance in MultiMC using MC Eternal version 1.3.5b
2) become a vampire and unlock nightvision

## Additional Information
Crash dump: https://paste.dimdev.org/jutavavugi.sql
I saved multiple crash logs, and all of them fail on the exact same line in getNightVisionBrightness

**Comment by maxanier** [comment]
I tried reproducing it, but everything works fine for me with that modpack.

This behavior is very odd, a crash should not be possible at that location unless there is a core mod changing things here. Do you know any mod that you used that might mess with night vision or render brightness?

About the overlay: Do you mean `disable_screen_overlay`? I honestly don't know how this can affect the crash in any way. Maybe it just randomly started working again after you changed that (or you changed something else at the same time (like `disable_replace_night_vision`)

**Comment by icthieves** [comment]
Well, I guess i've found a heisenbug, because today I can't recreate the issue.

Yesterday I re-created the issue 6 times by restarting my client, and disable_screen_overlay is the only option that remedied it (even with disable_replace_night_vision untouched).
Today, with no other changes to the MC instance, I haven't been able to trigger the issue again.

I'm closing the issue as I can no longer recreate the bug, and given that there's 290 mods in this pack, i'm not convinced there was a bug in Vampirism at all.

PS: I love Vampirism btw, I haven't had this much fun since I bought the game!

**Comment by maxanier** [comment]
Let us know if it should happen again and you can think of any mod that messed with night vision/brightness.
