### ISSUE TITLE
The cheat mode is broken [1.14.4]

### ISSUE THREAD

**Issue by varappdev** [TeamLapen/Vampirism#664]
## Versions
- Minecraft: 1.14.4                    
- Forge:  28.2.4                     
- Vampirism: 1.6.0 beta 6                                             

## Issue Description
I have already reported this in the past but you did not believe me. The issue is that cheat mode is broken and you do not see the constant 1 skill point left when you have it enabled, you see 13 skill points until you use all of them and cannot unlock anything more.

## Reproduce Steps
Toggle cheat mode in configs
Enter a minecraft world and level up to max
You do not have the constant 1 skill points left.

## Additional Information
I have reported this in the past.

**Comment by Cheaterpaul** [comment]
Are you sure that you edited the config file in the world directory of the world you are playing in.
You can edit and saving the file while playing the world .

**Comment by varappdev** [comment]
Did not know that individual worlds can be configured now. The issue is fixed.
