### ISSUE TITLE
[Bug] Blood vision

### ISSUE THREAD

**Issue by WarmIceCream** [TeamLapen/Vampirism#665]
## Versions
- Minecraft: 1.15.2                    
- Forge: 31.1.27                      
- Vampirism: 1.6.0-alpha+20200329-0137                                            

## Issue
Blood vision and Garlic vision don't work correctly. I do not use Optifine as I've seen asked in other theads.

I'm well aware this has been reported in the past, but with the most recent post I could find being almost 2 years old I was wondering if there was anything I could to do resolve this?

## Reproduce Steps
I am running the mod in a modpack on a server with some friends. Here's a list of the mods in the modpack: 
- Appleskin
- Cucumber
- DimDungeons
- FastLeafDecay
- IronChest
- JEI
- JourneyMap
- LycanitesMobs
- MapperBase
- MCWBridges
- MoreOresInOne
- Morpheus
- MouseTweaks
- MysticalAgriculture
- Obfuscate
- PlayerFinder
- RoadStuff
- SwingThroughGrass
- _Vampirism_
- CrayFishVehicles

I have vision bound to _n_ and all blood vision seems to do is make my current vision blurry and blackout name tags. I cannot see entities through walls. I have posted some screenshots below if that offers any assistance

## Additional Information
![2020-04-15_01 03 29](https://user-images.githubusercontent.com/63678263/79285570-dd960c00-7eb5-11ea-8c49-cc8897466ac0.png)
![2020-04-15_01 03 37](https://user-images.githubusercontent.com/63678263/79285574-e25ac000-7eb5-11ea-9829-284d20461beb.png)
![2020-04-15_01 04 01](https://user-images.githubusercontent.com/63678263/79285578-e4bd1a00-7eb5-11ea-9f05-fae475208b8f.png)
![2020-04-15_01 04 10](https://user-images.githubusercontent.com/63678263/79285584-e7b80a80-7eb5-11ea-8388-af4bff8120ad.png)

**Comment by maxanier** [comment]
This seems different from the previously reported bugs.
The shaders appear to be working fine, it's just that the entities outlines are not rendered properly.

I will look into this when I have time

**Comment by maxanier** [comment]
Implemented with beta.3
