### ISSUE TITLE
[Bug] [Maybe] loot table issue

### ISSUE THREAD

**Issue by IchigoGames** [TeamLapen/Vampirism#666]
this is more of and ask but can you check to make sure your loot tables are set up right iv been having a issue in my pack with empty chests aka something braking the loot table but i have 182 mods so its going to to take time to find the cause but i did see this in console. it could just mean something blocked it not sure.

 [05:08:02] [Server thread/WARN] [de.te.va.VampirismMod/]: LootTables -------------------------------
>.... [05:08:02] [Server thread/WARN] [de.te.va.VampirismMod/]: LootTables Failed to inject all loottables
>.... [05:08:02] [Server thread/WARN] [de.te.va.VampirismMod/]: LootTables ------------------

Minecraft 1.15.2
forge 31.1.43
Vampirism-1.15.2-1.6.0-alpha+20200329-0140

**Comment by IchigoGames** [comment]
![2020-04-19_13 34 42](https://user-images.githubusercontent.com/11888162/79696501-b25b4600-8242-11ea-8c32-fbdf39b422be.png)
is this chest suppose to be empty btw test word im the only one on it and first time loading in and only a a few mods like bop and jei and journeymap

**Comment by IchigoGames** [comment]
i am looking into each mod in my pack to find out what mod is breaking the loot table and atm this is my top suspect

**Comment by IchigoGames** [comment]
this does rule out that there may be another mod preventing this mod from adding loot unless it dont work with bop that seems unlikely.

**Comment by IchigoGames** [comment]
![Capture](https://user-images.githubusercontent.com/11888162/79696715-074b8c00-8244-11ea-9cd6-14391a400d14.PNG)

**Comment by maxanier** [comment]
@Cheaterpaul does this fix the issue, including the loot table warning? shall I build a new alpha?

**Comment by Cheaterpaul** [comment]
No just the empty hunter trainer chest.

Regarding other empty chests & the error message: this is not made by vampirism, because the message get send if we try to add drops to existing loot tables and they do not exist

**Comment by maxanier** [comment]
Alright, to conclude:
The warning you shows is printed because the respective loot tables (probably something like mineshaft etc. Do not exist when Vampirism tries to add something to them, so they have to be removed by some other cause.
Maybe there is something wrong in a data pack or another mod.
I would expect to find some warning in the full log file.

Only the empty hunter trainer chest was caused by a bug in Vampirism
