### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Bepi2090** [TeamLapen/Vampirism#667]
## Versions
- Minecraft: 1.12.2                    
- Forge:2847                       
- Vampirism: Vampirism-1.12.2-1.6.2                                            

## Issue Description

I decided to put the vampire mode in the integrated bucket, thinking that it wouldn't be a big deal to use the plugin mode all at once. By the way, this vampire mod can't be up all night in the pipe, and even at night. What's wrong?
Is it a problem to put the plug-in? When I got a pebwa, I had a problem with the plugin.

## Reproduce Steps
I don't know this part either. It's a very fundamental issue.

## Additional Information

Not at all. I would like to present it even in the report of the collision. In other words, the report of the collision cannot properly speak from Ella.

**Comment by maxanier** [comment]
Alright, I have no idea what you are talking about

**Comment by lunofe** [comment]
I feel like this person tried to run Vampirism on Bukkit.

**Comment by maxanier** [comment]
That would explain at least some parts.
Still, one of the best bug reports I have seen lately ^^. Not.
I don't really know where to start, so I'm not gonna
