### ISSUE TITLE
[Bug] Inventory Wipe with Death in Bat Mode

### ISSUE THREAD

**Issue by Hydraheads** [TeamLapen/Vampirism#669]
## Versions
- Minecraft:  1.12                   
- Forge:  1.12.2 - 14.23.5.2847                       
- Vampirism:    1.6.2                                

## Issue Description
For some reason, there is an issue on my server where players who die in bat form lose their entire inventory. There is a possibility it is linked to the corpse complex mod which allows you to set things that are lost on death.

## Reproduce Steps
Run vampirism and corpse complex keepinventory module, unsure if keepinventory from vanilla also yields this result.

**Comment by maxanier** [comment]
Cannot reproduce neither standalone nor with corpse compex. Neither on 1.12 nor 1.14
