### ISSUE TITLE
[Bug] Barons don't spawn

### ISSUE THREAD

**Issue by ChapperNi** [TeamLapen/Vampirism#671]
## Versions
- Minecraft:  1.12
- Forge:  14.23.5.2847      
- Vampirism:  1.6.2                                         

Barons simply don't spawn in the vampire biome.

**Comment by Cheaterpaul** [comment]
The spawnrate of the barons is low, but it should work fine. (couldn't reproduce it)
Maybe there is a mod that is modifying something, but to find this out we need the log files.

**Comment by maxanier** [comment]
In 1.12 this is confirmed to work.
They might only spawn during night time though
