### ISSUE TITLE
[Bug] Garlic crop just drops the initial one garlic

### ISSUE THREAD

**Issue by McKitten** [TeamLapen/Vampirism#675]
- Minecraft: 1.14.4                   
- Forge:   28.2.3                    
- Vampirism: 1.6.0-beta.6                                            

Issue :
Vampirism Garlic does not reproduce.

To reproduce
Crops hit age 7 (100% according to overlay) and can be harvested but only produce the single garlic that is initially placed in the ground (which i had to creative in for testing purposes).

ADDITIONAL INFORMATION
I'd noticed this outside a Hunter Trainer hut which was in a desert village and went to my river biome home to test. Light 15 sky, 11 block. Height 64.

**Comment by Cheaterpaul** [comment]
For me it works as expected to produce 1-4 garlic items. Maybe just unlucky?

or do you use some mod/resourcepack that could modify the drops of blocks?

**Comment by McKitten** [comment]
> For me it works as expected to produce 1-4 garlic items. Maybe just unlucky?
> 
> or do you use some mod/resourcepack that could modify the drops of blocks?

This is part of a pack but has not specifically been modified with any loot table mod.
The garlic is in the same field as 2 food mods (pams & simple) and only just recently explorercraft; all of which are producing 1-4 as would be expected of the garlic. Forge data also prevents the other variants from being substituted in.
This is beyond unlucky; hence the error testing & report.

This is also in a multiplayer environment. I have not tested SP.
(i find it confusing that it changes things but sometimes it does see:farlanders)

**Comment by Cheaterpaul** [comment]
are you using a specific modpack or modlist? so i could try to reproduce it with all the mods or see were an error could occur.

**Comment by McKitten** [comment]
https://www.curseforge.com/minecraft/modpacks/minion-swarm
You might want to turn off bloomful tho, Seriously considering dumping it.

**Comment by Cheaterpaul** [comment]
unfortunately i can not reproduce the bug with a fresh installation of the modpack.

**Comment by McKitten** [comment]
I have semi-located the issue. 
I was able to gain multiple garlic when i had a gardening tool in my hand but open hand is still broken so I am inclined to think it has to do with the right click harvest changes employed by more than one of my other mods.

**Comment by maxanier** [comment]
The garlic code is almost identical to the vanilla carrots or potato code. Therefore, I also don't know what is causing this. Does harvesting potatoes with your bare hand work?

With the next Vampirism version, garlic at least from pam harvestcraft should be interchangeable

**Comment by McKitten** [comment]
Potatoes work well, carrots nearly as well, beets are a little trickier. I have no idea why there is a ratio difference between them but between potatoes & beets it is nearly 4:1

MatrexVigil is actually the late to the food mods party, even the work she has done is incomplete and is only really saved by how annoying XLFood mod is - even after a re-write. She needs an assistant or something :s
The once unknown Simple Farming (enemeez1) seems to be the winner with my user base.

**Comment by maxanier** [comment]
As it seems to be some other mod causing issues here this is probably difficult to debug.
Since apparently, it works with a gardening tool, you should have some way to farm garlic, so this isn't a big problem.
Do you have just one or multiple farming related mods installed?

**Comment by McKitten** [comment]
I started with simple farming which predated any vampirism releases; added Pam's recently but this has been a bug since the beginning and was fixed when you added the compatibility.

Not sure what has caused it but it is no longer an issue.
