### ISSUE TITLE
MC Eternal: Level 6 vampire with no water damage unlocked but taking sun Damage underneath glass when holding an umbrella [Bug]

### ISSUE THREAD

**Issue by arniehayes** [TeamLapen/Vampirism#676]
## Versions
- Minecraft: 1.12.2                    
- Forge: Latest MC Eternal                      
- Vampirism: 1.6.2                                            

## Issue Description
I placed some ineffable glass underwater which is visible to the sun and I am taking sun damage when i stand under the glass even when holding an umbrella.

**Comment by arniehayes** [comment]
https://youtu.be/DKs62ksEBzM
Here's video proof as well

**Comment by maxanier** [comment]
Do you take sundamage below the water without the umbrella?

**Comment by arniehayes** [comment]
Yes, I even changed the glass and it still happens. And it only happens when after i move through ineffable glass and then stand under any glass underwater. the umbrella just doesn't work

**Comment by maxanier** [comment]
Regarding sundamage below water in general:

If you are below 4 water blocks, you should not take any sundamage at all.
However, for performance reasons this works only in certain situations.
1) You have to be below sea level
2) The water must start at sea level and the 4 water blocks must be right below (so basically blocks 64-60 must be water

Regarding the umbrella:
This is an issue with VampireNeedUmbrellas, it is kind of related to https://github.com/Focamacho/VampiresNeedUmbrellas/issues/2

**Comment by maxanier** [comment]
You are below sea level, right?
Maybe you can thicken the water layer, so you don't even need the umbrella

**Comment by maxanier** [comment]
The umbrella related problem has been fixed in VampireNeedUmbrellas
