### ISSUE TITLE
[Feature(?)] 1.12.2 Compatibility with the Enchantment Descriptions mod (Vampire Slayer, Infinity, & Arrow Frugality)

### ISSUE THREAD

**Issue by WolfBV** [TeamLapen/Vampirism#682]
## What would you like to have changed or added to Vampirism

Support to be added for the Enchantment Descriptions mod

Link to the mod: https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions

## Does this make the mod experience more balanced?

No.

## Can you provide additional resources (etc. textures or models)

![Screen Shot 2020-05-06 at 3 22 02 PM](https://user-images.githubusercontent.com/47493126/81234443-99c28e00-8fad-11ea-9b81-126650df5e5f.png)
![Screen Shot 2020-05-06 at 3 22 11 PM](https://user-images.githubusercontent.com/47493126/81234448-9b8c5180-8fad-11ea-9eb0-1b8d35e46344.png)
![Screen Shot 2020-05-06 at 3 24 23 PM](https://user-images.githubusercontent.com/47493126/81234495-b5c62f80-8fad-11ea-8ef6-b17110eaf928.png)

**Comment by maxanier** [comment]
Won't be introduced for 1.12 as it isn't supported anymore.
I already added it for newer version, but apparently messed up the strings.
