### ISSUE TITLE
[Feature] Bettere config, command and permission documentation

### ISSUE THREAD

**Issue by JonesiBlitz** [TeamLapen/Vampirism#683]
## What would you like to have changed or added to Vampirism
Better documentation on config options, any permissions, and any commands.
A clear option for option description would be useful for servers going through setup. 

## Does this make the mod experience more balanced?
Not Applicable

## Can you provide additional resources (etc. textures or models)
Not Applicable

**Comment by maxanier** [comment]
I have tried updating and extending the wiki regarding these things.
Is there anything specific that was unclear to you?
