### ISSUE TITLE
[Feature] Playermodel customization GUI

### ISSUE THREAD

**Issue by lunofe** [TeamLapen/Vampirism#684]
Currently, the only way to change the appearance of your fangs & eyes (as a Vampire obviously) is to use `/vampirism fang <0-6>` and `/vampirism eye <0-15>`. It's working, but not really an ideal way and players often don't know about new styles. So, maybe a customization GUI would be a great addition and could perhaps be added to the skill GUI. Here's a concept art:
![gui1](https://user-images.githubusercontent.com/42828197/81504613-8e8f9b00-92ea-11ea-8ab2-331d0756667c.jpg)
![gui2](https://user-images.githubusercontent.com/42828197/81504617-92232200-92ea-11ea-8707-7a67f03249d6.jpg)
![gui3](https://user-images.githubusercontent.com/42828197/81504619-93ece580-92ea-11ea-9927-35e7beadc2c5.jpg)

**Comment by Cheaterpaul** [comment]
that is a good idea. i will look into it, but i think this is easy straightforward possible.

**Comment by Cheaterpaul** [comment]
added with b5e9e6671403cb520ab13818cab2a828729e3260
