### ISSUE TITLE
Replace vampirism infinity enchanment

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#685]
Remove the vampirism infinity enchantment and use the vanilla one using `Item#canApply` and `Item#canApplyAtEnchantmenttable`

While we are at it, also look into arrows, are there vanilla crossbow arrows now, do the vanilla arrows have to be different from the Vampirism crossbow ones?

**Comment by Cheaterpaul** [comment]
about the arrows: at the moment the crossbow arrows costs one iron and stick and the arrows flint,stick,feather.
