### ISSUE TITLE
Crash upon launch

### ISSUE THREAD

**Issue by HazardMoonshine** [TeamLapen/Vampirism#686]
## Versions
- Minecraft: 1.14.4                   
- Forge: 28.2.0                      
- Vampirism: 1.6.1                                            

## Issue Description 
I get a error upon launch "Vampirism (vampirism) encountered an error during the common_setup event phase"

## Reproduce 
Steps Just launched the game with a semi large mod list

## Additional Information
[latest.log](https://github.com/TeamLapen/Vampirism/files/4607229/latest.log)

**Comment by maxanier** [comment]
Sorry about that. A fixed version has been uploaded
