### ISSUE TITLE
[Bug] Hunters not re-spawning in server

### ISSUE THREAD

**Issue by DavidGodinho** [TeamLapen/Vampirism#689]
## Versions
- Minecraft: 1.15.2                    
- Forge: 1.15.2 - 31.1.77                       
- Vampirism: 1.15.2-1.6.0-beta.1                                             

## Issue Description
Vampire Hunters do not respawn in their tents. No tampering has been done to the tents.

## Reproduce Steps
I am running a lot of mods in this server, namely:
- AdFinders-1.15.2-4.0.5.0-build.0020
- AI-Improvements-1.15.2-0.3.0
- Akashic Tome 1.3- 13
- AutoRegLib-1.5-40
- BiomesOPlenty 10.0.0.345-universal
- Botania r1.15-383
- Clumps-5.0.2
- CosmeticArmorReworked-1.15.2-v3a
- curios-FORGE-1.15.2-2.0.2.2
- FastLeafDecay-v22
- FluxNetworks-1.15.2-5.0.1-2
- ForgeEndertech-1.15.2-6.0.3.0-build.0036
- industrial-foregoing-1.15.2-2.3.0-6f57752
- jei-1.15.2-6.0.0.4
- jeiintegration_1.15.2-3.1.0
- JustEnoughResources-1.15.2-0.10.1.77
- Mekanism-1.15.2-9.10.4.417
- MekanismAdditions-1.15.2-9.10.4.417
- MekanismGenerators-1.15.2-9.10.4.417
- minecolonies-0.11.937-ALPHA-universal
- Morpheus-1.15.2-4.2.50
- Morph-o-Tool-1.3-23
- OreExcavation-1.7.151
- Patchouli-1.15.2-1.2-33
- QuarkOddities-1.15.2
- Quark-r2.1-235
- refinedstorage-1.8.3
- Reliquary-1.15.2-1.3.4.995
- SereneSeasons-1.15.2-3.0.0.69-universal
- StorageDrawers-1.15.2-7.0.2
- structurize-0.10.314-ALPHA
- swingthroughgrass-1.15.2-1.4.0
- titanium-1.15.2-2.4.0
- tombstone-4.3.5-1.15.2
- Trapcraft-1.15.2-2.7.0
- VampiresNeedUmbrellas-1.15.2-1.2
- Vampirism-1.15.2-1.6.0-beta.1
- Waystones_1.15.2-6.0.1

## Additional Information
Here is my Latest And Debug Logs
[latest.log](https://github.com/TeamLapen/Vampirism/files/4628074/latest.log)
[debug.log](https://github.com/TeamLapen/Vampirism/files/4628088/debug.log)

I have tried to run the command to kill all hunters, since I read somewhere there was a hunter cap, and it killed all entities in the world.

**Comment by DavidGodinho** [comment]
My friends say that after the first few vampire hunter spawns, they arent spawning at all even on new chunks.

**Comment by maxanier** [comment]
Confirmed. Happens after reloading the world (once)
