### ISSUE TITLE
1.15 [Bug] Excess blood doesnt continue to fill blood bottles

### ISSUE THREAD

**Issue by Inonedn** [TeamLapen/Vampirism#697]

**Comment by maxanier** [comment]
Can you describe this in more detail?
The blood bottles have to be on your hotbar while feeding

**Comment by Inonedn** [comment]
they are, and they dont fill, only by one stage

**Comment by maxanier** [comment]
Maybe provide a log file, or a modpack, or any further information

Cannot reproduce
