### ISSUE TITLE
I can't find garlic :P

### ISSUE THREAD

**Issue by TrevelMad** [TeamLapen/Vampirism#70]
There's a lot of Vampire Hunters in the village in my world but I can't seem to find any garlic so I can become a vampire hunter I just read it in the thing that you can become a vampire hunter but I can't find any garlic please help ;)

**Comment by maxanier** [comment]
Have you checked in multiple villages? There is a about 50% chance for a Hunter Trainer to spawn in a village. You can find garlic outside of his house
