### ISSUE TITLE
[Feature] Add config for fire damage for vampires

### ISSUE THREAD

**Issue by Inonedn** [TeamLapen/Vampirism#700]
Mind if you add a config of the fire damage? it makes exploring the nether almost impossible and does WAY too much damage

**Comment by maxanier** [comment]
In `world/serverconfig/vampirism-balance.toml` there already is `vpFireVulnerabilityMod` which you can reduce to 0.1.

Also, don't forget to craft vanilla fire protection potions. They help a little

**Comment by maxanier** [comment]
Closing this as it is already available and there haven't been any further comments
