### ISSUE TITLE
Vampire Hunter Trainer House not spawning in villages [Bug]

### ISSUE THREAD

**Issue by ghost** [TeamLapen/Vampirism#703]
## Versions
- Minecraft: 1.14.4                   
- Forge: 28.2.6                      
- Vampirism: 1.6.2                                            

- ModPack: Fantastica

I have Vampirism in my modpack, Fantastica, but I have never seen a Village with a Trainer in it. Hunters and Vampires spawn as expected and camps are found around the world, but no Trainer Houses to become a Hunter.

Create a new world in Fantastica. You will load into a village. There will be no Trainer House. You can explore every village you come across, you will not find a Hunter Trainer.

**Comment by Cheaterpaul** [comment]
i could confirm it at first, but after removing quark and ruins and adding them again it works. Even so i think a mod is messing around with the locate command.

**Comment by maxanier** [comment]
Haven't heard any other reports of this, maybe it was fixed in another mod.

As a ugly workaround you can always quickly enable cheats and spawn one hunter
