### ISSUE TITLE
[Bug] Blood container does not accept impure blood

### ISSUE THREAD

**Issue by SayulilyonPipeDream** [TeamLapen/Vampirism#706]
## Versions: 
- Minecraft:  1.15.2                  
- Forge:           31.2.5            
- Vampirism:   1.6.0 Beta 2                                          

- ModPack: Modding Mining Madames (Custom Pack, available on Curse)
We are having trouble getting the blood grinder to work, We put all types raw meat (including vanilla, as we have VanillaFoodPantry). We place a blood tank underneath, but the gears aren't moving. Tried to apply a redstone source, nothing. Tried feeding it rF and Eu, still nothing.
We tried the full stack of Grinder, Tank, Sieve, then tank, but nothing moved.  

## Reproduce Steps
Try using the Blood grinder to grind Raw Beef or Raw Prokchops in it.
We are using VanillaFoodPantry, but the meat is Vanilla as best as I can tell.

## Additional Information
I love your mod!

**Comment by maxanier** [comment]
Works for me.
Can you try a human heart?
If that works, press f3+h to enable advanced tooltips, then check what id the vanilla food items have.
Should be something like `minecraft:beef`

**Comment by SayulilyonPipeDream** [comment]
I apologize for the delay.

I can confirm that it was Minecraft:Beef and that a human heart does nothing. I have a couple of screenshots to confirm as well as a picture of the set-up in question.

![2020-06-03_23 08 11](https://user-images.githubusercontent.com/39207553/83721356-c212cc00-a5ef-11ea-9b23-9ab481c13be8.png)
![2020-06-03_23 06 13](https://user-images.githubusercontent.com/39207553/83721358-c343f900-a5ef-11ea-870f-4005106cef1b.png)
![2020-06-03_23 07 30](https://user-images.githubusercontent.com/39207553/83721361-c343f900-a5ef-11ea-9581-844bd6252c23.png)

**Comment by maxanier** [comment]
Ah, I see, I messed up a little. The blood container currently does not accept impure blood.
As a workaround just place the grinder directly on top of the sieve for now.
Thank you for your help.

**Comment by SayulilyonPipeDream** [comment]
It worked! Thank you very much!

Side Note, could we get the gears to turn, or the machine to drip blood or make noise when it grinds the meat?

Thank you for your help!

**Comment by maxanier** [comment]
Original issue will be fixed with next release

Grinding gears might be a little bit overkill. I have added some sound effect, not perfect, but should be better than nothing
