### ISSUE TITLE
[Feature] Visualize/indicate feed progress

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#708]
## What would you like to have changed or added to Vampirism
Somehow indicate that feeding takes time and you have to hold down the button. 
It should become clear even if only tapping the button. 

## Does this make the mod experience more balanced?
New players have a hard time figuring out that the key has to be held down. 

## how 
Maybe use something similar to the weapon cool down indicator. Make sure to start the progress at maybe 10%

**Comment by McKitten** [comment]
Also a cool down timer (similar to the animal breeding ones) so they don't accidentally turn their food into new vamps.
