### ISSUE TITLE
Vampire forest won't spawn vampires and barons

### ISSUE THREAD

**Issue by fattyguy999** [TeamLapen/Vampirism#711]
## Versions
- Minecraft:1.12.2                 
- Forge:latest version 14.23.5.2854
- Vampirism:latest version on 1.12.2  1.6.2                      

The vampire forest in my modpack won't spawn any vampires and barons, but it will spawn vampire animals. I have 285 mods in this modpack so i can't make a mod list, please help me! I can't process the game if I can't find barons! Although I can trade with the villagers to process the game, but emeralds are so rare.Please help me, I really love this mod and I don't want to delete it.
## Issue Description
I also download Vampires need umbrella and vampirsm integration mod

## Reproduce Steps
Create a world, find a forest and you won't see any vampires and barons.

## Additional Information
Well my minecraft didn't crash, so I don't have a crash report.

**Comment by lunofe** [comment]
Can't reproduce. As you're using 285 other mods, it's very likely that Vampirism isn't the root of this issue. Please check if any of the other mods somehow manipulate the mob spawning of other mods, etc.

**Comment by Rayuraker** [comment]
Hey buddy, did you manage to fix this bug in the game? I'm having the same issue. I think you're also using the Vampirism mod along with Dawncraft.
