### ISSUE TITLE
[Bug] 1.15.2 Hunters cannot craft in Weapon Table

### ISSUE THREAD

**Issue by SayulilyonPipeDream** [TeamLapen/Vampirism#712]
## Versions
- Minecraft:         1.15.2           
- Forge:               31.2.8        
- Vampirism:      1.6.0 Beta 4                                       

- ModPack: Modded Mining Madames

## Issue Description
Hunters cannot craft crossbows in Hunter's weapon table.

## Reproduce Steps
Level Up Hunter until access to both Weapons Table and Crossbows
Attempt to craft crossbows in Weapons table, using JEI and hand placing items.
Fill the Weapons Table with Lava and attempt again
Take pictures for the Mod maker

## Additional Information

![](https://cdn.discordapp.com/attachments/702602978015838267/718897638686195761/unknown.png)

![](https://cdn.discordapp.com/attachments/702602978015838267/718897710404468807/unknown.png)

**Comment by maxanier** [comment]
![2020-06-15_19 35 39](https://user-images.githubusercontent.com/3747729/84688358-c06dd000-af2e-11ea-8682-29601d83545e.png)
Not sure where your recipe is coming from.
Should look like this.

**Comment by SayulilyonPipeDream** [comment]
How weird!
In JEI, the recipe shows this instead:
https://cdn.discordapp.com/attachments/709417172778352702/722551219800899724/unknown.png

**Comment by maxanier** [comment]
Apparently, this happens only in multiplayer, the recipes work as usual, but JEI, guide book and the recipe book show the wrong recipes.
I will look into this.
