### ISSUE TITLE
[Bug] Server and client sometimes freeze during creating a new world

### ISSUE THREAD

**Issue by Blugori** [TeamLapen/Vampirism#713]
## Versions
- Minecraft: 1.15.2                    
- Forge: 31.2.0                  
- Vampirism: Vampirism-1.15.2-1.6.0-beta.2                                            

- ModPack: my "own" modpack
issue description
The server crash when trying to create a world sometimes, minecraft freeze in singleplayer when trying to make a new world sometimes

reproduce steps
Create a new world (survival or server), and sometimes the percentage freeze and you have to leave the game.

[debug.log](https://github.com/TeamLapen/Vampirism/files/4772777/debug.log)

It might be due to an incompatibility between mods
(this is a log from the server)

**Comment by maxanier** [comment]
I don't think that Vampirism is the root cause for this, but maybe we can do something on our end

**Comment by maxanier** [comment]
Might be fix with the next beta version (probably released later today).
Report again if this still occurs
