### ISSUE TITLE
[Feature] Skip Sanguinare

### ISSUE THREAD

**Issue by XGaming0814** [TeamLapen/Vampirism#714]
Please make there be a way to skip the sanguinare vampiris and immediately become a vampire

**Comment by PendragonII** [comment]
If you have cheats enabled you should be able to do `/vampirism level vampire 1` to become a Vampire immediately.

**Comment by maxanier** [comment]
You can also reduce the average sanguinare duration by modifying `sanguinareAverageDuration` (1.14+, there is something similar in Balance->VampirePlayer for 1.12)
