### ISSUE TITLE
[Feature] Biome weights for 1.15

### ISSUE THREAD

**Issue by McKitten** [TeamLapen/Vampirism#716]
## What would you like to have changed or added to Vampirism
Just a line in the common config about biome weight

## Does this make the mod experience more balanced?
I just added a new mod that overpowered almost everything when it first spawned, but thankfully had biome weights in the config. If you could throw in a native but configurable weight of 5 or something it would be appreciated

## Backstory
The one that shocked me into checking had almost everything set at 6 and ruined my nice grasslands, made a village almost impassible and the only way i found it was it had a beacon from this mod :)

**Comment by Cheaterpaul** [comment]
this config option already exists in the balance config.

**Comment by McKitten** [comment]
there is no balance config for 1.15

**Comment by Cheaterpaul** [comment]
take a look at https://github.com/TeamLapen/Vampirism/wiki/Configuration

**Comment by McKitten** [comment]
That would require a world to be generated before it can be edited. 
Totally inappropriate placement.

**Comment by Cheaterpaul** [comment]
yes but apparently forge decided that this should be the way to go.

> If you want to change the world specific options before creating a world, either to change world-generation or to change it for all created worlds, you can use the defaultconfigs folder. It is located in your .minecraft or server directory. Copy a server or balance config from an existing world to this folder and change the values as desired. It will be used for new worlds.`

**Comment by McKitten** [comment]
How is it 'Oh The Biomes You'll Go' gets away with a .toml in the standard config folder then?

**Comment by Cheaterpaul** [comment]
yes it is possible to put that into a common config.

If your mod exists only from world generation features, i would recommend to do so.
But otherwise you must put 100+ config options into the common config that have nothing to do with the client.

But yes eventually the world gen options could be moved to the common config until forge gets the idea to generate the default server config files by itself.

(And i assume you already generated a world with the mod before you want too edit the config files)

**Comment by McKitten** [comment]
Yes but single player & multiplayer are slightly different in what is generated in that folder.
I have emptied the region & playerdata folders in an old save and uploaded to the server in a folder under the seed name - hoping it doesn't see the difference in naming between the two.

The default generation for Vampirism wasn't to bad on this one but i have some be 50% of biomes surrounding spawn and others where i have gone 5k before finding a tiny island. It might be worth making that github link more prominent, like curseforge; which is then (usually (except when you need it to)) copied to twitch. 

I really can't wait for FTB to come out with this new client they're apparently making.

**Comment by Cheaterpaul** [comment]
if i am correct it should be enough to copy the server/balance config to the `defaultconfigs` folder on the server (like you would do it for SP) and generate a new world.

(unfortunately forge does not supply much documentation above the basics for user and modder)
