### ISSUE TITLE
Just like, a list of the action ids, anywhere?[Feature]

### ISSUE THREAD

**Issue by AydenBurgers** [TeamLapen/Vampirism#717]
I honestly don't know how this _isn't_ a thing already, maybe I missed it on the wiki, but without any resource to say what the ids for skills are the command to bind actions to the 2 quick use keys is unusable. All the book, the help command, and the skills page on the wiki say to do is just type "action-id" as if i know what to type there. I've been sitting here for 5 minutes trying to just guess the id for the dark blood projectile because like, what else am I expected to do? 
Edit: I found that the wiki _does_ say to use autocomplete to see the ids, except...that doesn't work. Autocomplete isn't showing up for this command when I use it. I guess that makes this a bug, then? I don't know.

**Comment by Cheaterpaul** [comment]
If you are using minecraft 1.14+ that is possible with  /vampirism bind-action <1,2> and then the action ids should be shown. (1 or 2 depending on the quick button). It is also possible to press 1 or 2 when selecting an action in the action menu.
Not sure about 1.12

**Comment by maxanier** [comment]
I have added a list of actions to the "help" subcommand of "bind-action" in the latest 1.15 version.
However, the autocomplete should work well for 1.14+.
1.12 might be worse, but isn't supported anymore.

**Comment by maxanier** [comment]
![2020-06-29_14 39 55](https://user-images.githubusercontent.com/3747729/86006625-c58a4f00-ba05-11ea-8fd5-a8022f100e9c.png)
Here is an up-to-date list
