### ISSUE TITLE
Non [a-z0-9/._-] character in path of location: vampirism:castle_block_dark_brıck

### ISSUE THREAD

**Issue by YaprakDolmasi** [TeamLapen/Vampirism#718]
![Screenshot_1](https://user-images.githubusercontent.com/67419521/85714262-ed6e6f80-b6f2-11ea-95e5-a05db5af49e0.png)

- Minecraft: 1.15.2                    
- Forge: 1.15.2-forge-31.1.0                      
- Vampirism: 1.6.0

**Comment by Cheaterpaul** [comment]
We needs the log files to identify the problem.

Depending on you launcher they are located in your minecraft folder (.minecraft) in the subfolder `logs`. There you can find the `debug.log` file, which is needed.

**Comment by lunofe** [comment]
Couldn't reproduce. Startup and creating/joining a world worked just fine.
![image](https://user-images.githubusercontent.com/42828197/85728949-ab482c80-b6f8-11ea-80f5-9375eb0ef571.png)

**Comment by YaprakDolmasi** [comment]
@Cheaterpaul here [latest.log](https://github.com/TeamLapen/Vampirism/files/4831773/latest.log)

**Comment by Cheaterpaul** [comment]
yes the `ý` in `vampirism:castle_block_dark_brýck` isn't supposed to be there. But that shouldn't be possible at all. Only if you edited the jar somehow.

Have you tried to replace the vampirism jar with a new downloaded one from https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire ?

**Comment by YaprakDolmasi** [comment]
yes , still same error. i didnt edit any jar

**Comment by Cheaterpaul** [comment]
It is probably a bug with converting uppercase characters to lowercase and so changing `I` to `ý`

**Comment by Cheaterpaul** [comment]
should be fixed with the next release
