### ISSUE TITLE
[Bug] version 1.15.2-1.6.0 June 16 

### ISSUE THREAD

**Issue by Hotseaserpent** [TeamLapen/Vampirism#719]
## Versions
- Minecraft: 1.15.2                   
- Forge:     31.2.0                  
- Vampirism:       version 1.15.2-1.6.0 June 16                                      

- ModPack: N/A

## Issue Description 
When I try to use toggle bat mode it does not turn me into a bat. I use the r button and have changed to left click, restarted and reinstalled. Nothing works.

## Reproduce Steps
In vampire mode, Press P then press the settings wheel in the bottom left corner. Once the options wheel comes up and choose a skill. We choose the bat skill then press r or whatever key we have set in options. Nothing happens once we do that.

**Comment by lunofe** [comment]
Can't reproduce. Please make sure you're using unique keys for the actions in the controls.

![GIF](https://user-images.githubusercontent.com/42828197/85881592-23d4e900-b7de-11ea-9ea8-cfb05240a87a.gif)

**Comment by Hotseaserpent** [comment]
@1LiterZinalco yes the unique key was set to the "r" key to activate the skills. Pressing the r key no longer works. we have gone into the settings and switched the unique key and that still didn't work.

**Comment by Hotseaserpent** [comment]
![20200626_130457](https://user-images.githubusercontent.com/67473772/85882717-c9bc2f80-b7ad-11ea-9f21-b50a5b32f18a.jpg)

**Comment by Hotseaserpent** [comment]
![20200626_130504](https://user-images.githubusercontent.com/67473772/85882754-db053c00-b7ad-11ea-954b-4a48e9cd4a5b.jpg)

**Comment by Hotseaserpent** [comment]
@1LiterZinalco I tried to upload video pressing the unique key"r" and the skills not being activated

**Comment by lunofe** [comment]
Try this and check if the problem still exists:

1. Make sure neither R and Y are used by something else
2. Set "Use Actions" to R
3. Set "Toggle Action 1" to Y
4. Open the skill menu and click the settings wheel
5. Select the bat mode with your mouse and press Y while it's selected

**Comment by Hotseaserpent** [comment]
@1LiterZinalco that did it! They r was used for another command. Seems we could only set a limited amount of commands in option. It works perfectly. Thank you!
