### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Hotseaserpent** [TeamLapen/Vampirism#720]
## Versions
- Minecraft:    1.15.2                
- Forge:  31.2.0                
- Vampirism:   1.15.2-1.6.0                                          

- ModPack: N/A

## Issue Description
My son is a level 14 vampire and we want to know how he can get more skills points to unlock the remaining skills: Dark Blood projectile, avoided by creepers, blood charge, damage limiter, Vista, freeze, invisibility and teleport.
Everything I read online says level 15 is only on 1.12 and I don't see anything else about how to get more skills to unlock these.

**Comment by Cheaterpaul** [comment]
It is intended to only be able to unlock 14 skills , so you have to choose which one is best for you.

But there is a config option, which can be enabled to unlock every skill when reaching lvl 14.
This option is located in the server configuration called `allSkillsAtMaxLevel`. To find the config file take a look at https://github.com/TeamLapen/Vampirism/wiki/Configuration#114-and-newer

**Comment by Hotseaserpent** [comment]
Thanks a lot. How do I access those Vampirism files to insert the code? I went into the library from finder and to the .jar file for Vampirism but can't open that way.

**Comment by Cheaterpaul** [comment]
They are generated by Minecraft and not included in the vampirism.jar.

The server configuration (`vampirism-server.toml`) is located in the save file of the world (presumably `%appdata%/.minecraft/saves/<worldname>/serverconfig/vampirism-server.toml`, <worldname> must be the name of the world which is used)

**Comment by Hotseaserpent** [comment]
I think I am close lol. I found the vampirism-common.toml in Library>minecraft>config>vampirism-common.toml

**Comment by Cheaterpaul** [comment]
yes there is the client & common configurations. But the server side configuration is generated for every world.

Depending on the minecraft launcher the position can differ, but there should be a folder called `saves` in `Library>minecraft` and within directories for each world that were generated. But if not, you should find out (eg. google) where the saves folder is located for the specific minecraft launcher

**Comment by Hotseaserpent** [comment]
Found it! Library>app support>minecraft>saves>new world name>serverconfig 

Last question, I don't have an app to open it, can you suggest one?

**Comment by Cheaterpaul** [comment]
simple text editor is enough

**Comment by Hotseaserpent** [comment]
I am trying textedit on my mac now

**Comment by lunofe** [comment]
I'm assuming this has been sorted out in the meantime.

**Comment by Hotseaserpent** [comment]
@1LiterZinalco Not yet.

@Cheaterpaul  I used text editor and found the line of code:
allSkillsAtMaxLevel

It was a true/false statement set to false. I changed it to true and saved. I restarted the computer yet the skills still remain locked... Any ideas?

**Comment by lunofe** [comment]
@Cheaterpaul Could it be that the allSkillsAtMaxLevel option is only checked when unlocking lvl 14 therefore creating the need to change the option to true before reaching lvl 14?

**Comment by Cheaterpaul** [comment]
No this should work after a reload of the world. @Hotseaserpent make sure to edit the file in the right world directory. (There in no need to restart, just to exit and reload the minecraft world. And then a constant 1 should be displayed in the Skill Screen, which means you can enable all skills.

**Comment by Hotseaserpent** [comment]
Well that constant one be displayed where are the skills points value is
located? Thanks for all of your help

**Comment by Hotseaserpent** [comment]
It works!!!! Thanks a mil @Cheaterpaul 
![20200628_131750](https://user-images.githubusercontent.com/67473772/85953951-01f47700-b942-11ea-93dd-74be375becfb.jpg)
