### ISSUE TITLE
[1.16] Check how to modify village density

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#723]
Maybe this can be done in some vanilla way now

**Comment by Orange1861** [comment]
Could a config be made for players to adjust village density?

**Comment by Cheaterpaul** [comment]
that should already be possible in the server config under `server.village.villageDistance`/`server.village.villageSeparation`

**Comment by Orange1861** [comment]
Ah, that's why I couldn't find it, the server config didn't generate for me in the 1.16 version (even tho I ran the mod multiple times). Should I make a github issue on that?

**Comment by Cheaterpaul** [comment]
the server config is located inside the world directory. take a look at https://github.com/TeamLapen/Vampirism/wiki/Configuration
