### ISSUE TITLE
BetterWithMods/AppleCore Hardcore Hunger mechanic

### ISSUE THREAD

**Issue by AydenCadillac** [TeamLapen/Vampirism#725]
## Versions
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Vampirism: 1.6.2
- ModPack: N/A

## Issue Description
I'm playing with Better With Mods as one of my mods, and I have the AppleCore integration for the Hardcore Hunger mechanic (basically, saturation turns to "fat" and there are consequences to overeating). I'm also playing with Vampirism (and Vampirism Integrations, but I doubt that caused the following), but when I tried to transform into a vampire, the following happened:
- the blood bar doesn't replace the hunger bar
- sucking blood doesn't refill the hunger bar (likely just Vampirism mechanics or something)
- eating normal food does refill the hunger bar, but a full hunger bar won't regenerate health
- when you suck enough blood and start regenerating health, your hunger bar immediately depleted to about two meat pops and three fat pops (white outline)

## Reproduce Steps
- download BetterWithMods, AppleCore, Vampirism
- enable the HCHunger mechanic in BWM's config file
- run the game
- transform

**Comment by AydenCadillac** [comment]
I guess imma disable HCHunger, simple solution for the time being

**Comment by maxanier** [comment]
We don't work on Vampirism for MC 1.12 anymore and BetterWithMods is not available for newer versions. So closing this for now.
Luckily there is a workaround as you mentioned
