### ISSUE TITLE
[Bug] Spawned Vampires in Villages are killed by Village Iron Golems

### ISSUE THREAD

**Issue by Orange1861** [TeamLapen/Vampirism#741]
## Versions
- Minecraft: 1.16.1                    
- Forge: 1.16.1-32.0.71                      
- Vampirism: 1.16.1 Alpha                                            

- ModPack: N/A

## Issue Description

Vampires that spawn in vampire controlled village are immediately attacked and killed by the village iron golems. This means that this feature of the mod basically doesn't do anything since the vampires almost always lose to the golem.

## Reproduce Steps

Find a village with a vampire in it and watch it get killed by the iron golem.

**Comment by Cheaterpaul** [comment]
called with a wrong parameter.

is fixed in next version
