### ISSUE TITLE
coffin doesn't work during the day

### ISSUE THREAD

**Issue by Fidulus** [TeamLapen/Vampirism#743]
forge 32. 0. 70

I just became a vampire and placed down a coffin to sleep in. It's day, and when i right click it to sleep it only says : "You can only sleep at day"
But it is day...

**Comment by Cheaterpaul** [comment]
yes, forge missed a patch at the 1.16 update but as soon as [MinecraftForge#7005](https://github.com/MinecraftForge/MinecraftForge/pull/7005) is accepted it should work by itself with the new forge version

**Comment by Cheaterpaul** [comment]
should be fixed with forge version 32.0.86
