### ISSUE TITLE
[Bug] Vampire Hunters not spawning

### ISSUE THREAD

**Issue by Kimchu16** [TeamLapen/Vampirism#745]
## Versions
- Minecraft:  1.16.1                 
- Forge: 32.0.75                      
- Vampirism:   Vampirism-1.16.1-1.6.0-alpha+20200719-2200                                          

- ModPack: N/A

## Issue Description
I travel to find newly loaded in camps and find no Vampire hunters

## Reproduce Steps
Downloaded the mod and went exploring into unloaded chunks

**Comment by Cheaterpaul** [comment]
Thx, Yes this is known and will be fixed in the next version
