### ISSUE TITLE
[Bug] Crash while charging vampire sword

### ISSUE THREAD

**Issue by kave777** [TeamLapen/Vampirism#749]
- Minecraft: 1.15.5                    
- Forge:  31.2.31                     
- Vampirism: 1.6.1                                              

Minecraft crashes while i am charging improved vampire swod, holdig shift+right click. 

here is the crash report
[crash-2020-07-30_12.34.09-server.TXT](https://github.com/TeamLapen/Vampirism/files/5000385/crash-2020-07-30_12.34.09-server.TXT)

**Comment by maxanier** [comment]
This seems like an issue with https://github.com/tterrag1098/Blur
I don't know how Vampirism is involved (besides triggering the crash)

**Comment by maxanier** [comment]
Might have been an issue on our end, not sure why it crashed though.
Let us know if this occurs with Vampirism 1.7+
