### ISSUE TITLE
Crash when loading world

### ISSUE THREAD

**Issue by aldun** [TeamLapen/Vampirism#75]
Forge Version: 12.17.0.1922
Vampirism Version: 1.0.0 Alpha 05-25-17-15

Client crashes just before the world is about to render, crash report attached.

[crash-2016-05-27_17.52.04-server.txt](https://github.com/TeamLapen/Vampirism/files/287463/crash-2016-05-27_17.52.04-server.txt)

**Comment by maxanier** [comment]
Thanks for the report, the issue is fixed and the updated version should be available on curseforge
