### ISSUE TITLE
[Bug] Hunter trainer houses are extreme rare

### ISSUE THREAD

**Issue by Cheaterpaul** [TeamLapen/Vampirism#751]
vampirism: 1.16:dev

all hunter trainer houses are extreme rare

**Comment by Cheaterpaul** [comment]
The JigsawManager.Assembler doesn't choose the trainer house somewhere in JigsawManager.Assembler#149-212.
 the check at JigsawManager.Assembler#174 seem to be nearly always false

**Comment by Cheaterpaul** [comment]
What i could figure out yet, is that the hunter trainer houses are too big to be placed, like big vanilla houses. Which means sometime it works.

Until now i could only guarantee a high present of an custom added piece with size 7x7x7 (modified `plains_small_house_1`)

**Comment by maxanier** [comment]
Hmm, that's annoying

**Comment by Cheaterpaul** [comment]
Retested it and compared to 1.14/1.15.

Actually seems like randomness of the jigsaw system is to random. Last 6 villages had a hunter trainer house.
Compared to the 1.14/1.15 version could not find a real difference and since no one complained i am closing this
