### ISSUE TITLE
[Bug]Blood pedestal crashes if sword is removed

### ISSUE THREAD

**Issue by Bozao** [TeamLapen/Vampirism#755]
## Versions
- Minecraft:1.16.1                    
- Forge:1.16.1-forge-32.0.106                       
- Vampirism:Vampirism-1.16.1-1.6.0-alpha+20200804-2321                                             

- ModPack: N/A

## Reproduce Steps
Place a blood pedestal on top of a blood container, put a new made heartseeker on the pedestal wait for it to charge and try to remove the heartseeker from the pedestal

**Comment by Cheaterpaul** [comment]
Unfortunately i could not reproduce the issue.

Could you provide a log file after this happens ?
