### ISSUE TITLE
[Bug] Cyclic inventory cake compatibility

### ISSUE THREAD

**Issue by jinkhya** [TeamLapen/Vampirism#756]
## Versions
- Minecraft: 1.12                    
- Forge: 2847                      
- Vampirism: 1.3                                             

- ModPack: MC Eternal

## Issue Description
When you use the inventory cake from cyclic, then become a vampire or a hunter, anything you had in that inventory is now gone. 

## Reproduce Steps
You only need a modpack with vampirism and cyclic mod to reproduce : 
1) as a neutral player, eat cyclic inventory cake
2) put some items in that inventory.
3) Become a hunter or a vampire.
4) Open the cyclic inventory again, items are gone. 

## Additional Information
It does seem to save it for each character state somehow, neutral, vampire, hunter (not sure where, I only see one cyclicinv file in the playerdata folder). So for example if you were a vampire, had items in cyclic inv, then became hunter, then rebecame a vampire you'd find your "vampire items" again in the cyclic inventory .

**Comment by maxanier** [comment]
Can reproduce on 1.12. 
However, the cyclic inventory cake does not exist in 1.15 anymore and Vampirism on 1.12 is not supported anymore.
So, no fix on our end. Not sure if this is a bug on Vampirism's or Cyclic's side though
