### ISSUE TITLE
I cant change the biteable creatures!

### ISSUE THREAD

**Issue by UchihaDiogo67** [TeamLapen/Vampirism#76]
I used the tutorial on the wiki about biteable creatures,i did as it was written,but the creatures still the same,i can't bite the creatures that i have wrote on the vampirism_blood_values.txt, can you make a tutorial about how to do this?or it doesn't work on pirate minecraft?(sorry for my bad english,im brazilian)

**Comment by maxanier** [comment]
Can you please post the content of your vampirism_blood_values.txt as well as the Vampirism Version you are using?

**Comment by UchihaDiogo67** [comment]
#General Multiplier. Is divided by 10.
multiplier=10
#Vanilla
Cow=15
Horse=15
Villager=15
Pig=15
Sheep=15
Ozelot=15
Wolf=15



#MCA
MCA.EntityHuman=15

#assassincraft
assassincraft.lightguard=15
assassincraft.heavyguard=15
assassincraft.general=15
assassincraft.deer=15

Vampirism mod 0.6.2.167

**Comment by UchihaDiogo67** [comment]
i'm using Assassin's Craft r130f

**Comment by maxanier** [comment]
Please update to the latest version of the mod (0.7.8.6) first and try again
