### ISSUE TITLE
[Bug] vampires are not generated automatically

### ISSUE THREAD

**Issue by ImFlashPvP** [TeamLapen/Vampirism#760]
## Versions
- Minecraft: 1.12.2                    
- Forge: 1.12.2-forge-14.23.5.2854                       
- Vampirism: 1.12.2-1.6.2                                            

- ModPack: N/A

I have a series of mods which do not appear vampires but vampire hunters, but I realized that if I can generate them but they do not appear alone, I looked in the server logs and I did not appear any error, I generated another map and it remains the same, I went to mode individual and also remained the same, change version and also remained the same, look at the launcher logs and I did not get an error. I need a solution please. Thank you

none

**Comment by maxanier** [comment]
I'm sorry, but I don't really understand the problem
