### ISSUE TITLE
[Bug] Hostile Piglin

### ISSUE THREAD

**Issue by PendragonII** [TeamLapen/Vampirism#762]
## Versions
- Minecraft: 1.16.1
- Forge: 32.0.108
- Vampirism: 1.6.0-alpha+20200814-1726
- ModPack: None; only Vampirism used.

## Issue Description
Piglins and Zombified Piglins are automatically hostile toward Hunter players, the expected behavior is Piglins behaving neutral until attacked. This appeared before in issue #572

## Reproduce Steps
- Create a MC singleplayer world (a flat world will do)
- Go to the Nether
- Become a Hunter `/vampirism level vampirism:hunter 1`
- Spawn Piglins and Zombified Piglins, do not attack them, they will automatically attack you

**Comment by Cheaterpaul** [comment]
The behavior of the Piglins was not altered in any way. Their AI should work right.

But the AI of the Zombified Piglins and Drowned Zombies was not updated to their custom target predicate

**Comment by maxanier** [comment]
Normal Piglins are hostile in vanilla (unless wearing gold): https://minecraft.gamepedia.com/Piglin
