### ISSUE TITLE
[Bug] Blood vision not working

### ISSUE THREAD

**Issue by joelmoli** [TeamLapen/Vampirism#765]
## Versions
- Minecraft:  1.16.1                  
- Forge: 1.16.1 32.0.106                       
- Vampirism:         Vampirism-1.16.1-1.6.0-alpha+20200814-1726                                    

- ModPack: N/A

## Issue Description
Blood Vision doesent work

 Pressing N when u have Blood Vision

**Comment by M0LD** [comment]
You need to be in Darkness for it to start

**Comment by maxanier** [comment]
Cannot reproduce.
As M0LD said: Make sure to use it outside of sunlight
If it still is an issue, please provide a full client log file
