### ISSUE TITLE
[Bug] Some mobs names can not be displayed correctly

### ISSUE THREAD

**Issue by atacool3** [TeamLapen/Vampirism#766]
## What would you like to have changed or added to Vampirism
Mods that display the mob name+hp dont seem to display the name properly for all the vampire mobs

## Does this make the mod experience more balanced?
It makes the mod work well with one of the most popular mods out. Referring to version 1.16.1

## Can you provide additional resources (etc. textures or models)
Mods like Torohealth damage indicators

**Comment by maxanier** [comment]
Which mobs are affected exactly and what does it display instead?
Could only reproduce an issue with vampire hunters

**Comment by atacool3** [comment]
Its for the vampire pigs/cattle/vampire enemies as well. All vampire animals+some vampire mobs
