### ISSUE TITLE
[Bug] vampries don't seem to be implemented as mobs correctly

### ISSUE THREAD

**Issue by alleygaytor** [TeamLapen/Vampirism#767]
## Versions 
vampirism 1.62.
- Minecraft:1.12.2                    
- Forge:14.23.5.2854                                                    

- ModPack: custom
## Issue Description
mega torches which prevent hostile spawns don't disable vampire spawns
open modular turrets which tareget hostile spawns (even when configured to target passives) don't target vampires
project e interdiction torches don't target vampires so it seems in the code it isn't like properly a hostile or a passive as far as the game is concerned.

EDIT iron gollems don't attack the vampires either

**Comment by Cheaterpaul** [comment]
see #492

**Comment by Cheaterpaul** [comment]
^^there is nothing we can do about this except a feature that is already implemented in 1.14+, which is only working in singleplayer
