### ISSUE TITLE
[Bug] crash when vampire villager meets a zombie

### ISSUE THREAD

**Issue by lag42** [TeamLapen/Vampirism#768]
## Versions
- Minecraft:                    1.15.2
- Forge:                       31.2.37
- Vampirism:                                             1.15.2-1.7.0

- ModPack: N/A

## Issue Description 
vampire villagers cause a ticking entity crash when near a zombie

## Reproduce Steps 
1: become a vampire
2: spawn a villager and convert it to a vampire
3: spawn a zombie near said villager and the game will crash momentarily

## Additional Information 
crash log: https://gist.github.com/lag42/26a23340acfddb448800e7e1b702e42e

**Comment by Cheaterpaul** [comment]
Could not reproduce this with forge 31.2.0, will test this further at the weekend.

@lag42 Could you reproduce this by yourself?

**Comment by lag42** [comment]
that crash log was after several attempts to reproduce it to figure out exactly what happened and i found that consistently converted villagers would crash the game when in aggro range of a zombie, so i tried it first thing in a new world and it crashed

i can 100% reproduce this with forge 31.2.0 or 31.2.37, java 1.8.0_261 with no arguments, and the vampirism 1.7.0 alpha in a fresh instance and a fresh world without anything else added, not even guide-api VP

**Comment by maxanier** [comment]
Can confirm. Only occurs outside Dev env. Maybe related to ATs

**Comment by maxanier** [comment]
For some weird reason `func_220988_c` does not properly override its parent in production.
Therefore a unboxing nullpointer occured in `func_220987_a`

**Comment by maxanier** [comment]
Thank you for reporting. Check out the latest fixed alpha
