### ISSUE TITLE
[Bug] lords have a really long name in chat after dying once

### ISSUE THREAD

**Issue by lag42** [TeamLapen/Vampirism#769]
## Versions
- Minecraft:             1.15.2       
- Forge:                       31.2.37
- Vampirism:                                           1.15.2-1.7.0  

- ModPack: N/A

## Issue Description 
hunter and vampire lords both have extremely long names in chat that appear to contain strings
it takes a death for this to kick in

## Reproduce Steps
1: become a vampire or hunter
2: become a lord
3: die once
4: say something in chat

## Additional Information
![2020-09-09 (1)](https://user-images.githubusercontent.com/22325011/92660313-cd952380-f2bf-11ea-92b9-219f30a28a84.png)
![2020-09-09 (2)](https://user-images.githubusercontent.com/22325011/92660352-de459980-f2bf-11ea-89e1-0b986a960770.png)

**Comment by Cheaterpaul** [comment]
Presumably only a missing `getFormattedText()` at ModPlayerEventHandler#272 `fph.getLordTitle()`
