### ISSUE TITLE
[Feature] Vampires should be treated as undead

### ISSUE THREAD

**Issue by ryleu** [TeamLapen/Vampirism#770]
## What would you like to have changed or added to Vampirism
Vampires should work like other undead mobs in regards to instant damage / health. Zombies and skeletons get hurt by healing and healed with harming, so vampires should too.

## Does this make the mod experience more balanced?
It doesn't mess with the balance very much, as hunters can use healing and vampires can use harming.

**Comment by maxanier** [comment]
This was requested many times and I agree that it would be quite cool.
However, after putting some more thought into it, this isn't viable from a modding point of view.
Inverting these effects could very easily mess up other mods that rely on instant damage or poison damaging a player.
I don't want to risk that.

Since it isn't viable for players, it won't be added for NPCs either

**Comment by ryleu** [comment]
That makes a lot of sense. The only way you could realistically make this work is with some sort of additional logic around potions and splash potions that would end up being either really expensive or really hard to implement.

Thanks for giving my idea a read and have a nice day!

**Comment by MarioSMB** [comment]
Pardon the bump, but I'm curious - is this not a simple case of extending the player to have the UNDEAD MobType when they're a vampire? Any mods that don't support it should probably be notified that they're doing some improper checks.

I'm not entirely sure how the Forge and Minecraft coding ecosystem works so I may be way off, just thought I'd mention it!

**Comment by ryleu** [comment]
you might be able to mixin into the check for MobType and have it also return UNDEAD if an entity is a vampire, but that sounds like it would be an expensive check because of how often it'd run

**Comment by maxanier** [comment]
Yes, it should theoretically be possible via Mixins. Performance would not be great, but I guess not too bad either.
Still I don't think it is worth the trouble. 
Could try implementing this as an optional feature, so people who really want this, can try if it works.  However, from past experience (and the lack of feedback) little users seem to use any of Vampirism's optional features

**Comment by MarioSMB** [comment]
I am genuinely surprised Forge offers no API hooks for mob types, but I do believe it would be worth trying - some things like drowning protection (and the desired potion behaviour) would be simplified as the game itself provides them, and it would make weapons with the smiting enchantment effective against vampires out of the box. 
Perhaps it's a matter of weighing the benefits vs the costs; if mixins are really slow then indeed it might not offset the benefits of allowing undead checks to work.

Regarding optional features; for what it's worth I don't even know what optional features the mod provides! It may help to announce or list them somewhere easy to find - perhaps a dedicated section on the wiki.  
Food (or blood in this case) for thought!
