### ISSUE TITLE
[Bug] Crash on crossbow fired by vampire hunter entity due to enchantment

### ISSUE THREAD

**Issue by Zainyest** [TeamLapen/Vampirism#771]
## Versions
- Minecraft: 1.15.2
- Forge: 31.2.36
- Vampirism: 1.6.1

- ModPack: Custom made by me (HeroCraft 1.15.2 v0.2.1.1

## Issue Description
A crash occurs when an aggroed hunter villager uses an enchanted crossbow with the 'ammunitionless' enchantment from Not Enough Enchantments' newest version during a vampire raid on a village.

## Reproduce Steps
Give an enchanted crossbow with the above enchantment to a hunter and force it to attack.

## Additional Information
[crash-2020-09-09_22.09.31-server.txt](https://github.com/TeamLapen/Vampirism/files/5199295/crash-2020-09-09_22.09.31-server.txt)

**Comment by Zainyest** [comment]
Ammendment: Does not need the enchantment to occur, seems to be arrow related

**Comment by maxanier** [comment]
As far as I can tell this is a bug on Not Enough Enchantments side.
Maybe they assume a `AbstractArrowEntity` is always a `ArrowEntity`. 
Cannot confirm as the mod is not open source.

Please create an issue with them.

**Comment by maxanier** [comment]
https://www.curseforge.com/minecraft/mc-mods/not-enough-enchantments/issues/6

**Comment by maxanier** [comment]
Closing this here as they confirmed that it is an issue on their side and it is going to be fixed in their next update. However, apparently they don't want to publish it for now :/
