### ISSUE TITLE
[Bug]Hunter tents overlap other mods' structures

### ISSUE THREAD

**Issue by Twisted-Code** [TeamLapen/Vampirism#772]
## Versions
- Minecraft: 1.15.2
- Forge: 3.1.2.36
- Vampirism: 1.6.1 

- ModPack: [Puncher Pack 6: Golden Carrot Edition](https://www.curseforge.com/minecraft/modpacks/puncher-pack-6-golden-carrot-edition/files/3050333) (self authored, just so were clear and you don't ask me to report this to myself 😉)

## Issue Description
during map generation, if a Hunter Camp happens to choose the same location as another structure (in particular, it just happened on my server with one of Astral Sorcery's small shrines), it can happen that the camp replaces some of the other structure's blocks, as shown in my screenshot below. I don't know if it can happen with just any structures or if it's something specific with these two mods, but I think whichever one generates second should cancel itself.

## Reproduce Steps
install Vampirism and AS
generate a world and either get really lucky or bump the frequency of campsites as high as the moon...
Yeah that should do it...

## Additional Information
![image](https://user-images.githubusercontent.com/7110033/92971606-c81a1380-f44e-11ea-9f84-b72f101ea2cf.png)

**Comment by Twisted-Code** [comment]
happened again randomly. Not sure what I'm doing but apparently it's reproducible for me, and this time I got some screenshots to commemorate his journey of self-discovery (or whatever the heck he's doing)
![2020-09-18_22 56 40](https://user-images.githubusercontent.com/7110033/93658458-b36aec00-fa09-11ea-9471-1e3801a2948f.png)
![2020-09-18_22 57 12](https://user-images.githubusercontent.com/7110033/93658465-b9f96380-fa09-11ea-9261-8dac8d8587b6.png)
![2020-09-18_22 58 51](https://user-images.githubusercontent.com/7110033/93658472-c2ea3500-fa09-11ea-83c5-ea288e4ca82f.png)
![2020-09-18_22 58 58](https://user-images.githubusercontent.com/7110033/93658473-c8477f80-fa09-11ea-95fd-d453299ec981.png)

**Comment by Cheaterpaul** [comment]
Yes i can confirm that on minimum hunter tent distance, there are some overlappings. But with default distance this should happen very rarely, so that it should be acceptable.

Nevertheless ^^a fix
