### ISSUE TITLE
[Bug]Hunters may randomly decide to run away.

### ISSUE THREAD

**Issue by Twisted-Code** [TeamLapen/Vampirism#773]
## Versions
- Minecraft: 1.15.2
- Forge: 3.1.2.36
- Vampirism: 1.6.1 

- ModPack: [Puncher Pack 6: Golden Carrot Edition](https://www.curseforge.com/minecraft/modpacks/puncher-pack-6-golden-carrot-edition/files/3050333) (self authored, just so were clear and you don't ask me to report this to myself 😉)

## Issue Description
as I described via discord, I noticed one leave a nearby camp and decided to follow him, and he's just running aimlessly. He passed by (through) another camp and is still going with no apparent end goal. it's really strange and I doubt it's intentional

## Reproduce Steps
no idea; I have no idea what the cause was. [He got up and he ~~danced~~ walked away](https://www.youtube.com/watch?v=i-potym82AE).

**Comment by maxanier** [comment]
I had a quick look, but can't find an obvious reason.
Since this does not seem like a severe issue, but rather like a fun bug, I won't spend much more time on debugging.

**Comment by Twisted-Code** [comment]
yeah, it's not that bad really. A little weird, but it's not like it's going to impact gameplay in any significant way. Nonetheless, I thought I should bring it up 😄
Edit: that said, it's worth noting that I seem to be able to accidentally reproduce it. If I can reproduce it deliberately, might be worth another look?

**Comment by maxanier** [comment]
I don't really see a reason to look into this.
Shouldn't have any relevant effect and might add some "fun aspect". Maybe they forgot to turn off their stove at home :shrug: 

Might fix itself eventually :)

**Comment by maxanier** [comment]
So, I came across such a hunter as well, so I decided to have a look where he wanted to go (in memory). Turns out he was heading for 0,0,0.
Apparently this happend to all hunters that for some reason left their home area towards 0,0,0 for a short moment.
I fixed that, but added a new, now actually random and very small, chance that a hunter decides to look for a new home

**Comment by Twisted-Code** [comment]
you know, had I thought about it, I probably would've realized they were heading for the origin of the map. It's the only location that I can think of they would be going such a long distance to get to, aside from the map spawnpoint.
I like the comment about turning off their stove. If you ever somehow connect hunter outposts to nearby villages somehow, that should become a thing
