### ISSUE TITLE
[Bug][mod compatibility?] Morpheus doesn't work well with Vampirism and vice versa

### ISSUE THREAD

**Issue by Twisted-Code** [TeamLapen/Vampirism#776]
## Versions
- Minecraft: 1.15.2
- Forge: 3.1.2.36
- Vampirism: 1.6.1
- ModPack: [Puncher Pack 6: Golden Carrot Edition](https://www.curseforge.com/minecraft/modpacks/puncher-pack-6-golden-carrot-edition/files/3050333) (self authored, just so were clear and you don't ask me to report this to myself 😉)

## Issue Description
Morpheus is (surprise surprise...) incompatible with coffins. Attempting to sleep in a coffin while another player is on and Morpheus is installed causes it to jump to the next morning, not the next night. I'm not sure what all is involved in the bug or how Morpheus and Vampirism's sides of the metaphorical fence are coded, but it would be really nice if you could figure out how to make this work in a sensible way. 

## Reproduce Steps
Install Vampirism and Morpheus on a server and 2 clients (pretty sure you need at least 2 people for this)
have one person be a VH and one person be a vampire
while both players are logged in, have the vampire try and sleep in a coffin
they will sleep, but it will go today instead of night.

## Additional Information
I have a few ideas how this could work sensibly, if you wouldn't mind coding a built-in alternative to Morpheus or figuring out how to make it worked this way with Morpheus. First, there should probably need to be a certain fraction of people in beds, to make sure the first person to sleep doesn't automatically get what they want (just like Morpheus normally works). Next, instead of always going to day, it should jump based on the ratio between beds and coffins. There can be a second ratio threshold for that, or just the same as the other ratio. Pretty straightforward really, but I understand if it's too much coding or too complicated to test (since you either need multiple players or to emulate the equivalent of having multiple players)

**Comment by Twisted-Code** [comment]
Update: and apparently nothing happens if you try and sleep in a coffin will and you are the only person on. You just stay "asleep" indefinitely or until you click "leave coffin" and time passes as it normally would without beds/coffins
edit: this behavior is inconsistent though. A moment before making this at it, I was able to get it to "work" when I slept during the first half of the night... or at least, I think that's why it worked. Point is it's acting weird even when I'm the only person on.

**Comment by Twisted-Code** [comment]
actually, come to think of it, didn't you have a separate module for mod compatibility? Does that do anything to help with this?

**Comment by Twisted-Code** [comment]
weird, I thought I edited the title earlier

**Comment by maxanier** [comment]
Can probably be solved on Morpheus end: https://github.com/Quetzi/Morpheus/issues/84

In the meantime I think you should be able to use Quarks Improved functionality as you have that installed as well. I think that should do something very similar and already work with Vampirism

**Comment by Twisted-Code** [comment]
What do you mean "quark's improved functionality"?

**Comment by maxanier** [comment]
ah, sorry, improved sleeping module

**Comment by Twisted-Code** [comment]
how do I use that?? I honestly didn't check all the features of the mod. I just trust Vazkii not to add anything crazy 😆

**Comment by maxanier** [comment]
Closing this here as this is Morpheus responsibility. 
Just use quark instead, I think one can disable all other features

**Comment by Twisted-Code** [comment]
looks like 1.17 will be adding a vanilla gamerule to replace Morpheus anyway, so as long as Forge handle the change in a sensible way, this bug should be a thing of the past

**Comment by maxanier** [comment]
That is good to hear, thanks for letting me know.
But I want to point fingers at Morpheus here. Forge already provides a sensible way to manage sleep timing that should provide reasonable inter-mod compatibility, but Quetzi does not want to use it

**Comment by Twisted-Code** [comment]
oh I'm certainly not blaming you. It looks like support for Morpheus is basically nonexistent based on the way he responded (if that can even be called a response?) to your issue. Like what was that even? "Just use this obscure API over..." *proceeds to ignore you when you asked where the documentation for said API is*
perhaps it's for the best that Morpheus will soon be obsolete...

**Comment by macks2008** [comment]
oh, I know, and I can wholeheartedly say I won't be missing Morpheus. After that waste of time (otherwise known as Morpheus issue 84), I didn't even put Morpheus in my 1.16 pack.
