### ISSUE TITLE
[Bug] Crash on world create/join

### ISSUE THREAD

**Issue by Tyrius1** [TeamLapen/Vampirism#782]
## Versions
- Minecraft:   1.16.3                 
- Forge:                     forge-34.1.17  
- Vampirism:          Vampirism-1.16.3-1.6.0-beta.1                                   

- ModPack: N/A

## Issue Description
Crash when attempting to create a world

## Reproduce Steps
launch pack and create world
it will go through the normal load process untill 100%
then when going to load world it crashes
Removing vampirism allows world to load normally

## Additional Information
https://pastebin.com/b65wjxF1

**Comment by maxanier** [comment]
Not sure why you closed it already, maybe you found a different workaround.
There was, at least a theoretical, bug in Vampirism here.
