### ISSUE TITLE
[Feature] dark blood projectile sidegrade

### ISSUE THREAD

**Issue by Dover2** [TeamLapen/Vampirism#783]
## What would you like to have changed or added to Vampirism
For the dark blood projectile, a new upgrade/sidegrade could become available when the player reaches max level (or becomes vampire lord) lets call it the dark blood jet for now. The dark blood jet has both upsides and downsides, one is that it deals more damage than the standard dark blood projectile. (lets say it deals 10 damage/5 hearts on direct hits) it will also have some form of projectile penetration (dealing damage to entities behind the first target) however the downside comes in that it deals no splash damage at all. requiring more precision from vampire players, to make things a bit easier, the dark blood jet will have a higher velocity than the dark blood projectile.

## Does this make the mod experience more balanced?
it gives vampire players another option for ranged attacks.

## Can you provide additional resources (etc. textures or models)
no

**Comment by maxanier** [comment]
Liking your own post ^^

Anyway, sounds good.
Maybe with #475
