### ISSUE TITLE
[Bug] Vampirism causes crash to desktop during Astral Sorcery attunement process

### ISSUE THREAD

**Issue by stepech** [TeamLapen/Vampirism#786]
## Versions
- Minecraft:    1.15.2                
- Forge:          31.2.45             
- Vampirism:   1.15.2-1.7.0-beta1                                         

- ModPack: 
                forge-1.15.2-31.2.45-client.jar Minecraft {minecraft@1.15.2 DONE}
		useful_backpacks-1.15.2-1.10.3.77.jar Useful Backpacks {usefulbackpacks@1.10.3.77 DONE}
		astralsorcery-1.15.2-1.12.9.jar Astral Sorcery {astralsorcery@1.15.2-1.12.9 DONE}
		structurize-0.13.94-ALPHA-universal.jar Structurize {structurize@0.13.94-ALPHA DONE}
		u_team_core-1.15.2-3.0.2.169.jar U Team Core {uteamcore@3.0.2.169 DONE}
		noRecipeBook_v1.5.4formc1.15.2.jar No Recipe Book {norecipebook@1.5.4 DONE}
		minecolonies-0.13.359-BETA-universal.jar Minecolonies {minecolonies@0.13.359-BETA DONE}
		observerlib-1.15.2-1.2.0.v60.jar ObserverLib {observerlib@1.15.2-1.2.0 DONE}
		jei-1.15.2-6.0.3.15.jar Just Enough Items {jei@6.0.3.15 DONE}
		Ma-Essentials-1.15.2-3.1.1.jar Ma Essentials {maessentials@1.15.2-3.1.1 DONE}
		forge-1.15.2-31.2.45-universal.jar Forge {forge@31.2.45 DONE}
		Guide-API-VP-1.15.2-2.2.1.jar Guide-API VP {guideapi-vp@2.2.1 DONE}
		Vampirism-1.15.2-1.7.0-beta.1.jar Vampirism {vampirism@1.7.0-beta.1 DONE, teamlapenlib@1.7.0-beta.1 DONE}
		curios-FORGE-1.15.2-2.0.2.6.jar Curios API {curios@FORGE-1.15.2-2.0.2.6 DONE}
		journeymap-1.15.2-5.7.0b3.jar Journeymap {journeymap@5.7.0b3 DONE}
		citadel-1.1.11.jar Citadel {citadel@1.1.11 DONE}
		iceandfire-2.1.0-1.15.2.jar Ice and Fire {iceandfire@2.0.3-1.15.2 DONE}

## Issue Description
Complete minecraft launcher crash to desktop - affected by event in Astral Sorcery, caused by some incompatibility with Vampirism mod and crashed

After finishing attunement altar and the structure around, player is able to "attune" himself to a power of some constellation. During this attunement process, whenewer player wants to start it, the whole game just crashed. Video:
[Here](https://youtu.be/3KNgthj-gRM)
I know it is vampirism's fault as downgrading to stable 1.6.1 version solves the issue. Crash report dump below.

[crash-2020-10-19_21.51.10-client.txt](https://github.com/TeamLapen/Vampirism/files/5404687/crash-2020-10-19_21.51.10-client.txt)
[crash-2020-10-19_22.12.50-client.txt](https://github.com/TeamLapen/Vampirism/files/5404689/crash-2020-10-19_22.12.50-client.txt)
[crash-2020-10-19_22.16.18-client.txt](https://github.com/TeamLapen/Vampirism/files/5404691/crash-2020-10-19_22.16.18-client.txt)
[crash-2020-10-19_22.27.13-client.txt](https://github.com/TeamLapen/Vampirism/files/5404692/crash-2020-10-19_22.27.13-client.txt)

**Comment by Cheaterpaul** [comment]
@maxanier fixed by a simple null check because the player is saved/loaded on the client, but should i add a log warning like 
`if (this.taskManager != null) { this.taskManager.writeNBT(nbt);
        } else {
            LOGGER.warn("The player is saved on the client side and therefore taskmaster related data is missing");
        }`

**Comment by maxanier** [comment]
Did you figure out, why astral sorcery is saving the player client side?

**Comment by Cheaterpaul** [comment]
they are using a duplicated player as render entity https://github.com/HellFirePvP/AstralSorcery/blob/377b3cc7bccfa56940c68579ef93fc5a62acb40a/src/main/java/hellfirepvp/astralsorcery/client/util/camera/CameraTransformerPlayerFocus.java#L40

**Comment by maxanier** [comment]
Ah, alright. I would skip the warning message (maybe debug/trace). As far as I can tell writing/reading entity data client side is not "illegal", so this could happen frequently with certain mods. As long as the data is then only used client side, it shouldn't cause any issue anyway.
Maybe double check that loading a player from nbt with missing task manager data does not crash.

**Comment by Cheaterpaul** [comment]
will be fixed in next release

**Comment by stepech** [comment]
Thank you guys, it's so nice to see someone taking care of their mods and fixing issue in under 24 hours is exemplary. Is there some way for me to donate/support development? It's somehow rare to see maintained/updated mods, there must be some way to help you in this effort.

**Comment by maxanier** [comment]
Given proper bug reports, it is always a pleasure to squash some bugs ^^ (especially when they are rather simple to fix).
To support the development just keep reporting issues if you should find some, and spread the word about Vampirism :)
You can also donate on the CurseForge page, but only if you don't need the money yourself :)
