### ISSUE TITLE
[Bug] Crashed game for class not found

### ISSUE THREAD

**Issue by AndresGutierrez05** [TeamLapen/Vampirism#787]
## Versions
- Minecraft: 1.16.3                   
- Forge:    realese 1.16.3-forge-34.1.23                   
- Vampirism: 1.16.3-1.6.0
                                            

- ModPack: N/A

##
The game crashed whilst unexpected error
Error: java.lang.NoClassDefFoundError: Could not initialize class de.teamlapen.vampirism.inventory.container.AltarInfusionContainer
Exit Code: -1

**Comment by Cheaterpaul** [comment]
Do you have a crashlog or debug log for the time the game crashes? It is possible that another mod could cause this issue.

**Comment by AndresGutierrez05** [comment]
Sorry i forgotten send the mods that i have installed

i have

![image](https://user-images.githubusercontent.com/24322326/96650089-d6820780-12f7-11eb-88f2-1fa22bb9c8ba.png)

and crashed log is this 

[crash-2020-10-20_17.11.54-client.txt](https://github.com/TeamLapen/Vampirism/files/5411901/crash-2020-10-20_17.11.54-client.txt)

**Comment by Cheaterpaul** [comment]
is the crash reproducible?

**Comment by AndresGutierrez05** [comment]
yes, when i put the altar infusion in middle of the four pillars the game crashed and now, every time that load the world show me that error

**Comment by maxanier** [comment]
This is a very strange issue. Can you try if this Vampirism version solves the issue for you: https://cloud.maxgb.de/s/2LHLFRLLj8st8t8

**Comment by AndresGutierrez05** [comment]
yeah, it seems fixed the error, the class AltarInfusionContainer now be right, but now show me other error of other class

**message**

The game crashed whilst unexpected error
Error: java.lang.NoClassDefFoundError: Could not initialize class de.teamlapen.vampirism.tileentity.AltarInfusionTileEntity
Exit Code: -1

**log**
[crash-2020-10-21_12.36.37-client.txt](https://github.com/TeamLapen/Vampirism/files/5417749/crash-2020-10-21_12.36.37-client.txt)

**Comment by maxanier** [comment]
Mhh, can you maybe upload your entire MC directory here https://cloud.maxgb.de/s/gt5EbF9bfWAG9ie so I can see if I can reproduce it myself?

**Comment by AndresGutierrez05** [comment]
all directory of minecraft (.minecraft)?

**Comment by maxanier** [comment]
I need the world (saves), the mods, the config directory and the options files. So either just these directorys or the entire `.minecraft`.
Compressed/Zipped preferably

**Comment by AndresGutierrez05** [comment]
done, i upload the files, and i play in mimundoxd world

**Comment by maxanier** [comment]
Thank you. I can reproduce the issue with this.
It seems the mod "world blender" is somehow causing/triggering this issue.
If I remove it the world loads fine.

Until I have figured out what is the exact cause, you could consider removing world blender (

**Comment by AndresGutierrez05** [comment]
Yeah, works perfectly but now i'm not vampire but i have the four hearth more and delete all the fast items lol, very very thanks for fixed my error

![image](https://user-images.githubusercontent.com/24322326/96772434-bfe7b900-13a8-11eb-908e-0124c5e923f3.png)

**Comment by maxanier** [comment]
Checkout Vampirism 1.6.1 which should resolve the issue and allow you to use all three mods again.
If you haven't played much since then, you can load the world backup you uploaded, you should have your hotbar items and your vampire levels then (worked for me at least).
