### ISSUE TITLE
Book Text Issues 

### ISSUE THREAD

**Issue by ChrisLTheNerd** [TeamLapen/Vampirism#788]
## Versions
- Minecraft: 1.16.3                    
- Forge: 34.1.25                      
- Vampirism: 1.16.3-1.6.0                                             

- ModPack: n/a

## The book for this mode from the Guide-API Village and Pillage: 1.16.3-2.2.0 mod has broken text formatting that makes the book unreadable. 
![2020-10-21_14 58 06](https://user-images.githubusercontent.com/50182206/96770963-0cce8e00-13af-11eb-853f-dc1a5fbad57f.png)

**Comment by Cheaterpaul** [comment]
Thanks for reporting this.

Fixed in the next version.
The hunter -> vamp slayer section had issues to.

Until then you can assume that it should only be "To reach level 5+".
