### ISSUE TITLE
Holy Water Gets Thrown The Wrong Way

### ISSUE THREAD

**Issue by ChrisLTheNerd** [TeamLapen/Vampirism#789]
## Versions
- Minecraft: 1.16.3                  
- Forge: 34.1.25                       
- Vampirism: 1.16.3-1.6.0                                            

- ModPack: N/A

## Every time I use the holy water splash potion it gets thrown to the side and not where I'm looking at. 
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/50182206/96794659-980a4c80-13cc-11eb-8d74-47d6f041f4ff.gif)

## This happens with all three types of holy water splash potion and they all seem to be thrown north according to the F3 Menu.
![2020-10-21_18 43 27](https://user-images.githubusercontent.com/50182206/96795319-6b0a6980-13cd-11eb-80f8-5b561b6ac6df.png)

**Comment by Cheaterpaul** [comment]
Fixed in next release

thx for reporting.
