### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by PresidentSwift** [TeamLapen/Vampirism#790]
Version 1.14.4
latest version of forge for 1.14.4
Vamperism 1.6.4

what I'm using

go to twitch launcher
download web of time modpack
go onto the server I am staff on and am having issue on (ip: apollo.rnshosting.xyz:25579)

when I'm or any other player is a vampire we cant see the skills tree, you can go onto where it should be, by clicking the fangs under the crafting table in inventory but the only thing that is in there is 'Becoming a vampire' but nothing else, i also couldn't move when in there but i fixed that issue by relogging.
I posted something on the discord server by the haven't seem to have seen it before. I want to get this fix cuz there is a small player base that plays on the server and it would be a shame to get rid of it from the modpack. Thanks

-Swift

![image](https://user-images.githubusercontent.com/73315113/96931225-daa75400-14b4-11eb-98b8-1f166224f70e.png)

**Comment by Cheaterpaul** [comment]
solved on discord
tetra caused the issue.
[debug_2.log](https://github.com/TeamLapen/Vampirism/files/5426457/debug_2.log) line 9701

**Comment by Cheaterpaul** [comment]
i created an issue there mickelus/tetra#219
