### ISSUE TITLE
More Book Text Issues

### ISSUE THREAD

**Issue by ChrisLTheNerd** [TeamLapen/Vampirism#791]
## Versions
- Minecraft: 1.16.3                    
- Forge: 34.1.25                        
- Vampirism: 1.16.3-1.6.1                                             

- ModPack: N/A

## Pages 6, 7, 8, and 9 are also having issues. Also I still have Guide-API-VP-1.16.3-2.2.0
![2020-10-22_19 05 07](https://user-images.githubusercontent.com/50182206/97037997-20593080-1538-11eb-887d-6f348c262114.png)
![2020-10-22_19 03 24](https://user-images.githubusercontent.com/50182206/97038008-24854e00-1538-11eb-850b-0131c511c0b2.png)
![2020-10-22_19 03 28](https://user-images.githubusercontent.com/50182206/97038022-2cdd8900-1538-11eb-8723-7bcab75ed114.png)
![2020-10-22_19 03 32](https://user-images.githubusercontent.com/50182206/97038029-2e0eb600-1538-11eb-813d-adf5a956e18c.png)

## I checked every single page and I can confirm only these pages are broken. All the other ones I reported where fixed and have no issues at all. Also in Blocks<Altar Of Infusion, page 3 is blank
![2020-10-23_14 24 38](https://user-images.githubusercontent.com/50182206/97040122-872c1900-153b-11eb-8b82-67af0b11d782.png)

**Comment by maxanier** [comment]
Thank you for the report and checking the book.
Fixed in 0a5f775dfce5e7f303e1945b22f4c276d60eb2fd and bea0a2e75bff033d27bf77c558de796c1a76f5fe
