### ISSUE TITLE
Alchemical Fire Not Burning 

### ISSUE THREAD

**Issue by ChrisLTheNerd** [TeamLapen/Vampirism#792]
## Versions
- Minecraft: 1.16.3                    
- Forge: 34.1.25                      
- Vampirism: 1.16.3-1.6.1                                           

- ModPack: N/A

## The Alchemical Fire is not burning any mobs
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/50182206/97092382-9f6e6780-1611-11eb-99b2-f5bc47b2a634.gif)

**Comment by maxanier** [comment]
Thx for reporting.  Fixed in next version
