### ISSUE TITLE
Use tags for coffin coloring dye

### ISSUE THREAD

**Issue by the-vindex** [TeamLapen/Vampirism#796]
## What would you like to have changed or added to Vampirism
Make it possible to dye coffins, namely I need pink one.

## Does this make the mod experience more balanced?
No, it makes it more attractive to female players.

## Can you provide additional resources (etc. textures or models)
Not right away, but if you tell me how/give me input, I could play with GIMP or something.

**Comment by Cheaterpaul** [comment]
That is already possible.

You can just place the coffin and right click it with a dye item and the coffin changes color.

**Comment by the-vindex** [comment]
Oh, ok, vanilla dye, not botania petal dust (which oredict with vanilla dye).

**Comment by maxanier** [comment]
Ok, so we should probably use tags for the dye color (if there are dye tags in 1.16)
