### ISSUE TITLE
Mobs spawning in biom

### ISSUE THREAD

**Issue by RacerDelux** [TeamLapen/Vampirism#80]
In the vampire biome, other mods' mobs are spawning at very high rates. Can you disable the spawning of all mobs but your own (naturally spawning that is).

Also, the light level does not seem to affect baron spawning, makes houses a bit surprising to walk though.

**Comment by maxanier** [comment]
Thanks for that report, other mobs should not spawn there already.But I need a few more information to fix this:
1. Which Vampirism/Minecraft version are you using?
2. Which other mods are you using?

Thanks

**Comment by RacerDelux** [comment]
Minecraft 1.9.4 mod version version 1.0.0 alpha 05-28-10-48 (current version)

The mobs in question are:
- concussion creeper from ender zoo
- Wither Witch from ender zoo

**Comment by maxanier** [comment]
Looks like I cannot directly do anything against that, since Ender Zoo just adds spawn entries for all biomes by default. But Ender Zoo can be configured to only spawn the entities in certain biomes, as far as I can tell from it's source code. Maybe you can try to use that to prevent them from spawning in the vampire forest.

**Comment by RacerDelux** [comment]
Thanks! Figured it out. It looks like you used to have torches that stopped vampire barons from spawning. I guess I will wait for those to be implemented for the other issue?

**Comment by maxanier** [comment]
Oh, forgot to answer that one, sorry. Jup, there currently is no way to stop vampires/barons from spawning in 1.9.4 (except half slabs and stuff), but there will be on in the (near) future

**Comment by maxanier** [comment]
Moved "stop vampires/barons from spawning" to new issue #83
