### ISSUE TITLE
[Bug] Mod Incompatibility with Matter Overdrive

### ISSUE THREAD

**Issue by RobTheKIng1987** [TeamLapen/Vampirism#802]
## Versions
- Minecraft: 1.12.2                   
- Forge: 14.23.5.2854                      
- Vampirism: 1.6.4                                            

- ModPack: N/A

## Issue Description
    Mod incompatibility with Matter Overdrive: Legacy Edition

## Reproduce Steps
    1. Become both Android And Vampire.
    2. Get the upgrade Zero Calories (removes need for food)
    3. Drains the battery for androids really fast

## Additional Information
    I wasn't sure to to post this here or with the other mods bug reports so i did both.
    If this could be fix i would extremely grateful

**Comment by maxanier** [comment]
Sorry, but we don't work on MC1.12 anymore.
Since this is not a severe crash there won't be a fix.

Also, vampire androids don't make much sense anyway ^^
