### ISSUE TITLE
Remaining 1.16-1.7 tasks

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#803]
- RandomBlockState changes
- #758 
- Structure id errors 0c7540c01d79454ee5a01d5b0aed1a5814aed47b
- Vampirism biome rework #759

**Comment by Cheaterpaul** [comment]
acc28791fe45b9f11a9db49a487ac80dd8eef40d d00e499f63f5e2c4475d39600bf4995495dcef96
