### ISSUE TITLE
Is there a way to  disable the yellow border?

### ISSUE THREAD

**Issue by KGXSparks** [TeamLapen/Vampirism#804]
1.15.2. 
Trying to disable the yellow border that you get when you take sun damage for multiple reasons. Is there a config for it or could that maybe be added? And is there a way to disable the vampire forest fog?

**Comment by KGXSparks** [comment]
Also do you by chance have a patron or any other way I could donate? I have been enjoying vampirism for a couple of years now and I feel like I should support the development of the mod if possible.

**Comment by maxanier** [comment]
`Config/vampirism-client.toml` `[client.render]` `screenOverlay = false` should disable the yellow border as well as the rage mode border and some effects during rituals

I had a patron some time ago, but it wasn't worth the trouble. Also I'm not really in this for the money.
If you really want to you can use the Donate button on the CurseForge page

Discord is probably better for questions, but I see you have already found it

**Comment by KGXSparks** [comment]
Thanks
