### ISSUE TITLE
[Feature] Vampire armor replacement

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#806]
An extensive suggestion to implement #287
By ♤SpadeIsACard♤,S_olace , spoopy special krab:

# Vampire armor idea/suggestions

How this would help balance the game

In the hunter class skills are chosen to help improve the weapons used because they have no magic, so vampires should have items that work off of the skills they choose since they only have magic. This would help give variety to how being vampire can be played and it&#39;s been stated before that you don&#39;t want vampires to have armor in the future so with the absence of vanilla defense this leaves room for possible cosmetics and vampire items that can go into those empty armor slots.

Summary of our suggestion

The item(s) that we&#39;re suggesting are essentially accessories that can go in armor slots to replace vanilla defence with customizing your stats, these items would act like armor in MMOs in the way that they boost different skills. We have four different kinds of accessories, each of which can go into an armor slot. They are then set into five types of rarity -common \&gt; uncommon \&gt; fine \&gt; rare \&gt; legendary- which determine how you can acquire them and what abilities they have. Common and uncommon being craftable and the rest are either drops or found in chests, higher in rarity, harder to find but greater abilities. Each in question could also have a small armor rating like the vampire cloak to give at the very least some protection.

# Rarity &amp; Item Types

**Common:** these would be craftable, using things such as iron, gold, etc. you would have to enchant these by either an enchantment table or a charging station. These would give small buffs such as speed, regen, low blood loss.

**Uncommon:** these would still be craftable but cost more to make, involving diamonds/gold/vampire book or something similar. These would still grant the same buffs, however, these buffs would be stronger.

**Fine:** these would be uncraftable, only found in any dungeon/ sold by vampire experts. These would provide flight changes to vampire abilities as a whole. Faster bat movement speed, garlic affects you less, etc.

**Rare:** these would be much rarer and only found in mineshafts, vampire dungeons, or dropped rarely from advanced vampires. These would give actual ability changes, such as turning into multiple bats for more health but slower movement and larger hitbox.

**Legendary:** These would only be found extremely rarely in vampire dungeons and rarely dropped off of level 5 barons. There would only be 5 variations (not 5 per world just 5 versions). These would also have the requirement of being a vampire lord to use (must have 1-5 minions to use).

**Common**

**Ankle bracelet:** these would be smaller ring-like objects that would be equipped to the boot section of one&#39;s inventory.

A common ankle bracelet would give small buffs, such as higher speed, regeneration, slower blood loss, etc. These effects would be stackable with other effects from other pieces of equipment.

**Obi Belt:** These would be around one&#39;s waist granting the same small buffs from before, more speed, regen, etc. Stackable.

**Rings/amulets:** These would go in the chestplate appearing as an amulet on the neck. These would give the same effects as before stated, stackable.

**Crowns/Hats:** These would go in the helmet section appearing as a crown or hat such as a tophat. Same effects given as before, Stackable.

**Uncommon**

**Ankle bracelet:** These would act the same as a common ankle bracelet with some stronger buffs. With an example being, If a common gives a regen buff by 2-3% this would buff it by 4-5% (these are placeholder numbers and are to be changed)

**Obi Belt:** These would act the same as a common obi belt with some stronger buffs. With an example being, If a common gives a regen buff by 2-3% this would buff it by 4-5% (these are placeholder numbers and are to be changed)

**Rings/amulets:** These would act the same as a common ring/amulet with some stronger buffs. With an example being, If a common gives a regen buff by 2-3% this would buff it by 4-5% (these are placeholder numbers and are to be changed)

**Crowns/Hats:** These would act the same as a common crown/hat with some stronger buffs. With an example being, If a common gives a regen buff by 2-3% this would buff it by 4-5% (these are placeholder numbers and are to be changed)

**Fine**

**Ankle bracelet:
 Obi Belt:
 Rings/Amulets:
 Crowns/Hats:**

**Rare**

**Ankle bracelet:
 Obi Belt:
 Rings/Amulets:
 Crowns/Hats:**

**------------------------------------------------------------------------------**

**Actual changes to abilities are seen below this point.**

**Fine Bracelet of wings** :this would make you move faster in bat mode
**Fine bracelet of disguise** : Once entering disguise form the next time to bite/attack from behind it deals bonus/poison damage.

**Fine bracelet of leaping** :in rage form you gain jump boost along with the speed given.

**Fine belt of biting:** after you&#39;ve gained the better biting perk this gives a passive ability causing you to gain more blood and drain less.

**Fine belt of Piercing:(replace dark blood projectile)**Gives you a small dagger made of blood dealing the equivalent of an iron sword each swing until your blood is depleted. (or a stone sword with high attack speed

**Fine belt of transportation:** your teleport ability has a smaller cooldown and goes farther.

**Fine amulet of feasting:** when under the effect of the regeneration ability you gain blood by eating normal raw food

**Fine amulet of the swarm:** instead of turning into one bat, you turn into three bats, gaining extra health at the cost of slower movement speed and larger hitbox.

**Fine amulet of hunger:** dark blood projectile now causes either thirst or hunger apon hitting a target.

**Fine crown of vampirism:** once you have the advanced biter perk, this crown allows you to always turn the animal/villager with a 100% chance. Biting a player with this crown equipped reduced the vampirism timer by half.

**Fine hat of rending:** Increases the max health needed for Finisher&#39;s one shot to 35%

**Fine crown of cursing:** those hit by your dark blood are given a &quot;curse&quot; (an effect that lasts for a 1:50) that makes them take more damage from vampire abilities.
 **Rare Bracelet of the bat:** you can use the summon bat skill in a human form, the bats also target other players in an attempt to body block attacks.

**Rare Bracelet of fog:** the vista skill now grants you a moving cloud of fog for 5 seconds after leaving a vampire forest

**Rare Bracelet of bloody daggers:(replace dark blood projectile)** dark blood projectile now turns into a dagger formed from blood, it does a smaller amount of damage but grants a lifesteal effect if it does damage

**Rare belt of bloody piercing:(replace dark blood projectile)** summon a sword formed from one&#39;s own blood, dealing the damage of a diamond sword, every swing depletes blood until it is no more. It also has a slight lifesteal effect.

**Rare belt of bones:** once you have the ignored by creepers ability, skeletons also ignore you (not while a bat)

**Rare belt of the beast:** forfeit speed for complete health, become a massive 2 block by 2 block bat beast, granting one&#39;s self a lot more health at the cost of mobility and speed.

**Rare amulet of charging:** you are able to charge a vampire sword by killing, gaining experience and blood to charge.

**Rare amulet of shielding:** after gaining the damage limiter perk, you at all time have a small amount of armor, this armor increases if you stand still and hit shift.

**Rare amulet of absolute fury:** when in raged form the more you kill the longer it lasts, killing animals gives an extra 5 seconds, killing players grants 10

**Rare crown of fog:(replaces vista)** upon activation of this skill an opponent is shrouded in fog blinding them and lowering attack reach.

**Rare crown of pride:** your immortality is a source of pride to you, when under the moon-lit night you gain strength and speed, however when at low health or under the sun your pride is slightly broken, lowering your strength and speed.

**Rare crown of fear:** while in rage weaker creatures such as animals, minions, and baby variants of all creatures run and hide. Strong creatures such as players, skeletons, and zombies are weakened. Hunter players are also weakened however gain motivation to destroy such a creature, gaining a small absorption buff.

**----------------------------------------------------------------------------------------------------**

**Legendary**

There are only 5 legendary effects, multiple legendary items of the same and different effects can spawn. They require you to be a lord of a certain level.

**Legendary amulet of hibernation:** you can only freeze one person at a time, with a long cooldown. This freeze turns them into stone draining their hunger and blinding them for a short time. Additionally as a passive skill, upon death instead of dying you yourself will freeze into rock, hibernating and rapidly regenerating to full health, then resuming the fight. The cooldown for the hibernation skill will be 5-10 minutes, if the stone freeze is used on anything, the hibernation passive is put on cooldown for 5 minutes. (requires lord level 3)

**Legendary amulet of shadow:** when using the invisibility skill, you vanish for a moderate amount of time, during which items you hold will also not appear. Additionally you summon 2 clones will appear acting as shields while you get out of range, If hit they will move towards the player/mob attacking and block their attacks. If you take damage or deal damage they will vanish and you will become visible. If you deal damage from behind you will deal extra damage as well as inflict a slow apon your opponent. (requires lord level 3)

**Legendary amulet of the void:** The teleportation skill now acts as an activated effect. Once activated for a certain amount of time (1-5 minutes) any projectile shot at the user will be teleported to hit who shot them. Additionally when the vampire in question teleports they gain absorption for 5 seconds to act as a defence. (requires lord level 3)

**Legendary crown of slaves:** You may own one additional minion. You will also instantly control this minion without fail. Additionally this minion will have 1 skill point put into all level up points.

**Legendary crown of Dracula:** While wearing this crown all minions cannot attack or harm you and will deny their masters request to do so. vampire barons will be also neutral to you. Additionally you gain a second menu for transformations allowing you to become a bat or a wolf.

I wanted to mention this, these are just suggestions and ideas of what we would consider balanced or fun. We implore you to ignore these and just use them as ideas, if you want to use them then do so, but please edit these and change them however you feel would work best.

List made by:
♤SpadeIsACard♤(willing to help make textures/writer
S\_olace (we asked if he could make textures and help, he said yes
spoopy special krab \&lt;- MVP(writer

**Comment by KGXSparks** [comment]
Sounds like an nice addition, would these items be put inside armor slots or will (if this was made into the mod) there be some slots for these items.

**Comment by jeroen11122005** [comment]
that sounds like a really cool idea but maybe its better to use baubles/curios API for these items and give the hunters something like this as well because in modded servers with stronger armor sets these items would be useless as you lose a lot of defence/perks if you don't use the modded armor sets

**Comment by Marsmalo** [comment]
Oh boy this sounds so complicated and getting the Swords in their ultimate form for is already a hard thing to get with no reward from them because a high level hunter without potions achieve higher DPS with a netherite sword full enchanted... This would make things really harder to find and vampires would be too focused on having items that Hunters could even find and steal from them making them way harder to find... But if they can be crafted that is another thing. But I still don't like the ideia of putting more and more items to the mod, this will not solve the problem, probably will only increase the balancing problem in the future.

**Comment by maxanier** [comment]
Implemented with #908 #896
