### ISSUE TITLE
[Bug] Vampirism/Minecolonies conflict

### ISSUE THREAD

**Issue by Chrysarius** [TeamLapen/Vampirism#808]
## Versions
- Minecraft: 1.16.4                    
- Forge: forge-1.16.4-35.0.18.jar                      
- Vampirism: Vampirism-1.16.4-1.6.2.jar                                            
- ModPack: N/A

## Issue Description
When trying to launch a server with Minecolonies and Vampirism both installed, the server crashes during loading with the message that there's a non-character in the namespace of minecolonies:citizen. The server works fine when Vampirism is removed.

## Reproduce Steps
Launch a server with the listed versions of Vampirism/Minecolonies/Structurize/Forge (the middle two have their versions below)

## Additional Information
Minecolonies version: minecolonies-0.13.450-ALPHA-universal.jar
Structurize version: structurize-0.13.96-ALPHA-universal.jar
latest.log: https://gist.github.com/Chrysarius/7968e05b7bda8f397f8985315babd23f
debug.log: https://gist.github.com/Chrysarius/403b2b2358af3d2af398393d11d91f33

This issue was also reported to the Minecolonies team [here](https://github.com/ldtteam/minecolonies/issues/6098), but they said to report it here instead.

**Comment by maxanier** [comment]
yeah, my bad. Fixed version available now
