### ISSUE TITLE
Hunter camps spawning on water - Streams Mod

### ISSUE THREAD

**Issue by RacerDelux** [TeamLapen/Vampirism#81]
While this does not cause crashing, seems like world gen is ok with spawning tents over the water (note it is a custom water block, so that is probably why)

Mod in question: http://minecraft.curseforge.com/projects/streams?gameCategorySlug=mc-mods&projectID=229769

Issue: https://i.gyazo.com/b87c4dbdfbbeabe1265b9898c624fa6b.png

**Comment by maxanier** [comment]
I'm not totally sure what caused this issue, but I have made some changes and wasn't able to reproduce the problem afterwards.
Please update Vampirism when the next version is released (probably this weekend).

If the problem occurs again, please reopen this issue, thanks :)
