### ISSUE TITLE
[Feature][1.16.4] Mod Compatibility: Charm

### ISSUE THREAD

**Issue by drakray** [TeamLapen/Vampirism#810]
## What would you like to have changed or added to Vampirism
There is a UI conflict with Charm's PortableCrafting Feature, where its player's inventory button overlap with yours

## Does this make the mod experience more balanced?
Irrelevant, cosmetic change

## Can you provide additional resources (etc. textures or models)
Not really no lol

**Comment by drakray** [comment]
Posted on Charm too https://github.com/svenhjol/Charm/issues/376

**Comment by Cheaterpaul** [comment]
You can modify vampirism skillmenu button with the clientconfig (https://github.com/TeamLapen/Vampirism/wiki/Configuration)
either disable the button (open the skillmenu with `p`) by changing `skillButtonEnable` to false
or move the skillmenu button with `levelOffsetX` and `levelOffsetY`

**Comment by drakray** [comment]
I don't know how I missed that!?, I'll try that right away(will offset to the left, placing the button where the vanilla recipe book would be should do the job)

Thanks, and sorry for the bother -_-' lol

**Comment by drakray** [comment]
Hi there, I tried the levelOffsetX, but it does nothing :/
the config description says "#X-Offset of the level indicator from the center in pixels", and doesn't say anything about "#Render skill menu button in inventory", which is just a true/false

**Comment by Cheaterpaul** [comment]
Sorry i didn't took another look at the actual names/description of the config value.

The config values are `overrideGuiSkillButtonX` and `overrideGuiSkillButtonY`, but we forgot to update these changes from 1.14 to newer versions.

Will be fixed in the next release.

**Comment by Cheaterpaul** [comment]
fixed with d2c12ad1
