### ISSUE TITLE
[Bug] Names displaying incorrectly for certain vampire mobs

### ISSUE THREAD

**Issue by Gartos** [TeamLapen/Vampirism#815]
## Versions
- Minecraft: 1.15.2                  
- Forge: 31.2.36                      
- Vampirism: 1.6.1                                            

- ModPack: Custom (Vampirism and at least one of the UI Mods)

## Issue Description
Mob names are not correct for some (but not all) Vampirism mobs. Infected animals seem to always be affected. Named Mobs never, although that might be because the name is changed. The basic Hunter seems to be affected allmost allways, but i have encountert vampires with the same bug. I tested with Hwyla (forge-1.10.8_B72_1.15.2), Neat (1.6-22) and The one Probe (1.15-2.0.7) and was able to replicate the Problem every time. In addition the small entity image displayed by the one probe flashes through different skins.

![2020-12-05_15 46 10](https://user-images.githubusercontent.com/24513746/101246071-32bab280-3711-11eb-8870-8394350d1d56.png)
![2020-12-05_15 28 17](https://user-images.githubusercontent.com/24513746/101245647-87106300-370e-11eb-8d1f-112d41f54f6b.png)

## Reproduce Steps
1. Have Hwyla installed
2. Have Entity information active
3. look at an affected entity (infected animals are best, cows and sheep seem to always have it, I recommend looking in a vampire forrest)

## Additional Information
The Vampirism integrations Mod does not seem to help.

**Comment by maxanier** [comment]
This should be fixed in Vampirism 1.7

**Comment by maxanier** [comment]
1.7 has been release (some time ago) this should be resolved
