### ISSUE TITLE
[Bug] Game crashes if you try to attune yourself with astral sorcery and Vampirism is installed.

### ISSUE THREAD

**Issue by fizechef** [TeamLapen/Vampirism#816]
## Versions
- Minecraft:  1.16.4
[crash-2020-12-05_18.51.47-client.txt](https://github.com/TeamLapen/Vampirism/files/5647602/crash-2020-12-05_18.51.47-client.txt)
                  
- Forge:   35.1.0                    
- Vampirism:  1.7.0 Beta 1  and earlier                                         

- ModPack: N/A

## Issue Description
Game crash.

## Reproduce Steps
Attune yourself with Astral Sorcery.

## Additional Information
Left this on the Astral Sorcery Page as well.

**Comment by Cheaterpaul** [comment]
missed to port this fix to 1.16 (#786)


fixed with aa0e8495 in next version
