### ISSUE TITLE
Configuration options for blood grinder

### ISSUE THREAD

**Issue by Pmox450** [TeamLapen/Vampirism#817]
As far as I can see within any of the configuartion files, there is no option to add or remove items to the list of grindable ones. Beyond that, an option to configure the amount of blood from a single gridned item could help balancing vamprirism especially  on servers. I have no idea of coding and how hard something like this is to impliment, but I would be glad to see it in a futer version, or maybe you can tell me, how to do it on my own.

Edit: I have noticed the textfile, which states, that I shall not edit it, so maybe you had that idea earlier.

**Comment by maxanier** [comment]
This is possible. For 1.12 it is a simple text file in your `config/vampirism` directory. For 1.14 we switched to data packs to be more streamlined with Vanilla even though it makes it more difficult to edit
Please have a look at this Wiki article
https://github.com/TeamLapen/Vampirism/wiki/Biteable-Creatures-Blood-Grinder
