### ISSUE TITLE
[Bug][1.16.4] Biomes shift after adding Vampirism to already generated world with modded biomes

### ISSUE THREAD

**Issue by drakray** [TeamLapen/Vampirism#818]
## Versions
- Minecraft: 1.16.4
- Forge: 35.1.13
- Vampirism: 1.16.4-1.7.0

- ModPack: N/A

## Issue Description
When adding Vampirism to my pack, if I start a world where the map is already generated, the modded Biomes shifts.
There is no crash, but the BYG.AlliumField become Vampirism.VampireForest, BYG.Bayou => BYG.AutumnalValley, even though I configed disableVampireForest = true in vampirism-server.toml before opening the world.(toml in world folder have the same config)
I also oldVampireBiomeGen = false
I checked in the level.dat with NBTExplorer, and vampisirm biomeId are NOT shifting the others, they are higher IDs(329 and 330)

## Reproduce Steps
Make a pack with BoP and BYG
Pregen Map, noting biome placement
CloseAll, add Vampirism
Reopen MC&world, biomes are shifted

## Additional Information
<details>
<summary>ModList</summary>

```
aawitherskull_1.16.4-1.1
additional_lights-1.16.4-2.1.3
alllootdrops_1.16.4-2.0
angelring-1.16.3-1.3.3
AppleSkin-mc1.16.2-forge-1.0.14
Aquaculture-1.16.4-2.1.7
ars_nouveau-1.16.3-1.8.1
assortedcore-1.16.4-1.0.0
assorteddecor-1.16.4-2.0.7
assortedstorage-1.16.4-2.1.0
assortedtools-1.16.4-2.2.1
AutoRegLib-1.6-47
AzureDoom-Chunk-Loader-1.16.4-1.0.0
BasaltBlocks-1.16.3-1.0.0
BetterAdvancements-1.16.4-0.1.0.103
betterbedrockgenerator-1.16.4-0.1.2
BetterCaves-1.16.3-1.0.6
BetterDefaultBiomes-1.16.4-Alpha+2.5.1
BetterMineshafts-Forge-1.16.3-1.1
biggerreactors-1.16.3-0.2.6-beta
BiomesOPlenty-1.16.4-13.0.0.425-universal
BloodMagic-1.16.3-3.0.2-7
Bookshelf-1.16.4-9.3.18
Botania-1.16.4-410
BotanyPots-1.16.4-6.0.7
BotanyTrees-1.16.4-2.0.4
Bountiful+Baubles+FORGE-1.16.3-0.0.2
BowInfinityFix-1.16.x-rv9.1
buildersaddition-1.16.4-20201203a
byg-1.1.5
caelus-forge-1.16.4-2.1.0.0
carmoury-1.16.3,4-1.1.0
carrierbees-1.16.3-0.0.2.2
Ceramics-1.16.4-1.5.2
ceramicshears-1.3.2-1.16.1+
charm-forge-1.16.4-2.1.6
chunkloaders-1.1.3-mc1.16.4
citadel-1.5.3
clib-1.16.3,4-1.5.0
collective-1.16.4-1.53
configurableextramobdrops_1.16.4-1.1
CookingForBlockheads_1.16.3-9.2.2
CosmeticArmorReworked-1.16.4-v1
CraftTweaker-1.16.4-7.0.0.63
CrockPot-1.16.3-1.2.1-release
curioofundying-forge-1.16.4-5.1.0.0
curios-forge-1.16.4-4.0.3.0
curiouselytra-forge-1.16.3-4.0.0.1
DoggyTalents-1.16.4-2.0.1.1
dropthemeat-1.16.4-1.1
DungeonCrawl-1.16.3-2.2.2
dungeons-plus-1.16.4-1.1.0
durabilityviewer-1.16.4-forge35.0.7-1.9
earthmobsmod-1.16.4-0.1.2-Beta
EnchantmentDescriptions-1.16.4-6.0.2
enderchests-1.16-1.7.5
endertanks-1.16-1.9.3
engineersdecor-1.16.4-1.1.4
EnigmaticLegacy-2.10.1
envirocore-1.16.4-3.0.4.1
enviromats-1.16.4-2.0.4.1
envirotech-1.16.4-3.0.4.1
ExtraArmor_1.16.4-1.1.4
extragolems-11.1.9
farlanders-1.16.3-1.3.4
FarmersDelight-1.16.3-0.2.4b
FarmingForBlockheads_1.16.3-7.2.1
FastLeafDecay-v25
FastWorkbench-1.16.3-4.4.1
forge-1.16.4-geckolib-3.0.0
FruitTrees-1.16.3-2.2.0
ftb-gui-library-1604.1.1.26
fxcontrol-1.16-2.0.1
gemsnjewels-1.16.4-0.18.0
glazedsymmetry-1.0
guardvillagers-1.16.3-1.1.5
Guide-API-VP-1.16.4-2.2.0
healingcf_1.16.4-3.1
Hwyla-forge-1.10.11-B78_1.16.2
iceandfire-2.1.4-1.16.4
ImmersiveEngineering-1.16.4-4.1.1-128
ImmersivePetroleum-1.16.3-3.1.0
immersiveposts-1.16.3-3.0.0
incontrol-1.16-5.0.3
infinitetrading_1.16.4-1.2
InitialInventory-5.0.1.11
inventorytotem_1.16.4-1.1
invtweaks-1.16.4-1.0.1
jei-1.16.4-7.6.0.62
jeiintegration_1.16.4-6.1.1.11
JEITweaker-1.16.4-1.0.1.5
justenoughbeacons-3.1-1.16.3
JustEnoughResources-1.16.4-0.12.0.103
kingvillager-1.6.1
Kiwi-1.16.3-3.4.1
livingthings-1.16.4-1.2.3
lumberjack-2.1.4
mana-and-artifice-1.2.0.1
Mantle-1.16.4-1.6.43
masonry-1.16.3-0.3.6
mcw-bridges-1.0.4-mc1.16.4
mcw-doors-1.0.1fix-mc1.16.4
mcws-roofs-2.0.0-mc1.16.4
mcw-trapdors-1.0.0-mc1.16.4
mcw-windows-1.0.2-mc1.16.4
moreoverlays-1.18.11-mc1.16.4
morevanillalib-1.16.4-1.3.8
MouseTweaks-2.13-mc1.16.2
mysticalchemy-0.0.7
NetherEnhanced-1.16.3-0.3
NetherPortalFix_1.16.3-7.2.1
NeverNeededOrWanted-1.16.3-1.0.5b
nhacampfire_1.16.4-3.0
observerlib-1.16.4-1.4.3
overloadedarmorbar-5.1.0
pamhc2crops-1.16.3-1.0.1
pamhc2foodcore-1.16.3-1.0.0
pamhc2foodextended-1.16.3-1.0.0
pamhc2trees-1.16.3-1.0.0
pandoras_creatures-1.16.3-2.0.1
Patchouli-1.16.4-48
phosphophyllite-1.16.3-0.2.1-beta
Placebo-1.16.3-4.3.3
polymorph-forge-1.16.4-0.18
potionofbees-1.16.4-1.1.0.2
productivebees-1.16.3-0.5.1.1
QuarkOddities-1.16.3
Quark-r2.4-279
ratlantis-1.0.0-1.16.3
rats-7.0.1-1.16.3
ReAuth-1.16-Forge-3.9.3
Regrowth-1.16.4-1.42.0.17
reliquary-1.16.3-1.3.4.1061
repurposed_structures-1.16.4-2.3.3
rsgauges-1.16.4-1.2.6-b2
shetiphiancore-1.16-3.8.4
solcarrot-1.16.3-1.9.8
storage_overhaul-1.16.4-1.0.1
StorageDrawers-1.16.3-8.2.1
structure-gel-api-1.16.4-1.7.2
supplementaries-0.9.10
swingthroughgrass-1.16.4-1.5.3
The_Undergarden-1.16.3-0.3.8
Tiny-Coal-1.16.4-1.0.0
tntbrbedrock_1.16.4-1.2
TwerkItMeal-1.3.4
u_team_core-1.16.4-3.1.16.190
useful_backpacks-1.16.4-1.11.6.86
valhelsia_structures-16.0.5
valkyrielib-1.16.4-3.0.4.3
Vampirism-1.16.4-1.7.0
vanillacookbook-1.16.4-1.10
vanillaexcavators-1.16.4-2.2.0
vanillahammers-1.16.4-2.2.0
WailaHarvestability-mc1.16.2-forge-1.1.13
WAWLA-1.16.4-7.0.2
Waystones_1.16.3-7.3.1
woot-1.16.4-1.0.2.2
WorldNameRandomizer-FORGE-1.16.4-v1.1.1
WorldPreGenerator-1.16.4-1.0.0
Wyrmroost-1.16.3-1.2.7
Xaeros_Minimap_FP20.28.2_Forge_1.16.4
xlpackets-1.1
```

</details>

**Comment by drakray** [comment]
In my old copy of level.dat, BYG.Bayou is ID.143, BYG.AutumnalValley is ID.141, BYG.AlliumField is ID.135, and there is 329 entries
In the new one, these IDs are the same, but there is 331 entries, with Vampirism at the end using V.VForest=329 and V>VForestHills=330

**Comment by drakray** [comment]
I further tested, and it seems only [BYG](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go)'s Biomes are shifted; [BOP](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)'s Biomes seems unaffected(saw Alps and ConiferousForest correctly)

EDIT: also, tested with disableVampireForest = false, with no change

**Comment by CorgiTaco** [comment]
Let's say....
The biome mods I have installed are BYG(Numerical ID's are 100 - 125), BOP(126 - 155), and Prehistoric Fauna(156 - 207).
I create a new world. the biome at 0, 0 is a PHF Hell's Creek.
Only the Biome numerical ID is saved to the chunk so... PHF Hell's Creek in this case is 157.
So biome numerical ID 157 is stored at 0, 0.
Alright... BYG just got an update and they added 3 new biomes. So what happens? Well....
The biome mods I have installed are now BYG(Numerical ID's are 100 - 128), BOP(129 - 158), and Prehistoric Fauna(159 - 210).
So now the biome at 0, 0 still has the numerical ID 157 but.... the ID's have shifted, now the biome at 0, 0 is a Biomes O Plenty Alps Biome.

I recommend that you use the latest version of your modloader as the issue has been fixed for sure.
Forge: http://files.minecraftforge.net/ or if that doesn't work, https://www.curseforge.com/minecraft/mc-mods/chocolate-fix/files
Fabric: https://fabricmc.net/use/ & https://www.curseforge.com/minecraft/mc-mods/fabric-api/files

**Comment by drakray** [comment]
I'll try ChocolateFix, because I already use the latest Forge for 1.16.4, 35.1.13

**Comment by drakray** [comment]
ChocolateFix seems to work, seem like Forge should implement it in its "Dynamic Registry" thing

**Comment by maxanier** [comment]
Thank you for sharing your solution!
It seems this cannot be resolved on Vampirism's end.
From ChocolateFix's page it sounds like the issue should only occur with data pack biomes (on the latest Forge versions), so hopefully this should occur that often
