### ISSUE TITLE
[Bug] Crash related to Hunter Villagers.

### ISSUE THREAD

**Issue by MagmaSlime123** [TeamLapen/Vampirism#819]
## Versions
- Minecraft: 1.12.2.
- Forge: 2854.
- Vampirism: 1.6.2.

- ModPack: Yes. Mods listed in the report.

Crashes due to something related to Hunter Villagers.
![image](https://user-images.githubusercontent.com/51277766/102702226-3112e380-4215-11eb-8f7e-cbe2c2168d74.png)
[crash-2020-12-19_16.10.15-server.txt](https://github.com/TeamLapen/Vampirism/files/5720333/crash-2020-12-19_16.10.15-server.txt)

Join a world.

N/A

**Comment by maxanier** [comment]
This is caused by the mod "VampirismFix" (I assume it is this one on Curse https://www.curseforge.com/minecraft/mc-mods/vampirism-spawn-remover).
It seems to be outdated and does not work with the newer 1.12 versions of Vampirism. You can try to contact its author

**Comment by maxanier** [comment]
Not really sure if that mod is good for anything anyway. I don't believe it greatly reduces lag and if it removes the hunter spawns it more or less breaks Vampirism as you cannot progress.
