### ISSUE TITLE
[Bug] [1.16.4] [Vampirism 1.7.0] Client Crash - NullPointerException

### ISSUE THREAD

**Issue by Maruhl** [TeamLapen/Vampirism#822]
[crash-2020-12-28_08.17.55-server.txt](https://github.com/TeamLapen/Vampirism/files/5746240/crash-2020-12-28_08.17.55-server.txt)

## Versions
- Minecraft: 1.16.4
- Forge: 1.16.4-forge-35.1.13
- Vampirism: Vampirism-1.16.4-1.7.0

- ModPack: N/A

## Issue Description
Client crashes while new world creating.

## Reproduce Steps
Create new Game/World.

## Additional Information
See attachement. - Null Ref/Pointer Exception: 
.... de.teamlapen.lib.lib.util.SimpleSpawnerLogic.updateSpawner

**Comment by maxanier** [comment]
Thx, for reporting. Will be fixed in the next version today or tomorrow
