### ISSUE TITLE
Biteable mobs on 1.12.2

### ISSUE THREAD

**Issue by sqikerz** [TeamLapen/Vampirism#823]
## Versions
- Minecraft: 1.12.2                    
- Forge: 14.23.5.2847                      
- Vampirism: 1.6.2                                             

I’ve tried to add biteable mobs through adding a txt file with mob IDs = amount of blood to the config files, this had worked in single player, but once I put this on my server (also had matching on my client side aswell), it displayed the blood but I could only bite and not suck.

Get MC Eternal (lite) server, try to add custom mobs.

Not sure where to get these from, will provide if the information on how to get these are given.

**Comment by sqikerz** [comment]
Side note; the icon appears when you look at a mob, but you can't suck on its blood. Also only reason I was doing this was that it did not automatically do the dynamic calculation? (Like only vanilla mobs + some, like crabs were biteable)

My file (basically every entity that you can /summon in the MC Eternal mod pack):
[https://cdn.discordapp.com/attachments/677309096856256547/793180119874535434/vampirism_blood_values.txt](https://cdn.discordapp.com/attachments/677309096856256547/793180119874535434/vampirism_blood_values.txt)

**Comment by maxanier** [comment]
Two things before I dig deeper:

- Did you test it on newly spawned entities on the server? Entities that have existed before the blood values have been added will not be affected
- Can you double check, that the file is named correctly and in the correct folder on the server? The client seems to load the values, but the server doesn't apparently

**Comment by sqikerz** [comment]
> Two things before I dig deeper:
> 
> * Did you test it on newly spawned entities on the server? Entities that have existed before the blood values have been added will not be affected
> * Can you double check, that the file is named correctly and in the correct folder on the server? The client seems to load the values, but the server doesn't apparently

I’ve summoned new entities to try it and it seems to not work for the new mobs that I’ve added.

And for the server folder, isn’t it supposed to be the same place? (Like config then place it in vampirism?). Also not sure why it says the blood values in WAWLA when I only have the config in the server and remove it from the client?

**Comment by maxanier** [comment]
Can you provide the full server log file after spawning a new creature and trying to feed from it?

**Comment by sqikerz** [comment]
[latest.log](https://github.com/TeamLapen/Vampirism/files/5751309/latest.log)
Here you go!

**Comment by maxanier** [comment]
Thank you.
It seems the blood values file is not found. Otherwise he log should contain some mention about it (either that it was loaded or that it failed to load). 
Is the `vampirism_blood_values.txt` placed alongside the `vampirims.cfg` and `vampirism_mod_compat.cfg`? 
On Windows there might sometimes be an issue with file extensions, make sure it is `vampirism_blood_values.txt` not `vampirism_blood_values.txt.txt`.

**Comment by sqikerz** [comment]
[https://gyazo.com/4877fff8c3c534999632204445263224](https://gyazo.com/4877fff8c3c534999632204445263224)

Not sure why it isn't loading.

**Comment by maxanier** [comment]
Not sure if you have enabled extension editing in Windows.
Remove the `.txt` from the file name and check again.

I just double checked and for me it is loading the file on the server and printing it to the log.
So either the file is somehow named wrong or another mod is messing with the configuration directory

**Comment by sqikerz** [comment]
Did some tests, it loads the configs when I started a new server, when I moved the world file into it, it broke again. Is there anything for me to fix or look at in specific?

**Comment by sqikerz** [comment]
Ah, I’ve deleted the vampirism folder from the world folder, it fixed the issue.

Even though the auto generated values txt is empty, it breaks it? (This might be a bug)

I am so sorry for wasting your time if isn’t a bug.

**Comment by maxanier** [comment]
Strange.
Glad you could resolve the issue
