### ISSUE TITLE
[Bug] Hunter table can not do any research after level 7+

### ISSUE THREAD

**Issue by zorc** [TeamLapen/Vampirism#826]
## Versions

- Minecraft: 1.16.4
- Forge: 35.1.28
- Vampirism: Vampirism-1.16.4-1.7.1

- ModPack: N/A

**Comment by lunofe** [comment]
You need to upgrade the research table. To do so, place a hunter weapon table, potion table and alchemical cauldron next to it.
![GIF](https://user-images.githubusercontent.com/42828197/103869683-f214d700-50ca-11eb-9ce8-236cfc530bb2.gif)
