### ISSUE TITLE
 Vampirism 1.16 1.7.1 Ability Wheel Goes To Bat Every Time

### ISSUE THREAD

**Issue by Z14D** [TeamLapen/Vampirism#827]
Whenever i try to move my mouse to use an ability it moves my cursor to the very bottom right of my screen unable to use any other ability except bat

**Comment by lunofe** [comment]
Please provide your Forge version, and a list of other mods, if any.

**Comment by Z14D** [comment]
> Please provide your Forge version, and a list of other mods, if any.

Forge 35.1.36

The modpack is Less tech More dragons on Curse launcher

**Comment by maxanier** [comment]
Cannot reproduce with the latest version of that mod pack.
Did you install any additional mods?

**Comment by Z14D** [comment]
> Cannot reproduce with the latest version of that mod pack.
> Did you install any additional mods?

Nope i play on a server that my friend recommended and i didn't add anything to the pack that is there or else i wouldn't be able to play it, but i believe its because i am using a macbook or i am using fullbright and the effect always happened to me i havent tried it in 1.12.2 but i might try it later if the problem is hardware wise or its with the mod.

**Comment by maxanier** [comment]
Have you had time to check this with 1.12? I am not really sure what I can do here.
If the issue persists, I could try changing some things in the GUI to achieve the same goal in a different way. But I currently do not have time for that, and you would have to be willing to test a few different versions then.

**Comment by Z14D** [comment]
> Have you had time to check this with 1.12? I am not really sure what I can do here.
> If the issue persists, I could try changing some things in the GUI to achieve the same goal in a different way. But I currently do not have time for that, and you would have to be willing to test a few different versions then.

sorry for the late reply but in 1.12.2 it works fine no problems it seems that the 1.16 version is bugged for me but i might try it out later in another pack

**Comment by maxanier** [comment]
If anyone else experiences the same issue, please let me know. Otherwise it is difficult to narrow this down.
