### ISSUE TITLE
Vampirism resetting after restart

### ISSUE THREAD

**Issue by DerLeon2017** [TeamLapen/Vampirism#829]
As soon as I leave my world or restart the game, the vampirism is still marked as active but no abilities are working and i have the normal hungerbar. I'm using the newest version in 1.16.4
(I have also tried it with different levels of vampirism)

Thx for any suggestions ^^

**Comment by DerLeon2017** [comment]
What i forgot, it works fine when it's the only mod installed.
Screenshot with all installed mods is attached
![Screenshot 2021-01-17 184106](https://user-images.githubusercontent.com/25402816/104851158-97158800-58f3-11eb-9c09-39b17b99a2b2.png)

**Comment by lunofe** [comment]
Please use the "bug report" template in the future. We need your Minecraft, Vampirism and Forge version. Don't use the term "latest", since it can change until and while we review your issue.

**Comment by DerLeon2017** [comment]
Okay, sorry, didn't know that. Minecraft Version is 1.16.4 with Forge 35.1.37 and Vampirism 1.7.2

**Comment by A-Table** [comment]
I'm currently experiencing the same bug. Using the same versions of Forge, Vampirism, and Minecraft. It seems that dying can also cause the same issue, but doesn't happen 100% of the time. This bug also affects Hunters. Here is the list of other mods I'm using. 
![Capture](https://user-images.githubusercontent.com/36554715/104887836-cd1d3100-5920-11eb-92cc-dbb09d7d7027.PNG)

**Comment by maxanier** [comment]
Unfortunately, I am not able to reproduce this with the given mods/versions. Potentially it requires a certain action/progress in on of the other mods.
Can you provide a client-latest log, right after this happens?

**Comment by A-Table** [comment]
[latest.log](https://github.com/TeamLapen/Vampirism/files/5833621/latest.log)

This good?

**Comment by maxanier** [comment]
Yes, thank you!. Unfortunately, I could not gain any insights from it.

Have made any specific changes to your Optifine configuration? Or did you do anything specific in IceAndFire before this happened?
Maybe you can upload your world here, so I can check if I can reproduce it with that.

**Comment by A-Table** [comment]
I hadn't done anything with IceAndFire. I uninstalled Optifine and it seemed to fix the issue. Turning off Internal Shaders and using default video settings with Optifine installed doesn't solve the issue however. It seems Optifine must be uninstalled. Reinstalling Optifine causes the issue to happen once more, even if it had been fixed from an uninstall.

**Comment by DerLeon2017** [comment]
So, i've also tried it and can confirm that it is caused by Optifine.
