### ISSUE TITLE
Compatibility with Terraforged

### ISSUE THREAD

**Issue by theCalcaholic** [TeamLapen/Vampirism#830]
## Versions

- Minecraft: 1.16.4
- Forge:  35.1.36
- Vampirism: 1.16.4 - 1.7.1
- Incompatible mod: Terraforged (presumably)
- Link to mod: https://www.curseforge.com/minecraft/mc-mods/terraforged

- ModPack: Loosely based on [Knight Academy](https://www.curseforge.com/minecraft/modpacks/knight-academy)

## Issue Description
When using Terraforged as world generator, no hunter tents will be generated.

## Reproduce Steps
1. Create new world
2. Set generator to TERRAFORGED
3. start looking for tents

## Additional Information
VampirismIntegrations is installed in version 1.16.4 - 1.4.1

**EDIT:** I just saw, that the vampire forest and vampire forest hill biomes aren't generated by terraforged either - are these biomes assigned the BiomeDictionary.Type.OVERWORLD type (as described here: https://github.com/TerraForged/TerraForged/wiki/Mod:-Biomes)?

At this point, maybe this topic should be moved to VampirismIntegrations?

**Comment by theCalcaholic** [comment]
Maybe it would be most feasible to have a generic configuration option that allows to configure biomes?

**Comment by maxanier** [comment]
The biome issue will be fixed in the next version. I missed that Forge reintroduced the BiomeDictionary.
Regarding the structures I am not sure, they should be properly registered.
I don't know if TerraForged considers modded structures properly. I could not find any information on that.

**Comment by theCalcaholic** [comment]
Thank you for the info. I'll see if I can find out more about the issue with structures.

**Comment by maxanier** [comment]
I have created an issue over at their tracker, let's see if they have some idea
https://github.com/TerraForged/tracker/issues/17
