### ISSUE TITLE
[Feature] Config for enabling batmode in the end

### ISSUE THREAD

**Issue by Silivek** [TeamLapen/Vampirism#838]
## Does this make the mod experience more balanced?
It allows it to be more malleable to tastes

## Can you provide additional resources (etc. textures or models)
None needed

Batmode doesn't work in the end, and I think that players would enjoy a config option for enabling this.

**Comment by maxanier** [comment]
There already is in server config: `batModeInEnd`

**Comment by Silivek** [comment]
On my 1.16.4 server there is only a client and common config, with neither having an option for this

**Comment by maxanier** [comment]
https://github.com/TeamLapen/Vampirism/wiki/Configuration
