### ISSUE TITLE
java.lang.NullPointerException: Exception in server tick loop

### ISSUE THREAD

**Issue by derSchotte** [TeamLapen/Vampirism#84]
Hi, a Friend gave me this crashlog. he try to generate a new world and on generation the client crashes.

Minecraft 1.9.4 / Forge 12.17.0.1968 / Vampirism 1.9.4-1.0.0-alpha+05-28-10-48

Crash report: [https://paste.ee/p/D3HMv](https://paste.ee/p/D3HMv)

**Comment by maxanier** [comment]
I'm not totally sure what caused this (there are tons of other mods installed),  
but in the Vampirism version I uploaded a few moments ago this should at least be avoided. 
So please try out that version http://minecraft.curseforge.com/projects/vampirism-become-a-vampire/files/2310245 and tell me if the crash still occurs.

**Comment by maxanier** [comment]
Did that version solve your problem?

**Comment by derSchotte** [comment]
Hi, sorry for the delay... yes Version 6 fix the Problem for him.... and Version 7 fix my Problems... XD
