### ISSUE TITLE
Crash when trying to join world

### ISSUE THREAD

**Issue by Maxi90909** [TeamLapen/Vampirism#842]
## Versions

- Minecraft: 1.16.5
- Forge: 1.16.5 - 36.0.9
- Vampirism: 1.16.4-1.7.3

- ModPack: My Own

I don't know why this is happening now. I just updated Forge more not with my current mods.

1. Load my mods (found in crash report) 2. Load a world (don't know if this happenes to create new world). 3. Wait for it to load 4. Blue Box at the top right saying failed to load world. 5. Go to singleplayer. 6. this Crash that is shown down at additional information.

## Additional Information
https://pastebin.com/VK24rUHQ (crash report)
[latest.log](https://github.com/TeamLapen/Vampirism/files/5888107/latest.log) (lastest logs)

**Comment by Maxi90909** [comment]
This is Not a Forge Problem. A Guy from the Forge Forum Team told me that

**Comment by maxanier** [comment]
I'm not really sure why this occurs, there must be some other mod involved. 
However, the related code wasn't really important anymore. So I just removed it.
Will be fixed in the next version

**Comment by Maxi90909** [comment]
Ok thank you 👍
