### ISSUE TITLE
Vampires should not be able to drink special hunter potions

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#848]
## What would you like to have changed or added to Vampirism

<!-- This may include suggesting crafting recipes, item names or places in skill tree if applicable ->>
Vampires should be unable to consume potions crafted by hunters using their special potion skills. Thx to Kranzy for pointing this out.

**Comment by Cheaterpaul** [comment]
should it be completely forbidden or should they get a debuff instead?

**Comment by maxanier** [comment]
Mhh, not sure. Maybe something similar to the hunter armor, where you receive toxicant.

But the goal is to make it practically unusable for them
