### ISSUE TITLE
Crash on breaking coffin in 1.10 Multiplayer

### ISSUE THREAD

**Issue by ironphildo69** [TeamLapen/Vampirism#85]
Hello, I was testing this amazing mod with some other mods on a multiplayer server and came across this crash when you break a coffin ether in survival or multiplayer. We do have other mods and i can confirm this is NOT an issue in a single player world with just Vampirism installed. I have attached the crash report, if you need anything else let me know :)

[crash-2016-06-27_16.40.24-client.txt](https://github.com/TeamLapen/Vampirism/files/334216/crash-2016-06-27_16.40.24-client.txt)

**Comment by ironphildo69** [comment]
Just a update, it seems to be a issue with optifine, tested it without and I didn't crash, where as everyone else did.

**Comment by maxanier** [comment]
As far as I can tell the behaviour leading to this crash is not possible in Vanilla Minecraft/Forge, so maybe you could inform the optifine devs about this.
(The tileentity renderer of an already broken [set to air] block is called)

In the mean time I've created a workaround which will be available in the next released version.

**Comment by ironphildo69** [comment]
thank you very much :) , i understand optifine is beyond your control so a work around for it is great. Ill close this issue and pass it on to the optifine devs.
