### ISSUE TITLE
[Feature] Offensive/Non-Offensive Hissing

### ISSUE THREAD

**Issue by PancakeCultist** [TeamLapen/Vampirism#850]
## What would you like to have changed or added to Vampirism
This idea comes from the idea of some Vampires being able to let out a more ear-piercing hiss, to the point where the senses of humans are rattled. My idea for this in game is that any humans (hunters or not) have their hearing turned down a bit and their vision is blurred much like the Blood Vision perk, but maybe to a lesser extent for a couple seconds. Even if the more offensive part of this idea seemed like a no-go, I would like the ability to hiss in game with a keybind of some sort.

## Does this make the mod experience more balanced?
I honestly can't tell because I have never played on a multiplayer server, but it seemed like it would be a unique idea for Vampires to either warn other players or get away from them. Plus, I also just wanna hiss in game.

## Can you provide additional resources (etc. textures or models)
While I don't have a sound myself, I'm sure you could modify the hissing in the game in some way.

**Comment by lunofe** [comment]
I actually like the idea. Sooo, who's gonna go record the hissing sounds? 😂
Anyways, maybe the H key could be the standard hotkey for normal hiss and the "super hiss" would be a skill with a certain cooldown then? Maybe like 5 minutes at least, if it has the effects described above.

**Comment by PancakeCultist** [comment]
> 
> 
> I actually like the idea. Sooo, who's gonna go record the hissing sounds? 😂
> Anyways, maybe the H key could be the standard hotkey for normal hiss and the "super hiss" would be a skill with a certain cooldown then? Maybe like 5 minutes at least, if it has the effects described above.

I could record it, or find someone who can. Idk I can look into it. Otherwise, I could try looking for some sort of stock sound to heavily modify into a hiss?

Also, another idea I had since I want the "super hiss" to have some practicality outside of multiplayer... This could de-aggro zombies attacking you, and make other mobs run. However some mobs that are tough might not run, examples being other vampires, endermen, ravagers, vindicators (I just think the vindicators are too insane to realize what they're dealing with and charge you anyways lol).

If we can't find someone to make a hissing sound effect, perhaps something similar, like a roar or something idk 😂

**Comment by froggystain** [comment]
Your idea kinda reminds me of the 2010 game Aliens vs Predator. If you played a xenomorph you had a hiss function that lured the marines to a certain place or scared scientists. At least, that's how I remember it 😊
