### ISSUE TITLE
[Feature] Add task to reset skills

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#853]
## What would you like to have changed or added to Vampirism

Maybe it would be nice to add a task that resets the skillpoints (without loosing an level).

## Does this make the mod experience more balanced?
It would be more integrated into the game instead of being just a GUI button

**Comment by Cheaterpaul** [comment]
This could be a unique task that resets after completing it, which means that you can complete the task anytime and repeatedly.

Or add a consumable that resets you skills (maybe even with an additional effect such as requires you to sleep). This variant could integrate  #849. The consumable could either be crafted or obtained by completing tasks

**Comment by Marsmalo** [comment]
I see like a misc item that you need to have in order to have the reset skill button works.

**Comment by Cheaterpaul** [comment]
^^ at the moment i am working on a Potion of Oblivion. It removes your skills one by one when consumed.
