### ISSUE TITLE
[Bug] Calculating blood values does not work

### ISSUE THREAD

**Issue by ri-nath** [TeamLapen/Vampirism#855]
### Versions

- Minecraft: 1.16.4
- Forge: forge-1.16.5-36.0.22
- Vampirism: Vampirism-1.16.4-1.7.4
- Modpack: Custom (https://www.technicpack.net/modpack/motorpack-2.1815086)

### Issue
https://github.com/TeamLapen/Vampirism/wiki/Biteable-Creatures-Blood-Grinder
This wiki page describes how values for mobs are dynamically calculated at runtime, and placed in a file named `world/vampirism/dynamic-blood-values.txt`. However, this is not working on my world. The world has been running for almost a week now, and the `dynamic-blood-values.txt` only has two lines:

```#Dynamically calculated blood values - DON'T EDIT
mysticalworld:venison=1
```

**Comment by Cheaterpaul** [comment]
What values would you expect to be shown?

What type do these entities have? (animal, zombie, villager ...)



Vanilla entities have assigned blood values through datapacks https://github.com/TeamLapen/Vampirism/wiki/Biteable-Creatures-Blood-Grinder#114

**Comment by ri-nath** [comment]
I have many mods such as Animalium, Creatures & Beasts, and Better Animals Plus which add lots of mobs (which I assume are typed animals) to the world. I would expect at least some of them to be listed. Perhaps the mobs they add aren't typed as animals, although that would be odd?

**Comment by Cheaterpaul** [comment]
there was an issue in the calculation that should be fixed in the next version
