### ISSUE TITLE
[Bug] Crash when entering other mod dimensions

### ISSUE THREAD

**Issue by optmisticnihilist** [TeamLapen/Vampirism#858]
## Versions

- Minecraft: 1.16.4
- Forge: 35.1.37
- Vampirism: 1.7.5

- ModPack: Custom

## Issue Description 
Game Crashes when enter mod dimensions of The Abyss: Chapter II, Moon Mod With New Material and BloodCraft 5 or on portal creation if the mod supports immersive portals.  The Nether, The End and dimension for Neverdark does not crash. 

The logic for reporting here is that disabling vampirism resolved issue with the Moon and BloodCraft mod. Have not tested Abyss again for other reasons.
 

## Reproduce Steps
Create Portal and enter.

## Additional Information
[crash-2021-02-15_14.13.06-server.txt](https://github.com/TeamLapen/Vampirism/files/5997800/crash-2021-02-15_14.13.06-server.txt)
[crash-2021-02-17_11.03.10-server.txt](https://github.com/TeamLapen/Vampirism/files/5997805/crash-2021-02-17_11.03.10-server.txt)

**Comment by maxanier** [comment]
Thx for reporting.
Hmm, I thought I specifically tested this, but apparently messed up somewhere.

Can you go set `enforceOverworldTentGeneration` to false in `config/vampirism-common.toml`?
I think that should serve as a workaround until fixed.

**Comment by optmisticnihilist** [comment]
It's working now with abyss. Unfortunately it's not screaming land of eternal night to me but that a me problem.
