### ISSUE TITLE
[Bug] Issue in the server console

### ISSUE THREAD

**Issue by Taknax** [TeamLapen/Vampirism#859]
## Versions

- Minecraft: 1.12.2
- Forge: 14.23.5.2855
- Vampirism: 1.6.2

- ModPack: In the future Taknaxpack (or Taxpack). Not finished atm.

I got a issue in my server console. Its not a chrash. The issue is:
Server thread/WARN [vampirism]: [EntityEventHandler]Could not replace creeper target task

Install minecraft and forge on server. Install vampirism. Run server. Watch console.

**Comment by maxanier** [comment]
This is some mod conflict. Avoiding this would require a lot of effort.
The only effect is that the Avoided by Creeper skill will not work
