### ISSUE TITLE
[Feature] Garlic beacon activation delay

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#861]
## What would you like to have changed or added to Vampirism

Delay activation of garlic beacon upon placement.

Somehow communicate this to players clearly.

Maybe only in multiplayer.

## Does this make the mod experience more balanced?
Garlic beacons are not intended as an offensive gadget

**Comment by Marsmalo** [comment]
This would be great for making the village easier to defend from Vampire attacks! Make the beacon for both factions or will end up in the same spot that we already are: Vampires are extremely weak! And Hunters extremily powerful.
You could implement too a potion made with the Orchid that gives immunity (temporaly like 20min) to the player to garlic and thus the vampire will be able to save this village from the terrible Hunters!  And the Vampire beacon could be a reward after becoming a Prince.
