### ISSUE TITLE
[Feature] Making the Vampire Evolution be more rewarding like the hunters.

### ISSUE THREAD

**Issue by Marsmalo** [TeamLapen/Vampirism#863]
> Devs I'm not entirely sure of what your thoughts on what the vampire should be in this mod: Disease? Blessing? Curse? I would love to know, that could help me understand better the role of the vampires in this mod and probably help you guys out on the skill lines that look a mess to me right now.

## What would you like to have changed or added to Vampirism

- Vampire cloaks can be enchanted as Breastplate reducing exposure to the sun in 50% making the sun no lethal anymore but slowing down and giving nausea (maybe blindness?) to the player after long exposure (5min) and can gives the player the elytra passive or slow fall (used at the same time with a Breastplate, create a new slot only for the cape) and only obtainable by a quest after you become baron or other title and can be dyed after that. _(please don't make the quest boring like collect 100 stuff of 3 different items)_

-  Heartseeker and Heartstriker can be fully enchanted like a normal sword (and still used only by vampires).

- Normal fire resistance potions can be used by the vampire player (because it's a vanilla feature and some of us use to get Netherite)

- Take out that Freeze skill and put up a skill that sucks the blood of your opponents (dealing damage, blind and slow to them and healing you, CD 2min and the duration 1min) in a "circle" (like an swarm of bats or a mist) 

- About the useless skill Swarm of Bats that blind people that get near them and no one would ever think of using that because it requires staying in a form that only makes you have 2 hearts, _if someone fart near you it's instant DEATH_!! Jokes aside, I thought about creating a new skill and switching slots with this new skill. We put the Advanced Bite where Swarm of Bats were and the new skill were Advanced Bite was: Wielding Power: can craft/enchant Vampiric Weapons and enchant the Cloak!

- The Vampire wasn't suppose to be a undead creature? So why only the Zombies don't attack him? Skeletons and Creepers should ignore him too.

- I thought about removing one of the skills that reduce sun damage and put a skill that drains the target health and heal the user. Dealing 0.5 hearts of damage and dures 10s and has 15s of CD.

## Does this make the mod experience more balanced?

It will bring balance because it will requires the player to get the last level and grind really hard and make him to play the most aspect character of a vampire: time brings wisdom and strenght. So only a powerful vampire knows that the immortality is what brings him the power over all other races. _(Beside his natural reflexes, strong like a 100 men etc)_

**Edit:** Vampire Swords* (Ultimate Version) are the only viable ones to use because the enhanced is weaker compared to a netherite full enchanted. And the skill: Swift as the Wind makes a Netherite Sword full enchanted deal more DPS than a Enhanced Sword. So that's why I'm asking for making the Vampiric Swords be able to recieve all the normal enchants because that will bring more balance because the Hunters have in their arsenal stronger potions like Strong level 3 etc. Remember how hard it's to find a Vampiric Sword in ultimate version and so frustrating not being able to use them as main sword because they don't have the mending effect.

_*Vampiric Swords Ultimate Version **should be** stronger than Netherite and Enhanced Swords and only wield by Vampire Lords (like a unlockable skill after finishing a quest, but still only obtainable looting chests or crafting)_
Thank you all.

**Comment by maxanier** [comment]
Will/Is partially addressed in the 1.8 update
