### ISSUE TITLE
entity selectors not working in 1.16

### ISSUE THREAD

**Issue by jeroen11122005** [TeamLapen/Vampirism#865]
## Versions

- Minecraft: minecraft 1.16.5
- Forge: forge 36.0.40
- Vampirism: 1.7.6

- ModPack: N/A

## Issue Description
The entity selectors are not working at all, whenever I try to use one it says "unknown option 'vampirism'" and doesn't execute the command

## Reproduce Steps
enter a world with cheats enabled
try using commands with the selectors

## Additional Information
![image](https://user-images.githubusercontent.com/42644683/109203208-28ee9b80-77a4-11eb-8698-cad3bcfbf1b3.png)

**Comment by PendragonII** [comment]
Try: `/kill @e[type=!#vampirism:vampire]`

Note that the `!` means "kill everything but vampire entities." The command your probably seeking is `/kill @e[type=#vampirism:vampire]` which means "kill every vampire entity."

**Comment by maxanier** [comment]
> Try: `/kill @e[type=!#vampirism:vampire]`
> 
> Note that the `!` means "kill everything but vampire entities." The command your probably seeking is `/kill @e[type=#vampirism:vampire]` which means "kill every vampire entity."

That works for killing the vampire entity type. But there are specific entity selectors https://github.com/TeamLapen/Vampirism/wiki/Commands-and-Cheats#entity-selectors-as-of-version-11 which appear to be bugged

**Comment by maxanier** [comment]
Ok, seems they just require quotes now:
`/kill @e["vampirism:faction"="vampirism:vampire"]`
I have updated the Wiki accordingly.

An alternative would be to not use a colon, but this makes it clear it is a modded selector
