### ISSUE TITLE
[Bug] Advanced NPCs Do Not Spawn

### ISSUE THREAD

**Issue by PendragonII** [TeamLapen/Vampirism#866]
## Versions

- Minecraft: 1.16.5
- Forge: 36.0.22
- Vampirism: 1.7.6
- ModPack: No additional mods loaded

## Issue Description

Advanced Vampires and Advanced Hunters do not spawn, the spawn eggs for both NPCs continue working. Singleplayer and multiplayer worlds are both affected.

## Reproduce Steps

- Create a new Minecraft singleplayer world
  - (Optional) More World Options > World Type > Single Biome = Vampirism
  - (Optional) Game Mode = Creative
- Roam the Vampire Forest seeking Advanced Vampires
  - (Optional) execute `/vampirism level vampirism:vampire 14` and purchase the skills *permanent speed boost* and *vista*, they will aid the exploration
- Notice the abundance of Vampire Barons and the nonexistence of Advanced Vampires

- Once it is confirmed that Advanced Vampires are not spawning, place down massive amounts of Hunter Tents across a large land mass
- Watch Hunters spawn, however Advanced Hunters do not 

## Additional Information

When watching Hunter Tents spawn Hunter NPCs you can periodically use `/kill @e[type=vampirism:hunter_imob]` to remove and refresh the spawning of Hunter NPCs.

**Comment by maxanier** [comment]
They do spawn as intended.
Advanced vampires do not spawn in the vampire forest, but only in Zombie biomes.
Advanced hunters are only spawned in larger naturally generated camp sites.

While double checking this, I have noticed that they might rarer than intended, so we might have to tweak that a bit

**Comment by maxanier** [comment]
Apparently there was a bug in the tent generation that cut advanced hunter generation by half.
Also their respawn limit wasn't always reset after one day
