### ISSUE TITLE
[Bug] Vampires do not spawn

### ISSUE THREAD

**Issue by Imaginigamer** [TeamLapen/Vampirism#867]
I have a minecraft server and I took the vampire hunter route, next to my house I had a vampire village but I cured it. The problem is that vampires no longer appear, only vampires appeared in that village (I have not found more vampire villages) but I cured it, and I went to a forest of vampires but they still do not appear.

**Comment by lunofe** [comment]
Please use English for future comments. We need your Minecraft, Forge and Vampirism version to help you.

**Comment by Darkaji** [comment]
I have the same problem, with the Minecraft version 1.12.2, Forge version 14.23.5.2854 and Vampirism version 1.6.0. I have others mods, can you help me?

**Comment by lunofe** [comment]
> I have the same problem, with the Minecraft version 1.12.2, Forge version 14.23.5.2854 and Vampirism version 1.6.0. I have others mods, can you help me?

@Darkaji Sorry, but 1.12.2 is only getting updates for game breaking bugs, that are caused by Vampirism. I've used the latest 1.12.2 for a long time and can confirm that your issue must be caused by other mods, configurations, etc. as it does work as intended if only Vampirism is installed.
