### ISSUE TITLE
[Bug] Village Totems

### ISSUE THREAD

**Issue by Piklach** [TeamLapen/Vampirism#868]
## Versions

- Minecraft: 1.16.5
- Forge: 1.16.5 - 36.0.21
- Vampirism: 1.16.4 - 1.7.6
- Vampirism Integrations: 1.16.4 - 1.5.0

- ModPack: N/A

## Issue Description
When mining base of totem, it drops 2 totem bases. This applies to both fragile and normal totem tops. 

## Reproduce Steps
Mine base of totem. 
(https://youtu.be/_oOF0AZV5tQ)

**Comment by maxanier** [comment]
Thx for reporting. Fixed in the next release.
While a video is never bad, for such issues it isn't really worth the effort :D
