### ISSUE TITLE
[Bug] Vampirism entity event handler causing massive lag?

### ISSUE THREAD

**Issue by Yourname942** [TeamLapen/Vampirism#869]
## Versions

- Minecraft: 1.16.5
- Forge: 36.0.42
- Vampirism: 1.7.4

- ModPack: [The Land of Super Friends](https://www.curseforge.com/minecraft/modpacks/the-land-of-super-friends)

## Issue Description
Something is causing an extreme amount of lag, and it seems to be an entity event hanlder - a task 

[27Feb2021 17:41:01.493] [Server thread/INFO] [de.teamlapen.vampirism.entity.ModEntityEventHandler/]: Unknown zombie entity type dungeons_mobs:armored_zombie for zombie target task

[27Feb2021 17:43:02.852] [Server thread/INFO] [de.teamlapen.vampirism.entity.ModEntityEventHandler/]: Unknown zombie entity type betterdefaultbiomes:frozen_zombie for zombie target task

## Reproduce Steps

1. be on a multiplayer server
2. Become a vampire
2. find a zombie spawner
3. player who is a zombie was mining and doing his thing for a while around the area around/below it
4. other players were experiencing a lot of lag and high ping.

## Additional Information
latest log: https://gist.github.com/Yourname942/2dfc101ee48eb8140a2602c81810c327
spark profile: https://spark.lucko.me/#nNEIA5Bgjm

**Comment by maxanier** [comment]
Pretty confident that the `ModEntityEventHandler` is not responsible for the lag.
The zombie AI changes are only executed once per zombie spawn, so at most every few seconds. Also they do not require a significant computation time.

I'm not sure why you are pinpointing Vampirism for this. The log you mentioned only occurs two times and in the profile I cannot see anything indicating that Vampirism is taking up more time than usual. Many other mods in the profile show higher computation time
