### ISSUE TITLE
Issue with commands not running in command blocks

### ISSUE THREAD

**Issue by xTheArchiTektx** [TeamLapen/Vampirism#871]
So the commands added by the Vamparism mod do not run in command blocks, at least not in always active, unconditional, repeating command blocks. If you copy and paste the command from the command block it runs in the chat but won’t run in the command block. One example of how I wanted to use this was to give the sunscreen effect for a few minutes if a vampire walks up and clicks the shrine.

verson 1.16.5

**Comment by Cheaterpaul** [comment]
And what command should the command block execute?

**Comment by xTheArchiTektx** [comment]
wow that was fast, sorry wan't expecting a reply so quickly. The command is:

/execute at @p if score @p Blood_Timer matches 100 run vampirism bloodBar
fill @p

the player must have their Blood_Timer scoreboard score = 100, on
further testing it seams the sunscreen effect works, but commandblocks with
actual vampirism commands don't seem to run.

**Comment by maxanier** [comment]
This was caused by the command requiring permission level 3 while the command blocks only have level 2.
This should be the only affected command though. E.g. level works
