### ISSUE TITLE
[Bug] - Server crash - Ticking block entity - TotemTileEntity

### ISSUE THREAD

**Issue by Rutes** [TeamLapen/Vampirism#872]
## Versions
- Minecraft: 1.16.5
- Forge: 1.16.5-36.0.46
- Vampirism: 1.16.4-1.7.7

- ModPack: Less Tech More Dragon

## Issue Description
server crashes when a player enters a specific area with Vampirism village capture totem 

## Reproduce Steps
I launch my server, player approaches the area, server crashes.

## Additional Information
crash log in https://github.com/WRLTech/Less-Tech-More-Dragon/issues/6

**Comment by Cheaterpaul** [comment]
Do you mean it crashed only the first time you got there but after a restart/reload every thing works?

**Comment by maxanier** [comment]
@Cheaterpaul 
We definitively need a null check there, just getting a TileEntity from a cached position can always be null.
The only question is what to do in that case... Just delete the cached position ... One possible scenario would be that in large villages the other totem's chunk isn't loaded yet. If it is loaded later on, it would probably be destroyed, right? Or do we have any mechanism for that in place

**Comment by Rutes** [comment]
Similar crash again today - crash report here: https://github.com/WRLTech/Less-Tech-More-Dragon/issues/6

full logs if you like: https://gist.github.com/Rutes/1b931d95ca1935a11394f2c4123f9d0e

Looks like it was a different totem in another area this time. So maybe it's crashing upon creation of the totem when a player is exploring? After a reboot the area seems fine.

![image](https://user-images.githubusercontent.com/5608566/110719674-dd3fe700-81d2-11eb-810c-49222081ff88.png)

**Comment by maxanier** [comment]
Should be fixed in the latest version, thx for reporting
