### ISSUE TITLE
[Modcompat] Minecolonies

### ISSUE THREAD

**Issue by Mondrethos** [TeamLapen/Vampirism#873]
## Versions

- Minecraft: 1.16.5
- Forge:  64.0.46
- Vampirism: Vampirism-1.16.4-1.7.7.jar
- Incompatible mod: Minecolonies
- Link to mod: https://www.curseforge.com/minecraft/mc-mods/minecolonies

- ModPack: N/A

When you drain the blood of a minecolonies villager all the way, they never regenerate blood again.

Find a minecolonies villager, drain them fully (when the vampire fangs cursor is gone) and they never regenerate blood agian or turn into a vampire or anything.

**Comment by Cheaterpaul** [comment]
This is caused because the maximum damage a citizen can receive is `maxhealth/5`

https://github.com/ldtteam/minecolonies/blob/e5753b7ad4d84027c04eb7fbb33c5cb2736c506b/src/main/java/com/minecolonies/coremod/entity/citizen/EntityCitizen.java#L1288
