### ISSUE TITLE
Config option for vampire health

### ISSUE THREAD

**Issue by Sadzony** [TeamLapen/Vampirism#875]
As said in the title,

I looked through the extensive balance options but couldn't find the config for vampire mob health. I'm getting a mod compatibility bug where some named (advanced) vampires spawn with maximum 1 health, and thought that if there's a general config value for this, i would be able to override that.

**Comment by Cheaterpaul** [comment]
TODO: think about importing [BalanceMobProps](https://github.com/TeamLapen/Vampirism/blob/52145b65a7f260856693b30c9de5f835d39db146/src/main/java/de/teamlapen/vampirism/config/BalanceMobProps.java) into the config again.
