### ISSUE TITLE
Compatibility with Repurposed Structures mod

### ISSUE THREAD

**Issue by Sadzony** [TeamLapen/Vampirism#876]
## What would you like to have changed or added to Vampirism
Make the biome variants of villages added with Repurposed structures (https://www.curseforge.com/minecraft/mc-mods/repurposed-structures) have the capturing mechanic and ability to spawn hunter houses.
## Does this make the mod experience more balanced?
More variety in villages, makes the villages spawned in modded biomes have Vampirism integration

**Comment by TelepathicGrunt** [comment]
If you need help with getting houses to spawn in my villages, check out this PR I made to Waystone that basically does just that https://github.com/ModdingForBlockheads/Waystones/pull/354

Alternative, you don’t need any code to add new pieces to my villages. Instead, in the data/repurposed_structures folder, create a pool_additions folder and put the same path to the pool file you want to add to. Then make a template pool file with just your building entry alone and my log will automatically import it into my pools. Here’s an example datapack that does this: https://github.com/TelepathicGrunt/RepurposedStructures/releases/tag/0.0.3

the pools addition is a recent thing added to my mod and it is really cool! Only issue is users can’t really turn it off with configs so maybe doing this compat in code would be best for the option to do a config. Or you can make a datapack for compat instead and give it to me so I can list it on my mod page for others to download. Lots of options

**Comment by Cheaterpaul** [comment]
we should probably add modified hunter trainer templates
