### ISSUE TITLE
Allow mod enchantments to be applied to Vampirism items

### ISSUE THREAD

**Issue by Jackiecrazy** [TeamLapen/Vampirism#879]
## What would you like to have changed or added to Vampirism

Allow vampire swords and hunter crossbows to be enchanted with enchantments from other mods.

## Does this make the mod experience more balanced?
In modded games that include a great number of enchantments, the weapons are often outclassed by others via enchantment superiority (e.g. vanilla crossbow+crescendo of bolts from apotheosis+multishot). It makes finding rare weapons rather disappointing. Besides, all armor can already receive every enchantment, so why not weapons as well?

## Can you provide additional resources (etc. textures or models)
I don't think it'd be particularly necessary in this case.

**Comment by Cheaterpaul** [comment]
Was implemented in 296af4c2
