### ISSUE TITLE
Description: Rendering Block Entity

### ISSUE THREAD

**Issue by derSchotte** [TeamLapen/Vampirism#88]
Hi, i craft a coffin and place it on the ground. i try to brake it with the pickaxe and MC crashes.

[Crash-Log](https://paste.ee/p/SQOzH)

**Comment by maxanier** [comment]
See issue #85, pretty sure that is Optifine's fault, but the next Vampirism version will contain a workaround

**Comment by derSchotte** [comment]
Version 7 works with Optifine and Shader on... thanks
