### ISSUE TITLE
[Bug] advanced vampires spawn with minimal(1) health

### ISSUE THREAD

**Issue by EnderMelody** [TeamLapen/Vampirism#881]
## Versions

- Minecraft: 1.16.5
- Forge: 36.1.0
- Vampirism: 1.16.4-1.7.8

- ModPack: N/A

## Issue Description
advanced vampires, both summoned and naturally spawned, spawn with basically zero health. I tried loading only vampirism in a fresh instance, and they still spawned like this.

## Reproduce Steps
install vampirism
find or summon an advanced vampire
use some method to view health... or just punch and insta kill them

## Additional Information
[latest.log](https://github.com/TeamLapen/Vampirism/files/6153663/latest.log)
![2021-03-16_23 49 59](https://user-images.githubusercontent.com/12649140/111412892-9b6fde80-86b3-11eb-8488-2cf2c85dd330.png)
![2021-03-16_23 50 27](https://user-images.githubusercontent.com/12649140/111412900-9dd23880-86b3-11eb-8a5c-df2100451414.png)

**Comment by lunofe** [comment]
Fixed by [fd26279](https://github.com/TeamLapen/Vampirism/commit/fd26279b32790730337bdd6d593dc40e8a8f5825)
