### ISSUE TITLE
[Modcompat]

### ISSUE THREAD

**Issue by TheRighteousLion** [TeamLapen/Vampirism#883]
Hello, I have Vampirism and Epic Siege together in a modpack, the passive Vampire Hunter mob is affected by the Epic Siege Mob AI, I have tried all the minecraft: Vampire_Hunter and vampirism: vampire_hunter that I can think of in the mod config, I don't know why they are attacking me and each other still, Please Help ;(
 

## Versions

- Minecraft: 1.12.2
- Forge:  1.12.2  14.23.5.2854
- Vampirism: 1.12.2  1.6.2
- Incompatible mod: Epic Seige Mod
- Link to mod: https://www.curseforge.com/minecraft/mc-mods/epic-siege-mod

- ModPack: Custom

**Comment by lunofe** [comment]
In 1.12.2, only bugs that break the game will be fixed. This sounds more like a problem with Epic Siege Mob AI than with Vampirism. The ID of the Hunter NPCs is `vampirism:vampire_hunter`.

**Comment by maxanier** [comment]
https://github.com/TeamLapen/Vampirism/issues/374#issuecomment-450708157
