### ISSUE TITLE
Vampire Books do not work on Barons[Bug]

### ISSUE THREAD

**Issue by Spindelle** [TeamLapen/Vampirism#884]
## Versions

- Minecraft: Java
- Forge: 1.16.4
- Vampirism: 1.16.4- 1.7.8

- ModPack: N/A

## Issue Description

I know how to reach Vampire level 15 but when I try to use the Vampire Book on a baron level 5, it simply will not work. It opens the book to read it and it reads "Invalid book tag". I've searched everywhere on the internet to see if this is a bug for anyone else but I found nothing.

## Reproduce Steps

 Go into Creative. Spawn a level 5 Baron. Spawn a Vampire Book. Use said book on Baron. (Creative Mode method)
Go into survival. Hunt vampires until the other type of vampire book is found. Use that on a naturally spawned Baron lvl 5. No results. No possibility of getting a lvl 6 Baron.

## Additional Information

I have used both the Vampire Book and the other books dropped by Advanced Vampires, neither work.

**Comment by lunofe** [comment]
Level 15 is only in Vampirism 1.12.2
