### ISSUE TITLE
[Bug] Vampire villagers can despawn/reset trades?

### ISSUE THREAD

**Issue by Jackiecrazy** [TeamLapen/Vampirism#885]
## Versions

- Minecraft: 1.16.5
- Forge: 36.1.0
- Vampirism: 1.7.8

- ModPack: N/A

It seems that vampire villagers are either despawning and respawning or resetting their trades and expertise every so often. This applies to every villager, including the vampire expert and sometimes the representative, which makes trading much less useful. I'm not sure if it's the same villager I'm looking at between trading sessions, since they leave for their houses during the day and I spend much time caving, but they'll have different trades and novice level by the time I get back.

1. find or create a vampire village
2. place a workstation somewhere and trade with the vampire villager who goes there, such that they level up
3. go do something else, maybe a few chunks away
4. come back and trade with whoever now works at that workstation

As an aside, Eidolon zombie brutes will still attack vampire villagers, and converting villagers manually in vampire villages will still raise their prices when trading.

**Comment by Cheaterpaul** [comment]
This is an old issues that i can not reproduce. Feel free to reopen the issue, if this bug is still present
