### ISSUE TITLE
[Feature] Custom in-game Skin Modifier for Vampires

### ISSUE THREAD

**Issue by Tanjim-Fuad-Arik** [TeamLapen/Vampirism#888]
## What would you like to have changed or added to Vampirism

 
Add Custom Skin Modifier for Vampires.
I am not telling to remove the premade fangs and eyes, but to make it more better.
Like…

-  Sometimes people have derp skins.

![derp](https://user-images.githubusercontent.com/62837144/112421305-fc08b680-8d58-11eb-8f54-dcf6249e4c9a.png)

- Sometimes they have chest over head skins.

![chesthead](https://user-images.githubusercontent.com/62837144/112421347-0fb41d00-8d59-11eb-8540-952a92ce677c.png)

Or Sometimes People just want to make their own changes to their skins.

## Does this make the mod experience more balanced?

Probably. It makes the skins more better.
Especially to me.

## Can you provide additional resources (etc. textures or models)

I dont think there is anything that is needed here.

**Comment by Tanjim-Fuad-Arik** [comment]
Please add this feature. Thank you.

**Comment by lunofe** [comment]
I don't know if this is worth the effort. We already have multiple eye & fang layouts that should probably cover 95% of the skins, and there's also the option to disable both overlays.

**Comment by maxanier** [comment]
I agree with Zin, adding an ingame texture editor would be a very large effort for a very limited usecase.
Just in case someone wants to PR this in the future, I will leave this open, but don't expect it to be implemented.
Players can always modify the eye textures using a resource pack. Of course this is only shown for the ones using that resource pack
