### ISSUE TITLE
[Bug] Crossbow related crash with Not Enough Enchantments

### ISSUE THREAD

**Issue by bettertest** [TeamLapen/Vampirism#889]
## Versions

- Minecraft: 1.15.2
- Forge:  31.2.50
- Vampirism:  1.7.1

- ModPack: N/A

## Issue Description
[crash-2021-03-26_18.06.43-server.txt](https://github.com/TeamLapen/Vampirism/files/6214844/crash-2021-03-26_18.06.43-server.txt)
When a hunter shots their weapon (crossbow) the system crash happnes.

## Reproduce Steps
Seems to happen when the hunter mob fires their crossbow, however, it's been happening more frequently.

**Comment by maxanier** [comment]
This is a bug in Not Enough Enchantments
It was confirmed by its author, but they have not released an update so far
https://www.curseforge.com/minecraft/mc-mods/not-enough-enchantments/issues/6

#771

**Comment by bettertest** [comment]
thank you very much

**Comment by maxanier** [comment]
There will be a workaround in the next 1.15 vampirism version as NEE is kind of abandoned?
However, it will only affect hunter mobs (not players) and will simply prevent them from shooting
