### ISSUE TITLE
[Bug] Turtle Master Potions

### ISSUE THREAD

**Issue by Piklach** [TeamLapen/Vampirism#890]
## Versions

- Minecraft: 1.16.5
- Forge: 36.0.21
- Vampirism: 1.7.8

- ModPack: N/A

## Issue Description
Bypass the turtle master potion's slowness effect, by wearing opposite races armour for a second.

## Reproduce Steps
Drink a turtle master potion,
Wear an armour piece of the opposite race (hunters wear vampire cloak),
Remove the armour piece,
Slowness effect from the turtle master potion disappears.
https://youtu.be/Ivbv9lV0X5o

**Comment by maxanier** [comment]
Thx for reporting. 
Actually the bug is much more severe, taking damage will always remove any slowness effect ^^
