### ISSUE TITLE
[Feature] Vampire Claw Attack

### ISSUE THREAD

**Issue by Wubadubb** [TeamLapen/Vampirism#891]
## What would you like to have changed or added to Vampirism
When fighting a mob, it feels weird to imagine spamming them with bites. I feel like it would make more sense to have certain perks that relate to claws and upgrading them, sort've like the old poisonous and tough fangs. This could be when unarmed to add a special playstyle for vampires, also removing bite spam.

## Does this make the mod experience more balanced?
It would be a neat way to integrate & upgrade both an old and current feature. 

## Can you provide additional resources (etc. textures or models)
That stuff is outta my skill range. All I feel like would be needed is maybe a slash effect like the sword sweep move.

**Comment by maxanier** [comment]
I agree that the bite spam does not really make sense.
The bite attack will be removed in the next major update.
But I'm not sure about the claws, while it sort of fits to vampires I think it is best to reserve this to the werewolf faction from the WIP addon
