### ISSUE TITLE
[Feature] Smart Village Vampire

### ISSUE THREAD

**Issue by Wubadubb** [TeamLapen/Vampirism#892]
## What would you like to have changed or added to Vampirism
As far as i'm aware, vampire NPC's dont care at all about conserving blood in vampire owned villages. I feel like it would be way, way less annoying if the NPC's reframed from turning the villagers and harassing them, maybe even killing zombies since villagers are their main food source.

## Does this make the mod experience more balanced?
Oh god yes it is so annoying having a vampire owned village just for the vampire npcs to slaughter/infect my entire food source.

## Can you provide additional resources (etc. textures or models)
I don't think any would be needed.

**Comment by maxanier** [comment]
Hmm, this should already be a thing, I will look into that
