### ISSUE TITLE
[Bug] Vampire Cloak clipping through player

### ISSUE THREAD

**Issue by VampireTechnologyLord** [TeamLapen/Vampirism#893]
## Versions

- Minecraft: 1.16.5
- Forge: 36.0.14
- Vampirism: 1.16.4-1.7.4

- ModPack: N/A

## Issue Description
If you sneak, the cloak of a vampire player clips through the player. This also happens in Multiplayer and Singleplayer worlds.

## Reproduce Steps
1. Become Vampire
2. Equip any vampire cloak
3. Go into `<F5>` - Mode
4. Sneak
![2021-03-27_11 37 53](https://user-images.githubusercontent.com/75166884/112718206-c945f600-8ef1-11eb-9164-9e37ae7ca7df.png)

## Additional Information
Here are screenshots of how the cloak looks without sneaking and with sneaking.
![2021-03-27_11 37 56](https://user-images.githubusercontent.com/75166884/112718209-cc40e680-8ef1-11eb-8a6e-2374c0186d93.png)

**Comment by lunofe** [comment]
confirmed in v1.7.8 as well
