### ISSUE TITLE
[Feature] Vampire immortality

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#894]
## What would you like to have changed or added to Vampirism

When receiving lethal damage from certain damage sources, vampire players will go to a DBNO (down but not out) state.
In this state they are invulnerable and are in sleeping pose, but can be finished off using a stake and probably holy water.
In this state the DBNOed player has a screen allowing them to choose to die or wait a defined time span and then resurrect. 
Upon resurrection they receive a effect giving multiple debuffs. Furthermore all blood (-1) is converted to health. 
While the debuff is active it is not possible to go to DBNO when receiving lethal damage.

The delay before being able to resurrect is decreased with higher vampire levels.

New skill: Debuff effect duration (and amplifier) is reduced.

**Comment by VampireTechnologyLord** [comment]
I especially like the idea of the debuff reduction, since you are undead, but still able to get withered, poisoned etc. This would become very useful, because hunters are able to brew extremely long and strong potions.
