### ISSUE TITLE
[Feature] Configfile for Entity Bloodvalues

### ISSUE THREAD

**Issue by VampireTechnologyLord** [TeamLapen/Vampirism#902]
## What would you like to have changed or added to Vampirism

I think it would be a great addition to the mod, if there would be a configfile, in which you can manually adjust the bloodlevel per entity. That way, you could alse add blood values for entities from other mods, which would definitely be useful for players with more then just this mod. Maybe you could also add a true/false statement in the file, wether the entity can be infected (and become a vampire creature) or not.
## Does this make the mod experience more balanced?
It doesn't makes the mod experience more balanced, it just makes the mod more configurable.

## Can you provide additional resources (etc. textures or models)
the file could look like this:
![image](https://user-images.githubusercontent.com/75166884/112970931-ffcc7c80-914e-11eb-8f3b-125f57773942.png)

**Comment by Cheaterpaul** [comment]
You can already change or set blood values for all entities with datapacks.
Take a look at https://github.com/TeamLapen/Vampirism/wiki/Biteable-Creatures-Blood-Grinder for further information.

If you want to disable the convertibles you can the the blood value to 0, enable it for modded entites is only available when it is added to the mod directly see https://github.com/TeamLapen/Vampirism/wiki/Biteable-Creatures-Blood-Grinder#adding-a-new-convertible-creature
