### ISSUE TITLE
blood bottles dont fill when biting a mob [Bug]

### ISSUE THREAD

**Issue by EnderJon** [TeamLapen/Vampirism#905]
## Versions
 

- Minecraft: 1.16.5
- Forge: 36.1.3
- Vampirism: Vampirism-1.16.4-1.7.8

- ModPack: N/A

## Issue Description
When biting a mob, it fills up the blood bottle once, but then moves on to the next bottle, then fills that one up once, I cant fill them up more than once,

## Reproduce Steps
I have all of these mods installed on a 1.16.5 server: 
- Vampirism 
- Biomes o’ plenty
- Vampirism Integrations
- Chisels and Bits
- Waystones
- Create
- MMO mod
- Quark
- Aquaculture 2
- Building Gadgets
- Blood Magic
- Gravestone mod
- Caves and Cliffs mod
- Inventory Pets
- BetterEnd
- Angel Ring
- When Dungeons Arise
- Repurposed Structures
- Artifacts
- Curios API
- Curious Armor Stands
- Sophisticated Backpacks
- Outvoted 
- Security Craft
- MrCrayfish’s furniture mod
- Clumps
- CC:Tweaked
- DynmapForge

**Comment by maxanier** [comment]
Does this also happen when you only have blood/glass bottles on your hotbar?

**Comment by Anesca38** [comment]
Hi I had the same issue with that set up.
It did fixed itself after i restarted the game however.
I did not had the chance to test if it happened when i only had blood/glass bottle in my hotbar.

## Versions
* Minecraft: 1.16.4
* Forge: 35.1.37
* Vampirism: Vampirism-1.16.4-1.7.8
* ModPack: custom one

## Issue Description
When biting a mob, it fills up the blood bottle once, but then moves on to the next bottle, then fills that one up once, I cant fill them up more than once,

## Reproduce Steps
I have all of these mods installed on a 1.16.4 client

* Akashic Tome
* Apotheosis
* AppleSkin
* Architectury API (Forge)
* Astral Sorcery
* AutoRegLib
* Biomes O' Plenty
* Blood Magic
* Bookshelf
* Botania
* Carry On
* Citadel
* Cloth Config API (Forge)
* Create
* Curios API (Forge)
* Eidolon
* Enchanted Book Redesign
* Fast Leaf Decay
* GeckoLib
* Guide-API Village and Pillage
* Immersive Engineering
* Just Enough Items (JEI)
* Just Enough Resources (JER)
* Light Overlay (Rift/Forge/Fabric)
* Mana and Artifice
* Mouse Tweaks
* Nature's Aura
* ObserverLib
* Ore Excavation
* Patchouli
* Placebo
* Psi
* Rats
* Spice of Life: Carrot Edition
* Storage Drawers
* Traveler's Backpack
* Vampirism - Become a vampire!
* Vampirism Integrations
* Wawla - What Are We Looking At
* Waystones
* Xaero's Minimap

## Additional Information

**Comment by maxanier** [comment]
Thanks for letting us know

@EnderJon Did it also work again after a restart for you?

When this happens the next time, please check if removing all other items from the hotbar solves the issue. And if so, try to find out which item is causing trouble
