### ISSUE TITLE
[Modcompat] Bat fly is not working - Create: Stuff Additions

### ISSUE THREAD

**Issue by somanen** [TeamLapen/Vampirism#911]
## Versions

- Minecraft: 1.16.5
- Forge:  36.1.0
- Vampirism: 1.16.4-1.7.8.jar
- Incompatible mod: Create : Stuff Additions
- Link to mod: https://www.curseforge.com/minecraft/mc-mods/create-stuff-additions/files/3264520

- ModPack: N/A

## Issue Description
When You are A vampire and use the bat mode you can not fly.

## Reproduce Steps
1.Become a vampire
2.Get to level 4
3.Unlock bat mode skill
4.Can not fly

**Comment by maxanier** [comment]
This is likely something that a bug on Create: Stuff Additions side and their handling of creative fly with their armor.
Since that mod is not Open Source I cannot see what they are doing.
Please raise an issue on their side

**Comment by rameth17** [comment]
So Ive been having the same issues and that creat mod i just removed, but i still cant fly in bat mode, here is the mod list im using could it be any of these mods? Maybe its one of the magic mods???


Just gonna uninstall most and play with a few ive now dumbed it down to 91 mods.


AI Improvements
Akashic Tome
Animated Recipe Book
Apotheosis
Ars Nouveau
AttributeFix
AutoFish for Forge
Automatic Doors
Automatic Tool Swap
AutoRegLib
Babel
Bad Wither No Cookie - Reloaded
Better Advancements
Better Bedrock Generator
Better Burning
Better Creeper Griefing [Suggestion]
Better End Sky (Forge)
Better Muffling
Better Respawn
Better Spawner Control
Better Than Mending
Better Title Screen
Better Weather - Seasons, Blizzards, and more!
Better-Shields
BetterDefaultBiomes
BetterEnd (Forge)
BetterGolem
Book Display
Bookshelf
Botania
Botany Pots
Botany Trees
BuildPaste
Caelus API (Forge)
Clumps
CollectiveConstruction Wand
Corpse
Corpse Complex
Cosmetic Armor Reworked
Craftable Elytras Mod 1.16.x
Crafting Expansion
Curio of Undying (Forge)
Curios API (Forge)
Curious Elytra (Forge)
Customizable Elytra
Death Finder
DeathQuotes / Death Quotes
Dimension Teleport
Dragon Drops Elytra
Easy Diamond
Easy Elytra Takeoff
Easy Emerald
Easy Magic
Easy Netherite Mod
Easy Piglins
Easy Recipes for uncraftable items!
Easy Shulker Access
Easy Updates🔨
Easy Villagers
EasySlimeBlock
ElekLib
Enchanting Books
Enchantment Descriptions
Farmer's Delight
Farmer's Delight Cookbook Addon
Fast Leaf Decay
FastFurnace
FastWorkbench
GeckoLib
Godly Vampirism
Guide-API Village and Pillage
Harvest Sprites
In Control!
Iron Chests
JourneyMap
Just Enough Items (JEI)
Just Enough Piglin Bartering
Just Enough Resources (JER)
Mana and Artifice
Mantle
Mass Key Unbinder
McJtyLib
Miner's Helmet
Mob Grinding Utils
Mod Name Tooltip
More Craftings
Mystical World
Nature's Compass
Neat
Neko's Enchanted Books
Netherite Elytra
NetherPortalFix
Patchouli
Placebo
Polymorph (Forge)
Reap Mod
ReAuth
Refined Storage
Repair Chests
Ring of Teleport [FORGE]
Smaller Nether Portals
Sophisticated Backpacks
Spawner Bug Fix
SwingThroughGrass
T_Rawwww__`s Epic Loot
Torchmaster
Trample Stopper
TrashSlot
Traveler's Backpack
Tree Harvester
Useful Backpacks
Vampires Need Umbrellas
Vampirism - Become a vampire!
Vampirism Integrations
Waystone
Wither Skeleton Tweaks
XP Tome
YUNG's API (Forge)
YUNG's Better Mineshafts (Forge)

**Comment by maxanier** [comment]
I'm closing this as the original issue can only be fixed on "Stuff Additions" side. For rameth17 issue I can't do much unless you narrow it down further. Anything that introduces creative like fly could be interesting
