### ISSUE TITLE
[Modcompat] Blood bottles are emptied through repair 

### ISSUE THREAD

**Issue by Mrdestruch** [TeamLapen/Vampirism#914]
## Versions

- Minecraft: 1.16.5
- Forge:  36.1.4
- Vampirism: 1.7.8
- Incompatible mod: Ring of Repair
- Link to mod: https://www.curseforge.com/minecraft/mc-mods/ring-of-repair-forge

- ModPack: N/A

## Issue Description

The blood from the blood bottles disappears by itself when the repair ring is in the inventory . The blood disappears gradually.

**Comment by Cheaterpaul** [comment]
This is a issue with Ring of Repair as they are missing a check. The Ring of Repair from the Gobber mod works though.

I created an issue there https://github.com/kwpugh/gobber/issues/95

**Comment by Cheaterpaul** [comment]
they fixed the issue and uploaded a new version
