### ISSUE TITLE
[Bug] Vampire forest fog disappears when using shaders.

### ISSUE THREAD

**Issue by FlameHunt** [TeamLapen/Vampirism#915]
## Versions

- Minecraft: 1.16.5
- Forge: 1.16.5 - 36.1.0
- Vampirism: 1.16.4-1.7.8

- ModPack: N/A

## Issue Description
When i use shaders with Optifine, the fog of vampire forest disappear completely and inside the forest everything looks perfectly as if you were a valley outside the forest. I tried with most popular Shaders in Minecraft and it happens with all of them. Any suggestions or fixes?

## Reproduce Steps
You simply activate the shaders inside or outside the forest, and the vampire's fog disappears.

## Additional Information
I didn't get any crash or something like that, but it ruins the gaming experience and gives the hunters an advantage.

**Comment by lunofe** [comment]
Hi, that's because shaders change the way the image you see is rendered on a higher level. Most shaders remove the vanilla fog entirely to replace it with their own, which then isn't controllable by Vampirism.
