### ISSUE TITLE
Hunter Weapon Table not working - FastWorkbench

### ISSUE THREAD

**Issue by schindlershadow** [TeamLapen/Vampirism#920]
## Versions

- Minecraft: 1.16.5
- Forge: 36.1.1
- Vampirism: 1.7.8

- ModPack: Private

## Issue Description
Hunter Weapon Table not working

Hunter Weapon Table
https://cdn.discordapp.com/attachments/430336806010224650/835235393329823794/unknown.png

Skills:
https://cdn.discordapp.com/attachments/430336806010224650/835240110919516160/unknown.png

## Reproduce Steps
Hunter player with required skills obtained opens a Hunter Weapon Table and enters the crafting recipe, the output for the recipe does not show up

## Additional Information
vampirism_integrations        |1.5.0  

Modlist:
https://pastebin.com/raw/4MSAwVkt

**Comment by maxanier** [comment]
Thank you for reporting this issue.
Unfortunately, I cannot reproduce it with Vampirism alone, so it seems to be an issue with another mod.
Since I don't want to manually download all those mods, our best bet would be to have a look at the `debug.log`.
Can you start the game try to craft the crossbow and then upload your `debug.log`. Thank you

**Comment by schindlershadow** [comment]
Entire debug.log (3mb):
https://drive.google.com/file/d/1u41ETqIlZOPWrB9MRlDgtyvuH4bDA_4E/view?usp=sharing

grep vamp debug.log  -i:
https://pastebin.com/raw/QEw61JbE

I can provide a private modpack profile if needed for testing

**Comment by maxanier** [comment]
Thank you! A private modpack would be great. The log sadly doesn't contain anything helpful.
If you don't want to link it here, you can send a link to dev@maxgb.de or DM it on Discord

**Comment by schindlershadow** [comment]
Email and Discord DM sent.

Thanks for looking into this.

**Comment by maxanier** [comment]
Thank you, it seems some mod is locking the recipe or preventing Vampirism from unlocking it.
If do disable the `doLimitedCrafting` gamerule everything works fine.

Usually the recipe is unlocked once you unlock the weapon table skill, so some mod seems to be interfering.
I have also noticed some mod giving me crafting XP or something when I use the vanilla crafting table. Do you have an idea what mods might mess with crafting/recipes/recipe unlocks?

**Comment by schindlershadow** [comment]
That is Project MMO but removing it does not solve the issue. 

I have identified the mod causing the issue, it is FastWorkbench. A workaround is to use a different mod "FastWorkbench Minus Replacement" which "has out of the box support for all simple modded crafting tables without the need to hard dep on FastWorkBench"

Sorry for wasting your time but hopefully if someone else has this issue this will point them in the right direction.

**Comment by maxanier** [comment]
Thank you for identifying the offending mod and sharing your workaround.

I will reopen this issue, as I plan to investigate why exactly this is happening and if a workaround or at least a warning message is appropriate
