### ISSUE TITLE
Hunter village takeover never finishes

### ISSUE THREAD

**Issue by CFlatFlat** [TeamLapen/Vampirism#924]
## Versions

- Minecraft: 1.16.5
- Forge: 36.1.0
- Vampirism: 1.7.8

- ModPack: Custom

When trying to take over a vampire village as a hunter, I get to the point where only one defender remains. However, they never spawn. I've tried teleporting every kind of vampire to me with no luck. This prevent me from ever taking over a village as a vampire. Eventually the hunters just despawn.

Also: Advanced vampires seem to always spawn with only one health, and the stake's crosshair sometimes isn't red when it should be (when the vampire I'm looking at would be insta-killed if I attack).

1. Become a hunter
2. Find a vampire village (not hard since 95% of them vampire ones, perhaps even more so than in 1.12.2)
3. Initiate the raid, and kill every vampire that spawns until you're in the second phase with only one vampire remaining
4. Get stuck because the last one never spawns (and eventually all of the hunters despawn)

I've tried this 4 times between 2 different worlds with the same result each time

Not sure if I should put anything here yet.

**Comment by Cheaterpaul** [comment]
All entities that are relevant for the second phase of the capturing are already spawned.
By ringing the bell all entities of the opposing faction are being highlight.

Please test if there are still highlighted ones in the village area.

**Comment by CFlatFlat** [comment]
I wasn't killing the villagers. I never played a hunter before so I didn't know you had to kill the villagers too.

**Comment by maxanier** [comment]
I assumed this is resolved then?
