### ISSUE TITLE
extrem blood lose [Bug]

### ISSUE THREAD

**Issue by HandsomeJacc** [TeamLapen/Vampirism#928]
## Versions

- Minecraft: 1.12.2
- Forge: 14.23.3.2679
- Vampirism: 1.12.2-1.6.2

- ModPack: N/A
- after Humans Platinum

## Issue Description
while runig or juming in the game i have an extrem blood lose i cant even sprint 100 blocks bevor i have no blood anymore
problem at any vampir level

**Comment by maxanier** [comment]
Are you using a modpack? (Not sure if "after Humans Platinum" is supposed to describe a modpack)
Or did you change any configuration?

Please double check the `config/vampirism/balance/vampire_player.cfg` to make sure
`blood_exhaustion_basic_modifier` is `0.7` and `exhaustion_modifier_max` is equal to `1`.
You can probably also just delete that file or run `/vampirism resetBalance`.

https://github.com/TeamLapen/Vampirism/wiki/Configuration---1.12
