### ISSUE TITLE
[Feature]Reply to Vampirism 1.8 Preview live and my thoughts

### ISSUE THREAD

**Issue by Marsmalo** [TeamLapen/Vampirism#929]
> Hi Devs, it's me again! Thank you very, very much for all your effort to make this mod amazingly good! Hope you all are doing extremely good and safe.

## What would you like to have changed or added to Vampirism
So, after watching the stream vod (2h after it ended, sorry I couldn't watch it live), I was so glad that you guys are making so much improvement on the Vampires! But still, I have some suggestions to make! So. here we go:
First of all: _The Skill Tree!_ 
I was wondering how good it is to hunters to play together since all the tree brunches work well together (the garlic one should recieve some attention, minor buffs that I'll explain later) but the Vampire skill line is... Sorry I really don't know what it is. We don't have a skill line that gives the player the vampire archetype that lives and hunts alone, or the vampire that like to have cattles and minions to do their work! Or even the ones that likes to be among mortals because they see them as a funny being to toy with.
So after explaining my thoughts let me show you guys what I mean:
**The Creature of the Night:**
This skill line aims to focus on a solo play, focused on combat and survivability.
-**Vampiric Rage** = stays the same (the ring effect is gracious but take off that penalty, isn't good at all)
-**Focused and Deadly** = means that a vampire using a vampire sword would swing their weapon faster like a lightning strike! (Double the attack speed permantly when using a trained sword) Piercing the enemy and slicing them in a blink of an eye, vampires go chop chop. (Hunters to counter that effect should use holy water to burn their flesh and slow them down and use crossbows, let's emphasize the ranged gameplay that is left forggoten for too long);
-**Finisher** = lets keep the execution passive but on every mob  and player (including vampires) and give it a lil bit more look: after the vampire kills a living or dead (vampires hehe) being, he engorge himself in blood making him not to loose hunger for 1min; 
-**Immortal Predator** = Armor stacks and water don't give you weakness (so you can outmatch hunter armor) and doesn't slow your attacks or movement, you're able to walk normally again (yeah not recieving any penalties, the sun damage still applies!! Let's remember that most of the player base is actually playing online) and for the cringe people here goes a solution: potions hunters, use the potions, there is more than resistance and strong potions in the game.
-**Predator** = This skill will give the player a lower rate for hunger loss and will be satisfied with less blood and can see entities through walls like merging Frugal Vampire, Blood Vision and Advanced biter;
-**Night Walker** = Night time is when the Vampires are strong, after the sun goes out and moon rises, fear is what the mortals think, when the Kings of the night go out to feed and control what is theirs for the taken! Jump Boost 2, Speed boost 2,Strenght 2, survives fatal damage but slows you down (damage limiter) and now people cry: Resistance (the golden apple one) during the night time, in the end and in the nether these effect is permantly.

---------------------------------------------------------------NEXT-------------------------------------------------------------------------

**The Immortal Prince**
This skill line aims in making your minions do the work for you, fighting, gathering resources for you need, you are their Master and you should feel that way.
-**Obedience** = Your minions now can gather wood, coal and random loot from lootable chests (like the enchantment soul speed 3);
-**Charismatic Leader** = Your minions recieve a small bonus of health and damage near you (like 5 hearts and strenght 1);
-**Vengence is a cold dish** = After a minion is defeated in battle you and your minions enter Frenezy and gain Regeneration 2 for 1min and Strenght 3 for 15s; 
-**Eternal Army** = Skeletons and Zombies near you will defend and protect you;
-**Swore to Protect** = You now can level up your minions up to level 10 and after reaching that point, their last level give you 2 points to spend in their attributes;
-**The Ruler** = When surrounded by your minions you will gain Strenght 2 and Resistance (like the golden apple) and now can have up to 8 minions.

------------------------------------------------------------LAST----------------------------------------------------------------------------
**The Eternal Noble**
This is the playstyle for the people who love to play collaboratively, but still likes to be on top because they are the top notch.
-**Not a sun fan** = Can now craft an umbrella and WALK DURING THE DAY!! 
-**Charming Personality** = Have permanently discount from all kind of traders in the game, can choose to not have their vampiric appeance AND if they are attacked, every peaceful mob will turn hostile to the attacker. (Careful who you HUNT!);
-**Charming and Deadly** = Crossbows and Bows do more damage after 50 meters and Headshots does double damage. (OMG who thought about a RANGED VAMPIRE? Works pretty well with the outfit enchanted!)
-**Night Kiss** = Feeding during the night on PLAYERS or Villagers grants you 30min of Regeneration 2, Strenght 1, Jump Boost.
-**Higher Status** = Your charming personality makes every gossip falls into your ears, making you know who is who. Now you can detect Hunters, similar to Garlic blood vision. But now works through walls.
-**Don't you dare** = Freezes everything around the player for 20s making the Vampire choose to instakill it or fly away. Killing will decrease the CD hability. (10min irl, each kill decreases 1min).

## Does this make the mod experience more balanced?
Indeed it does. After that changes we now can have an explicity skill tree for each of the 3 archetype of players that we see in the server or how they wanna play in their singleplayer world. The changes that I suggest to make in the garlic diffuser are: slowness 3 and blindness. 

## Can you provide additional resources (etc. textures or models)
Not now, but if it's to be implemented I will try my very best to help.

**Comment by maxanier** [comment]
Thank you for your feedback. Some skill tree rearrangements are incorporated in 1.8.
Most suggested new skills are either too overpowered or too difficult to implement :/
