### ISSUE TITLE
[Bug] CTD when non vampire players punch vampires

### ISSUE THREAD

**Issue by Oxbower** [TeamLapen/Vampirism#930]
## Versions

- Minecraft: 1.16.5
- Forge: 1.16.5-36.1.16
- Vampirism: Vampirism-1.16.5-1.8.0-alpha+20210508-1759

- ModPack: N/A - using mods without a modpack

## Additional Information
[crash-2021-05-10_16.08.37-client.txt](https://github.com/TeamLapen/Vampirism/files/6454541/crash-2021-05-10_16.08.37-client.txt)

**Comment by maxanier** [comment]
Thank you for reporting. I forgot to remove some test code.
