### ISSUE TITLE
[Feature] GUI Sun bars toggler

### ISSUE THREAD

**Issue by DarkEnergy13** [TeamLapen/Vampirism#932]
(Sorry for the poor grammar)
Can you add a separate disable button for the effect of being in sunlight? I enjoy Vampirism but the sun effect is giving me headaches.

**Comment by maxanier** [comment]
You can do this by editing the config.
Either set `maxYellowBorderPercentage` in the balancing config to `0` to remove just the yellow border.
Or set `renderScreenOverlay` in the client config to `false` to disable any overlay.
