### ISSUE TITLE
Adding a blood extractor to draw blood from meat

### ISSUE THREAD

**Issue by 0richrdd** [TeamLapen/Vampirism#933]
**Blood Extractor (Portable)**
A blood extractor that vampire players can use to draw blood from the meat of mobs such as pigs or cows.
- The amount of blood drawn can vary depending on the meat.
- The flesh without blood would become another element called; Dried meat
- Dried meat can be cooked into bone powder.
- Enough blood could be drawn from each meat to fill at least half a bottle or one.

**Blood Extractor (Small Structure)**
It is like an altar or structure (it can be 3x3, I don't know) in which we will have to put a live mob and kill it to extract much more blood than to suck from a mob directly or with a portable blood extractor.
Logically it extracts more blood when all the blood of the murdered mafia falls into the structure and not much blood will be lost, this method of blood extraction being more effective
- It would be like a ritual and using this method the mob would not release meat.
- The blood drawn would be enough to fill at least 2 bottles of blood
**Large bottle for blood**
More blood could be stored, obviously because it is larger than the common bottle, this will be done with a full blood bottle and 8 glasses.

**I just give you my idea, I would like you to add at least some of what I said, at least to vary the blood collection methods.**

**Comment by maxanier** [comment]
It isn't as detailed as you propose, but there is the blood grinder. You place it on-top of a blood sieve and put a blood container below the sieve. Then you can throw meat into the grinder and get blood

**Comment by maxanier** [comment]
Does that fulfill your needs
