### ISSUE TITLE
[Bug] Screen goes black when I activate blood vision

### ISSUE THREAD

**Issue by 0richrdd** [TeamLapen/Vampirism#934]
## Versions

- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2855
- Vampirism: 1.6.0

- ModPack: Personal Use
I don't think I have to upload my modpack, These are the names taken from the crash report.

https://pastebin.com/06fdv7Xz

## Issue Description
Not much to say, the screen just goes black when I turn on blood view, even though I press ESC, I can't see anything unless I turn it off

## Reproduce Steps
Just activate blood vision

## Additional Information
I don't know if they can use whatever. This crash report is generated when there was incompatibility between MalisisDoors and Dynamic Surroundings, I just removed Dynamic Surroundings and was able to play

Crash Report: 
[crash-2021-05-15_17.35.49-client.txt](https://github.com/TeamLapen/Vampirism/files/6488416/crash-2021-05-15_17.35.49-client.txt)

**Comment by maxanier** [comment]
Yeah, this is Optifine (and maybe shaders).
On 1.15+ things work fine with Optifine.
a) Optifine breaks many things
b) Even if it was fixable, 1.12 is not supported by us anymore
So either remove Optifine or forgo blood vision (or play a modern MC version), sorry.
