### ISSUE TITLE
[Bug] Fire and Ice Mod causing Ticking Entity Errors with Vampirism and Ice and Fire Mod

### ISSUE THREAD

**Issue by Antitect** [TeamLapen/Vampirism#935]
## Versions

- Minecraft: 1.12.2
- Forge: 1.14.23.5.2854
- Vampirism: 1.6.2

- ModPack: Custom Modpack (Based off Roguelike Adventures and Dungeons)

## Issue Description
When attempting to spawn an entity in the Ice and Fire mod, the game crashes with a Ticking Entity error. Through trial and error I have narrowed it down to Vampirism and Ice and Fire being the conflicting mods.

## Reproduce Steps
1. Download both Vampirism and Ice and Fire mods and start Minecraft
2, Start any new world in creative
3. Spawn any Ice and Fire mob

## Additional Information
Crash report here: 
[crash-2021-05-15_22.06.13-client.txt](https://github.com/TeamLapen/Vampirism/files/6488660/crash-2021-05-15_22.06.13-client.txt)

**Comment by maxanier** [comment]
If I follow the reproduce steps, everything works fine.
Also, there are several 1.12 modpacks that include both Vampirism and IceAndFire and work just fine.
So it cannot be Vampirism (alone).
How did you narrow it down to Vampirism?

**Comment by Antitect** [comment]
> 
> 
> If I follow the reproduce steps, everything works fine.
> Also, there are several 1.12 modpacks that include both Vampirism and IceAndFire and work just fine.
> So it cannot be Vampirism (alone).
> How did you narrow it down to Vampirism?

@maxanier I essentially kept adding and removing mods, testing which ones the issue would happen. Once I removed the Vampirism mods, it started working normally again. Basically, I trial and error'd by removing and re-adding different mods until I eventually removed Vampirism, Vampirism integrations, and Vampires Need Umbrellas, at which point it began working again

**Comment by maxanier** [comment]
But can you reproduce it with just Vampirism and IceAndFire?
