### ISSUE TITLE
Faction raids

### ISSUE THREAD

**Issue by FurryApocalypse** [TeamLapen/Vampirism#936]
## What would you like to have changed or added to Vampirism
Hello there.
I would like to suggest some sort of raids from oposite factions that could take over your village from time to time. This could be totally random or counted by days. There could be also possibility to create some item that you could use on village totem to summon a faction raid if needed. 

## Does this make the mod experience more balanced?
Why do I want to see such an idea in the future? The answer is simple. Village capturing is an integral part of class progression. It is a cool idea indeed but when you come to the conquering village quests there is a huge problem caused by huge amount of exploration or you will need to wait/beg (if player of opposite faction just don't want to take over villages) others to capture villages. Even with exploration there are villages that have no faction allegiance so if you're unlucky you have to go over thousands of blocks just for one hostile village.

That's just an idea. Of course if someone doesn't want to have such features it could always be configurable to be turned off.

**Comment by maxanier** [comment]
See #931 #598  :D
