### ISSUE TITLE
[Bug] Server crash when player joins

### ISSUE THREAD

**Issue by HenrikoMagnifico** [TeamLapen/Vampirism#938]
## Versions

- Minecraft: Minecraft 1.16.5
- Forge: Forge 36.1.0
- Vampirism: Vampirism 1.7.8

- ModPack: Magnifico Pack

## Issue Description
The server crashes whenever a specific player joins the game (presumably because a chunk is loaded with a corruption tile or entity inside it?)

## Reproduce Steps
Unknown how this was caused, there is no way to tell how to reproduce. Maybe use Magnifico Pack, start a server and become a lvl 5 hunter?

## Additional Information
The crash occured after the player in question had played on the server for a few days. They were a level 5 "Hunter" at the time of the crash and have not been able to join the server since, simply resulting in a server crash whenever they try to join.

## Crash log:
[crash-2021-05-18_14.44.07-server.txt](https://github.com/TeamLapen/Vampirism/files/6502202/crash-2021-05-18_14.44.07-server.txt)

**Comment by Cheaterpaul** [comment]
this is fixed by 3096231a.
Please update to Vampirism 1.16.4-1.7.10
