### ISSUE TITLE
1.16.5 Advanced Vampires not Spawning or not visible after spawning[Bug]

### ISSUE THREAD

**Issue by volldersuchter** [TeamLapen/Vampirism#939]
## Versions

- Minecraft: 1.16.5
- Forge: 36.1.0
- Vampirism: 1.7.10

- ModPack: Self made one(can List all 80 mods if neccesary)

## Issue Description
I have found only a single advanced vampire in 2-3 hours of playing
I have tried removing all of the leaves in the 2 separate forests and fly around it to find any but so far nothing. In my statistics I can see that I killed a single advanced Vampire. I tried boosting the spawns with /kill @e[type=vampirism:vampire] and /kill @e[type=vampirism:vampire_baron] many many times over killing hundreds of them. Then I fly around everywhere and don't find a single advanced Vampire so I do /kill @e[type=vampirism:advanced_vampire] and kill like 3 of them but I can not find any of them what so ever. 

## Reproduce Steps
Same as written in Issue Description:

I tried boosting the spawns with /kill @e[type=vampirism:vampire] and /kill @e[type=vampirism:vampire_baron] many many times over killing hundreds of them. Then I fly around everywhere and don't find a single advanced Vampire so I do /kill @e[type=vampirism:advanced_vampire] and kill like 3 of them but I can not find any of them what so ever. 

## Additional Information
-run on Sever 
-no crashes

this might be important: We had the Server running for about two weeks before we installed Vampirism onto it but so far it doesn't seem to have created issues: The Bioms spawn, Hunters spawn, Advanced Hunters spawn, the Villages spawn and nothing has conflicted with our other mods like BiomsOPlenty

General Stats of me:
-killed 313 Vampires so far              
-killed 100 Vampire Barons so far
-killed 99 Vampire Hunters
-killed one Advanced Vampire

Also sorry I could not find how to add a flair for 1.16.5 this is my first Issue (:

edit: About an Hour after posting this I have since doubled this number and have killed 650 Vampires and 150 Vampire Barons and have not found or killed a single Advanced Vampire
I also get that this mod is supposed to be grindy but not being able to level up a single level in hours of searching especially considering that the drop rate of books is 5% (not sure if implemented but I read that you wanted to implement a 1% increase of drop chance of books per level of looting) then I would probably have to grind for weeks in order to level up more than a few level or make the server lag more from discovering a lot of stuff and also having to grind hundreds of loot chest is a lot less fun for me than killing mobs.

**Comment by maxanier** [comment]
Can you check if `advancedVampireSpawnChance` in the world balance config file is set to `23` and if so increase it to something like 70.
https://github.com/TeamLapen/Vampirism/wiki/Configuration

**Comment by jpaulo-rb** [comment]
Hello, I am having a similar problem, I think it may be the cause of the same problem mentioned above, 99% of advanced vampires are being born with 1 life, there is a very small chance that they will be born with a normal life. Perhaps because they are born this way, they die before seeing them.

**Comment by maxanier** [comment]
Oh, damn, we forgot to include that fix in 1.7.10. The next version (later today) should fix  that.
If the original issue still persists, please test my last suggestion.

Regarding `/kill @e[type=vampirism:advanced_vampire]`: If you are hunter or human in SP, you will probably have to use `/kill @e[type=vampirism:advanced_vampire_imob]` instead
