### ISSUE TITLE
Sun does not damage certain vampire players [Bug]

### ISSUE THREAD

**Issue by Dng52** [TeamLapen/Vampirism#942]
## Versions

- Minecraft: 1.16.5
- Forge: 36.1.0
- Vampirism: 1.7.8

- ModPack: Self-compiled

## Issue Description
There are currently 3 players that have turned into vampires. 1 (the first person to turn) takes damage from the sun as intended. The other 2 that turned after do not take damage from the sun. They are not in any of the biomes that prevent sun damage (the ones listed in Vampirism Integrations).

## Reproduce Steps
Currently unsure how to reproduce the steps. We can try to convert more players to vampires and see if the result is no sun damage.

## Additional Information
- There have been no crashes due to this bug
- Vampirism has been installed since day 1 of server start
- Mods that interact with Vampirism on the server include Vampires Need Umbrellas and Vampirism Integrations

**Comment by lunofe** [comment]
Sun damage is being dealt from level 4 upwards, are the other two players maybe below that?
