### ISSUE TITLE
[Feature]Vampire lords [including players] can become demons

### ISSUE THREAD

**Issue by gshdg** [TeamLapen/Vampirism#944]
_**Vampire lords [including players] can become demons**_

-It's the idea I got from the movie Van Helsing.

-You can have a skill to make the vampire Lord bigger, have a pair of wings to fly, have a tall figure, sharp and long claws, and have a devil's head. [including players can also have it]

**Comment by maxanier** [comment]
Might eventually come with https://github.com/TeamLapen/Vampirism/issues/757
