### ISSUE TITLE
[Feature] Crossbows needs animation

### ISSUE THREAD

**Issue by RandomDovah** [TeamLapen/Vampirism#946]
## What would you like to have changed or added to Vampirism
Crossbows are excellent weapons for hunters but they are lacks any animations. I suggest to remove sword attack animation and make it hunters players will hold usual/doubled/semi-automatic crossbows like hunters NPC when they are aiming. Also I suggest to make it hunters players will hold semi-automatic crossbow (when your other hand isn't hold another item) like vanilla Minecraft loaded crossbow and there will be the same look from the 1st person. And I suggest to make it that crossbow model will have a bowstring that will change it look to loose version for a moment after shoot and will reclaim previous look after that.

## Does this make the mod experience more balanced?
I guess many hunters using crossbows and now it doesn't look like they are trying to shoot, but looks like they are trying to hit an enemy or throw their crossbows at him, but instead of that bolt is appear and start flying. It doesn't ruin mod experience so much but looks like crossbows are WIP.

## Can you provide additional resources (etc. textures or models)
Not need I guess

**Comment by Cheaterpaul** [comment]
With Vampirism 1.9 all crossbows have the same loading animation and view angle as the vanilla crossbow.
