### ISSUE TITLE
[Bug] Vampire books not existing

### ISSUE THREAD

**Issue by Birbus69** [TeamLapen/Vampirism#950]
## Versions

- Minecraft: 1.16
- Forge: 36.1.31
- Vampirism: 1.7.12

- ModPack: N/A

## Issue Description
I tried to look at how to get a vampire book on JEI but the book doesnt exist at all? the item itself doesnt exist and can't get it with /give either

## Reproduce Steps
I really don't know

## Additional Information
None

**Comment by zaze06** [comment]
i have the same problem

**Comment by maxanier** [comment]
E.g. `/vampirism-test vampireBook`
