### ISSUE TITLE
Fire Protection has the same texture as sunscreen (umbrella)

### ISSUE THREAD

**Issue by yavincl** [TeamLapen/Vampirism#957]
- Minecraft: 1.16.5
- Forge: 36.1.32
- Vampirism: 1.8.0

- ModPack: Enigmatica 6

![2021-06-27_20 35 26](https://user-images.githubusercontent.com/57966308/123562777-3aae7280-d787-11eb-8725-b94959b4bf74.png)

Used to be a flaming armor on 1.12.2

**Comment by Cheaterpaul** [comment]
Vampirism's `Fire Protection` effect is not the same as the vanilla effect `Fire Resistance`.

If you are a vampire and receive the Fire Resistance effect it will get replaced by the Fire Protection effect, because vampires should not be immune to fire.

But the icon may be misleading.
