### ISSUE TITLE
Option for vanilla loot table modification

### ISSUE THREAD

**Issue by yavincl** [TeamLapen/Vampirism#958]
Hello. I'm dev-ing a modpack and I would like vampirism not to modify the vanilla loot tables, but I'd like the vampirism 'dungeons' to continue spawning. This is because I need the vampire fangs and rings, belts, etc to not spawn in most chests. Would it be reasonable to implement such a config option?

[This is the relevant code I want to be switchable](https://github.com/TeamLapen/Vampirism/blob/320e6240f0c2921d94e137d29305c1f36602610f/src/main/java/de/teamlapen/vampirism/core/ModLootTables.java#L34-L38)

As for why I don't to this with KubeJS, it unfortunately doesn't support fine grained operations like this on non-block loot tables :/

**Comment by Cheaterpaul** [comment]
The referenced loot table generator just creates the json loottables in [inject loottables](https://github.com/TeamLapen/Vampirism/tree/1.16/src/generated/resources/data/vampirism/loot_tables/inject) which then will be merged into the vanilla loot tables on joining the world.

Which means that you can already modify them under `data/vampirism/loot_tables/inject/<*>.json`

**Comment by yavincl** [comment]
Thank you!
