### ISSUE TITLE
Hunter armor and weapons

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#96]
Add weapons and armor which can be crafted at the weapon table

**Comment by maxanier** [comment]
Maybe add a option to enhance an existent (vanilla or mod) armor e.g. with a protection from bites.
Could be implemented by NBT tags or maybe capabilities.

**Comment by tech-boy101** [comment]
i think it be cool if add both vampire and hunter armor that own vampire or hunter can make and give them perk for wear it like for hunter chest it make where vampire can see them use blood eye or what ever it cell and vampire hat made them immune to sun but have low hp for the hat

**Comment by tech-boy101** [comment]
if wann make it take some time where you can do this is to not make the builds but make like rpg level thing so more you feed the more exp you get and more exp you get the more level you get do understand what im say in
