### ISSUE TITLE
[Feature] Hunter cross

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#961]
**Hunter Cross Suggestion**
By Oreo365, Sniperfoxy34 and Йода, with thanks to Random2325 for input

**Part 1: Effects of the Cross**
There are 3 tiers of cross: Wooden, Iron and Golden. 
Wooden ones effect Vampires up to level 4 at “Maximum Strength”, and ones up to 8 at “Reduced Strength”, and has a range of 3 blocks and cooldown of 7 Seconds.

Iron ones effect Vampires up to level 14 at “Maximum Strength”, and ones up to Lord Level 2 at “Reduced Strength”, and has a range of 5 blocks and cooldown of 5 seconds.
Gold ones effect Vampires at up to Lord Level 4 at “Maximum Strength”, and any vampire at “Reduced Strength”, and has a range of 10 blocks and cooldown of 3 seconds.

A cross is used by holding down the right click button, like you would do to usually draw a bow. While it is “drawn” the cross takes effect, having a cooldown once you let go of the button before you can use it again. “Drawing” it also includes the speed penalty typically associated with drawing a bow.

At “Maximum Strength”, any vampires within the radius suffer Weakness and Slowness. Additionally they may not use any combat based abilities such as biting, and only ones such as bat form to allow them to escape. These abilities also consume double blood

At “Reduced Strength” any vampire within the radius suffers Weakness and Slowness. They may however cast combat based abilities although they will consume double blood. Non-combat abilities such as bat form cost the regular amount.

**Part 2: Crafting and Skills**
(All recipes and models will be included at the end of the document)

Wooden Crosses would be crafted on a regular crafting table and requite no prerequisite other then being a hunter to craft or use.

An Iron cross would require a skill found down the alchemical Skill tree for Hunters to both Craft and Use. This Skill would be unlocked around the same time as holy water crafting.

The Gold Cross would require a skill found near the end of the Alchemical Skill Tree for hunters to Craft and Use, due to its immense power.

**Part 3: Resisting the Cross**
There would be a new skill added to the vampire skill tree called “Athiest Vampire”. This would make the vampire’s level count as 2 higher for the purposes of the cross.

**Part 4: Recipes and Model Downloads**

WOODEN CROSS
![grafik](https://user-images.githubusercontent.com/3747729/124510583-aca83c80-ddc3-11eb-8845-caf7ba85c76a.png)

IRON CROSS

![grafik](https://user-images.githubusercontent.com/3747729/124510587-af0a9680-ddc3-11eb-8dd2-44e998de4bac.png)

GOLDEN CROSS
![grafik](https://user-images.githubusercontent.com/3747729/124510590-b0d45a00-ddc3-11eb-81c0-c838b1b82d4b.png)

**Part 5: Werewolf Addon**
Finally, I believe a specific new cross, the “Silver Cross” should be added to the Werewolf Addon. For the purposes of use against vampires, this would have the same stats as an Iron Cross. However, when it comes to use against Werewolves it is much better.

Crosses also have an effect on Werewolves, although it is far lesser then the effect on Vampires. While a werewolf is under the effect of a Cross, every second of rage instead counts as X seconds, where X depends on the type of cross (2 for Wooden, 3 for Iron and 5 for Gold), meaning their rage expires far faster. A Silver Cross however, Instantly takes the Werewolf out of Rage Mode.

When a Werewolf is taken out of Rage mode, it also applies to all Summoned Wolves.

SILVER CROSS (Requires same skill as Iron Cross to craft and use) 
![grafik](https://user-images.githubusercontent.com/3747729/124510598-b467e100-ddc3-11eb-8234-cbd0ffb5ec46.png)

**Part 5: Resisting the Cross**
Without giving vampires some ways to resist the cross, this suggestion would be unbalanced. Firstly, I believe vampires should have access to 2 new skills.

“Athiest Vampire”: The vampire counts as 2 levels higher for the purpose of resisting the effects of a cross.

“Cross-Resistant”: When in the Prescence of a Cross and suffering the effects of “Maximum Strength”, non-combat abilities only cost 1.5x blood instead of 2x blood. When in the Prescence of a Cross and suffering the effects of “Reduced  Strength”, combat abilities only cost 1.5x blood instead of 2x blood. 

Additionally, I believe that a new possible “Roll” on Vampire Artifacts should be for the vampire wearing it to count as one level higher for the purpose of resisting a cross.

**Comment by Cheaterpaul** [comment]
cross models

[cross_models_by_oreo.zip](https://github.com/TeamLapen/Vampirism/files/6984880/cross_models_by_oreo.zip)
[cross_models_by_random.zip](https://github.com/TeamLapen/Vampirism/files/6984881/cross_models_by_random.zip)

**Comment by Oreo365** [comment]
i personally think this is an amazing idea and should certainly be implemented

**Comment by maxanier** [comment]
I am not sure about the increased blood usage.
At the moment, actions do not really consume blood directly. So we can't 2x it.

**Comment by maxanier** [comment]
Maybe an alternative would be to just make the cross actually vampire repelling: Any vampire moving towards the cross is slowed down. Moving away from the cross is fine.
Not sure if that works, but might be cool
