### ISSUE TITLE
[Bug] Mod loading error has occurred

### ISSUE THREAD

**Issue by Mewcenary** [TeamLapen/Vampirism#962]
@maxanier 
## Versions

- Minecraft:  1.16.5
- Forge:  1.16.5
- Vampirism:  Vampirism-1.16.5-1.8.0-beta.3

- ModPack:  N/A

## Issue Description
the newly updated vampirism fails to load when launching the game.  I had to update it because I added your werewolf mod and the vampirismaddon,

## Reproduce Steps
Launching the game?

## Additional Information
[crash-2021-07-12_22.10.20-fml.txt](https://github.com/TeamLapen/Vampirism/files/6806629/crash-2021-07-12_22.10.20-fml.txt)

**Comment by maxanier** [comment]
Thank you for reporting.
This is caused by GodlyVampirism. I will upload a fixed version later tonight.

**Comment by Mewcenary** [comment]
> Thank you for reporting.
> This is caused by GodlyVampirism. I will upload a fixed version later tonight.

Thank you! I love your mods, I can't wait to see the werewolf mod in action!
