### ISSUE TITLE
[Bug] Cannot properly launch

### ISSUE THREAD

**Issue by Dark-Matter-X** [TeamLapen/Vampirism#963]
## Versions

- Minecraft: 1.16.5
- Forge: 36.1.62
- Vampirism: 1.8.0-beta.3

- ModPack: N/A

## Issue Description
Failed to launch because got an error on mod loading

## Reproduce Steps
Launch Minecraft

## Additional Information

[crash-2021-07-19_23.45.04-fml.txt](https://github.com/TeamLapen/Vampirism/files/6841886/crash-2021-07-19_23.45.04-fml.txt)

**Comment by Cheaterpaul** [comment]
This has been fixed with GodlyVampirism 1.0.2
