### ISSUE TITLE
[Modcompat] Cannot use coffins with Morpheus

### ISSUE THREAD

**Issue by sharkck** [TeamLapen/Vampirism#964]
## Versions

- Minecraft: 1.16.5
- Forge:  36.2.0
- Vampirism: 1.7.12
- Incompatible mod:  Morpheus
- Link to mod: https://www.curseforge.com/minecraft/mc-mods/morpheus?page=5

- ModPack: N/A

## Issue Description
When players sleep in a coffin, it turns it to morning

## Reproduce Steps
Sleep in a coffin

## Additional Information
Per Morpheus, they provide compatibility with the mod.  The issue is within Vampirism to take advantage of that compatibility.

**Comment by sharkck** [comment]
magic0whi
Posted Jun 10, 2020
Not compatible with Vampirism:
Coffin can skip the daytime, but with this mod, it just skip to morning.

Posted Jun 11, 2020
In reply to magic0whi:
 Vampirism just needs to add support, I provide ways for them to do this easily.

**Comment by maxanier** [comment]
https://github.com/Quetzi/Morpheus/issues/84

This is on Morpheus. There is a standardized way of supporting day sleep mods out of the box. But they refuse to do so and instead require every other mod to manually support morpheus. And they don't even explain their reasoning.

**Comment by maxanier** [comment]
Mods like quark for example use the Forge events properly and therefore support Vampirism's day sleep out of the box
