### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by wiktorzm** [TeamLapen/Vampirism#965]
## Versions

- Minecraft: 1.16.5
- Forge: 36.2.0
- Vampirism: 1.8.0-beta.3 (older versions didn't work for me too)

- ModPack: N/A

## Issue Description
So whenever i try to launch Minecraft with the mod (GodlyVamprism installed!!) I get an error message after initial forge libraries loading (shown in crash log)

## Reproduce Steps
Just launch Minecraft with the mod on

## Additional Information
The problem follows me through many fresh releases (the beta ones and normal, like 1.16.4)

[crash-2021-08-02_12.38.40-fml.txt](https://github.com/TeamLapen/Vampirism/files/6916338/crash-2021-08-02_12.38.40-fml.txt)
![crash_message_ingame](https://user-images.githubusercontent.com/88321073/127850280-01cac232-922f-4f08-923e-85c3e59bbbfa.png)

**Comment by maxanier** [comment]
Please remove the Optifine 1.17 jar from your mod folder and try again
`/preview_OptiFine_1.17.1_HD_U_G9_pre27.jar OptiFine`

**Comment by wiktorzm** [comment]
It works now, thanks.
