### ISSUE TITLE
[Bug] Crash when opening hunter research table

### ISSUE THREAD

**Issue by HacoKavanah** [TeamLapen/Vampirism#966]
## Versions

- Minecraft: 1.16.5
- Forge: 36.2.2
- Vampirism: 1.8.0-beta.4

- ModPack: N/A

## Issue Description
The game crashes whenever I open the hunter research table.

## Reproduce Steps
I played the game like normal and when I got to hunter level 4 this crash started to always appear whenever I opened the table.

## Additional Information
[Crash.txt](https://github.com/TeamLapen/Vampirism/files/6933882/Crash.txt)

**Comment by maxanier** [comment]
Thank you for reporting. Will be fixed with the next beta/release, maybe this weekend.
