### ISSUE TITLE
1.17 todos

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Vampirism#967]
List of things that may have been broken with the 1.17 code update.
Manually verify that these things still work:
- [x] AlchemicalCauldron burn rendering
- [x] AlchemicalCauldron functionality
- [x] Coffin sound
- [x] Multibossbar
- [x] Garlic beacon rendering with finder
- [x] Pedestal item rendering
- [x] Totem beam
- [x] Converted creatures (rendering)
- [x] Garlic diffusor strings
- [x] Blood vision
- [x] Hunter minion hat configuration
- [x] Vampire night vision 
- [x] Coffin item rendering
- [x] RecipeBook weapon table recipe placement
- [x] All GUI rendering
- [x] Hunter Weapon Table missing lava rendering
- [x] Blood container rendering
- [x] Remove mixin dependency and check if "remap = false" is still required
- [x] Altar infusion voxelshape
- [x] Vampire trees (also separate saplings)
- [x] Faction raid boss bar (color texture does not work)
- [x] Hunter tent generation
- [x] entity rendering (advanced hunter axe, advanced vampire leg)

Cherry pick:
- [x] d8e6394b
- [x] 79945a96
- [x] 270214cb
- [x] 47b459bc
- [x] 4db12f6a
- [x] 6c6d8f2d
- [x] 2565320c
- [x] 29e4bc16
- [x] 29b6df3d
- [x] 44c57e0a
- [x] ac6c4d25
- [x] 5761a9e5
- [x] cd644eb5
- [x] 817cd8d0
- [x] 1882fd0e
- [x] c3cc36a1
- [x] f08b23cd
- [x] acb9f118
- [x] 3b68badc
- [x] 012e6596
- [x] b6118f7b
- [x] e589400f
- [x] c465f01d
- [x] 7d7abf28
- [x] 390f20d2
- [x] 7fdd62e0
- [x] d66687a8
- [x] 4915a224
- [x] 0a2cc341
- [x] 107b5a6a
- [x] 4f249336
- [x] 6e265d94
- [x] fe0f459b
- [x] 4f00f3a9

**Comment by maxanier** [comment]
@Cheaterpaul can you have a look at the three last points please :=)

**Comment by Cheaterpaul** [comment]
Gui rendering:
- [x] Weapon Table
- [x] Alchemical Cauldron
- [x] Blood Grinder
- [ ] Garlic Diffuser
- [x] Hunter table
- [x] Potion Table
- [ ] ChurchAltar (ChurchAltarBlock#77 not on render thread?)
