### ISSUE TITLE
[Feature Request] Separate saplings for Vampire and Bloody Spruce trees

### ISSUE THREAD

**Issue by Brun333rp** [TeamLapen/Vampirism#971]
Rather than a single sapling that grows either into Bloody Spruces or Vampire Spruces depending of the soil it was planted, there should be saplings for both types of trees. The reason is: the sapling that grows into both trees is named after only one of the resulting trees, wich is the Bloody Spruce; and the Vampire Spruces can only be grown when planted in regular dirt, even though they generate in Vampire Forests, wich have a ground mainly made of Cursed Soil, so it doesn't makes sense for them to generate there. Therefore, the addition of separate saplings for both trees would fix this inconsistency.

**Comment by maxanier** [comment]
Should be fixed for 1.17+. 
For 1.16 Vampirism 1.9 will change the trees anyways
