### ISSUE TITLE
[Modcompat] Flying incompatibility with Lost Trinkets

### ISSUE THREAD

**Issue by 4s-ary** [TeamLapen/Vampirism#972]
## Versions

- Minecraft: 1.16.5
- Forge:  36.2.0
- Vampirism: 1.8.0-beta.5
- Incompatible mod: Lost Trinkets
- Link to mod: https://www.curseforge.com/minecraft/mc-mods/lost-trinkets

- ModPack: N/A

## Issue Description
 I can't fly when I'm in bat mode 'cause Lost Trinkets adds ability to creative fly

**Comment by maxanier** [comment]
Not at all or just when you have a "flying trinket" ?
