### ISSUE TITLE
Help.

### ISSUE THREAD

**Issue by Frizzledizzley** [TeamLapen/Vampirism#973]
## Versions

- Minecraft: 1.16.5
- Forge: 36.2.0
- Vampirism: 1.16.5 1.80

- ModPack: N/A

## Issue Description
 26.08 21:08:07 [Server] Server thread/WARN [de.te.va.VampirismMod/]: LootTables -------------------------------
26.08 21:08:07 [Server] Server thread/WARN [de.te.va.VampirismMod/]: LootTables Failed to inject all loottables
26.08 21:08:07 [Server] Server thread/WARN [de.te.va.VampirismMod/]: LootTables -------------------------------

**Comment by maxanier** [comment]
This is not a big issue as long as you can find some Vampirism loot in some loot chests
