### ISSUE TITLE
Incompatible with Just Enough Resources

### ISSUE THREAD

**Issue by Rightfuldeathray** [TeamLapen/Vampirism#975]
Version 1.8.0 release for Minecraft 1.16.5, released today on Aug 29 appears to be incompatible with JEI plugin: JER, Causes game to crash on world load, exit code -1. I was able to create this error with only Vampirism, JEI, and JER running on Forge 36.2.0-Forge 36.2.2, I am using the latest updates for all mods as of this post.

**Comment by Cheaterpaul** [comment]
could you provide the crash report or if not available the latest log files

**Comment by optmisticnihilist** [comment]
I'm running into similar issue, with same forge and mods include jei and jer.

Modpack does launch world with Vampirism-1.16.5-1.8.0-beta.5.jar

[crash-2021-08-29_13.01.35-client.txt](https://github.com/TeamLapen/Vampirism/files/7072990/crash-2021-08-29_13.01.35-client.txt)

**Comment by Rightfuldeathray** [comment]
Here you go, looks pretty similar to optmistic's

> could you provide the crash report or if not available the latest log files

[crash-2021-08-29_12.21.15-client.txt](https://github.com/TeamLapen/Vampirism/files/7073011/crash-2021-08-29_12.21.15-client.txt)

**Comment by Rightfuldeathray** [comment]
And if this info is at all helpful there is no issue with running the latest update with JEI, JEI integrations or any other JEI addon, my 165 mod build works great if I disable JER, or Vampirism, or roll Vampirism back 1 update.

**Comment by Shines113** [comment]
I was unable to gather my crash log due to time, but I'm having a similar error by putting this into my enigmatica 6 file. The beta version of vampirism works just fine, but the latest one crashed with JER.

**Comment by Diversion98** [comment]
same thing happening to me.
1.8.0 Beta 5 works just fine

**Comment by maxanier** [comment]
Damn it

**Comment by maxanier** [comment]
Thank you for reporting. Fixed version 1.8.1 is available now
