### ISSUE TITLE
Vampire hunters spawn on slabs

### ISSUE THREAD

**Issue by Dragochu** [TeamLapen/Vampirism#976]
## Versions
 

- Minecraft: 1.16.5
- Forge: 36.2.0
- Vampirism: Vampirism.co 1.8

- ModPack: N/A

## Issue Description
I am trying to make a vampire hunter farm, but anything i do doesn't help, vampire hunters keep spawning on top of slabs, where normal mobs never spawn on them.

## Reproduce Steps
All you have to do to reproduce it is to find a world placed tent or just place a tent that spawns hunters, and then cover the whole floor where they spawn with slabs.

## Additional Information
None.

**Comment by maxanier** [comment]
The tents work similar to spawner blocks which also disregard slabs as far as I know, but I will confirm that

**Comment by Cheaterpaul** [comment]
fixed in the next version

**Comment by Dragochu** [comment]
Thank you, that means my vampire hunter farm will finally work. :)

2021-09-10, pn, 15:01 Paul Becker ***@***.***> rašė:
