### ISSUE TITLE
[Bug] Using the "Phoenix's Blessing" From Astral sorcery after pressing "Give Up" Glitches player

### ISSUE THREAD

**Issue by 2468cool** [TeamLapen/Vampirism#977]
## Versions

- Minecraft: 1.16.5
- Forge: 36.2.0
- Vampirism: 1.8.0
- Astral Sorcery: 1.13.12

- ModPack: N/A

## Issue Description
When pressing the "Give Up" button as a vampire with the phoenix's blessing perk from Astral Sorcery, the player stays laying on the ground and is unable to move. Expected to receive phoenix's blessing's effects normally without even having the menu open like how a totem of undying works. Phoenix's Blessing perk acts like a totem of undying, the bug does not occur when using a regular totem or when dying in neonatal phase.

## Reproduce Steps
- Become a vampire
- Unlock exploration in astral tome by placing a collector crystal by a crafting table and linking the crystal to the table with a linking tool.
- Unlock attunement section in Astral Tome by upgrading luminous crafting table
- Place attunement altar and right-click with resonating wand until the structure is auto-made if in creative
- Set time to night (midnight might be best but idk)
- Grab a constellation paper in the creative tab for it and right-click with the paper. Press Esc to exit the constellation view. (Grab Armara since it is closest to the perk)
- Use looking glass in the night sky until you find stars that look like the constellation you picked.
- Hold shift to trace the constellation
- Once constellation is unlocked, grab astral relays and hold the constellation paper at the attunement altar
- Place astral relays in areas emitting light
- Once the altar activates, step into it and wait for animation to finish.
- Open up astral tome and select the "perks" section (Once perk tree is unlocked you can do "/astralsorcery exp <player name> <exp amount>" to quickly level up to grab the perk.)
- Unlock the "Phoenix's Blessing" perk from Astral Sorcery
- Die as a vampire
- Press "Give up"
- Be unable to get up or move fast.
- /kill to end the glitch by dying

Sorry for the long steps list, I just want to make sure this is easy for you to replicate.

![2021-08-31_19 07 12](https://user-images.githubusercontent.com/83475290/131587293-68b287f1-f107-4f90-9c4a-0f49ac792e2d.png)
![2021-08-31_19 08 25](https://user-images.githubusercontent.com/83475290/131587296-0fb274af-d305-4d0e-b10b-1f54ebdd96d5.png)
![2021-08-31_19 08 31](https://user-images.githubusercontent.com/83475290/131587297-2663ff0e-2289-49ef-bb95-75a2a621d92a.png)
![2021-08-31_19 08 33](https://user-images.githubusercontent.com/83475290/131587299-53a399a5-6745-462b-9320-ba10ea040907.png)

**Comment by 2468cool** [comment]
This glitch also occurs when using a ring of last chance from nature's aura mod

**Comment by maxanier** [comment]
Thank you for providing such a detailed list of steps to reproduce.
Fixed in the next version
