### ISSUE TITLE
[Feature] Zombie Summoning for Vampires Skill

### ISSUE THREAD

**Issue by Traincrafter111** [TeamLapen/Vampirism#984]
## What would you like to have changed or added to Vampirism
A new skill for the vampire class that let the Vampire summon a Zombie/Zombie horde to fight for them, working similar to the summon bat skill

## Does this make the mod experience more balanced?
Not really, but neither more OP

**Comment by MarioSMB** [comment]
If I may add my personal opinion here, necromancy is a little outside the realm of vampires and their powers, and may be better suited to a separate class or mod. It's a cool idea though!

**Comment by Cheaterpaul** [comment]
I agree with Mario, summoning Zombies has nothing to do with Vampires. If you want help to defend yourself, become vampire lord and command minions to protect you.
