### ISSUE TITLE
New texture for bottles

### ISSUE THREAD

**Issue by Samlegamer** [TeamLapen/Vampirism#987]
Hi!
For a future project in 1.12 I made the bottle textures which makes them a bit more Minecraft 1.14+.
And I thought it would be interesting to propose them to you to put them in the real mod.

Here is a small preview:

![2021-09-30_21 12 10](https://user-images.githubusercontent.com/83614614/135581055-f9e8e6ab-6805-4709-9c23-ca37ca57c331.png)

Link : https://www.mediafire.com/file/uelufha2mxacuv8/vampirism_texture_bottle_mc1.14%252B.zip/file

**Comment by maxanier** [comment]
Hello, thank you for your contribution. 
I am not really sure what you changed about the textures. From the preview they look exactly as the current ones .

**Comment by Samlegamer** [comment]
Yes it looks like the current one but with some differences... the outline is inspired by the texture of the bottles of minecraft 1.14 and the following versions.

![bottle](https://user-images.githubusercontent.com/83614614/138598097-6ebc8299-1872-4f45-8997-1d4369aae764.PNG)

Here is a small example:

Normal

![vampirism blood bottle 9 ancienne](https://user-images.githubusercontent.com/83614614/138598106-351febe1-974e-4f70-91e3-c6244c47e496.PNG)

My texture redone following the model 1.14 and more

![vampirism blood bottle 9 refaite](https://user-images.githubusercontent.com/83614614/138598118-14b802aa-fe84-4bc2-92f4-f11675c8acb4.PNG)

**Comment by maxanier** [comment]
Oh, I see, that makes sense. Thank you for your contribution
