### ISSUE TITLE
While using vampirism mod, if ai died I can't respawn[Bug]

### ISSUE THREAD

**Issue by Minaxs** [TeamLapen/Vampirism#990]
## Versions

- Minecraft: 1.17.1
- Forge: 1.17.1 forge 37.0.70
- Vampirism: 1.17.1-1.8.3-alpha+2011003-1844

- ModPack: N/A

## Additional Information
When you remove the vampirism mod, you can have other mods and there is no problem if you die, you can respawn normaly

**Comment by maxanier** [comment]
Update to the latest alpha please
https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire/files/3485817
