### ISSUE TITLE
[Feature] Option to prevent sprinting in bat mode

### ISSUE THREAD

**Issue by MarioSMB** [TeamLapen/Vampirism#992]
## What would you like to have changed or added to Vampirism
Bat mode with some adjustments can be quite fun and balanced, an option to prevent sprinting would go a long way in making the flight less overpowered.

## Does this make the mod experience more balanced?
Yes.

## Can you provide additional resources (etc. textures or models)
N.A.

**Comment by maxanier** [comment]
This would require some ugly code I think.
What do you think about an option to modify the base speed in bat mode. E.g. to a level where the sprint speed is as fast as the normal non-sprinting flight

**Comment by MarioSMB** [comment]
The ability to change how fast the bat can move would help immensely, and would be a fine alternative to hacking away the sprint option.
