### ISSUE TITLE
[Feature] Fall to the ground instead of turning back when bat mode wears off

### ISSUE THREAD

**Issue by MarioSMB** [TeamLapen/Vampirism#993]
## What would you like to have changed or added to Vampirism
This may be a nice optional alternative or additive to the blue screen effect; when the bat flight timer is reached they just glide to the ground rather than turning back into human (vampire).

## Does this make the mod experience more balanced?
Yes.

## Can you provide additional resources (etc. textures or models)
N.A.

**Comment by maxanier** [comment]
I think it makes sense to turn back once the timer runs out. The vampire just does not have the energy to stay a bat any longer. Flying is less of a problem.

Also implementing this is too much work for an optional feature only

**Comment by MarioSMB** [comment]
Understandable, I've just been looking for ways to make the flight a bit more balanced - the current configuration option ends up dropping players out of the sky, and with a duration setting of 10 the blue effect is prominent right from the beginning, leaving no true indicator of when the player will be dropped.
